== Table of Contents of Appendix 1

*Decisions relating to the establishment of the SI page*

9^th^ CGPM, 1948:: decision to establish the SI

10^th^ CGPM, 1954:: decision on the first six base units

CIPM 1956:: decision to adopt the name "Système International d'Unités"

[align=left]
11^th^ CGPM, 1960:: confirms the name and the abbreviation "SI", +
names prefixes from tera to pico, +
establishes the supplementary units rad and sr, +
lists some derived units

CIPM, 1969:: declarations concerning base, supplementary, derived and coherent units, and the use of prefixes

CIPM, 2001:: "SI units" and "units of the SI"

23^rd^ CGPM, 2007:: possible redefinition of certain base units of the International System of Units, the SI

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

25^th^ CGPM, 2014:: future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)


*Decisions relating to the base units of the SI*

*Length*

1^st^ CGPM, 1889:: sanction of the prototype metre

7^th^ CGPM, 1927:: definition and use of the prototype metre

10^th^ CGPM, 1954:: metre adopted as a base unit

11^th^ CGPM, 1960:: redefinition of the metre in terms of krypton 86 radiation

15^th^ CGPM, 1975:: recommends value for the speed of light

[align=left]
17^th^ CGPM, 1983:: redefinition of the metre using the speed of light, +
realization of the definition of the metre

CIPM, 2002:: specifies the rules for the practical realization of the definition of the metre

CIPM, 2003:: revision of the list of recommended radiations

CIPM, 2005:: revision of the list of recommended radiations

CIPM, 2007:: revision of the list of recommended radiations

23^th^ CGPM, 2007:: revision of the _mise en pratique_ of the definition of the metre and development of new optical frequency standards

CIPM, 2009:: updates to the list of standard frequencies

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

24^th^ CGPM, 2011:: revision of the _mise en pratique_ of the definition of the metre and development of new optical frequency standards

CIPM, 2013:: updates to the list of standard frequencies

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)

*Mass*

1^st^ CGPM, 1889:: sanction of the prototype kilogram

3^rd^ CGPM, 1901:: declaration on distinguishing mass and weight, and on the conventional value of stem:[g_n]

10^th^ CGPM, 1954:: kilogram adopted as a base unit

CIPM, 1967:: declaration on applying prefixes to the gram

21^st^ CGPM, 1999:: future redefinition of the kilogram

23^rd^ CGPM, 2007:: possible redefinition of certain base units of the International System of Units (SI)

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

25^th^ CGPM, 2014:: future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)

*Time*

10^th^ CGPM, 1954:: second adopted as a base unit

CIPM, 1956:: definition of the second as a fraction of the tropical year 1900

11^th^ CGPM, 1960:: ratifies the CIPM 1956 definition of the second

CIPM, 1964:: declares the caesium 133 hyperfine transition to be the recommended standard

12^th^ CGPM, 1964:: empowers CIPM to investigate atomic and molecular frequency standards

13^th^ CGPM, 1967/68:: defines the second in terms of the caesium transition

CCDS, 1970:: defines International Atomic Time, TAI

14^th^ CGPM, 1971:: requests the CIPM to define and establish International Atomic Time, TAI

15^th^ CGPM, 1975:: endorses the use of Coordinated Universal Time, UTC

CIPM, 2006:: secondary representations of the second

23^rd^ CGPM, 2007:: on the revision of the _mise en pratique_ of the definition of the metre and the development of new optical frequency standards

CIPM, 2009:: updates to the list of standard frequencies

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

24^th^ CGPM, 2011:: revision of the _mise en pratique_ of the metre and the development of new optical frequency standards

CIPM, 2013:: updates to the list of standard frequencies

CIPM, 2015:: updates to the list of standard frequencies

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)


*Electrical units*

CIPM, 1946:: definitions of coherent electrical units in the metre-kilogram-second (MKS) system of units (to enter into force on 1 January 1948)

10^th^ CGPM, 1954:: ampere adopted as a base unit

14^th^ CGPM, 1971:: adopts the name siemens, symbol stem:[S], for electrical conductance

18^th^ CGPM, 1987:: forthcoming adjustment to the representations of the volt and of the ohm

CIPM, 1988:: conventional value of the Josephson constant defined (to enter into force on 1 January 1990)

CIPM, 1988:: conventional value of the von Klitzing constant defined (to enter into force on 1 January 1990)

23^rd^ CGPM, 2007:: possible redefinition of certain base units of the International System of Units (SI)

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

25^th^ CGPM, 2014:: future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)


*Thermodynamic temperature*

9^th^ CGPM, 1948:: adopts the triple point of water as the thermodynamic reference point, adopts the zero of Celsius temperature to be 0.01 degree below the triple point

CIPM, 1948:: adopts the name degree Celsius for the Celsius temperature scale

10^th^ CGPM, 1954:: defines thermodynamic temperature such that the triple point of water is stem:[273.16] degrees Kelvin exactly, defines standard atmosphere

10^th^ CGPM, 1954:: degree Kelvin adopted as a base unit

13^th^ CGPM, 1967/68:: decides formal definition of the kelvin, symbol stem:[K]

CIPM, 1989:: the International Temperature Scale of 1990, ITS-90

CIPM, 2005:: note added to the definition of the kelvin concerning the isotopic composition of water

23^rd^ CGPM, 2007:: clarification of the definition of the kelvin, unit of thermodynamic temperature

23^rd^ CGPM, 2007:: possible redefinition of certain base units of the International System of Units (SI)

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

25^th^ CGPM, 2014:: future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)

*Amount of substance*

14^th^ CGPM, 1971:: definition of the mole, symbol stem:[mol], as a seventh base unit, and rules for its use

21^st^ CGPM, 1999:: adopts the special name katal, kat

23^rd^ CGPM, 2007:: on the possible redefinition of certain base units of the International System of Units (SI)

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

25^th^ CGPM, 2014:: future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)

*Luminous intensity*

CIPM, 1946:: definition of photometric units, new candle and new lumen (to enter into force on 1 January 1948)

10^th^ CGPM, 1954:: candela adopted as a base unit

13^th^ CGPM, 1967/68:: defines the candela, symbol stem:[cd], in terms of a black body radiator

16^th^ CGPM, 1979:: redefines the candela in terms of monochromatic radiation

24^th^ CGPM, 2011:: possible future revision of the International System of Units, the SI

26^th^ CGPM, 2018:: revision of the International System of Units, the SI (to enter into force on 20 May 2019)


*Decisions relating to SI derived and supplementary units*

*SI derived units*

12^th^ CGPM, 1964:: accepts the continued use of the curie as a non-SI unit

13^th^ CGPM, 1967/68:: lists some examples of derived units

15^th^ CGPM, 1975:: adopts the special names becquerel, Bq, and gray, Gy

16^th^ CGPM, 1979:: adopts the special name sievert, Sv

CIPM, 1984:: decides to clarify the relationship between absorbed dose (SI unit gray) and dose equivalent (SI unit sievert)

CIPM, 2002:: modifies the relationship between absorbed dose and dose equivalent

*Supplementary units*

CIPM, 1980:: decides to interpret supplementary units as dimensionless derived units

20^th^ CGPM, 1995:: decides to abrogate the class of supplementary units, and confirms the CIPM interpretation that they are dimensionless derived units


*Decisions concerning terminology and the acceptance of units for use with the SI page*

*SI prefixes*

12^th^ CGPM, 1964:: decides to add femto and atto to the list of prefixes

15^th^ CGPM, 1975:: decides to add peta and exa to the list of prefixes

19^th^ CGPM, 1991:: decides to add zetta, zepto, yotta, and yocto to the list of prefixes

*Unit symbols and numbers*

9^th^ CGPM, 1948:: decides rules for printing unit symbols

*Unit names*

13^th^ CGPM, 1967/68:: abrogates the use of the micron and new candle as units accepted for use with the SI

*The decimal marker*

22^nd^ CGPM, 2003:: decides to allow the use of the point or the comma on the line as the decimal marker

*Units accepted for use with the SI: an example, the litre*

3^rd^ CGPM, 1901:: defines the litre as the volume of 1 kg of water

11^th^ CGPM, 1960:: requests the CIPM to report on the difference between the litre and the cubic decimetre

CIPM, 1961:: recommends that volume be expressed in SI units and not in litres

12^th^ CGPM, 1964:: abrogates the former definition of the litre, recommends that litre may be used as a special name for the cubic decimetre

16^th^ CGPM, 1979:: decides, as an exception, to allow both stem:[l] and stem:[L] as symbols for the litre