
<<<

[type=toc]
== Table of Contents of Appendix 1

=== Decisions relating to the establishment of the SI (((establishment of the SI)))(((International System of Units (SI))))

* <<cgpm9th1948r6,9th CGPM, 1948:pass:[<tab/>]decision to establish the SI>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]decision on the first six base units(((base unit(s))))>>

* <<cipm1956r3,CIPM, 1956:pass:[<tab/>]decision to adopt the name "Système International d'Unités">>

* <<cgpm11th1960r12,11th CGPM, 1960:pass:[<tab/>]confirms the name and the abbreviation "SI", names prefixes from tera to pico, establishes the supplementary units stem:["unitsml(rad)"] and stem:["unitsml(sr)"], lists some derived units>>

* <<cipm1969r1,CIPM, 1969:pass:[<tab/>]declarations concerning base, supplementary, derived and coherent units, and the use of prefixes>>

* <<cipm-si-units,CIPM, 2001:pass:[<tab/>]"SI units" and "units of the SI">>

* <<cgpm23rd2007r12,23rd CGPM, 2007:pass:[<tab/>]possible redefinition of certain base units(((base unit(s)))) of the International System of Units, the SI>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm25th2014r1,25th CGPM, 2014:pass:[<tab/>]future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>


=== Decisions relating to the base units(((base unit(s)))) of the SI

==== Length (((length)))

* <<cgpm1st1889sanction,1st CGPM, 1889:pass:[<tab/>]sanction of the prototype metre>>

* <<cgpm7th1927metre,7th CGPM, 1927:pass:[<tab/>]definition and use of the prototype metre>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]metre adopted as a base unit(((base unit(s))))>>

* <<cgpm11th1960r6,11th CGPM, 1960:pass:[<tab/>]redefinition of the metre in terms of krypton 86 radiation>>

* <<cgpm15th1975r2,15th CGPM, 1975:pass:[<tab/>]recommends value for the speed of light>>

* <<cgpm17th1983r1,17th CGPM, 1983:pass:[<tab/>]redefinition of the metre using the speed of light, realization of the definition of the metre>>

* <<cipm2002r1,CIPM, 2002:pass:[<tab/>]specifies the rules for the practical realization of the definition of the metre>>

* <<cipm2003r1,CIPM, 2003:pass:[<tab/>]revision of the list of recommended radiations>>

* <<cipm2005r3,CIPM, 2005:pass:[<tab/>]revision of the list of recommended radiations>>

* <<cipm2007r1,CIPM, 2007:pass:[<tab/>]revision of the list of recommended radiations>>

* <<cgpm23rd2007r9,23rd CGPM, 2007:pass:[<tab/>]revision of the _mise en pratique_ of the definition of the metre and development of new optical frequency standards>>

* <<cipm2009r2,CIPM, 2009:pass:[<tab/>]updates to the list of standard frequencies>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm24th2011r8,24th CGPM, 2011:pass:[<tab/>]revision of the _mise en pratique_ of the definition of the metre and development of new optical frequency standards>>

* <<cipm2013r1,CIPM, 2013:pass:[<tab/>]updates to the list of standard frequencies>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>

==== Mass (((mass)))

* <<cgpm1st1889sanction,1st CGPM, 1889:pass:[<tab/>]sanction of the prototype kilogram>>

* <<cgpm3rd1901mass,3rd CGPM, 1901:pass:[<tab/>]declaration on distinguishing mass and weight, and on the conventional value of stem:[g_{"n"}]>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]kilogram adopted as a base unit(((base unit(s))))>>

* <<cipm1967r2,CIPM, 1967:pass:[<tab/>]declaration on applying prefixes to the gram>>

* <<cgpm21st1999r7,21st CGPM, 1999:pass:[<tab/>]future redefinition of the kilogram>>

* <<cgpm23rd2007r12,23rd CGPM, 2007:pass:[<tab/>]possible redefinition of certain base units(((base unit(s)))) of the International System of Units (SI)>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm25th2014r1,25th CGPM, 2014:pass:[<tab/>]future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>

==== Time (((second (stem:["unitsml(s)"]))))(((time (duration))))

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]second adopted as a base unit(((base unit(s))))>>

* <<cipm1956r1,CIPM, 1956:pass:[<tab/>]definition of the second as a fraction of the tropical year 1900>>

* <<cgpm11th1960r9,11th CGPM, 1960:pass:[<tab/>]ratifies the CIPM 1956 definition of the second>>

* <<cipm1964freq,CIPM, 1964:pass:[<tab/>]declares the caesium 133 hyperfine transition to be the recommended standard>>

* <<cgpm12th1964r5,12th CGPM, 1964:pass:[<tab/>]empowers CIPM to investigate atomic and molecular frequency standards>>

* <<cgpm13th1967r1,13th CGPM, 1967/68:pass:[<tab/>]defines the second in terms of the caesium transition>>

* <<ccds1970tai,CCDS, 1970:pass:[<tab/>]defines International Atomic Time, TAI>>

* <<cgpm14th1971r1,14th CGPM, 1971:pass:[<tab/>]requests the CIPM to define and establish International Atomic Time, TAI>>

* <<cgpm15th1975r5,15th CGPM, 1975:pass:[<tab/>]endorses the use of Coordinated Universal Time, UTC>>

* <<cipm2006r1,CIPM, 2006:pass:[<tab/>]secondary representations of the second>>

* <<cgpm23rd2007r9,23rd CGPM, 2007:pass:[<tab/>]on the revision of the _mise en pratique_ of the definition of the metre and the development of new optical frequency standards>>

* <<cipm2009r2,CIPM, 2009:pass:[<tab/>]updates to the list of standard frequencies>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm24th2011r8,24th CGPM, 2011:pass:[<tab/>]revision of the _mise en pratique_ of the metre and the development of new optical frequency standards>>

* <<cipm2013r1,CIPM, 2013:pass:[<tab/>]updates to the list of standard frequencies>>

* <<cipm2015r2,CIPM, 2015:pass:[<tab/>]updates to the list of standard frequencies>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>


==== Electrical units (((electrical units)))

* <<cipm1946r2,CIPM, 1946:pass:[<tab/>]definitions of coherent electrical units in the metre-kilogram-second (MKS) system of units (to enter into force on 1 January 1948)>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]ampere(((ampere (stem:["unitsml(A)"])))) adopted as a base unit(((base unit(s))))>>

* <<cgpm14th1971siemens,14th CGPM, 1971:pass:[<tab/>]adopts the name siemens, symbol stem:["unitsml(S)"], for electrical conductance>>

* <<cgpm18th1987r6,18th CGPM, 1987:pass:[<tab/>]forthcoming adjustment to the representations of the volt and of the ohm>>

* <<cipm1988r1,CIPM, 1988:pass:[<tab/>]conventional value of the Josephson constant defined (to enter into force on 1 January 1990)>>

* <<cipm1988r2,CIPM, 1988:pass:[<tab/>]conventional value of the von Klitzing constant defined (to enter into force on 1 January 1990)>>

* <<cgpm23rd2007r12,23rd CGPM, 2007:pass:[<tab/>]possible redefinition of certain base units(((base unit(s)))) of the International System of Units (SI)>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm25th2014r1,25th CGPM, 2014:pass:[<tab/>]future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>


==== Thermodynamic temperature (((kelvin (stem:["unitsml(K)"]))))(((triple point of water)))

* <<cgpm9th1948r3,9th CGPM, 1948:pass:[<tab/>]adopts the triple point of water as the thermodynamic reference point, adopts the zero of ((Celsius temperature)) to be 0.01 degree below the triple point>>

* <<cipm1948,CIPM, 1948:pass:[<tab/>]adopts the name degree Celsius for the Celsius temperature scale>>

* <<cgpm10th1954r3,10th CGPM, 1954:pass:[<tab/>]defines thermodynamic temperature such that the triple point of water is stem:[273.16] degrees Kelvin exactly, defines standard atmosphere>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]degree Kelvin adopted as a base unit(((base unit(s))))>>

* <<cgpm13th1967r3,13th CGPM, 1967/68:pass:[<tab/>]decides formal definition of the kelvin, symbol stem:["unitsml(K)"]>>

* <<cipm1989temp,CIPM, 1989:pass:[<tab/>]the International Temperature Scale of 1990, ITS-90>>

* <<cipm2005r2,CIPM, 2005:pass:[<tab/>]note added to the definition of the kelvin concerning the isotopic composition of water>>

* <<cgpm23rd2007r10,23rd CGPM, 2007:pass:[<tab/>]clarification of the definition of the kelvin, unit of thermodynamic temperature>>

* <<cgpm23rd2007r12,23rd CGPM, 2007:pass:[<tab/>]possible redefinition of certain base units(((base unit(s)))) of the International System of Units (SI)>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm25th2014r1,25th CGPM, 2014:pass:[<tab/>]future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>

==== Amount of substance

* <<cgpm14th1971r3,14th CGPM, 1971:pass:[<tab/>]definition of the mole, symbol stem:["unitsml(mol)"], as a seventh base unit(((base unit(s)))), and rules for its use>>

* <<cgpm21st1999r12,21st CGPM, 1999:pass:[<tab/>]adopts the special name katal, stem:["unitsml(kat)"]>>

* <<cgpm23rd2007r12,23rd CGPM, 2007:pass:[<tab/>]on the possible redefinition of certain base units(((base unit(s)))) of the International System of Units (SI)>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm25th2014r1,25th CGPM, 2014:pass:[<tab/>]future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>

==== Luminous intensity (((luminous intensity))) (((lumen (stem:["unitsml(lm)"]))))

* <<cipm1946photo,CIPM, 1946:pass:[<tab/>]definition of photometric units, new candle and new lumen (to enter into force on 1 January 1948)>>

* <<cgpm10th1954r6,10th CGPM, 1954:pass:[<tab/>]candela(((candela (stem:["unitsml(cd)"])))) adopted as a base unit(((base unit(s))))>>

* <<cgpm13th1967r5,13th CGPM, 1967/68:pass:[<tab/>]defines the candela(((candela (stem:["unitsml(cd)"])))), symbol stem:["unitsml(cd)"], in terms of a black body radiator>>

* <<cgpm16th1979r3,16th CGPM, 1979:pass:[<tab/>]redefines the candela(((candela (stem:["unitsml(cd)"])))) in terms of monochromatic radiation>>

* <<cgpm24th2011r1,24th CGPM, 2011:pass:[<tab/>]possible future revision of the International System of Units, the SI>>

* <<cgpm26th2018r1,26th CGPM, 2018:pass:[<tab/>]revision of the International System of Units, the SI (to enter into force on 20 May 2019)>>


=== Decisions relating to SI derived and supplementary units

==== SI derived units

* <<cgpm12th1964r7,12th CGPM, 1964:pass:[<tab/>]accepts the continued use of the curie as a non-SI unit>>

* <<cgpm13th1968r6,13th CGPM, 1967/68:pass:[<tab/>]lists some examples of derived units>>

* <<cgpm15th1975r8_9,15th CGPM, 1975:pass:[<tab/>]adopts the special names becquerel(((becquerel (stem:["unitsml(Bq)"])))), stem:["unitsml(Bq)"], and gray, stem:["unitsml(Gy)"]>>

* <<cgpm16th1979r5,16th CGPM, 1979:pass:[<tab/>]adopts the special name sievert, stem:["unitsml(Sv)"]>>

* <<cipm1984r1,CIPM, 1984:pass:[<tab/>]decides to clarify the relationship between ((absorbed dose)) (SI unit gray) and dose equivalent (SI unit sievert)>>

* <<cipm2002r2,CIPM, 2002:pass:[<tab/>]modifies the relationship between ((absorbed dose)) and dose equivalent>>

==== Supplementary units(((supplementary units)))

* <<cipm1980r1,CIPM, 1980:pass:[<tab/>]decides to interpret supplementary units as dimensionless derived units>>

* <<cgpm20th1995r8,20th CGPM, 1995:pass:[<tab/>]decides to abrogate the class of supplementary units, and confirms the CIPM interpretation that they are dimensionless derived units>>


=== Decisions concerning terminology and the acceptance of units for use with the SI

==== SI prefixes

* <<cgpm12th1964r8,12th CGPM, 1964:pass:[<tab/>]decides to add femto and atto to the list of prefixes>>

* <<cgpm15th1975r10,15th CGPM, 1975:pass:[<tab/>]decides to add peta and exa to the list of prefixes>>

* <<cgpm19th1991r4,19th CGPM, 1991:pass:[<tab/>]decides to add zetta, zepto, yotta, and yocto to the list of prefixes>>

==== Unit symbols and numbers

* <<cgpm9th1948r7,9th CGPM, 1948:pass:[<tab/>]decides rules for printing unit symbols>>

==== Unit names (((unit names)))

* <<cgpm13th1967r7,13th CGPM, 1967/68:pass:[<tab/>]abrogates the use of the micron and new candle as units accepted for use with the SI>>

==== The ((decimal marker))

* <<cgpm22nd2003r10,22nd CGPM, 2003:pass:[<tab/>]decides to allow the use of the point or the comma on the line as the ((decimal marker))>>

==== Units accepted for use with the SI: an example, the litre

* <<cgpm3rd1901litre,3rd CGPM, 1901:pass:[<tab/>]defines the litre as the volume of stem:[1 "unitsml(kg)"] of water>>

* <<cgpm11th1960r13,11th CGPM, 1960:pass:[<tab/>]requests the CIPM to report on the difference between the litre and the cubic decimetre>>

* <<cipm1961litre,CIPM, 1961:pass:[<tab/>]recommends that volume be expressed in SI units and not in litres>>

* <<cgpm12th1964r6,12th CGPM, 1964:pass:[<tab/>]abrogates the former definition of the litre, recommends that litre may be used as a special name for the cubic decimetre>>

* <<cgpm16th1979r6,16th CGPM, 1979:pass:[<tab/>]decides, as an exception, to allow both stem:["unitsml(l)"] and stem:["unitsml(L)"] as symbols for the litre>>


<<<
