== 3^rd^ CGPM, 1901

=== Declaration concerning the definition of the litre (CR, 38-39)

____
&#x200c;. . .

*The Conference declares*

. The unit of volume, for high accuracy determinations, is the volume occupied by a mass of 1 kilogram of pure water, at its maximum density and at standard atmospheric pressure: this volume is called "litre".

. . . .
____

NOTE: This definition was abrogated in 1964 by the <<cgpm12thr6,12^th^ CGPM (Resolution 6)>>.

===  Declaration on the unit of mass and on the definition of weight; conventional value of stem:[g_n] (CR, 70)

____
*Taking into account* the decision of the Comité International des Poids et Mesures of 15 October 1887, according to which the kilogram has been defined as unit of mass;

*Taking into account* the decision contained in the sanction of the prototypes of the Metric System, unanimously accepted by the Conférence Générale des Poids et Mesures on 26 September 1889;

*Considering* the necessity to put an end to the ambiguity which in current practice still exists on the meaning of the word _weight_, used sometimes for _mass_, sometimes for _mechanical force_;

*The Conference declares*

[align=left]
. The kilogram is the unit of mass; it is equal to the mass of the international prototype of the kilogram; footnote:[This definition was abrogated in 2018 by the <<cgpm26th2018r1,26^th^ CGPM (Resolution 1)>>.]
. The word "weight" denotes a quantity of the same nature as a "force": the weight of a body is the product of its mass and the acceleration due to gravity; in particular, the standard weight of a body is the product of its mass and the standard acceleration due to gravity;
. The value adopted in the International Service of Weights and Measures for the standard acceleration due to gravity is stem:[980.665 " cm/s"^2], value already stated in the laws of some countries. footnote:[This value of stem:[g_"n"] was the conventional reference for calculating the now obsolete unit kilogram force.]
____