[[cgpm9th1948]]
== 9th CGPM, 1948

[[cgpm9th1948r3]]
=== Triple point of water; thermodynamic scale with a single fixed point; unit of quantity of heat (joule) (CR, 55 and 63)index-range:joule_j[(((joule (J))))](((triple point of water)))

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>). (((kelvin (K))))

[[cgpm9th1948r3r3]]
==== Resolution 3
____

. With present-day techniques, the triple point of water is capable of providing a thermometric reference point with an accuracy higher than can be obtained from the melting point of ice. +
In consequence the Comité Consultatif de Thermométrie et Calorimétrie (CCTC) considers that the zero of the centesimal thermodynamic scale must be defined as the temperature 0.0100 degree below that of the triple point of water.

. The CCTC accepts the principle of an absolute thermodynamic scale with a single fundamental fixed point, at present provided by the triple point of pure water, the absolute temperature of which will be fixed at a later date. +
The introduction of this new scale does not affect in any way the use of the International Scale, which remains the recommended practical scale.

. The unit of quantity of heat is the joule.

NOTE: It is requested that the results of calorimetric experiments be as far as possible expressed in joules. If the experiments are made by comparison with the rise of temperature of water (and that, for some reason, it is not possible to avoid using the ((calorie))), the information necessary for conversion to joules must be provided. The CIPM, advised by the CCTC, should prepare a table giving, in joules per degree, the most accurate values that can be obtained from experiments on the specific heat of water. [[joule_j]]
____

A table, prepared in response to this request, was approved and published by the CIPM in 1950 (PV, *22*, 92).


[[cipm1948]]
=== Adoption of "degree Celsius" [CIPM, 1948 (PV, 21, 88) and 9th CGPM, 1948 (CR, 64)] (((degree Celsius (°C))))

From three names ("degree centigrade", "centesimal degree", "degree Celsius") proposed to denote the degree of temperature, the CIPM has chosen "degree Celsius" (PV, *21*, 88). (((degree Celsius (°C))))

This name is also adopted by the 9th CGPM (CR, 64).

[[cgpm9th1948r6]]
=== Proposal for establishing a practical system of units of measurement (CR, 64)

[[cgpm9th1948r6r6]]
==== Resolution 6
____

The Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the Comité International des Poids et Mesures (CIPM) has been requested by the International Union of Physics to adopt for international use a practical Système International d'Unités; that the International Union of Physics recommends the ((MKS system)) and one electric unit of the absolute practical system, but does not recommend that the ((CGS)) system be abandoned by physicists;
* that the CGPM has itself received from the French Government a similar request, accompanied by a draft to be used as basis of discussion for the establishment of a complete specification of units of measurement;

*instructs* the CIPM:

* to seek by an energetic, active, official enquiry the opinion of scientific, technical and educational circles of all countries (offering them, in fact, the French document as basis);
* to gather and study the answers;
* to make recommendations for a single practical system of units of measurement, suitable for adoption by all countries adhering to the ((Metre Convention)).
____


[[cgpm9th1948r7]]
=== Writing and printing of unit symbols and of numbers (CR, 70)(((digits in groups of three, grouping digits)))(((litre (L or l))))

NOTE: The CGPM abrogated certain decisions on units and terminology, in particular: micron, degree absolute, and the terms "degree", and "deg", 13th CGPM, 1967/68 (<<cgpm13th1967r7r7,Resolution 7>>) and (<<cgpm13th1967r3r3,Resolution 3>>), and the litre; 16th CGPM, 1979 (<<cgpm16th1979r6r6,Resolution 6>>).

[[cgpm9th1948r7r7]]
==== Resolution 7
____

*Principles*

Roman (upright) type, in general lower-case, is used for symbols of units; if, however, the symbols are derived from proper names, capital roman type is used. These symbols are not followed by a full stop.

In numbers, the comma (French practice) or the dot (British practice) is used only to separate the integral part of numbers from the decimal part. Numbers may be divided in groups of three in order to facilitate reading; neither dots nor commas are ever inserted in the spaces between groups.

[%unnumbered]
[cols="<,<,<,<"]
|===
| Unit | Symbol | Unit | Symbol

| &#x2022; metre | stem:["unitsml(m)"]| ampere(((ampere (A)))) | stem:[sf "unitsml(A)"]
| &#x2022; square metre | stem:["unitsml(m^2)"] | volt| stem:[sf "unitsml(V)"]
| &#x2022; cubic metre | stem:["unitsml(m^2)"] | watt | stem:[sf "unitsml(W)"] (((watt (W))))
| &#x2022; micron | stem:[mu] | ohm | stem:[sf Omega] (((ohm (stem:[Omega]))))
| &#x2022; litre (((litre (L or l)))) | stem:["unitsml(l)"] | coulomb(((coulomb \(C)))) | stem:[sf "unitsml(C)"]
| &#x2022; gram | stem:["unitsml(g)"] | farad | stem:[sf "unitsml(F)"] (((farad (F)))) (((gram)))
| &#x2022; tonne | stem:["unitsml(t)"] | henry | stem:[sf "unitsml(H)"] (((henry (H)))) (((tonne)))
| second | stem:["unitsml(s)"] | hertz | stem:[sf "unitsml(Hz)"] (((hertz (Hz))))(((second (s))))
| ((erg)) | stem:["unitsml(erg)"] | poise | stem:[sf "unitsml(P)"] (((poise (P))))
| dyne (((dyne (dyn)))) | stem:["unitsml(dyn)"] | newton | stem:[sf "unitsml(N)"] (((newton (N))))
| degree Celsius(((degree Celsius (°C)))) | stem:["unitsml(°C)"] a| &#x2022; candela(((candela (cd)))) +
(new candela) | stem:[sf "unitsml(cd)"]
| &#x2022; degree absolute | stem:["unitsml(°K)"] | lux | stem:[sf "unitsml(lx)"] (((lux (lx))))
| ((calorie)) | stem:["unitsml(cal)"] | lumen (((lumen (lm)))) | stem:[sf "unitsml(lm)"]
| ((bar)) | stem:["unitsml(bar)"] | stilb | stem:[sf "unitsml(sb)"] (((stilb (sb))))
| hour | stem:["unitsml(h)"] | | (((hour (h))))
|===

NOTE: The symbols whose unit names are preceded by dots are those which had already been adopted by a decision of the CIPM.

NOTE: The symbol for the stere, the unit of volume for firewood, shall be "st" and not "s", which had been previously assigned to it by the CIPM.

NOTE: To indicate a temperature interval or difference, rather than a temperature, the word "degree" in full, or the abbreviation "deg", must be used.
____
