== 10^th^ CGPM, 1954

=== Definition of the thermodynamic temperature scale (CR, 79)

[align=center]
*Resolution 3*

The 10^th^ Conférence Générale des Poids et Mesures decides to define the thermodynamic temperature scale by choosing the triple point of water as the fundamental fixed point, and assigning to it the temperature stem:[273.16 text( degrees Kelvin)], exactly.

NOTE: The 13^th^ CGPM in 1967 explicitly defined the kelvin (Resolution 4, see p. 169).

NOTE: The kelvin was redefined by the 26^th^ CGPM in 2018 (Resolution 1, see p. 197).

=== Definition of the standard atmosphere (CR, 79)

[align=center]
*Resolution 4*

The 10^th^ Conférence Générale des Poids et Mesures (CGPM), having noted that the definition of the standard atmosphere given by the 9^th^ CGPM when defining the International Temperature Scale led some physicists to believe that this definition of the standard atmosphere was valid only for accurate work in thermometry,

*declares* that it adopts, for general use, the definition:

[align=left]
stem:[1 text( standard atmosphere ) = 1 " "013 " "250 text( dynes per square centimetre)], +
i.e., stem:[101 " "325 text( newtons per square metre)].

=== Practical system of units (CR, 80)

[align=center]
*Resolution 6*

In accordance with the wish expressed by the 9^th^ Conférence Générale des Poids et Mesures (CGPM) in its Resolution 6 concerning the establishment of a practical system of units of measurement for international use, the 10^th^ CGPM

*decides* to adopt as base units of the system, the following units:

[%unnumbered]
|===
| length | metre
| mass | kilogram
| time | second
| electric current | ampere
| thermodynamic temperature | degree Kelvin
| luminous intensity | candela
|===

NOTE: The unit name "degree kelvin" was changed to "kelvin" in 1967 by the 13^th^ CGPM (Resolution 3, see p. 169).