[[cgpm10th1954]]
== 10th CGPM, 1954

[[cgpm10th1954r3]]
=== {blank}

[.variant-title,type=quoted]
*Definition of the thermodynamic temperature scale* (CR, 79) (((kelvin (stem:["unitsml(K)"])))) (((thermodynamic temperature))(((thermodynamic temperature scale)))

NOTE: The 13th CGPM in 1967 explicitly defined the kelvin (<<cgpm13th1967r4r4,Resolution 4>>).

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).

[[cgpm10th1954r3r3]]
==== Resolution 3
____

The 10th Conférence Générale des Poids et Mesures decides to define the thermodynamic temperature scale by choosing the ((triple point of water)) as the fundamental fixed point, and assigning to it the temperature stem:[273.16 text( degrees Kelvin)], exactly.
____


=== {blank}

[.variant-title,type=quoted]
*Definition of the standard atmosphere* (CR, 79) (((standard atmosphere)))

==== Resolution 4
____

The 10th Conférence Générale des Poids et Mesures (CGPM), having noted that the definition of the standard atmosphere given by the 9th CGPM when defining the International Temperature Scale led some physicists to believe that this definition of the standard atmosphere was valid only for accurate work in thermometry,

*declares* that it adopts, for general use, the definition: (((dyne (stem:["unitsml(dyn)"]))))

[align=left]
stem:[1 text( standard atmosphere ) = 1013250 text( dynes per square centimetre)], +
i.e., stem:[101325 text( newtons per square metre)].
____

[[cgpm10th1954r6]]
=== {blank}

[.variant-title,type=quoted]
*Practical system of units* (CR, 80)(((kelvin (stem:["unitsml(K)"]))))

NOTE: The unit name "degree Kelvin" was changed to "kelvin" in 1967 by the 13th CGPM (<<cgpm13th1967r3r3,Resolution 3>>).

[[cgpm10th1954r6r6]]
==== Resolution 6
____

In accordance with the wish expressed by the 9th Conférence Générale des Poids et Mesures (CGPM) in its Resolution 6 concerning the establishment of a practical system of units of measurement for international use, the 10th CGPM

*decides* to adopt as base units of the system, the following units:
(((base unit(s))))
(((ampere (stem:["unitsml(A)"]))))
(((kelvin (stem:["unitsml(K)"]))))
(((candela (stem:["unitsml(cd)"]))))
(((length)))
(((luminous intensity)))
(((mass)))
(((metre (stem:["unitsml(m)"]))))
(((thermodynamic temperature)))
(((time (duration))))

[%unnumbered]
|===
| length | metre
| mass | ((kilogram))
| time | second
| ((electric current)) | ampere
| thermodynamic temperature | degree Kelvin
| luminous intensity | candela
|===
____
