
[[cipm1956]]
== CIPM, 1956

[[cipm1956r1]]
=== Definition of the unit of time (second) (PV, 25, 77)

NOTE: This definition was abrogated in 1967 by the 13^th^ CGPM (<<cgpm13th1967r1r1,Resolution 1>>).

[[cipm1956r1r1]]
==== Resolution 1
____

In virtue of the powers invested in it by Resolution 5 of the 10^th^ Conférence Générale des Poids et Mesures, the Comité International des Poids et Mesures,

*considering*

. that the 9^th^ General Assembly of the International Astronomical Union (Dublin, 1955) declared itself in favour of linking the second to the tropical year,

[align=left]
. that, according to the decisions of the 8^th^ General Assembly of the International Astronomical Union (Rome, 1952), the second of ephemeris time (ET) is the fraction +
stem:[(12 " "960 " "276 " "813) / (408 " "986 " "496) times 10^(-9)] of the tropical year for 1900 January 0 at 12 h ET,

*decides*

"The second is the fraction stem:[1text(/)31 " "556 " "925.9747] of the tropical year for 1900 January 0 at 12 hours ephemeris time."
____


[[cipm1956r3]]
=== Système International d'Unités (PV, 25, 83)

[[cipm1956r3r3]]
==== Resolution 3
____

The Comité International des Poids et Mesures,

*considering*

* the task entrusted to it by Resolution 6 of the 9^th^ Conférence Générale des Poids et Mesures (CGPM) concerning the establishment of a practical system of units of measurement suitable for adoption by all countries adhering to the Metre Convention,
* the documents received from twenty-one countries in reply to the enquiry requested by the 9^th^ CGPM,
* Resolution 6 of the 10^th^ CGPM, fixing the base units of the system to be established,

*recommends*

[align=left]
. that the name "Système International d'Unités" be given to the system founded on the base units adopted by the 10^th^ CGPM, viz.: +
[This is followed by the list of the six base units with their symbols, reproduced in Resolution 12 of the 11^th^ CGPM (1960)].

. that the units listed in the table below be used, without excluding others which might be added later: +
[This is followed by the table of units reproduced in paragraph 4 of Resolution 12 of the 11^th^ CGPM (1960)].
____
