[[cgpm12th1964]]
== 12th CGPM, 1964

[[cgpm12th1964r5]]
=== Atomic standard of frequency (CR, 93)

[[cgpm12th1964r5r5]]
==== Resolution 5
____

The 12th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the 11th CGPM noted in its Resolution 10 the urgency, in the interests of accurate metrology, of adopting an atomic or molecular standard of time interval, 
* that, in spite of the results already obtained with caesium atomic frequency standards, the time has not yet come for the CGPM to adopt a new definition of the second, base unit(((base unit(s)))) of the Système International d'Unités, because of the new and considerable improvements likely to be obtained from work now in progress,

*considering also* that it is not desirable to wait any longer before time measurements in physics are based on atomic or molecular frequency standards,

*empowers* the Comité International des Poids et Mesures to name the atomic or molecular frequency standards to be employed for the time being,

*requests* the organizations and laboratories knowledgeable in this field to pursue work connected with a new definition of the second.
____

[[cgpm12th1964r6]]
=== Litre (CR, 93)

[[cgpm12th1964r6r6]]
==== Resolution 6
____

The 12th Conférence Générale des Poids et Mesures (CGPM)_,_

*considering* Resolution 13 adopted by the 11th CGPM in 1960 and the Recommendation adopted by the Comité International des Poids et Mesures in 1961,

. *abrogates* the definition of the litre given in 1901 by the 3rd CGPM,

. *declares* that the word "litre" may be employed as a special name for the cubic decimetre,

. *recommends* that the name litre should not be employed to give the results of high-accuracy volume measurements.
____

[[cgpm12th1964r7]]
=== Curie (CR, 94)(((curie (stem:["unitsml(Ci)"]))))

NOTE: The name "becquerel"(((becquerel (stem:["unitsml(Bq)"])))) (stem:["unitsml(Bq)"]) was adopted by the 15th CGPM in 1975 (<<cgpm15th1975r8_9r8_9,Resolution 8>>) for the SI unit of activity: stem:[1 "unitsml(Ci)" = 3.7 xx 10^(10) "unitsml(Bq)"].

NOTE: The name "becquerel"(((becquerel (stem:["unitsml(Bq)"])))) (stem:["unitsml(Bq)"]) was adopted by the 15th CGPM in 1975 (<<cgpm15th1975r8_9r8_9,Resolution 8>>) for the SI unit of activity: stem:[1 "unitsml(Ci)" = 3.7 xx 10^(10) "unitsml(Bq)"].

[[cgpm12th1964r7r7]]
==== Resolution 7
____

The 12th Conférence Générale des Poids et Mesures,
(((activity referred to a radionuclide)))

*considering* that the curie has been used for a long time in many countries as unit of activity for radionuclides,

*recognizing* that in the Système International d'Unités (SI), the unit of this activity is the second to the power of minus one (stem:["unitsml(s^(−1))"]),

*accepts* that the curie be still retained, outside SI, as unit of activity, with the value stem:[3.7 xx 10^(10) "unitsml(s^(−1))"]. The symbol for this unit is stem:["unitsml(Ci)"].
____



[[cgpm12th1964r8]]
=== SI prefixes femto and atto (CR, 94)(((prefixes)))(((SI prefixes)))((("submultiples, prefixes for")))

NOTE: New prefixes were added by the 15th CGPM in 1975 (<<cgpm15th1975r10r10,Resolution 10>>).

[[cgpm12th1964r8r8]]
==== Resolution 8 ((("multiples, prefixes for")))

____

The 12th Conférence Générale des Poids et Mesures (CGPM)

*decides* to add to the list of prefixes for the formation of names of multiples and sub­multiples of units, adopted by the 11th CGPM, Resolution 12, paragraph 3, the following two new prefixes:

[%unnumbered]
[cols="<,<,<"]
|===
| Multiplying factor | Prefix | Symbol
| stem:[10^(−15)] | femto | stem:["f"]
| stem:[10^(−18)] | atto | stem:["a"]
|===
____

