== 12^th^ CGPM, 1964

=== Atomic standard of frequency (CR, 93)

[align=center]
*Resolution 5*

The 12^th^ Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the 11^th^ CGPM noted in its Resolution 10 the urgency, in the interests of accurate metrology, of adopting an atomic or molecular standard of time interval, 
* that, in spite of the results already obtained with caesium atomic frequency standards, the time has not yet come for the CGPM to adopt a new definition of the second, base unit of the Système International d'Unités, because of the new and considerable improvements likely to be obtained from work now in progress,

*considering also* that it is not desirable to wait any longer before time measurements in physics are based on atomic or molecular frequency standards,

*empowers* the Comité International des Poids et Mesures to name the atomic or molecular frequency standards to be employed for the time being,

*requests* the organizations and laboratories knowledgeable in this field to pursue work connected with a new definition of the second.

=== Litre (CR, 93)

[align=center]
*Resolution 6*

The 12^th^ Conférence Générale des Poids et Mesures (CGPM)_,_

*considering* Resolution 13 adopted by the 11^th^ CGPM in 1960 and the Recommendation adopted by the Comité International des Poids et Mesures in 1961,

. *abrogates* the definition of the litre given in 1901 by the 3^rd^ CGPM,

. *declares* that the word "litre" may be employed as a special name for the cubic decimetre,

. *recommends* that the name litre should not be employed to give the results of high-accuracy volume measurements.

=== Curie (CR, 94)

[align=center]
*Resolution 7*

The 12^th^ Conférence Générale des Poids et Mesures,

*considering* that the curie has been used for a long time in many countries as unit of activity for radionuclides,

*recognizing* that in the Système International d'Unités (SI), the unit of this activity is the second to the power of minus one (stem:["s"^(−1)]),

*accepts* that the curie be still retained, outside SI, as unit of activity, with the value stem:[3.7 times 10^(10) " s"^(−1)]. The symbol for this unit is stem:["Ci"].

NOTE: The name "becquerel" (stem:["Bq"]) was adopted by the 15^th^ CGPM in 1975 (Resolution 8, see p. 172) for the SI unit of activity: stem:[1 " Ci" = 3.7 times 10^(10) " Bq"].

=== SI prefixes femto and atto (CR, 94)

[align=center]
*Resolution 8*

The 12^th^ Conférence Générale des Poids et Mesures (CGPM)

*decides* to add to the list of prefixes for the formation of names of multiples and sub­multiples of units, adopted by the 11^th^ CGPM, Resolution 12, paragraph 3, the following two new prefixes:

Multiplying factor Prefix Symbol

[%unnumbered]
[cols="<,<,<"]
|===
| Multiplying factor | Prefix | Symbol
| stem:[10^(−15)] | femto | stem:["f"]
| stem:[10^(−18)] | atto | stem:["a"]
|===

NOTE: New prefixes were added by the 15^th^ CGPM in 1975 (Resolution 10, see p. 173).
