[[cgpm13th1967_68]]
== 13th CGPM, 1967/68

[[cgpm13th1967r1]]
=== SI unit of time (second) (CR, 103 and _Metrologia_, 1968, 4, 43)

[[cgpm13th1967r1r1]]
==== Resolution 1
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the definition of the second adopted by the Comité International des Poids et Mesures (CIPM) in 1956 (Resolution 1) and ratified by Resolution 9 of the 11th CGPM (1960), later upheld by Resolution 5 of the 12th CGPM (1964), is inadequate for the present needs of metrology,
* that at its meeting of 1964 the CIPM, empowered by Resolution 5 of the 12th CGPM (1964), recommended, in order to fulfil these requirements, a caesium atomic frequency standard for temporary use,
* that this frequency standard has now been sufficiently tested and found sufficiently accurate to provide a definition of the second fulfilling present requirements,
* that the time has now come to replace the definition now in force of the unit of time of the Système International d'Unités by an atomic definition based on that standard,

*decides*

[align=left]
. The SI unit of time is the second defined as follows: +
"The second is the duration of 9 192 631 770 periods of the radiation corresponding to the transition between the two hyperfine levels of the ground state of the caesium 133 atom"; footnote:[At its 1997 meeting, the CIPM affirmed that this definition refers to a caesium atom at rest at a thermodynamic temperature of 0 K. The wording of the definition of the second was modified by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).]

. Resolution 1 adopted by the CIPM at its meeting of 1956 and Resolution 9 of the 11th CGPM are now abrogated.
____

[[cgpm13th1967r3]]
=== SI unit of thermodynamic temperature (kelvin) (CR, 104 and _Metrologia_, 1968, 4, 43)

NOTE: At its 1980 meeting, the CIPM approved the report of the 7th meeting of the CCU, which requested that the use of the symbols "stem:["°K"]" and "stem:["deg"]" no longer be permitted.

[[cgpm13th1967r3r3]]
==== Resolution 3
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* the names "degree Kelvin" and "degree", the symbols "stem:["°K"]" and "stem:["deg"]" and the rules for their use given in Resolution 7 of the 9th CGPM (1948), in Resolution 12 of the 11th CGPM (1960), and the decision taken by the Comité International des Poids et Mesures in 1962 (PV, *30*, 27),
* that the unit of thermodynamic temperature and the unit of temperature interval are one and the same unit, which ought to be denoted by a single name and a single symbol,

*decides*

. the unit of thermodynamic temperature is denoted by the name "kelvin" and its symbol is "stem:["K"]"; footnote:[See Recommendation 2 (<<cipm2005r2r2,CI-2005>>) of the CIPM on the isotopic composition of water entering in the definition of the kelvin.]

. the same name and the same symbol are used to express a temperature interval;

. a temperature interval may also be expressed in degrees Celsius;

. the decisions mentioned in the opening paragraph concerning the name of the unit of thermo­dynamic temperature, its symbol and the designation of the unit to express an interval or a difference of temperatures are abrogated, but the usages which derive from these decisions remain permissible for the time being.
____


[[cgpm13th1967r4]]
=== Definition of the SI unit of thermodynamic temperature (kelvin) (CR, 104 and _Metrologia_, 1968, 4, 43)

NOTE: See Recommendation 5 (<<cipm1989temp,CI-1989>>) of the CIPM on the International Temperature Scale of 1990.

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).

[[cgpm13th1967r4r4]]
==== Resolution 4
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering* that it is useful to formulate more explicitly the definition of the unit of thermodynamic temperature contained in Resolution 3 of the 10th CGPM (1954),

*decides* to express this definition as follows:

"The kelvin, unit of thermodynamic temperature, is the fraction stem:[1text(/)273.16] of the thermodynamic temperature of the triple point of water."
____

[[cgpm13th1967r5]]
=== SI unit of luminous intensity (candela) (CR, 104 and _Metrologia_, 1968, 4, 43-44)

NOTE: This definition was abrogated by the 16th CGPM in 1979 (<<cgpm16th1979r3r3,Resolution 3>>).

[[cgpm13th1967r5r5]]
==== Resolution 5
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* the definition of the unit of luminous intensity ratified by the 9th CGPM (1948) and contained in the "Resolution concerning the change of photometric units" adopted by the Comité International des Poids et Mesures in 1946 (PV, *20*, 119) in virtue of the powers conferred by the 8th CGPM (1933),
* that this definition fixes satisfactorily the unit of luminous intensity, but that its wording may be open to criticism,

*decides* to express the definition of the candela as follows:

"The candela is the luminous intensity, in the perpendicular direction, of a surface of stem:[1text(/)600  000 text( square metre)] of a black body at the temperature of freezing platinum under a pressure of stem:[101 325 text( newtons per square metre)]."
____



[[cgpm13th1968r6]]
=== SI derived units (CR, 105 and _Metrologia_, 1968, 4, 44)

NOTE: The unit of activity was given a special name and symbol by the 15th CGPM in 1975 (<<cgpm15th1975r8_9,Resolution 8>>).

[[cgpm13th1968r6r6]]
==== Resolution 6
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering* that it is useful to add some derived units to the list of paragraph 4 of Resolution 12 of the 11th CGPM (1960),

*decides* to add:

[%unnumbered]
|===
| wave number | 1 per metre | stem:["m"^(–1)]
| entropy | joule per kelvin | stem:["J/K"]
| specific heat capacity | joule per kilogram kelvin | stem:["J/"("kg" * "K")]
| thermal conductivity | watt per metre kelvin | stem:["W/"("m" * "K")]
| radiant intensity | watt per steradian | stem:["W/sr"]
| activity (of a radioactive source) | 1 per second | stem:["s"^(–1)]
|===
____

[[cgpm13th1967r7]]
=== Abrogation of earlier decisions (micron and new candle) (CR, 105 and _Metrologia_, 1968, 4, 44)

[[cgpm13th1967r7r7]]
==== Resolution 7
____

The 13th Conférence Générale des Poids et Mesures (CGPM),

*considering* that subsequent decisions of the General Conference concerning the Système International d'Unités are incompatible with parts of Resolution 7 of the 9th CGPM (1948),

*decides* accordingly to remove from Resolution 7 of the 9th Conference:

. the unit name "micron", and the symbol "stem:[mu]" which had been given to that unit but which has now become a prefix;

. the unit name "new candle".
____