== CIPM, 1969

=== Système International d'Unités, Rules for application of Resolution 12 of the 11^th^ CGPM (1960) (PV, 37, 30 and _Metrologia_, 1970, 6, 66)

____
[align=center]
*Recommendation 1*

The Comité International des Poids et Mesures,

*considering* that Resolution 12 of the 11^th^ Conférence Générale des Poids et Mesures (CGPM) (1960), concerning the Système International d'Unités, has provoked discussions on certain of its aspects,

*declares*

. the base units, the supplementary units and the derived units of the Système International d'Unités, which form a coherent set, are denoted by the name "SI units"; footnote:[The CIPM approved in 2001 a proposal of the CCU to clarify the definition of "SI units" and "units of the SI", see p. 180.]

. the prefixes adopted by the CGPM for the formation of decimal multiples and submultiples of SI units are called "SI prefixes";

and *recommends*

[start=3]
. the use of SI units and of their decimal multiples and submultiples whose names are formed by means of SI prefixes.

NOTE: The name "supplementary units", appearing in Resolution 12 of the 11^th^ CGPM (and in the present Recommendation) is given to SI units for which the General Conference declines to state whether they are base units or derived units.
____

NOTE: The 20^th^ CGPM in 1995 decided to abrogate the class of supplementary units in the SI (Resolution 8, see p. 179).