== 14^th^ CGPM, 1971

=== Pascal and siemens (CR, 78)

____
The 14^th^ Conférence Générale des Poids et Mesures adopted the special names "pascal" (symbol stem:["Pa"]), for the SI unit newton per square metre, and "siemens" (symbol stem:["S"]), for the SI unit of electric conductance [reciprocal ohm].
____

=== International Atomic Time, function of CIPM (CR, 77-78 and _Metrologia_, 1972, 8, 35)

____
[align=center]
*Resolution 1*

The 14^th^ Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the second, unit of time of the Système International d'Unités, has since 1967 been defined in terms of a natural atomic frequency, and no longer in terms of the time scales provided by astronomical motions,
* that the need for an International Atomic Time (TAI) scale is a consequence of the atomic definition of the second,
* that several international organizations have ensured and are still successfully ensuring the establishment of the time scales based on astronomical motions, particularly thanks to the permanent services of the Bureau International de l'Heure (BIH), 
* that the BIH has started to establish an atomic time scale of recognized quality and proven usefulness,
* that the atomic frequency standards for realizing the second have been considered and must continue to be considered by the Comité International des Poids et Mesures (CIPM) helped by a Consultative Committee, and that the unit interval of the International Atomic Time scale must be the second realized according to its atomic definition,
* that all the competent international scientific organizations and the national laboratories active in this field have expressed the wish that the CIPM and the CGPM should give a definition of International Atomic Time, and should contribute to the establishment of the International Atomic Time scale,
* that the usefulness of International Atomic Time entails close coordination with the time scales based on astronomical motions, 

*requests* the CIPM

. to give a definition of International Atomic Time, footnote:[The definition of TAI was given by the CCDS in 1970 (now the CCTF), see CCDS report p. 22.]

. to take the necessary steps, in agreement with the international organizations concerned, to ensure that available scientific competence and existing facilities are used in the best possible way to realize the International Atomic Time scale and to satisfy the requirements of users of International Atomic Time.
____

[[cgpm14th1971r3]]
=== SI unit of amount of substance (mole) (CR, 78 and _Metrologia_, 1972, 8, 36)

____
[align=center]
*Resolution 3*

The 14^th^ Conférence Générale des Poids et Mesures (CGPM),

*considering* the advice of the International Union of Pure and Applied Physics, of the International Union of Pure and Applied Chemistry, and of the International Organization for Standardization, concerning the need to define a unit of amount of substance,

*decides*

. The mole is the amount of substance of a system which contains as many elementary entities as there are atoms in 0.012 kilogram of carbon 12; its symbol is "stem:["mol"]". footnote:[The mole was redefined by the <<cgpm26th2018r1,26^th^ CGPM in 2018 (Resolution 1)>>.]

. When the mole is used, the elementary entities must be specified and may be atoms, molecules, ions, electrons, other particles, or specified groups of such particles.

. The mole is a base unit of the Système International d'Unités.
____

NOTE: At its 1980 meeting, the CIPM approved the report of the 7^th^ meeting of the CCU (1980) specifying that, in this definition, it is understood that unbound atoms of carbon 12, at rest and in their ground state, are referred to.