[[cgpm16th1979]]
== 16th CGPM, 1979

[[cgpm16th1979r3]]
=== SI unit of luminous intensity (candela) (CR, 100 and _Metrologia_, 1980, 16, 56)

NOTE: The wording of the definition of the candela was modified by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).

[[cgpm16th1979r3r3]]
==== Resolution 3
____

The 16th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that despite the notable efforts of some laboratories there remain excessive divergences between the results of realizations of the candela based upon the present black body primary standard,
* that radiometric techniques are developing rapidly, allowing precisions that are already equivalent to those of photometry and that these techniques are already in use in national laboratories to realize the candela without having to construct a black body,
* that the relation between luminous quantities of photometry and radiometric quantities, namely the value of 683 lumens per watt for the spectral luminous efficacy of monochromatic radiation of frequency stem:[540 times 10^(12) text( hertz)], has been adopted by the Comité International des Poids et Mesures (CIPM) in 1977,
* that this value has been accepted as being sufficiently accurate for the system of luminous photopic quantities footnote:[Photopic vision is detected by the cones on the retina of the eye, which are sensitive to a high level of luminance (stem:["L" > " ca. " 10 " cd/m"^2]) and are used in daytime vision.], that it implies a change of only about 3 % for the system of luminous scotopic quantities footnote:[Scotopic vision is detected by the rods of the retina, which are sensitive to low level luminance (stem:["L" < " ca. " 10^(−3) " cd/m"^2]), used in night vision.], and that it therefore ensures satisfactory continuity,
* that the time has come to give the candela a definition that will allow an improvement in both the ease of realization and the precision of photometric standards, and that applies to both photopic and scotopic photometric quantities and to quantities yet to be defined in the mesopic field footnote:[In the domain between these levels of luminance both cones and rods are used, and this is described as mesopic vision.],

*decides*

. The candela is the luminous intensity, in a given direction, of a source that emits monochromatic radiation of frequency stem:[540 times 10^(12) text( hertz)] and that has a radiant intensity in that direction of stem:[1text(/)683 text( watt per steradian)].

. The definition of the candela (at the time called new candle) adopted by the CIPM in 1946 by reason of the powers conferred by the 8th CGPM in 1933, ratified by the 9th CGPM in 1948, then amended by the 13th CGPM in 1967, is abrogated.
____



[[cgpm16th1979r5]]
=== Special name for the SI unit of dose equivalent (sievert) (CR, 100 and _Metrologia_, 1980, 16, 56)

NOTE: The CIPM, in 1984, decided to accompany this Resolution with an explanation (<<cipm1984r1r1,Recommendation 1>>).

[[cgpm16th1979r5r5]]
==== Resolution 5
____

The 16th Conférence Générale des Poids et Mesures,

*considering*

* the effort made to introduce SI units into the field of ionizing radiations,
* the risk to human beings of an underestimated radiation dose, a risk that could result from a confusion between absorbed dose and dose equivalent,
* that the proliferation of special names represents a danger for the Système International d'Unités and must be avoided in every possible way, but that this rule can be broken when it is a matter of safeguarding human health,

*adopts* the special name *_sievert_*, symbol stem:["Sv"], for the SI unit of dose equivalent in the field of radioprotection. The sievert is equal to the joule per kilogram.
____


[[cgpm16th1979r6]]
=== Symbols for the litre (CR, 101 and _Metrologia_, 1980, 16, 56-57)

[[cgpm16th1979r6r6]]
==== Resolution 6
____

The 16th Conférence Générale des Poids et Mesures (CGPM),

*recognizing* the general principles adopted for writing the unit symbols in Resolution 7 of the 9th CGPM (1948),

*considering* that the symbol stem:["l"] for the unit litre was adopted by the Comité International des Poids et Mesures (CIPM) in 1879 and confirmed in the same Resolution of 1948,

*considering* also that, in order to avoid the risk of confusion between the letter l and the number 1, several countries have adopted the symbol stem:["L"] instead of stem:["l"] for the unit litre,

*considering* that the name litre, although not included in the Système International d'Unités, must be admitted for general use with the System,

*decides*, as an exception, to adopt the two symbols stem:["l"] and stem:["L"] as symbols to be used for the unit litre, footnote:[The CIPM, in 1990, considered that it was still too early to choose a single symbol for the litre.]

*considering* further that in the future only one of these two symbols should be retained,

*invites* the CIPM to follow the development of the use of these two symbols and to give the 18th CGPM its opinion as to the possibility of suppressing one of them.
____
