[[cipm1980]]
== CIPM, 1980

[[cipm1980r1]]
=== SI supplementary units (radian and steradian) (PV, 48, 24 and _Metrologia_, 1981, 17, 72)

NOTE: The class of SI supplementary units was abrogated by decision of the 20th CGPM in 1995 (<<cgpm20th1995r8r8,Resolution 8>>).

[[cipm1980r1r1]]
==== Recommendation 1
____

The Comité International des Poids et Mesures (CIPM),
((("quantity, base"))) index-range:radian_rad-2[(((radian (stem:["unitsml(rad)"]))))] index-range:steradian_sr-2[(((steradian (stem:["unitsml(sr)"]))))] (((supplementary units)))

*taking into consideration* Resolution 3 adopted by ((ISO/TC 12)) in 1978 and Recommendation U 1 (1980) adopted by the Comité Consultatif des Unités at its 7th meeting,

*considering*

* that the units radian and steradian(((steradian (stem:["unitsml(sr)"])))) are usually introduced into expressions for units when there is need for clarification, especially in photometry where the steradian plays an important role in distinguishing between units corresponding to different quantities,
* that in the equations used one generally expresses plane ((angle)) as the ratio of two lengths and solid ((angle)) as the ratio between an area and the square of a length, and consequently that these quantities are treated as ((dimensionless quantities)),
* that the study of the formalisms in use in the scientific field shows that none exists which is at the same time coherent and convenient and in which the quantities plane ((angle)) and solid ((angle)) might be considered as base quantities(((base quantity))),

*considering also*
(((radian (stem:["unitsml(rad)"]))))

* that the interpretation given by the CIPM in 1969 for the class of ((supplementary units)) introduced in Resolution 12 of the 11th Conférence Générale des Poids et Mesures (CGPM) in 1960 allows the freedom of treating the radian and the steradian as SI base units(((base unit(s)))),
* that such a possibility compromises the internal coherence of the SI based on only seven base units(((base unit(s)))),

*decides* to interpret the class of ((supplementary units)) in the International System as a class of dimensionless derived units for which the CGPM allows the freedom of using or not using them in expressions for SI derived units. [[radian_rad-2]] [[steradian_sr-2]]
____

