== CIPM, 1980

=== SI supplementary units (radian and steradian) (PV, 48, 24 and _Metrologia_, 1981, 17, 72)

____
[align=center]
*Recommendation 1*

The Comité International des Poids et Mesures (CIPM),

*taking into consideration* Resolution 3 adopted by ISO/TC 12 in 1978 and Recommendation U 1 (1980) adopted by the Comité Consultatif des Unités at its 7^th^ meeting,

*considering*

* that the units radian and steradian are usually introduced into expressions for units when there is need for clarification, especially in photometry where the steradian plays an important role in distinguishing between units corresponding to different quantities,
* that in the equations used one generally expresses plane angle as the ratio of two lengths and solid angle as the ratio between an area and the square of a length, and consequently that these quantities are treated as dimensionless quantities,
* that the study of the formalisms in use in the scientific field shows that none exists which is at the same time coherent and convenient and in which the quantities plane angle and solid angle might be considered as base quantities,

*considering also*

* that the interpretation given by the CIPM in 1969 for the class of supplementary units introduced in Resolution 12 of the 11^th^ Conférence Générale des Poids et Mesures (CGPM) in 1960 allows the freedom of treating the radian and the steradian as SI base units,
* that such a possibility compromises the internal coherence of the SI based on only seven base units,

*decides* to interpret the class of supplementary units in the International System as a class of dimensionless derived units for which the CGPM allows the freedom of using or not using them in expressions for SI derived units.
____

NOTE: The class of SI supplementary units was abrogated by decision of the 20^th^ CGPM in 1995 (Resolution 8, see p. 179).