[[cipm1984]]
== CIPM, 1984

[[cipm1984r1]]
=== Concerning the sievert (PV, 52, 31 and _Metrologia_, 1985, 21, 90)

____
[align=center]
*Recommendation 1*

The Comité International des Poids et Mesures,

*considering* the confusion which continues to exist on the subject of Resolution 5, approved by the 16^th^ Conférence Générale des Poids et Mesures (1979),

*decides* to introduce the following explanation in the brochure "Le Système International d'Unités (SI)":

The quantity dose equivalent stem:[H] is the product of the absorbed dose stem:[D] of ionizing radiation and the dimensionless factors stem:[Q] (quality factor) and stem:[N] (product of any other multiplying factors) stipulated by the International Commission on Radiological Protection: +

[stem%unnumbered]
++++
H = Q cdot N cdot D.
++++

Thus, for a given radiation, the numerical value of stem:[H] in joules per kilogram may differ from that of stem:[D] in joules per kilogram depending upon the values of stem:[Q] and stem:[N]. In order to avoid any risk of confusion between the absorbed dose stem:[D] and the dose equivalent stem:[H], the special names for the respective units should be used, that is, the name gray should be used instead of joules per kilogram for the unit of absorbed dose stem:[D] and the name sievert instead of joules per kilogram for the unit of dose equivalent stem:[H].
____

NOTE: The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (<<cipm2002r2,Recommendation 2>>).