[[cgpm18th1987]]
== 18^th^ CGPM, 1987

[[cgpm18th1987r6]]
=== Forthcoming adjustment to the representations of the volt and of the ohm (CR, 100 and _Metrologia_, 1988, 25, 115)

[[cgpm18th1987r6r6]]
==== Resolution 6
____

The 18^th^ Conférence Générale des Poids et Mesures,

*considering*

* that worldwide uniformity and long-term stability of national representations of the electrical units are of major importance for science, commerce and industry from both the technical and economic points of view, 
* that many national laboratories use the Josephson effect and are beginning to use the quantum Hall effect to maintain, respectively, representations of the volt and of the ohm, as these offer the best guarantees of long-term stability, 
* that because of the importance of coherence among the units of measurement of the various physical quantities the values adopted for these representations must be as closely as possible in agreement with the SI, 
* that the results of recent and current experiment will permit the establishment of an acceptable value, sufficiently compatible with the SI, for the coefficient which relates each of these effects to the corresponding electrical unit,

*invites* the laboratories whose work can contribute to the establishment of the quotient voltage/frequency in the case of the Josephson effect and of the quotient voltage/current for the quantum Hall effect to vigorously pursue these efforts and to communicate their results without delay to the Comité International des Poids et Mesures, and

*instructs* the Comité International des Poids et Mesures to recommend, as soon as it considers it possible, a value for each of these quotients together with a date for them to be put into practice simultaneously in all countries; these values should be announced at least one year in advance and would be adopted on 1 January 1990.
____