[[cipm1988]]
== CIPM, 1988

[[cipm1988r1]]
=== Representation of the volt by means of the Josephson effect (PV, 56, 44 and _Metrologia_, 1989, 26, 69) (((Josephson effect)))

NOTE: The 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>) abrogated the adoption of a conventional value for stem:[ii(K)_"J"].

[[cipm1988r1r1]]
==== Recommendation 1
____

The Comité International des Poids et Mesures,

*acting* in accordance with instructions given in Resolution 6 of the 18th Conférence Générale des Poids et Mesures concerning the forthcoming adjustment of the representations of the volt and the ohm,

*considering*

* that a detailed study of the results of the most recent determinations leads to a value of stem:[483597.9 " "rm(GHz)//rm(V)] for the Josephson constant, stem:[ii(K)_"J"],that is to say, for the quotient of frequency divided by the potential difference corresponding to the stem:[n = 1] step in the ((Josephson effect)), (((Josephson constant (stem:[K_J,K_{J-90}]))))
* that the Josephson effect, together with this value of stem:[ii(K)_"J"],can be used to establish a reference standard of electromotive force having a one-standard-deviation uncertainty with respect to the volt estimated to be 4 parts in stem:[10^7], and a reproducibility which is significantly better,

*recommends*

* that stem:[483597.9 " "rm(GHz)//rm(V)] exactly be adopted as a conventional value, denoted by stem:[ii(K)_("J-90")] for the Josephson constant, stem:[ii(K)_"J"], (((Josephson constant (stem:[K_J,K_{J-90}]))))
* that this new value be used from 1 January 1990, and not before, to replace the values currently in use,
* that this new value be used from this same date by all laboratories which base their measurements of electromotive force on the ((Josephson effect)), and
* that from this same date all other laboratories adjust the value of their laboratory reference standards to agree with the new adopted value,

*is of the opinion* that no change in this recommended value of the Josephson constant will be necessary in the foreseeable future, and (((Josephson constant (stem:[K_J,K_{J-90}]))))

*draws the attention* of laboratories to the fact that the new value is greater by stem:[3.9 " "rm(GHz)//rm(V)], or about 8 parts in stem:[10^6], than the value given in 1972 by the Comité Consultatif d'Électricité in its Declaration E-72.
____



[[cipm1988r2]]
=== Representation of the ohm by means of the quantum Hall effect (PV, 56, 45 and _Metrologia_, 1989, 26,70) index-range:hall_effect(((Hall effect (incl. quantum Hall effect))))

NOTE: At its 89th meeting in 2000, the CIPM approved the declaration of the 22nd meeting of the CCEM on the use of the value of the von Klitzing constant.

NOTE: The 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>) abrogated the adoption of a conventional value for stem:[ii(R)_"K"].

[[cipm1988r2r2]]
==== Recommendation 2
____

The Comité International des Poids et Mesures,

*acting* in accordance with instructions given in Resolution 6 of the 18th Conférence Générale des Poids et Mesures concerning the forthcoming adjustment of the representations of the volt and the ohm,

*considering*

* that most existing laboratory reference standards of resistance change significantly with time, 
* that a laboratory reference standard of resistance based on the quantum Hall effect would be stable and reproducible, 
* that a detailed study of the results of the most recent determinations leads to a value of stem:[25812.807 Omega] for the von Klitzing constant, stem:[ii(R)_"K"],that is to say, for the quotient of the Hall potential difference divided by current corresponding to the plateau stem:[i = 1] in the quantum Hall effect, 
* that the quantum Hall effect, together with this value of stem:[ii(R)_"K"], can be used to establish a reference standard of resistance having a one-standard-deviation uncertainty with respect to the ohm estimated to be 2 parts in stem:[10^7], and a reproducibility which is significantly better,

*recommends*

* that stem:[25812.807 Omega] exactly be adopted as a conventional value, denoted by stem:[ii(R)_("K-90")], for the von Klitzing constant, stem:[ii(R)_"K"],
* that this value be used from 1 January 1990, and not before, by all laboratories which base their measurements of resistance on the quantum Hall effect,
* that from this same date all other laboratories adjust the value of their laboratory reference standards to agree with stem:[ii(R)_("K-90")],
* that in the use of the quantum Hall effect to establish a laboratory reference standard of resistance, laboratories follow the most recent edition of the technical guidelines for reliable measurements of the quantized Hall resistance drawn up by the Comité Consultatif d'Électricité and published by the Bureau International des Poids et Mesures, and

*is of the opinion* that no change in this recommended value of the von Klitzing constant will be necessary in the foreseeable future. [[hall_effect]]
____

