[[cipm1989]]
== CIPM, 1989

[[cipm1989temp]]
=== The International Temperature Scale of 1990 (PV, 57, 115 and _Metrologia_, 1990, 27, 13)
(((International Temperature Scale of 1990 (ITS-90))))

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>). (((kelvin (K))))

==== Recommendation 5
____

The Comité International des Poids et Mesures (CIPM) acting in accordance with Resolution 7 of the 18th Conférence Générale des Poids et Mesures (1987) has adopted the International Temperature Scale of 1990 (ITS-90) to supersede the International Practical Temperature Scale of 1968 (IPTS-68).

The CIPM *notes* that, by comparison with the IPTS-68, the ITS-90

* extends to lower temperatures, down to stem:[0.65 " "rm(K)], and hence also supersedes the EPT-76,
* is in substantially better agreement with corresponding ((thermodynamic temperature))s,
* has much improved ((continuity)), precision and reproducibility throughout its range and
* has subranges and alternative definitions in certain ranges which greatly facilitate its use.

The CIPM also *notes* that, to accompany the text of the ITS-90 there will be two further documents, the _Supplementary Information for the ITS-90_ and _Techniques for Approximating the ITS-90_. These documents will be published by the BIPM and periodically updated.

The CIPM *recommends*

* that on 1 January 1990 the ITS-90 come into force and 
* that from this same date the IPTS-68 and the EPT-76 be abrogated.
____

