[[cgpm19th1991]]
== 19^th^ CGPM, 1991

[[cgpm19th1991r4]]
=== SI prefixes zetta, zepto, yotta and yocto (CR, 185 and _Metrologia_, 1992, 29, 3)

____
[align=center]
*Resolution 4*

The 19^th^ Conférence Générale des Poids et Mesures (CGPM)

*decides* to add to the list of SI prefixes to be used for multiples and submultiples of units, adopted by the 11^th^ CGPM, Resolution 12, paragraph 3, the 12^th^ CGPM, Resolution 8 and the 15^th^ CGPM, Resolution 10, the following prefixes:

[%unnumbered]
[cols="<,<,<"]
|===
| Multiplying factor | Prefix | Symbol

| stem:[10^(21)] | zetta | stem:["Z"]
| stem:[10^(-21)] | zepto | stem:["z"]
| stem:[10^(24)] | yotta | stem:["Y"]
| stem:[10^(-24)] | yocto | stem:["y"]
|===

NOTE: The names zepto and zetta are derived from septo suggesting the number seven (the seventh power of stem:[10^3]) and the letter "z" is substituted for the letter "s" to avoid the duplicate use of the letter "s" as a symbol. The names yocto and yotta are derived from octo, suggesting the number eight (the eighth power of stem:[10^3]); the letter "y" is added to avoid the use of the letter "o" as a symbol because it may be confused with the number zero.
____