== 20^th^ CGPM, 1995

=== Elimination of the class of supplementary units in the SI (CR, 223 and _Metrologia_, 1996, 33, 83)

____
[align=center]
*Resolution 8*

The 20^th^ Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the 11^th^ Conférence Générale in 1960 in its Resolution 12, establishing the Système International d'Unités, SI, distinguished between three classes of SI units: the base units, the derived units, and the supplementary units, the last of these comprising the radian and the steradian,
* that the status of the supplementary units in relation to the base units and the derived units gave rise to debate,
* that the Comité International des Poids et Mesures, in 1980, having observed that the ambiguous status of the supplementary units compromises the internal coherence of the SI, has in its Recommendation 1 (CI-1980) interpreted the supplementary units, in the SI, as dimensionless derived units,

*approving* the interpretation given by the Comité International in 1980,

*decides*

* to interpret the supplementary units in the SI, namely the radian and the steradian, as dimensionless derived units, the names and symbols of which may, but need not, be used in expressions for other SI derived units, as is convenient,
* and, consequently, to eliminate the class of supplementary units as a separate class in the SI.
____