[[cgpm21st1999]]
== 21^st^ CGPM, 1999

[[cgpm21st1999r7]]
=== The definition of the kilogram (CR, 331 and _Metrologia_, 2000, 37, 94)

____
[align=center]
*Resolution 7*

The 21^st^ Conférence Générale des Poids et Mesures,

*considering*

* the need to assure the long-term stability of the International System of Units (SI),
* the intrinsic uncertainty in the long-term stability of the artefact defining the unit of mass, one of the base units of the SI,
* the consequent uncertainty in the long-term stability of the other three base units of the SI that depend on the kilogram, namely, the ampere, the mole and the candela,
* the progress already made in a number of different experiments designed to link the unit of mass to fundamental or atomic constants,
* the desirability of having more than one method of making such a link,

*recommends* that national laboratories continue their efforts to refine experiments that link the unit of mass to fundamental or atomic constants with a view to a future redefinition of the kilogram.
____

[[cgpm21st1999r12]]
=== Special name for the SI derived unit mole per second, the katal, for the expression of catalytic activity (CR, 334-335 and _Metrologia_, 2000, 37, 95)

____
[align=center]
*Resolution 12*

The 21^st^ Conférence Générale des Poids et Mesures,

*considering*

* the importance for human health and safety of facilitating the use of SI units in the fields of medicine and biochemistry,
* that a non-SI unit called "unit", symbol stem:["U"], equal to stem:[1 text( )mu "mol" * "min"^(–1)], which is not coherent with the International System of Units (SI), has been in widespread use in medicine and biochemistry since 1964 for expressing catalytic activity,
* that the absence of a special name for the SI coherent derived unit mole per second has led to results of clinical measurements being given in various local units,
* that the use of SI units in medicine and clinical chemistry is strongly recommended by the international unions in these fields,
* that the International Federation of Clinical Chemistry and Laboratory Medicine has asked the Consultative Committee for Units to recommend the special name katal, symbol stem:["kat"], for the SI unit mole per second,
* that while the proliferation of special names represents a danger for the SI, exceptions are made in matters related to human health and safety (15^th^ General Conference, 1975, Resolutions 8 and 9, 16^th^ General Conference, 1979, Resolution 5),

*noting* that the name katal, symbol stem:["kat"], has been used for the SI unit mole per second for over thirty years to express catalytic activity,

*decides* to adopt the special name katal, symbol stem:["kat"], for the SI unit mole per second to express catalytic activity, especially in the fields of medicine and biochemistry,

and *recommends* that when the katal is used, the measurand be specified by reference to the measurement procedure; the measurement procedure must identify the indicator reaction.
____