[[cipm2002]]
== CIPM, 2002

[[cipm2002r1]]
=== Revision of the practical realization of the definition of the metre (PV, 70, 194-204 and _Metrologia_, 40, 103-133) (((metre (m))))

[[cipm2002r1r1]]
==== Recommendation 1
____

The International Committee for Weights and Measures,

*recalling*

* that in 1983 the 17th General Conference (CGPM) adopted a new definition of the metre;
* that in the same year the CGPM invited the International Committee (CIPM)
** to draw up instructions for the practical realization of the metre,
** to choose radiations which can be recommended as standards of wavelength for the interferometric measurement of ((length)) and draw up instructions for their use,
** to pursue studies undertaken to improve these standards and in due course to extend or revise these instructions;

* that in response to this invitation the CIPM adopted Recommendation 1 (CI-1983) (_mise en pratique_ of the definition of the metre) to the effect
** [[cipm2002-abc]]that the metre should be realized by one of the following methods:
+
--
[loweralpha]
... [[cipm2002-a]]by means of the ((length)) stem:[l] of the path travelled in vacuum by a plane electromagnetic wave in a time stem:[t]; this length is obtained from the measured time stem:[t], using the relation stem:[l = c_0 * t] and the value of the ((speed of light in vacuum)) stem:[c_0 = 299792458 " "rm(m)//rm(s)],

... [[cipm2002-b]]by means of the wavelength in vacuum stem:[ii(lambda)] of a plane electromagnetic wave of frequency stem:[f]; this wavelength is obtained from the measured frequency stem:[f] using the relation stem:[ii(lambda) = c_0 // f] and the value of the ((speed of light in vacuum)) stem:[c_0 = 299792458 " "rm(m)//rm(s)],

... [[cipm2002-c]]by means of one of the radiations from the list below, whose stated wavelength in vacuum or whose stated frequency can be used with the uncertainty shown, provided that the given specifications and accepted good practice are followed;
--
** that in all cases any necessary corrections be applied to take account of actual conditions such as diffraction, gravitation or imperfection in the vacuum; (((general relativity)))
** that in the context of general relativity, the metre is considered a unit of proper length. Its definition, therefore, applies only within a spatial extent sufficiently small that the effects of the non-uniformity of the gravitational field can be ignored (note that, at the surface of the Earth, this effect in the vertical direction is about 1 part in stem:[10^(16) text( per metre)]). In this case, the effects to be taken into account are those of special relativity only. The local methods for the realization of the metre recommended in <<cipm2002-b>> and <<cipm2002-c>> provide the proper metre but not necessarily that given in <<cipm2002-a>>. Method <<cipm2002-a>> should therefore be restricted to lengths stem:[l] which are sufficiently short for the effects predicted by general relativity to be negligible with respect to the uncertainties of realization. For advice on the interpretation of measurements in which this is not the case, see the report of the Consultative Committee for Time and Frequency (CCTF) Working Group on the Application of General Relativity to Metrology (Application of general relativity to metrology, _Metrologia_, 1997, *34*, 261-290);

* that the CIPM had already recommended a list of radiations for this purpose;

*recalling* also that in 1992 and in 1997 the CIPM revised the practical realization of the definition of the metre;

*considering*
(((metre (m))))

* that science and technology continue to demand improved accuracy in the realization of the metre;
* that since 1997 work in national laboratories, in the BIPM and elsewhere has identified new radiations and methods for their realization which lead to lower uncertainties;
* that there is an increasing move towards optical frequencies for time-related activities, and that there continues to be a general widening of the scope of application of the recommended radiations of the _mise en pratique_ to cover not only dimensional metrology and the realization of the metre, but also high-resolution spectroscopy, atomic and molecular physics, fundamental constants and telecommunication; (((fundamental constants (of physics))))
* that a number of new frequency values with reduced uncertainties for radiations of high-stability cold atom and ion standards already listed in the recommended radiations list are now available, that the frequencies of radiations of several new cold atom and ion species have also recently been measured, and that new improved values with substantially reduced uncertainties for a number of optical frequency standards based on gas cells have been determined, including the wavelength region of interest to optical telecommunications;
* that new femtosecond comb techniques have clear significance for relating the frequency of high-stability optical frequency standards to that of the frequency standard realizing the SI second, that these techniques represent a convenient measurement technique for providing traceability to the International System of Units (SI) and that comb technology also can provide frequency sources as well as a measurement technique;

*recognizes* comb techniques as timely and appropriate, and recommends further research to fully investigate the capability of the techniques;

*welcomes* validations now being made of comb techniques by comparison with other frequency chain techniques;

*urges* national metrology institutes and other laboratories to pursue the comb technique to the highest level of accuracy achievable and also to seek simplicity so as to encourage widespread application;

*recommends*

* that the list of recommended radiations given by the CIPM in 1997 (Recommendation 1 (CI-1997)) be replaced by the list of radiations given below footnote:[The list of recommended radiations, Recommendation 1 (CI-2002), is given in PV, *70*, 197-204 and _Metrologia_, 2003, *40*, 104-115.], including
** updated frequency values for cold stem:["Ca"] atom, stem:["H"] atom and the trapped stem:["Sr"^+] ion,
** frequency values for new cold ion species including trapped stem:["Hg"^\+] ion, trapped stem:["In"^+] ion and trapped stem:["Yb"^+] ion,
** updated frequency values for stem:["Rb"]-stabilized lasers, stem:["I"_2]-stabilized Nd:YAG and stem:["He-Ne"] lasers, stem:["CH"_4]-stabilized stem:["He-Ne"] lasers and stem:["OsO"_4]-stabilized stem:["CO"_2] lasers at stem:[10 " "mu "m"],
** frequency values for standards relevant to the optical communications bands, including stem:["Rb-"] and stem:["C"_2"H"_2]-stabilized lasers.

&#x200c;. . .
____

[[cipm2002r2]]
=== Dose equivalent (PV, 70, 205)index-range:sievert_sv[(((sievert (Sv))))]

NOTE: See also _J. Radiol. Prot._, 2005, *25*, 97-100.

[[cipm2002r2r2]]
==== Recommendation 2
____

The International Committee for Weights and Measures,

*considering* that

* the current definition of the SI unit of dose equivalent (sievert) includes a factor "stem:[ii(N)]" (product of any other multiplying factors) stipulated by the International Commission on Radiological Protection (ICRP), and 
* both the ICRP and the International Commission on Radiation Units and Measurements (ICRU) have decided to delete this factor stem:[ii(N)] as it is no longer deemed to be necessary, and 
* the current SI definition of stem:[ii(H)] including the factor stem:[ii(N)] is causing some confusion,

*decides* to change the explanation in the brochure "Le Système International d'Unités (SI)" to the following:

The quantity dose equivalent stem:[ii(H)] is the product of the ((absorbed dose)) stem:[ii(D)] of ((ionizing radiation)) and the dimensionless factor stem:[ii(Q)] (quality factor) defined as a function of linear energy transfer by the ICRU:

[stem%unnumbered]
++++
ii(H) = ii(Q) * ii(D).
++++


Thus, for a given radiation, the numerical value of stem:[ii(H)] in joules(((joule (J)))) per kilogram may differ from that of stem:[ii(D)] in joules per kilogram depending on the value of stem:[ii(Q)].

The Committee further *decides* to maintain the final sentence in the explanation as follows:
(((gray (Gy))))(((joule (J))))

In order to avoid any risk of confusion between the ((absorbed dose)) stem:[ii(D)] and the dose equivalent stem:[ii(H)], the special names for the respective units should be used, that is, the name gray should be used instead of joules per kilogram for the unit of ((absorbed dose)) stem:[ii(D)] and the name sievert instead of joules per kilogram for the unit of dose equivalent stem:[ii(H)]. [[sievert_sv]]
____
