[[cipm2003]]
== CIPM, 2003

[[cipm2003r1]]
=== {blank}

[.variant-title,type=quoted]
*Revision of the Mise en Pratique list of recommended radiations* (PV, *71*, 146 and _Metrologia_, 2004, *41*, 99-100)

[[cipm2003r1r1]]
==== Recommendation 1
____

The International Committee for Weights and Measures,

*considering* that

* improved frequency values for radiations of some high-stability cold ion standards already documented in the recommended radiations list have recently become available;
* improved frequency values for the infra-red gas-cell-based optical frequency standard in the optical telecommunications region, already documented in the recommended radiations list, have been determined;
* femtosecond comb-based frequency measurements for certain iodine gas-cell standards on the subsidiary recommended source list have recently been made for the first time, leading to significantly reduced uncertainty;

*proposes* that the _recommended radiation_ list be revised to include the following:

* updated frequency values for the single trapped ^88^Sr^\+^ ion quadrupole transition and the single trapped ^171^Yb^+^ octupole transition;
* an updated frequency value for the stem:["C"_2"H"_2]-stabilized standard at stem:[1.54 "unitsml(um)"];
* updated frequency values for the stem:["I"_2]-stabilized standards at stem:[543 "unitsml(nm)"] and stem:[515 "unitsml(nm)"].
____