[[cgpm22nd2003]]
[%unnumbered]
== 22nd CGPM, 2003

[[cgpm22nd2003r10]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Symbol for the ((decimal marker))* (<<CR381>> and _Metrologia_, 2004, *41*, 104)

[[cgpm22nd2003r10r10]]
==== Resolution 10
____

The 22nd General Conference,

*considering* that

* a principal purpose of the International System of Units (SI) is to enable values of quantities to be expressed in a manner that can be readily understood throughout the world,
* the value of a quantity is normally expressed as a number times a unit,
* often the number in the expression of the value of a quantity contains multiple digits with an integral part and a decimal part,
* in Resolution 7 of the 9th General Conference, 1948, it is stated that "In numbers, the comma (French practice) or the dot (British practice) is used only to separate the integral part of numbers from the decimal part",
* following a decision of the International Committee made at its 86th meeting (1997), the International Bureau of Weights and Measures now uses the dot (point on the line) as the ((decimal marker)) in all the English language versions of its publications, including the English text of the SI Brochure (the definitive international reference on the SI), with the comma (on the line) remaining the ((decimal marker)) in all of its French language publications,
* however, some international bodies use the comma on the line as the ((decimal marker)) in their English language documents,
* furthermore, some international bodies, including some international standards organizations, specify the ((decimal marker)) to be the comma on the line in all languages,
* the prescription of the comma on the line as the ((decimal marker)) is in many languages in conflict with the customary usage of the point on the line as the ((decimal marker)) in those languages,
* in some languages that are native to more than one country, either the point on the line or the comma on the line is used as the ((decimal marker)) depending on the country, while in some countries with more than one native language, either the point on the line or comma on the line is used depending on the language,

*declares* that the symbol for the ((decimal marker)) shall be either the point on the line or the comma on the line,

*reaffirms* that "Numbers may be divided in groups of three in order to facilitate reading; neither dots nor commas are ever inserted in the spaces between groups", as stated in Resolution 7 of the 9th CGPM, 1948.
____