[[cipm2005]]
[%unnumbered]
== CIPM, 2005

[[cipm2005r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Clarification of the definition of the kelvin, unit of thermodynamic temperature* (<<PV73_2>> and <<Met_43_1_175,_Metrologia_, 2006, *43*, 177-178>>)

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).

[[cipm2005r2r2]]
==== Recommendation 2
____

The International Committee for Weights and Measures (CIPM),
(((digits in groups of three, grouping digits))) (((kelvin (stem:["unitsml(K)"])))) (((thermodynamic temperature)))

*considering*

* that the kelvin, unit of thermodynamic temperature, is defined as the fraction stem:[1//273.16] of the thermodynamic temperature of the ((triple point of water)),
* that the temperature of the triple point depends on the relative amount of isotopes of hydrogen and oxygen present in the sample of water used,
* that this effect is now one of the major sources of the observed variability between different realizations of the water triple point,

*decides*
(((mole (stem:["unitsml(mol)"]))))
((("water, isotopic composition")))

* that the definition of the kelvin refer to water of a specified isotopic composition,
* that this composition be:
+
--
[align=left]
stem:[0.00015576 text( mole of ) ^2"H" text( per mole of ) ^1"H"], +
stem:[0.0003799 text( mole of ) ^(17)"O" text( per mole of ) ^(16)"O"], and +
stem:[0.0020052 text( mole of ) ^(18)"O" text( per mole of ) ^(16)"O"],

which is the composition of the International Atomic Energy Agency reference material Vienna Standard Mean Ocean Water (VSMOW), as recommended by ((IUPAC)) in "Atomic Weights of the Elements: Review 2000".
--

* that this composition be stated in a note attached to the definition of the kelvin in the SI brochure as follows:
+
--
"This definition refers to water having the isotopic composition defined exactly by the following amount of substance ratios: stem:[0.00015576] mole of ^2^H per mole of ^1^H, stem:[0.0003799] mole of ^17^O per mole of ^16^O and stem:[0.0020052] mole of ^18^O per mole of ^16^O".
--
____


[[cipm2005r3]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Revision of the _Mise en pratique_ list of recommended radiations* (<<PV73_3>> and <<Met_43_1_175,_Metrologia_, 2006, *43*, 178>>)

[[cipm2005r3r3]]
==== Recommendation 3
____

The International Committee for Weights and Measures (CIPM),

*considering* that:

* improved frequency values for radiations of some high-stability cold ion and cold atom standards already documented in the recommended radiations list have recently become available;
* improved frequency values for the infra-red gas-cell-based optical frequency standard in the optical telecommunications region, already documented in the recommended radiations list, have been determined;
* improved frequency values for certain iodine gas-cell standard, already documented in the subsidiary recommended source list, have been determined;
* frequencies of new cold atoms, of atoms in the near-infrared region and of molecules in the optical telecommunications region have been determined by femtosecond comb-based frequency measurements for the first time;

*decides* that the list of _recommended radiations_ be revised to include the following:

* updated frequency values for the single trapped ^88^Sr^\+^ ion quadrupole transition, the single trapped ^199^Hg^+^ quadrupole transition and the single trapped ^171^Yb^+^ quadrupole transition;
* an updated frequency value for the stem:["Ca"] atom transition;
* an updated frequency value for the stem:["C"_2"H"_2]-stabilized standard at stem:[1.54 "unitsml(um)"];
* an updated frequency value for the stem:["I"_2]-stabilized standard at stem:[515 "unitsml(nm)"];
* the addition of the ^87^Sr atom transition at stem:[698 "unitsml(nm)"];
* the addition of the ^87^Rb atom two-photon transitions at stem:[760 "unitsml(nm)"];
* the addition of the ^12^C~2~H~2~ (stem:["v"_1 + "v"_3]) band and the ^13^C~2~H~2~ (stem:["v"_1 + "v"_3]) and (stem:["v"_1 + "v"_3 + "v"_4 + "v"_5]) bands at stem:[1.54 "unitsml(um)"].
____
