[[cipm2006]]
[%unnumbered]
== CIPM, 2006

[[cipm2006r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Concerning secondary representations of the second* (<<PV74,page=249>> and _Metrologia_, 2007, *44*, 97) (((second (stem:["unitsml(s)"]))))

[[cipm2006r1r1]]
==== Recommendation 1
____

The International Committee for Weights and Measures (CIPM),

*considering* that
(((second (stem:["unitsml(s)"]))))

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre(((metre (stem:["unitsml(m)"])))) and secondary representations of the second" shall be established,
* the CCL/CCTF Joint Working Group (JWG) on the _Mise en Pratique_ of the Definition of the Metre and the Secondary Representations of the Second in its meeting at the International Bureau of Weights and Measures (BIPM) in September 2005 discussed possible candidates to be included in this list for secondary representations of the second,
* the CCL/CCTF JWG reviewed and updated the values for the stem:["Hg"] ion, stem:["Sr"] ion, stem:["Yb"] ion, and the stem:["Sr"] neutral atom transition frequencies in its session in September 2006,
* the CCTF in its Recommendation CCTF 1 (2004) already recommended the unperturbed ground-state hyperfine quantum transition frequency of ^87^Rb as a secondary representation of the second;

*recommends* that the following transition frequencies shall be used as secondary representations of the second and be included into the new list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second"

* the unperturbed ground-state hyperfine quantum transition of ^87^Rb with a frequency of stem:[f_("Rb")^(87) = 6834682610.904324 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[3 xx 10^(−15)], 
* the unperturbed optical stem:[5"s" text( )^2ii(S)_(1//2) - 4"d " text()^2"D"_(5//2)] transition of the ^88^Sr^\+^ ion with a frequency of stem:[f^(88)"Sr"^+ = 444779044095484 "unitsml(Hz)"] and a relative uncertainty of stem:[7 xx 10^(−15)],
* the unperturbed optical stem:[5"d"^(10)" "6"s " text()^2"S"_(1//2)" "(ii(F) = 0) - 5"d"^9" "6"s"^2" "text()^2"D"_(5//2)" "(ii(F) = 2)] transition of the ^199^Hg^\+^ ion with a frequency of stem:[f^(199)Hg^+ = 1064721609899145 "unitsml(Hz)"] and a relative standard uncertainty of stem:[3 xx 10^(−15)],
* the unperturbed optical stem:[6"s " text()^2"S"_(1//2)" "(ii(F) = 0) - 5"d " text()^2"D"_(3//2)" "(ii(F) = 2)] transition of the ^171^Yb^\+^ ion with a frequency of stem:[f^(171)Yb^+ = 688358979309308 "unitsml(Hz)"] and a relative standard uncertainty of stem:[9 xx 10^(−15)],
* the unperturbed optical transition stem:[5"s"^2" "text()^1"S"_0 - 5"s " 5"p " text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[f_("Sr")^(87) = 429228004229877 "unitsml(Hz)"] and a relative standard uncertainty of stem:[1.5 xx 10^(−14)].
____
