[[cipm2007]]
== CIPM, 2007

[[cipm2007r1]]
=== Revision of the Mise en pratique list of recommended radiations (PV, 75, 185)

[[cipm2007r1r1]]
==== Recommendation 1
____

The International Committee for Weights and Measures,

*considering that*:

* improved frequency values of molecules in the optical telecommunications region, already documented in the list of standard frequencies, have been determined by femtosecond comb-based frequency measurements; 
* frequencies of molecules in the optical telecommunications region have been determined by femtosecond comb-based frequency measurements for the first time; 
* frequencies of certain iodine gas-cell absorptions close to the stem:[532 " ""unitsml(nm)"] optical frequency standard have been determined by femtosecond comb-based frequency measurements for the first time; 

*proposes* that the list of standard frequencies be revised to include the following:

* an updated list of frequency values for the ^12^C~2~H~2~ stem:[(ii(nu)_1 + ii(nu)_3)] band at stem:[1.54 " " mu "unitsml(m)"];
* the addition of frequency values for the ^12^C~2~HD stem:[(2ii(nu)_1)] band at stem:[1.54 " " mu "unitsml(m)"];
* the addition of frequency values for the hyperfine components of the P(142) 37-0, R(121) 35-0 and R(85) 33-0 iodine transitions at stem:[532 " ""unitsml(nm)"].
____
