[[cgpm23rd2007]]
== 23rd CGPM, 2007

[[cgpm23rd2007r9]]
=== On the revision of the mise en pratique of the definition of the metre and the development of new optical frequency standards (CR, 431)

[[cgpm23rd2007r9r9]]
==== Resolution 9
____

The 23rd General Conference,

*considering that:*

* there have been rapid and important improvements in the performance of optical frequency standards,
* femtosecond comb techniques are now used routinely for relating optical and microwave radiations at a single location,
* National Metrology Institutes (NMIs) are working on comparison techniques for optical frequency standards over short distances,
* remote comparison techniques need to be developed at an international level so that optical frequency standards can be compared,

*welcomes*

* the activities of the Joint Working Group of the Consultative Committee for Length and the Consultative Committee for Time and Frequency to review the frequencies of optically-based representations of the second,
* the additions to the _mise en pratique_ of the definition of the metre and to the list of recommended radiations made by the International Committee in 2002, 2003, 2005, 2006, and 2007,
* the initiative taken by the International Bureau of Weights and Measures (BIPM) to raise the issue of how to compare optical frequency standards,

*recommends that:*

* NMIs commit resources to the development of optical frequency standards and their comparison,
* the BIPM works toward the coordination of an international project with the participation of NMIs, oriented to the study of the techniques which could serve to compare optical frequency standards.
____

[[cgpm23rd2007r10]]
=== Clarification of the definition of the kelvin, unit of thermodynamic temperature (CR, 432)

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>).

[[cgpm23rd2007r10r10]]
==== Resolution 10
____

The 23rd General Conference,

*considering*

* that the kelvin, unit of thermodynamic temperature, is defined as the fraction stem:[1//273.16] of the thermodynamic temperature of the triple point of water,
* that the temperature of the triple point depends on the relative amount of isotopes of hydrogen and oxygen present in the sample of water used,
* that this effect is now one of the major sources of the observed variability between different realizations of the water triple point,

*notes and welcomes* the decision by the International Committee for Weights and Measures in October 2005, on the advice of the Consultative Committee for Thermometry, that

[align=left]
* the definition of the kelvin refers to water of a specified isotopic composition,
* this composition be:
+
--
[align=left]
stem:[0.00015576 text( mole of ) ^2"H" text( per mole of ) ^1"H"], +
stem:[0.0003799 text( mole of ) ^(17)"O" text( per mole of ) ^(16)"O"], and +
stem:[0.0020052 text( mole of ) ^(18)"O" text( per mole of ) ^(16)"O"],

which is the composition of the International Atomic Energy Agency reference material Vienna Standard Mean Ocean Water (VSMOW), as recommended by the International Union of Pure and Applied Chemistry in "Atomic Weights of the Elements: Review 2000",
--
* this composition be stated in a note attached to the definition of the kelvin in the SI Brochure as follows:
+
--
"This definition refers to water having the isotopic composition defined by the following amount-of-substance ratios: stem:[0.00015576] mole of ^2^H per mole of ^1^H, stem:[0.0003799] mole of ^17^O per mole of ^16^O and stem:[0.0020052] mole of ^18^O per mole of ^16^O".
--
____

[[cgpm23rd2007r12]]
=== On the possible redefinition of certain base units of the International System of Units (SI) (CR, 434)

NOTE: The 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>) finally approved the revision of the SI.

[[cgpm23rd2007r12r12]]
==== Resolution 12
____

The 23rd General Conference,

*considering*

* that, for many years, National Metrology Institutes (NMIs) as well as the International Bureau of Weights and Measures (BIPM) have made considerable efforts to advance and improve the International System of Units (SI) by extending the frontiers of metrology so that the SI base units could be defined in terms of the invariants of nature - the fundamental physical constants,
* that, of the seven base units of the SI, only the kilogram is still defined in terms of a material artefact - the international prototype of the kilogram (2nd CGPM, 1889, 3rd CGPM, 1901) and that the definitions of the ampere, mole and candela depend on the kilogram,
* Resolution 7 of the 21st General Conference (1999) which recommended that "national laboratories continue their efforts to refine experiments that link the unit of mass to fundamental or atomic constants with a view to a future redefinition of the kilogram",
* the many advances, made in recent years, in experiments which relate the mass of the international prototype to the Planck constant stem:[h] or the Avogadro constant stem:[N_"A"],
* initiatives to determine the value of a number of relevant fundamental constants, including work to redetermine the Boltzmann constant stem:[k_"B"],
* that as a result of recent advances, there are significant implications for, and potential benefits from, redefinitions of the kilogram, the ampere, the kelvin and the mole,
* Recommendation 1 of the International Committee (C1-2005) at its meeting in October 2005, and various Recommendations of Consultative Committees on the subject of a redefinition of one or more of the base units of the SI,

*noting*

* that any changes in definitions of units of the SI must be constrained by self-consistency,
* that it is desirable that definitions of the base units should be easily understood,
* the work of the International Committee and the Consultative Committees,
* the need to monitor the results of relevant experiments,
* the importance of soliciting comments and contributions from the wider scientific and user communities, and
* the decision of the International Committee in 2005 to approve, in principle, the preparation of new definitions of the kilogram, ampere, kelvin and the possibility of redefining the mole,

*recommends* that National Metrology Institutes and the BIPM

* pursue the relevant experiments so that the International Committee can come to a view on whether it may be possible to redefine the kilogram, the ampere, the kelvin, and the mole using fixed values of the fundamental constants at the time of the 24th General Conference (2011),
* should, together with the International Committee, its Consultative Committees, and appropriate working groups, work on practical ways of realizing any new definitions based on fixed values of the fundamental constants, prepare a mise en pratique for each of them, and consider the most appropriate way of explaining the new definitions to users,
* initiate awareness campaigns to alert user communities to the possibility of redefinitions and that the technical and legislative implications of such redefinitions and their practical realizations be carefully discussed and considered,

*and requests* the International Committee to report on these issues to the 24th General Conference in 2011 and to undertake whatever preparations are considered necessary so that, if the results of experiments are found to be satisfactory and the needs of users met, formal proposals for changes in the definitions of the kilogram, ampere, the kelvin and mole can be put to the 24th General Conference.
____

