[[cipm2009]]
[%unnumbered]
== CIPM, 2009

[[cipm2009r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Updates to the list of standard frequencies* (<<PV77_2>>)

[[cipm2009r2r2]]
==== Recommendation 2
____

The International Committee for Weights and Measures (CIPM),

*considering* that
(((second (stem:["unitsml(s)"]))))

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre(((metre (stem:["unitsml(m)"])))) and secondary representations of the second" has been established;
* the CCL-CCTF Frequency Standards Working Group (FSWG) has reviewed several promising candidates for inclusion in the list;

*recommends*

that the following transition frequencies shall be included or updated in the list of recommended standard frequencies:

* the unperturbed optical transition stem:[5"s"^2" "text()^1"S"_0 - 5"s " 5"p " text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[f = 429228004229873.7 "unitsml(Hz)"] and a relative standard uncertainty of stem:[1 xx 10^(−15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[5"s"^2" "text()^1"S"_0 - 5"s " 5"p " text()^3"P"_0] of the ^88^Sr neutral atom with a frequency of stem:[f = 429228066418012 "unitsml(Hz)"] and a relative standard uncertainty of stem:[1 xx 10^(−14)];
* the unperturbed optical transition stem:[4"s " text()^2 "S"_(1//2) - 3"d " text()^2"D"_(5//2)] of the ^40^Ca^+^ ion with a frequency of stem:[f = 411042129776393 "unitsml(Hz)"] and a relative standard uncertainty of stem:[4 xx 10^(−14)];
* the unperturbed optical transition stem:[text()^2"S"_(1//2) (ii(F) = 0) - text()^2 ii(F)_(7//2)" "(ii(F) = 3," "m_"F" = 0)] of the ^171^Yb^+^ ion with a frequency of stem:[f = 642121496772657 "unitsml(Hz)"] and a relative standard uncertainty of stem:[6 xx 10^(−14)];
* the unperturbed optical transition stem:[6"s"^2" "text()^1"S"_0" "(ii(F) = 1//2) - 6"s " 6"p " text()^3 "P"_0" "(ii(F) = 1//2)] of the ^171^Yb neutral atom with a frequency of stem:[f = 518295836590864 "unitsml(Hz)"] and a relative standard uncertainty of stem:[1.6 xx 10^(−13)].
____
