== CIPM, 2009

=== Updates to the list of standard frequencies (PV, 77, 235)

____
[align=center]
*Recommendation 2*

The International Committee for Weights and Measures (CIPM),

*considering* that

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established; 
* the CCL-CCTF Frequency Standards Working Group (FSWG) has reviewed several promising candidates for inclusion in the list;

*recommends*

that the following transition frequencies shall be included or updated in the list of recommended standard frequencies:

* the unperturbed optical transition stem:[5"s"^2 text()^1"S"_0 – 5"s" 5"p" text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[f = 429" " 228 " " 004" " 229" " 873.7 " Hz"] and a relative standard uncertainty of stem:[1 times 10^(−15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[5"s"^2 text()^1"S"_0 – 5"s" 5"p" text()^3"P"_0] of the ^88^Sr neutral atom with a frequency of stem:[f = 429" " 228" " 066" " 418" " 012 " Hz"] and a relative standard uncertainty of stem:[1 times 10^(−14)];
* the unperturbed optical transition stem:[4"s" text()^2 "S"_(1text(/)2) – 3"d" text()^2"D"_(5text(/)2)] of the ^40^Ca^+^ ion with a frequency of stem:[f = 411" " 042 " " 129" " 776" " 393 " Hz"] and a relative standard uncertainty of stem:[4 times 10^(−14)];
* the unperturbed optical transition ^2^S~1/2~ stem:[(F = 0) – text()^2 F_(7text(/)2) (F = 3, m_F = 0)] of the ^171^Yb^+^ ion with a frequency of stem:[f = 642" " 121" " 496" " 772" " 657 " Hz"] and a relative standard uncertainty of stem:[6 times 10^(−14)]; 
* the unperturbed optical transition stem:[6"s"^2 text()^1"S"_0 (F = 1text(/)2) – 6"s" 6"p" text()^3 "P"_0 (F = 1text(/)2)] of the ^171^Yb neutral atom with a frequency of stem:[f = 518" " 295 " "836 " "590 " "864 " Hz"] and a relative standard uncertainty of stem:[1.6 times 10^(−13)].
____