[[cgpm24th2011]]
== 24th CGPM, 2011

[[cgpm24th2011r1]]
=== On the possible future revision of the International System of Units, the SI (CR, 532)

NOTE: The 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>) finally approved the revision of the SI.

[[cgpm24th2011r1r1]]
==== Resolution 1
____

The General Conference on Weights and Measures (CGPM), at its 24th meeting,

*considering*

* the international consensus on the importance, value, and potential benefits of a redefinition of a number of units of the International System of Units (SI),
* that the national metrology institutes (NMIs) as well as the International Bureau of Weights and Measures (BIPM) have rightfully expended significant effort during the last several decades to advance the International System of Units (SI) by extending the frontiers of metrology so that SI base units can be defined in terms of the invariants of nature - the fundamental physical constants or properties of atoms,
* that a prominent example of the success of such efforts is the current definition of the SI unit of length, the metre (17th meeting of the CGPM, 1983, Resolution 1), which links it to an exact value of the speed of light in vacuum stem:[c], namely, stem:[299792458 text( metre per second)],
* that of the seven base units of the SI, only the kilogram is still defined in terms of a material artefact, namely, the international prototype of the kilogram (1st meeting of the CGPM, 1889, 3rd meeting of the CGPM, 1901), and that the definitions of the ampere, mole and candela depend on the kilogram,
* that although the international prototype has served science and technology well since it was sanctioned by the CGPM at its 1st meeting in 1889, it has a number of important limitations, one of the most significant being that its mass is not explicitly linked to an invariant of nature and in consequence its long-term stability is not assured,
* that the CGPM at its 21st meeting in 1999 adopted Resolution 7 in which it recommended that "national laboratories continue their efforts to refine experiments that link the unit of mass to fundamental or atomic constants with a view to a future redefinition of the kilogram",
* that many advances have been made in recent years in relating the mass of the international prototype to the Planck constant stem:[h], by methods which include watt balances and measurements of the mass of a silicon atom,
* that the uncertainties of all SI electrical units realized directly or indirectly by means of the Josephson and quantum Hall effects together with the SI values of the Josephson and von Klitzing constants stem:[K_"J"] and stem:[R_"K"] could be significantly reduced if the kilogram were redefined so as to be linked to an exact numerical value of stem:[h], and if the ampere were to be redefined so as to be linked to an exact numerical value of the elementary charge stem:[e],
* that the kelvin is currently defined in terms of an intrinsic property of water that, while being an invariant of nature, in practice depends on the purity and isotopic composition of the water used,
* that it is possible to redefine the kelvin so that it is linked to an exact numerical value of the Boltzmann constant stem:[k],
* that it is also possible to redefine the mole so that it is linked to an exact numerical value of the Avogadro constant stem:[N_"A"], and is thus no longer dependent on the definition of the kilogram even when the kilogram is defined so that it is linked to an exact numerical value of stem:[h], thereby emphasizing the distinction between amount of substance and mass,
* that the uncertainties of the values of many other important fundamental constants and energy conversion factors would be eliminated or greatly reduced if stem:[h], stem:[e], stem:[k], and stem:[N_"A"] had exact numerical values when expressed in SI units,
* that the General Conference, at its 23rd meeting in 2007, adopted Resolution 12 in which it outlined the work that should be carried out by the NMIs, the BIPM and the International Committee for Weights and Measures (CIPM) together with its Consultative Committees (CCs) so that new definitions of the kilogram, ampere, kelvin, and mole in terms of fundamental constants could be adopted,
* that, although this work has progressed well, not all the requirements set out in Resolution 12 adopted by the General Conference at its 23rd meeting in 2007 have been satisfied and so the International Committee for Weights and Measures is not yet ready to make a final proposal,
* that, nevertheless, a clear and detailed explanation of what is likely to be proposed can now be presented,

*takes note* of the intention of the International Committee for Weights and Measures to propose a revision of the SI as follows:

* the International System of Units, the SI, will be the system of units in which:

** the ground state hyperfine splitting frequency of the caesium stem:[133] atom stem:[Delta nu](^133^Cs)~hfs~ is exactly stem:[9192631770 text( hertz)],
** the speed of light in vacuum stem:[c] is exactly stem:[299792458 text( metre per second)],
** the Planck constant stem:[h] is exactly stem:[6.62606"X" times 10^(−34) text( joule second)] footnote:[The stem:["X"] digit appearing in the expression of the constants indicates that this digit was unknown at the time of the resolution.],
** the elementary charge stem:[e] is exactly stem:[1.60217"X" times 10^(−19) text( coulomb)],
** the Boltzmann constant stem:[k] is exactly stem:[1.3806"X" xx 10^(−23) text( joule per kelvin)],
** the Avogadro constant stem:[N_"A"] is exactly stem:[6.02214"X" xx 10^(23) text( reciprocal mole)],
** the luminous efficacy stem:[K_("cd")] of monochromatic radiation of frequency stem:[540 xx 10^(12) " Hz"] is exactly stem:[683 text( lumen per watt)],

where

[lowerroman]
. the hertz, joule, coulomb, lumen, and watt, with unit symbols stem:["Hz", " J", " C", " lm"], and stem:["W"], respectively, are related to the units second, metre, kilogram, ampere, kelvin, mole, and candela, with unit symbols stem:["s", " m", " kg", " A", " K", " mol"], and stem:["cd"], respectively, according to stem:["Hz" = "s"^(−1), " J" = "m"^2 " kg s"^(−2), " C" = "s A", "lm" = "cd m"^2 " m"^(−2) = "cd sr"], and stem:["W" = "m"^2 " kg s"^(−3)],

. the symbol stem:["X"] in this Draft Resolution represents one or more additional digits to be added to the numerical values of stem:[h], stem:[e], stem:[k], and stem:[N_"A"], using values based on the most recent CODATA adjustment,

from which it follows that the SI will continue to have the present set of seven base units, in particular

* the kilogram will continue to be the unit of mass, but its magnitude will be set by fixing the numerical value of the Planck constant to be equal to exactly stem:[6.62606"X" xx 10^(−34)] when it is expressed in the SI unit stem:["m"^2 " kg s"^(−1)], which is equal to stem:["J s"],
* the ampere will continue to be the unit of electric current, but its magnitude will be set by fixing the numerical value of the elementary charge to be equal to exactly stem:[1.60217"X" xx 10^(−19)] when it is expressed in the SI unit stem:["s A"], which is equal to stem:["C"],
* the kelvin will continue to be the unit of thermodynamic temperature, but its magnitude will be set by fixing the numerical value of the Boltzmann constant to be equal to exactly stem:[1.3806"X" xx 10^(−23)] when it is expressed in the SI unit stem:["m"^2 " kg s"^(−2) " K"^(-1)], which is equal to stem:["J K"^(−1)],
* the mole will continue to be the unit of amount of substance of a specified elementary entity, which may be an atom, molecule, ion, electron, any other particle or a specified group of such particles, but its magnitude will be set by fixing the numerical value of the Avogadro constant to be equal to exactly stem:[6.02214"X" xx 10^(23)] when it is expressed in the SI unit stem:["mol"^(−1)].

The General Conference on Weights and Measures

*further notes* that since

* the new definitions of the kilogram, ampere, kelvin and mole are intended to be of the explicit-constant type, that is, a definition in which the unit is defined indirectly by specifying explicitly an exact value for a well-recognized fundamental constant,
* the existing definition of the metre is linked to an exact value of the speed of light in vacuum, which is also a well-recognized fundamental constant,
* the existing definition of the second is linked to an exact value of a well-defined property of the caesium atom, which is also an invariant of nature,
* although the existing definition of the candela is not linked to a fundamental constant, it may be viewed as being linked to an exact value of an invariant of nature,
* it would enhance the understandability of the International System if all of its base units were of similar wording,

the International Committee for Weights and Measures will also propose

the reformulation of the existing definitions of the second, metre and candela in completely equivalent forms, which might be the following:

* the second, symbol stem:["s"], is the unit of time; its magnitude is set by fixing the numerical value of the ground state hyperfine splitting frequency of the caesium stem:[133] atom, at rest and at a temperature of stem:[0 " K"], to be equal to exactly stem:[9192631770] when it is expressed in the SI unit stem:["s"^(−1)], which is equal to stem:["Hz"],
* the metre, symbol stem:["m"], is the unit of length; its magnitude is set by fixing the numerical value of the speed of light in vacuum to be equal to exactly stem:[299792458] when it is expressed in the SI unit stem:["m s"^(−1)],
* the candela, symbol stem:["cd"], is the unit of luminous intensity in a given direction; its magnitude is set by fixing the numerical value of the luminous efficacy of monochromatic radiation of frequency stem:[540 times 10^(12) " Hz"] to be equal to exactly stem:[683] when it is expressed in the SI unit stem:["m"^(−2) " kg"^(−1) " s"^3 " cd sr"], or stem:["cd sr W"^(−1)], which is equal to stem:["lm W"^(−1)].

In this way, the definitions of all seven base units will be seen to follow naturally from the set of seven constants given above.

In consequence, on the date chosen for the implementation of the revision of the SI:

* the definition of the kilogram in force since 1889 based upon the mass of the international prototype of the kilogram (1st meeting of the CGPM, 1889, 3rd meeting of the CGPM, 1901) will be abrogated,
* the definition of the ampere in force since 1948 (9th meeting of the CGPM, 1948) based upon the definition proposed by the International Committee (CIPM, 1946, Resolution 2) will be abrogated,
* the conventional values of the Josephson constant stem:[K_("J-90")] and of the von Klitzing constant stem:[R_("K-90")] adopted by the International Committee (CIPM, 1988, Recommendations 1 and 2) at the request of the General Conference (18th meeting of the CGPM, 1987, Resolution 6) for the establishment of representations of the volt and the ohm using the Josephson and quantum Hall effects, respectively, will be abrogated,
* the definition of the kelvin in force since 1967/68 (13th meeting of the CGPM, 1967/68, Resolution 4) based upon a less explicit, earlier definition (10th meeting of the CGPM, 1954, Resolution 3) will be abrogated,
* the definition of the mole in force since 1971 (14th meeting of the CGPM, 1971, Resolution 3) based upon a definition whereby the molar mass of carbon 12 had the exact value stem:[0.012 " kg mol"^(-1)] will be abrogated,
* the existing definitions of the metre, second and candela in force since they were adopted by the CGPM at its 17th (1983, Resolution 1), 13th (1967/68, Resolution 1) and 16th (1979, Resolution 3) meetings, respectively, will be abrogated.

The General Conference on Weights and Measures

*further notes* that on the same date

* the mass of the international prototype of the kilogram stem:[m(K)] will be stem:[1 " kg"] but with a relative uncertainty equal to that of the recommended value of stem:[h] just before redefinition and that subsequently its value will be determined experimentally,
* that the magnetic constant (permeability of vacuum) stem:[mu_0] will be stem:[4pi times 10^(−7) " H m"^(−1)] but with a relative uncertainty equal to that of the recommended value of the fine-structure constant stem:[alpha] and that subsequently its value will be determined experimentally,
* that the thermodynamic temperature of the triple point of water stem:[T_("TPW")] will be stem:[273.16 " K"] but with a relative uncertainty equal to that of the recommended value of stem:[k] just before redefinition and that subsequently its value will be determined experimentally,
* that the molar mass of carbon 12 stem:[M(""^{12}"C")] will be stem:[0.012 " kg mol"^(−1)] but with a relative uncertainty equal to that of the recommended value of stem:[N_"A"h] just before redefinition and that subsequently its value will be determined experimentally.

The General Conference on Weights and Measures

*encourages*

* researchers in national metrology institutes, the BIPM and academic institutions to continue their efforts and make known to the scientific community in general and to CODATA in particular, the outcome of their work relevant to the determination of the constants stem:[h], stem:[e], stem:[k], and stem:[N_"A"], and
* the BIPM to continue its work on relating the traceability of the prototypes it maintains to the international prototype of the kilogram, and in developing a pool of reference standards to facilitate the dissemination of the unit of mass when redefined,

*invites*

* CODATA to continue to provide adjusted values of the fundamental physical constants based on all relevant information available and to make the results known to the International Committee through its Consultative Committee for Units since these CODATA values and uncertainties will be those used for the revised SI,
* the CIPM to make a proposal for the revision of the SI as soon as the recommendations of Resolution 12 of the 23rd meeting of the General Conference are fulfilled, in particular the preparation of _mises en pratique_ for the new definitions of the kilogram, ampere, kelvin and mole,
* the CIPM to continue its work towards improved formulations for the definitions of the SI base units in terms of fundamental constants, having as far as possible a more easily understandable description for users in general, consistent with scientific rigour and clarity,
* the CIPM, the Consultative Committees, the BIPM, the OIML and National Metrology Institutes significantly to increase their efforts to initiate awareness campaigns aimed at alerting user communities and the general public to the intention to redefine various units of the SI and to encourage consideration of the practical, technical, and legislative implications of such redefinitions, so that comments and contributions can be solicited from the wider scientific and user communities.
____


[[cgpm24th2011r8]]
=== On the revision of the mise en pratique of the metre and the development of new optical frequency standards (CR, 546)

[[cgpm24th2011r8r8]]
==== Resolution 8
____

The General Conference on Weight and Measures (CGPM), at its 24th meeting,

*considering* that

* there have been rapid and important improvements in the performance of optical frequency standards,
* national metrology institutes are working on comparison techniques for optical frequency standards over short distances,
* remote comparison techniques need to be developed at an international level so that optical frequency standards can be compared,

*welcomes*

* the activities of the joint working group of the CCTF and the CCL to review the frequencies of optically-based representations of the second,
* the additions made by the CIPM in 2009 to the common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second",
* the establishment of a CCTF working group on Coordination of the Development of Advanced Time and Frequency Transfer Techniques,

*recommends* that

* NMIs commit resources to the development of optical frequency standards and their comparison,
* the BIPM supports the coordination of an international project with the participation of NMIs, oriented to the study of the techniques which could serve to compare optical frequency standards.
____
