[[cipm2013]]
[%unnumbered]
== CIPM, 2013

[[cipm2013r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Updates to the list of standard frequencies* (<<PV81>>)

[[cipm2013r1r1]]
==== Recommendation 1
____

The International Committee for Weights and Measures (CIPM),

*considering* that
(((second (stem:["unitsml(s)"]))))

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established,
* the CCL-CCTF Frequency Standards Working Group (FSWG) has reviewed several candidates for inclusion into the list,

*recommends* the following changes to the list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second":

* that the following transition frequency be added to the list:

** the unperturbed optical transition stem:[6"s"^2" "text()^1S_0 - 6"s " 6"p " text()^3"P"_0] of the ^199^Hg neutral atom with a frequency of stem:[1128575290808162 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.7 xx 10^(-14)];

* that the following transition frequencies be updated in the list:

** the unperturbed optical transition stem:[4"s " text()^2"S"_(1//2) - 3"d " text()^2"D"_(5//2)] of the ^40^Ca^+^ ion with a frequency of stem:[411042129776395 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.5 xx 10^(-14)];
** the unperturbed optical transition stem:[1"S" - 2"S"] of the ^1^H neutral atom with a frequency of stem:[1233030706593518 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.2 xx 10^(-14)];
+
--
NOTE: This frequency corresponds to half of the energy difference between the stem:[1"S"] and stem:[2"S"] states;
--
* that the following transition frequencies be updated in the list and endorsed as secondary representations of the second:

** the unperturbed optical transition stem:[6"s " text()^2 "S"_(1//2) - 4"f"^(13) " " 6"s"^2" "text()^2"F"_(7//2)] of the ^171^Yb^+^ ion (octupole) with a frequency of stem:[642121496772645.6 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.3 xx 10^(-15)];
** the unperturbed optical transition stem:[6"s"^2" "text()^1"S"_0 - 6"s " 6"p " text()^3"P"_0] of the ^171^Yb neutral atom with a frequency of stem:[518295836590865.0 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[2.7 xx 10^(-15)];

* that the following transition frequency be added to the list and as a secondary representation of the second:

** the unperturbed optical transition stem:[3"s"^2" "text()^1"S"_0 - 3"s " 3"p " text()^3"P"_0] of the ^27^Al^+^ ion with a frequency of stem:[1121015393207857.3 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.9 xx 10^(-15)];

* that the following transition frequencies be updated in the list and as secondary representations of the second:

** the unperturbed optical transition stem:[5"d"^(10) " " 6"s " text()^2"S"_(1//2) - 5"d"^9 " " 6"s"^2" "text()^2"D"_(5//2)] of the ^199^Hg^+^ ion with a frequency of stem:[1064721609899145.3 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.9 xx 10^(-15)];
** the unperturbed optical transition stem:[6"s " text()^2"S"_(1//2)" "(ii(F) = 0," "m_"F" = 0) - 5"d " text()^2"D"_(3//2)" "(ii(F) = 2," "m_"F" = 0)] of the ^171^Yb^+^ ion (quadrupole) with a frequency of stem:[688358979309307.1 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[3 xx 10^(-15)];
** the unperturbed optical transition stem:[5"s " text()^2"S"_(1//2) - 4"d " text()^2"D"_(5//2)] of the ^88^Sr^+^ ion with a frequency of stem:[444779044095485.3 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[4.0 xx 10^(-15)];
** the unperturbed optical transition stem:[5"s"^2" "text()^1"S"_0 - 5"s "5"p " text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[429228004229873.4 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1 xx 10^(-15)];

* that the following transition frequency be updated as a secondary representation of the second:

** the unperturbed ground - state hyperfine transition of ^87^Rb with a frequency of stem:[6834682610.904312 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.3 xx 10^(-15)].

NOTE: The value of the estimated standard uncertainty is assumed to correspond to a confidence level of 68 %. However, given the very limited number of available data there is a possibility that in hindsight this might not prove to be exact.
____
