== CIPM, 2013

=== Updates to the list of standard frequencies (PV, 81, 144)

[align=center]
*Recommendation 1*

The International Committee for Weights and Measures (CIPM),

*considering* that

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established, 
* the CCL-CCTF Frequency Standards Working Group (FSWG) has reviewed several candidates for inclusion into the list, 

*recommends* the following changes to the list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second":

* that the following transition frequency be added to the list: 

** the unperturbed optical transition stem:[6"s"^2 text()^1S_0 – 6"s " 6"p" text()^3"P"_0] of the ^199^Hg neutral atom with a frequency of stem:[1 " "128 " "575 " "290 " "808 " "162 " Hz"] and an estimated relative standard uncertainty of stem:[1.7 times 10^(−14)];

* that the following transition frequencies be updated in the list: 

** the unperturbed optical transition stem:[4"s" text()^2"S"_(1text(/)2) – 3"d" text()^2"D"_(5text(/)2)] of the ^40^Ca^+^ ion with a frequency of stem:[411 " "042 " "129 " "776 " "395 " Hz"] and an estimated relative standard uncertainty of stem:[1.5 times 10^(−14)]; 
** the unperturbed optical transition stem:[1"S" – 2"S"] of the ^1^H neutral atom with a frequency of stem:[1 " "233 " "030 " "706 " "593 " "518 " Hz"] and an estimated relative standard uncertainty of stem:[1.2 times 10^(−14)];
+
--
NOTE: This frequency corresponds to half of the energy difference between the stem:[1"S"] and stem:[2"S"] states;
--
* that the following transition frequencies be updated in the list and endorsed as secondary representations of the second:

** the unperturbed optical transition stem:[6"s" text()^2 "S"_(1text(/)2) – 4"f" text()^(13)6"s"^2 text()^2"F"_(7text(/)2)] of the ^171^Yb^+^ ion (octupole) with a frequency of stem:[642 " "121 " "496 " "772 " "645.6 " Hz"] and an estimated relative standard uncertainty of stem:[1.3 times 10^(−15)];
** the unperturbed optical transition stem:[6"s"^2 text()^1"S"_0 – 6"s " 6"p" text()^3"P"0] of the ^171^Yb neutral atom with a frequency of stem:[518 " "295 " "836 " "590 " "865.0 " Hz"] and an estimated relative standard uncertainty of stem:[2.7 times 10^(−15)]; 

* that the following transition frequency be added to the list and as a secondary representation of the second:

** the unperturbed optical transition stem:[3"s"^2 text()^1"S"_0 – 3"s " 3"p" text()^3"P"_0] of the ^27^Al^+^ ion with a frequency of stem:[1 " "121 " "015 " "393 " "207 " "857.3 " Hz"] and an estimated relative standard uncertainty of stem:[1.9 times 10^(−15)];

* that the following transition frequencies be updated in the list and as secondary representations of the second:

** the unperturbed optical transition stem:[5"d" text()^(10)6"s" text()^2"S"_(1text(/)2) – 5"d" text()^96"s"^2 text()^2"D"_(5text(/)2)] of the ^199^Hg^+^ ion with a frequency of stem:[1 " "064 " "721 " "609 " "899 " "145.3 " Hz"] and an estimated relative standard uncertainty of stem:[1.9 times 10^(−15)];
** the unperturbed optical transition stem:[6"s" text()^2"S"_(1text(/)2) (F = 0, m_F = 0) – 5"d" text()^2"D"_(3text(/)2) (F = 2, m_F = 0)] of the ^171^Yb^+^ ion (quadrupole) with a frequency of stem:[688 " "358 " "979 " "309 " "307.1 " Hz"] and an estimated relative standard uncertainty of stem:[3 times 10^(−15)];
** the unperturbed optical transition stem:[5"s" text()^2"S"_(1text(/)2) – 4"d" text()^2"D"_(5text(/)2)] of the ^88^Sr^+^ ion with a frequency of stem:[444 " "779 " "044 " "095 " "485.3 " Hz"] and an estimated relative standard uncertainty of stem:[4.0 times 10^(−15)]; 
** the unperturbed optical transition stem:[5"s"^2 text()^1"S"_0 – 5"s"5"p" text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[429 " " 228 " "004 " "229 " "873.4 " Hz"] and an estimated relative standard uncertainty of stem:[1 times 10^(−15)];

* that the following transition frequency be updated as a secondary representation of the second:

** the unperturbed ground - state hyperfine transition of ^87^Rb with a frequency of stem:[6 " "834 " "682 " "610.904 " "312 " Hz"] and an estimated relative standard uncertainty of stem:[1.3 times 10^(−15)]. 

NOTE: The value of the estimated standard uncertainty is assumed to correspond to a confidence level of 68 %. However, given the very limited number of available data there is a possibility that in hindsight this might not prove to be exact.