[[cgpm25th2014]]
== 25th CGPM, 2014

[[cgpm25th2014r1]]
=== On the future revision of the International System of Units, the SI (CR, 416 and _Metrologia_, 2015, 52, 155)

NOTE: The 26th CGPM in 2018 (<<cgpm26th2018r1r1,Resolution 1>>) finally approved the revision of the SI.

[[cgpm25th2014r1r1]]
==== Resolution 1
____

The General Conference on Weights and Measures (CGPM), at its 25th meeting,

*recalling*

* Resolution 1 adopted by the CGPM at its 24th meeting (2011), which takes note of the intention of the International Committee for Weights and Measures (CIPM) to propose a revision of the SI that links the definitions of the ((kilogram)), ampere(((ampere (stem:["unitsml(A)"])))), kelvin, and mole to exact numerical values of the ((Planck constant)) stem:[h], ((elementary charge)) stem:[e], ((Boltzmann constant)) stem:[k], and ((Avogadro constant)) stem:[ii(N)_"A"], respectively, and which revises the way the SI is defined including the wording of the definitions of the SI units for time, length, ((mass)), ((electric current)), thermodynamic temperature, amount of substance, and ((luminous intensity)) so that the reference constants on which the SI is based are clearly apparent,
* the many benefits summarized in Resolution 1 that will accrue to science, technology, industry, and commerce from such a revision, especially from linking the ((kilogram)) to an invariant of nature rather than to the mass of a material artefact, thereby ensuring its long-term stability,
* Resolution 7 adopted by the CGPM at its 21st meeting (1999), which encourages work at the National Metrology Institutes (NMIs) that can lead to such a redefinition of the ((kilogram)),
* Resolution 12 adopted by the CGPM at its 23rd meeting (2007), which outlines the work that should be carried out by the NMIs, the International Bureau of Weights and Measures (BIPM), and the CIPM together with its Consultative Committees (CCs) that could enable the planned revision of the SI to be adopted by the CGPM,

*considering that* there has been significant progress in completing the necessary work, including

* the acquisition of relevant data and their analysis by the Committee on Data for Science and Technology (CODATA) to obtain the required values of stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"],
* establishment by the BIPM of an ensemble of reference standards of mass to facilitate the dissemination of the unit of mass in the revised SI,
* the preparation of mises-en-pratique for the new definitions of the ((kilogram)), ampere(((ampere (stem:["unitsml(A)"])))), kelvin, and mole,

*noting that* further work by the Consultative Committee for Units (CCU), the CIPM, the BIPM, the NMIs and the CCs should focus on

* awareness campaigns to alert user communities as well as the general public to the proposed revision of the SI,
* the preparation of the 9th edition of the SI Brochure that presents the revised SI in a way that can be understood by a diverse readership without compromising scientific rigour,

*that* despite this progress the data do not yet appear to be sufficiently robust for the CGPM to adopt the revised SI at its 25th meeting,

*encourages*

* continued effort in the NMIs, the BIPM, and academic institutions to obtain data relevant to the determination of stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"] with the requisite uncertainties,
* the NMIs to continue acting through the CCs to discuss and review this data,
* the CIPM to continue developing a plan to provide the path via the Consultative Committees and the CCU for implementing Resolution 1 adopted by the CGPM at its 24th meeting (2011), and
* continued effort by the CIPM, together with its Consultative Committees, the NMIs, the BIPM, and other organizations such as the International Organization of Legal Metrology (OIML)(((OIML))), to complete all work necessary for the CGPM at its 26th meeting to adopt a resolution that would replace the current SI with the revised SI, provided the amount of data, their uncertainties, and level of consistency are deemed satisfactory.
____

