[[cipm2015]]
[%unnumbered]
== CIPM, 2015

[[cipm2015r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Updates to the list of standard frequencies* (<<PV83>>)

NOTE: Further updates are available on the BIPM website.

[[cipm2015r2r2]]
==== Recommendation 2
____

The International Committee for Weights and Measures (CIPM),

*considering*
(((second (stem:["unitsml(s)"]))))

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established, 
* the CCL-CCTF Frequency Standards Working Group (WGFS) has reviewed several candidates for updating the list,

*recommends*

that the following transition frequencies shall be updated in the list of recommended values of standard frequencies:
(((second (stem:["unitsml(s)"]))))

* the unperturbed optical transition stem:[6"s"^2" "text()^1"S"_0 - 6"s "6"p " text()^3"P"_0] of the ^199^Hg neutral atom with a frequency of stem:[f_(199"Hg") = 1128575290808154.8 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[6 xx 10^(-16)]; 
* the unperturbed optical transition stem:[6"s " text()^2"S"_(1//2) - 4"f"^(13)" "6"s"^2" "text()^2"F"_(7//2)] of the ^171^Yb^\+^ ion with a frequency of stem:[f_(171"Yb+") "(octupole)" = 642121496772645.0 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[6 xx 10^(-16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[6"s " text()^2"S"_(1//2)" "(ii(F) = 0," "m_"F" = 0) - 5"d " text()^2"D"_(3//2)" "(ii(F) = 2," "m_"F" = 0)] of the ^171^Yb^\+^ ion with a frequency of stem:[f_(171"Yb+") "(quadrupole)" = 688358979309308.3 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[6 xx 10^(-16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[5"s " text()^2"S"_(1//2) - 4"d " text()^2"D"_(5//2)] of the ^88^Sr^\+^ ion with a frequency of stem:[f_(88"Sr+") = 444779044095486.6 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.6 xx 10^(-15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[4"s " text()^2"S"_(1//2) - 3"d " text()^2"D"_(5//2)] of the ^40^Ca^\+^ ion with a frequency of stem:[f_(40"Ca+") = 411042129776398.4 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[1.2 times 10^(-14)];
* the unperturbed optical transition stem:[1"S" - 2"S"] of the ^1^H neutral atom with a frequency of stem:[f_(1"H") = 1233030706593514 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[9 xx 10^(-15)].
+
--
NOTE: This frequency corresponds to half of the energy difference between the stem:[1"S"] and stem:[2"S"] states;
--
* the unperturbed optical transition stem:[5"s"^2" "text()^1"S"_0 - 5"s "5"p " text()^3"P"_0] of the ^87^Sr neutral atom with a frequency of stem:[f_(87"Sr") = 429228004229873.2 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[5 times 10^(-16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed optical transition stem:[6"s"^2" "text()^1"S"_0 - 6"s "6"p " text()^3"P"_0] of the ^171^Yb neutral atom with a frequency of stem:[f_(171"Yb") = 518295836590864.0 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[2 xx 10^(-15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed ground-state hyperfine transition of ^87^Rb with a frequency of stem:[f_(87"Rb") = 6834682610.904310 "unitsml(Hz)"] and an estimated relative standard uncertainty of stem:[7 xx 10^(-16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second). 

and also *recommends*

that the following transition frequencies shall be included in the list of recommended values of standard frequencies:

* Absorbing molecule ^127^I~2~, saturated absorption stem:["a"_1] component, stem:["R"(36) 32-0] transition.
+
--
[align=left]
The values:: stem:[f_("a"1) = 564074632.42 "unitsml(MHz)"] +
stem:[lambda_("a"1) = 531476582.65 "unitsml(fm)"]
--

with an estimated relative standard uncertainty of stem:[1 xx 10^(-10)] apply to the radiation of a frequency-doubled diode DFB laser, stabilized with an iodine cell external to the laser.

* Absorbing atom ^87^Rb stem:[5"S"_(1//2) - 5"P"_(3//2)] crossover between the stem:["d"] and stem:["f"] hyperfine components of the saturated absorption at stem:[780 "unitsml(nm)"] (D2 transition)
+
--
[align=left]
The values:: stem:[f_("d/f crossover") = 384227981.9 "unitsml(MHz)"] +
stem:[lambda_("d/f crossover") = 780246291.6 "unitsml(fm)"]
--

with an estimated relative standard uncertainty of stem:[5 xx 10^(-10)] apply to the radiation of a tunable External Cavity Diode Laser, stabilized to the stem:["d/f"] crossover in a rubidium cell external to the laser.

NOTE: The value of the standard uncertainty is assumed to correspond to a confidence level of 68 %. However, given the limited availability of data there is a possibility that in hindsight this might not prove to be exact

____

