[[cgpm26th2018]]
[%unnumbered]
== 26th CGPM, 2018

[[cgpm26th2018r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*On the revision of the International System of Units, the SI* (CR, in press and _Metrologia_, 2019, *56*, 022001)

[[cgpm26th2018r1r1]]
==== Resolution 1
____

The General Conference on Weights and Measures (CGPM), at its 26th meeting,

*considering*

* the essential requirement for an International System of Units (SI) that is uniform and accessible world-wide for international trade, high-technology manufacturing, human health and safety, protection of the environment, global climate studies and the basic science that underpins all these,
* that the SI units must be stable in the long term, internally self-consistent and practically realizable being based on the present theoretical description of nature at the highest level,
* that a revision of the SI to meet these requirements was described in Resolution 1 of the 24th General Conference in 2011, adopted unanimously, that laid out in detail a new way of defining the SI based on a set of seven ((defining constants)), drawn from the fundamental constants of physics and other constants of nature, from which the definitions of the seven base units(((base unit(s)))) are deduced, (((fundamental constants (of physics))))
* that the conditions set by the 24th General Conference, confirmed by the 25th General Conference, before such a revised SI could be adopted have now been met,

*decides*

that, effective from 20 May 2019, the International System of Units, the SI, is the system of units in which

* the unperturbed ground state hyperfine transition frequency of the caesium stem:[133] atom stem:[Delta ii(nu)_("Cs")] is stem:[9192631770 "unitsml(Hz)"],
* the ((speed of light in vacuum)) stem:[c] is stem:[299792458 "unitsml(m//s)"],
* the ((Planck constant)) stem:[h] is stem:[6.62607015 xx 10^(-34) "unitsml(J*s)"],
* the ((elementary charge)) stem:[e] is stem:[1.602176634 xx 10^(-19) "unitsml(C)"],
* the ((Boltzmann constant)) stem:[k] is stem:[1.380649 xx 10^(-23) "unitsml(J//K)"],
* the ((Avogadro constant)) stem:[ii(N)_"A"] is stem:[6.02214076 xx 10^(23) "unitsml(mol^(-1))"],
* the ((luminous efficacy)) of monochromatic radiation of frequency stem:[540 xx 10^(12) "unitsml(Hz)", ii(K)_("cd")], is stem:[683 "unitsml(lm//W)"],
(((hertz (stem:["unitsml(Hz)"]))))(((coulomb (stem:["unitsml(C)"]))))(((joule (stem:["unitsml(J)"]))))(((lumen (stem:["unitsml(lm)"]))))(((watt (stem:["unitsml(W)"]))))

where the hertz, joule, coulomb, lumen, and watt, with unit symbols stem:["unitsml(Hz)", "unitsml(J)", "unitsml(C)", "unitsml(lm)"], and stem:["unitsml(W)"], respectively, are related to the units second, metre, ((kilogram)), ampere(((ampere (stem:["unitsml(A)"])))), kelvin, mole, and candela(((candela (stem:["unitsml(cd)"])))), with unit symbols stem:["unitsml(s)", "unitsml(m)", "unitsml(kg)", "unitsml(A)", "unitsml(K)", "unitsml(mol)"], and stem:["unitsml(cd)"], respectively, according to stem:["unitsml(Hz)" = "unitsml(s)"^(-1)], stem:["unitsml(J)" = "unitsml(kg*m^2*s^(-2))"], stem:["unitsml(C)" = "unitsml(A*s)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], and stem:["unitsml(W)" = "unitsml(kg*m^2*s^(-3))"].

In making this decision, the General Conference notes the consequences as set out in Resolution 1 of the 24th General Conference in respect to the base units(((base unit(s)))) of the SI and confirms these in the following Appendices to this Resolution, which have the same force as the Resolution itself.

The General Conference invites the International Committee to produce a new edition of its Brochure _The International System of Units, SI_ in which a full description of the SI is given.
____

===== Appendix 1. Abrogation of former definitions of the base units: (((base unit(s))))

____
It follows from the new definition of the SI adopted above that

* the definition of the second in force since 1967/68 (13th meeting of the CGPM, Resolution 1) is abrogated,
* the definition of the metre in force since 1983 (17th meeting of the CGPM, Resolution 1), is abrogated,
* the definition of the ((kilogram)) in force since 1889 (1st meeting of the CGPM, 1889, 3rd meeting of the CGPM, 1901) based upon the mass of the ((international prototype of the kilogram)) is abrogated,
* the definition of the ampere(((ampere (stem:["unitsml(A)"])))) in force since 1948 (9th meeting of the CGPM) based upon the definition proposed by the International Committee (CIPM, 1946, Resolution 2) is abrogated,
* the definition of the kelvin in force since 1967/68 (13th meeting of the CGPM, Resolution 4) is abrogated,
* the definition of the mole in force since 1971 (14th meeting of the CGPM, Resolution 3) is abrogated,
* the definition of the candela(((candela (stem:["unitsml(cd)"])))) in force since 1979 (16th meeting of the CGPM, Resolution 3) is abrogated,(((von Klitzing constant (stem:[R_K,R_{k-90}]))))
* the decision to adopt the conventional values of the Josephson constant stem:[ii(K)_("J–90")] and of the von Klitzing constant stem:[ii(R)_("K–90")] taken by the International Committee (CIPM, 1988, Recommendations 1 and 2) at the request of the General Conference (18th meeting of the CGPM, 1987, Resolution 6) for the establishment of representations of the volt(((volt (stem:["unitsml(V)"])))) and the ohm using the Josephson and quantum Hall effects(((quantum Hall effect))), respectively, is abrogated. (((Josephson constant (stem:[K_J,K_{J-90}]))))
____


===== Appendix 2. Status of constants previously used in the former definitions:

____
It follows from the new definition of the SI adopted above, and from the recommended values of the 2017 special ((CODATA)) adjustment on which the values of the ((defining constants)) are based, that at the time this Resolution was adopted

* the mass of the ((international prototype of the kilogram)) stem:[m(cc "K")] is equal to stem:[1 "unitsml(kg)"] within a relative standard uncertainty equal to that of the recommended value of stem:[h] at the time this Resolution was adopted, namely stem:[1.0 xx 10^(–8)] and that in the future its value will be determined experimentally,
* the vacuum magnetic permeability stem:[ii(mu)_0] is equal to stem:[4pi xx 10^(–7) "unitsml(H*m^(-1))"] within a relative standard uncertainty equal to that of the recommended value of the fine-structure constant stem:[ii(alpha)] at the time this Resolution was adopted, namely stem:[2.3 xx 10^(-10)] and that in the future its value will be determined experimentally, (((fine structure constant)))
* the thermodynamic temperature of the ((triple point of water)) stem:[ii(T)_("TPW")] is equal to stem:[273.16 "unitsml(K)"] within a relative standard uncertainty closely equal to that of the recommended value of stem:[k] at the time this Resolution was adopted, namely stem:[3.7 xx 10^(-7)], and that in the future its value will be determined experimentally,
* the molar mass of ((carbon 12)), stem:[ii(M)(""^{12}"C")], is equal to stem:[0.012 "unitsml(kg*mol^(-1))"] within a relative standard uncertainty equal to that of the recommended value of stem:[ii(N)_"A"h] at the time this Resolution was adopted, namely stem:[4.5 xx 10^(-10)], and that in the future its value will be determined experimentally.
____


===== Appendix 3. The base units(((base unit(s)))) of the SI

____
Starting from the definition of the SI adopted above in terms of fixed numerical values of the ((defining constants)), definitions of each of the seven base units(((base unit(s)))) are deduced by taking, as appropriate, one or more of these ((defining constants)) to give the following set of definitions:
(((second (stem:["unitsml(s)"]))))

* The second, symbol stem:["unitsml(s)"], is the SI unit of time. It is defined by taking the fixed numerical value of the ((caesium frequency)) stem:[Delta ii(nu)_("Cs")], the unperturbed ground-state hyperfine transition frequency of the caesium stem:[133] atom, to be stem:[9192631770] when expressed in the unit stem:["unitsml(Hz)"], which is equal to stem:["unitsml(s^(-1))"].
* The metre(((metre (stem:["unitsml(m)"])))), symbol stem:["unitsml(m)"], is the SI unit of length. It is defined by taking the fixednumerical value of the ((speed of light in vacuum)) stem:[c] to be stem:[299792458] when expressed in the unit stem:["unitsml(m/s)"], where the second is defined in terms of the ((caesium frequency)) stem:[Delta ii(nu)_("Cs")].
* The ((kilogram)), symbol stem:["unitsml(kg)"], is the SI unit of mass. It is defined by taking the fixed numerical value of the ((Planck constant)) stem:[h] to be stem:[6.62607015 xx 10^(–34)] when expressed in the unit stem:["unitsml(J*s)"], which is equal to stem:["unitsml(kg*m^2*s^(-1))"], where the metre and the second are defined in terms of stem:[c] and stem:[Delta ii(nu)_("Cs")].
* The ampere(((ampere (stem:["unitsml(A)"])))), symbol stem:["unitsml(A)"], is the SI unit of ((electric current)). It is defined by taking the fixed numerical value of the ((elementary charge)) stem:[e] to be stem:[1.602176634 xx 10^(–19)] when expressed in the unit stem:["unitsml(C)"], which is equal to stem:["unitsml(A*s)"], where the second is defined in terms of stem:[Delta ii(nu)_("Cs")].
* The kelvin, symbol stem:["unitsml(K)"], is the SI unit of ((thermodynamic temperature)). It is defined by taking the fixed numerical value of the ((Boltzmann constant)) stem:[k] to be stem:[1.380649 xx 10^(–23)] when expressed in the unit stem:["unitsml(J*K^(-1))"], which is equal to stem:["unitsml(kg*m^2*s^(-2)*K^(-1))"], where the ((kilogram)), metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta ii(nu)_("Cs")].
* The mole, symbol stem:["unitsml(mol)"], is the SI unit of amount of substance. One mole contains exactly stem:[6.02214076 xx 10^(23)] elementary entities. This number is the fixed numerical value of the ((Avogadro constant)), stem:[ii(N)_"A"], when expressed in the unit stem:["unitsml(mol^(-1))"] and is called the ((Avogadro number)). +
The amount of substance, symbol stem:[n], of a system is a measure of the number of specified elementary entities. An elementary entity may be an atom, a molecule, an ion, an electron, any other particle or specified group of particles.
* The candela(((candela (stem:["unitsml(cd)"])))), symbol stem:["unitsml(cd)"], is the SI unit of luminous intensity in a given direction. It is defined by taking the fixed numerical value of the ((luminous efficacy)) of monochromatic radiation of frequency stem:[540 xx 10^(12) "unitsml(Hz)", ii(K)_("cd")], to be stem:[683] when expressed in the unit stem:["unitsml(lm*W^(-1))"], which is equal to stem:["unitsml(cd*sr*W^(-1))"], or stem:["unitsml(cd*sr*kg^(-1)*m^(-2)*s^3)"], where the ((kilogram)), metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta ii(nu)_("Cs")].
____
