[[cgpm26th2018]]
== 26th CGPM, 2018

[[cgpm26th2018r1]]
=== On the revision of the International System of Units, the SI (CR, in press and _Metrologia_, 2019, 56, 022001)

[[cgpm26th2018r1r1]]
==== Resolution 1
____

The General Conference on Weights and Measures (CGPM), at its 26th meeting,

*considering*

* the essential requirement for an International System of Units (SI) that is uniform and accessible world-wide for international trade, high-technology manufacturing, human health and safety, protection of the environment, global climate studies and the basic science that underpins all these, 
* that the SI units must be stable in the long term, internally self-consistent and practically realizable being based on the present theoretical description of nature at the highest level,
* that a revision of the SI to meet these requirements was described in Resolution 1 of the 24th General Conference in 2011, adopted unanimously, that laid out in detail a new way of defining the SI based on a set of seven ((defining constants)), drawn from the fundamental constants of physics and other constants of nature, from which the definitions of the seven base units(((base unit(s)))) are deduced, (((fundamental constants (of physics))))
* that the conditions set by the 24th General Conference, confirmed by the 25th General Conference, before such a revised SI could be adopted have now been met,

*decides*

that, effective from 20 May 2019, the International System of Units, the SI, is the system of units in which

* the unperturbed ground state hyperfine transition frequency of the caesium stem:[133] atom stem:[Delta ii(nu)_("Cs")] is stem:[9192631770 " "rm(Hz)],
* the ((speed of light in vacuum)) stem:[c] is stem:[299792458 " "rm(m)//rm(s)], 
* the ((Planck constant)) stem:[h] is stem:[6.62607015 xx 10^(-34) " "rm(J)" "rm(s)], 
* the ((elementary charge)) stem:[e] is stem:[1.602176634 xx 10^(-19) " "rm(C)], 
* the ((Boltzmann constant)) stem:[k] is stem:[1.380649 xx 10^(-23) " "rm(J)//rm(K)], 
* the ((Avogadro constant)) stem:[ii(N)_"A"] is stem:[6.02214076 xx 10^(23) " "rm(mol)^(-1)],
* the ((luminous efficacy)) of monochromatic radiation of frequency stem:[540 xx 10^(12) " "rm(Hz), ii(K)_("cd")], is stem:[683 " "rm(lm)//rm(W)], 
(((hertz (Hz))))(((coulomb \(C))))(((joule (J))))(((lumen (lm))))(((watt (W))))

where the hertz, joule, coulomb, lumen, and watt, with unit symbols stem:[rm(Hz), " "rm(J), " "rm(C), " "rm(lm)], and stem:[rm(W)], respectively, are related to the units second, metre, kilogram, ampere(((ampere (A)))), kelvin, mole, and candela(((candela (cd)))), with unit symbols stem:[rm(s), " "rm(m), " "rm(kg), " "rm(A), " "rm(K), " "rm(mol)], and stem:[rm(cd)], respectively, according to stem:[rm(Hz) = rm(s)^(–1)], stem:[rm(J) = rm(kg)" "rm(m)^2 " "rm(s)^(–2)], stem:[rm(C) = " "rm(A)" "rm(s)], stem:[rm(lm) = rm(cd)" "rm(m)^2 " "rm(m)^(–2) = " "rm(cd)" "rm(sr)], and stem:[rm(W) = rm(kg)" "rm(m)^2" " rm(s)^(–3)].

In making this decision, the General Conference notes the consequences as set out in Resolution 1 of the 24th General Conference in respect to the base units(((base unit(s)))) of the SI and confirms these in the following Appendices to this Resolution, which have the same force as the Resolution itself.

The General Conference invites the International Committee to produce a new edition of its Brochure _The International System of Units, SI_ in which a full description of the SI is given.
____
