[appendix,obligation=informative]
== Status of constants previously used in the former definitions:

It followsfrom the new definition of the SI adopted above, and from the recommended values of the 2017 special ((CODATA)) adjustment on which the values of the ((defining constants)) are based, that at the time this Resolution was adopted

* the mass of the ((international prototype of the kilogram)) stem:[m(cc "K")] is equal to stem:[1 "unitsml(kg)"] within a relative standard uncertainty equal to that of the recommended value of stem:[h] at the time this Resolution was adopted, namely stem:[1.0 xx 10^(–8)] and that in the future its value will be determined experimentally,
* the vacuum magnetic permeability stem:[ii(mu)_0] is equal to stem:[4pi xx 10^(–7) "unitsml(H*m^(–1))"] within a relative standard uncertainty equal to that of the recommended value of the fine-structure constant stem:[ii(alpha)] at the time this Resolution was adopted, namely stem:[2.3 xx 10^(-10)] and that in the future its value will be determined experimentally, (((fine structure constant)))
* the thermodynamic temperature of the ((triple point of water)) stem:[ii(T)_("TPW")] is equal to stem:[273.16 "unitsml(K)"] within a relative standard uncertainty closely equal to that of the recommended value of stem:[k] at the time this Resolution was adopted, namely stem:[3.7 xx 10^(-7)], and that in the future its value will be determined experimentally, 
* the molar mass of ((carbon 12)), stem:[ii(M)(""^{12}"C")], is equal to stem:[0.012 "unitsml(kg*mol^(–1))"] within a relative standard uncertainty equal to that of the recommended value of stem:[ii(N)_"A"h] at the time this Resolution was adopted, namely stem:[4.5 xx 10^(-10)], and that in the future its value will be determined experimentally. 
