[appendix,obligation=informative]
== The base units(((base unit(s)))) of the SI

Starting from the definition of the SI adopted above in terms of fixed numerical values of the ((defining constants)), definitions of each of the seven base units(((base unit(s)))) are deduced by taking, as appropriate, one or more of these ((defining constants)) to give the following set of definitions:
(((second (stem:["unitsml(s)"]))))

* The second, symbol stem:["unitsml(s)"], is the SI unit of time. It is defined by taking the fixed numerical value of the ((caesium frequency)) stem:[Delta ii(nu)_("Cs")], the unperturbed ground-state hyperfine transition frequency of the caesium stem:[133] atom, to be stem:[9192631770] when expressed in the unit stem:["unitsml(Hz)"], which is equal to stem:["unitsml(s^(–1))"].
* The metre(((metre (stem:["unitsml(m)"])))), symbol stem:["unitsml(m)"], is the SI unit of length. It is defined by taking the fixednumerical value of the ((speed of light in vacuum)) stem:[c] to be stem:[299792458] when expressed in the unit stem:["unitsml(m/s)"], where the second is defined in terms of the ((caesium frequency)) stem:[Delta ii(nu)_("Cs")].
* The ((kilogram)), symbol stem:["unitsml(kg)"], is the SI unit of mass. It is defined by taking the fixed numerical value of the ((Planck constant)) stem:[h] to be stem:[6.62607015 xx 10^(–34)] when expressed in the unit stem:["unitsml(J*s)"], which is equal to stem:["unitsml(kg*m^2*s^(–1))"], where the metre and the second are defined in terms of stem:[c] and stem:[Delta ii(nu)_("Cs")].
* The ampere(((ampere (stem:["unitsml(A)"])))), symbol stem:["unitsml(A)"], is the SI unit of ((electric current)). It is defined by taking the fixed numerical value of the ((elementary charge)) stem:[e] to be stem:[1.602176634 xx 10^(–19)] when expressed in the unit stem:["unitsml(C)"], which is equal to stem:["unitsml(A*s)"], where the second is defined in terms of stem:[Delta ii(nu)_("Cs")]. 
* The kelvin, symbol stem:["unitsml(K)"], is the SI unit of ((thermodynamic temperature)). It is defined by taking the fixed numerical value of the ((Boltzmann constant)) stem:[k] to be stem:[1.380649 xx 10^(–23)] when expressed in the unit stem:["unitsml(J*K^(–1))"], which is equal to stem:["unitsml(kg*m^2*s^(–2)*K^(–1))"], where the ((kilogram)), metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta ii(nu)_("Cs")].
* The mole, symbol stem:["unitsml(mol)"], is the SI unit of amount of substance. One mole contains exactly stem:[6.02214076 xx 10^(23)] elementary entities. This number is the fixed numerical value of the ((Avogadro constant)), stem:[ii(N)_"A"], when expressed in the unit stem:["unitsml(mol^(-1))"] and is called the ((Avogadro number)). +
The amount of substance, symbol stem:[n], of a system is a measure of the number of specified elementary entities. An elementary entity may be an atom, a molecule, an ion, an electron, any other particle or specified group of particles.
* The candela(((candela (stem:["unitsml(cd)"])))), symbol stem:["unitsml(cd)"], is the SI unit of luminous intensity in a given direction. It is defined by taking the fixed numerical value of the ((luminous efficacy)) of monochromatic radiation of frequency stem:[540 xx 10^(12) "unitsml(Hz)", ii(K)_("cd")], to be stem:[683] when expressed in the unit stem:["unitsml(lm*W^(–1))"], which is equal to stem:["unitsml(cd*sr*W^(–1))"], or stem:["unitsml(cd*sr*kg^(–1)*m^(–2)*s^3)"], where the ((kilogram)), metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta ii(nu)_("Cs")].