[appendix,obligation=informative]
== The base units of the SI

Starting from the definition of the SI adopted above in terms of fixed numerical values of the defining constants, definitions of each of the seven base units are deduced by taking, as appropriate, one or more of these defining constants to give the following set of definitions:

* The second, symbol stem:[rm(s)], is the SI unit of time. It is defined by taking the fixed numerical value of the caesium frequency stem:[Delta nu_("Cs")], the unperturbed ground-state hyperfine transition frequency of the caesium stem:[133] atom, to be stem:[9192631770] when expressed in the unit stem:[rm(Hz)], which is equal to stem:[rm(s)^(–1)].
* The metre, symbol stem:[rm(m)], is the SI unit of length. It is defined by taking the fixednumerical value of the speed of light in vacuum stem:[c] to be stem:[299792458] when expressed in the unit stem:[rm(m)//rm(s)], where the second is defined in terms of the caesium frequency stem:[Delta nu_("Cs")].
* The kilogram, symbol stem:[rm(kg)], is the SI unit of mass. It is defined by taking the fixed numerical value of the Planck constant stem:[h] to be stem:[6.62607015 times 10^(–34)] when expressed in the unit stem:[rm(J)" "rm(s)], which is equal to stem:[rm(kg)" "rm(m)^2 " "rm(s)^(–1)], where the metre and the second are defined in terms of stem:[c] and stem:[Delta nu_("Cs")].
* The ampere, symbol stem:[rm(A)], is the SI unit of electric current. It is defined by taking the fixed numerical value of the elementary charge stem:[e] to be stem:[1.602176634 times 10^(–19)] when expressed in the unit stem:[rm(C)], which is equal to stem:[rm(A)" "rm(s)], where the second is defined in terms of stem:[Delta nu_("Cs")]. 
* The kelvin, symbol stem:[rm(K)], is the SI unit of thermodynamic temperature. It is defined by taking the fixed numerical value of the Boltzmann constant stem:[k] to be stem:[1.380649 times 10^(–23)] when expressed in the unit stem:[rm(J)" "rm(K)^(–1)], which is equal to stem:[rm(kg)" "rm(m)^2 " "rm(s)^(–2) " "rm(K)^(–1)], where the kilogram, metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta nu_("Cs")].
* The mole, symbol stem:[rm(mol)], is the SI unit of amount of substance. One mole contains exactly stem:[6.02214076 times 10^(23)] elementary entities. This number is the fixed numerical value of the Avogadro constant, stem:[ii(N)_"A"], when expressed in the unit stem:[rm(mol)^(-1)] and is called the Avogadro number. +
The amount of substance, symbol stem:[n], of a system is a measure of the number of specified elementary entities. An elementary entity may be an atom, a molecule, an ion, an electron, any other particle or specified group of particles.
* The candela, symbol stem:[rm(cd)], is the SI unit of luminous intensity in a given direction. It is defined by taking the fixed numerical value of the luminous efficacy of monochromatic radiation of frequency stem:[540 times 10^(12) " "rm(Hz), ii(K)_("cd")], to be stem:[683] when expressed in the unit stem:[rm(lm)" "rm(W)^(–1)], which is equal to stem:[rm(cd)" "rm(sr)" "rm(W)^(–1)], or stem:[rm(cd)" "rm(sr)" "rm(kg)^(–1)" " rm(m)^(–2) " "rm(s)^3], where the kilogram, metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta nu_("Cs")].