=== 17th CGPM, 1983

==== Definition of the metre (CR, 97 and Metrologia, 1984, 20, 25)

[align=center]
*Resolution 1*

The 17th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the present definition does not allow a sufficiently precise realization of the metre for all requirements,
* that progress made in the stabilization of lasers allows radiations to be obtained that are more reproducible and easier to use than the standard radiation emitted by a krypton 86 lamp,
* that progress made in the measurement of the frequency and wavelength of these radiations has resulted in concordant determinations of the speed of light whose accuracy is limited principally by the realization of the present definition of the metre,
* that wavelengths determined from frequency measurements and a given value for the speed of light have a reproducibility superior to that which can be obtained by comparison with the wavelength of the standard radiation of krypton 86,
* that there is an advantage, notably for astronomy and geodesy, in maintaining unchanged the value of the speed of light recommended in 1975 by the 15th CGPM in its Resolution 2 (stem:[c = 299 792 458 text( ) m text(/)s]),
* that a new definition of the metre has been envisaged in various forms all of which have the effect of giving the speed of light an exact value, equal to the recommended value, and that this introduces no appreciable discontinuity into the unit of length, taking into account the relative uncertainty of stem:[+- 4 times 10^(-9)] of the best realizations of the present definition of the metre, +
NOTE: The relative uncertainty given here corresponds to three standard deviations in the data considered.
* that these various forms, making reference either to the path travelled by light in a specified time interval or to the wavelength of a radiation of measured or specified frequency, have been the object of consultations and deep discussions, have been recognized as being equivalent and that a consensus has emerged in favour of the first form,
* that the Comité Consultatif pour la Définition du Mètre (CCDM) is now in a position to give instructions for the practical realization of such a definition, instructions which could include the use of the orange radiation of krypton 86 used as standard up to now, and which may in due course be extended or revised,

*decides*

. The metre is the length of the path travelled by light in vacuum during a time interval of stem:[1text(/)299 792 458] of a second,

. The definition of the metre in force since 1960, based upon the transition between the levels stem:[2p_(10)] and stem:[5d_5] of the atom of krypton 86, is abrogated.

NOTE: The wording of the definition of the metre was modified by the 26th CGPM in 2018 (Resolution 1, see p. 197).

==== On the realization of the definition of the metre (CR, 98 and Metrologia, 1984, 20, 25-26)

[align=center]
*Resolution 2*

The 17th Conférence Générale des Poids et Mesures,

*invites* the Comité International des Poids et Mesures

* to draw up instructions for the practical realization of the new definition of the metre,
* to choose radiations which can be recommended as standards of wavelength for the interferometric measurement of length and to draw up instructions for their use,
* to pursue studies undertaken to improve these standards.

NOTE: See Recommendation 1 (CI-2002) of the CIPM on the revision of the practical realization of the definition of the metre, p. 181.