=== 26th CGPM, 2018

==== On the revision of the International System of Units, the SI (CR, in press and Metrologia, 2019, 56, 022001)

[align=center]
*Resolution 1*

The General Conference on Weights and Measures (CGPM), at its 26th meeting,

*considering*

* the essential requirement for an International System of Units (SI) that is uniform and accessible world-wide for international trade, high-technology manufacturing, human health and safety, protection of the environment, global climate studies and the basic science that underpins all these, 
* that the SI units must be stable in the long term, internally self-consistent and practically realizable being based on the present theoretical description of nature at the highest level,
* that a revision of the SI to meet these requirements was described in Resolution 1 of the 24^th^ General Conference in 2011, adopted unanimously, that laid out in detail a new way of defining the SI based on a set of seven defining constants, drawn from the fundamental constants of physics and other constants of nature, from which the definitions of the seven base units are deduced,
* that the conditions set by the 24^th^ General Conference, confirmed by the 25^th^ General Conference, before such a revised SI could be adopted have now been met,

*decides*

that, effective from 20 May 2019, the International System of Units, the SI, is the system of units in which

* the unperturbed ground state hyperfine transition frequency of the caesium stem:[133] atom stem:[Delta nu_(Cs)] is stem:[9 192 631 770 text( ) Hz],
* the speed of light in vacuum stem:[c] is stem:[299 792 458 text( ) mtext(/)s], 
* the Planck constant stem:[h] is stem:[6.626 070 15 times 10^(-34) text( ) J s], 
* the elementary charge stem:[e] is stem:[1.602 176 634 times 10^(-19) text( ) C], 
* the Boltzmann constant stem:[k] is stem:[1.380 649 times 10^(-23) text( ) Jtext(/)K], 
* the Avogadro constant stem:[N_A] is stem:[6.022 140 76 times 10^(23) text( ) mol^(-1)],
* the luminous efficacy of monochromatic radiation of frequency stem:[540 times 10^(12) text( ) Hz, K_(cd)], is stem:[683 text( ) lmtext(/)W], 

where the hertz, joule, coulomb, lumen, and watt, with unit symbols stem:[Hz, J, C, lm], and stem:[W], respectively, are related to the units second, metre, kilogram, ampere, kelvin, mole, and candela, with unit symbols stem:[s, m, kg, A, K, mol], and stem:[cd], respectively, according to stem:[Hz = s^(–1), J = kg m^2 s^(–2), C = A s, lm = cd text( ) m^2 m^(–2) = cd text( ) sr], and stem:[W = kg m^2 s^(–3)].

In making this decision, the General Conference notes the consequences as set out in Resolution 1 of the 24^th^ General Conference in respect to the base units of the SI and confirms these in the following Appendices to this Resolution, which have the same force as the Resolution itself.

The General Conference invites the International Committee to produce a new edition of its Brochure _The International System of Units, SI_ in which a full description of the SI is given.