[appendix,obligation=informative]
=== Abrogation of former definitions of the base units:

It follows from the new definition of the SI adopted above that

* the definition of the second in force since 1967/68 (13th meeting of the CGPM, Resolution 1) is abrogated,
* the definition of the metre in force since 1983 (17th meeting of the CGPM, Resolution 1), is abrogated,
* the definition of the kilogram in force since 1889 (1st meeting of the CGPM, 1889, 3rd meeting of the CGPM, 1901) based upon the mass of the international prototype of the kilogram is abrogated,
* the definition of the ampere in force since 1948 (9th meeting of the CGPM) based upon the definition proposed by the International Committee (CIPM, 1946, Resolution 2) is abrogated, 
* the definition of the kelvin in force since 1967/68 (13th meeting of the CGPM, Resolution 4) is abrogated, 
* the definition of the mole in force since 1971 (14th meeting of the CGPM, Resolution 3) is abrogated, 
* the definition of the candela in force since 1979 (16th meeting of the CGPM, Resolution 3) is abrogated, 
* the decision to adopt the conventional values of the Josephson constant stem:[K_(J–90)] and of the von Klitzing constant stem:[R_(K–90)] taken by the International Committee (CIPM, 1988, Recommendations 1 and 2) at the request of the General Conference (18th meeting of the CGPM, 1987, Resolution 6) for the establishment of representations of the volt and the ohm using the Josephson and quantum Hall effects, respectively, is abrogated.