source "https://rubygems.org"

gem "sassc"
gem "metanorma-bipm", github: "metanorma/metanorma-bipm", branch: "main"
gem "metanorma-standoc", github: "metanorma/metanorma-standoc", branch: "main"
gem "metanorma-iso", github: "metanorma/metanorma-iso", branch: "main"
gem "metanorma-cli", github: "metanorma/metanorma-cli", branch: "main"
gem "metanorma", github: "metanorma/metanorma", branch: "main"
gem "isodoc", github: "metanorma/isodoc", ref: "b3c09f3e6f0e58e384fdf9072ada721c54579f73"
#gem "metanorma-cli"
