= SI Brochure edition 9, semantic encoded version (WARNING: DRAFT)

WARNING: DO NOT USE THESE FOR ANY OFFICIAL PURPOSE. These documents are under
development -- the authoritative documents can be found on the
https://www.bipm.org[BIPM website].

image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml/badge.svg["Publish", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml"]
image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml/badge.svg["Build", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml"]

Published components are available here:

* https://metanorma.github.io/bipm-si-brochure/[BIPM SI Brochure components index (DRAFT DOCUMENTS)]


== LICENSE

This work item belongs to the https://www.bipm.org[BIPM].

Official BIPM documents are distributed under the
https://creativecommons.org/licenses/by/3.0/igo/[Creative Commons Attribution 3.0 IGO License].


== Purpose

This repository holds the Metanorma source markup for the semantic
version of the SI Brochure (edition 9) and its components.

These components include:

* SI Brochure (bilingual)
** content body (fr, en)
** Appendix 1 (fr, en)
** Appendix 2: individual mise en pratique documents (en)
** Appendix 3 (fr, en)
** Appendix 4 (fr, en)

Rendering formats supported include:

* Metanorma semantic XML
* Metanorma presentation XML
* HTML
* PDF

Each of these components can be individually published.

The composite bilingual SI Brochure is compiled as a Metanorma
collection which includes all its components as individual
documents.


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/bipm-si-brochure/
----


== Installing build tools

See https://www.metanorma.org/install/


== Building the documents

Run the following commands to build the full collection of the documents.

[source,sh]
----
metanorma site generate --agree-to-terms
metanorma collection collection.yml
----

If you wish only to generate the bilingual SI Brochure, the following will
suffice. (the `brochure.yml` file does not compile any MEP documents)

=== Method 1: all in one

This method will generate the bilingual SI Brochure in one command.

[source,sh]
----
metanorma site generate -c brochure.yml --agree-to-terms
----

=== Method 2: individual document generation

This method generates the English and French SI Brochures separately, and
then combines them together into the bilingual version.

[source,sh]
----
metanorma sources/si-brochure-en.adoc
metanorma sources/si-brochure-fr.adoc
mkdir -p _site/documents
mv sources/si-brochure-en.xml _site/documents
mv sources/si-brochure-fr.xml _site/documents
metanorma collection collection.yml
----

=== Outputs

The following outputs will be built:

Component index:: `_site/index.html`
Component outputs:: under `_site/documents/` (HTML, PDF, MN S/P XML)
Bilingual brochure:: `bilingual-brochure/collection.{pdf,xml,presentation.xml}`


== References

The original source files for the SI Brochure are available at:

* https://github.com/metanorma/bipm-si-brochure-refs (private link)


== License

Content copyright BIPM. Other tools copyright Ribose.

