= BIPM SI Brochure

This work item belongs to the BIPM.

image:https://github.com/metanorma/bipm-si-brochure/badges/master/pipeline.svg["Build Status (master)", link="https://github.com/metanorma/bipm-si-brochure/pipelines"]

This document is available in its rendered forms here:

* https://metanorma.github.io/bipm-si-brochure/[BIPM SI Brochure]


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/bipm-si-brochure/
----


== Installing Build Tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=metanorma/mn
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* Document index at `documents.html`
* Output document at `documents/bipm-si-brochure.html`
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make
open documents/bipm-si-brochure.html
----
