= SI Brochure edition 9, semantic encoded version (WARNING: DRAFT)

WARNING: DO NOT USE THESE FOR ANY OFFICIAL PURPOSE. These documents are under
development -- the authoritative documents can be found on the
https://www.bipm.org[BIPM website].

image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml/badge.svg["Publish", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml"]
image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml/badge.svg["Build", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml"]

Published components are available here:

* https://metanorma.github.io/bipm-si-brochure/[BIPM SI Brochure components index (DRAFT DOCUMENTS)]


== LICENSE

This work item belongs to the https://www.bipm.org[BIPM].

Official BIPM documents are distributed under the
https://creativecommons.org/licenses/by/3.0/igo/[Creative Commons Attribution 3.0 IGO License].


== Purpose

This repository holds the Metanorma source markup for the semantic
version of the SI Brochure (edition 9) and its components.

These components include:

* SI Brochure (bilingual)
** content body (fr, en)
** Appendix 1 (fr, en)
** Appendix 2: individual mise en pratique documents (en)
** Appendix 3 (fr, en)
** Appendix 4 (fr, en)

Rendering formats supported include:

* Metanorma semantic XML
* Metanorma presentation XML
* HTML
* PDF

Each of these components can be individually published.

The composite bilingual SI Brochure is compiled as a Metanorma
collection which includes all its components as individual
documents.


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/bipm-si-brochure/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Building the documents

Run the following commands to build the full collection of the documents.

[source,sh]
----
metanorma site generate --agree-to-terms
metanorma collection collection.yml -x xml,html,presentation,pdf \
  -w bilingual-brochure -c sources/collection_cover.html
----

If you wish only to generate the bilingual SI Brochure, the following will
suffice. (the `brochure.yml` file does not compile any MEP documents)

[source,sh]
----
metanorma site generate -c brochure.yml --agree-to-terms
metanorma collection collection.yml -x xml,html,presentation,pdf \
  -w bilingual-brochure -c sources/collection_cover.html
----

The following outputs will be built:

Component index:: `site/index.html`
Component outputs:: under `site/documents/` (HTML, PDF, MN S/P XML)
Bilingual brochure:: `bilingual-brochure/collection.{pdf,xml,presentation.xml}`

