= SI Brochure edition 9, semantic encoded version (WARNING: DRAFT)

WARNING: DO NOT USE THESE FOR ANY OFFICIAL PURPOSE. These documents are under
development -- the authoritative documents can be found on the
https://www.bipm.org[BIPM website].

image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml/badge.svg["Publish", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/docker.yml"]
image:https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml/badge.svg["Build", link="https://github.com/metanorma/bipm-si-brochure/actions/workflows/generate.yml"]

Published components are available here:

* https://metanorma.github.io/bipm-si-brochure/[BIPM SI Brochure components index (DRAFT DOCUMENTS)]


== LICENSE

This work item belongs to the https://www.bipm.org[BIPM].

Official BIPM documents are distributed under the
https://creativecommons.org/licenses/by/3.0/igo/[Creative Commons Attribution 3.0 IGO License].


== Purpose

This repository holds the Metanorma source markup for the semantic
version of the SI Brochure (edition 9) and its components.

These components include:

* SI Brochure (bilingual)
** content body (fr, en)
** Appendix 1 (fr, en)
** Appendix 2: individual mise en pratique documents (en)
** Appendix 3 (fr, en)
** Appendix 4 (fr, en)

* SI Brochure concise summary (fr, en)
* SI Brochure FAQ (fr, en)

Rendering formats supported include:

* Metanorma semantic XML
* Metanorma presentation XML
* HTML
* PDF

Each of these components can be individually published.

The composite bilingual SI Brochure is compiled as a Metanorma
collection which includes all its components as individual
documents.

== Structure

`sources/si-brochure/`:: source files for the SI Brochure and its components.

`sources/si-brochure/1.08`:: source files for the SI Brochure edition 9 v1.08, published 2020-09-17.

`sources/si-brochure/2.01`:: source files for the SI Brochure edition 9 v2.01, published 2019-05-20.

`sources/si-brochure/3.01`:: source files for the SI Brochure edition 9 v3.01.

`sources/si-brochure/3.01/collection.yml`:: collection for the bilingual SI Brochure.

`sources/si-brochure/3.01/si-brochure-{en|fr}.adoc`:: root document for the SI Brochure
(English or French).

`sources/si-brochure/3.01/sib-a1-{en|fr}.adoc`:: root document for the SI
Brochure Appendix 1 (English or French).

`sources/si-brochure/3.01/sib-a4-{en|fr}.adoc`:: root document for the SI
Brochure Appendix 4 (English or French).

`sources/sib-a3-{en|fr}.adoc`:: root document for the SI Brochure Appendix 3
(English or French).

`sources/si-brochure-concise-{en|fr}.adoc`:: source file for the SI Brochure
concise summary (English or French).

`sources/si-brochure-faq-{en|fr}.adoc`:: source file for the SI Brochure FAQ
(English or French).

`sources/mep-*.adoc`:: source files for the individual mise
en pratique documents:

`sources/mep-{si-unit-name}-definition-{en|fr}.adoc`:::
MEPs on the definition of the 7 SI base units (ampere, candela, kelvin,
kilogram, metre, mole, second).

`sources/guide-*.adoc`:: source files for the guidelines published by the BIPM
Consultative Committees on the realization of certain SI units.

`sources/rec-values/mep-*/document.adoc`:: source files for the recommended
values of standard frequencies.


== Fetching the document

[source,sh]
----
git clone https://github.com/metanorma/bipm-si-brochure/
----


== Installing build tools

See https://www.metanorma.org/install/


== Building the documents

=== Full set

Run the following command to build the full collection of the documents.

[source,sh]
----
$ bundle exec metanorma site generate --agree-to-terms
----

=== SI Brochure

If you wish only to generate the bilingual SI Brochure, the following will
suffice. (the `brochure.yml` file does not compile any MEP documents)

.Compile document in single language
[source,sh]
----
$ bundle exec metanorma sources/si-brochure/3.01/si-brochure-en.adoc
----

.Compile collection with dual languages
[source,sh]
----
$ bundle exec metanorma collection --agree-to-terms sources/si-brochure/3.01/collection.yml
----


This method generates the English and French SI Brochures separately, and
then combines them together into the bilingual version.

[source,sh]
----
metanorma sources/si-brochure-en.adoc
metanorma sources/si-brochure-fr.adoc
mkdir -p _site/documents
mv sources/si-brochure-en.xml _site/documents
mv sources/si-brochure-fr.xml _site/documents
metanorma collection collection.yml
----

=== Outputs

The following outputs will be built:

Component index:: `_site/index.html`
Component outputs:: under `_site/documents/` (HTML, PDF, MN S/P XML)
Bilingual brochure:: `bilingual-brochure/collection.{pdf,xml,presentation.xml}`


== References

The original source files for the SI Brochure are available at:

* https://github.com/metanorma/bipm-si-brochure-refs (private link)


== License

Content copyright BIPM. Other tools copyright Ribose.

