=== 11th CGPM, 1960

==== Definition of the metre (CR, 85)

[align=center]
*Resolution 6*

The 11th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the international Prototype does not define the metre with an accuracy adequate for the present needs of metrology,
* that it is moreover desirable to adopt a natural and indestructible standard,

*decides*

. The metre is the length equal to 1 650 763.73 wavelengths in vacuum of the radiation corresponding to the transition between the levels stem:[2p_(10)] and stem:[5d_5] of the krypton 86 atom.

. The definition of the metre in force since 1889, based on the international Prototype of platinum-iridium, is abrogated.

. The international Prototype of the metre sanctioned by the 1st CGPM in 1889 shall be kept at the BIPM under the conditions specified in 1889.

NOTE: This definition was abrogated in 1983 by the 17th CGPM (Resolution 1, see p. 175).

==== Definition of the unit of time (second) (CR, 86)

[align=center]
*Resolution 9*

The 11th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* the powers given to the Comité International des Poids et Mesures (CIPM) by the 10th CGPM to define the fundamental unit of time, 
* the decision taken by the CIPM in 1956, 

*ratifies* the following definition:

"The second is the fraction stem:[1text(/)31 556 925.9747] of the tropical year for 1900 January 0 at 12 hours ephemeris time."

NOTE: This definition was abrogated in 1967 by the 13th CGPM (Resolution 1, see p. 168).

==== Système International d'Unités (CR, 87)

[align=center]
*Resolution 12*

The 11th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* Resolution 6 of the 10th CGPM, by which it adopted six base units on which to establish a practical system of measurement for international use:
+
--
[%unnumbered]
|===
| length | metre | stem:[m]
| mass | kilogram | stem:[kg]
| time | second | stem:[s]
| electric current | ampere | stem:[A]
| thermodynamic temperature | degree Kelvin | stem:[°K]
| luminous intensity | candela | stem:[cd]
|===

NOTE: The CGPM later abrogated certain of its decisions and extended the list of prefixes, see notes below.

NOTE: The name and symbol for the unit of thermodynamic temperature was modified by the 13th CGPM in 1967 (Resolution 3, see p. 169).
--
* Resolution 3 adopted by the Comité International des Poids et Mesures (CIPM) in 1956,
* the recommendations adopted by the CIPM in 1958 concerning an abbreviation for the name of the system, and prefixes to form multiples and submultiples of the units,

*decides*

[align=left]
. the system founded on the six base units above is called the "Système International d'Unités";
+
NOTE: A seventh base unit, the mole, was adopted by the 14th CGPM in 1971 (Resolution 3, see p. 172).

. the international abbreviation of the name of the system is: SI;

. names of multiples and submultiples of the units are formed by means of the following prefixes:
+
--
[%unnumbered]
|===
| Multiplying factor | Prefix | Symbol | Multiplying factor | Prefix | Symbol
| stem:[1 000 000 000 000 = 10^(12)] | tera | stem:[T] | stem:[0.1 = 10^(–1)] | deci | stem:[d]
| stem:[1 000 000 000 = 10^9] | giga | stem:[G] | stem:[0.01  = 10^(–2)] | centi | stem:[c]
| stem:[1 000 000 = 10^6] | mega | stem:[M] | stem:[0.001 = 10^(–3)] | milli | stem:[m]
| stem:[1 000 = 10^3] | kilo | stem:[k] | stem:[0.000 001 = 10^(–6)] | micro | stem:[mu]
| stem:[100 = 10^2] | hecto | stem:[h] | stem:[0.000 000 001 = 10^(–9)] | nano | stem:[n]
| stem:[10 = 10^1] | deca | stem:[da] | stem:[0.000 000 000 001 = 10^(–12)] | pico | stem:[p]
|===

NOTE: Furtherprefixes were adopted by the 12th CGPM in 1964 (Resolution 8, see p. 168), the 15th CGPM in 1975 (Resolution 10, see p. 173) and the 19th CGPM in 1991 (Resolution 4, see p. 179).
--
. the units listed below are used in the system, without excluding others which might be added later.

*_Supplementary units_*

[%unnumbered]
|===
| plane angle | radian | stem:[rad]
| solid angle | steradian | stem:[sr]
|===

NOTE: The 20th CGPM in 1995 abrogated the class of supplementary units in the SI (Resolution 8, see p. 179). These are now considered as derived units.

*_Derived units_*

[%unnumbered]
|===
| area | square metre | stem:[m^2] |
| volume | cubic metre | stem:[m^3] |
| frequency | hertz | stem:[Hz] | stem:[1text(/)s]
| mass density (density) | kilogram per cubic metre | stem:[kg text(/)m^3] |
| speed, velocity | metre per second | stem:[m text(/)s] |
| angular velocity | radian per second | stem:[rad text(/)s] |
| acceleration | metre per second squared | stem:[m text(/)s^2] |
| angular acceleration | radian per second squared | stem:[rad text(/)s^2] |
| force | newton | stem:[N] | stem:[kg * m text(/)s^2]
| pressure (mechanical stress) | newton per square metre | stem:[N text(/)m^2] |
| kinematic viscosity | square metre per second | stem:[m^2 text(/)s] |
| dynamic viscosity | newton-second per square metre | stem:[N * s text(/)m^2] |
| work, energy, quantity of heat | joule | stem:[J] | stem:[N * m]
| power | watt | stem:[W] | stem:[J text(/)s]
| quantity of electricity | coulomb | stem:[C] | stem:[A * s]
a| tension (voltage), +
potential difference, +
electromotive force | volt | stem:[V] | stem:[W text(/)A]
| electric field strength | volt per metre | stem:[V text(/)m] |
| electric resistance | ohm | stem:[ohm] | stem:[V text(/)A]
| capacitance | farad | stem:[F] | stem:[A * s text(/)V]
| magnetic flux | weber | stem:[Wb] | stem:[V * s]
| inductance | henry | stem:[H] | stem:[V * s text(/)A]
| magnetic flux density | tesla | stem:[T] | stem:[Wb text(/)m^2]
| magnetic field strength | ampere per metre | stem:[A text(/)m] |
| magnetomotive force | ampere | stem:[A] |
| luminous flux | lumen | stem:[lm] | stem:[cd * sr]
| luminance | candela per square metre | stem:[cd text(/)m^2] |
| illuminance | lux | stem:[lx] | stem:[lm text(/)m^2]
|===

NOTE: The 13th CGPM in 1967 (Resolution 6, see p. 170) specified other units which should be added to the list. In principle, this list of derived units is without limit.

NOTE: Modern practice is to use the phrase "amount of heat" rather than "quantity of heat", because the word quantity has a different meaning in metrology.

NOTE: Modern practice is to use the phrase "amount of electricity" rather than "quantity of electricity" (see note above).

==== Cubic decimetre and litre (CR, 88)

[align=center]
*Resolution 13*

The 11th Conférence Générale des Poids et Mesures (CGPM),

*considering*

* that the cubic decimetre and the litre are unequal and differ by about 28 parts in stem:[10^6], 
* that determinations of physical quantities which involve measurements of volume are being made more and more accurately, thus increasing the risk of confusion between the cubic decimetre and the litre,

*requests* the Comité International des Poids et Mesures to study the problem and submit its conclusions to the 12th CGPM.