=== CCDS, 1970 (In CIPM, 1970)

==== Definition of TAI (PV, 38, 110-111 and Metrologia, 1971, 7, 43)

[align=center]
*Recommendation S 2*

International Atomic Time (TAI) is the time reference coordinate established by the Bureau International de l'Heure on the basis of the readings of atomic clocks operating in various establishments in accordance with the definition of the second, the unit of time of the International System of Units.

In 1980, the definition of TAI was completed as follows (declaration of the CCDS, _BIPM Com. Cons. Déf. Seconde_, 1980, *9*, S 15 and _Metrologia_, 1981, *17*, 70):

TAI is a coordinate time scale defined in a geocentric reference frame with the SI second as realized on the rotating geoid as the scale unit.

[NOTE]
====
This definition was further amplified by the International Astronomical Union in 1991, Resolution A4:

"TAI is a realized time scale whose ideal form, neglecting a constant offset of 32.184 s, is Terrestrial Time (TT), itself related to the time coordinate of the geocentric reference frame, Geocentric Coordinate Time (TCG), by a constant rate."

(see Proc. 21st General Assembly of the IAU, _IAU Trans._, 1991, vol. *XXIB,* Kluwer.)
====