=== CIPM, 2003

==== Revision of the Mise en Pratique list of recommended radiations (PV, 71, 146 and Metrologia, 2004, 41, 99-100)

[align=center]
*Recommendation 1*

The International Committee for Weights and Measures,

*considering* that

* improved frequency values for radiations of some high-stability cold ion standards already documented in the recommended radiations list have recently become available;
* improved frequency values for the infra-red gas-cell-based optical frequency standard in the optical telecommunications region, already documented in the recommended radiations list, have been determined;
* femtosecond comb-based frequency measurements for certain iodine gas-cell standards on the subsidiary recommended source list have recently been made for the first time, leading to significantly reduced uncertainty;

*proposes* that the _recommended radiation_ list be revised to include the following:

* updated frequency values for the single trapped stem:[text()^(88)Sr^\+] ion quadrupole transition and the single trapped stem:[text()^(171)Yb^+] octupole transition;
* an updated frequency value for the stem:[C_2H_2]-stabilized standard at stem:[1.54 text( ) mu m];
* updated frequency values for the stem:[I_2]-stabilized standards at stem:[543 text( ) nm] and stem:[515 text( ) nm].