=== CIPM, 2005

==== Clarification of the definition of the kelvin, unit of thermodynamic temperature (PV, 73, 235 and Metrologia, 2006, 43, 177-178)

[align=center]
*Recommendation 2*

The International Committee for Weights and Measures (CIPM),

*considering*

* that the kelvin, unit of thermodynamic temperature, is defined as the fraction stem:[1text(/)273.16] of the thermodynamic temperature of the triple point of water,
* that the temperature of the triple point depends on the relative amount of isotopes of hydrogen and oxygen present in the sample of water used,
* that this effect is now one of the major sources of the observed variability between different realizations of the water triple point, 

*decides*

* that the definition of the kelvin refer to water of a specified isotopic composition,
* that this composition be:
+
--
[align=left]
stem:[0.000 155 76 text( mole of ) ^2H text( per mole of ) ^1H], +
stem:[0.000 379 9 text( mole of ) ^(17)O text( per mole of ) ^(16)O], and +
stem:[0.002 005 2 text( mole of ) ^(18)O text( per mole of ) ^(16)O],

which is the composition of the International Atomic Energy Agency reference material Vienna Standard Mean Ocean Water (VSMOW), as recommended by IUPAC in "Atomic Weights of the Elements: Review 2000".
--

* that this composition be stated in a note attached to the definition of the kelvin in the SI brochure as follows:

"This definition refers to water having the isotopic composition defined exactly by the following amount of substance ratios: stem:[0.000 155 76 text( mole of ) ^2H text( per mole of ) ^1H], stem:[0.000 379 9 text( mole of ) ^(17)O text( per mole of ) ^(16)O] and stem:[0.002 005 2 text( mole of ) ^(18)O text( per mole of ) ^(16)O]".

NOTE: The kelvin was redefined by the 26th CGPM in 2018 (Resolution 1, see p. 197).

==== Revision of the Mise en pratique list of recommended radiations (PV, 73, 236 and Metrologia, 2006, 43, 178)

[align=center]
*Recommendation 3*

The International Committee for Weights and Measures (CIPM),

*considering* that:

* improved frequency values for radiations of some high-stability cold ion and cold atom standards already documented in the recommended radiations list have recently become available;
* improved frequency values for the infra-red gas-cell-based optical frequency standard in the optical telecommunications region, already documented in the recommended radiations list, have been determined;
* improved frequency values for certain iodine gas-cell standard, already documented in the subsidiary recommended source list, have been determined;
* frequencies of new cold atoms, of atoms in the near-infrared region and of molecules in the optical telecommunications region have been determined by femtosecond comb-based frequency measurements for the first time;

*decides* that the list of _recommended radiations_ be revised to include the following:

* updated frequency values for the single trapped stem:[text()^(88)Sr^\+] ion quadrupole transition, the single trapped stem:[text()^(199)Hg^+] quadrupole transition and the single trapped stem:[text()^(171)Yb^+] quadrupole transition;
* an updated frequency value for the stem:[Ca] atom transition;
* an updated frequency value for the stem:[C_2H_2]-stabilized standard at stem:[1.54 text( ) mm];
* an updated frequency value for the stem:[I_2]-stabilized standard at stem:[515 text( ) nm];
* the addition of the stem:[text()^(87)Sr] atom transition at stem:[698 text( ) nm];
* the addition of the stem:[text()^(87)Rb] atom two-photon transitions at stem:[760 text( ) nm];
* the addition of the stem:[text()^(12)C_2H_2] (stem:[nu1 + nu3]) band and the stem:[text()^(13)C_2H_2] (stem:[nu1 + nu3]) and (stem:[nu1 + nu3 + nu4 + nu5]) bands at stem:[1.54 text( ) mu m].