=== CIPM, 2006

==== Concerning secondary representations of the second (PV, 74, 249 and Metrologia, 2007, 44, 97)

[align=center]
*Recommendation 1*

The International Committee for Weights and Measures (CIPM),

*considering* that

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" shall be established,
* the CCL/CCTF Joint Working Group (JWG) on the _Mise en Pratique_ of the Definition of the Metre and the Secondary Representations of the Second in its meeting at the International Bureau of Weights and Measures (BIPM) in September 2005 discussed possible candidates to be included in this list for secondary representations of the second,
* the CCL/CCTF JWG reviewed and updated the values for the Hg ion, Sr ion, Yb ion, and the Sr neutral atom transition frequencies in its session in September 2006,
* the CCTF in its Recommendation CCTF 1 (2004) already recommended the unperturbed ground-state hyperfine quantum transition frequency of 87Rb as a secondary representation of the second;

*recommends* that the following transition frequencies shall be used as secondary representations of the second and be included into the new list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second"

* the unperturbed ground-state hyperfine quantum transition of stem:[text()^(87)Rb] with a frequency of stem:[f_(Rb)^(87) = 6 834 682 610.904 324 Hz] and an estimated relative standard uncertainty of stem:[3 times 10^(−15)], 
* the unperturbed optical stem:[5s text( )^2S_(1text(/)2) – 4d text()^2D_(5text(/)2)] transition of the stem:[text()^(88)Sr^\+] ion with a frequency of stem:[f^(88)Sr^+ = 444 779 044 095 484 text( ) Hz] and a relative uncertainty of stem:[7 times 10^(−15)],
* the unperturbed optical stem:[5d^(10) 6s text()^2S_(1text(/)2) (F = 0) – 5d^9 6s^2 text()^2D_(5text(/)2) (F = 2)] transition of the stem:[text()^(199)Hg^\+] ion with a frequency of stem:[f^(199)Hg^+ = 1 064 721 609 899 145 text( ) Hz] and a relative standard uncertainty of stem:[3 times 10^(−15)],
* the unperturbed optical stem:[6s text()^2S_(1text(/)2) (F = 0) – 5d text()^2D_(3text(/)2) (F = 2)] transition of the stem:[text()^(171)Yb^\+] ion with a frequency of stem:[f^(171)Yb^+ = 688 358 979 309 308 text( ) Hz] and a relative standard uncertainty of stem:[9 times 10^(−15)],
* the unperturbed optical transition stem:[5s^2 text()^1S_0 – 5s 5p text()^3P_0] of the stem:[text()^(87)Sr] neutral atom with a frequency of stem:[f_(Sr)^(87) = 429 228 004 229 877 text( ) Hz] and a relative standard uncertainty of stem:[1.5 times 10^(−14)].