= SI Brochure FAQ
:docnumber: Brochure FAQ
:edition: 9
:copyright-year: 2019
:revdate: 2019-05-20
:language: fr
:title-en: Frequently Asked Questions about the revision of the SI that came into force on 20 May 2019
:title-fr: Questions fréquentes au sujet de la révision du SI entrée en vigueur le 20 mai 2019
:status: in-force
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

[[Q1]]
== Quels changements ont eu lieu{nbsp}?

[[R1]]Le kilogramme, stem:["unitsml(kg)"], l'ampère, stem:["unitsml(A)"],
le kelvin, stem:["unitsml(K)"], et la mole, stem:["unitsml(mol)"],
ont de nouvelles définitions qui ont été choisies de façon à ce qu'au
moment de la mise en place du SI révisé, l'amplitude de chacune des
unités redéfinies soit équivalente à celle de l'unité avant sa redéfinition.

[[Q2]]
== Quel était, dans ce cas, l'intérêt d'adopter de nouvelles définitions{nbsp}?

[[R2]]Le fait de définir le kilogramme en se fondant sur des constantes
fondamentales assure sa stabilité à long terme et, par conséquent,
la fiabilité de l'unité de masse, or la fiabilité du kilogramme a
fait l'objet de débats. Les nouvelles définitions de l'ampère et du
kelvin devraient améliorer de manière significative l'exactitude à
laquelle les mesures de grandeurs électriques et de température radiométrique
sont effectuées. L'impact sur les mesures électriques a été immédiat{nbsp}:
les mesures les plus précises dans ce domaine étaient déjà effectuées
à l'aide des effets Josephson et Hall quantique avant la révision
du SI, et le fait de fixer les valeurs numériques de la constante
de Planck stem:[h] et de la charge élémentaire e pour les nouvelles
définitions des unités a permis d'obtenir des valeurs numériques exactes
pour les constantes de Josephson et de von Klitzing. Il n'est plus
nécessaire d'utiliser les unités électriques conventionnelles plutôt
que les unités du SI pour exprimer les résultats des mesures électriques
(voir <<R14>>). En utilisant les définitions actuelles du kelvin et
du kilogramme, le facteur de conversion entre la luminance énergétique
mesurée et la température thermodynamique (constante de Stefan-Boltzmann)
est exact, ce qui devrait améliorer la métrologie des températures
au fur et à mesure des progrès technologiques. La nouvelle définition
de la mole est plus simple que la précédente, ce qui devrait aider
les utilisateurs du SI à mieux comprendre la nature de la grandeur
«{nbsp}quantité de matière{nbsp}» et de son unité, la mole. Dans tous
les cas, le SI est en meilleure adéquation avec les technologies de
ce siècle.

[[Q3]]
== Qu'en est-il des définitions de la seconde, s, du mètre, m, et de la candela, stem:["unitsml(cd)"]{nbsp}?

[[R3]]Les définitions de la seconde, stem:["unitsml(s)"], du mètre,
stem:["unitsml(m)"], et de la candela, stem:["unitsml(cd)"], n'ont
pas changé mais la façon de les rédiger a été révisée afin que la
formulation soit cohérente avec celle utilisée pour les définitions
actuelles du kilogramme, stem:["unitsml(kg)"], de l'ampère, stem:["unitsml(A)"],
du kelvin, stem:["unitsml(K)"], et de la mole, stem:["unitsml(mol)"].

[[Q4]]
== Que deviendra le prototype international du kilogramme maintenant que la révision du SI est entrée en vigueur{nbsp}? Est-ce que le public pourra enfin le voir dans un musée{nbsp}?

[[R4]]Il n'est pas prévu de modifier les conditions de conservation
du prototype international du kilogramme{nbsp}: il restera donc au
BIPM et ne pourra pas être exposé au public. Le prototype international
du kilogramme gardera un intérêt métrologique{nbsp}: il sera par conséquent
utilisé de manière sporadique pour des mesures afin d'éviter autant
que possible tout endommagement de sa surface. Des mesures de la stabilité
de la masse du prototype international du kilogramme réalisées dans
le futur permettront de faire des extrapolations quant à la stabilité
passée du kilogramme.

[[Q5]]
== Est-ce que mon étalon de masse peut être étalonné de la même façon qu'avant le 20 mai 2019{nbsp}?

[[R5]]Vous pouvez continuer à faire étalonner votre étalon de masse
dans votre laboratoire national de métrologie ou dans un laboratoire
secondaire, exactement comme vous le faisiez auparavant. Toutefois,
la voie de traçabilité utilisée par votre laboratoire national de
métrologie pour relier la masse de votre étalon au kilogramme du SI
a changé.

En effet, le BIPM organise une comparaison en continu des réalisations
primaires du kilogramme afin de déterminer une _valeur de consensus_
du kilogramme. Les laboratoires nationaux de métrologie qui disposent
d'une réalisation du kilogramme doivent utiliser cette _valeur de
consensus_ pour disséminer l'unité de masse redéfinie, jusqu'à ce
que la dispersion des résultats soit compatible avec les incertitudes
des réalisations individuelles{nbsp}: cela préserve l'équivalence
internationale des certificats d'étalonnage et respecte les principes
et les protocoles approuvés de l'Arrangement de reconnaissance mutuelle
du CIPM (CIPM MRA).

Les États Membres qui ne disposent pas d'une réalisation du kilogramme
peuvent établir la traçabilité à la même _valeur de consensus_ par
le biais des services d'étalonnage du BIPM pendant la phase d'utilisation
de cette _valeur de consensus_.

[[Q6]]
== Une fois que les laboratoires pourront réaliser eux-mêmes le kilogramme, comment serons-nous sûrs que les résultats des différents laboratoires seront compatibles{nbsp}?

[[R6]]Dans le cas du kilogramme, lorsque la _valeur de consensus_
ne sera plus nécessaire, tous les laboratoires devront démontrer la
traçabilité de leurs mesures de masse à la définition du kilogramme,
fondée sur des constantes de la physique. Néanmoins, comme il est
toujours possible de sous-estimer une incertitude expérimentale ou
de simplement faire une erreur, les laboratoires qui déclareront les
incertitudes les plus faibles compareront régulièrement les résultats
de leurs mesures afin d'évaluer leur compatibilité. Un mécanisme de
base pour cela existe déjà et est couramment utilisé en métrologie{nbsp}:
il se fonde sur l'Arrangement de reconnaissance mutuelle du CIPM (CIPM
MRA) établi en 1999.

[[Q7]]
== Est-ce que les laboratoires nationaux de métrologie doivent également utiliser une _valeur de consensus_ pour disséminer les trois autres unités redéfinies{nbsp}?

[[R7]]Non. Le kilogramme est un cas à part. Les unités électriques
et le kelvin sont évoqués dans les réponses <<R14>> et <<R8>> ci-après.
Concernant la mole, il n'y a aucun changement par rapport à la pratique
précédente.

[[Q8]]
== Est-ce que mon thermomètre peut être étalonné de la même façon qu'avant le 20 mai 2019{nbsp}?

[[R8]]Oui. La nouvelle définition du kelvin n'a pas eu d'effet sur
les échelles de température couramment utilisées EIT-90 et EPTB-2000.
Le Comité consultatif de thermométrie (CCT) a publié des informations
sur les avantages immédiats et à venir de la nouvelle définition du
kelvin.

[[Q9]]
== Dans le SI, la constante de référence pour le kilogramme est la constante de Planck stem:[h], exprimée en stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"]. Cela serait plus facilement compréhensible si la constante de référence avait pour unité l'unité de masse, le kilogramme. Il serait alors possible de dire que le kilogramme est la masse de _<quelque chose>_, telle que la masse d'un nombre donné d'atomes de carbone ou de silicium. Cette définition n'aurait-elle pas été meilleure{nbsp}?

[[R9]]C'est, dans une certaine mesure, une question de subjectivité.
Il est toutefois à noter que la constante de référence utilisée pour
définir une unité donnée n'a pas à avoir la même dimension que cette
unité (même si cela peut paraître plus simple d'un point de vue conceptuel
lorsque tel est le cas). Le SI utilise depuis longtemps plusieurs
constantes de référence, chacune ayant une unité différente de celle
définie. Ainsi, le mètre est défini en utilisant comme constante de
référence la vitesse de la lumière stem:[c], avec pour unité
stem:["unitsml(m/s)"], et non une longueur spécifique exprimée en
stem:["unitsml(m)"]. Cette définition n'est pas considérée comme
insatisfaisante. Cette pratique a commencé en 1960 avec la définition
de l'ampère fondée sur une valeur fixée d'une constante dont l'unité
était stem:["unitsml(kg*m*s^(-2)*A^(-2))"]. (L'actuelle définition
de l'ampère est plus simple.)

Bien qu'intuitivement il puisse sembler préférable de définir le kilogramme
avec une masse comme constante de référence, le fait d'utiliser la
constante de Planck présente d'autres avantages. Ainsi, étant donné
que stem:[h] et e sont désormais connues exactement, les constantes
de Josephson et de von Klitzing, KJ et RK, sont également connues
exactement, ce qui apporte des bénéfices majeurs à la métrologie de
l'électricité. (La physique nous apprend que nous ne pouvons pas fixer
à la fois stem:[h] et la masse de <quelque chose>, telle la masse
d'un atome de carbone 12 stem:[m(""^(12)C)], sans redéfinir la seconde
d'une manière qui ne serait pas du tout pratique.)

[[Q10]]
== Malgré la réponse donnée à la <<Q9>>, il subsiste des personnes qui mettent en doute le bien-fondé de redéfinir le kilogramme en se fondant sur stem:[h] comme référence plutôt qu'en utilisant stem:[m(""^(12)C)]. L'un des arguments avancés est que l'expérience de la balance de Kibble footnote:[La balance du watt a été renommée balance de Kibble, du nom de son inventeur Bryan Kibble] visant à déterminer stem:[h] repose sur un équipement complexe plus difficile à utiliser et plus onéreux à construire que les expériences de masse volumique de cristaux par rayons X (projet XRCD) dont l'objectif est de mesurer la masse d'un atome de silicium 28, et d'en déduire la masse d'un atome de carbone 12. Quelles sont les principales raisons de choisir stem:[h] plutôt que stem:[m(""^(12)C)] comme constante de référence pour le kilogramme{nbsp}?

[[R10]]Cette question aborde deux points qui n'ont pas de rapport
entre eux{nbsp}:

. Pourquoi choisir stem:[h] plutôt que stem:[m(""^(12)C)] comme constante
de référence pour le kilogramme{nbsp}?

. Est-ce que le choix de stem:[h] ou stem:[m(""^(12)C)] détermine
si le kilogramme sera réalisé en pratique par une expérience de la
balance de Kibble ou par des mesures de masse volumique de cristaux
par rayons x{nbsp}?

[start=1]
. Une fois la valeur numérique d'une constante fixée, il n'est ensuite
pas nécessaire, ni même possible, de mesurer la constante. Ainsi,
lorsqu'en 1983 le SI a été modifié afin que la vitesse de la lumière
dans le vide, stem:[c], devienne la constante de référence pour le
mètre, la longue histoire de la mesure de stem:[c] a soudainement
pris fin. Cela a constitué un immense avantage pour la science et
la technologie, notamment en raison du fait que stem:[c] étant utilisée
dans de nombreux domaines scientifiques et technologiques, il était
nécessaire à chaque changement apporté à la valeur du SI recommandée
pour stem:[c] de mettre à jour les valeurs de multiples constantes
et facteurs de conversion liés à stem:[c]. La décision de définir
la valeur numérique de stem:[c] comme exacte était de toute évidence
adéquate.
+
--
De la même façon, stem:[h] est la constante fondamentale de la physique
quantique et, par conséquent, sa valeur du SI est utilisée dans de
nombreux domaines de la science et de la technologie. Par le passé,
les changements apportés à la valeur recommandée de stem:[h] à mesure
que les expériences progressaient ont pu être source, dans le meilleur
des cas, de désagrément et, dans le pire, de confusion. La principale
raison de définir la valeur numérique de stem:[h] a été similaire
à celle de définir stem:[c], et présentait de plus des avantages spécifiques
pour la métrologie de l'électricité, tel que mentionné au point <<R2>>.

Bien entendu, stem:[m(""^(12)C)] est de façon indéniable une constante
et revêt une importance incontestable, en particulier dans les domaines
de la chimie et de la physique des atomes. La raison en est que les
«{nbsp}poids atomiques{nbsp}» (pour un chimiste) ou «{nbsp}masses
atomiques relatives{nbsp}» (pour un physicien) se fondent sur
stem:[m(""^(12)C)]. Toutefois, les poids atomiques ne dépendent pas
de la définition du kilogramme et n'ont évidemment été aucunement
affectés par la nouvelle définition.
--

. Non. Le choix de la constante de référence à utiliser pour définir
le kilogramme n'implique aucune méthode particulière pour réaliser
l'unité de masse, la Résolution 1 (2018) n'en mentionne d'ailleurs
aucune. Nous savons que la réalisation du kilogramme, quelle qu'elle
soit, doit être traçable à stem:[h] car stem:[h] est la constante
de référence de l'actuelle définition du kilogramme. Toutefois, on
sait également que stem:[h//m(""^(12) C) = Q], où stem:[Q] représente
un produit de facteurs numériques exacts et de constantes déterminées
de façon expérimentale. L'incertitude-type relative de stem:[Q] est
inférieure à stem:[4,5 xx 10^(-10)] en se fondant sur les valeurs
actuelles recommandées pour les constantes concernées. Il est possible,
pour réaliser le kilogramme, d'utiliser un équipement tel qu'une balance
de Kibble, qui mesure directement un étalon de masse de stem:[1 "unitsml(kg)"]
à partir de stem:[h] (par des mesures électriques réalisées à l'aide
de dispositifs quantiques), ainsi que des mesures auxiliaires de longueur
et de temps. Toutefois, une expérience qui mesure un étalon de masse
de stem:[1 "unitsml(kg)"] à partir de stem:[m(""^(12)C)], tel que
dans le projet de mesures de masse volumique de cristaux par rayons
X, peut également permettre de réaliser le kilogramme. La raison en
est que stem:[m(""^(12) C)Q = h] et donc le prix à payer pour arriver
à stem:[h] à partir de la mesure de stem:[m(""^(12)C)] est l'incertitude
supplémentaire de stem:[Q] mais cette incertitude est négligeable
dans le contexte de la mise en pratique de l'actuelle définition du
kilogramme.

[[Q11]]
== Les sept grandeurs et unités de base du SI ont-elles changé{nbsp}?

[[R11]]Non. Les sept grandeurs de base (temps, longueur, masse, courant
électrique, température thermodynamique, quantité de matière, intensité
lumineuse) et les sept unités de base correspondantes (seconde, mètre,
kilogramme, ampère, kelvin, mole, candela) sont les mêmes.

[[Q12]]
== Les 22 unités dérivées cohérentes ayant des noms spéciaux et des symboles particuliers ont-elles changé{nbsp}?

[[R12]]Non, ces unités dérivées cohérentes restent inchangées.

[[Q13]]
== Les noms et les symboles des préfixes des multiples et sous-multiples (kilo pour stem:[10^3], milli pour stem:[10^(-3)], etc.) ont-ils changé{nbsp}?

[[R13]]Non, les noms et symboles des préfixes n'ont pas changé.

[[Q14]]
== L'amplitude des unités a-t-elle changé dans le SI révisé{nbsp}?

[[R14]]Non, ce n'est pas le cas. Des conditions visant à assurer la
continuité du SI ont été établies avant l'entrée en vigueur des nouvelles
définitions afin de s'assurer qu'il n'y aurait pas de changement d'amplitude
pour aucune des unités de base du SI et, par conséquent, pour aucune
des unités qui en sont dérivées.

(Il existe une exception concernant les unités électriques{nbsp}:
de 1990 au 20 mai 2019, les unités électriques utilisées dans la pratique
se sont fondées sur des valeurs conventionnelles de la constante de
Josephson et de la constante de von Klitzing plutôt que sur leur définition
du SI. Cela a généré un petit décalage entre les valeurs conventionnelles
et les valeurs du SI. Avec la révision du SI, les unités électriques
pratiques sont de nouveau dans le SI. Cela a entraîné le 20 mai 2019
un unique

changement de + 0,1 partie par million (ppm) pour les valeurs de tension
et de + 0,02 ppm pour les valeurs de résistance, exprimées en unités
du SI.)

[[Q15]]
== Comment vous est-il possible de fixer la valeur d'une constante fondamentale telle que stem:[h] pour définir le kilogramme, e pour définir l'ampère, etc.{nbsp}? Comment avez-vous su quelles valeurs choisir pour fixer ces constantes{nbsp}? Que se passera-t-il si l'on s'aperçoit à l'avenir que la valeur que vous avez choisie est erronée{nbsp}?

[[R15]]Nous n'avons pas fixé -- ni changé -- la valeur de quelque
constante que ce soit pour définir des unités. En effet, les valeurs
des constantes fondamentales sont des constantes de la nature et nous
avons seulement fixé la valeur numérique de chaque constante lorsque
celle-ci est exprimée en unité du SI. En fixant cette valeur numérique,
nous déterminons l'amplitude de l'unité dans laquelle nous mesurons
la constante.

Par exemple, si c est la valeur de la vitesse de la lumière, stem:[{c}]
sa valeur numérique, et stem:[[c\]] l'unité, de sorte que

[stem%unnumbered]
++++
c = {c} [c] = 299792458 "unitsml(m/s)"
++++

alors la valeur c est le produit du nombre stem:[{c}] multiplié par
l'unité stem:[[c\]], et cette valeur ne change jamais. Toutefois,
les facteurs stem:[{c}] et stem:[[c\]] peuvent être choisis de diverses
manières de façon à que le produit stem:[c] reste inchangé.

Il a été décidé en 1983 de fixer le nombre stem:[{c}] à exactement
stem:[299792458], ce qui a défini l'unité de vitesse
stem:[[c\] = "unitsml(m/s)"]. La seconde, stem:["unitsml(s)"], étant
déjà définie, cela a eu pour conséquence de redéfinir le mètre,
stem:["unitsml(m)"]. Le nombre stem:[{c}] dans cette nouvelle définition
a été choisi de façon à ce que l'amplitude de l'unité stem:["unitsml(m/s)"]
reste inchangée, afin que la continuité entre l'ancienne et la nouvelle
définition soit assurée.

[[Q16]]
== Vous n'avez donc fixé en réalité que la valeur numérique de la constante exprimée en unité du SI. Pour le kilogramme, par exemple, vous avez choisi de fixer la valeur numérique stem:[{h}] de la constante de Planck exprimée en unité du SI stem:[[h\] = "unitsml(kg*m^2*s^(-1))"]. Mais la question subsiste{nbsp}: si une nouvelle expérience semble montrer que vous avez choisi une valeur numérique erronée pour stem:[{h}], que se passera-t-il{nbsp}?

[[R16]]Du fait de la révision du SI, la masse du prototype international
du kilogramme, qui a défini l'unité de masse de 1889 au 20 mai 2019,
devra être déterminée de façon expérimentale. S'il s'avérait que nous
avons choisi une valeur erronée pour stem:[{h}], cela signifiera simplement
que, d'après cette nouvelle expérience, la masse du prototype international
du kilogramme n'est pas exactement stem:[1 "unitsml(kg)"].

Cette situation n'aurait de répercussions que sur les mesures de masses
macroscopiques{nbsp}; les masses des atomes et les valeurs d'autres
constantes relatives à la physique quantique n'en seraient pas affectées.
Si au lieu de redéfinir le kilogramme nous avions conservé la définition
approuvée en 1889, nous continuerions à utiliser une grandeur de référence
(la masse du prototype international du kilogramme) pour laquelle
on ne peut affirmer avec certitude qu'elle ne varie pas dans le temps
par rapport à des constantes de la nature telles que la masse d'un
atome ou la constante de Planck.

La question de savoir dans quelle mesure la masse du prototype international
du kilogramme était en train de varier par rapport à la masse d'une
vraie constante de la nature a fait l'objet de nombreux débats au
cours de ces dernières années. L'avantage de la nouvelle définition
réside dans le fait que nous sommes sûrs que la constante de référence
utilisée pour redéfinir le kilogramme est un vrai invariant de la
nature.

[[Q17]]
== Chacune des constantes fondamentales utilisées pour la redéfinition du SI a une incertitude{nbsp}: sa valeur numérique n'est donc pas connue exactement. Toutefois, vous avez fixé exactement la valeur numérique. Comment est-ce posible{nbsp}? Qu'en est-il de l'incertitude{nbsp}?

[[R17]]La précédente définition du kilogramme fixait la masse du prototype
international du kilogramme à exactement un kilogramme, avec une incertitude
zéro, stem:[u_r(m_{"IPK"}) = 0]. La constante de Planck, avant la
révision du SI, était déterminée de façon expérimentale et présentait
une incertitude-type relative stem:[u_r(h)] voisine de
stem:[1,0 xx 10^(-8)].

Désormais, la valeur de stem:[h], exprimée en unités du SI, est connue
exactement, de sorte que stem:[u_r(h) = 0]. Cependant, la masse du
prototype international du kilogramme doit être déterminée de façon
expérimentale et sa valeur initiale a une incertitude relative
stem:[u_r(m_{"IPK"})] de stem:[1,0 xx 10^(-8)]. Ainsi, l'incertitude
est conservée au moment de l'adoption de la nouvelle définition mais
elle est transférée à la référence précédente qui n'est plus utilisée,
tel qu'indiqué dans le tableau ci-dessous.

[cols="3",options="header,unnumbered"]
|===
| Constante utilisée pour définir le kilogramme
| Incertitude dans le précédent SI
| Incertitude dans l'actuel SI

| masse du prototype international du kilogramme, stem:[m(cc "K")]
| 0
| stem:[1,0 xx 10^(-8)] (obtenue expérimentalement)

| constante de Planck, stem:[h]
| stem:[1,0 xx 10^(-8)] (obtenue expérimentalement)
| 0
|===

[[Q18]]
== L'unité de la constante de Planck est l'unité d'action, stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"]. Comment le fait de fixer la valeur numérique de la constante de Planck permet-il de définir le kilogramme{nbsp}?

[[R18]]Le fait de fixer la valeur numérique de stem:[h] définit en
fait l'unité d'action, stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"].
Comme nous avons déjà défini la seconde, stem:["unitsml(s)"], en fixant
la valeur numérique de la fréquence de la transition hyperfine de
l'état fondamental de l'atome de césium stem:[Delta nu_{C_s}], ainsi
que le mètre, stem:["unitsml(m)"], en fixant la valeur numérique de
la vitesse de la lumière dans le vide, stem:[c], le fait de fixer
l'amplitude de l'unité stem:["unitsml(kg*m^2*s^(-1))"] a pour effet
de définir l'unité stem:["unitsml(kg)"].

[[Q19]]
== Les définitions actuelles pour les unités de base du SI révisé ne sont-elles pas circulaires, et par là même insatisfaisantes{nbsp}?

[[R19]]Non, les définitions proposées ne sont pas circulaires. Une
définition circulaire utilise le résultat de la définition dans sa
formulation. Les termes proposés pour chacune des définitions des
unités de base de l'actuel SI précisent la _valeur numérique_ de chaque
constante de référence choisie mais le résultat n'est pas utilisé
pour formuler la définition.

[[Q20]]
== Est-il toujours possible de vérifier la cohérence de la physique maintenant que nous avons fixé les valeurs de toutes les constantes fondamentales{nbsp}?

[[R20]]Ce ne sont pas les valeurs de toutes les constantes fondamentales
que nous avons fixées mais seulement les [underline]#_valeurs numériques_#
d'un petit sous-ensemble de constantes et des combinaisons des constantes
de ce sous-ensemble. Cela a eu pour effet de changer les définitions
des unités, mais non les équations de la physique, et cela n'empêche
en rien les chercheurs de vérifier la cohérence des équations.

[[Q21]]
== Les valeurs numériques des constantes de la physique stem:[c], stem:[h] et stem:[e] sont fixées. Toutefois, cela ne fixe-t-il pas la valeur de la constante de structure fine alors que la valeur de cette constante ne doit pas être fixée{nbsp}?

[[A21]]Non. La valeur de la constante de structure fine continue à
être déterminée par des expériences. Dans le SI, la constante de structure
fine a toujours été fonction de stem:[c], stem:[h], stem:[e] et stem:[mu_0],
la perméabilité magnétique du vide{nbsp}; cette dernière constante,
qui définissait l'ampère, est désormais déterminée de façon expérimentale
par une mesure de la constante de structure fine.