== Non-SI units that are accepted for use with the SI

The SI provides the internationally agreed reference in terms of which all other units are defined. The coherent SI units have the important advantage that unit conversions are not required when inserting particular values for quantities into quantity equations.

Nonetheless it is recognized that some non-SI units are widely used and are expected to continue to be used for many years. Therefore, the CIPM has accepted some non-SI units for use with the SI; these are listed in <<table8>>. If these units are used it should be understood that some advantages of the SI are lost. The SI prefixes can be used with several of these units, but not, for example, with the non-SI units of time.

[[table8]]
.Non-SI units accepted for use with the SI Units
|===
| Quantity | Name of unit | Symbol for unit | Value in SI units

| time a| minute +
hour +
day a| stem:[min] +
stem:[h] +
stem:[d] a| stem:[1 text( )min = 60 text( )s] +
stem:[1 text( )h = 60 text( )min = 3600 text( )s] +
stem:[1 text( )d = 24 text( )h = 86 400 text( )s]
| length | astronomical unit footnote:[As decided at the XXVIII General Assembly of the International Astronomical Union (Resolution B2, 2012).] | stem:[au] | stem:[1 text( )au = 149 597 870 700 text( )m]
a| plane and +
phase angle a| degree +
minute +
second footnote:[For some applications such as in astronomy, small angles are measured in arcseconds (i.e. seconds of plane angle), denoted as or stem:[text(")], milliarcseconds, microarcseconds and picoarcseconds, denoted stem:[mas], stem:[mu as] and stem:[pas], respectively, where arcsecond is an alternative name for second of plane angle.] a| stem:[°] +
stem:[text(')] +
stem:[text(")] a| stem:[1° = (pi text(/)180) text( rad)] +
stem:[1text(') = (1text(/)60)^o = (pi text(/)10 800) text( rad)] +
stem:[1text(") = (1text(/)60)text(') = (pi text(/)648 000) text( rad)]
| area | hectare footnote:[The unit hectare and its symbol ha, were adopted by the CIPM in 1879 (PV, 1879, 41). The hectare is used to express land area.] | stem:[ha] | stem:[1 text( )ha = 1 text( )hm^2 = 10^4 text( )m^2]
| volume | litre footnote:[The litre and the symbol lower-case l, were adopted by the CIPM in 1879 (PV, 1879, 41). The alternative symbol, capital L, was adopted by the 16th CGPM (1979, Resolution 6; CR, 101 and _Metrologia,_ 1980, *16*, 56-57) in order to avoid the risk of confusion between the letter l (el) and the numeral 1 (one).] | stem:[l, L] | stem:[1 text( )l = 1 text( )L = 1 text( )dm^3 = 10^3 text( )cm^3 = 10^(−3) text( )m^3]
| mass a| tonne footnote:[The tonne and its symbol stem:[t], were adopted by the CIPM in 1879 (PV, 1879, 41). This unit is sometimes referred to as "metric ton" in some English-speaking countries.] +
dalton footnote:[The dalton (stem:[Da]) and the unified atomic mass unit (stem:[u]) are alternative names (and symbols) for the same unit, equal to 1/12 of the mass of a free carbon 12 atom, at rest and in its ground state. This value of the dalton is the value recommended in the CODATA 2018 adjustment.] a| stem:[t] +
stem:[Da] a| stem:[1 text( )t = 10^3 text( )kg] +
stem:[1 text( )Da=1.66053906660(50) times 10^(−27) text( )kg]
| energy | electronvolt footnote:[The electronvolt is the kinetic energy acquired by an electron in passing through a potential difference of one volt in vacuum. The electronvolt is often combined with the SI prefixes.] | stem:[eV] | stem:[1 text( )eV = 1.602 176 634 times 10^(−19) text( )J]
| logarithmic ratio quantities a| neper footnote:h[In using these units it is important that the nature of the quantity be specified and that any reference value used be specified.] +
bel footnote:h[] +
decibel footnote:h[] a| stem:[Np] +
stem:[B] +
stem:[dB] | see text
|===

[NOTE]
====
The gal (symbol: stem:[Gal]) is a non SI unit of acceleration employed in geodesy and geophysics to express acceleration due to gravity

stem:[1 Gal = 1 cm s^(−2) = 10^(−2) m text( )s^(−2)]
====

<<table8>> also includes the units of logarithmic ratio quantities, the neper, bel and decibel. They are used to convey information on the nature of the logarithmic ratio quantity concerned. The neper, stem:[Np], is used to express the values of quantities whose numerical values are based on the use of the neperian (or natural) logarithm, stem:[ln = log_e]. The bel and the decibel, stem:[B] and stem:[dB], where stem:[1 dB = (1text(/)10) text( )B], are used to express the values of logarithmic ratio quantities whose numerical values are based on the decadic logarithm, stem:[lg = log_(10)]. The statement stem:[L_X = m text( )dB = (m text(/)10) B] (where stem:[m] is a number) is interpreted to mean that stem:[m = 10 text( )lg(X/(X_0))]. The units neper, bel and decibel have been accepted by the CIPM for use with the International System, but are not SI units.

There are many more non-SI units, which are either of historical interest, or are still used in specific fields (for example, the barrel of oil) or in particular countries (the inch, foot and yard). The CIPM can see no case for continuing to use these units in modern scientific and technical work. However, it is clearly a matter of importance to be able to recall the relation of these units to the corresponding SI units and this will continue to be true for many years.
