bundle exec metanorma 2020-02/document.adoc
bundle exec metanorma guide-ccem-ampere-revised-si-en.adoc	
bundle exec metanorma guide-ccl-GD-MeP-1-en.adoc		
bundle exec metanorma guide-ccl-GD-MeP-2-en.adoc		
bundle exec metanorma guide-ccl-GD-MeP-3-en.adoc		
bundle exec metanorma guide-ccm-kilogram-calibration-en.adoc	
bundle exec metanorma guide-ccm-kilogram-dissemination-en.adoc
bundle exec metanorma mep-ampere-definition-en.adoc
bundle exec metanorma mep-candela-rapport.adoc
bundle exec metanorma mep-candela-si-app2.adoc
bundle exec metanorma mep-kelvin-definition-en.adoc
bundle exec metanorma mep-kilogram-definition-en.adoc
bundle exec metanorma mep-metre-definition-en.adoc
bundle exec metanorma mep-mole-definition-en.adoc
bundle exec metanorma mep-second-definition-en.adoc
bundle exec metanorma sib-a4-en.adoc
bundle exec metanorma sib-a4-fr.adoc
bundle exec metanorma si-brochure-en.adoc
bundle exec metanorma si-brochure-fr.adoc
bundle exec metanorma collection si-brochure-bilingual.yml -x xml,html,presentation,pdf -w bilingual-brochure -c collection_cover.html
