= Identifiers for BIPM information resources
:edition: 1
:copyright-year: 2022
:revdate: 2022-11-08
:language: en
:title-en: Identifiers for BIPM information resources
:title-fr: Identifiants pour les ressources d'information du BIPM
:doctype: guide
:docnumber: BIPM 1010
:committee-en: International Bureau of Weights and Measures
:committee-fr: Bureau international des poids et mesures
:committee-acronym: BIPM
:status: draft-proposal
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:

[[sec-1]]
== Introduction

The BIPM is the international organization established by the Metre Convention,
through which Member States act together on matters related to measurement
science and measurement standards, and the home of the International System of
Units (SI) and the international reference time scale (UTC).

The BIPM publishes information resources that are independently citable by
third-parties, such as in international standards.
This leads to the need to adopt a unified and predictable format for
referencing.

BIPM uses French as its official language but heavily adopts bi-lingual practices,
and often publishes in English.

This document provides guidance to citation users on how to cite BIPM
information resources, for situations in French, English or as bi-lingual
references.


[bibliography]
== Normative references

== Terms and definitions

=== information resource

work manifestation or item in physical or digital form or any other asset that
contributes to human knowledge

NOTE: Information resource can refer to an asset, a record, a dataset, a
document or a component part of a document.

[.source]
<<iso690,clause=3.20>>

=== outcome

statement of action originating from a meeting or a group

[example]
Resolution, decision or statement are different types of meeting outcomes.

=== decision

{{outcome}} documenting a decision

=== resolution

{{outcome}} documenting a resolution

=== recommendation

{{outcome}} documenting a recommendation

=== statement

{{outcome}} documenting a statement


=== CIPM Consultative Committee

committee as part of CIPM with designated responsibilities in a particular
metrology domain

[example]
CCM.

=== joint committee

committee composed of BIPM representatives and one or more partner organizations

[example]
JCGM.

=== CIPM

International Committee for Weights and Measures

=== CGPM

General Conference on Weights and Measures



== Types of information resources

BIPM publishes a number of information resources that can be individually
citable, including the following:

* Relevant to meetings
** Meetings
** Meeting reports
** Meeting outcomes (decisions, resolutions, recommendations, statement)

* Publications
** Strategy documents
** Meeting documents
** Guidance documents

* Entities
** Committees
** Working groups
** Discussion groups

* Workshops

These information resources are published by various entities within the BIPM,
including:

* CIPM
* CGPM
* CIPM Consultative Committees
** Working groups
** Discussion groups
* joint committees
** Working groups
** Discussion groups


== Identifiers and citation syntax for meeting outcomes

=== General

This document defines two types of citation syntaxes for BIPM outcomes:

* full-length syntax: to be used when referencing within textual content;

* short syntax: to be used as a shorthand reference within and in a
bibliographic reference list.


Citations can be made in single language or language-independent settings:

* When a citation points to an outcome of a particular language, the reference
is made towards the outcome's text in that particular language;

* When a citation is made without reference to a particular language, the
reference is made towards the outcome described in both languages.


=== Syntax components

In the following clauses, these components are used to describe particular
parts of the reference syntax.

`group-name`:: is the name of the publishing group
`resource-type`:: is the English or French name of the outcome type
`resource-specific-id`:: is the identifier of the outcome
`year`:: is the year when the outcome was published


=== Full-length syntax

==== General

The full-length syntax is used for referencing within text because they uniquely
identify an information resource with adequate readability.

[[full-french]]
==== Single language: French

The pattern is as follows:

[source%unnumbered]
----
{resource-type} {resource-specific-id} {conjunctive} {group-name} ({year})
----

Where,

`conjunctive`:: is the French conjunctive that connects the resource label
and the group name.

For CIPM and the Consultative Committees::: the conjunctive is "du";

For the CGPM::: the conjunctive is "de la".

`resource-type`:: is one of the following:

Résolution::: For a Resolution;
Recommandation::: For a Recommendation;
Décision::: For a Decision;
Déclaration::: For a Statement;

[example]
Recommandation 2 du CCDS (1970).

[example]
Résolution X de la CGPM (YYYY).


[[full-english]]
==== Single language: English

The pattern is as follows:

[source%unnumbered]
----
{group-name} {resource-type} {resource-specific-id} ({year})
----

Where,

`resource-type`:: is one of the following:

Resolution::: For a Resolution
Recommendation::: For a Recommendation
Decision::: For a Decision
Statement::: For a Statement


[example]
CIPM Decision 111-10 (2022).

[example]
JCRB Recommendation 43-1 (2021).


=== Language-independent

The pattern is as follows:

[source%unnumbered]
----
{identifier in English} / {identifier in French}
----

Where,

`identifier in English`:: refers to the full-length syntax identifier in the
English language described in <<full-english>>.

`identifier in French`:: refers to the full-length syntax identifier in the
French language <<full-french>>.


[example]
CIPM Decision 111-10 (2022) / Décision 111-10 (2022).

[example]
JCRB Recommendation 43-1 (2021) / Recommandation 43-1 (2021).

[example]
CCTF Recommandation 2 / Recommendation 2 (1970).


=== Short syntax

==== General

The short syntax is used for referencing in a bibliography or outside content
text, because they are unambiguous and easily understandable identifiers.


==== Syntax components

In the following clauses, these components are used to describe particular
parts of the reference syntax.

`resource-type-short`:: is the English or French name of the outcome type in short

The `resource-type-short` value can be one of:

`RES`:: Resolution / Résolution
`REC`:: Recommendation / Recommandation
`DEC`:: Decision / Décision
`DECL`:: Déclaration / Statement


==== Single language: French

The pattern is as follows:

[source%unnumbered]
----
{group-name} {resource-type-short} {resource-specific-id} ({year}, F)
----

[example]
CCTF REC 2 (1970, F).

[example]
CIPM DECN 111-10 (2022, F).

[example]
JCRB REC 43-1 (2021, F).


==== Single language: English

The pattern is as follows:

[source%unnumbered]
----
{group-name} {resource-type-short} {resource-specific-id} ({year}, E)
----

[example]
CCTF REC 2 (1970, E).

[example]
CIPM DECN 111-10 (2022, E).

[example]
JCRB REC 43-1 (2021, E).


==== Language-independent

[source%unnumbered]
----
{group-name} {resource-type-short} {resource-specific-id} ({year})
----

[example]
CCTF REC 2 (1970).

[example]
CIPM DECN 111-10 (2022)

[example]
JCRB REC 43-1 (2021)


[bibliography]
== References

* [[[bipm,BIPM SI Brochure]]] BIPM, The International System of Units (SI Brochure) [9th edition, 2019], https://www.bipm.org/en/publications/si-brochure/.

* [[[iso690,ISO 690:2021]]]
