= CCEM Guidelines for Implementation of the ‘Revised SI’
:appendix-id: 2
:partnumber: 4.2
:edition: 1
:copyright-year: 2017
:revdate: 2017-08-12
:language: en
:docnumber: CCEM-GD-RSI-1
:title-en: CCEM Guidelines for Implementation of the ‘Revised SI’
:title-fr: Directives du CCEM concernant la mise en oeuvre du SI révisé
:doctype: guide
:committee-acronym: CCEM
:committee-en: Consultative Committee for Electricity and Magnetism
:committee-fr: Comité consultatif d'électricité et magnétisme
:si-aspect: A_e
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:


.Foreword

In preparation for the implementation of the '`Revised SI`' the Consultative Committee for Electricity
and Magnetism (CCEM) has prepared the following general guidelines for use by National
Metrology Institutes (NMIs) and their clients concerning the impact of the '`Revised SI`' on electrical
metrology. The purpose of these guidelines is to establish a minimal set of actions and justifications
for the electrical community to provide a smooth transition through the implementation of the
'`Revised SI`', maintaining critical measurement traceability while avoiding unnecessary effort.


== Introduction

The '`Revised SI`' is well documented but the authoritative source should be the latest version of the
SI Brochure <<meas-units>>, as well as related documents of the CIPM, CCU, CCM, CCEM and other
Consultative Committees <<committes>>. In essence, the change to the SI is the abrogation of the older base unit
definitions and the acceptance of exact defining values of seven reference constants. These seven
reference values can in turn be utilized to establish direct SI traceability to a number of SI units, both
base units and derived units. The distinction between base and derived units is no longer
fundamental, but is maintained mainly for historical continuity and pedagogical purposes. Details of
the techniques typically used to establish traceability to the '`Revised SI`' are available in the _mise en
pratique_ documents prepared by various Consultative Committees <<committes>>.

At the time of preparation of this document it is expected that the '`Revised SI`' will be approved by
the CGPM meeting in November, 2018 and that the '`Revised SI`' will be implemented worldwide on
International Metrology Day, May 20, 2019. For the purposes of this document we simply refer to
this as the implementation day.

The changes caused by implementing the '`Revised SI`' can be broadly categorized as follows:

* *Text*
+
--
The text of various documents and in particular the text of the definitions of the base units in
the SI Brochure will be changed and will now include references to the seven defining
constants.
--

* *Concepts*
+
--
The physical concepts behind the definitions will change for the ampere, the kilogram, the
kelvin and the mole. These concepts will be the subject of a longer term public education
process.
--

* *Values and Uncertainties*
+
--
The numerical values and uncertainties of various reference constants, some constants of
nature and values of high precision reference artifacts will change on the day of
implementation. In all cases, apart from the electrical units, these changes will be very small
or zero and will go unnoticed by the general public.
--

* *Traceability Paths*
+
--
The transition to the '`Revised SI`' will allow new paths of SI traceability to the seven
reference constants which were not valid in the past. These new traceability paths will have
their own new uncertainty budgets.
--

While the transition to the '`Revised SI`' includes all of these types of change this document is
primarily concerned with the impact of the changes to the values and uncertainties in electrical
quantities on implementation day and immediately following.


== The Impact on Electrical Metrology

In the electrical community, these changes to the SI primarily involve the fixing of the values of the
Planck constant, stem:[h], and the elementary charge, stem:[e]. Fortunately, this concept of using values for stem:[h] and stem:[e]
has been in use by the electrical community since 1990 with the adoption of the conventional values
of stem:[ii(K)_{J-90} ~= 2e//h] and stem:[ii(R)_{K-90} ~= h//e^2]. However, the new values of stem:[h] and stem:[e] are slightly different from those
used to set stem:[ii(K)_{J-90}] and stem:[ii(R)_{K-90}]. The elimination of the '`conventional`' units, represented by stem:[ii(K)_{J-90}] and stem:[ii(R)_{K-90}], will mean that the disseminated electrical units will become fully coherent with the SI. However, this
will result in a small discontinuous change on the day of implementation of the '`Revised SI`' but,
from then on, no further changes will be necessary.

In other communities such as mass, temperature, length, time etc. the changes to the '`Revised SI`' will
not result in an observable discontinuity in quantity values. So the electrical community in particular
needs guidance on two generic questions:

. What do I need to do in preparation for the '`Revised SI`'?
. What do I need to do on or immediately following implementation day?


[align=center]
*What do I need to do in preparation for the '`Revised SI`'?*

Well in advance of implementation day several tasks should be initiated.

First, familiarize yourself, your staff and your impacted clients about the '`Revised SI`', its
consequences and its implementation. Information is available from the CIPM publicity working
group, various NMIs and public presentations <<cipm-tgsi>>-<<nick>>.

Secondly, review your traceability requirements by identifying standards, artifacts, instrumentation,
control and statistical software and specific measurements that may be affected by this change.
Particular focus should be made on the highest accuracy (lowest uncertainty) components (guidance
for this is given in the next section).

Thirdly, review your quality management documents to identify references to the conventional
values stem:[ii(K)_{J-90}] and stem:[ii(R)_{K-90}], for example in calibration procedures and measurement software. These
references need to be updated.

NMIs should also contact their clients so that they too can follow these guidelines.


[align=center]
*What do I need to do on or immediately following implementation day?*

This question pertains specifically to what metrological changes are required on implementation day.
On implementation day software, quality system procedures and other associated documentation
should be updated to reflect the newly defined values of stem:[h] and stem:[e], as well as any revised traceability
paths. At this time, the calibration values of all electrical instrumentation undergo a small
discontinuous change. Of course it is acceptable to numerically correct, or even to recalibrate, all
relevant instrumentation and standards. However, it is often impractical, and in many cases simply
not necessary, to change the previous calibration values so that acceptable traceability to the SI is
maintained.

The relative change, stem:[d], will be about stem:[+1.067 xx 10^(-7)] for voltage related quantities and about
stem:[+1.779 xx 10^(-8)] for resistance related quantities. The magnitude of these changes establishes general criteria
that can be used to decide what action should be taken on implementation day. In general, if the
existing stem:[k = 2] expanded relative uncertainty, stem:[ii(U)], of any particular artifact or measurement is such that

stem:[2.5" "d <= ii(U)]:: no action is necessary until the next recalibration (or measurement). The previous
calibration data is still metrologically valid and any use of this data between
implementation day and the next recalibration date should have an insignificant
impact (the probability of the pre-redefinition confidence interval changes from 95 %
to 87 %). This indicates that voltage related quantities with relative uncertainties of
larger than stem:[2.5 xx 10^(-7)] require no action. Similarly, resistance (and impedance) related
quantities with uncertainties of larger than stem:[5 xx 10^(-8)] require no action. The criteria are
easily extended to compound quantities like power etc. This criterion applies to the
majority of electrical instrumentation.

stem:[ii(U) < 2.5" "d]:: numerical correct or recalibrate before the standard's next use for traceability. This
criterion applies to all quantum standards, as well as some upper echelon artifact
standards such as Zener voltage standards and top-quality resistance and capacitance
standards. Note it also applies to the software that controls these measurements and
the software that is used to statistically monitor their results.


Quantum standards such as Josephson voltage standards and quantum Hall resistance standards
should have their reference values for stem:[2e//h] and stem:[h//e^2] updated, i.e.


[stem%unnumbered]
++++
2e // h = 483597.848416984 "unitsml(GHz//V)"
++++


[stem%unnumbered]
++++
h // e^2 = 25812.8074593045 "unitsml(Ohm)"
++++


and their uncertainty budgets reviewed before their next use after implementation day. Truncation of
the values of stem:[2e//h] and stem:[h//e^2] should adhere to the CCEM _mise en pratique_ <<wgsi>> and should not
detrimentally impact the results. In this way ultimate accuracy and subsequent traceability will be
maintained through the transition.

Also note that the electric and magnetic constants, stem:[ii(epsilon)_0] and stem:[ii(mu)_0], will have approximately the same values
after redefinition but now with relative uncertainties the same as that of the fine structure constant,
stem:[~ 2.3 xx 10^(-10)].

For more detailed information or advice contact your local NMI, your RMO or BIPM.


[bibliography]
== References

* [[[meas-units,1]]] http://www.bipm.org/en/measurement-units/new-si/#communication

* [[[committes,2]]] http://www.bipm.org/en/committees/cc/

* [[[cipm-tgsi,3]]] http://www.bipm.org/en/committees/cc/wg/cipm-tgsi.html

* [[[wgsi,4]]] http://www.bipm.org/en/committees/cc/wg/wgsi.html

* [[[david,5]]] David B. Newell, “A more fundamental International System of Units”, _Physics Today_ *67(7)*, 35 (2014)

* [[[new-si,6]]] www.npl.co.uk/news/special-journal-edition-on-the-new-si

* [[[si-changes,7]]] http://www.npl.co.uk/reference/measurement-units/proposed-si-changes/

* [[[research-new-si,8]]] https://www.ptb.de/cms/en/research-development/research-on-the-new-si.html

* [[[nick,9]]] Nick Fletcher, Gert Rietveld, James Olthoff, Ilya Budovsky, and Martin Milton, “Electrical Units in the New SI: Saying Goodbye to the 1990 Values”, _NCSLI Measure_, *Vol. 9*, Iss. 3, 2014


