= Note on the impact of the redefinition of the kilogram on BIPM mass calibration uncertainties
:appendix: 2
:partnumber: 1
:edition: 1
:copyright-year: 2019
:revdate: 2020-05-20
:language: en
:docnumber: CCM-GD-RSI-1
:title-en: Note on the impact of the redefinition of the kilogram on BIPM mass calibration uncertainties
:title-fr: Note sur l'impact de la redéfinition du kilogramme sur les incertitudes des étalonnages de masse du BIPM
:doctype: guide
:parent-document: si-brochure.adoc
:committee-acronym: CCQM
:committee: Consultative Committee for Amount of Substance: Metrology in Chemistry and Biology
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,doc,pdf,rxl
:local-cache-only:
:data-uri-image:


[abstract]

This note provides information on the impact of the redefinition of the kilogram, which takes place on 20 May 2019, on mass calibration uncertainties stated on BIPM calibration certificates issued before this date.


== Background

In November 2018 the General Conference on Weights and Measures (CGPM) approved a revision of the International System of Units (SI). After the implementation date of the revised SI, 20 May 2019, the kilogram will change from being equal to the mass of the International Prototype of the Kilogram (IPK) to a quantity related to a fixed numerical value of the Planck constant. At this point the IPK will change from having a fixed mass without uncertainty to having a mass with a finite uncertainty which can change with time. Directly after the implementation date of the revised SI the IPK will inherit the uncertainty that had previously been associated with the Planck constant, equal to stem:[10] stem:[mu "g"] (stem:[k = 1]).



== Adjustment of the mass uncertainty of BIPM calibration certificates issued before 20 May 2019

Prior to the decision to redefine the kilogram, all NMIs took traceability, directly or indirectly, from the IPK. This will continue to be the case immediately after 20 May 2019. The mass of the IPK will then have an associated uncertainty of stem:[10] stem:[mu "g"].

NMIs will need to review and, where necessary, adjust their uncertainty budgets for measurements made after 20 May 2019 by:

. Adding stem:[10] stem:[mu "g"] in quadrature to the existing uncertainty given by the BIPM for those standard(s) by which they achieve traceability to the BIPM
. Updating their uncertainty budgets with the new uncertainty for the standard(s)


The mass values stated on the BIPM certificates remain valid.

The Consultative Committee for Mass and Related Quantities (CCM) will meet on 16 and 17 May 2019 and will provide guidance on how Calibration and Measurement Capabilities (CMCs) published in the BIPM Key Comparison Database (KCDB) should be adjusted.

BIPM calibration certificates issued after 20 May 2019 will include the stem:[10] stem:[mu "g"] uncertainty of the IPK with respect to the Planck constant, until completion of the first key comparison of primary realization experiments. Then, mass calibrations at the BIPM will be traceable to the consensus value, determined from the comparison, following CCM Recommendation G1 (2017). The CCM is preparing a detailed information note on the dissemination process after the redefinition of the kilogram.






































































