= Mise en pratique for the definition of the second in the SI
:appendix-id: 2
:partnumber: 1
:edition: 9
:copyright-year: 2019
:revdate: 2019-05-20
:language: en
:title-appendix-en: Mise en pratique for the definition of the second in the SI
:title-appendix-fr: Mise en pratique de la définition de la seconde
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:parent-document: si-brochure.adoc
:docnumber: SI MEP S1
:committee-acronym: CCTF
:committee-en: Consultative Committee for Time and Frequency
:committee-fr: Comité consultatif du temps et des fréquences
:si-aspect: s_deltanu
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Introduction

The purpose of this mise en pratique, prepared by the Consultative Committee for Time and Frequency (CCTF) of the International Committee for Weights and Measures (CIPM), is to indicate how the definition of the SI base unit, the second, symbol stem:[rm(s)], may be realized in practice.

In general, the term “to realize a unit” is interpreted to mean the establishment of the value and associated uncertainty of a quantity of the same kind as the unit that is consistent with the definition of the unit. The definition of the second does not imply any particular experiment for its practical realization. Any method capable of deriving a time value traceable to the set of seven reference constant could, in principle, be used. Thus, the list of methods given is not meant to be an exhaustive list of all possibilities, but rather a list of those methods that are easiest to implement and/or that provide the smallest uncertainties and which are officially recognized as primary methods by the relevant Consultative Committee.

A primary method is a method having the highest metrological properties; whose operation can be completely described and understood; for which a complete uncertainty statement can be written down in terms of SI units; and which does not require a reference standard of the same quantity.


== Definition of the second

The definition of the second, SI base unit of time, is as follows <<BIPMSIB>>:

* The second, symbol stem:[rm(s)], is the SI unit of time. It is defined by taking the fixed numerical value of the caesium frequency stem:[Delta ii(nu)_("Cs")], the unperturbed ground-state hyperfine transition frequency of the caesium 133 atom, to be stem:[9192631770] when expressed in the unit stem:[rm(Hz)], which is equal to stem:[rm(s)^{-1}].

The effect of this definition is that the second is equal to the duration of stem:[9192631770] periods of the radiation corresponding to the transition between the two hyperfine levels of the unperturbed ground state of the stem:[{}^{133}"Cs"] atom.


== Practical realization of the second

=== Atomic clocks

The definition of a unit refers to an idealized situation that can be reached in the practical realization with some uncertainty only. In this spirit, the definition of the second has to be understood as referring to atoms free of any perturbation, at rest and in the absence of electric and magnetic fields.

A future re-definition of the second will be justified if these idealized conditions can be achieved much easier than with the current definition.

The definition of the second should be understood as the definition of the unit of proper time: it applies in a small spatial domain which shares the motion of the caesium atom used to realize the definition.

In a laboratory sufficiently small to allow the effects of the non-uniformity of the gravitational field to be neglected when compared to the uncertainties of the realization of the second, the proper second is obtained after application of the special relativistic correction for the velocity of the atom in the laboratory. It is wrong to correct for the local gravitational field.

==== Primary frequency standards

A small number of national metrology laboratories realize the unit of time with the highest accuracy. To do so, they design and build frequency standards that produce electric oscillations at a frequency whose relationship to the transition frequency of the atom of caesium 133, which defines the second, is known with a very low uncertainty. For such *primary frequency standards*, the various frequency shifts, including those due to the relativistic Doppler effect linked to the atomic motion, the thermal radiation of the environment (blackbody shift), and several other effects related to the clock design and operation, are estimated and corrected for.

In 2017, the best of these primary standards produce the SI second with a relative standard
uncertainty almost approaching one part in stem:[10^(16)].

Note that at such a level of accuracy the effect of the non-uniformity of the gravitational field over the size of the device cannot be ignored. The standard should then be considered in the framework of general relativity in order to provide the proper time at a specified point, for instance a connector.

==== Secondary representations of the second

A list of frequencies recommended for secondary representations of the second is maintained since 2006 and is available at https://www.bipm.org/en/publications/mises-en-pratique/standard-frequencies.html.

The list contains the frequency values and the respective standard uncertainties for the rubidium microwave transition and for other optical transitions, including such in neutral atoms and in single trapped ions. They are considered as *secondary frequency standards, which* can be intrinsically accurate at the level of parts in stem:[10^(18)]; however, the uncertainties provided in the list are in the range of parts in low stem:[10^(14)] – stem:[10^(16)] since the numerical values of the transition frequencies need to be determined by measurements with respect to primary standards with their intrinsic uncertainty as explained above.

==== Other frequency standards

Primary frequency standards can be used for calibration of the frequency of other frequency standards used as clocks in national time-service laboratories. These are generally commercial *caesium clocks* characterized by a very good long-term frequency stability: they are able to maintain a frequency with a stability better than 1 part in stem:[10^(14)] over a few months, and thus constitute very good “time-keepers”. The relative uncertainty of their frequencies is today of the order of stem:[5 xx 10^{−13}] in stand-alone operations, a value which has improved by only a factor of 2 during the last 25 years.

Time metrology laboratories also use *hydrogen masers* which rely on the stem:[1.4 " "rm(GHz)] hyperfine transition in atomic hydrogen. Masers have a much better short-term frequency stability than any
commercial caesium clock. These instruments have traditionally been used in all applications which require a stable reference over intervals of less than one day (frequency stability of about 1 part in stem:[10^{15}] for averaging times of a few hours). Some active hydrogen masers exhibit a small but well predictable drift of their frequencies with time, and they have thus been included with increasing importance in the realization of International Atomic Time (TAI) based on an ensemble of commercial clocks by BIPM (see below).

=== Clock comparisons

The readings of clocks operated in metrology institutes cooperating with the BIPM with respect to a reference need to be known with high accuracy. In some applications, synchronous operation of clocks in widely separated establishments is a requirement. Both situations call for accurate methods of clocks comparison that can be operated anywhere on the Earth, at any time. In the context of general relativity, the concept of synchronization is arbitrary, and lies on a convention for simultaneity and synchronization.

The Global Navigation Satellite Systems (GNSS) provide a satisfactory solution to the problem of time transfer. The two complete systems orbiting − the US Global Positioning System (GPS) and the Russian Global Navigation Satellite System (GLONASS), composed respectively of 30 and 24 non- geostationary satellites − are designed for positioning, but have the particular feature that the satellites are equipped with atomic clocks which broadcast time signals. The European Galileo and the Chinese BeiDou are going to be equally useable in the near future. The signal received from one satellite in a laboratory equipped with an antenna with accurately known position allows the time difference between the local time scale and the GNSS system time to be determined with a Type A uncertainty of a few nanoseconds when averaging over 15 minutes. Receivers allow the simultaneous reception of signals from several satellites, and make use of signals transmitted on two frequencies. In the past, for data to be compared between two laboratories it was essential that they be collected under the strict condition of “common view”. Common-view analysis still has some advantages, but it is no longer required in the case of GPS time transfer thanks to the availability in deferred time of satellite clock parameters, very precise satellite ephemerides and of ionospheric parameters, provided by the International GNSS Service (IGS). Alternatively, one can average over a set of observations in each laboratory and calculate the offsets between the local time scales from the differences in these mean values.

As of 2017, GPS is used on a regular basis to link national laboratories in many countries. The use of GLONASS satellites for time comparisons has increased with the completion of the satellite constellation and the operation of suitable dual-system GPS/GLONASS receivers. However, it remains limited to common-views until adequate parameters will be available.

Two-way satellite time and frequency transfer (TWSFTF) is used regularly for comparing more than ten timing centres world-wide. It consists of the quasi-simultaneous transmission of radiofrequency signals between two laboratories, using a geostationary telecommunication satellite as relay. It provides one-nanosecond accuracy in quasi real-time after typically 2 minutes of measurement.

All these methods of time comparison are subject to relativistic effects typically of several tens of nanoseconds, so corrections must be applied to take them into account.

Equally important is the determination of signal propagation delays in the transmitting (TWSTFT) and receiving equipment (GNSS). The BIPM developed a scheme for GPS equipment calibration in this context which builds on the support of the regional metrology organizations (RMOs) (see http://www.bipm.org/jsp/en/TimeCalibrations.jsp). Campaigns for TWSTFT link calibrations are undertaken and supported by the BIPM. The results of calibration campaigns are inter alia reflected in the uncertainty values for the differences stem:[[UTC - UTC(k)]] in the _Circular T_ (see below) which amount to between stem:[1 " "rm(ns)] and stem:[7 " "rm(ns)], depending on the method and age of the calibration.

=== Time scales

National laboratories usually operate a number of clocks. These are run independently of one another and their data are sometimes combined to generate a perennial time scale. This scale is more stable and more accurate than that of any individual contributing clocks. The scale is based on the results of local clock comparisons in the laboratory. These atomic time scales are generally designated stem:["TA"(k)] for laboratory stem:[k].

Optimal combination of all the results of comparisons between the clocks maintained in the national time-service laboratories results in a world reference time scale, Coordinated Universal Time (UTC), based on International Atomic Time (TAI), as introduced by the 14th CGPM in 1971 (Resolution 1; CR, 77 and _Metrologia_, 1972, *8*, 35). The formal definitions of TAI and UTC have been provided by the Consultative Committee for Time and Frequency (CCTF) in the Recommendation CCTF 3 (2017) and approved in the Resolution 2 of the CGPM (2018) https://www.bipm.org/utils/common/pdf/CGPM-2018/26th-CGPM-Resolutions.pdf:

[quote]
____
International Atomic Time (TAI) is a continuous time scale produced by the BIPM based on the best realizations of the SI second. TAI is a realization of Terrestrial Time (TT) with the same rate as that of TT, as defined by the IAU Resolution B1.9 (2000),

Coordinated Universal Time (UTC) is a time scale produced by the BIPM with the same rate as TAI, but differing from TAI only by an integral number of seconds.
____

Responsibility for TAI was accepted by the CIPM and transferred from the _Bureau International de l’Heure_ to the BIPM on 1 January 1988.

TAI is processed in two steps.

* A weighted average based on some 450 clocks maintained under metrological conditions in about 80 laboratories is first calculated. The algorithm used is optimized for long-term stability, which requires observation of the behaviour of clocks over a long duration. In consequence, TAI is a deferred-time time scale, available with a delay of a few weeks. In 2017, the relative frequency stability of TAI was estimated to 3 parts in stem:[10^(16)] for mean durations of one month.

* The frequency accuracy of TAI is then evaluated by comparing the TAI scale unit with calibrations of the SI second produced by primary and secondary frequency standards. This requires the application of a correction to compensate for the relativistic frequency shift between the location of the primary standard and a fixed point on a conventional surface of equal gravity potential, very close to the rotating geoid. The magnitude of this correction is, between points fixed on the surface of the Earth, of the order of 1 part in stem:[10^(16)] per metre of altitude. During 2017, the fractional deviation between the TAI scale unit and the SI second
on the rotating geoid was a few parts in stem:[10^(16)] , and was known with a standard uncertainty of about stem:[3 xx 10^{−16}]. Both numerical values change slightly from month to month and are reported in the BIPM _Circular T_. This difference is reduced whenever necessary by steering the frequency of TAI through the application of corrections, of a few parts in stem:[10^(16)] in magnitude, every month. This method improves the accuracy of TAI while not degrading its middle-term stability.

TAI is not distributed directly in everyday life. The time in common use is UTC as recommended by the 15^th^ CGPM in its Resolution 5 in 1975 (CR, 104 and _Metrologia_, 1975, *11*, 180).

UTC differs from TAI by an integer number of seconds such that stem:[UTC - TAI = –37 " s"] until at least 1 July 2019. Beyond this date, updated values can be found at ftp://ftp2.bipm.org/pub/tai/publication/leaptab. This difference will be modified in steps of stem:[1 " "rm(s)], using a positive or negative leap second, in order to keep UTC in agreement with the time defined by the rotation of the Earth such that, when averaged over a year, the Sun crosses the Greenwich meridian at noon UTC to within stem:[0.9 " "rm(s)].

National time-service laboratories, which contribute to the formation of UTC at the BIPM, maintain an approximation of UTC, known as stem:["UTC"(k)] for laboratory stem:[k]. UTC is disseminated monthly through the publication of the offsets stem:[[UTC – UTC(k)]] at five-day intervals. These offsets amount to only a few tens of nanoseconds for 35 of the 78 laboratories involved. According to Recommendation S5 of the CCDS footnote:[The CCDS has been renamed Consultative Committee for Time and Frequency (CCTF) since 1997. ] (1993), laboratories should maintain the local realizations stem:[UTC(k)] within stem:[100 " "rm(ns)] offset from UTC. The values of these offsets and their uncertainties are published in the BIPM _Circular T_. In some cases, stem:["UTC"(k)] represents the basis of the legal time in the respective country. Legal times are then in general offset from UTC by an integer whole (with exceptions) number of hours to establish time zones and daylight-saving time. Such legal times are disseminated by various means, depending on the country, such as dedicated time-signal transmitters, radio, television, the speaking clock, telephone lines, the Internet, and dedicated fibre-optic transmission services. In addition, each of the GNSS de facto serves as a means for disseminating a prediction of UTC, with deviations from UTC by a few ten nanoseconds or better.

The computation of UTC is the basis of the key comparison CCTF-K001.UTC, defined in the framework of the CIPM Mutual Recognition Arrangement: the offsets stem:[[UTC – UTC(k)]] and their uncertainties constitute the degrees of equivalence, which are published in the BIPM key comparison database (KCDB).

The CCTF Working Group on the CIPM Mutual Recognition Arrangement (CCTF WGMRA) establishes guidance documents on the requisites to participate to the computation of UTC and to the key comparison on time CCTF-K001.UTC. These guidelines can be accessed at http://www.bipm.org/en/committees/cc/cctf/publications-cc.html#pv.

//Last updated: 2017


== References

* [[[BIPMSIB,BIPM SI Brochure]]], BIPM, The International System of Units (SI Brochure) [9th edition, 2019], https://www.bipm.org/en/publications/si-brochure/.

