= Mise en pratique for the definition of the ampere and other electric units in the SI
:appendix-id: 2
:partnumber: 4.1
:edition: 9
:copyright-year: 2019
:revdate: 2019-05-20
:language: en
:title-appendix-en: Mise en pratique
:title-appendix-fr: Mise en pratique
:title-part-en: Mise en pratique for the definition of the ampere and other electric units in the SI
:title-part-fr: Mise en pratique de la définition de l'ampère et d'autres unités électriques
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:docnumber: SI MEP A1
:committee-acronym: CCEM
:committee-en: Consultative Committee for Electricity and Magnetism
:committee-fr: Comité consultatif d'électricité et magnétisme
:docstage: in-force
:docsubstage: 60
:si-aspect: A_e
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:



[[sec-1]]
== Introduction

The purpose of this _Mise en pratique_, prepared by the Consultative Committee for Electricity and Magnetism (CCEM) of the International Committee for Weights and Measures (CIPM), is to indicate how the SI base unit, the ampere, symbol stem:[rm(A)], and the derived electric SI units with names and symbols, the volt stem:[rm(V)], ohm stem:[Omega], siemens stem:[rm(S)], coulomb stem:[rm(C)], farad stem:[rm(F)], henry stem:[rm(H)], watt stem:[rm(W)], tesla stem:[rm(T)], and weber stem:[rm(Wb)], may be realized in practice.

In general, the term "`to realize a unit`" is interpreted to mean the establishment of the value and associated uncertainty of a quantity of the same kind as the unit that is consistent with the definition of the unit. The definition of the ampere does not imply any particular experiment for its practical realization. Any method capable of deriving an electric current value traceable to the set of seven reference constants could, in principle, be used. Thus, the list of methods given is not meant to be an exhaustive list of all possibilities, but rather a list of those primary methods that are easiest to implement and/or that provide the smallest uncertainties.

A primary method is a method having the highest metrological properties; whose operation can be completely described and understood; for which a complete uncertainty statement can be written down in terms of SI units; and which does not require a reference standard of the same quantity.


== Definition of the ampere

The definition of the ampere, SI base unit of electric current, is as follows <<bipm>>:

____
*The ampere, symbol A, is the SI unit of electric current. It is defined by taking the fixed numerical value of the elementary charge stem:[e] to be stem:[1.602176634 xx 10^{-19}] when expressed in the unit stem:[rm(C)], which is equal to stem:[rm(A)" "rm(s)], where the second is defined in terms of stem:[Delta ii(nu)_{"Cs"}].*
____


[[sec-3]]
== Practical realization of the ampere

As already noted in <<sec-1>>, to realize a unit generally means to establish the value and associated uncertainty of a quantity of the same kind as the unit that is consistent with the definition of the unit. In practice, the ampere stem:[rm(A)] can be realized:

. by using Ohm's law, the unit relation stem:[rm(A) = rm(V)//Omega], and using practical realizations of the SI
derived units the volt stem:[rm(V)] and the ohm stem:[Omega], based on the Josephson and quantum Hall effects,
respectively, as discussed in <<sec-4>> and <<sec-5>> below; or

. by using a single electron transport (SET) or similar device, the unit relation stem:[rm(A) = rm(C)//rm(s)], the
value of stem:[e] given in the definition of the ampere and a practical realization of the SI base unit
the second s; or

. by using the relation stem:[ii(I) = ii(C) * "d"ii(U)//"d"t], the unit relation stem:[rm(A) = rm(F) * rm(V) // rm(s)], and practical realizations of the
SI derived units the volt stem:[rm(V)] and the farad stem:[rm(F)] and of the SI base unit second stem:[rm(s)].

At the time of the preparation of this _Mise en pratique_, single electron transport (SET)
implementations still have technical limitations and often larger relative uncertainties than some
other competitive techniques. However, SET implementations are included in this _Mise en pratique_
because they offer unique and elegant approaches to realizing SI units, and their uncertainties have
been improving in recent years, and they promise to improve further in the future.


[[sec-4]]
== Practical realization of the volt, V, SI derived unit of electric potential difference (voltage) and electromotive force

The volt stem:[rm(V)] can be realized using the Josephson effect and the following value of the Josephson constant stem:[ii(K)_"J"] footnote:[This value has been calculated to 15 significant digits.]:

[[eq-1]]
[stem]
++++
ii(K)_"J" = 483597.848416984 " GHz V"^{-1}
++++

This value follows from the assumption of the accuracy of the equation stem:[ii(K)_"J" = 2e//h], which is strongly
supported by a large body of experimental and theoretical works, and the values of stem:[h] and stem:[e] given in
<<bipm>>. Although the quotient stem:[2e//h] can obviously be calculated with any number of digits, this truncated
recommended value is in error by less than 1 part in stem:[10^(15)], which is intended to be negligible in the
vast majority of applications. In those rare cases where this error may not be negligible, additional
digits should be employed. The advantage of recommending a particular value of stem:[ii(K)_"J"] for practical use
is that it ensures that virtually all realizations of the volt based on the Josephson effect employ
exactly the same value.

Note that the value of stem:[ii(K)_"J"] in <<eq-1>> is smaller than the value stem:[ii(K)_{"J-90"} = 483597.9 " GHz V"^{-1}], which was
adopted by the CIPM starting 1 January 1990 for the international realization of the volt using the
Josephson effect, by the fractional amount stem:[106.665 xx 10^{-9}]. This implies that the unit of voltage
realized using stem:[ii(K)_{"J-90"}] was larger than the present SI unit as realized using the value in <<eq-1>> by the
same fractional amount. Thus, the numerical value of a voltage measured in terms of stem:[ii(K)_{"J-90"}] would
have been smaller by the same fractional amount as the numerical value of the identical voltage
measured today in terms of the present SI volt realized using the value of stem:[ii(K)_"J"] given in <<eq-1>>.


[[sec-5]]
== Practical realization of the ohm, stem:[Omega], SI derived unit of electric resistance and impedance

The ohm stem:[Omega] can be realized as follows:

. by using the quantum Hall effect in a manner consistent with the CCEM Guidelines <<delahaye>> and the following value of the von Klitzing constant stem:[ii(R)_"K"] footnote:[This value has been calculated to 15 significant digits.]:
+
--
[[eq-2]]
[stem]
++++
ii(R)_"K" = 25812.8074593045 text( ) Omega
++++

This value follows from the assumption of the accuracy of the equation stem:[ii(R)_"K" = h//e^2], which is
strongly supported by a large body of experimental and theoretical works, and the values of stem:[h]
and stem:[e] given in <<bipm>>. Although the quotient stem:[h//e^2] can obviously be calculated with any number
of digits, this truncated recommended value is in error by less than 1 part in stem:[10^(15)], which is
intended to be negligible in the vast majority of applications. In those rare cases where this
error may not be negligible, additional digits should be employed. The advantage of
recommending a particular value of stem:[ii(R)_"K"] for practical use is that it ensures that virtually all
realizations of the ohm based on the quantum Hall effect employ exactly the same value; or
--

. by comparing an unknown resistance to the impedance of a known capacitance using, for
example, a quadrature bridge, where, for example, the capacitance has been determined by
means of a calculable capacitor and the value of the electric constant given by <<eq-3>> in
<<magnetic_constant>> below.


Note that the value of stem:[ii(R)_"K"] in <<eq-2>> is larger than the value stem:[ii(R)_{"K-90"} = 25812.807 text( ) Omega], which was adopted
by the CIPM starting 1 January 1990 for the international realization of the ohm using the quantum
Hall effect, by the fractional amount stem:[17.793 xx 10^{-9}]. This implies that the unit of resistance realized
using stem:[ii(R)_{"K-90"}] was larger than the present SI unit as realized using the value in <<eq-2>> by the same
fractional amount. Thus, the numerical value of a resistance measured in terms of stem:[ii(R)_{"K-90"}] would have
been smaller by the same fractional amount as the numerical value of the identical resistance
measured today in terms of the present SI ohm realized using the value of stem:[ii(R)_"K"] given in <<eq-2>>.



== Practical realization of the siemens, S, SI derived unit of electric conductance

The siemens stem:[rm(S)] can be realized from a realization of the ohm (see <<sec-5,nosee%>>) since stem:[rm(S)] is related to stem:[Omega] by the
unit relation stem:[rm(S) = Omega^{-1}].


== Practical realization of the coulomb, C, SI derived unit of electric charge

The coulomb stem:[rm(C)] can be realized as follows:

. by measuring the duration in terms of the SI unit of time, the second s, of the flow of an
electric current known in terms of the ampere realized as indicated in <<sec-3>>; or

. by determining the amount of charge placed on a capacitance known in terms of the farad stem:[rm(F)] realized by method <<item-8a>> or <<item-8b>>, using the unit relation stem:[rm(C) = rm(F) * rm(V)] and by measuring the voltage across the capacitance in terms of the volt stem:[rm(V)] as realized by the Josephson effect and the value of the Josephson constant given in <<eq-1>> (see <<sec-4,nosee%>>); or

. by using a SET or similar device to transfer a known amount of charge based on the value of stem:[e], given in the definition of the ampere, onto a suitable circuit element.


[[sec-8]]
== Practical realization of the farad, F, SI derived unit of capacitance

The farad stem:[rm(F)] can be realized as follows:

. [[item-8a]]by comparing the impedance of a known resistance obtained using the quantum Hall effect and the value of the von Klitzing constant given in <<eq-2>> (see <<sec-5>>), including a quantized Hall resistance itself, to the impedance of an unknown capacitance using, for example, a quadrature bridge; or

. [[item-8b]]by using a calculable capacitor and the value of the electric constant given by <<eq-3>>.


== Practical realization of the henry, H, SI derived unit of inductance

The henry stem:[rm(H)] can be realized as follows:

. by comparing the impedance of an unknown inductance to the impedance of a known capacitance with the aid of known resistances using, for example, a Maxwell-Wien bridge, where the known capacitance and resistances have been determined, for example, from the quantum Hall effect and the value of stem:[ii(R)_"K"] given in <<eq-2>> (see <<sec-5>> and <<sec-8>>); or

. by using a calculable inductor of, for example, the Campbell type of mutual inductor and the value of the magnetic constant stem:[ii(mu)_0] given by <<eq-6>>.


== Practical realization of the watt, W, SI derived unit of power

The watt W can be realized using electrical units by using the fact that electric power is equal to current times voltage, the unit relation based on Ohm's law, stem:[rm(W) = rm(V)^2//Omega], and realizations of the volt and ohm using the Josephson and quantum Hall effects and the values of the Josephson and von Klitzing constants given in <<eq-1>> and <<eq-2>> (see <<sec-4,nosee%>> and <<sec-5,nosee%>>).



== Practical realization of the tesla, T, SI derived unit of magnetic flux density

The tesla stem:[rm(T)] can be realized as follows:

. by using a solenoid, Helmholtz coil or other configuration of conductors of known dimensions carrying an electric current determined in terms of the ampere realized as
discussed in <<sec-3>>, and the value of the magnetic constant stem:[ii(mu)_0] given in <<eq-6>> in the calculation of the magnetic flux density generated by the current carrying conductors; or

. by using nuclear magnetic resonance (NMR) with a sample of known gyromagnetic ratio, for example, a spherical sample of pure stem:["H"_2 "O"] at 25 °C and the most recent recommended value of the shielded gyromagnetic ratio of the proton stem:[gamma_{"p'"}] given by CODATA.


== Practical realization of the weber, Wb, SI derived unit of magnetic flux

The weber stem:[rm(Wb)] can be realized from the tesla based on the unit relation stem:[rm(Wb) = rm(T)" "rm(m)^2] or from the volt based on the unit relation stem:[rm(Wb) = rm(V)" "rm(s)]. Use can also be made of the fact that the magnetic flux quantum stem:[ii(phi)_0], which characterizes the magnetic properties of superconductors, is related to stem:[h] and stem:[e] as given in <<bipm>> by the exact relation stem:[ii(phi)_0 = h//2e].

[[magnetic_constant]]
== Magnetic constant stem:[ii(mu)_0] and related quantities

The new definitions of the kilogram, ampere, kelvin, and mole do not alter the relationships among the magnetic constant (permeability of vacuum) stem:[ii(mu)_0], electric constant (permittivity of vacuum) stem:[ii(epsilon)_0], characteristic impedance of vacuum stem:[ii(Z)_0], admittance of vacuum stem:[ii(Y)_0], and speed of light in vacuum stem:[c]. Moreover, they do not change the exact value of stem:[c], which is explicit in the definition of the SI base unit of length, the metre, m. The relationships among these constants are

[[eq-3]]
[stem]
++++
ii(epsilon)_0 = 1 // ii(mu)_0 c^2
++++

[stem]
++++
ii(Z)_0 = ii(mu)_0 c = (ii(mu)_0 // ii(epsilon)_0)^{1//2}
++++

[stem]
++++
ii(Y)_0 = 1 // ii(mu)_0 c = (ii(epsilon)_0 // ii(mu)_0)^{1//2} = 1 // ii(Z)_0
++++


However, the new definitions do affect the value of stem:[ii(mu)_0], and hence the values of stem:[ii(epsilon)_0], stem:[ii(Z)_0], and stem:[ii(Y)_0]. In particular, stem:[ii(mu)_0] no longer has the exact value stem:[4 pi xx 10^{-7} " "rm(N)" "rm(A)^{-2}] and must be determined experimentally. The value of stem:[ii(mu)_0] can be obtained with a relative standard uncertainty, stem:[u_"r"], identical to that of the fine structure constant stem:[ii(alpha)] from the exact relation

[[eq-6]]
[stem]
++++
ii(mu)_0 = ii(alpha) {2h} / {c e^2}
++++


Since stem:[h], stem:[c], and stem:[e] have fixed numerical values, it follows from <<eq-3>>-<<eq-6>> that


[stem]
++++
u_"r" (ii(Y)_0) = u_"r" (ii(Z)_0) = u_"r" (ii(epsilon)_0) = u_"r" (ii(mu)_0) = u_"r" (ii(alpha))
++++

The recommended values of stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"] resulting from the 2017 CODATA special least-squares adjustment of the values of the fundamental constants <<newell>> were the basis of the exact values used for these four constants in the new definitions of the kilogram, ampere, kelvin, and mole adopted by the 26^th^ CGPM <<bipm>>. The 2017 special adjustment but with stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"] taken to have the exact values used in the new definitions, yields the following currently recommended value of the magnetic constant:


[stem]
++++
ii(mu)_0 = 4 pi [1 + 2.0(2.3) xx 10^{-10}] xx 10^{-7} " "rm(N)" "rm(A)^{-2}
= 12.5663706169(29) xx 10^{-7} " "rm(N)" "rm(A)^{-2}
++++


However, users should always compute the value from the most recent CODATA adjustment <<codata>>. The values and uncertainties of the electric constant, characteristic impedance of vacuum and characteristic admittance of vacuum may always be obtained from the relationships of <<eq-3>>-<<eq-6>>.

It should be recognized that the recommended values for stem:[ii(mu)_0], stem:[ii(epsilon)_0], stem:[ii(Z)_0], and stem:[ii(Y)_0] are expected to change slightly from one future CODATA adjustment to the next, as new data that influence the value of stem:[ii(alpha)] become available. Users of this document should, therefore, always employ the most up-to-date CODATA recommended values for these constants in their calculations. Of course, the values of stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"] fixed by the new definitions will be unchanged from one adjustment to the next.


[bibliography]
== References

* [[[bipm,1]]] BIPM, The International System of Units (SI Brochure) [9th edition, 2019], https://www.bipm.org/en/publications/si-brochure/.

* [[[delahaye,2]]] F. Delahaye and B. Jeckelmann, ‘Revised technical guidelines for reliable dc measurements of the quantized Hall resistance’, _Metrologia_, *40(5)*, 217-223 (2003).

* [[[newell,3]]] D. Newell, F. Cabiati, J. Fischer, K. Fujii, S. G. Karshenboim, H. S. Margolis, E. de Mirandes, P.J. Mohr, F. Nez, K. Pachucki, T. J. Quinn, B. N. Taylor, M. Wang, B. Wood and Z. Zhang, ‘The CODATA 2017 Values of stem:[h], stem:[e], stem:[k], and stem:[ii(N)_"A"] for the Revision of the SI’, _Metrologia_, *55(1)* L13-L16 (2018).

* [[[codata,4]]] '`CODATA recommended values of the fundamental physical constants: 2018`', https://physics.nist.gov/cuu/Constants/index.html.
