= SI Brochure FAQ
:docnumber: Brochure
:edition: 9
:copyright-year: 2019
:revdate: 2019-05-20
:language: en
:title-en: Frequently Asked Questions about the revision of the SI that came into force on 20 May 2019
:title-fr: Questions fréquentes au sujet de la révision du SI entrée en vigueur le 20 mai 2019
:status: in-force
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

[[Q1]]
== What has changed?

[[A1]]The kilogram, stem:["unitsml(kg)"], ampere, stem:["unitsml(A)"], kelvin,
stem:["unitsml(K)"], and mole, stem:["unitsml(mol)"], have new definitions,
but they have been so chosen that at the moment of the change the
magnitudes of the new units were indistinguishable from those of the
old units.

[[Q2]]
== So what was the point of changing to new definitions?

[[A2]]Defining the kilogram in terms of fundamental physical constants
ensures its long-term stability, and hence its reliability, which
was previously in doubt. The new definitions of the ampere and kelvin
are expected to significantly improve the accuracy with which electrical,
and radiometric temperature measurements can be made. The impact on
electrical measurements has been immediate: the most precise electrical
measurements were already made using the Josephson and quantum Hall
effects prior to the redefinition, and fixing the numerical values
of the Planck constant stem:[h] and the elementary electrical charge
stem:[e] in the new definitions of the units has led to exact numerical
values for the Josephson and von Klitzing constants. This eliminates
the previous need to use conventional electrical units rather than
SI units to express the results of electrical measurements (see <<A14>>).
The conversion factor between measured radiance and thermodynamic
temperature (the Stefan-Boltzmann constant) is now exact with the
present definitions of the kelvin and kilogram, leading to improved
temperature metrology as technology improves. The revised definition
of the mole is simpler than the previous definition, and it should
help users of the SI to better understand the nature of the quantity
"amount of substance" and its unit, the mole. All in all, the SI is
now a better fit to the technology of this century.

[[Q3]]
== What about the definitions of the second, stem:["unitsml(s)"], metre, stem:["unitsml(m)"], and candela, stem:["unitsml(cd)"]?

[[A3]]The definitions of the second, stem:["unitsml(s)"], metre, stem:["unitsml(m)"],
and candela, stem:["unitsml(cd)"], have not changed, but the way the
definitions are written was revised to make them consistent in form
with the current definitions for the kilogram, stem:["unitsml(kg)"],
ampere, stem:["unitsml(A)"], kelvin, stem:["unitsml(K)"], and mole,
stem:["unitsml(mol)"].

[[Q4]]
== What will happen to the IPK now that the revised SI has taken effect? Will it go to a museum where the general public can at last see it?

[[A4]]There are no plans to change the storage conditions for the IPK. It
will remain at the BIPM and it will not be on display for the general
public. The IPK will retain a bit of metrological interest and therefore
it will be monitored very sporadically in the future to avoid as much
as possible any surface damage. Measurements of the mass stability
of the IPK in the future may help us extrapolate its mass stability
in the recent past.

[[Q5]]
== Can I get my standard of mass calibrated in the same way as I did before 20 May 2019?

[[A5]]You can continue sending your mass standard to your National Metrology
Institute (NMI) for calibration or to a secondary calibration laboratory
just as you did before. However, the traceability path that your NMI
uses to link it to the SI kilogram has changed.

Indeed, the BIPM is organizing an ongoing comparison among primary
realizations of the kilogram and a _consensus value_ of the kilogram
will be determined from it. National Metrology Institutes having a
realization of the kilogram are requested to avail themselves of the
_consensus value_ when disseminating the unit of mass according to
the new definition, until the dispersion in values becomes compatible
with the individual realization uncertainties, thus preserving the
international equivalence of calibration certificates and in accordance
with the principles and agreed protocols of the CIPM Mutual Recognition
Arrangement.

Member States not having realizations of the new definition of the
kilogram have direct access to traceability to the same
_consensus value_ through the calibration services of the BIPM during
the phase where the consensus value is used.

[[Q6]]
== Once laboratories can realize the kilogram themselves, how can we be sure that inter-laboratory results are compatible?

[[A6]]In the case of the kilogram, when the _consensus value_ will no longer
be needed, all laboratories will need to demonstrate traceability
to the definition of the kilogram, which will be based on physical
constants. Since it is always possible to underestimate an experimental
uncertainty or just to make a mistake, laboratories that claim the
smallest uncertainties will compare results periodically to assess
compatibility with their peers. A basic mechanism for this already
exists and is widely used in metrology. It is based on the CIPM Mutual
Recognition Arrangement established in 1999.

[[Q7]]
== Are NMIs also requested to avail themselves of a _consensus value_ for the dissemination of the three other redefined units?

[[A7]]No. The kilogram is a special case. Electrical units and the kelvin
are mentioned in <<A14>> and <<A8>>, below. As for the mole, there
has been no change to previous practice.

[[Q8]]
== Can I get my thermometer calibrated in the same way as I did before 20 May 2019?

[[A8]]Yes. The new definition of the kelvin has not impacted the status
of the widely-used ITS-90 and PLTS-2000 temperature scales. The Consultative
Committee for Thermometry (CCT) has published information concerning
immediate and future advantages of the new definition.

[[Q9]]
== In the SI the reference constant for the kilogram is the Planck constant stem:[h], with unit stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"]. It would be much easier to comprehend if the reference constant had the unit of mass, the stem:["unitsml(kg)"]. Then we could say: "The kilogram is the mass of _<something>_", such as perhaps the mass of a specified number of carbon or silicon atoms. Would that not have been a better definition?

[[A9]]This is to some extent a matter of subjective judgement. However note
that the reference constant used to define a unit does not _have_
to be dimensionally the same as the unit (even though it may be conceptually
simpler when this is the case). For a long time the SI has used several
reference constants, each of which having a different unit to that
being defined. For example, the metre is defined using as reference
constant the speed of light stem:[c] with unit stem:["unitsml(m/s)"],
not a specified length in stem:["unitsml(m)"]. This definition has
not been found unsatisfactory. This practice first began in 1960,
with the previous definition of the ampere which was based on the
fixed value of a constant whose unit was stem:["unitsml(kg*m*s^(-2)*A^(-2))"].
(The present definition of the ampere is simpler.)

Although it may seem intuitively preferable to define the kilogram
using a mass as the reference constant, using the Planck constant
has other advantages. For example, now that both stem:[h] and stem:[e]
are exactly known, both the Josephson and von Klitzing constants KJ
and RK are also exactly known, with great advantages for electrical
metrology. (Physics tells us that we cannot fix both stem:[h] and
the mass of _<something>_, for instance the mass of a carbon 12 atom
stem:[m(""^(12)C)], without consequently redefining the second in
a very impractical way.)

[[Q10]]
== Despite the answer to <<Q9>> above, there are still people who question the wisdom of defining the kilogram by using stem:[h] as a reference rather than by using stem:[m(""^(12)C)]. One of the arguments they use is that the Kibble footnote:[To recognize Bryan Kibble's invention of the watt balance] balance (KB) experiment to determine stem:[h] uses a complex apparatus that is difficult to use and expensive to build, in comparison with the XRCD (x-ray crystal density) experiment to measure the mass of a silicon 28 atom, and hence the mass of a carbon 12 atom. What are the principal reasons for choosing stem:[h] rather than stem:[m(""^(12)C)] as the reference constant for the kilogram?

[[A10]]These are really two unrelated questions:

. Why choose stem:[h] rather than stem:[m(""^(12)C)] as the reference
constant for the kilogram?
. Does the choice of stem:[h] or stem:[m(""^(12)C)] determine whether
the kilogram will be realized in practice by a KB experiment or by
the XRCD experiment?

[start=1]
. Once the numerical value of a constant is given a fixed value, the
constant need not, indeed cannot, be measured subsequently. For example,
in 1983 when the SI was modified by making the speed of light in vacuum,
stem:[c], the reference constant for the metre, the long history of
measuring stem:[c] abruptly ended. This was an enormous benefit to
science and technology, in part because stem:[c] enters into so many
domains of science and technology that every time there was a change
to the recommended SI value of stem:[c], the values of numerous constants
and conversion factors related to stem:[c] needed to be updated. The
decision to define the numerical value of stem:[c] as exact was obviously
correct.
+
--
Similarly, stem:[h] is the fundamental constant of quantum physics
and consequently its SI value is used in many diverse fields of modern
science and technology. In the past, changes to the recommended value
of stem:[h] as experiments improved were at best annoying and at worst
confusing. The rationale for defining the numerical value of stem:[h]
was similar to that for defining stem:[c], but had the specific advantages
in electrical metrology given in <<A2>>.

Of course stem:[m(""^(12)C)] is undeniably a constant and is undeniably
important, especially for chemistry and the physics of atoms. This
is because atomic weights (if you are a chemist), also known as relative
atomic masses (if you are a physicist), are all based on stem:[m(""^(12)C)].
Nevertheless, atomic weights do not depend on the definition of the
kilogram and, of course, they have been unaffected by the new definition.
--

. No. The choice of which reference constant is used to define the
kilogram does not imply any particular method to realize the kilogram,
and none is mentioned in Resolution 1 (2018). We do know that any
realization must be traceable to stem:[h] since stem:[h] is the reference
constant in the present definition of the kilogram. However, it is
also known that stem:[h//m(""^(12)C) = Q], where stem:[Q] represents
a product of exact numerical factors and experimentally-determined
constants. The relative standard uncertainty of stem:[Q] is less than
stem:[4.5 xx 10^(-10)] based on the current recommended values of
the constants involved. An apparatus, such as the KB, which measures
a stem:[1 "unitsml(kg)"] mass standard directly in terms of stem:[h]
(through electrical measurements made with quantum devices) and auxiliary
measurements of length and time can be used to realize the kilogram.
However, an experiment that measures a stem:[1 "unitsml(kg)"] mass
standard in terms of stem:[m(""^(12)C)], as in the XRCD project, also
has the potential to realize the kilogram. This is because
stem:[m(""^12 C)Q = h], and thus the price to pay for arriving at
stem:[h] by way of stem:[m(""^(12)C)] is the added uncertainty of
stem:[Q], which is negligible in the context of realizing the present
definition.

[[Q11]]
== Have the seven base quantities and base units of the SI changed?

[[A11]]No. The seven base quantities (time, length, mass, electric current,
thermodynamic temperature, amount of substance, luminous intensity)
and corresponding base units (second, metre, kilogram, ampere, kelvin,
mole, candela) have remained unchanged.

[[Q12]]
== Have the 22 coherent derived units with special names and symbols changed?

[[A12]]No, the 22 coherent derived units with special names and symbols have
remained unchanged in the SI.

[[Q13]]
== Have the names and symbols of the multiple and sub-multiple prefixes (kilo for stem:[10^3], milli for stem:[10^(-3)], etc.) changed in the present SI?

[[A13]]No, the names and symbols for the prefixes have remained unchanged.

[[Q14]]
== Have the magnitudes of any of the units changed?

[[A14]]No. So-called "continuity conditions" were established before
the transition to help ensure that there would be no change in magnitude
of any of the SI base units, and hence no change in any units derived
from the base units.

(There is a small exception involving electrical units: since 1990
until May 2019, the electrical units used in practice were based on
conventional values for the Josephson constant and the von Klitzing
constant rather than on their SI definitions at the time. This led
to small offsets between the conventional and the SI values. The revision
of the SI has brought the practical electrical units back into the
SI. On 20 May 2019 there was a one-time change of + 0.1 parts per
million (ppm) for voltage values and of + 0.02 ppm for resistance
values when expressed in the SI units.)

[[Q15]]
== How can you fix the value of a fundamental constant like stem:[h] to define the kilogram, and e to define the ampere, and so on? How did you know what value to fix them to? What if it emerges that you have chosen the wrong value?

[[A15]]We have not fixed -- or changed -- the [underline]#_value_# of any
constant that we use to define a unit. The values of the fundamental
constants are constants of nature and we have only fixed the numerical
value of each constant when expressed in its SI unit. By fixing its
numerical value we define the magnitude of the unit in which we measure
that constant at present.

Example: If stem:[c] is the value of the speed of light, stem:[{c}]
is its numerical value, and stem:[[c\]] is the unit, so that

[stem%unnumbered]
++++
c = {c} [c] = 299792458 "unitsml(m/s)"
++++

then the value stem:[c] is the product of the number stem:[{c}] times
the unit stem:[[c\]], and the value never changes. However the factors
stem:[{c}] and stem:[[c\]] may be chosen in different ways such that
the product stem:[c] remains unchanged.

In 1983 it was decided to fix the number stem:[{c}] to be exactly
stem:[299792458], which then defined the unit of speed
stem:[[c\] = "unitsml(m/s)"]. Since the second, stem:["unitsml(s)"],
was already defined, the effect was to define the metre, stem:["unitsml(m)"].
The number stem:[{c}] in the new definition was chosen so that the
magnitude of the unit stem:["unitsml(m/s)"] was unchanged, thereby
ensuring continuity between the new and old definitions of the units.

[[Q16]]
== OK, you actually have only fixed the [underline]#_numerical value_# of the constant expressed in its [underline]#_unit_#. For the kilogram, for example, you have chosen to fix the numerical value stem:[{h}] of the Planck constant expressed in its unit stem:[[h\] = "unitsml(kg*m^2*s^(-1))"]. But the question remains: suppose a new experiment suggests that you have chosen a wrong numerical value for stem:[{h}], what then?

[[A16]]Now that we have made the change, the mass of the international prototype
of the kilogram (the IPK), which defined the kilogram from 1889 until
20 May 2019, will have to be determined by experiment. If we have
chosen a "wrong value" it simply means that the new experiment will
tell us that the mass of the IPK is not exactly stem:[1 "unitsml(kg)"].
This situation would only affect macroscopic mass measurements; the
masses of atoms and the values of other constants related to quantum
physics would not be affected. Continuing with the definition of the
kilogram agreed in 1889 would continue the practice of using a reference
quantity (i.e. the mass of the IPK) that we cannot be sure is not
changing with time compared to a true invariant such as the mass of
an atom or the Planck constant.

There has been much debate over the years about how much the mass
of the IPK might be changing with respect to the mass of a true physical
constant. The advantage of the new definition is that we are certain
that the reference constant used to define the kilogram is a true
invariant.

[[Q17]]
== Each of the fundamental constants used to define a unit has an uncertainty; its value is not known exactly. But you have fixed its numerical value exactly. How can you do that? What has happened to the uncertainty?

[[A17]]The previous definition of the kilogram fixed the mass of the IPK
to be one kilogram exactly with zero uncertainty,
stem:[u_r(m_("IPK")) = 0]. The Planck constant, before the revision
of the SI, was experimentally determined, and had reached a relative
standard uncertainty of 1.0 part in stem:[10^8],
stem:[u_r(h) = 1.0 xx 10^(-8)].

Now, the value of stem:[h] is known exactly in terms of its SI unit
so that stem:[u_r(h) = 0]. But the mass of the IPK needs to be experimentally
determined, and its initial value has a relative uncertainty of
stem:[ur(m_("IPK")) = 1.0 xx 10^(-8)]. Thus the uncertainty is not
lost in the new definition, but it moves to become the uncertainty
of the previous reference that is no longer used, as in the table
below.

[cols="3",options="header,unnumbered"]
|===
| Constant used to define the kilogram
| Previous SI status uncertainty
| Current SI status uncertainty

| mass of the IPK, stem:[m(cc "K")] | exact 0 | expt. stem:[1.0 xx 10^(-8)]
| Planck constant, stem:[h] | expt. stem:[1.0 xx 10^(-8)] | exact 0
|===

[[Q18]]
== The unit of the Planck constant is the unit of action, stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"]. How does fixing the numerical value of the Planck constant define the kilogram?

[[A18]]Fixing the numerical value of stem:[h] actually defines the unit of
action, stem:["unitsml(J*s)" = "unitsml(kg*m^2*s^(-1))"]. But if we
have already defined the second, stem:["unitsml(s)"], to fix the numerical
value of the caesium hyperfine transition frequency stem:[Delta nu_("Cs")],
and the metre, stem:["unitsml(m)"], to fix the numerical value of
the speed of light in vacuum, stem:[c], then fixing the magnitude
of the unit stem:["unitsml(kg*m^2*s^(-1))"] has the effect of defining
the unit stem:["unitsml(kg)"].

[[Q19]]
== Are not the current definitions of the base units in the Revised SI circular definitions, and therefore unsatisfactory?

[[A19]]No, they are not circular. A circular definition is one that makes
use of the result of the definition in formulating the definition.
The words for the individual definitions of the base units in the
current SI specify the _numerical value_ of each chosen reference
constant to define the corresponding unit, but this does not make
use of the result to formulate the definition.

[[Q20]]
== Can we still check the consistency of physics now that we have fixed the values of all the fundamental constants?

[[A20]]We have not fixed the values of all the fundamental constants, only
the [underline]#_numerical values_# of a small subset and combinations
of the constants in this subset. This has had the effect of changing
the definitions of the units, but not the equations of physics, and
it cannot prevent researchers from checking the consistency of the
equations.

[[Q21]]
== Now the physical constants stem:[c], stem:[h] and stem:[e] all have fixed numerical values. But doesn't this fix the value of the fine-structure constant, which must not be given a fixed value?

[[A21]]No. The value of the fine-structure constant continues to be determined
by experiment. In the SI, the fine-structure constant has always depended
on stem:[c], stem:[h], stem:[e] and stem:[mu_0]. The fourth constant
is the vacuum magnetic permeability, which previously defined the
ampere but now is determined experimentally from a measurement of
the fine-structure constant.

