
[[cipm1956]]
[%unnumbered]
== CIPM, 1956

[[cipm1956r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Definition of the unit of time (second)* (<<PV25_1>>)(((second (stem:["unitsml(s)"]))))

NOTE: This definition was abrogated in 1967 by the 13th CGPM (<<cgpm13th1967r1r1,Resolution 1>>).

[[cipm1956r1r1]]
==== Resolution 1
____

In virtue of the powers invested in it by Resolution 5 of the 10th Conférence Générale des Poids et Mesures, the Comité International des Poids et Mesures,

*considering*

. that the 9th General Assembly of the International Astronomical Union (Dublin, 1955) declared itself in favour of linking the second to the tropical year,

. that, according to the decisions of the 8th General Assembly of the International Astronomical Union (Rome, 1952), the second of ephemeris time (ET) is the fraction +
stem:[(12960276813) / (408986496) xx 10^(-9)] of the tropical year for 1900 January 0 at 12 h ET,

*decides*

"The second is the fraction stem:[1//31556925.9747] of the tropical year for 1900 January 0 at 12 hours ephemeris time."
____


[[cipm1956r3]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Système International d'Unités* (<<PV25_3>>)

[[cipm1956r3r3]]
==== Resolution 3
____

The Comité International des Poids et Mesures,

*considering*
(((metre (stem:["unitsml(m)"]))))

* the task entrusted to it by Resolution 6 of the 9th Conférence Générale des Poids et Mesures (CGPM) concerning the establishment of a practical system of units of measurement suitable for adoption by all countries adhering to the ((Metre Convention)),
* the documents received from twenty-one countries in reply to the enquiry requested by the 9th CGPM,
* Resolution 6 of the 10th CGPM, fixing the base units(((base unit(s)))) of the system to be established,

*recommends*

[align=left]
. that the name "Système International d'Unités" be given to the system founded on the base units(((base unit(s)))) adopted by the 10th CGPM, viz.:
____

[This is followed by the list of the six base units(((base unit(s)))) with their symbols, reproduced in Resolution 12 of the 11th CGPM (1960)].
____
[start=2]
. that the units listed in the table below be used, without excluding others which might be added later:
____

[This is followed by the table of units reproduced in paragraph 4 of Resolution 12 of the 11th CGPM (1960)].
