[[cgpm27th2022]]
[%unnumbered]
== 27th CGPM, 2022

[[cgpm27th2022r3]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*On the extension of the range of SI prefixes* (CR, in press)

[[cgpm27th2022r3r3]]
==== Resolution 3
____

The General Conference on Weights and Measures (CGPM), at its 27th meeting,

*recalling*

that decisions were made at previous meetings when it was considered timely to extend the
range of SI prefixes including Resolution 12 (paragraph 3) adopted by the CGPM at its
11th meeting (1960), Resolution 8 adopted by the CGPM at its 12th meeting (1964),
Resolution 10 adopted by the CGPM at its 15th meeting (1975), and Resolution 4 adopted by
the CGPM at its 19th meeting (1991),

*considering*

* the essential role of the International System of Units (SI) in providing confidence in the
accuracy and global comparability of measurements needed for international trade,
manufacturing, human health and safety, protection of the environment, global climate
studies and scientific research,
* the benefits of encouraging the use of SI units by providing new SI prefixes for scientific
communities that depend on measurements that are not covered by the current range,
* the needs of data science in the near future to express quantities of digital information
using orders of magnitude in excess of 1024,
* the importance of timely action to prevent unofficial prefix names being de facto adopted in
other communities,

*decides*

to add to the list of SI prefixes to be used for multiples and submultiples of units the
following prefixes:

[cols="<,<,<",options="header,unnumbered"]
|===
| Multiplying factor | Name | Symbol

| stem:[10^27]    | ronna   | stem:["unitsml(R-)"]
| stem:[10^{−27}] | ronto   | stem:["unitsml(r-)"]
| stem:[10^30]    | quetta  | stem:["unitsml(Q-)"]
| stem:[10^{−30}] | quecto  | stem:["unitsml(q-)"]
|===
____