[[cgpm27e2022]]
[%unnumbered]
== 27th CGPM, 2022

[[cgpm27e2022r3]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Sur l’extension de la liste des préfixes du SI* (CR, sous presse)

[[cgpm27e2022r3r3]]
==== Résolution 3
____

La Conférence générale des poids et mesures (CGPM), à sa 27^e^ réunion,

*rappelant* les décisions prises lors de ses précédentes réunions lorsqu’il a été considéré
opportun d’étendre la liste des préfixes du SI, notamment la Résolution 12 (paragraphe 3)
adoptée par la CGPM à sa 11^e^ réunion (1960), la Résolution 8 adoptée par la CGPM à sa
12^e^ réunion (1964), la Résolution 10 adoptée par la CGPM à sa 15^e^ réunion (1975), et la
Résolution 4 adoptée par la CGPM à sa 19^e^ réunion (1991),

*considérant*

* le rôle essentiel que joue le Système international d’unités (SI) afin d’établir la confiance
dans l’exactitude et la comparabilité au niveau mondial des mesures nécessaires pour le
commerce international, l’industrie, la santé humaine et la sécurité, la protection de
l’environnement, les études sur l’évolution du climat, ainsi que la recherche scientifique,

* les avantages à encourager l’utilisation des unités du SI en mettant de nouveaux préfixes
du SI à la disposition des communautés scientifiques qui dépendent de mesures qui ne
sont pas couvertes par les préfixes existant actuellement,

* les besoins de la science des données, dans un futur proche, afin d’exprimer des quantités
d’informations numériques d’un ordre de grandeur supérieur à stem:[10^24],

* l’importance de prendre une mesure en temps opportun afin d’éviter que des noms de
préfixe non officiels ne soient adoptés de facto par d’autres communautés,

écide d’ajouter à la liste des préfixes du SI pour la formation des noms des multiples et
sous-multiples des unités les préfixes suivants{nbsp}:


[cols="^,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[10^27]      | ronna     | stem:["unitsml(R-)"]
| stem:[10^{−27}]   | ronto     | stem:["unitsml(r-)"]
| stem:[10^30]      | quetta    | stem:["unitsml(Q-)"]
| stem:[10^{−30}]   | quecto    | stem:["unitsml(q-)"]
|===

____
