[abstract]
== The BIPM and the Metre Convention

The International Bureau of Weights and Measures (BIPM) was set up by the Metre Convention signed in Paris on 20 May 1875 by seventeen States during the final session of the diplomatic Conference of the Metre. This Convention was amended in 1921.

The BIPM has its headquarters near Paris, in the grounds (43 520 m^2^) of the Pavillon de Breteuil (Parc de Saint-Cloud) placed at its disposal by the French Government; its upkeep is financed jointly by the Member States of the Metre Convention.

The task of the BIPM is to ensure worldwide unification of measurements; its objectives are to:

* represent the world-wide measurement community, aiming to maximize its uptake and impact,
* be a centre for scientific and technical collaboration between Member States, providing capabilities for international measurement comparisons on a shared-cost basis,
* be the coordinator of the world-wide measurement system, ensuring it gives comparable and internationally accepted measurement results.

The BIPM operates under the exclusive supervision of the International Committee for Weights and Measures (CIPM) which itself comes under the authority of the General Conference on Weights and Measures (CGPM) and reports to it on the work accomplished by the BIPM.

NOTE: As of 20 May 2019 there were fifty nine Member States: Argentina, Australia, Austria, Belgium, Brazil, Bulgaria, Canada, Chile, China, Colombia, Croatia, Czech Republic, Denmark, Egypt, Finland, France, Germany, Greece, Hungary, India, Indonesia, Iran (Islamic Rep. of), Iraq, Ireland, Israel, Italy, Japan, Kazakhstan, Kenya, Korea (Republic of), Lithuania, Malaysia, Mexico, Montenegro, Netherlands, New Zealand, Norway, Pakistan, Poland, Portugal, Romania, Russian Federation, Saudi Arabia, Serbia, Singapore, Slovakia, Slovenia, South Africa, Spain, Sweden, Switzerland, Thailand, Tunisia, Turkey, Ukraine, United Arab Emirates, United Kingdom, United States of America and Uruguay

Delegates from all Member States attend the General Conference, which normally meets every four years. The function of these meetings is to:

* discuss and initiate the arrangements required to ensure the propagation and improvement of the International System of Units (SI), which is the modern form of the metric system;
* confirm the results of new fundamental metrological determinations and various scientific resolutions of international scope;
* take all major decisions concerning the finance, organization and development of the BIPM.

NOTE: Forty-two States and Economies were Associates of the General Conference: Albania, Azerbaijan, Bangladesh, Belarus, Bolivia, Bosnia and Herzegovina, Botswana, CARICOM, Chinese Taipei, Costa Rica, Cuba, Ecuador, Estonia, Ethiopia, Georgia, Ghana, Hong Kong (China), Jamaica, Kuwait, Latvia, Luxembourg, Malta, Mauritius, Moldova (Republic of), Mongolia, Namibia, North Macedonia, Oman, Panama, Paraguay, Peru, Philippines, Qatar, Seychelles, Sri Lanka, Sudan, Syrian Arab Republic, Tanzania (United Republic of), Uzbekistan, Viet Nam, Zambia, and Zimbabwe

The CIPM has eighteen members each from a different State: at present, it meets every year. The officers of this committee present an annual report on the administrative and financial position of the BIPM to the Governments of the Member States. The principal task of the CIPM is to ensure worldwide uniformity in units of measurement. It does this by direct action or by submitting proposals to the CGPM.

The activities of the BIPM, which in the beginning were limited to measurements of length and mass, and to metrological studies in relation to these quantities, have been extended to standards of measurement of electricity (1927), photometry and radiometry (1937), ionizing radiation (1960), time scales (1988) and to chemistry (2000). To this end the original laboratories, built in 1876 - 1878, were enlarged in 1929; new buildings were constructed in 1963-1964 for the ionizing radiation laboratories, in 1984 for the laser work and in 1988 for a library and offices. In 2001 a new building for the workshop, offices and meeting rooms was opened.

Some forty-five physicists and technicians work in the BIPM laboratories. They mainly conduct metrological research, international comparisons of realizations of units and calibrations of standards. An annual Director's report gives details of the work in progress.

Following the extension of the work entrusted to the BIPM in 1927, the CIPM has set up bodies, known as Consultative Committees, whose function is to provide it with information on matters that it refers to them for study and advice. These Consultative Committees, which may form temporary or permanent working groups to study special topics, are responsible for coordinating the international work carried out in their respective fields and for proposing recommendations to the CIPM concerning units.

The Consultative Committees have common regulations (Document CIPM-D-01, _Rules of procedure for the Consultative Committees (CCs) created by the CIPM, CC working groups and CC workshops_). They meet at irregular intervals. The president of each Consultative Committee is designated by the CIPM and is normally a member of the CIPM. The members of the Consultative Committees are metrology laboratories and specialized institutes, agreed by the CIPM, which send delegates of their choice. In addition, there are individual members appointed by the CIPM, and a representative of the BIPM (Document CIPM-D-01, _Rules of procedure for the Consultative Committees (CCs) created by the CIPM, CC working groups and CC workshops_). At present, there are ten such committees:

. The Consultative Committee for Electricity and Magnetism (CCEM), new name given in 1997 to the Consultative Committee for Electricity (CCE) set up in 1927;

. The Consultative Committee for Photometry and Radiometry (CCPR), new name given in 1971 to the Consultative Committee for Photometry (CCP) set up in 1933 (between 1930 and 1933 the CCE dealt with matters concerning photometry);

. The Consultative Committee for Thermometry (CCT), set up in 1937;

. The Consultative Committee for Length (CCL), new name given in 1997 to the Consultative Committee for the Definition of the Metre (CCDM), set up in 1952;

. The Consultative Committee for Time and Frequency (CCTF), new name given in 1997 to the Consultative Committee for the Definition of the Second (CCDS) set up in 1956;

. The Consultative Committee for Ionizing Radiation (CCRI), new name given in 1997 to the Consultative Committee for Standards of Ionizing Radiation (CCEMRI) set up in 1958 (in 1969 this committee established four sections: Section I (X- and stem:[gamma]-rays, electrons), Section II (Measurement of radionuclides), Section III (Neutron measurements), Section IV (stem:[alpha]-energy standards); in 1975 this last section was dissolved and Section II was made responsible for its field of activity);

. The Consultative Committee for Units (CCU), set up in 1964 (this committee replaced the Commission for the System of Units set up by the CIPM in 1954);

. The Consultative Committee for Mass and Related Quantities (CCM), set up in 1980;

. The Consultative Committee for Amount of Substance: Metrology in Chemistry and Biology (CCQM), set up in 1993;

. The Consultative Committee for Acoustics, Ultrasound and Vibration (CCAUV), set up in 1999.

The proceedings of the General Conference and the CIPM are published by the BIPM in the following series:

* _Report of the meeting of the General Conference on Weights and Measures_;
* _Report of the meeting of the International Committee for Weights and Measures_.

The CIPM decided in 2003 that the reports of meetings of the Consultative Committees should no longer be printed, but would be placed on the BIPM website, in their original language.

The BIPM also publishes monographs on special metrological subjects and, under the title The International System of Units (SI), a brochure, periodically updated, in which are collected all the decisions and recommendations concerning units.

The collection of the _Travaux et Mémoires du Bureau International des Poids et Mesures_ (22 volumes published between 1881 and 1966) and the _Recueil de Travaux du Bureau International des Poids et Mesures_ (11 volumes published between 1966 and 1988) ceased by a decision of the CIPM.

The scientific work of the BIPM is published in the open scientific literature.

Since 1965 _Metrologia_, an international journal published under the auspices of the CIPM, has printed articles dealing with scientific metrology, improvements in methods of measurement, work on standards and units, as well as reports concerning the activities, decisions and recommendations of the various bodies created under the Metre Convention.
