== Introduction

=== The SI and the ((defining constants))
index-range:si_2[(((International System of Units (SI))))]

This brochure presents information on the definition and use of the International System of Units, universally known as the SI (from the French _Système international d'unités_), for which the General Conference on Weights and Measures (CGPM) has responsibility. In 1960 the 11th CGPM formally defined and established the SI and has subsequently revised it from time to time in response to the requirements of users and advances in science and technology. The most recent and perhaps the most significant revision of the SI since its establishment was made by the 26th CGPM (2018) and is documented in this 9th edition of the SI Brochure. The ((Metre Convention))(((Convention du Mètre))) and its organs, the CGPM, the Comité Internationaldes Poids et Mesures (CIPM), the Bureau International des Poids et Mesures (BIPM), and the Consultative Committees are described in the text <<bipm_metre_convention,"The BIPM and the Metre Convention">> on page <<bipm_metre_convention,pagenumber%>>.

The SI is a consistent system of units for use in all aspects of life, including international trade, manufacturing, security, health and safety, protection of the environment, and in the basic science that underpins all of these. The system of quantities underlying the SI and the equations relating them are based on the present description of nature and are familiar to all scientists, technologists and engineers.

The definition of the SI units is established in terms of a set of seven ((defining constants)). The complete system of units can be derived from the fixed values of these ((defining constants)), expressed in the units of the SI. These seven ((defining constants)) are the most fundamental feature of the definition of the entire system of units. These particular constants were chosen after having been identified as being the best choice, taking into account the previous definition of the SI, which was based on seven base units(((base unit(s)))), and progress in science.

A variety of experimental methods described by the CIPM Consultative Committees may be used to realize the definitions. Descriptions of these realizations are also referred to as "mises en pratique". Realizations may be revised whenever new experiments are developed; for this reason advice on realizing the definitions is not included in this brochure but is available on the BIPM website.

=== Motivation for the use of ((defining constants)) to define the SI

Historically, SI units have been presented in terms of a set of – most recently seven – _base units_(((base unit(s)))). All other units, described as _derived units,_ are constructed as products of powers of the base units(((base unit(s)))).

Different types of definitions for the base units(((base unit(s)))) have been used: specific properties of artefacts such as the ((mass)) of the international prototype for the unit kilogram; a specific physical state such as the triple point of water for the unit kelvin; idealized experimental prescriptions as in the case of the ampere(((ampere (A)))) and the candela(((candela (cd)))); or constants of nature such as the speed of light for the definition of the unit metre. (((metre (m))))

To be of any practical use, these units not only have to be defined, but they also have to be realized physically for dissemination. In the case of an artefact, the definition and the realization are equivalent – a path that was pursued by advanced ancient civilizations. Although this is simple and clear, artefacts involve the risk of loss, damage or change. The other types of unit definitions are increasingly abstract or idealized. Here, the realizations are separated conceptually from the definitions so that the units can, as a matter of principle, be realized independently at any place and at any time. In addition, new and superior realizations may be introduced as science and technologies develop, without the need to redefine the unit. These advantages – most obviously seen with the history of the definition of the metre from artefacts through an atomic reference transition to the fixed numerical value of the speed of light – led to the decision to define all units by using ((defining constants)).

The choice of the base units(((base unit(s)))) was never unique, but grew historically and became familiar to users of the SI. This description in terms of base and derived units is maintained in the present definition of the SI, but has been reformulated as a consequence of adoption of the ((defining constants)). [[si_2]]

=== Implementation of the SI

The definitions of the SI units, as decided by the CGPM, represent the highest reference level for measurement traceability to the SI.

Metrology institutes around the world establish the practical realizations of the definitions in order to allow for traceability of measurements to the SI. The Consultative Committees provide the framework for establishing the equivalence of the realizations in order to harmonize traceability world-wide.

Standardization bodies may specify further details for quantities and units and rules for their application, where these are needed by interested parties. Whenever SI units are involved, these standards must refer to the definitions by the CGPM. Many such specifications are listed for example in the standards developed by the International Organization for Standardization and the International Electrotechnical Commission (((ISO/IEC 80000 series)) of international standards).

(((legislation on units)))
Individual countries have established rules concerning the use of units by national legislation, either for general use or for specific areas such as commerce, health, public safety and education. In almost all countries, this legislation is based on the SI. The International Organization of Legal Metrology (OIML) is charged with the international harmonization of the technical specifications of this legislation.
