== The International System of Units

=== Defining the unit of a quantity

The value of a quantity is generally expressed as the product of a number and a unit. The unit is simply a particular example of the quantity concerned which is used as a reference, and the number is the ratio of the value of the quantity to the unit.

NOTE: For example, the speed of light in vacuum is a constant of nature, denoted by stem:[c], whose value in SI units is given by the relation stem:[c = 299792458 " "rm(m)//rm(s)] where the numerical value is stem:[299792458] and the unit is stem:[rm(m)//rm(s)].

For a particular quantity different units may be used. For example, the value of the speed stem:[v] of a particle may be expressed as stem:[v = 25 " "rm(m)//rm(s)] or stem:[v = 90 " "rm(km)//rm(h)], where metre per second and kilometre per hour are alternative units for the same value of the quantity speed.

Before stating the result of a measurement, it is essential that the quantity being presented is adequately described. This may be simple, as in the case of the length of a particular steel rod, but can become more complex when higher accuracy is required and where additional parameters, such as temperature, need to be specified.

When a measurement result of a quantity is reported, the *_estimated value_* of the measurand (the quantity to be measured), and the *_uncertainty_* associated with that value, are necessary. Both are expressed in the same unit.

=== Definition of the SI

As for any quantity, the value of a fundamental constant can be expressed as the product of a number and a unit.

[NOTE]
====
Quotients of SI units may be expressed using either a solidus (/) or a negative exponent (^−^)

[align=left]
For example, +
stem:[rm(m)//rm(s) = rm(m)" "rm(s)^{-1}] +
stem:[rm(mol)//rm(mol) = rm(mol)" "rm(mol)^{-1}]
====

The definitions below specify the exact numerical value of each constant when its value is expressed in the corresponding SI unit. By fixing the exact numerical value, the unit becomes defined, since the product of the *_numerical value_* and the *_unit_* has to equal the *_value_* of the constant, which is postulated to be invariant.

The seven constants are chosen in such a way that any unit of the SI can be written either through a defining constant itself or through products or quotients of defining constants.

*The International System of Units, the SI, is the system of units in which:*

* *the unperturbed ground state hyperfine transition frequency of the caesium 133 atom, stem:[Delta nu_("Cs")], is stem:[9192631770 " "rm(Hz)],*
* *the speed of light in vacuum, stem:[c], is stem:[299792458 " "rm(m)//rm(s)],* 
* *the Planck constant, stem:[h], is stem:[6.62607015 xx 10^(−34) " "rm(J)" "rm(s)],* 
* *the elementary charge, stem:[e], is stem:[1.602176634 xx 10^(−19) " "rm(C)],* 
* *the Boltzmann constant, stem:[k], is stem:[1.380649 xx 10^(-23) " "rm(J)//rm(K)],* 
* *the Avogadro constant, stem:[N_"A"], is stem:[6.02214076 xx 10^(23) " "rm(mol)^(−1)],*
* *the luminous efficacy of monochromatic radiation of frequency stem:[540 xx 10^(12) " "rm(Hz)], stem:[K_("cd")], is stem:[683 " "rm(lm)//rm(W)],*

where the hertz, joule, coulomb, lumen, and watt, with unit symbols stem:[rm(Hz)], stem:[rm(J)], stem:[rm(C)], stem:[rm(lm)], and stem:[rm(W)], respectively, are related to the units second, metre, kilogram, ampere, kelvin, mole, and candela, with unit symbols stem:[rm(s)], stem:[rm(m)], stem:[rm(kg)], stem:[rm(A)], stem:[rm(K)], stem:[rm(mol)], and stem:[rm(cd)], respectively, according to stem:[rm(Hz) = rm(s)^(–1)], stem:[rm(J) = rm(kg)" "rm(m)^2 " "rm(s)^(–2)], stem:[rm(C) = rm(A)" "rm(s)], stem:[rm(lm) = rm(cd)" "rm(m)^2 " "rm(m)^(–2) = rm(cd)" "rm(sr)], and stem:[rm(W) = rm(kg)" "rm(m)^2 " "rm(s)^(–3)].

The numerical values of the seven defining constants have no uncertainty.

.The seven defining constants of the SI and the seven corresponding units they define
[cols="<,<,<,<"]
|===
| Defining constant | Symbol | Numerical value | Unit

| hyperfine transition frequency of stem:["Cs"] | stem:[Delta nu_("Cs")] | stem:[9192631770] | stem:[rm(Hz)]
| speed of light in vacuum | stem:[c] | stem:[299792458] | stem:[rm(m)" "rm(s)^(−1)]
| Planck constant | stem:[h] | stem:[6.62607015 xx 10^(−34)] | stem:[rm(J)" "rm(s)]
| elementary charge | stem:[e] | stem:[1.602176634 xx 10^(−19)] | stem:[rm(C)]
| Boltzmann constant | stem:[k] | stem:[1.380649 xx 10^(−23)] | stem:[rm(J)" "rm(K)^(−1)]
| Avogadro constant | stem:[N_"A"] | stem:[6.02214076 xx 10^(23)] | stem:[rm(mol)^(−1)]
| luminous efficacy | stem:[K_("cd")] | stem:[683] | stem:[rm(lm)" "rm(W)^(−1)]
|===

Preserving continuity, as far as possible, has always been an essential feature of any changes to the International System of Units. The numerical values of the defining constants have been chosen to be consistent with the earlier definitions in so far as advances in science and knowledge allow.

==== The nature of the seven defining constants

The nature of the defining constants ranges from fundamental constants of nature to technical constants.

The use of a constant to define a unit disconnects definition from realization. This offers the possibility that completely different or new and superior practical realizations can be developed, as technologies evolve, without the need to change the definition.

A technical constant such as stem:[K_("cd")], the luminous efficacy of monochromatic radiation of frequency stem:[540 xx 10^(12) " "rm(Hz)] refers to a special application. In principle, it can be chosen freely, such as to include conventional physiological or other weighting factors. In contrast, the use of a fundamental constant of nature, in general, does not allow this choice because it is related to other constants through the equations of physics.

The set of seven defining constants has been chosen to provide a fundamental, stable and universal reference that simultaneously allows for practical realizations with the smallest uncertainties. The technical conventions and specifications also take historical developments into account.

Both the Planck constant stem:[h] and the speed of light in vacuum stem:[c] are properly described as fundamental. They determine quantum effects and space-time properties, respectively, and affect all particles and fields equally on all scales and in all environments.

The elementary charge stem:[e] corresponds to a coupling strength of the electromagnetic force via the fine-structure constant stem:[alpha = e^2//(2c epsilon_0h)] where stem:[epsilon_0] is the vacuum electric permittivity orelectric constant. Some theories predict a variation of stem:[alpha] over time. The experimental limits of the maximum possible variation in stem:[alpha] are so low, however, that any effect on foreseeable practical measurements can be excluded.

The Boltzmann constant stem:[k] is a proportionality constant between the quantities temperature (with unit kelvin) and energy (with unit joule), whereby the numerical value is obtained from historical specifications of the temperature scale. The temperature of a system scales with the thermal energy, but not necessarily with the internal energy of a system. In statistical physics the Boltzmann constant connects the entropy stem:[S] with the number stem:[ii Omega] of quantum-mechanically accessible states, stem:[S = k " ln " ii Omega].

The caesium frequency stem:[Delta nu_("Cs")], the unperturbed ground-state hyperfine transition frequency of the caesium 133 atom, has the character of an atomic parameter, which may be affected by the environment, such as electromagnetic fields. However, the underlying transition is well understood, stable and a good choice as a reference transition under practical considerations. The choice of an atomic parameter like stem:[Delta nu_("Cs")] does not disconnect definition and realization in the same way that stem:[h], stem:[c], stem:[e], or stem:[k] do, but specifies the reference.

The Avogadro constant stem:[N_"A"] is a proportionality constant between the quantity amount of substance (with unit mole) and the quantity for counting entities (with unit one, symbol stem:[1]). Thus it has the character of a constant of proportionality similar to the Boltzmann constant stem:[k].

The luminous efficacy of monochromatic radiation of frequency stem:[540 xx 10^(12) " " rm(Hz)], stem:[K_("cd")], is a technical constant that gives an exact numerical relationship between the purely physical characteristics of the radiant power stimulating the human eye (stem:[rm(W)]) and its photobiological response defined by the luminous flux due to the spectral responsivity of a standard observer (stem:[rm(lm)]) at a frequency of stem:[540 xx 10^(12) text( hertz)].

=== Definitions of the SI units

Prior to the definitions adopted in 2018, the SI was defined through seven _base units_ from which the _derived units_ were constructed as products of powers of the _base units._ Defining the SI by fixing the numerical values of seven defining constants has the effect that this distinction is, in principle, not needed, since all units, _base_ as well as _derived units_, may be constructed directly from the defining constants. Nevertheless, the concept of base and derived units is maintained because it is useful and historically well established, noting also that the ISO/IEC 80000 series of Standards specify base and derived quantities which necessarily correspond to the SI base and derived units defined here.

==== Base units

The base units of the SI are listed in <<table2>>.

[[table2]]
.SI base units
|===
2+h| Base quantity 2+h| Base unit
<h| Name <h| Typical symbol <h| Name <h| Symbol

<| time <| stem:[t] <| second <| stem:[rm(s)]
<| length <| stem:[l, x, r],etc. <| metre <| stem:[rm(m)]
<| mass <| stem:[m] <| kilogram <| stem:[rm(kg)]
<| electric current <| stem:[I, i] <| ampere <| stem:[rm(A)]
<| thermodynamic temperature <| stem:[T] <| kelvin <| stem:[rm(K)]
<| amount of substance <| stem:[n] <| mole <| stem:[rm(mol)]
<| luminous intensity <| stem:[I_"v"] <| candela <| stem:[rm(cd)]
|===

NOTE: The symbols for quantities are generally single letters of the Latin or Greek alphabets, printed in an italic font, and are _recommendations_. The symbols for units are printed in an upright (roman) font and are _mandatory_, see <<unit_symbols>>.

Starting from the definition of the SI in terms of fixed numerical values of the defining constants, definitions of each of the seven base units are deduced by using, as appropriate, one or more of these defining constants to give the following set of definitions:


*The second*

*The second, symbol stem:[rm(s)], is the SI unit of time. It is defined by taking the fixed numerical value of the caesium frequency, stem:[Delta nu_("Cs")], the* *unperturbed ground-state hyperfine transition frequency of the caesium 133 atom, to be stem:[9192631770] when expressed in the unit stem:[rm(Hz)], which is equal to stem:[rm(s)^(−1)].*

This definition implies the exact relation stem:[Delta nu_("Cs") = 9192631770 " "rm(Hz)]. Inverting this relation gives an expression for the unit second in terms of the defining constant stem:[Delta nu_("Cs")]:

[stem%unnumbered]
++++
1 " "rm(Hz) = (Delta nu_("Cs"))/(9192631770) " or " 1 " "rm(s) = (9192631770)/(Delta nu_("Cs"))
++++

The effect of this definition is that the second is equal to the duration of stem:[9192631770] periods of the radiation corresponding to the transition between the two hyperfine levels of the unperturbed ground state of the ^133^Cs atom.

The reference to an unperturbed atom is intended to make it clear that the definition of the SI second is based on an isolated caesium atom that is unperturbed by any external field, such as ambient black-body radiation.

The second, so defined, is the unit of proper time in the sense of the general theory of relativity. To allow the provision of a coordinated time scale, the signals of different primary clocks in different locations are combined, which have to be corrected for relativistic caesium frequency shifts (see <<si_units_gtr,nosee%>>).

The CIPM has adopted various secondary representations of the second, based on a selected number of spectral lines of atoms, ions or molecules. The unperturbed frequencies of these lines can be determined with a relative uncertainty not lower than that of the realization of the second based on the ^133^Cs hyperfine transition frequency, but some can be reproduced with superior stability.

*The metre*

*The metre, symbol stem:[rm(m)], is the SI unit of length. It is defined by taking the fixed numerical value of the speed of light in vacuum, stem:[c], to be stem:[299792458] when expressed in the unit stem:[rm(m)" "rm(s)^(−1)], where the second is defined in terms of the caesium frequency stem:[Delta nu_("Cs")].*

This definition implies the exact relation stem:[c = 299792458 " "rm(m)" "rm(s)^(−1)].Inverting this relation gives an exact expression for the metre in terms of the defining constants stem:[c] and stem:[Delta nu_("Cs")]:

[stem%unnumbered]
++++
1 " "rm(m) = (c/(299792458)) " "rm(s) = (9192631770)/(229792458) c/(Delta nu_("Cs")) ~~ 30.663319 c/(Delta nu_("Cs")).
++++

The effect of this definition is that one metre is the length of the path travelled by light in vacuum during a time interval with duration of stem:[1//299792458] of a second.

*The kilogram*

*The kilogram, symbol stem:[rm(kg)], is the SI unit of mass. It is defined by taking the fixed numerical value of the Planck constant, stem:[h], to be stem:[6.62607015 xx 10^(−34)] when expressed in the unit stem:[rm(J)" "rm(s)], which is equal to stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−1)], where the metre and the second are defined in terms of stem:[c] and stem:[Delta nu_("Cs")].*

This definition implies the exact relation stem:[h = 6.62607015 xx 10^(−34) " "rm(kg)" "rm(m)^2 " "rm(s)^(−1)]. Inverting this relation gives an exact expression for the kilogram in terms of the three defining constants stem:[h], stem:[Delta nu_("Cs")] and stem:[c]:

[stem%unnumbered]
++++
1 " "rm(kg) = (h/(6.62607015 xx 10^(-34)))rm(m)^(-2)" "rm(s)
++++

which is equal to

[stem%unnumbered]
++++
1 " "rm(kg) = ((299792458)^2)/((6.62607015 xx 10^(-34))(9192631770)) (hDelta nu_("Cs"))/(c^2) ~~ 1.4755214 xx 10^(40) (hDelta nu_("Cs"))/(c^2).
++++

The effect of this definition is to define the unit stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−1)] (the unit of both the physical quantities action and angular momentum). Together with the definitions of the second and the metre this leads to a definition of the unit of mass expressed in terms of the Planck constant stem:[h].

The previous definition of the kilogram fixed the value of the mass of the international prototype of the kilogram, stem:[m(cc "K")], to be equal to one kilogram exactly and the value of the Planck constant stem:[h] had to be determined by experiment. The present definition fixes the numerical value of stem:[h] exactly and the mass of the prototype has now to be determined by experiment.

The number chosen for the numerical value of the Planck constant in this definition is such that at the time of its adoption, the kilogram was equal to the mass of the international prototype, stem:[m(cc "K") = 1 " "rm(kg)], with a relative standard uncertainty of stem:[1 xx 10^(−8)], which was the standard uncertainty of the combined best estimates of the value of the Planck constant at that time.

Note that with the present definition, primary realizations can be established, in principle, at any point in the mass scale.

*The ampere*

*The ampere, symbol stem:[rm(A)], is the SI unit of electric current. It is defined by taking the fixed numerical value of the elementary charge, stem:[e], to be stem:[1.602176634 xx 10^(−19)] when expressed in the unit stem:[rm(C)], which is equal to stem:[rm(A)" "rm(s)], where the second is defined in terms of stem:[Delta nu_("Cs")].*

This definition implies the exact relation stem:[e = 1.602176634 xx 10^(−19) " "rm(A)" "rm(s)].Inverting this relation gives an exact expression for the unit ampere in terms of the defining constants stem:[e] and stem:[Delta nu_("Cs")]:

[stem%unnumbered]
++++
1 " "rm(A) = (e/(1.602176634 xx 10^(-19)))" "rm(s)^(-1)
++++

which is equal to

[stem%unnumbered]
++++
1 " "rm(A) = 1/((9192631770)(1.602176634 xx 10^(-19)))Delta nu_("Cs") e ~~ 6.7896868 xx 10^8 Delta nu_("Cs") e.
++++

The effect of this definition is that one ampere is the electric current corresponding to the flow of stem:[1//(1.602176634 xx 10^(−19))] elementary charges per second.

The previous definition of the ampere was based on the force between two current carrying conductors and had the effect of fixing the value of the vacuum magnetic permeability stem:[mu_0] (also known as the magnetic constant) to be exactly stem:[4pi xx 10^(−7) " "rm(H)" "rm(m)^(−1) = 4pi xx 10^(−7) " "rm(N)" "rm(A)^(−2)], where stem:[rm(H)] and stem:[rm(N)] denote the coherent derived units henry and newton, respectively. The new definition of the ampere fixes the value of stem:[e] instead of stem:[mu_0]. As a result, stem:[mu_0] must be determined experimentally.

It also follows that since the vacuum electric permittivity stem:[epsilon_0] (also known as the electric constant), the characteristic impedance of vacuum stem:[Z_0], and the admittance of vacuum stem:[Y_0] are equal to stem:[1//mu_0 c^2], stem:[mu_0 c], and stem:[1//mu_0c], respectively, the values of stem:[epsilon_0], stem:[Z_0], and stem:[Y_0] must now also be determined experimentally, and are affected by the same relative standard uncertainty as stem:[mu_0] since stem:[c] is exactly known. The product stem:[epsilon_0 mu_0 = 1//c^2] and quotient stem:[Z_0//mu_0 = c] remain exact. At the time of adopting the present definition of the ampere, stem:[mu_0] was equal to stem:[4pi xx 10^(−7) " "rm(H)//rm(m)] with a relative standard uncertainty of stem:[2.3 xx 10^(−10)].

*The kelvin*

*The kelvin, symbol stem:[rm(K)], is the SI unit of thermodynamic temperature. It is defined by taking the fixed numerical value of the Boltzmann constant, stem:[k], to be stem:[1.380649 xx 10^(−23)] when expressed in the unit stem:[rm(J)" "rm(K)^(−1)], which is equal to stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(K)^(−1)], where the kilogram, metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta nu_("Cs")].*

This definition implies the exact relation stem:[k = 1.380649 xx 10^(−23) " "rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(K)^(−1)]. Inverting this relation gives an exact expression for the kelvin in terms of the defining constants stem:[k], stem:[h] and stem:[Delta nu_("Cs")]:

[stem%unnumbered]
++++
1 " "rm(K) = ((1.380649 xx 10^(-23))/k) " "rm(kg)" "rm(m)^2 " "rm(s)^(-2)
++++

which is equal to

[stem%unnumbered]
++++
1 " "rm(K) = (1.380649 xx 10^(-23))/((6.62607015 xx 10^(-34))(9192631770)) (Delta nu_("Cs")h)/k ~~ 2.2666653 (Delta nu_("Cs")h)/k .
++++

The effect of this definition is that one kelvin is equal to the change of thermodynamic temperature that results in a change of thermal energy stem:[kT] by stem:[1.380649 xx 10^(−23) " "rm(J)].

The previous definition of the kelvin set the temperature of the triple point of water, stem:[T_("TPW")], to be exactly stem:[273.16 " "rm(K)]. Due to the fact that the present definition of the kelvin fixes the numerical value of stem:[k] instead of stem:[T_("TPW")], the latter must now be determined experimentally. At the time of adopting the present definition stem:[T_("TPW")] was equal to stem:[273.16 " "rm(K)] with a relative standard uncertainty of stem:[3.7 xx 10^(−7)] based on measurements of stem:[k] made prior to the redefinition.

As a result of the way temperature scales used to be defined, it remains common practice to express a thermodynamic temperature, symbol stem:[T], in terms of its difference from the reference temperature stem:[T_0 = 273.15 " "rm(K)], close to the ice point. This difference is called the Celsius temperature, symbol stem:[t], which is defined by the quantity equation

[stem%unnumbered]
++++
t = T − T_0 .
++++

The unit of Celsius temperature is the degree Celsius, symbol stem:["°"rm(C)], which is by definition equal in magnitude to the unit kelvin. A difference or interval of temperature may be expressed in kelvin or in degrees Celsius, the numerical value of the temperature difference being the same in either case. However, the numerical value of a Celsius temperature expressed in degrees Celsius is related to the numerical value of the thermodynamic temperature expressed in kelvin by the relation

[stem%unnumbered]
++++
t "/°"rm(C) = T//rm(K) − 273.15
++++

(see <<quantity_value>> for an explanation of the notation used here).

The kelvin and the degree Celsius are also units of the International Temperature Scale of 1990 (ITS-90) adopted by the CIPM in 1989 in Recommendation 5 (CI-1989, PV, *57*, 115). Note that the ITS-90 defines two quantities stem:[T_(90)] and stem:[t_(90)] which are close approximations to the corresponding thermodynamic temperatures stem:[T] and stem:[t].

Note that with the present definition, primary realizations of the kelvin can, in principle, be established at any point of the temperature scale.

*The mole*

*The mole, symbol stem:[rm(mol)], is the SI unit of amount of substance. One mole contains exactly stem:[6.02214076 xx 10^(23)] elementary entities. This number is the fixed numerical value of the Avogadro constant, stem:[N_"A"], when expressed in the unit stem:[rm(mol)^(−1)] and is called the Avogadro number.*

*The amount of substance, symbol stem:[n], of a system is a measure of the number of specified elementary entities. An elementary entity may be an atom, a molecule, an ion, an electron, any other particle or specified group of particles.*

This definition implies the exact relation stem:[N_"A" = 6.02214076 xx 10^(23) " "rm(mol)^(−1)]. Inverting this relation gives an exact expression for the mole in terms of the defining constant stem:[N_"A"]:

[stem%unnumbered]
++++
1 " "rm(mol) = ((6.02214076 xx 10^(23))/N_"A").
++++

The effect of this definition is that the mole is the amount of substance of a system that contains stem:[6.02214076 xx 10^(23)] specified elementary entities.

The previous definition of the mole fixed the value of the molar mass of carbon 12, stem:[M](^12^C), to be exactly stem:[0.012 " "rm(kg)//rm(mol)]. According to the present definition stem:[M](^12^C) is no longer known exactly and must be determined experimentally. The value chosen for stem:[N_"A"] is such that at the time of adopting the present definition of the mole, stem:[M](^12^C) was equal to stem:[0.012 " "rm(kg)//rm(mol)] with a relative standard uncertainty of stem:[4.5 xx 10^(−10)].

The molar mass of any atom or molecule stem:["X"] may still be obtained from its relative atomic mass from the equation

[stem%unnumbered]
++++
ii(M)("X") = A_"r"("X")["M"(text()^(12)C)//12] = A_"r"("X")M_"u"
++++

and the molar mass of any atom or molecule stem:["X"] is also related to the mass of the elementary entity stem:[m("X")] by the relation

[stem%unnumbered]
++++
ii(M)("X") = N_"A" m("X") = N_"A" A_"r"("X") m_"u" .
++++

In these equations stem:[M_"u"] is the molar mass constant, equal to stem:[M](^12^C)/12 and stem:[m_"u"] is the unified atomic mass constant, equal to stem:[m](^12^C)/12. They are related to the Avogadro constant through the relation

[stem%unnumbered]
++++
M_"u" = N_"A" m_"u" .
++++

In the name "amount of substance", the word "substance" will typically be replaced by words to specify the substance concerned in any particular application, for example "amount of hydrogen chloride", or "amount of benzene". It is important to give a precise definition of the entity involved (as emphasized in the definition of the mole); this should preferably be done by specifying the molecular chemical formula of the material involved. Although the word "amount" has a more general dictionary definition, the abbreviation of the full name "amount of substance" to "amount" may be used for brevity. This also applies to derived quantities such as "amount-of-substance concentration", which may simply be called "amount concentration". In the field of clinical chemistry, the name "amount-of-substance concentration" is generally abbreviated to "substance concentration".

*The candela*

*The candela, symbol stem:[rm(cd)], is the SI unit of luminous intensity in a given direction. It is defined by taking the fixed numerical value of the luminous efficacy of monochromatic radiation of frequency stem:[540 xx 10^(12) " "rm(Hz)], stem:[K_("cd")], to be 683 when expressed in the unit stem:[rm(lm)" "rm(W)^(−1)], which is equal to stem:[rm(cd)" "rm(sr)" "rm(W)^(−1)], or stem:[rm(cd)" "rm(sr)" "rm(kg)^(−1) " "rm(m)^(−2) " "rm(s)^3], where the kilogram, metre and second are defined in terms of stem:[h], stem:[c] and stem:[Delta nu_("Cs")].*

This definition implies the exact relation stem:[K_("cd") = 683 " "rm(cd)" "rm(sr)" "rm(kg)^(−1) " "rm(m)^(−2) " "rm(s)^3] for monochromatic radiation of frequency stem:[nu = 540 xx 10^(12) " "rm(Hz)]. Inverting this relation gives an exact expression for the candela in terms of the defining constants stem:[K_("cd")], stem:[h] and stem:[Delta nu_("Cs")]:

[stem%unnumbered]
++++
1 " "rm(cd) = (K_("cd")/683) " "rm(kg)" "rm(m)^2 " "rm(s)^(-3) " "rm(sr)^(-1)
++++

which is equal to

[stem%unnumbered]
++++
1 " "rm(cd) = 1/((6.62607015 xx 10^(-34))(9192631770)^{2} 683)(Delta nu_("Cs"))^2 h K_("cd")
++++

[stem%unnumbered]
++++
~~ 2.6148305 xx 10^(10)(Delta nu_("Cs"))^2 h K_("cd") .
++++

The effect of this definition is that one candela is the luminous intensity, in a  given direction, of a source that emits monochromatic radiation of frequency stem:[540 xx 10^(12) " "rm(Hz)] and has a radiant intensity in that direction of stem:[(1//683) " "rm(W)" "rm(sr)^(−1)]. The definition of the steradian is given below <<table4>>.

==== Practical realization of SI units

The highest-level experimental methods used for the realization of units using the equations of physics are known as primary methods. The essential characteristic of a primary method is that it allows a quantity to be measured in a particular unit by using only measurements of quantities that do not involve that unit. In the present formulation of the SI, the basis of the definitions is different from that used previously, so that new methods may be used for the practical realization of SI units.

Instead of each definition specifying a particular condition or physical state, which sets a fundamental limit to the accuracy of realization, a user is now free to choose any convenient equation of physics that links the defining constants to the quantity intended to be measured. This is a much more general way of defining the basic units of measurement. It is not limited by today's science or technology; future developments may lead to different ways of realizing units to a higher accuracy. When defined this way, there is, in principle, no limit to the accuracy with which a unit might be realized. The exception remains the definition of the second, in which the original microwave transition of caesium must remain, for the time being, the basis of the definition. For a more comprehensive explanation of the realization of SI units see <<appendix2>>.

[[dimensions_of_quantities]]
==== Dimensions of quantities

Physical quantities can be organized in a system of dimensions, where the system used is decided by convention. Each of the seven base quantities used in the SI is regarded as having its own dimension. The symbols used for the base quantities and the symbols used to denote their dimension are shown in <<table3>>.

[[table3]]
.Base quantities and dimensions used in the SI
[cols="<,<,<"]
|===
| Base quantity | Typical symbol for quantity | Symbol for dimension

| time | stem:[t] | stem:[sf "T"]
| length | stem:[l, x, r], etc. | stem:[sf "L"]
| mass | stem:[m] | stem:[sf "M"]
| electric current | stem:[I, i] | stem:[sf "I"]
| thermodynamic temperature | stem:[T] | stem:[Theta]
| amount of substance | stem:[n] | stem:[sf "N"]
| luminous intensity | stem:[I_("v")] | stem:[sf "J"]
|===

All other quantities, with the exception of counts, are derived quantities, which may be written in terms of base quantities according to the equations of physics. The dimensions of the derived quantities are written as products of powers of the dimensions of the base quantities using the equations that relate the derived quantities to the base quantities. In general the dimension of any quantity stem:[Q] is written in the form of a dimensional product,

[stem%unnumbered]
++++
"dim "Q = sf "T"^(alpha) sf "L"^(beta) sf "M"^(gamma) sf "I"^(delta) Theta^(epsilon) sf "N"^(zeta) sf "J"^(eta)
++++

where the exponents stem:[alpha, beta, gamma, delta, epsilon, zeta] and stem:[eta], which are generally small integers, which can be positive, negative, or zero, are called the dimensional exponents.

There are quantities stem:[Q] for which the defining equation is such that all of the dimensional exponents in the equation for the dimension of stem:[Q] are zero. This is true in particular for any quantity that is defined as the ratio of two quantities of the same kind. For example, the refractive index is the ratio of two speeds and the relative permittivity is the ratio of the permittivity of a dielectric medium to that of free space. Such quantities are simply numbers. The associated unit is the unit one, symbol stem:[1], although this is rarely explicitly written (see <<stating_quantity,nosee%>>).

There are also some quantities that cannot be described in terms of the seven base quantities of the SI, but have the nature of a count. Examples are a number of molecules, a number of cellular or biomolecular entities (for example copies of a particular nucleic acid sequence), or degeneracy in quantum mechanics. Counting quantities are also quantities with the associated unit one.

The unit one is the neutral element of any system of units – necessary and present automatically. There is no requirement to introduce it formally by decision. Therefore, a formal traceability to the SI can be established through appropriate, validated measurement procedures.

Plane and solid angles, when expressed in radians and steradians respectively, are in effect also treated within the SI as quantities with the unit one (see <<plane_angles,nosee%>>). The symbols rad and sr are written explicitly where appropriate, in order to emphasize that, for radians or steradians, the quantity being considered is, or involves the plane angle or solid angle respectively. For steradians it emphasizes the distinction between units of flux and intensity in radiometry and photometry for example. However, it is a long-established practice in mathematics and across all areas of science to make use of stem:[rm(rad) = 1] and stem:[rm(sr) = 1]. For historical reasons the radian and steradian are treated as derived units, as described in <<derived_units>>.

It is especially important to have a clear description of any quantity with unit one (see <<stating_quantity,nosee%>>) that is expressed as a ratio of quantities of the same kind (for example length ratios or amount fractions) or as a count (for example number of photons or decays).

[[derived_units]]
==== Derived units

Derived units are defined as products of powers of the base units. When the numerical factor of this product is one, the derived units are called _coherent derived units_. The base and coherent derived units of the SI form a coherent set, designated the _set of coherent SI units_. The word "coherent" here means that equations between the numerical values of quantities take exactly the same form as the equations between the quantities themselves.

Some of the coherent derived units in the SI are given special names. <<table4,nosee%>> lists 22 SI units with special names. Together with the seven base units (<<table2,nosee%>>) they form the core of the set of SI units. All other SI units are combinations of some of these 29 units.

It is important to note that any of the seven base units and 22 SI units with special names can be constructed directly from the seven defining constants. In fact, the units of the seven defining constants include both base and derived units.

The CGPM has adopted a series of prefixes for use in forming the decimal multiples and sub-multiples of the coherent SI units (see <<multiples,nosee%>>). They are convenient for expressing the values of quantities that are much larger than or much smaller than the coherent unit. However, when prefixes are used with SI units, the resulting units are no longer coherent, because the prefix introduces a numerical factor other than one. Prefixes may be used with any of the 29 SI units with special names with the exception of the base unit kilogram, which is further explained in <<multiples>>.

[[table4]]
.The 22 SI units with special names and symbols
[cols="<,<,<,<"]
|===
| Derived quantity | Special name of unit | Unit expressed in terms of base units footnote:[The order of symbols for base units in this Table is different from that in the 8th edition following a decision by the CCU at its 21st meeting (2013) to return to the original order in Resolution 12 of the 11th CGPM (1960) in which newton was written stem:[rm(kg)" "rm(m)" "rm(s)^(−2)], the joule as stem:[rm(kg)" "rm(m)^2" "rm(s)^(−2)] and stem:[rm(J)" "rm(s)] as stem:[rm(kg)" "rm(m)^(−2) " "rm(s)^(−1)]. The intention was to reflect the underlying physics of the corresponding quantity equations although for some more complex derived units this may not be possible.] | Unit expressed in terms of other SI units

| plane angle | radian footnote:[The radian is the coherent unit for plane angle. One radian is the https://en.wikipedia.org/wiki/Angle[angle] https://en.wikipedia.org/wiki/Subtended[subtended] at the centre of a https://en.wikipedia.org/wiki/Circle[circle] by an https://en.wikipedia.org/wiki/Arc_%28geometry%29[arc] that is equal in length to the https://en.wikipedia.org/wiki/Radius[radius]. It is also the unit for phase angle. For periodic phenomena, the phase angle increases by stem:[2pi " "rm(rad)] in one period. The radian was formerly an https://en.wikipedia.org/wiki/SI_supplementary_unit[SI supplementary unit], but this category was abolished in 1995.] | stem:[rm(rad) = rm(m)//rm(m)] |
| solid angle | steradian footnote:[The steradian is the coherent unit for solid angle. One steradian is the solid angle subtended at the centre of a sphere by an area of the surface that is equal to the squared radius. Like the radian, the steradian was formerly an SI supplementary unit.] | stem:[rm(sr) = rm(m)^2//rm(m)^2] |
| frequency | hertz footnote:d[The hertz shall only be used for periodic phenomena and the becquerel shall only be used for stochastic processes in activity referred to a radionuclide.] | stem:[rm(Hz) = rm(s)^(−1)] |
| force | newton | stem:[rm(N) = rm(kg)" "rm(m)" "rm(s)^(−2)] |
| pressure, stress | pascal | stem:[rm(Pa) = rm(kg)" "rm(m)^(−1) " "rm(s)^(−2)] |
| energy, work, amount of heat | joule | stem:[rm(J) = rm(kg)" "rm(m)^2 " "rm(s)^(−2)] | stem:[rm(N)" "rm(m)]
| power, radiant flux | watt | stem:[rm(W) = rm(kg)" "rm(m)^2 " "rm(s)^(−3)] | stem:[rm(J)//rm(s)]
| electric charge | coulomb | stem:[rm(C) = rm(A)" "rm(s)] |
| electric potential difference footnote:[Electric potential difference is also called "voltage" in many countries, as well as "electric tension" or simply "tension" in some countries.] | volt | stem:[rm(V) = rm(kg)" "rm(m)^2 " "rm(s)^(−3) " "rm(A)^(−1)] | stem:[rm(W)//rm(A)]
| capacitance | farad | stem:[rm(F) = rm(kg)^(−1) " "rm(m)^(−2) " "rm(s)^4 " "rm(A)^2] | stem:[rm(C)//rm(V)]
| electric resistance | ohm | stem:[Omega = rm(kg)" "rm(m)^2 " "rm(s)^(-3) " "rm(A)^(−2)] | stem:[rm(V)//rm(A)]
| electric conductance | siemens | stem:[rm(S) = rm(kg)^(−1) " "rm(m)^(−2) " "rm(s)^3 " "rm(A)^2] | stem:[rm(A)//rm(V)]
| magnetic flux | weber | stem:[rm(Wb) = rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(A)^(−1)] | stem:[rm(V)" "rm(s)]
| magnetic flux density | tesla | stem:[rm(T) = rm(kg)" "rm(s)^(−2) " "rm(A)^(−1)] | stem:[rm(Wb)//rm(m)^2]
| inductance | henry | stem:[rm(H) = rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(A)^(−2)] | stem:[rm(Wb)//rm(A)]
| Celsius temperature | degree Celsius footnote:[The degree Celsius is used to express Celsius temperatures. The numerical value of a temperature difference or temperature interval is the same when expressed in either degrees Celsius or in kelvin.] | stem:["°"rm(C) = rm(K)] |
| luminous flux | lumen | stem:[rm(lm) = rm(cd)" "rm(sr)] footnote:[In photometry the name steradian and the symbol sr are usually retained in expressions for units] | stem:[rm(cd)" "rm(sr)]
| illuminance | lux | stem:[rm(lx) = rm(cd)" "rm(sr)" "rm(m)^(−2)] | stem:[rm(lm)//rm(m)^2]
| activity referred to a radionuclide footnote:d[] footnote:[Activity referred to a radionuclide is sometimes incorrectly called radioactivity.]| becquerel | stem:[rm(Bq) = rm(s)^(−1)] |
| absorbed dose, kerma | gray | stem:[rm(Gy) = rm(m)^2 " "rm(s)^(−2)] | stem:[rm(J)//rm(kg)]
| dose equivalent | sievert footnote:[See CIPM Recommendation 2 on the use of the sievert (PV, 2002, *70*, 205).] | stem:[rm(Sv) = rm(m)^2 " "rm(s)^(−2)] | stem:[rm(J)//rm(kg)]
| catalytic activity | katal | stem:[rm(kat) = rm(mol)" "rm(s)^(−1)] |
|===

The seven base units and 22 units with special names and symbols may be used in combination to express the units of other derived quantities. Since the number of quantities is without limit, it is not possible to provide a complete list of derived quantities and derived units. <<table5>> lists some examples of derived quantities and the corresponding coherent derived units expressed in terms of base units. In addition, <<table6>> lists examples of coherent derived units whose names and symbols also include derived units. The complete set of SI units includes both the coherent set and the multiples and sub-multiples formed by using the SI prefixes.

[[table5]]
.Examples of coherent derived units in the SI expressed in terms of base units
[cols="<,<,<"]
|===
| Derived quantity | Typical symbol of quantity | Derived unit expressed in terms of base units

| area | stem:[A] | stem:[rm(m)^2]
| volume | stem:[V] | stem:[rm(m)^3]
| speed, velocity | stem:[v] | stem:[rm(m)" "rm(s)^(−1)]
| acceleration | stem:[a] | stem:[rm(m)" "rm(s)^(−2)]
| wavenumber | stem:[sigma] | stem:[rm(m)^(−1)]
| density, mass density | stem:[rho] | stem:[rm(kg)" "rm(m)^(−3)]
| surface density | stem:[rho_A] | stem:[rm(kg)" "rm(m)^(−2)]
| specific volume | stem:[v] | stem:[rm(m)^3 " "rm(kg)^(−1)]
| current density | stem:[j] | stem:[rm(A)" "rm(m)^(−2)]
| magnetic field strength | stem:[H] | stem:[rm(A)" "rm(m)^(−1)]
| amount of substance concentration | stem:[c] | stem:[rm(mol)" "rm(m)^(-3)]
| mass concentration | stem:[rho, gamma] | stem:[rm(kg)" "rm(m)^(−3)]
| luminance | stem:[L_"v"] | stem:[rm(cd)" "rm(m)^(−2)]
|===

[[table6]]
.Examples of SI coherent derived units whose names and symbols include SI coherent derived units with special names and symbols
|===
| Derived quantity | Name of coherent derived unit | Symbol | Derived unit expressedin terms of base units

| dynamic viscosity | pascal second | stem:[rm(Pa)" "rm(s)] | stem:[rm(kg)" "rm(m)^(−1) " "rm(s)^(−1)]
| moment of force | newton metre | stem:[rm(N)" "rm(m)] | stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−2)]
| surface tension | newton per metre | stem:[rm(N)" "rm(m)^(−1)] | stem:[rm(kg)" "rm(s)^(−2)]
| angular velocity, angular frequency | radian per second | stem:[rm(rad)" "rm(s)^(−1)] | stem:[rm(s)^(−1)]
| angular acceleration | radian per second squared | stem:[rm(rad)" "rm(s)^(−2)] | stem:[rm(s)^(−2)]
| heat flux density, irradiance | watt per square metre | stem:[rm(W)" "rm(m)^(−2)] | stem:[rm(kg)" "rm(s)^(−3)]
| heat capacity, entropy | joule per kelvin | stem:[rm(J)" "rm(K)^(−1)] | stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(K)^(−1)]
| specific heat capacity, specific entropy | joule per kilogram kelvin | stem:[rm(J)" "rm(K)^(−1) " "rm(kg)^(−1)] | stem:[rm(m)^2 " "rm(s)^(−2) " "rm(K)^(−1)]
| specific energy | joule per kilogram | stem:[rm(J)" "rm(kg)^(−1)] | stem:[rm(m)^2 " "rm(s)^(−2)]
| thermal conductivity | watt per metre kelvin | stem:[rm(W)" "rm(m)^(−1) " "rm(K)^(−1)] | stem:[rm(kg)" "rm(m)" "rm(s)^(−3) " "rm(K)^(−1)]
| energy density | joule per cubic metre | stem:[rm(J)" "rm(m)^(−3)] | stem:[rm(kg)" "rm(m)^(−1) " "rm(s)^(−2)]
| electric field strength | volt per metre | stem:[rm(V)" "rm(m)^(−1)] | stem:[rm(kg)" "rm(m)" "rm(s)^(−3) " "rm(A)^(−1)]
| electric charge density | coulomb per cubic metre | stem:[rm(C)" "rm(m)^(−3)] | stem:[rm(A)" "rm(s)" "rm(m)^(−3)]
| surface charge density | coulomb per square metre | stem:[rm(C)" "rm(m)^(−2)] | stem:[rm(A)" "rm(s)" "rm(m)^(−2)]
| electric flux density, electric displacement | coulomb per square metre | stem:[rm(C)" "rm(m)^(−2)] | stem:[rm(A)" "rm(s)" "rm(m)^(−2)]
| permittivity | farad per metre | stem:[rm(F)" "rm(m)^(−1)] | stem:[rm(kg)^(−1) " "rm(m)^(−3) " "rm(s)^4 " "rm(A)^2]
| permeability | henry per metre | stem:[rm(H)" "rm(m)^(−1)] | stem:[rm(kg)" "rm(m)" "rm(s)^(−2) " "rm(A)^(−2)]
| molar energy | joule per mole | stem:[rm(J)" "rm(mol)^(−1)] | stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(mol)^(−1)]
| molar entropy, molar heat capacity | joule per mole kelvin | stem:[rm(J)" "rm(K)^(−1) " "rm(mol)^(−1)] | stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−2) " "rm(mol)^(−1) " "rm(K)^(−1)]
| exposure (stem:["x"]- and stem:[gamma]-rays) | coulomb per kilogram | stem:[rm(C)" "rm(kg)^(−1)] | stem:[rm(A)" "rm(s)" "rm(kg)^(−1)]
| absorbed dose rate | gray per second | stem:[rm(Gy)" "rm(s)^(−1)] | stem:[rm(m)^2 " "rm(s)^(−3)]
| radiant intensity | watt per steradian | stem:[rm(W)" "rm(sr)^(−1)] | stem:[rm(kg)" "rm(m)^2 " "rm(s)^(−3)]
| radiance | watt per square metre steradian | stem:[rm(W)" "rm(sr)^(−1) " "rm(m)^(−2)] | stem:[rm(kg)" "rm(s)^(−3)]
| catalytic activity concentration | katal per cubic metre | stem:[rm(kat)" "rm(m)^(−3)] | stem:[rm(mol)" "rm(s)^(−1) " "rm(m)^(−3)]
|===

It is important to emphasize that each physical quantity has only one coherent SI unit, even though this unit can be expressed in different forms by using some of the special names and symbols.

The converse, however, is not true, because in general several different quantities may share the same SI unit. For example, for the quantity heat capacity as well as for the quantity entropy the SI unit is joule per kelvin. Similarly, for the base quantity electric current as well as the derived quantity magnetomotive force the SI unit is the ampere. It is therefore important not to use the unit alone to specify the quantity. This applies not only to technical texts, but also, for example, to measuring instruments (i.e. the instrument read-out needs to indicate both the unit and the quantity measured).

In practice, with certain quantities, preference is given to the use of certain special unit names to facilitate the distinction between different quantities having the same dimension. When using this freedom, one may recall the process by which this quantity is defined. For example, the quantity torque is the cross product of a position vector and a force vector. The SI unit is newton metre. Even though torque has the same dimension as energy (SI unit joule), the joule is never used for expressing torque.

NOTE: The International Electrotechnical Commission (IEC) has introduced the var (symbol: stem:[rm(var)]) as a special name for the unit of reactive power. In terms of SI coherent units, the stem:[rm(var)] is identical to the volt ampere.

The SI unit of frequency is hertz, the SI unit of angular velocity and angular frequency is radian per second, and the SI unit of activity is becquerel, implying counts per second. Although it is formally correct to write all three of these units as the reciprocal second, the use of the different names emphasizes the different nature of the quantities concerned. It is especially important to carefully distinguish frequencies from angular frequencies, because by definition their numerical values differ by a factor footnote:[see ISO 80000-3 for details] of stem:[2pi]. Ignoring this fact may cause an error of stem:[2pi]. Note that in some countries, frequency values are conventionally expressed using "cycle/s" or "cps" instead of the SI unit stem:[rm(Hz)], although "cycle" and "cps" are not units in the SI. Note also that it is common, although not recommended, to use the term frequency for quantities expressed in rad/s. Because of this, it is recommended that quantities called "frequency", "angular frequency", and "angular velocity" always be given explicit units of stem:[rm(Hz)] or stem:[rm(rad)//rm(s)] and not stem:[rm(s)^(−1)].

In the field of ionizing radiation, the SI unit becquerel rather than the reciprocal second is used. The SI units gray and sievert are used for absorbed dose and dose equivalent, respectively, rather than joule per kilogram. The special names becquerel, gray and sievert were specifically introduced because of the dangers to human health that might arise from mistakes involving the units reciprocal second and joule per kilogram, in case the latter units were incorrectly taken to identify the different quantities involved.

Special care must be taken when expressing temperatures or temperature differences, respectively. A temperature difference of stem:[1 " "rm(K)] equals that of stem:[1 " °"rm(C)], but for an absolute temperature the difference of stem:[273.15 " "rm(K)] must be taken into account. The unit degree Celsius is only coherent when expressing temperature differences.

==== Units for quantities that describe biological and physiological effects

Four of the SI units listed in <<table2>> and <<table4>> include physiological weighting factors: candela, lumen, lux and sievert.

Lumen and lux are derived from the base unit candela. Like the candela, they carry information about human vision. The candela was established as a base unit in 1954, acknowledging the importance of light in daily life. Further information on the units and conventions used for defining photochemical and photobiological quantities is in <<appendix3>>.

Ionizing radiation deposits energy in irradiated matter. The ratio of deposited energy to mass is termed absorbed dose stem:[D]. As decided by the CIPM in 2002, the quantity dose equivalent stem:[H = QD] is the product of the absorbed dose stem:[D] and a numerical quality factor stem:[Q] that takes into account the biological effectiveness of the radiation and is dependent on the energy and type of radiation.

There are units for quantities that describe biological effects and involve weighting factors, which are not SI units. Two examples are given here:

Sound causes pressure fluctuations in the air, superimposed on the normal atmospheric pressure, that are sensed by the human ear. The sensitivity of the ear depends on the frequency of the sound, but it is not a simple function of either the pressure changes or the frequency. Therefore, frequency-weighted quantities are used in acoustics to approximate the way in which sound is perceived. They are used, for example, for measurements concerning protection against hearing damage. The effect of ultrasonic acoustic waves poses similar concerns in medical diagnosis and therapy.

There is a class of units for quantifying the biological activity of certain substances used in medical diagnosis and therapy that cannot yet be defined in terms of the units of the SI. This lack of definition is because the mechanism of the specific biological effect of these substances is not yet sufficiently well understood for it to be quantifiable in terms of physico-chemical parameters. In view of their importance for human health and safety, the World Health Organization (WHO) has taken responsibility for defining WHO International Units (IU) for the biological activity of such substances.

[[si_units_gtr]]
==== SI units in the framework of the general theory of relativity

The practical realization of a unit and the process of comparison require a set of equations within a framework of a theoretical description. In some cases, these equations include relativistic effects.

For frequency standards it is possible to establish comparisons at a distance by means of electromagnetic signals. To interpret the results, the general theory of relativity is required, since it predicts, among other things, a relative frequency shift between standards of about 1 part in stem:[10^(16)] per metre of altitude difference at the surface of the earth. Effects of this magnitude must be corrected for when comparing the best frequency standards.

When practical realizations are compared locally, i.e. in a small space-time domain, effects due to the space-time curvature described by the general theory of relativity can be neglected. When realizations share the same space-time coordinates (for example the same motion and acceleration or gravitational field), relativistic effects may be neglected entirely.
