[[multiples]]
== Decimal multiples and sub-multiples of SI units
index-range:multiples_prefixes-2[(((multiples - prefixes for)))]
(((prefixes)))

Decimal multiples and submultiples ranging from stem:[10^(24)] to stem:[10^(−24)] are provided for use with the SI units. The names and symbols of these multiple and sub-multiple prefixes are presented in <<table7>>.

Prefix symbols are printed in upright typeface, as are unit symbols, regardless of the typeface used in the surrounding text and are attached to unit symbols without a space between the prefix symbol and the unit symbol. With the exception of stem:[rm(da)] (deca), stem:[rm(h)] (hecto) and stem:[rm(k)] (kilo), all multiple prefix symbols are upper-case letters and all sub-multiple prefix symbols are lowercase letters. All prefix names are printed in lowercase letters, except at the beginning of a sentence.

[NOTE]
====
The SI prefixes refer strictly to powers of 10. They should not be used to indicate powers of 2 (for example, one kilobit represents 1000 bits and not 1024 bits). The names and symbols for prefixes to be used with powers of 2 are recommended as follows:

[%unnumbered]
[cols="<,<,<"]
|===
| kibi | stem:[rm(Ki)] | stem:[2^(10)]
| mebi | stem:[rm(Mi)] | stem:[2^(20)]
| gibi | stem:[rm(Gi)] | stem:[2^(30)]
| tebi | stem:[rm(Ti)] | stem:[2^(40)]
| pebi | stem:[rm(Pi)] | stem:[2^(50)]
| exbi | stem:[rm(Ei)] | stem:[2^(60)]
| zebi | stem:[rm(Zi)] | stem:[2^(70)]
| yobi | stem:[rm(Yi)] | stem:[2^(80)]
|===
====

[[table7]]
.SI prefixes
|===
| Factor | Name | Symbol | Factor | Name | Symbol

| stem:[10^1] | deca | stem:[rm(da)] | stem:[10^(−1)] | deci | stem:[rm(d)]
| stem:[10^2] | hecto | stem:[rm(h)] | stem:[10^(−2)] | centi | stem:[rm(c)]
| stem:[10^3] | kilo | stem:[rm(k)] | stem:[10^(−3)] | milli | stem:[rm(m)]
| stem:[10^6] | mega | stem:[rm(M)] | stem:[10^(−6)] | micro | stem:[mu]
| stem:[10^9] | giga | stem:[rm(G)] | stem:[10^(−9)] | nano | stem:[rm(n)]
| stem:[10^(12)] | tera | stem:[rm(T)] | stem:[10^(−12)] | pico | stem:[rm(p)]
| stem:[10^(15)] | peta | stem:[rm(P)] | stem:[10^(−15)] | femto | stem:[rm(f)]
| stem:[10^(18)] | exa | stem:[rm(E)] | stem:[10^(−18)] | atto | stem:[rm(a)]
| stem:[10^(21)] | zetta | stem:[rm(Z)] | stem:[10^(−21)] | zepto | stem:[rm(z)]
| stem:[10^(24)] | yotta | stem:[rm(Y)] | stem:[10^(−24)] | yocto | stem:[rm(y)]
|===

The grouping formed by a prefix symbol attached to a unit symbol constitutes a new inseparable unit symbol (forming a multiple or sub-multiple of the unit concerned) that can be raised to a positive or negative power and that can be combined with other unit symbols to form compound unit symbols.

[example]
====
stem:[rm(p)rm(m)] (picometre), stem:[rm(mmol)] (millimole), stem:[rm(G) Omega] (gigaohm), stem:[rm(THz)] (terahertz)

stem:[2.3 " "rm(cm)^3 = 2.3 " "(rm(cm))^3 = 2.3 (10^(−2) " "rm(m))^3 = 2.3 xx 10^(−6) " "rm(m)^3]

stem:[1 " "rm(cm)^(−1) = 1 " "(rm(cm))^(−1) = 1 (10^(−2) " "rm(m))^(−1) = 10^2 " "rm(m)^(−1) = 100 " "rm(m)^(−1).]
====

(((pascal (Pa))))
Similarly prefix names are also inseparable from the unit names to which they are attached. Thus, for example, millimetre, micropascal and meganewton are single words.

Compound prefix symbols, i.e. prefix symbols formed by the juxtaposition of two or more prefix symbols, are not permitted. This rule also applies to two or more compound prefix names.

Prefix symbols can neither stand alone nor be attached to the number 1, the symbol for the unit one. Similarly, prefix names cannot be attached to the name of the unit one, that is, to the word "one".

(((gram)))(((mass)))(((multiples (and submultiples) of the kilogram)))
The kilogram is the only coherent SI unit, whose name and symbol, for historical reasons, include a prefix. Names and symbols for decimal multiples and sub-multiples of the unit of mass are formed by attaching prefix names and symbols to the unit name "gram" and the unit symbol "g" respectively. For example, stem:[10^(−6) " "rm(kg)] is written as milligram, stem:[rm(mg)], not as microkilogram, stem:[mu rm(kg)]. [[multiples_prefixes-2]]
