[[cgpm1re1889]]
== 1^re^ CGPM, 1889 (((kilogramme,prototype international)))(((mètre (stem:["unitsml(m)"])))) (((mètre (m),prototype international)))

[[cgpm1re1889sanction]]
=== Sanction des prototypes internationaux du mètre et du ((kilogramme)) (CR, 34-38)

____
La Conférence générale,

*considérant*

* le «{nbsp}Compte rendu du Président du Comité international{nbsp}» et le «{nbsp}Rapport du Comité
international des poids et mesures{nbsp}», d’où il résulte que, par les soins communs de la Section
française de la Commission internationale du Mètre, et du Comité international des poids et
mesures, les déterminations métrologiques fondamentales des prototypes internationaux et
nationaux du mètre et du ((kilogramme)) ont été exécutées dans toutes les conditions de garantie
et de précision que comporte l’état actuel de la science{nbsp};
* que les prototypes internationaux et nationaux du mètre et du kilogramme sont formés de
platine allié à 10 pour 100 d’iridium, à stem:[0.0001] près{nbsp};
* l’identité de ((longueur)) du Mètre et l’identité de la ((masse)) du Kilogramme internationaux avec la
longueur du Mètre et la ((masse)) du Kilogramme déposés aux Archives de France{nbsp};
* que les équations des Mètres nationaux, par rapport au Mètre international, sont renfermées
dans la limite de stem:[0.01] millimètre et que ces équations reposent sur une échelle thermométrique
à hydrogène qu’il est toujours possible de reproduire, à cause de la permanence de l’état de ce
corps, en se plaçant dans des conditions identiques{nbsp};
* que les équations des Kilogrammes nationaux, par rapport au Kilogramme international, sont
renfermées dans la limite de 1 milligramme{nbsp};
* que le Mètre(((mètre (stem:["unitsml(m)"])))) et le ((Kilogramme)) internationaux et que les Mètres et les Kilogrammes nationaux
remplissent les conditions exigées par la ((Convention du Mètre)),


*sanctionne*

. En ce qui concerne les prototypes internationaux{nbsp}:
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
désormais, à la température de la glace fondante, l’unité métrique de ((longueur)).
.. Le Prototype du ((kilogramme)) adopté par le Comité international. Ce prototype sera considéré
désormais comme unité de ((masse)).
.. L’échelle thermométrique centigrade à hydrogène par rapport à laquelle les équations des
Mètres prototypes ont été établies.

. En ce qui concerne les prototypes nationaux{nbsp}:

&#x200c;. . .
____

NOTE: La définition du mètre a
été abrogée en 1960 par la 11^e^ CGPM (<<cgpm11e1960r6r6,Résolution 6>>).
