[[cgpm3e1901]]
== 3^e^ CGPM, 1901 (((litre (L ou l))))

[[cgpm3e1901litre]]
=== Déclaration concernant la définition du litre (CR, 38-39)

____
&#x200c;. . .

*La Conférence déclare{nbsp}:*

. L’unité de volume, pour les déterminations de haute précision, est le volume occupé par la
masse de 1 ((kilogramme)) d’eau pure, à son maximum de densité et sous la pression
atmosphérique normale{nbsp}; ce volume est dénommé «&nbsp;litre&nbsp;».

. . . .
____

NOTE: Définition abrogée en 1964 par la 12^e^ CGPM (<<cgpm12e1964r6r6,Résolution 6>>).

[[cgpm3e1901mass]]
=== Déclaration relative à l’unité de masse et à la définition du poids{nbsp}; valeur conventionnelle de stem:[g_n](CR, 70) ((("accélération due à la pesanteur "(stem:[g_{"n"}])))) (((masse))) (((masse et poids)))

____
*Vu* la décision du Comité international des poids et mesures du 15 octobre 1887,
par laquelle le ((kilogramme)) a été défini comme unité de ((masse)){nbsp};

*Vu* la décision contenue dans la formule de sanction des prototypes du Système métrique,
acceptée à l’unanimité par la Conférence générale des poids et mesures dans sa réunion du 26
septembre 1889{nbsp};

*Considérant* la nécessité de faire cesser l’ambiguïté qui existe encore dans l’usage courant sur
la signification du terme poids, employé tantôt dans le sens du terme _masse_, tantôt dans le sens
du terme _effort mécanique_{nbsp};


*La Conférence déclare{nbsp}:*
(((kilogramme,prototype international)))(((masse)))

. Le ((kilogramme)) est l’unité de masse{nbsp}; il est égal à la masse du prototype international du
((kilogramme)){nbsp}; footnote:[Définition abrogée en 2018 par la CGPM à sa 26^e^ réunion (<<cgpm26th2018r1r1,Résolution 1>>).]

. Le terme poids désigne une grandeur de la même nature qu’une force{nbsp}; le poids d’un corps
est le produit de la masse de ce corps par l’accélération de la pesanteur{nbsp};
en particulier, le poids normal d’un corps est le produit de la masse de ce corps par
l’accélération normale de la pesanteur{nbsp};
(((législation sur les unités)))

. Le nombre adopté dans le Service international des Poids et Mesures pour la valeur de
l’accélération normale de la pesanteur est stem:[980.665] stem:[rm(cm)//rm(s)^2], nombre sanctionné déjà par
quelques législations. footnote:[Cette valeur de stem:[g_"n"] est la valeur conventionnelle de référence pour le calcul de l’unité kilogramme-force
maintenant abolie.]
____
