[[cgpm3e1901]]
== 3^e^ CGPM, 1901

[[cgpm3e1901litre]]
=== Déclaration concernant la définition du litre (CR, 38-39)

____
&#x200c;. . .

*La Conférence déclare:*

. L’unité de volume, pour les déterminations de haute précision, est le volume occupé par la
masse de 1 kilogramme d’eau pure, à son maximum de densité et sous la pression
atmosphérique normale; ce volume est dénommé «&nbsp;litre&nbsp;».

. . . .
____

NOTE: Définition abrogée en 1964 par la 12^e^ CGPM (<<cgpm12e1964r6r6,Résolution 6>>).

[[cgpm3e1901mass]]
=== Déclaration relative à l’unité de masse et à la définition du poids; valeur conventionnelle de stem:[g_n] (CR, 70)

____
*Vu* la décision du Comité international des poids et mesures du 15 octobre 1887,
par laquelle le kilogramme a été défini comme unité de masse;

*Vu* la décision contenue dans la formule de sanction des prototypes du Système métrique,
acceptée à l’unanimité par la Conférence générale des poids et mesures dans sa réunion du 26
septembre 1889;

*Considérant* la nécessité de faire cesser l’ambiguïté qui existe encore dans l’usage courant sur
la signification du terme poids, employé tantôt dans le sens du terme _masse_, tantôt dans le sens
du terme _effort mécanique_;


*La Conférence déclare:*

. Le kilogramme est l’unité de masse; il est égal à la masse du prototype international du
kilogramme; footnote:[Définition abrogée en 2018 par la CGPM à sa 26^e^ réunion (<<cgpm26th2018r1r1,Résolution 1>>).]

. Le terme poids désigne une grandeur de la même nature qu’une force; le poids d’un corps
est le produit de la masse de ce corps par l’accélération de la pesanteur;
en particulier, le poids normal d’un corps est le produit de la masse de ce corps par
l’accélération normale de la pesanteur;

. Le nombre adopté dans le Service international des Poids et Mesures pour la valeur de
l’accélération normale de la pesanteur est stem:[980.665] stem:[rm(cm)//rm(s)^2], nombre sanctionné déjà par
quelques législations. footnote:[Cette valeur de stem:[g_"n"] est la valeur conventionnelle de référence pour le calcul de l’unité kilogramme-force
maintenant abolie.]
____
