== CIPM, 1946

=== Définition des unités photométriques (PV, 20, 119-122)

NOTE: Les deux définitions contenues dans cette
Résolution furent ratifiées par la CGPM à sa
9^e^ réunion en 1948, qui a en outre approuvé le nom de
candela donné à la « bougie nouvelle » (CR, 54). Pour le
lumen, le qualificatif « nouveau » a été
abandonné par la suite.

[align=center]
*Résolution*

&#x200c;. . .
[start=4]
. Les unités photométriques peuvent être définies comme suit:
+
--
*Bougie nouvelle* (unité d’intensité lumineuse). -- La grandeur de la bougie nouvelle est telle
que la brillance du radiateur intégral à la température de solidification du platine soit de
60 bougies nouvelles par centimètre carré.

*Lumen nouveau* (unité de flux lumineux). -- Le lumen nouveau est le flux lumineux émis dans
l’angle solide unité (stéradian) par une source ponctuelle uniforme ayant une intensité
lumineuse de 1 bougie nouvelle.
--

. . . .


NOTE: La définition de la candela a été modifiée par la 13^e^ CGPM en 1967 (Résolution 5, _voir_ p. 59).


=== Définitions des unités électriques (PV, 20, 132-133)

[align=center]
*Résolution 2*


&#x200c;. . .

. Définitions des unités mécaniques utilisées dans les définitions des unités électriques:
+
--
*Unité de force.* -- L’unité de force [dans le système MKS (mètre, kilogramme, seconde)] est la
force qui communique à une masse de 1 kilogramme l’accélération de 1 mètre par seconde,
par seconde.

*Joule* (unité d’énergie ou de travail) -- Le joule est le travail effectué lorsque le point
d’application de 1 unité MKS de force [newton] se déplace d’une distance égale à 1 mètre
dans la direction de la force.

*Watt* (unité de puissance) -- Le watt est la puissance qui donne lieu à une production d’énergie
égale à 1 joule par seconde.
--

. Définitions des unités électriques. Le Comité [international] admet les propositions
suivantes définissant la grandeur théorique des unités électriques:
+
--
*Ampère* (unité d’intensité de courant électrique) -- L’ampère est l’intensité d’un courant
constant qui, maintenu dans deux conducteurs parallèles, rectilignes, de longueur infinie, de
section circulaire négligeable et placés à une distance de 1 mètre l’un de l’autre dans le vide,
produirait entre ces conducteurs une force égale à stem:[2 xx 10^{-7}] unité MKS de force [newton] par
mètre de longueur.

NOTE: Définition de l’ampère abrogée en 2018 par la
CGPM à sa 26^e^ réunion (Résolution 1, _voir_ p.92).

*Volt* (unité de différence de potentiel et de force électromotrice) -- Le volt est la différence de
potentiel électrique qui existe entre deux points d’un fil conducteur transportant un courant
constant de 1 ampère, lorsque la puissance dissipée entre ces points est égale à 1 watt.

*Ohm* (unité de résistance électrique) -- L’ohm est la résistance électrique qui existe entre deux
points d’un conducteur lorsqu’une différence de potentiel constante de 1 volt, appliquée
entre ces deux points, produit, dans ce conducteur, un courant de 1 ampère, ce conducteur
n’étant le siège d’aucune force électromotrice.

*Coulomb* (unité de quantité d’électricité) -- Le coulomb est la quantité d’électricité transportée
en 1 seconde par un courant de 1 ampère.

*Farad* (unité de capacité électrique) -- Le farad est la capacité d’un condensateur électrique
entre les armatures duquel apparaît une différence de potentiel électrique de 1 volt, lorsqu’il
est chargé d’une quantité d’électricité égale à 1 coulomb.

*Henry* (unité d’inductance électrique) -- Le henry est l’inductance électrique d’un circuit fermé
dans lequel une force électromotrice de 1 volt est produite lorsque le courant électrique qui
parcourt le circuit varie uniformément à raison de 1 ampère par seconde.

*Weber* (unité de flux magnétique) -- Le weber est le flux magnétique qui, traversant un circuit
d’une seule spire, y produirait une force électromotrice de 1 volt, si on l’amenait à zéro en
1 seconde par décroissance uniforme.
--