[[cgpm9e1948]]
== 9^e^ CGPM, 1948

[[cgpm9e1948r3]]
=== Point triple de l’eau; échelle thermodynamique à un seul point fixe; unité de quantité de chaleur (joule) (CR, 55 et 63)

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).

[[cgpm9e1948r3r3]]
==== Résolution 3
____

. En l’état actuel de la technique, le point triple de l’eau est susceptible de constituer un repère
thermométrique avec une précision plus élevée que le point de fusion de la glace.
+
--
En conséquence, le Comité consultatif [de thermométrie et calorimétrie] estime que le zéro
de l’échelle thermodynamique centésimale doit être défini comme étant la température
inférieure de stem:[0.0100] degré à celle du point triple de l’eau pure.
--

. Le Comité consultatif [de thermométrie et calorimétrie] admet le principe d’une échelle
thermodynamique absolue ne comportant qu’un seul point fixe fondamental, constitué
actuellement par le point triple de l’eau pure, dont la température absolue sera fixée
ultérieurement.
+
--
L’introduction de cette nouvelle échelle n’affecte en rien l’usage de l’Échelle internationale,
qui reste l’échelle pratique recommandée.
--

. L’unité de quantité de chaleur est le joule.

NOTE: Il est demandé que les résultats d’expériences calorimétriques soient autant que possible
exprimés en joules. Si les expériences ont été faites par comparaison avec un échauffement
d’eau (et que, pour une raison quelconque, on ne puisse éviter l’usage de la calorie), tous les
renseignements nécessaires pour la conversion en joules doivent être fournis. Il est laissé aux
soins du Comité international, après avis du Comité consultatif de thermométrie et calorimétrie,
d’établir une table qui présentera les valeurs les plus précises que l’on peut tirer des
expériences faites sur la chaleur spécifique de l’eau, en joules par degré.
____

Une table, établie conformément à cette demande, a été approuvée et publiée par le Comité
international en 1950 (PV, *22*, 92).


[[cipm1948]]
=== Adoption de « degré Celsius » [CIPM, 1948 (PV, 21, 88) et 9^e^ CGPM, 1948 (CR, 64)]

Entre les trois termes (« degré centigrade », « degré centésimal », « degré Celsius ») proposés
pour désigner le degré de température, le Comité international a choisi « degré Celsius » (PV,
*21*, 88).

Ce terme est également adopté par la 9^e^ Conférence générale (CR, 64).


[[cgpm9e1948r6]]
=== Proposition d’établissement d’un système pratique d’unités de mesure (CR, 64)

[[cgpm9e1948r6r6]]
==== Résolution 6
____

La Conférence générale,

*considérant*

* que le Comité international des poids et mesures a été saisi d’une demande de l’Union
internationale de physique le sollicitant d’adopter pour les relations internationales un système
pratique international d’unités, recommandant le système MKS et une unité électrique du
système pratique absolu, tout en ne recommandant pas que le système CGS soit abandonné
par les physiciens;

* qu’elle-même a reçu du Gouvernement français une demande analogue, accompagnée d’un
projet destiné à servir de base de discussion pour l’établissement d’une réglementation
complète des unités de mesure;

*charge* le Comité international:

* d’ouvrir à cet effet une enquête officielle sur l’opinion des milieux scientifiques, techniques et
pédagogiques de tous les pays (en offrant effectivement comme base le document français)
et de la pousser activement;

* de centraliser les réponses;

* et d’émettre des recommandations concernant l’établissement d’un même système pratique
d’unités de mesure, susceptible d’être adopté dans tous les pays signataires de la Convention
du Mètre.
____


[[cgpm9e1948r7]]
=== Écriture des symboles d’unités et des nombres (CR, 70)

NOTE: La Conférence générale a abrogé un certain nombre
de décisions concernant les unités et la terminologie,
en particulier celles relatives au micron, au
degré absolu et aux noms « degré » et « deg »,
13^e^ CGPM, 1967/68 (<<cgpm13e1968r7r7,Résolutions 7>>) et (<<cgpm13e1968r3r3,Résolutions 3>>), ainsi
qu’au litre, 16^e^ CGPM, 1979 (<<cgpm16e1979r6r6,Résolution 6>>).

[[cgpm9e1948r7r7]]
==== Résolution 7
____

*Principes*

Les symboles des unités sont exprimés en caractères romains, en général minuscules;
toutefois, si les symboles sont dérivés de noms propres, les caractères romains majuscules sont
utilisés. Ces symboles ne sont pas suivis d’un point.

Dans les nombres, la virgule (usage français) ou le point (usage britannique) sont utilisés
seulement pour séparer la partie entière des nombres de leur partie décimale.
Pour faciliter la lecture, les nombres peuvent être partagés en tranches de trois chiffres:
ces tranches ne sont jamais séparées par des points, ni par des virgules.


[cols="1,^,1,^",options="unnumbered"]
|===
| Unités | Symboles | Unités | Symboles

a| ·mètre | stem:["m"] | ampère | stem:["A"]
a| ·mètre carré | stem:["m"^2] | volt | stem:["V"]
a| ·mètre cube | stem:["m"^3] | watt | stem:["W"]
a| ·micron | stem:[mu] | ohm | stem:[Omega]
a| ·litre | stem:["l"] | coulomb | stem:["C"]
a| ·gramme | stem:["g"] | farad | stem:["F"]
a| ·tonne | stem:["t"] | henry | stem:["H"]
| seconde | stem:["s"] | hertz | stem:["Hz"]
| erg | stem:["erg"] | poise | stem:["P"]
| dyne | stem:["dyn"] | newton | stem:["N"]
| degré Celsius | stem:["°C"] a| ·candela (bougie nouvelle) | stem:["cd"]
a| ·degré absolu | stem:["°K"] | lux | stem:["lx"]
| calorie | stem:["cal"] | lumen | stem:["lm"]
| bar | stem:["bar"] | stilb | stem:["sb"]
| heure | stem:["h"] | |
|===


NOTE: Les symboles dont les unités sont précédées d’un point sont ceux qui avaient déjà été
antérieurement adoptés par une décision du Comité international.

NOTE: L’unité de volume stère, employée dans le mesurage des bois, aura pour symbole « st » et
non plus « s », qui lui avait été précédemment affecté par le Comité international.

NOTE: S’il s’agit, non d’une température, mais d’un intervalle ou d’une différence de température,
le mot « degré » doit être écrit en toutes lettres ou par l’abréviation « deg ».
____
