[[cgpm10e1954]]
== 10^e^ CGPM, 1954

[[cgpm10e1954r3]]
=== Définition de l’échelle thermodynamique de température (CR, 79)

NOTE: La 13^e^ CGPM en 1967/68 <<cgpm13e1698r4r4,Résolution 4>> a explicitement défini le kelvin(((kelvin (K)))).

NOTE: Le kelvin(((kelvin (K)))) a été redéfini par
la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).

[[cgpm10e1954r3r3]]
==== Résolution 3
____

La Dixième Conférence générale des poids et mesures décide de définir l’échelle
thermodynamique de température au moyen du ((point triple de l’eau)) comme point fixe
fondamental, en lui attribuant la température stem:[273.16] degrés Kelvin(((kelvin (K)))), exactement.
____


=== Définition de l’atmosphère normale (CR, 79)

==== Résolution 4
____

La Dixième Conférence générale des poids et mesures, ayant constaté que la définition de
l’atmosphère normale donnée par la Neuvième Conférence générale des poids et mesures dans
la définition de l’Échelle internationale de température a laissé penser à quelques physiciens
que la validité de cette définition de l’atmosphère normale était limitée aux besoins de la
thermométrie de précision,

*déclare* qu’elle adopte, pour tous les usages, la définition{nbsp}:
(((mètre (m))))

[align=left]
1 atmosphère normale stem:[= 1013250] dynes(((dyne (dyn)))) par centimètre carré, +
c’est-à-dire{nbsp}: stem:[101325] newtons par mètre carré.
____

[[cgpm10e1954r6]]
=== Système pratique d’unités de mesure (CR, 80)

NOTE: Le nom de l’unité de température thermodynamique
a été changé en «&nbsp;kelvin&nbsp;»(((kelvin (K)))) en 1967
par la 13^e^ CGPM (<<cgpm13e1968r3r3,Résolution 3>>).

[[cgpm10e1954r6r6]]
==== Résolution 6 (((unité(s),de base)))
____

La Dixième Conférence générale des poids et mesures, en exécution du voeu exprimé dans sa
Résolution 6 par la Neuvième Conférence générale concernant l’établissement d’un système
pratique d’unités de mesure pour les relations internationales,

*décide* d’adopter comme unités de base de ce système à établir, les unités suivantes{nbsp}:

[cols="2",options="unnumbered"]
|===
| ((longueur)) | mètre(((mètre (m))))
| ((masse)) | ((kilogramme))
| temps | ((seconde))
| intensité de ((courant électrique)) | ampère(((ampère (A))))
| température thermodynamique | degré Kelvin(((kelvin (K))))(((degré kelvin)))
| intensité lumineuse(((intensité lumineuse))) | candela(((candela (cd))))
|===
____
