== 10^e^ CGPM, 1954

=== Définition de l’échelle thermodynamique de température (CR, 79)

____
[align=center]
*Résolution 3*

La Dixième Conférence générale des poids et mesures décide de définir l’échelle
thermodynamique de température au moyen du point triple de l’eau comme point fixe
fondamental, en lui attribuant la température 273,16 degrés Kelvin, exactement.
____

NOTE: La <<cgpm13e1698r4,13^e^ CGPM en 1967/68 (Résolution 4)>> a explicitement défini le kelvin.

NOTE: Le kelvin a été redéfini par
la <<cgpm26th2018r1,CGPM à sa 26^e^ réunion en 2018 (Résolution 1)>>.

=== Définition de l’atmosphère normale (CR, 79)

____
[align=center]
*Résolution 4*

La Dixième Conférence générale des poids et mesures, ayant constaté que la définition de
l’atmosphère normale donnée par la Neuvième Conférence générale des poids et mesures dans
la définition de l’Échelle internationale de température a laissé penser à quelques physiciens
que la validité de cette définition de l’atmosphère normale était limitée aux besoins de la
thermométrie de précision,

*déclare* qu’elle adopte, pour tous les usages, la définition:

[align=left]
1 atmosphère normale = 1 013 250 dynes par centimètre carré, +
c’est-à-dire: 101 325 newtons par mètre carré.
____

[[cgpm10e1954r6]]
=== Système pratique d’unités de mesure (CR, 80)

____
[align=center]
*Résolution 6*

La Dixième Conférence générale des poids et mesures, en exécution du voeu exprimé dans sa
Résolution 6 par la Neuvième Conférence générale concernant l’établissement d’un système
pratique d’unités de mesure pour les relations internationales,

*décide* d’adopter comme unités de base de ce système à établir, les unités suivantes:

[cols="2",options="unnumbered"]
|===
| longueur | mètre
| masse | kilogramme
| temps | seconde
| intensité de courant électrique | ampère
| température thermodynamique | degré Kelvin
| intensité lumineuse | candela
|===
____

NOTE: Le nom de l’unité de température thermodynamique
a été changé en « kelvin » en 1967
par la <<cgpm13e1968r1,13^e^ CGPM (Résolution 3)>>.