== CIPM, 1956

=== Définition de l’unité de temps (seconde) (PV, 25, 77)

____
[align=center]
*Résolution 1*

En vertu des pouvoirs que lui a conférés la Dixième Conférence générale des poids et mesures
par sa Résolution 5, le Comité international des poids et mesures,

*considérant*

1. que la Neuvième Assemblée générale de l’Union astronomique internationale (Dublin, 1955)
a émis un avis favorable au rattachement de la seconde à l’année tropique,

2. que, selon les décisions de la Huitième Assemblée générale de l’Union astronomique
internationale (Rome, 1952), la seconde de temps des éphémérides (T.E.) est la fraction
+
--
stem:[(12 " "960 " "276 " "813)/(408 " "986 " "496) xx 10^{-9}] de l’année tropique pour 1900 janvier 0 à 12 h T.E.,
--

*décide*

« La seconde est la fraction 1/31 556 925,9747 de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides. »
____

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM
(Résolution 1, _voir_ p. 58).

=== Système international d’unités (PV, 25, 83)

____
[align=center]
*Résolution 3*

Le Comité international des poids et mesures,

*considérant*

* la mission dont l’a chargé la Neuvième Conférence générale des poids et mesures par sa
Résolution 6 concernant l’établissement d’un système pratique d’unités de mesure susceptible
d’être adopté par tous les pays signataires de la Convention du Mètre,
* l’ensemble des documents envoyés par les vingt et un pays qui ont répondu à l’enquête
prescrite par la Neuvième Conférence générale des poids et mesures,
* la Résolution 6 de la Dixième Conférence générale des poids et mesures fixant le choix des
unités de base du système à établir,
____

____
*recommande*

1. que soit désigné comme « Système international d’unités » le système fondé sur les unités
de base adoptées par la Dixième Conférence générale, qui sont:
____

[Suit la liste des six unités de base avec leur symbole, reproduite dans la Résolution 12
de la 11^e^ CGPM (1960)].

____
2. que soient employées les unités de ce système énumérées au tableau suivant, sans
préjudice d’autres unités qu’on pourrait ajouter à l’avenir:
____

[Suit le tableau des unités reproduit dans le paragraphe 4 de la Résolution 12 de la
11^e^ CGPM (1960)].