[[cipm1956]]
[%unnumbered]
== CIPM, 1956 index-range:seconde-2[(((seconde)))]

[[cipm1956r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Définition de l’unité de temps* (seconde) (<<PV25>>)

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM (<<cgpm13e1968r1r1,Résolution 1>>).

[[cipm1956r1r1]]
==== Résolution 1
____

En vertu des pouvoirs que lui a conférés la Dixième Conférence générale des poids et mesures
par sa Résolution 5, le Comité international des poids et mesures,

*considérant*

1. que la Neuvième Assemblée générale de l’Union astronomique internationale (Dublin, 1955)
a émis un avis favorable au rattachement de la seconde à l’année tropique,

2. que, selon les décisions de la Huitième Assemblée générale de l’Union astronomique
internationale (Rome, 1952), la seconde de temps des éphémérides (T.E.) est la fraction
+
--
stem:[(12960276813)/(408986496) xx 10^(-9)] de l’année tropique pour 1900 janvier 0 à 12 h T.E.,
--

*décide*

«{nbsp}La seconde est la fraction stem:[1//31556925.9747] de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides.{nbsp}» [[seconde-2]]
____



[[cipm1956r3]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Système international d’unités* (<<PV25>>) (((unité(s),de base)))

[[cipm1956r3r3]]
==== Résolution 3
____

Le Comité international des poids et mesures,

*considérant*

* la mission dont l’a chargé la Neuvième Conférence générale des poids et mesures par sa
Résolution 6 concernant l’établissement d’un système pratique d’unités de mesure susceptible
d’être adopté par tous les pays signataires de la ((Convention du Mètre)),
* l’ensemble des documents envoyés par les vingt et un pays qui ont répondu à l’enquête
prescrite par la Neuvième Conférence générale des poids et mesures,
* la Résolution 6 de la Dixième Conférence générale des poids et mesures fixant le choix des
unités de base du système à établir,

*recommande*

[align=left]
. que soit désigné comme «{nbsp}Système international d’unités{nbsp}» le système fondé sur les unités
de base adoptées par la Dixième Conférence générale, qui sont{nbsp}: +
[Suit la liste des six unités de base avec leur symbole, reproduite dans la Résolution 12
de la 11^e^ CGPM (1960)].

. que soient employées les unités de ce système énumérées au tableau suivant, sans
préjudice d’autres unités qu’on pourrait ajouter à l’avenir{nbsp}: +
[Suit le tableau des unités reproduit dans le paragraphe 4 de la Résolution 12 de la
11^e^ CGPM (1960)].
____
