== 11^e^ CGPM, 1960

=== Définition du mètre (CR, 85)

[align=center]
*Résolution 6*

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le Prototype international ne définit pas le mètre avec une précision suffisante pour les
besoins actuels de la métrologie,
* qu’il est d’autre part désirable d’adopter un étalon naturel et indestructible,

*décide*

. Le mètre est la longueur égale à 1 650 763,73 longueurs d’onde dans le vide de la radiation
correspondant à la transition entre les niveaux 2p~10~ et 5d~5~ de l’atome de krypton 86.

. La définition du mètre en vigueur depuis 1889, fondée sur le Prototype international en
platine iridié, est abrogée.

. Le Prototype international du mètre sanctionné par la Première Conférence générale des
poids et mesures en 1889 sera conservé au Bureau international des poids et mesures dans
les mêmes conditions que celles qui ont été fixées en 1889.

NOTE: Définition abrogée en 1983 par la 17^e^ CGPM
(Résolution 1, _voir_ p. 66).

=== Définition de l’unité de temps (seconde) (CR, 86)

[align=center]
*Résolution 9*

La Onzième Conférence générale des poids et mesures,

*considérant*

* le pouvoir donné par la Dixième Conférence générale des poids et mesures au Comité
international des poids et mesures de prendre une décision au sujet de la définition de l’unité
fondamentale de temps,
* la décision prise par le Comité international des poids et mesures dans sa session de 1956,

*ratifie* la définition suivante:

« La seconde est la fraction 1/31 556 925,9747 de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides. »

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM
(Résolution 1, _voir_ p. 58).

=== Système international d’unités (CR, 87)

[align=center]
*Résolution 12*

*considérant*

* la Résolution 6 de la Dixième Conférence générale des poids et mesures par laquelle elle a
adopté les six unités devant servir de base à l’établissement d’un système pratique de mesure
pour les relations internationales:
+
--
[cols="3",options="unnumbered"]
|===
| longueur | mètre | m
| masse | kilogramme | kg
| temps | seconde | s
| intensité de courant électrique | ampère | A
| température thermodynamique | degré Kelvin | °K
| intensité lumineuse | candela | cd
|===

NOTE: La CGPM a ultérieurement abrogé
certaines de ces décisions et complété la liste des
préfixes SI: _voir_ notes ci-dessous.

NOTE: Le nom et symbole de l’unité de température
thermodynamique ont été modifiés par la 13^e^ CGPM
en 1967 (Résolution 3, _voir_ p. 58).
--

* la Résolution 3 adoptée par le Comité international des poids et mesures en 1956,
* les recommandations adoptées par le Comité international des poids et mesures en 1958
concernant l’abréviation du nom de ce système et les préfixes pour la formation des multiples et
sous-multiples des unités,

*décide*

. le système fondé sur les six unités de base ci-dessus est désigné sous le nom de « Système
international d’unités »;
+
--
NOTE: Une septième unité de base, la mole, fut adoptée
par la 14^e^ CGPM en 1971 (Résolution 3, _voir_ p. 62).
--
. l’abréviation internationale du nom de ce Système est: SI;

. les noms des multiples et sous-multiples des unités sont formés au moyen des préfixes
suivants:
+
--
[cols=">,<,^,>,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole | Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[1 " "000 " "000 " "000 " "000 = 10^(12)] | téra | stem:["T"] | stem:[0,1 = 10^{-1}] | déci | stem:["d"]
| stem:[1 " "000 " " 000 " "000 = 10^9] | giga | stem:["G"] | stem:[0,01 = 10^{-2}] | centi | stem:["c"]
| stem:[1 " "000 " "000 = 10^6] | méga | stem:["M"] | stem:[0,001 = 10^{-3}] | milli | stem:["m"]
| stem:[1 " "000 = 10^3] | kilo | stem:["k"] | stem:[0,000 " "001 = 10^{-6}] | micro | stem:[mu]
| stem:[100 = 10^2] | hecto | stem:["h"] | stem:[0,000 " "000 " "001 = 10^{-9}] | nano | stem:["n"]
| stem:[10 = 10^1] | déca | stem:["da"] | stem:[0,000 " "000 " "000" "001 = 10^{-12}] | pico | stem:["p"]
|===

NOTE: D’autres préfixes furent
adoptés par la 12^e^ CGPM en 1964 (Résolution 8,
_voir_ p. 57), par la 15^e^ CGPM en 1975
(Résolution 10, _voir_ p. 63)
et par la 19^e^ CGPM en 1991 (Résolution 4,
_voir_ p. 70). 
--

. sont employées dans ce Système les unités ci-dessous, sans préjudice d’autres unités qu’on
pourrait ajouter à l’avenir

[cols="3",options="unnumbered"]
|===
3+h| _Unités supplémentaires_

| angle | radian | stem:["rad"]
| angle solide | stéradian | stem:["sr"]
|===

NOTE: La 20^e^ CGPM a abrogé en
1995 la classe des unités
supplémentaires dans le SI
(Résolution 8, _voir_ p. 70).
Ces unités sont maintenant
considérées comme des
unités dérivées.

[cols="4",options="unnumbered"]
|===
4+h| _Unités dérivées_

| superficie | mètre carré | stem:["m"^2] |
| volume mètre | cube | stem:["m"^3] |
| fréquence | hertz | stem:["Hz"] | stem:[1//"s"]
| masse volumique (densité) | kilogramme par mètre cube | stem:["kg/m"^3] |
| vitesse | mètre par seconde | stem:["m/s"] |
| vitesse angulaire | radian par seconde | stem:["rad/s"] |
| accélération | mètre par seconde carrée | stem:["m/s"^2] |
| accélération angulaire | radian par seconde carrée | stem:["rad/s"^2] |
| force | newton | stem:["N"] | stem:["kg" * "m/s"^2]
| pression (tension mécanique) | newton par mètre carré | stem:["N/m"^2] |
| viscosité cinématique | mètre carré par seconde | stem:["m"^2//"s"] |
| viscosité dynamique | newton-seconde par mètre carré | stem:["N" * "s/m"^2] |
| travail, énergie, quantité de chaleur | joule | stem:["J"] | stem:["N" * "m"]
| puissance | watt | stem:["W"] | stem:["J/s"]
| quantité d’électricité | coulomb | stem:["C"] | stem:["A" * "s"]
| tension électrique, différence de potentiel, force électromotrice | volt | stem:["V"] | stem:["W/A"]
| intensité de champ électrique | volt par mètre | stem:["V/m"] |
| résistance électrique | ohm | stem:[Omega] | stem:["V/A"]
| capacité électrique | farad | stem:["F"] | stem:["A" * "s/V"]
| flux d’induction magnétique | weber | stem:["Wb"] | stem:["V" * "s"]
| inductance | henry | stem:["H"] | stem:["V" * "s/A"]
| induction magnétique | tesla | stem:["T"] | stem:["Wb/m"^2]
| intensité de champ magnétique | ampère par mètre | stem:["A/m"] |
| force magnétomotrice | ampère | stem:["A"] |
| flux lumineux | lumen | stem:["lm"] | stem:["cd" * "sr"]
| luminance | candela par mètre carré | stem:["cd/m"^2] |
| éclairement | lux | stem:["lx"] | stem:["lm/m"^2]
|===

NOTE: La 13^e^ CGPM en 1967 (Résolution 6, _voir_ p. 59)
a ajouté d’autres unités à cette liste d’unités
dérivées, qui, en principe, n’est pas limitative.

=== Décimètre cube et litre (CR, 88)

[align=center]
*Résolution 13*

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le décimètre cube et le litre sont inégaux et diffèrent d’environ 28 millionièmes,
* que les déterminations de grandeurs physiques impliquant des mesures de volume ont une
précision de plus en plus élevée, aggravant par là les conséquences d’une confusion possible
entre le décimètre cube et le litre,

*invite* le Comité international des poids et mesures à mettre ce problème à l’étude et à
présenter ses conclusions à la Douzième Conférence générale.