[[cgpm11e1960]]
[%unnumbered]
== 11^e^ CGPM, 1960

[[cgpm11e1960r6]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Définition du mètre* (<<CR1960-6,page=85>>)

NOTE: Définition abrogée en 1983 par la 17^e^ CGPM (<<cgpm17e1983r1r1,Résolution 1>>).

[[cgpm11e1960r6r6]]
==== Résolution 6
____

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le Prototype international ne définit pas le mètre avec une précision suffisante pour les
besoins actuels de la métrologie,
* qu’il est d’autre part désirable d’adopter un étalon naturel et indestructible,

*décide*
(((mètre (stem:["unitsml(m)"]),prototype international)))

. Le mètre est la ((longueur)) égale à stem:[1650763.73] longueurs d’onde dans le vide de la radiation
correspondant à la transition entre les niveaux 2p~10~ et 5d~5~ de l’atome de krypton 86.

. La définition du mètre en vigueur depuis 1889, fondée sur le Prototype international en
platine iridié, est abrogée.

. Le Prototype international du mètre sanctionné par la Première Conférence générale des
poids et mesures en 1889 sera conservé au Bureau international des poids et mesures dans
les mêmes conditions que celles qui ont été fixées en 1889.
____


[[cgpm11e1960r9]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Définition de l’unité de temps (seconde)* (<<CR1960-9,page=86>>)(((seconde)))

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM (<<cgpm13e1968r1r1,Résolution 1>>).

[[cgpm11e1960r9r9]]
==== Résolution 9
____

La Onzième Conférence générale des poids et mesures,

*considérant*

* le pouvoir donné par la Dixième Conférence générale des poids et mesures au Comité
international des poids et mesures de prendre une décision au sujet de la définition de l’unité
fondamentale de temps,
* la décision prise par le Comité international des poids et mesures dans sa session de 1956,

*ratifie* la définition suivante{nbsp}:

«{nbsp}La seconde est la fraction stem:[1//31556925.9747] de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides.{nbsp}»
____



[[cgpm11e1960r12]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Système international d’unités* (<<CR1960-12,page=87>>)(((préfixes SI)))

NOTE: La CGPM a ultérieurement abrogé
certaines de ces décisions et complété la liste des
préfixes SI{nbsp}: _voir_ notes
ci-dessous.

[[cgpm11e1960r12r12]]
==== Résolution 12
____

La Onzième Conférence générale des poids et mesures,
(((unité(s),de base)))(((unité(s),multiples et sous-multiples des)))

*considérant*

* la Résolution 6 de la Dixième Conférence générale des poids et mesures par laquelle elle a
adopté les six unités devant servir de base à l’établissement d’un système pratique de mesure
pour les relations internationales{nbsp}:
+
--
[cols="3",options="unnumbered"]
|===
| longueur | mètre | stem:["unitsml(m)"]
| ((masse)) | ((kilogramme)) | stem:["unitsml(kg)"]
| temps | ((seconde)) | stem:["unitsml(s)"]
| intensité de ((courant électrique)) | ampère(((ampère (stem:["unitsml(A)"])))) | stem:["unitsml(A)"]
| température thermodynamique footnote:[Le nom et symbole de l’unité de température thermodynamique ont été modifiés par la 13^e^ CGPM en 1967 (<<cgpm13e1968r3r3,Résolution 3>>).] | degré Kelvin(((kelvin (stem:["unitsml(K)"]))))(((degré kelvin))) | stem:["unitsml(degK)"]
| ((intensité lumineuse)) | candela(((candela (stem:["unitsml(cd)"])))) | stem:["unitsml(cd)"]
|===
--

* la Résolution 3 adoptée par le Comité international des poids et mesures en 1956,
((("multiples et sous-multiples, préfixes")))

* les recommandations adoptées par le Comité international des poids et mesures en 1958
concernant l’abréviation du nom de ce système et les préfixes pour la formation des multiples et
sous-multiples des unités,

*décide*

. le système fondé sur les six unités de base ci-dessus est désigné sous le nom de «{nbsp}Système international d’unités{nbsp}»{nbsp}; footnote:[Une septième unité de base, la mole, fut adoptée par la 14^e^ CGPM en 1971 (<<cgpm14e1971r3r3,Résolution 3>>).]

. l’abréviation internationale du nom de ce Système est{nbsp}: SI{nbsp};

. les noms des multiples et sous-multiples des unités sont formés au moyen des préfixes
suivants{nbsp}:
+
--
[cols=">,^,^,>,^,^",options="header,unnumbered"]
|===
^| Facteur par lequel l’unité est multipliée | Préfixe footnote:[D’autres préfixes furent adoptés par la 12^e^ CGPM en 1964 (<<cgpm12e1964r8r8,Résolution 8>>), par la 15^e^ CGPM en 1975 (<<cgpm15e1975r10r10,Résolution 10>>) et par la 19^e^ CGPM en 1991 (<<cgpm19e1991r4r4,Résolution 4>>). ] | Symbole ^| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[1000000000000 = 10^(12)] | téra | stem:["unitsml(T-)"] | stem:[0.1 = 10^(-1)] | déci | stem:["unitsml(d-)"]
| stem:[1000000000 = 10^9] | giga | stem:["unitsml(G-)"] | stem:[0.01 = 10^(-2)] | centi | stem:["unitsml(c-)"]
| stem:[1000000 = 10^6] | méga | stem:["unitsml(M-)"] | stem:[0.001 = 10^(-3)] | milli | stem:["unitsml(m-)"]
| stem:[1000 = 10^3] | kilo | stem:["unitsml(k-)"] | stem:[0.000001 = 10^(-6)] | micro | stem:["unitsml(u-)"]
| stem:[100 = 10^2] | hecto | stem:["unitsml(h-)"] | stem:[0.000000001 = 10^(-9)] | nano | stem:["unitsml(n-)"]
| stem:[10 = 10^1] | déca | stem:["unitsml(da-)"] | stem:[0.000000000001 = 10^(-12)] | pico | stem:["unitsml(p-)"]
|===

--

. sont employées dans ce Système les unités ci-dessous, sans préjudice d’autres unités qu’on
pourrait ajouter à l’avenir

[cols="3",options="unnumbered"]
|===
3+h| _Unités supplémentaires_ (((unité(s),supplémentaires))) footnote:[La 20^e^ CGPM a abrogé en 1995 la classe des unités supplémentaires dans le SI (<<cgpm20e1995r8r8,Résolution 8>>). Ces unités sont maintenant considérées comme des unités dérivées.]

| angle(((angle))) | radian(((radian (stem:["unitsml(rad)"])))) | stem:["unitsml(rad)"]
| angle solide | stéradian(((stéradian (sr)))) | stem:["unitsml(sr)"]
|===

[cols="4",options="unnumbered"]
|===
4+h| _Unités dérivées_ footnote:[La 13^e^ CGPM en 1967 (<<cgpm13e1967r6r6,Résolution 6>>) a ajouté d’autres unités à cette liste d’unités
dérivées, qui, en principe, n’est pas limitative.]

| superficie | mètre carré | stem:["unitsml(m^2)"] |
| volume | mètre cube | stem:["unitsml(m^3)"] |
| fréquence | hertz(((hertz (stem:["unitsml(Hz)"])))) | stem:["unitsml(Hz)"] | stem:[1//"unitsml(s)"]
| ((masse)) volumique (densité) | ((kilogramme)) par mètre cube | stem:["unitsml(kg/m^3)"] |
| vitesse | mètre par ((seconde)) | stem:["unitsml(m/s)"] |
| vitesse angulaire | radian(((radian (stem:["unitsml(rad)"])))) par seconde | stem:["unitsml(rad//s)"] |
| accélération | mètre par seconde carrée | stem:["unitsml(m/s^2)"] |
| accélération angulaire | radian(((radian (stem:["unitsml(rad)"])))) par seconde carrée | stem:["unitsml(rad/s^2)"] |
| force | newton(((newton (stem:["unitsml(N)"])))) | stem:["unitsml(N)"] | stem:["unitsml(kg)" * "unitsml(m/s^2)"]
| pression (tension mécanique) | newton par mètre carré | stem:["unitsml(N/m^2)"] |
| viscosité cinématique (((viscosité,cinématique (stokes)))) | mètre carré par seconde | stem:["unitsml(m^2/s)"] |
| viscosité dynamique (((viscosité,dynamique (poise)))) | newton-seconde par mètre carré | stem:["unitsml(N)" * "unitsml(s//m^2)"] |
| travail, énergie, quantité de chaleur | joule(((joule (stem:["unitsml(J)"])))) | stem:["unitsml(J)"] | stem:["unitsml(N*m,symbol:N cdot m)"]
| puissance | watt (((watt (stem:["unitsml(W)"])))) | stem:["unitsml(W)"] | stem:["unitsml(J/s)"]
| quantité d’électricité | coulomb(((coulomb (stem:["unitsml(C)"])))) | stem:["unitsml(C)"] | stem:["unitsml(A*s,symbol:A cdot s)"]
| tension électrique, différence de potentiel, force électromotrice | volt(((volt (stem:["unitsml(V)"])))) | stem:["unitsml(V)"] | stem:["unitsml(W/A)"]
| intensité de champ électrique | volt par mètre | stem:["unitsml(V/m)"] |
| résistance électrique | ohm(((ohm (stem:["unitsml(Ohm)"])))) | stem:["unitsml(Ohm)"] | stem:["unitsml(V/A)"]
| capacité électrique | farad(((farad (stem:["unitsml(F)"])))) | stem:["unitsml(F)"] | stem:["unitsml(A)" * "unitsml(s//V)"]
| flux d’induction magnétique | weber(((weber (stem:["unitsml(Wb)"])))) | stem:["unitsml(Wb)"] | stem:["unitsml(V*s,symbol:V cdot s)"]
| inductance | henry(((henry (stem:["unitsml(H)"])))) | stem:["unitsml(H)"] | stem:["unitsml(V)" * "unitsml(s/A)"]
| induction magnétique | tesla(((tesla (stem:["unitsml(T)"])))) | stem:["unitsml(T)"] | stem:["unitsml(Wb/m^2)"]
| intensité de champ magnétique | ampère par mètre | stem:["unitsml(A/m)"] |
| force magnétomotrice | ampère(((ampère (stem:["unitsml(A)"])))) | stem:["unitsml(A)"] |
| flux lumineux | lumen(((lumen (stem:["unitsml(lm)"])))) | stem:["unitsml(lm)"] | stem:["unitsml(cd*sr,symbol:cd cdot sr)"]
| luminance | candela par mètre carré | stem:["unitsml(cd//m^2)"] |
| éclairement | lux(((lux (stem:["unitsml(lx)"])))) | stem:["unitsml(lx)"] | stem:["unitsml(lm//m^2)"]
|===
____



[[cgpm11e1960r13]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Décimètre cube et litre* (<<CR1960-13,page=88>>)

[[cgpm11e1960r13r13]]
==== Résolution 13 (((litre (stem:["unitsml(L)"] ou stem:["unitsml(l)"]))))
____

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le décimètre cube et le litre sont inégaux et diffèrent d’environ 28 millionièmes,
* que les déterminations de grandeurs physiques impliquant des mesures de volume ont une
précision de plus en plus élevée, aggravant par là les conséquences d’une confusion possible
entre le décimètre cube et le litre,

*invite* le Comité international des poids et mesures à mettre ce problème à l’étude et à
présenter ses conclusions à la Douzième Conférence générale.
____
