== 12^e^ CGPM, 1964

=== Étalon atomique de fréquence (CR, 93)

[align=center]
*Résolution 5*

La Douzième Conférence générale des poids et mesures,

*considérant*

* que la Onzième Conférence générale des poids et mesures a constaté dans sa Résolution 10
l’urgence pour les buts de la haute métrologie d’arriver à un étalon atomique ou moléculaire
d’intervalle de temps,
* que, malgré les résultats acquis dans l’utilisation des étalons atomiques de fréquence à césium,
le moment n’est pas encore venu pour la Conférence générale d’adopter une nouvelle définition
de la seconde, unité de base du Système international d’unités, en raison des progrès
nouveaux et importants qui peuvent être obtenus à la suite des études en cours,

*considérant aussi* qu’on ne peut pas attendre davantage pour fonder les mesures physiques
de temps sur des étalons atomiques ou moléculaires de fréquence,

*habilite* le Comité international des poids et mesures à désigner les étalons atomiques ou
moléculaires de fréquence à employer temporairement,

*invite* les Organisations et les Laboratoires experts dans ce domaine à poursuivre les études
utiles à une nouvelle définition de la seconde.


=== Litre (CR, 93)

[align=center]
*Résolution 6*

La Douzième Conférence générale des poids et mesures,

*considérant* la Résolution 13 adoptée par la Onzième Conférence générale en 1960 et la
Recommandation adoptée par le Comité international des poids et mesures à sa session de
1961,

. *abroge* la définition du litre donnée en 1901 par la Troisième Conférence générale des poids
et mesures,
. *déclare* que le mot « litre » peut être utilisé comme un nom spécial donné au décimètre
cube,
. *recommande* que le nom de litre ne soit pas utilisé pour exprimer les résultats des mesures
de volume de haute précision.


=== Curie (CR, 94)

[align=center]
*Résolution 7*

La Douzième Conférence générale des poids et mesures,

*considérant* que depuis longtemps le curie est utilisé dans beaucoup de pays comme unité
pour l’activité des radionucléides,

*reconnaissant* que dans le Système international d’unités (SI), l’unité de cette activité est la
seconde à la puissance moins un (stem:["s"^{-1}]),

*admet* que le curie soit encore retenu comme unité en dehors du SI pour l’activité, avec la
valeur stem:[3,7 xx 10^(10)] stem:["s"^{-1}]. Le symbole de cette unité est stem:["Ci"].

NOTE: Le nom « becquerel » (stem:["Bq"]) a été adopté par la
15^e^ CGPM en 1975 (Résolution 8, _voir_ p. 63)
pour l’unité SI d’activité:
stem:[1 " Ci" = 3,7 xx 10^(10) " Bq"].

=== Préfixes SI femto et atto (CR, 94)

[align=center]
*Résolution 8*

La Douzième Conférence générale des poids et mesures,

décide d’ajouter à la liste des préfixes pour la formation des noms des multiples et des
sous-multiples des unités, adoptée par la Onzième Conférence générale, Résolution 12,
paragraphe 3, les deux nouveaux préfixes suivants:

[cols="<,<,<",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[10^{-15}] | femto | stem:["f"]
| stem:[10^{-18}] | atto | stem:["a"]
|===

NOTE: De nouveaux préfixes
furent ajoutés par la 15^e^ CGPM en 1975
(Résolution 10, _voir_ p. 63).