[[cipm1967]]
[%unnumbered]
== CIPM, 1967 (((masse))) index-range:kilogramme_multiples[(((kilogramme,multiples et sous-multiples)))] index-range:multiples_kilogramme[(((multiples du kilogramme)))]

[[cipm1967r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Multiples et sous-multiples décimaux de l’unité de masse* (PV, *35*, 29 et _Metrologia_, 1968, *4*, 45)

[[cipm1967r2r2]]
==== Recommandation 2

____
Le Comité international des poids et mesures,

*considérant* que la règle de formation des noms des multiples et sous-multiples décimaux des
unités du paragraphe 3 de la Résolution 12 de la Onzième Conférence générale des poids et
mesures (1960) peut prêter à des interprétations divergentes dans son application à l’unité de
masse,

*déclare* que les dispositions de la Résolution 12 de la Onzième Conférence générale
s’appliquent dans le cas du ((kilogramme)) de la façon suivante{nbsp}: les noms des multiples et
sous-multiples décimaux de l’unité de masse sont formés par l’adjonction des préfixes au mot
«{nbsp}gramme{nbsp}». (((gramme))) [[kilogramme_multiples]] [[multiples_kilogramme]]
____