== 13^e^ CGPM, 1967/68

=== Unité SI de temps (seconde) (CR, 103 et _Metrologia_, 1968, 4, 43)

____
[align=center]
*Résolution 1*

La Treizième Conférence générale des poids et mesures,

*considérant*

* que la définition de la seconde décidée par le Comité international des poids et mesures à sa
session de 1956 (Résolution 1) et ratifiée par la Résolution 9 de la Onzième Conférence
générale (1960), puis maintenue par la Résolution 5 de la Douzième Conférence générale
(1964) ne suffit pas aux besoins actuels de la métrologie,
* qu’à sa session de 1964 le Comité international des poids et mesures, habilité par la Résolution
5 de la Douzième Conférence (1964), a désigné pour répondre à ces besoins un étalon
atomique de fréquence à césium à employer temporairement,
* que cet étalon de fréquence est maintenant suffisamment éprouvé et suffisamment précis pour
servir à une définition de la seconde répondant aux besoins actuels,
* que le moment est venu de remplacer la définition actuellement en vigueur de l’unité de temps
du Système international d’unités par une définition atomique fondée sur cet étalon,


*décide*

. L’unité de temps du Système international d’unités est la seconde définie dans les termes
suivants:
+
--
« La seconde est la durée de 9 192 631 770 périodes de la radiation correspondant à
la transition entre les deux niveaux hyperfins de l’état fondamental de l’atome de
césium 133 ».
--
. La Résolution 1 adoptée par le Comité international des poids et mesures à sa session de
1956 et la Résolution 9 de la Onzième Conférence générale des poids et mesures sont
abrogées.
____

[NOTE]
====
Lors de sa session de 1997, le Comité international a
confirmé que cette définition se réfère à un
atome de césium au repos, à une température de 0 K.

La formulation de la définition de la seconde a
été modifiée par la CGPM à sa 26^e^ réunion en 2018
(Résolution 1, _voir_ p.92).
====

=== Unité SI de température thermodynamique (kelvin) (CR, 104 et _Metrologia_, 1968, 4, 43)

____
[align=center]
*Résolution 3*

La Treizième Conférence générale des poids et mesures,

*considérant*

* les noms « degré Kelvin » et « degré », les symboles « °K » et « deg » et leurs règles d’emploi
contenus dans la Résolution 7 de la Neuvième Conférence générale (1948), dans la Résolution
12 de la Onzième Conférence générale (1960) et la décision prise par le Comité international
des poids et mesures en 1962 (PV, *30*, 27),

* que l’unité de température thermodynamique et l’unité d’intervalle de température sont une
même unité qui devrait être désignée par un nom unique et par un symbole unique,

*décide*

. l’unité de température thermodynamique est désignée sous le nom « kelvin » et son symbole
est « K »; footnote:[Voir la Recommandation 2
(CI-2005) du CIPM relative à la composition
isotopique de l’eau entrant dans la définition du
kelvin (p. 76).]

. ce même nom et ce même symbole sont utilisés pour exprimer un intervalle de température;
. un intervalle de température peut aussi s’exprimer en degrés Celsius;
. les décisions mentionnées au premier considérant concernant le nom de l’unité de
température thermodynamique, son symbole et la désignation de l’unité pour exprimer un
intervalle ou une différence de température sont abrogées, mais les usages qui sont la
conséquence de ces décisions restent admis temporairement.
____

NOTE: À sa session de 1980, le Comité international a
approuvé le rapport de la 7^e^ session du CCU
demandant que l’emploi des symboles « °K » et
« deg » ne soit plus admis.


=== Définition de l’unité SI de température thermodynamique (kelvin) (CR, 104 et _Metrologia_, 1968, 4, 43)

____
[align=center]
*Résolution 4*

La Treizième Conférence générale des poids et mesures,

*considérant* qu’il est utile de formuler dans une rédaction explicite la définition de l’unité de
température thermodynamique contenue dans la Résolution 3 de la Dixième Conférence
générale (1954),

*décide* d’exprimer cette définition de la façon suivante:
« Le kelvin, unité de température thermodynamique, est la fraction 1/273,16 de la température
thermodynamique du point triple de l’eau. »
____

NOTE: Voir la Recommandation 5
(CI-1989) du CIPM relative à l’Échelle
internationale de température de 1990 (p. 69).

NOTE: Le kelvin a été redéfini
par la CGPM à sa 26^e^
réunion en 2018
(Résolution 1, _voir_ p.92).

=== Unité SI d’intensité lumineuse (candela) (CR, 104 et _Metrologia_, 1968, 4, 43-44)

____
[align=center]
*Résolution 5*

La Treizième Conférence générale des poids et mesures,

*considérant*

* la définition de l’unité d’intensité lumineuse ratifiée par la Neuvième Conférence générale
(1948) et contenue dans la « Résolution concernant le changement des unités
photométriques » adoptée par le Comité international des poids et mesures en 1946
(PV, *20*, 119) en vertu des pouvoirs conférés par la Huitième Conférence générale (1933),
* que cette définition fixe bien la grandeur de l’unité d’intensité lumineuse mais prête à des
critiques d’ordre rédactionnel,

*décide* d’exprimer la définition de la candela de la façon suivante:

« La candela est l’intensité lumineuse, dans la direction perpendiculaire, d’une surface de
1/600 000 mètre carré d’un corps noir à la température de congélation du platine sous la
pression de 101 325 newtons par mètre carré. »
____

NOTE: Définition abrogée en 1979 par la 16^e^ CGPM
(Résolution 3, _voir_ p. 63).


=== Unités SI dérivées (CR, 105 et _Metrologia_, 1968, 4, 44)

____
[align=center]
*Résolution 6*

La Treizième Conférence générale des poids et mesures,

*considérant* qu’il est utile de citer d’autres unités dérivées dans la liste du paragraphe 4 de la
Résolution 12 de la Onzième Conférence générale (1960),

*décide* d’y ajouter:

[cols="3",options="unnumbered"]
|===
| nombre d’ondes | 1 par mètre | stem:["m"^{-1}]
| entropie | joule par kelvin | stem:["J/K"]
| chaleur massique | joule par kilogramme kelvin | stem:["J"//("kg" * "K")]
| conductivité thermique | watt par mètre kelvin | stem:["W"//("m" * "K")]
| intensité énergétique | watt par stéradian | stem:["W/sr"]
| activité (d’une source radioactive) | 1 par seconde | stem:["s"^{-1}]
|===
____

NOTE: L’unité d’activité a reçu un nom spécial et un
symbole particulier lors de la 15^e^ CGPM en 1975
(Résolution 8, _voir_ p. 63).

=== Abrogation de décisions antérieures (micron et bougie nouvelle) (CR, 105 et _Metrologia_, 1968, 4, 44)

____
[align=center]
*Résolution 7*

La Treizième Conférence générale des poids et mesures,

*considérant* que les décisions prises ultérieurement par la Conférence générale concernant le
Système international d’unités contredisent quelques parties de la Résolution 7 de la Neuvième
Conférence générale (1948),

*décide* en conséquence de retirer de la Résolution 7 de la Neuvième Conférence:

. le nom d’unité « micron », et le symbole « stem:[mu] » qui fut attribué à cette unité et qui est devenu
un préfixe;
. le nom d’unité « bougie nouvelle ».
____