[[cipm1969]]
== CIPM, 1969

[[cipm1969r1]]
=== Système international d’unités, modalités d’application de la Résolution 12 de la 11^e^ CGPM (1960) (PV, 37, 30 et _Metrologia_, 1970, 6, 66)*

NOTE: La 20^e^ CGPM a décidé d’abroger en 1995 (<<cgpm20e1995r8r8,Résolution 8>>) la classe des unités supplémentaires dans le SI.

[[cipm1969r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures,

*considérant* que la Résolution 12 de la Onzième Conférence générale des poids et mesures
(1960), concernant le Système international d’unités, a suscité des discussions sur certaines
dénominations,

*déclare*

. les unités de base, les unités supplémentaires et les unités dérivées du Système international d’unités, qui forment un ensemble cohérent, sont désignées sous le nom
d’«unités SI»; footnote:[Le CIPM a approuvé en
2001 une proposition du CCU visant à clarifier la
définition des «unités SI» et «unités du SI»,
_voir_ <<cipm-unites-si>>]

. les préfixes adoptés par la Conférence générale pour la formation des multiples et
sous-multiples décimaux des unités SI sont appelés «préfixes SI»;

*et recommande*

[start=3]
. d’employer les unités SI et leurs multiples et sous-multiples décimaux dont les noms sont
formés au moyen des préfixes SI.

NOTE: L’appellation «unités supplémentaires», figurant dans la Résolution 12 de la Onzième
Conférence générale des poids et mesures (et dans la présente Recommandation), est donnée
aux unités SI pour lesquelles la Conférence générale ne décide pas s’il s’agit d’unités de base
ou bien d’unités dérivées.
____

