[[ccds1970]]
[%unnumbered]
== CCDS, 1970 (_In_ CIPM, 1970)

[NOTE]
====
L’Union astronomique internationale a précisé
cette définition dans sa Résolution A4 de 1991{nbsp}:

«{nbsp}Le TAI est une échelle de temps réalisée dont la
forme idéale, si l’on néglige un décalage
constant de stem:[32.184 "unitsml(s)"], est le Temps terrestre (TT),
lui-même relié à la coordonnée temps du
référentiel géocentrique, le Temps-coordonnée
géocentrique (TCG), par une marche
constante.{nbsp}»

(_voir_ Proc. 21st General Assembly of the IAU, _IAU Trans._, 1991, vol. *XXIB*, Kluwer.)
====

[[ccds-tai-definition]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Définition du TAI* (PV, *38*, 110-111 et _Metrologia_, 1971, *7*, 43)

[[ccds-tai-definition_s2]]
==== Recommandation S 2
____

Le Temps atomique international est la coordonnée de repérage temporel établie par le Bureau
international de l’heure sur la base des indications d’horloges atomiques fonctionnant dans
divers établissements conformément à la définition de la seconde, unité de temps du Système
international d’unités.
____

En 1980, la définition du TAI a été complétée comme suit (déclaration du CCDS, _BIPM Com.
cons. déf. seconde_, 1980, 9, S 15 et _Metrologia_, 1981, *17*, 70){nbsp}:

____
Le TAI est une échelle de temps-coordonnée définie dans un repère de référence géocentrique
avec comme unité d’échelle la seconde du SI telle qu’elle est réalisée sur le géoïde en rotation.
____
