[[cgpm14e1971]]
== 14^e^ CGPM, 1971

[[cgpm14e1971siemens]]
=== Pascal et siemens (CR, 78)

____
La 14^e^ Conférence générale a adopté les noms spéciaux «&nbsp;pascal&nbsp;» (symbole Pa) pour l’unité SI
newton par mètre carré et «&nbsp;siemens&nbsp;» (symbole S) pour l’unité SI de conductance électrique
(ohm à la puissance moins un).
____

[[cgpm14e1971r1]]
=== Temps atomique international; rôle du CIPM (CR, 77-78 et _Metrologia_, 1972, 8, 35)

[[cgpm14e1971r1r1]]
==== Résolution 1
____

La Quatorzième Conférence générale des poids et mesures,

*considérant*

* que la seconde, unité de temps du Système international d’unités, est définie depuis 1967
d’après une fréquence atomique naturelle, et non plus d’après des échelles de temps fournies
par des mouvements astronomiques,
* que le besoin d’une échelle de Temps atomique international (TAI) est une conséquence de la
définition atomique de la seconde,
* que plusieurs organisations internationales ont assuré et assurent encore avec succès
l’établissement des échelles de temps fondées sur des mouvements astronomiques,
particulièrement grâce aux services permanents du Bureau international de l’heure (BIH),
* que le Bureau international de l’heure a commencé à établir une échelle de temps atomique
dont les qualités sont reconnues et qui a prouvé son utilité,
* que les étalons atomiques de fréquence servant à la réalisation de la seconde ont été
considérés et doivent continuer de l’être par le Comité international des poids et mesures
assisté d’un Comité consultatif, et que l’intervalle unitaire de l’échelle de Temps atomique
international doit être la seconde réalisée conformément à sa définition atomique,
* que toutes les organisations scientifiques internationales compétentes et les laboratoires
nationaux actifs dans ce domaine ont exprimé le désir que le Comité international et la
Conférence générale des poids et mesures donnent une définition du Temps atomique
international, et contribuent à l’établissement de l’échelle de Temps atomique international,
* que l’utilité du Temps atomique international nécessite une coordination étroite avec les
échelles de temps fondées sur des mouvements astronomiques,


*demande* au Comité international des poids et mesures

. de donner une définition du Temps atomique international; footnote:[La définition du TAI a été donnée par le CCDS en 1970 (maintenant renommé CCTF), _voir_ Recommandation S 2 (<<ccds-tai-definition_s2>>)]
. de prendre les mesures nécessaires, en accord avec les organisations internationales
intéressées, pour que les compétences scientifiques et les moyens d’action existants soient
utilisés au mieux pour la réalisation de l’échelle de Temps atomique international, et pour
que soient satisfaits les besoins des utilisateurs du Temps atomique international.
____

[[cgpm14e1971r3]]
=== Unité SI de quantité de matière (mole) (CR, 78 et _Metrologia_, 1972, 8, 36)

NOTE: À sa session de 1980, le CIPM a approuvé le rapport de la 7^e^ session du
CCU (1980) précisant que, dans cette définition, il est
entendu que l’on se réfère à des atomes de carbone 12 non liés,
au repos et dans leur état fondamental.

[[cgpm14e1971r3r3]]
==== Résolution 3
____

La Quatorzième Conférence générale des poids et mesures,

*considérant* les avis de l’Union internationale de physique pure et appliquée, de l’Union
internationale de chimie pure et appliquée et de l’Organisation internationale de normalisation
concernant le besoin de définir une unité de quantité de matière,

*décide*

. La mole est la quantité de matière d’un système contenant autant d’entités élémentaires qu’il
y a d’atomes dans stem:[0.012] kilogramme de carbone 12; son symbole est «&nbsp;mol&nbsp;». footnote:[La mole a été redéfinie
par la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).]

. Lorsqu’on emploie la mole, les entités élémentaires doivent être spécifiées et peuvent être
des atomes, des molécules, des ions, des électrons, d’autres particules ou des groupements
spécifiés de telles particules.

. La mole est une unité de base du Système international d’unités.
____

