== 15^e^ CGPM, 1975

=== Valeur recommandée pour la vitesse de la lumière (CR, 103 et _Metrologia_, 1975, 11, 179-180)

[align=center]
*Résolution 2*

La Quinzième Conférence générale des poids et mesures,

*considérant* l’excellent accord entre les résultats des mesures de longueur d’onde portant sur
des radiations de lasers asservis sur une raie d’absorption moléculaire dans la région visible ou
infrarouge, avec une incertitude estimée à stem:[+- 4 xx 10^{-9}] qui correspond à l’indétermination de la
réalisation du mètre,

NOTE: L’incertitude relative doit être comprise comme étant
trois fois l’incertitude-type estimée sur les résultats
considérés.

*considérant* aussi les mesures concordantes de la fréquence de plusieurs de ces radiations,

*recommande* l’emploi de la valeur qui en résulte pour la vitesse de propagation des ondes
électromagnétiques dans le vide stem:[c = 299 " " 792 " " 458] mètres par seconde.


=== Temps universel coordonné (UTC) (CR, 104 et _Metrologia_, 1975, 11, 180)

[align=center]
*Résolution 5*

La Quinzième Conférence générale des poids et mesures,

*considérant* que le système appelé « Temps universel coordonné » (UTC) est employé très
largement, qu’il est diffusé par la plupart des émetteurs hertziens de signaux horaires, que sa
diffusion fournit aux utilisateurs à la fois des fréquences étalons, le Temps atomique
international et une approximation du Temps universel (ou, si l’on préfère, du temps solaire
moyen),

*constate* que ce Temps universel coordonné est à la base du temps civil dont l’usage est légal
dans la plupart des pays,

*estime* que cet emploi est parfaitement recommandable.


=== Unités SI pour les rayonnements ionisants (becquerel et gray) (CR, 105 et _Metrologia_, 1975, 11, 180)

[align=center]
*Résolutions 8 et 9*

La Quinzième Conférence générale des poids et mesures,

en raison de l’urgence, exprimée par la Commission internationale des unités et mesures de
rayonnements (ICRU), d’étendre l’usage du Système international d’unités aux recherches et
aux applications de la radiologie,

en raison de la nécessité de rendre aussi simple que possible l’usage des unités aux
non-spécialistes,

tenant compte aussi de la gravité des risques d’erreurs dans la thérapeutique,

*adopte* le nom spécial suivant d’unité SI pour l’activité:

le *becquerel*, symbole stem:["Bq"], égal à la seconde à la puissance moins un (Résolution 8),

*adopte* le nom spécial suivant d’unité SI pour les rayonnements ionisants:

le *gray*, symbole stem:["Gy"], égal au joule par kilogramme (Résolution 9).

NOTE: À sa session de 1976, le Comité international a
approuvé le rapport de la 5^e^ session du CCU (1976)
précisant que, suivant l’avis de l’ICRU, le gray
peut être employé aussi pour exprimer l’énergie
communiquée massique, le kerma et l’indice de
dose absorbée.

NOTE: Le gray est l’unité SI de dose absorbée. Dans le domaine des rayonnements ionisants, le
gray peut encore être employé avec d’autres grandeurs physiques qui s’expriment aussi en
joules par kilogramme; le Comité consultatif des unités est chargé d’étudier cette question en
collaboration avec les organisations internationales compétentes.


=== Préfixes SI péta et exa (CR, 106 et _Metrologia_, 1975, 11, 180-181)

[align=center]
*Résolution 10*

La Quinzième Conférence générale des poids et mesures,

*décide* d’ajouter à la liste des préfixes SI pour la formation des noms des multiples des unités,
adoptée par la Onzième Conférence générale, Résolution 12, paragraphe 3,
les deux préfixes suivants:

[cols="<,<,<",options="unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole
| stem:[10^(15)] | peta | stem:["P"]
| stem:[10^(18)] | exa | stem:["E"]
|===

NOTE: De nouveaux préfixes furent ajoutés en 1991
par la 19^e^ CGPM (Résolution 4, _voir_ p. 70).

NOTE: En français, il est d’usage
courant de mettre un accent à péta.