[[cgpm16e1979]]
== 16^e^ CGPM, 1979

[[cgpm16e1979r3]]
=== Unité SI d’intensité lumineuse (candela) (CR, 100 et _Metrologia_, 1980, 16, 56)(((candela (cd))))

NOTE: La formulation de la définition de la candela(((candela (cd)))) a été modifiée par la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).

[[cgpm16e1979r3r3]]
==== Résolution 3
____

La Seizième Conférence générale des poids et mesures,

*considérant*

* que, malgré les efforts méritoires de quelques laboratoires, il subsiste des divergences
excessives entre les résultats de la réalisation de la candela(((candela (cd)))) à l’aide du corps noir étalon
primaire actuel,
* que les techniques radiométriques se développent rapidement, autorisant des précisions qui
sont déjà analogues à celles de la photométrie et que ces techniques sont déjà en usage dans
des laboratoires nationaux pour réaliser la candela(((candela (cd)))) sans avoir à construire un corps noir,
* que la relation entre les grandeurs lumineuses de la photométrie et les grandeurs énergétiques,
à savoir la valeur 683 lumens par watt pour l’efficacité lumineuse spectrale de la radiation
monochromatique de fréquence stem:[540 xx 10^12] hertz(((hertz (Hz)))), a été adoptée par le Comité international des
poids et mesures en 1977,
* que cette valeur a été reconnue suffisamment exacte pour le système des grandeurs
lumineuses photopiques footnote:[La vision photopique est détectée sur la rétine de
l’oeil par les cônes, sensibles aux luminances élevées (stem:[ii(L) >] environ stem:[10 " "rm(cd)" "rm(m)^{-2}]), qui
correspondent à la vision diurne.], qu’elle n’entraîne qu’un changement d’environ 3 % pour le système
des grandeurs lumineuses scotopiques footnote:[La vision scotopique est détectée sur la rétine de
l’oeil par les bâtonnets, sensibles aux faibles luminances (stem:[ii(L) <] environ stem:[10^{-3} " "rm(cd)" "rm(m)^{-2}]), qui correspondent à la vision nocturne.] et que par conséquent elle assure une ((continuité))
satisfaisante,
* que le moment est venu de donner à la candela(((candela (cd)))) une définition susceptible d’améliorer la facilité
d’établissement des étalons photométriques et leur précision, et qui s’applique aux grandeurs
photopiques et scotopiques de la photométrie et aux grandeurs à définir dans le domaine
mésopique footnote:[Dans le cas de luminances intermédiaires entre la
vision photopique et la vision scotopique, les cônes et les bâtonnets fonctionnent
simultanément, on est alors dans le domaine de la vision mésopique.],

*décide*
(((intensité lumineuse)))(((rayonnement monochromatique)))

. La candela(((candela (cd)))) est l’intensité lumineuse, dans une direction donnée, d’une source qui émet un
rayonnement monochromatique de fréquence stem:[540 xx 10^12] stem:["hertz"] et dont l’intensité énergétique
dans cette direction est 1/683 watt par stéradian(((stéradian (sr)))).

. La définition de la candela(((candela (cd)))) (à l’époque appelée bougie nouvelle(((bougie nouvelle)))) décidée par le Comité
international des poids et mesures en 1946 en vertu des pouvoirs conférés par la
8^e^ Conférence générale des poids et mesures (CGPM) en 1933, ratifiée par la 9^e^ CGPM en
1948, puis amendée par la 13^e^ CGPM en 1967, est abrogée.
____

[[cgpm16e1979r5]]
=== Nom spécial pour l’unité SI d’équivalent de dose (sievert) (CR, 100 et _Metrologia_, 1980, 16, 56)(((sievert (Sv))))

NOTE: Le Comité international a décidé en 1984 d’accompagner cette
Résolution d’une explication, (<<cipm1984r1r1,Recommandation 1>>).

[[cgpm16e1979r5r5]]
==== Résolution 5
____

La Seizième Conférence générale des poids et mesures,

*considérant*

* l’effort fait pour introduire les unités SI dans le domaine des ((rayonnements ionisants)),
* les risques que peuvent encourir des êtres humains soumis à des irradiations sous-estimées,
risques qui pourraient résulter de la confusion entre ((dose absorbée)) et équivalent de dose,
* que la prolifération des noms spéciaux représente un danger pour le Système international
d’unités et doit être évitée dans toute la mesure du possible, mais que cette règle peut être
transgressée lorsqu’il s’agit de sauvegarder la santé humaine,

*adopte* le nom spécial *_sievert_*, symbole stem:[rm(Sv)], pour l’unité SI d’équivalent de dose dans le
domaine de la radioprotection. Le sievert(((sievert (Sv)))) est égal au joule(((joule (J)))) par kilogramme.
____


[[cgpm16e1979r6]]
=== Symboles du litre (CR, 101 et _Metrologia_, 1980, 16, 56-57)

[[cgpm16e1979r6r6]]
==== Résolution 6 (((litre (L ou l))))
____

La Seizième Conférence générale des poids et mesures,

*reconnaissant* les principes généraux adoptés pour l’écriture des symboles des unités dans la
Résolution 7 de la 9^e^ Conférence générale des poids et mesures (1948),

*considérant* que le symbole stem:[rm(l)] pour l’unité litre a été adopté par le Comité international des poids
et mesures en 1879 et confirmé dans cette même Résolution de 1948,

*considérant* aussi que, afin d’éviter un risque de confusion entre la lettre l et le chiffre 1,
plusieurs pays ont adopté le symbole stem:[rm(L)] au lieu de stem:[rm(l)] pour l’unité litre,

*considérant* que le nom litre(((litre (L ou l)))), bien qu’il ne soit pas inclus dans le Système international d’unités,
doit être admis pour l’usage général avec ce Système,

*décide*, à titre exceptionnel, d’adopter les deux symboles stem:[rm(l)] et stem:[rm(L)] comme symboles utilisables
pour l’unité litre(((litre (L ou l)))) footnote:[Le Comité international a estimé encore prématuré,
en 1990, de choisir un symbole unique du litre.],

*considérant* en outre que dans l’avenir un seul des deux symboles devrait être retenu,

*invite* le Comité international des poids et mesures à suivre le développement de l’usage des
deux symboles et à donner à la 18^e^ Conférence générale des poids et mesures son avis sur la
possibilité de supprimer l’un d’eux.
____
