[[cipm1980]]
== CIPM, 1980

[[cipm1980r1]]
=== Unités SI supplémentaires (radian et stéradian) (PV, 48, 24 et _Metrologia_, 1981, 17, 72)(((radian (stem:["unitsml(rad)"]))))

NOTE: La classe des unités supplémentaires dans le SI
a été abrogée en 1995 par décision de la 20^e^ CGPM (<<cgpm20e1995r8r8,Résolution 8>>).

[[cipm1980r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures (CIPM),
(((ISO,ISO/TC 12)))(((unité(s),supplémentaires)))

*prenant en considération* la Résolution 3 adoptée par l’ISO/TC 12 en 1978 et la
Recommandation U 1 (1980) adoptée par le Comité consultatif des unités (CCU)
à sa 7^e^ session,

*considérant*
(((stéradian (sr))))(((unité(s),de base)))

* que les unités radian(((radian (stem:["unitsml(rad)"])))) et stéradian sont introduites usuellement dans des expressions des unités
pour des besoins de clarification, notamment en photométrie où le stéradian joue un rôle
important pour distinguer les unités correspondant aux diverses grandeurs, (((grandeurs,sans dimension)))
* que dans les équations utilisées on exprime généralement l’angle(((angle))) plan comme le rapport entre
deux longueurs et l’angle(((angle))) solide comme le rapport entre une aire et le carré d’une ((longueur)), et
que par conséquent ces grandeurs sont traitées comme des grandeurs sans dimension,
(((grandeurs,de base)))

* que l’étude des formalismes en usage dans le domaine scientifique montre qu’il n’en existe
aucun qui soit à la fois cohérent et convenable, et dans lequel les grandeurs angle(((angle))) plan et angle(((angle)))
solide soient considérées comme des grandeurs de base,

*considérant aussi*

* que l’interprétation donnée par le CIPM en 1969 pour la classe des unités supplémentaires
introduite dans la Résolution 12 de la 11^e^ Conférence générale des poids et mesures en 1960
laisse la liberté de traiter le radian(((radian (stem:["unitsml(rad)"])))) et le stéradian(((stéradian (sr)))) comme unités de base dans le Système
international,
* qu’une telle possibilité compromet la cohérence interne du Système international fondé sur sept
unités de base seulement,

*décide* d’interpréter la classe des unités supplémentaires dans le Système international comme
une classe d’unités dérivées sans dimension pour lesquelles la Conférence générale des poids
et mesures laisse la liberté de les utiliser ou non dans les expressions des unités dérivées du
Système international.
____
