== CIPM, 1984

[[cipm1984r1]]
=== Au sujet du sievert (PV, 52, 31 et _Metrologia_, 1985, 21, 90)

____
[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*considérant* la confusion qui continue d’exister au sujet de la Résolution 5, votée par la
16^e^ Conférence générale des poids et mesures (1979),

*décide* d’introduire l’explication suivante dans la Brochure « Le Système international d’unités
(SI) »:

La grandeur équivalent de dose stem:[H] est le produit de la dose absorbée stem:[D] de rayonnements
ionisants et de deux facteurs sans dimension stem:[Q] (facteur de qualité) et stem:[N] (produit de tous les
autres facteurs de multiplication) prescrits par l’International Commission on Radiological
Protection:

[stem%unnumbered]
++++
H = Q * N * D
++++

Ainsi, pour une radiation donnée, la valeur numérique de stem:[H] en joules par kilogramme peut être
différente de la valeur numérique de stem:[D] en joules par kilogramme, puisqu’elle est fonction de la
valeur de stem:[Q] et de stem:[N]. Afin d’éviter tout risque de confusion entre la dose absorbée stem:[D] et
l’équivalent de dose stem:[H], il faut employer les noms spéciaux pour les unités correspondantes,
c’est-à-dire qu’il faut utiliser le nom gray au lieu de joule par kilogramme pour l’unité de dose
absorbée stem:[D] et le nom sievert au lieu de joule par kilogramme pour l’unité d’équivalent de dose
stem:[H].
____

NOTE: Le CIPM a décidé en 2002 de modifier les
explications sur la grandeur « équivalent de
dose » dans la Brochure sur le <<cipm2002r2,SI (Recommandation 2 (CI-2002))>>.