[[cipm1984]]
== CIPM, 1984

[[cipm1984r1]]
=== Au sujet du sievert (PV, 52, 31 et _Metrologia_, 1985, 21, 90)(((sievert (stem:["unitsml(Sv)"]))))

NOTE: Le CIPM a décidé en 2002 de modifier les
explications sur la grandeur «&nbsp;équivalent de
dose&nbsp;» dans la Brochure sur le SI (Recommandation 2 (<<cipm2002r2r2,CI-2002>>)).

[[cipm1984r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures,
(((unité(s),ayant des noms spéciaux et des symboles particuliers)))

*considérant* la confusion qui continue d’exister au sujet de la Résolution 5, votée par la
16^e^ Conférence générale des poids et mesures (1979),

*décide* d’introduire l’explication suivante dans la Brochure «&nbsp;Le Système international d’unités
(SI)&nbsp;»:

La grandeur équivalent de dose stem:[ii(H)] est le produit de la ((dose absorbée)) stem:[ii(D)] de rayonnements
ionisants et de deux facteurs sans dimension stem:[ii(Q)] (facteur de qualité) et stem:[ii(N)] (produit de tous les
autres facteurs de multiplication) prescrits par l’International Commission on Radiological
Protection:

[stem%unnumbered]
++++
ii(H) = ii(Q) * ii(N) * ii(D)
++++

Ainsi, pour une radiation donnée, la valeur numérique de stem:[ii(H)] en joules(((joule (stem:["unitsml(J)"])))) par kilogramme peut être
différente de la valeur numérique de stem:[ii(D)] en joules par ((kilogramme)), puisqu’elle est fonction de la
valeur de stem:[ii(Q)] et de stem:[ii(N)]. Afin d’éviter tout risque de confusion entre la ((dose absorbée)) stem:[ii(D)] et
l’équivalent de dose stem:[ii(H)], il faut employer les noms spéciaux pour les unités correspondantes,
c’est-à-dire qu’il faut utiliser le nom gray(((gray (stem:["unitsml(Gy)"])))) au lieu de joule par kilogramme pour l’unité de dose
absorbée stem:[ii(D)] et le nom sievert au lieu de joule par kilogramme pour l’unité d’équivalent de dose
stem:[ii(H)].
____
