[[cgpm18e1987]]
== 18^e^ CGPM, 1987

[[cgpm18e1987r6]]
=== Ajustement prévu des représentations du volt et de l’ohm (CR, 100 et _Metrologia_, 1988, 25, 115)

[[cgpm18e1987r6r6]]
==== Résolution 6
____

La Dix-huitième Conférence générale des poids et mesures,

*considérant*

* que l’uniformité mondiale et la constance à long terme des représentations nationales des
unités électriques sont d’une importance majeure pour la science, le commerce et l’industrie du
point de vue technique comme du point de vue économique, (((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))
* que de nombreux laboratoires nationaux utilisent l’effet Josephson et commencent à utiliser
l’effet Hall quantique pour conserver respectivement des représentations du volt et de l’ohm qui
donnent les meilleures garanties de stabilité à long terme,
* qu’en raison de l’importance de la cohérence entre les unités de mesure des diverses
grandeurs physiques les valeurs attribuées à ces représentations doivent être autant que
possible en accord avec le SI,
* que l’ensemble des résultats des expériences en cours ou récemment achevées permettra
d’établir une valeur acceptable, suffisamment compatible avec le SI, pour le coefficient qui relie
chacun de ces effets à l’unité électrique correspondante,

*invite* les laboratoires dont les travaux peuvent contribuer à établir la valeur du quotient de la
tension par la fréquence dans l’effet Josephson et de la tension par le courant dans l’effet Hall
quantique à poursuivre activement ces travaux et à communiquer sans délai leurs résultats au
Comité international des poids et mesures et,

*charge* le Comité international des poids et mesures de recommander, dès qu’il le jugera
possible, une valeur de chacun de ces quotients et une date à laquelle elle pourra être mise en
pratique simultanément dans tous les pays; cette valeur devrait être annoncée au moins un an
à l’avance et pourrait être adoptée au 1^er^ janvier 1990.
____