[[cipm1988]]
== CIPM, 1988

[[cipm1988r1]]
=== Représentation du volt au moyen de l’effet Josephson (PV, 56, 19 et _Metrologia_, 1989, 26, 69)

NOTE: La CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>) a abrogé l’adoption d’une valeur
conventionnelle de stem:[ii(K)_"J"].

[[cipm1988r1r1]]
==== Recommandation 1 (((effet,Josephson)))
____

Le Comité international des poids et mesures
(((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))

*agissant* conformément aux instructions données dans la Résolution 6 de la 18^e^ Conférence
générale des poids et mesures concernant l’ajustement prévu des représentations du volt et de
l’ohm,

*considérant*

* qu’une étude approfondie des résultats des déterminations les plus récentes conduit à une
valeur de stem:[483597.9 " "rm(GHz)//rm(V)] pour la constante de Josephson(((constante, de Josephson (stem:[rm(K)_"J"], stem:[rm(K)_"J-90"]))), stem:[ii(K)_"J"], c’est-à-dire pour le quotient de
la fréquence par la tension correspondant au palier de rang stem:[n = 1] dans l’effet Josephson,
* que l’effet Josephson, avec cette valeur de stem:[ii(K)_"J"], peut être utilisé pour établir un étalon de
référence de force électromotrice dont l’incertitude (écart-type), par rapport au volt, est estimée
à stem:[4 xx 10^{-7}] en valeur relative et dont la reproductibilité est nettement meilleure,

*recommande*

* que l’on adopte, par convention, pour la constante de Josephson(((constante, de Josephson (stem:[rm(K)_"J"], stem:[rm(K)_"J-90"]))), stem:[ii(K)_"J"], la valeur
stem:[ii(K)_{"J-90"} = 483597.9 " "rm(GHz)//rm(V)] exactement,
* que cette nouvelle valeur soit utilisée à partir du 1^er^ janvier 1990, et non auparavant,
pour remplacer les valeurs actuellement en usage,
* que cette nouvelle valeur soit utilisée à partir de cette même date par tous les laboratoires qui
fondent sur l’effet Josephson leurs mesures de force électromotrice,
* qu’à partir de cette même date tous les autres laboratoires ajustent la valeur de leurs étalons de
référence pour la mettre en accord avec cette nouvelle valeur,

*estime* qu’aucun changement de cette valeur recommandée de la constante de Josephson(((constante, de Josephson (stem:[rm(K)_"J"], stem:[rm(K)_"J-90"]))) ne
sera nécessaire dans un avenir prévisible,

*attire* l’attention des laboratoires sur le fait que la nouvelle valeur est supérieure de stem:[3.9 " "rm(GHz)//rm(V)],
soit approximativement stem:[8 xx 10^{-6}] en valeur relative, à la valeur donnée en 1972 par le Comité
consultatif d’électricité dans sa Déclaration E-72.
____

[[cipm1988r2]]
=== Représentation de l’ohm au moyen de l’effet Hall quantique (PV, 56, 20 et _Metrologia_, 1989, 26, 70)

NOTE: Lors de sa 89^e^ session en 2000, le CIPM a approuvé
la déclaration de la 22^e^ session du CCEM
concernant la valeur de la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))).

NOTE: La CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>) a abrogé l’adoption d’une valeur conventionnelle de stem:[ii(R)_"K"].

[[cipm1988r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures,
(((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))

*agissant* conformément aux instructions données dans la Résolution 6 de la 18^e^ Conférence
générale des poids et mesures concernant l’ajustement prévu des représentations du volt et de
l’ohm,

*considérant*

* que la plupart des étalons actuels de référence de résistance électrique présentent au cours du
temps des variations significatives,
* qu’un étalon de référence de résistance électrique fondé sur l’effet Hall quantique serait stable
et reproductible,
* qu’une étude approfondie des résultats des déterminations les plus récentes conduit à une
valeur de stem:[25812.807 " " Omega] pour la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))), stem:[ii(R)_K], c’est-à-dire pour le quotient de la
tension de Hall par le courant correspondant au plateau de rang stem:[i = 1] dans l’effet Hall
quantique,
* que l’effet Hall quantique, avec cette valeur de stem:[ii(R)_"K"], peut être utilisé pour établir un étalon de
référence de résistance dont l’incertitude (écart-type), par rapport à l’ohm, est estimée stem:[2 xx 10^{-7}]
en valeur relative et dont la reproductibilité est nettement meilleure,

*recommande*

* que l’on adopte par convention, pour la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))), stem:[ii(R)_"K"], la valeur
stem:[ii(R)_{"K-90"} = 25812.807 " " Omega] exactement,
* que cette valeur soit utilisée à partir du 1^er^ janvier 1990, et non auparavant, par tous les
laboratoires qui fondent sur l’effet Hall quantique leurs mesures de résistance électrique,
* qu’à partir de cette même date tous les autres laboratoires ajustent la valeur de leurs étalons de
référence pour la mettre en accord avec stem:[ii(R)_{"K-90"}],
* que, pour établir un étalon de référence de résistance électrique fondé sur l’effet Hall quantique,
les laboratoires suivent les conseils pour la mise en oeuvre de la résistance de Hall quantifiée
élaborés par le Comité consultatif d’électricité et publiés par les soins du Bureau international
des poids et mesures, dans leur édition la plus récente,

*et estime* qu’aucun changement de cette valeur recommandée de la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"]))))
ne sera nécessaire dans un avenir prévisible.
____
