== CIPM, 1989

=== L’Échelle internationale de température de 1990 (PV, 57, 26 et _Metrologia_, 1990, 27, 13)

____
[align=center]
*Recommandation 5*

Le Comité international des poids et mesures (CIPM), conformément à l’invitation formulée par
la 18^e^ Conférence générale des poids et mesures en 1987 (Résolution 7),
a adopté l’Échelle internationale de température de 1990 (EIT-90) en remplacement de l’Échelle
internationale pratique de température de 1968 (EIPT-68).

Le CIPM *souligne* que, par rapport à l’EIPT-68, l’EIT-90

* s’étend vers des températures plus basses, jusqu’à stem:[0,65 " K"], et remplace, de ce fait, aussi
l’Échelle provisoire de température de 1976 (EPT-76),
* est en bien meilleur accord avec les températures thermodynamiques correspondantes,
* a une continuité, une précision et une reproductibilité nettement améliorées sur toute son
étendue,
* comporte des sous-domaines et donne, dans certains domaines, des définitions équivalentes
qui facilitent grandement son utilisation.

Le CIPM *note* de plus, que le texte de l’EIT-90 sera accompagné de deux documents,
_Supplementary Information for the ITS-90_ et _Techniques for Approximating the ITS-90_,
qui seront publiés par le Bureau international des poids et mesures et remis à jour
périodiquement.

Le CIPM recommande

* que l’EIT-90 soit mise en application le 1^er^ janvier 1990,
* et que, à la même date, l’EIPT-68 et l’EPT-76 soient abrogées.
____

NOTE: Le kelvin a été redéfini par
la CGPM à sa 26^e^ réunion en 2018 (Résolution 1,
_voir_ p.92).