[[cgpm19e1991]]
== 19^e^ CGPM, 1991

[[cgpm19e1991r4]]
=== Préfixes SI zetta, zepto, yotta et yocto (CR, 97 et _Metrologia_, 1992, 29, 3)

[[cgpm19e1991r4r4]]
==== Résolution 4
____

La 19^e^ Conférence générale des poids et mesures (CGPM),

*décide* d’ajouter à la liste des préfixes SI pour la formation des noms des multiples et
sous-multiples des unités, adoptée par la 11^e^ CGPM, Résolution 12, paragraphe 3,
la 12^e^ CGPM, Résolution 8 et la 15^e^ CGPM, Résolution 10, les préfixes suivants:

[cols="^,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[10^(21)] | zetta | stem:["Z"]
| stem:[10^(-21)] | zepto | stem:["z"]
| stem:[10^(24)] | yotta | stem:["Y"]
| stem:[10^(-24)] | yocto | stem:["y"]
|===

NOTE: Les noms zepto et zetta évoquent le chiffre sept
(septième puissance de stem:[10^3]) et la lettre «&nbsp;z&nbsp;»
remplace la lettre «&nbsp;s&nbsp;» pour éviter le double
emploi de la lettre «&nbsp;s&nbsp;» comme symbole. Les noms
yocto et yotta sont dérivés de octo, qui évoque le
chiffre huit (huitième puissance de stem:[10^3]); la lettre
«&nbsp;y&nbsp;» est ajoutée pour éviter l’emploi de la lettre
«&nbsp;o&nbsp;» comme symbole à cause de la confusion
possible avec le chiffre zéro.
____