[[cgpm20e1995]]
== 20^e^ CGPM, 1995

[[cgpm20e1995r8]]
=== Suppression de la classe des unités supplémentaires dans le SI (CR, 121 et _Metrologia_, 1996, 33, 83)

[[cgpm20e1995r8r8]]
==== Résolution 8
____

La 20^e^ Conférence générale des poids et mesures,

*considérant*

* que la 11^e^ Conférence générale, en 1960, dans sa Résolution 12 établissant le Système
international d’unités, SI, a distingué trois classes d’unités, celle des unités de base,
celle des unités dérivées et celle des unités supplémentaires, cette dernière comprenant
seulement le radian et le stéradian,
* que le statut des unités supplémentaires par rapport aux unités de base et aux unités dérivées,
a donné lieu à des discussions,
* que le Comité international des poids et mesures (CIPM), en 1980, constatant que le statut
ambigu des unités supplémentaires compromet la cohérence interne du SI,
a interprété dans sa Recommandation 1 (CI-1980) les unités supplémentaires, dans le SI,
comme des unités dérivées sans dimension,

*approuvant* l’interprétation donnée par le CIPM en 1980,

*décide*

* d’interpréter les unités supplémentaires, dans le SI, c’est-à-dire le radian et le stéradian,
comme des unités dérivées sans dimension dont les noms et les symboles peuvent être
utilisés, mais pas nécessairement, dans les expressions d’autres unités dérivées SI, suivant les
besoins,
* et, par conséquent, de supprimer la classe des unités supplémentaires en tant que classe
séparée dans le SI.
____