[[cgpm21e1999]]
== 21^e^ CGPM, 1999

[[cgpm21e1999r7]]
=== La définition du ((kilogramme)) (CR, 141-142 et _Metrologia_, 2000, 37, 94)

[[cgpm21e1999r7r7]]
==== Résolution 7
____

La 21^e^ Conférence générale des poids et mesures,

*considérant*
(((unité(s),de base)))

* le besoin d'assurer la stabilité à long terme du Système international d’unités (SI),
* l'incertitude intrinsèque relative à la stabilité à long terme du prototype qui sert à définir l'unité
de ((masse)), l'une des unités de base du SI,
* que cette incertitude se répercute sur la stabilité à long terme des trois autres unités de base du
SI, nommément l'ampère(((ampère (A)))), la mole(((mole (mol)))) et la candela(((candela (cd)))), dont la définition dépend de celle du
kilogramme,
* les progrès déjà obtenus dans différentes expériences destinées à relier l'unité de ((masse)) à des
constantes fondamentales(((constante, fondamentale (de la physique)))) ou atomiques,
* qu'il est souhaitable de disposer de plusieurs méthodes pour réaliser ce lien,

*recommande* que les laboratoires nationaux poursuivent leurs efforts pour affiner les
expériences qui relient l'unité de ((masse)) à des constantes fondamentales(((constante, fondamentale (de la physique)))) ou atomiques et qui
pourraient, dans l'avenir, servir de base à une nouvelle définition du kilogramme.
____

[[cgpm21e1999r12]]
=== Nom spécial donné à l'unité SI mole par seconde, le katal, pour exprimer l'activité catalytique (CR, 145 et _Metrologia_, 2000, 37, 95) index-range:katal_kat[(((katal (kat))))](((mole (mol))))

[[cgpm21e1999r12r12]]
==== Résolution 12
____

La 21^e^ Conférence générale des poids et mesures,

*considérant*

* l'importance pour la santé humaine et la sécurité de faciliter l'emploi des unités du Système
international d’unités (SI) dans les domaines de la médecine et de la biochimie,
* qu'une unité en dehors du SI appelée «&nbsp;unité&nbsp;» représentée par le symbole U, qui est égale à
stem:[1] stem:[mu rm(mol) cdot rm(min)^{-1}], et qui n'est pas cohérente avec le SI, a été largement répandue en médecine et
en biochimie depuis 1964 pour exprimer l'activité catalytique,
* que l'absence d'un nom spécial pour désigner l'unité dérivée et cohérente du SI qu'est la mole(((mole (mol))))
par seconde a conduit à ce que des résultats de mesures cliniques soient donnés en
différentes unités locales,
* que l'emploi des unités SI en médecine et en ((chimie clinique)) est vivement recommandé par les
unions internationales de ces domaines,
* que la Fédération internationale de ((chimie clinique)) et médecine de laboratoire a demandé au
Comité consultatif des unités de recommander le nom spécial katal, symbole kat, pour l'unité SI
mole par seconde,
* que tandis que la prolifération de noms spéciaux représente un danger pour le SI,
il existe des exceptions pour certains sujets liés à la santé humaine et à la sécurité
(15^e^ Conférence générale, 1975, Résolutions 8 et 9, 16^e^ Conférence générale, 1979,
Résolution 5),

*notant* que le nom katal, symbole kat, est utilisé pour l'unité SI mole(((mole (mol)))) par seconde depuis plus de
trente ans, pour exprimer l'activité catalytique,

*décide* d'adopter le nom spécial katal, symbole kat, pour l'unité SI mole(((mole (mol)))) par seconde pour
exprimer l'activité catalytique, particulièrement dans les domaines de la médecine et de la
biochimie,

et *recommande* que, lorsque le katal est utilisé, le mesurande soit spécifié en faisant référence
au mode opératoire de mesure; le mode opératoire de mesure doit mentionner le produit
indicateur de la réaction mesurée. [[katal_kat]]
____