[[cipm2002]]
[%unnumbered]
== CIPM, 2002 index-range:metre-2[(((mètre (stem:["unitsml(m)"]))))]

[[cipm2002r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Révision de la mise en pratique de la définition du mètre* (<<PV70>> et _Metrologia_, *40*, 103-133)

[[cipm2002r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures,

*rappelant*

* qu’en 1983 la 17^e^ Conférence générale des poids et mesures (CGPM) a adopté une nouvelle
définition du mètre,
* qu’à la même date la Conférence générale a invité le Comité international des poids et mesures
(CIPM)
** à établir des instructions pour la réalisation pratique de la nouvelle définition du mètre
(la mise en pratique),
** à choisir des radiations qui puissent être recommandées comme étalons de ((longueur))
d'onde pour la mesure interférentielle des longueurs et à établir des instructions pour leur
emploi,
** à poursuivre les études entreprises pour améliorer ces étalons et à compléter ou réviser
par la suite ces instructions,
* qu’en réponse à cette invitation le CIPM a adopté la Recommandation 1 (CI-1983) (mise en
pratique de la définition du mètre) avec pour effet
** [[cipm2002-abc]]que le mètre soit réalisé par l’une des méthodes suivantes{nbsp}:
+
--
[loweralpha]
... [[cipm2002-a]]au moyen de la ((longueur)) stem:[l] du trajet parcouru dans le vide par une onde électromagnétique
plane pendant la durée stem:[t]{nbsp}; cette longueur est obtenue à partir de la mesure de la durée stem:[t], en
utilisant la relation stem:[l = c_0 * t] et la valeur de la ((vitesse de la lumière dans le vide))
stem:[c_0 = 299792458 "unitsml(m/s)"],
... [[cipm2002-b]]au moyen de la longueur d’onde dans le vide stem:[ii(lambda)] d’une onde électromagnétique plane de
fréquence stem:[f]{nbsp}; cette longueur d’onde est obtenue à partir de la mesure de la fréquence stem:[f], en
utilisant la relation stem:[ii(lambda) = c_0 // f] et la valeur de la ((vitesse de la lumière dans le vide))
stem:[c_0 = 299792458 "unitsml(m/s)"],
... [[cipm2002-c]]au moyen de l’une des radiations de la liste ci-dessous, radiations pour lesquelles on peut
utiliser la valeur donnée de la longueur d’onde dans le vide ou de la fréquence, avec
l’incertitude indiquée, pourvu que l’on observe les conditions spécifiées et le mode opératoire
reconnu comme approprié{nbsp};
--
** que dans tous les cas les corrections nécessaires soient appliquées pour tenir compte
des conditions réelles telles que diffraction, gravitation ou imperfection du vide{nbsp};

** que dans le contexte de la ((relativité générale)), le mètre est considéré comme une unité de
((longueur)) propre. Sa définition s’applique donc seulement dans un domaine spatial
suffisamment petit, pour lequel les effets de la non-uniformité du champ gravitationnel
peuvent être ignorés (notons, qu’à la surface de la Terre, cet effet est d’environ stem:[1 xx 10^(-16)]
par mètre d’altitude en valeur relative). Dans ce cas, les seuls effets à prendre en compte
sont ceux de la relativité restreinte. Les méthodes locales, préconisées en <<cipm2002-b>> et <<cipm2002-c>> pour
réaliser le mètre, fournissent le mètre propre, mais la méthode préconisée en <<cipm2002-a>> ne le
permet pas nécessairement. La méthode préconisée en <<cipm2002-a>> devrait donc être restreinte
aux longueurs l suffisamment courtes pour que les effets prévus par la relativité générale
soient négligeables par rapport aux incertitudes de mesure. Si ce n’est pas le cas,
il convient de se référer au rapport du Groupe de travail du Comité consultatif du temps
et des fréquences (CCTF) sur l’application de la relativité générale à la métrologie pour
l’interprétation des mesures (Application of general relativity to metrology, _Metrologia_,
1997, *34*, 261-290),

* que le CIPM avait recommandé une liste de radiations à cet effet{nbsp};

*rappelant* aussi qu’en 1992 et en 1997 le CIPM a révisé la mise en pratique de la définition du
mètre{nbsp};

*considérant*

* que la science et les techniques continuent à exiger une meilleure exactitude dans la réalisation
du mètre{nbsp};
* que, depuis 1997, les travaux effectués dans les laboratoires nationaux, au BIPM et dans
d’autres laboratoires ont permis d’identifier de nouvelles radiations et des méthodes pour leur
mise en oeuvre qui conduisent à de plus faibles incertitudes{nbsp};
* que l’on s’oriente de plus en plus vers des fréquences optiques pour les activités liées au
temps, et que l’on continue à élargir le domaine d’application des radiations recommandées
dans la mise en pratique, non seulement à la métrologie dimensionnelle et à la réalisation du
mètre, mais aussi à la spectroscopie de haute résolution, à la physique atomique et
moléculaire, aux constantes fondamentales(((constante, fondamentale (de la physique)))) et aux télécommunications{nbsp};
* que l’on dispose maintenant d’un certain nombre de nouvelles valeurs plus exactes de
l’incertitude des fréquences de radiations d’atomes et d’ions refroidis très stables déjà
mentionnées dans la liste de radiations recommandées, que la valeur de la fréquence de la
radiation de plusieurs espèces d’atomes et d’ions refroidis a aussi été mesurée récemment, et
que de nouvelles valeurs améliorées, et présentant des incertitudes réduites de manière
significative, d’un certain nombre d’étalons de fréquence optique fondés sur des cuves à gaz
ont été déterminées, y compris dans le domaine des longueurs d’ondes pour les
télécommunications optiques{nbsp};
* que les nouvelles techniques de peigne à impulsions femtosecondes ont un intérêt manifeste
pour relier la fréquence des étalons de fréquence optique très stables à celle des étalons de
fréquence utilisés pour la réalisation de la seconde du Système international d’unités (SI), que
ces techniques de mesure sont un moyen commode pour assurer la traçabilité au SI et peuvent
fournir aussi bien des sources de fréquence que des techniques de mesure{nbsp}; [[metre-2]]


*reconnaît* que les techniques de peigne arrivent au moment opportun et sont appropriées, et
recommande de poursuivre les recherches pour étudier leurs possibilités{nbsp};

*accueille favorablement* les essais de validation en cours des techniques de peigne effectués
par comparaison avec les autres techniques de chaînes de fréquence{nbsp};

*encourage* les laboratoires nationaux de métrologie et les autres laboratoires à poursuivre les
études sur les techniques de peigne au plus haut niveau d’exactitude possible et à rechercher la
simplicité pour encourager leur mise en pratique la plus étendue{nbsp};

*recommande*

* que la liste des radiations recommandées donnée par le CIPM en 1997 (Recommandation 1
(CI-1997)) soit remplacée par la liste de radiations ci-dessous footnote:[La liste des radiations recommandées, Recommandation 1
(CI-2002), figure dans les <<PV70_1>> et dans _Metrologia_, 2003, *40*, 104-115.], qui inclut{nbsp};

** des valeurs mises à jour de la fréquence des atomes de calcium et d’hydrogène refroidis
et de l’ion piégé de strontium,
** la valeur de la fréquence de nouvelles espèces d’ions refroidis, y compris de l’ion piégé
de stem:["Hg"^\+], de l’ion piégé d’In^+^, et de l’ion piégé d’Yb^+^,
** des valeurs mises à jour de la fréquence de lasers asservis sur le rubidium, de lasers à
grenat d’yttrium-aluminium dopé au néodyme (Nd:YAG) et de lasers à hélium-néon
(stem:["He-Ne"]) asservis sur l’iode, de lasers à hélium-néon asservis sur le méthane, et de lasers
à dioxyde de ((carbone)) asservis sur le tétroxyde d’osmium à stem:[10 "unitsml(um)"],
** des valeurs de la fréquence d’étalons pour les télécommunications optiques, y compris
les lasers asservis sur le rubidium et l’acétylène.

&#x200c;. . .
____


[[cipm2002r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Équivalent de dose* (<<PV70>>)index-range:sievert_sv-2[(((sievert (stem:["unitsml(Sv)"]))))]

NOTE: _Voir_ aussi _J. Radiol. Prot._, 2005, 25, 97-100.

[[cipm2002r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures,

*considérant* que

* la définition actuelle de l’unité SI d’équivalent de dose (sievert) comprend un facteur «{nbsp}stem:[ii(N)]{nbsp}»
(produit de tous les autres facteurs de multiplication) prescrit par l’International Commission on
Radiological Protection (ICRP),
* l’ICRP et l’International Commission on Radiation Units and Measurements (ICRU) ont décidé
de supprimer ce facteur stem:[ii(N)] qui n’est plus considéré comme nécessaire,
* la définition actuelle de l’équivalent de dose stem:[ii(H)] dans le Système international d’unités, qui
comprend le facteur stem:[ii(N)], porte à confusion,

*décide* de modifier l’explication donnée dans la Brochure sur «{nbsp}Le Système International
d'Unités (SI){nbsp}» de la manière suivante{nbsp}:

La grandeur équivalent de dose stem:[ii(H)] est le produit de la ((dose absorbée)) stem:[ii(D)] de rayonnements
ionisants et du facteur sans dimension stem:[ii(Q)] (facteur de qualité) prescrit par l’ICRU, facteur défini
en fonction du transfert d’énergie linéaire{nbsp}:

[stem%unnumbered]
++++
ii(H) = ii(Q) * ii(D)
++++

Ainsi, pour une radiation donnée, la valeur numérique de stem:[ii(H)] en joules(((joule (stem:["unitsml(J)"])))) par kilogramme peut être
différente de la valeur de stem:[ii(D)] en joules par kilogramme, puisqu’elle
est fonction de la valeur de stem:[ii(Q)].

Le Comité *décide* donc de maintenir la dernière phrase de l’explication sous la forme suivante{nbsp}:

Afin d’éviter tout risque de confusion entre la ((dose absorbée)) stem:[ii(D)] et l’équivalent de dose stem:[ii(H)],
il faut employer les noms spéciaux pour les unités correspondantes, c’est-à-dire qu’il faut utiliser
le nom gray(((gray (stem:["unitsml(Gy)"])))) au lieu de joule par kilogramme pour l’unité de ((dose absorbée)) stem:[ii(D)] et le nom sievert
au lieu de joule par kilogramme pour l’unité d’équivalent de dose stem:[ii(H)]. [[sievert_sv-2]]
____

