[[cipm2003]]
== CIPM, 2003

[[cipm2003r1]]
=== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (PV, 71, 70 et _Metrologia_, 2004, 41, 99-100)

[[cipm2003r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures,

considérant que

* l’on dispose depuis peu de meilleures valeurs des fréquences des radiations de certains
étalons à ions refroidis très stables, déjà publiées dans la liste des radiations recommandées;
* l’on a déterminé de meilleures valeurs des fréquences des étalons de fréquence optique dans
l’infrarouge, fondés sur des cuves à gaz, dans le domaine des télécommunications optiques,
valeurs déjà publiées dans la liste des radiations recommandées;
* l’on a effectué récemment et pour la première fois des mesures de fréquence à l’aide de
peignes à impulsions femtosecondes de certains étalons fondés sur des cuves à iode, qui
figurent sur la liste complémentaire de radiations recommandées, mesures qui conduisent à
une réduction considérable de l’incertitude;

*propose* que la liste des radiations recommandées soit révisée pour inclure:

* les valeurs mises à jour des fréquences de la transition quadripolaire de l’ion piégé de ^88^Sr^\+^ et
de la transition octupolaire de l’ion piégé de ^171^Yb^+^;
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’acétylène à stem:[1.54] stem:[mu"m"];
* des valeurs mises à jour de la fréquence d’étalons asservis sur l’iode à 543 nm et à 515 nm.
____