[[cgpm22e2003]]
== 22^e^ CGPM, 2003

[[cgpm22e2003r10]]
=== Symbole du séparateur décimal (CR, 169 et _Metrologia_, 2004, 41, 104)

[[cgpm22e2003r10r10]]
==== Résolution 10
____

La 22^e^ Conférence générale des poids et mesures,

*considérant* que

* l’un des principaux objectifs du Système international d’unités (SI) est de permettre d’exprimer
la valeur des grandeurs d’une manière aisément compréhensible dans le monde entier,
* la valeur d’une grandeur est normalement exprimée par un nombre qui multiplie une unité,
* souvent le nombre utilisé pour exprimer la valeur d’une grandeur contient plusieurs chiffres,
avec une partie entière et une partie décimale,
* la 9^e^ Conférence générale dans sa Résolution 7 (1948) avait décidé que «&nbsp;Dans les nombres,
la virgule (usage français) ou le point (usage britannique) sont utilisés seulement pour séparer
la partie entière des nombres de leur partie décimale&nbsp;»,
* conformément à la décision du Comité international des poids et mesures lors de sa
86^e^ session (1997), le Bureau international des poids et mesures utilise maintenant le point
(sur la ligne) comme séparateur décimal dans toutes les versions en anglais de ses
publications, y compris dans le texte anglais de la Brochure sur le SI (la référence internationale
sur le SI), tout en continuant à utiliser la virgule (sur la ligne) comme séparateur décimal dans
toutes ses publications en français,
* néanmoins certaines organisations internationales utilisent la virgule sur la ligne comme
séparateur décimal dans leurs documents en anglais,
* de plus, certaines organisations internationales, y compris certaines organisations
internationales de normalisation, spécifient que le séparateur décimal doit être la virgule sur la
ligne, dans toutes les langues,
* la recommandation d’utiliser la virgule sur la ligne comme séparateur décimal est, dans de
nombreuses langues, en conflit avec l’usage courant, qui consiste à utiliser le point sur la ligne,
* le fait d’utiliser le point sur la ligne ou la virgule sur la ligne comme séparateur décimal n’est pas
toujours lié à la langue, car certains pays de même langue maternelle ont des usages
différents, alors que d’autres pays pratiquant le plurilinguisme utilisent le point sur la ligne ou la
virgule sur la ligne suivant la langue,

*déclare* que le symbole du séparateur décimal pourra être le point sur la ligne ou la virgule sur
la ligne,

*réaffirme* que «&nbsp;Pour faciliter la lecture, les nombres peuvent être partagés en tranches de trois
chiffres; ces tranches ne sont jamais séparées par des points, ni par des virgules&nbsp;», comme le
recommande la Résolution 7 de la 9^e^ Conférence générale de 1948.
____