[[cipm2005]]
== CIPM, 2005

[[cipm2005r2]]
=== Clarification de la définition du kelvin, unité de température thermo-dynamique (PV, 73, 119 et _Metrologia_, 2006, 43, 177-178)(((kelvin (K))))

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).

[[cipm2005r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures (CIPM),
index-range:eau_isotopique[((("eau, composition isotopique")))]

*considérant*

* que le kelvin(((kelvin (K)))), l’unité de température thermodynamique, est défini par la fraction stem:[1//273.16] de la
température thermodynamique du ((point triple de l’eau)),
* que la température du point triple de l’eau dépend des abondances relatives des isotopes de
l’hydrogène et de l’oxygène présents dans l’échantillon d’eau utilisé,
* que cet effet est maintenant l’une des sources majeures d’écarts observés entre les différentes
réalisations du point triple de l’eau,

*décide*

* que la définition du kelvin(((kelvin (K)))) se réfère à une eau de composition isotopique spécifiée,
* que cette composition isotopique de l’eau soit la suivante{nbsp}: (((mole (mol))))
+
--
[align=left]
stem:[0.00015576] mole de ^2^H par mole de ^1^H, +
stem:[0.0003799] mole de ^17^O par mole de ^16^O, et +
stem:[0.0020052] mole de ^18^O par mole de ^16^O,

cette composition étant celle du matériau de référence de l’Agence internationale de l’énergie
atomique «&nbsp;Vienna Standard Mean Ocean Water (VSMOW)&nbsp;», recommandée par l’Union
internationale de chimie pure et appliquée dans «&nbsp;Atomic Weights of the Elements{nbsp}: Review
2000&nbsp;»,
--

* que cette composition soit définie dans une note attachée à la définition du kelvin dans la
Brochure sur le SI de la manière suivante{nbsp}: (((mole (mol))))
+
--
«&nbsp;Cette définition se réfère à l’eau de composition isotopique définie par les rapports de
((quantité de matière)) suivants{nbsp}: stem:[0.00015576] mole de ^2^H par mole de ^1^H, stem:[0.0003799] mole de
^17^O par mole de ^16^O et stem:[0.0020052] mole de ^18^O par mole de ^16^O&nbsp;».
--
____



[[cipm2005r3]]
=== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (PV, 73, 120 et _Metrologia_, 2006, 43, 178)

[[cipm2005r3r3]]
==== Recommandation 3
____

Le Comité international des poids et mesures,

*considérant que*

* l’on dispose de meilleures valeurs des fréquences des radiations de certains étalons à ion ou à
atomes refroidis très stables, déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a déterminé de meilleures valeurs des fréquences des étalons de fréquence optique,
fondés sur des cuves à gaz, dans le domaine des télécommunications optiques, dans
l’infrarouge, valeurs déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a déterminé de meilleures valeurs des fréquences de certains étalons fondés sur des cuves
à iode, valeurs déjà publiées dans la liste complémentaire des sources recommandées{nbsp};
* l’on a effectué pour la première fois des mesures de la fréquence de nouveaux atomes
refroidis, d’atomes dans la région de l’infrarouge proche et de molécules dans le domaine des
télécommunications optiques, à l’aide de peignes à impulsions femtosecondes{nbsp};

*décide* que la liste des radiations recommandées soit révisée pour y inclure{nbsp}:

* les valeurs mises à jour des fréquences des transitions quadripolaires de l’ion piégé de ^88^Sr^\+^,
de l’ion piégé de ^199^Hg^+^ et de l’ion piégé de ^171^Yb^+^{nbsp};
* la valeur mise à jour de la fréquence de la transition de l’atome de calcium{nbsp};
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’acétylène à stem:[1.54 " "mu rm(m)]{nbsp};
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’iode à stem:[515 " "rm(nm)]{nbsp};
* la fréquence de la transition de l’atome de ^87^Sr à stem:[698 " "rm(nm)]{nbsp};
* les fréquences des transitions de l’atome de ^87^Rb autour de stem:[760 " "rm(nm)]{nbsp};
* les fréquences des transitions de la bande (stem:[nu1 + nu3]) de ^12^C~2~H~2~, et des bandes (stem:[nu1 + nu3]) et
(stem:[nu1 + nu3 + nu4 + nu5]) de ^13^C~2~H~2~, autour de stem:[1.54 " "mu rm(m)]. [[eau_isotopique]]
____