== CIPM, 2006

=== Au sujet des représentations secondaires de la seconde (PV, 74, 123 et _Metrologia_, 2007, 44, 97)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune de « valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » est à établir,
* que le Groupe de travail commun au Comité consultatif des longueurs (CCL) et au CCTF sur
la mise en pratique de la définition du mètre et sur les représentations secondaires de la
seconde, lors de sa réunion au Bureau international des poids et mesures (BIPM) en
septembre 2005, a discuté des fréquences des radiations candidates potentielles en vue de
leur inclusion dans la liste des représentations secondaires de la seconde,
* que le Groupe de travail commun au CCL et au CCTF a examiné et mis à jour les valeurs
des fréquences des transitions de l’ion de mercure (Hg), de l’ion de strontium (Sr), de l’ion
d’ytterbium (Yb) et de l’atome neutre de strontium lors de sa session de septembre 2006,
* que le CCTF avait déjà recommandé dans sa Recommandation CCTF 1 (2004) la fréquence
de la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de 87Rb
comme représentation secondaire de la seconde,

*recommande* que les fréquences des transitions suivantes soient utilisées comme
représentations secondaires de la seconde et soient intégrées à la nouvelle liste des « valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde »

* la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb, à la
fréquence de f^87^~Rb~ = 6 834 682 610,904 324 Hz, avec une incertitude-type relative estimée de
stem:[3 xx 10^{-15}],
* la transition optique non perturbée 5s ^2^S~1/2~ – 4d ^2^D~5/2~ de l’ion de ^88^Sr^\+^, à la fréquence de
f^88^Sr^+^ = 444 779 044 095 484 Hz, avec une incertitude-type relative estimée de stem:[7 xx 10^{-15}],
* la transition optique non perturbée
5d^10^ 6s ^2^S~1/2~ (stem:[F = 0]) – 5d^9^ 6s^2^ ^2^D~5/2~ (stem:[F = 2]) de l’ion de
^199^Hg^\+^, à la fréquence de f^199^Hg^+^ = 1 064 721 609 899 145 Hz, avec une incertitude-type
relative estimée de stem:[3 xx 10^{-15}],
* la transition optique non perturbée 6s ^2^S~1/2~ (F = 0) – 5d ^2^D~3/2~ (F = 2) de l’ion de ^171^Yb^\+^, à la
fréquence de f^171^Yb^+^ = 688 358 979 309 308 Hz, avec une incertitude-type relative estimée
de stem:[9 xx 10^{-15}],
* la transition optique non perturbée 5s^2^ ^1^S0 – 5s 5p ^3^P0 de l’atome neutre de ^87^Sr, à la
fréquence de f^87^~Sr~ = 429 228 004 229 877 Hz, avec une incertitude-type relative estimée de
stem:[1,5 xx 10^{-14}]