== CIPM, 2006

=== Au sujet des représentations secondaires de la seconde (PV, 74, 123 et _Metrologia_, 2007, 44, 97)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune de « valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » est à établir,
* que le Groupe de travail commun au Comité consultatif des longueurs (CCL) et au CCTF sur
la mise en pratique de la définition du mètre et sur les représentations secondaires de la
seconde, lors de sa réunion au Bureau international des poids et mesures (BIPM) en
septembre 2005, a discuté des fréquences des radiations candidates potentielles en vue de
leur inclusion dans la liste des représentations secondaires de la seconde,
* que le Groupe de travail commun au CCL et au CCTF a examiné et mis à jour les valeurs
des fréquences des transitions de l’ion de mercure (stem:["Hg"]), de l’ion de strontium (stem:["Sr"]), de l’ion
d’ytterbium (stem:["Yb"]) et de l’atome neutre de strontium lors de sa session de septembre 2006,
* que le CCTF avait déjà recommandé dans sa Recommandation CCTF 1 (2004) la fréquence
de la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb
comme représentation secondaire de la seconde,

*recommande* que les fréquences des transitions suivantes soient utilisées comme
représentations secondaires de la seconde et soient intégrées à la nouvelle liste des « valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde »

* la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb, à la
fréquence de stem:[f_("Rb")^(87) = 6 " "834 " "682 " " 610.904 " "324 " Hz"], avec une incertitude-type relative estimée de
stem:[3 xx 10^{-15}],
* la transition optique non perturbée stem:[5"s" text( )^2S_(1text(/)2) – 4"d" text()^2"D"_(5text(/)2)] de l’ion de ^88^Sr^\+^, à la fréquence de
stem:[f^(88)"Sr"^+ = 444 " "779 " "044 " "095 " "484 " Hz"], avec une incertitude-type relative estimée de stem:[7 xx 10^{-15}],
* la transition optique non perturbée
stem:[5"d"^(10) 6"s" text()^2"S"_(1text(/)2) (F = 0) – 5"d"^9 6"s"^2 text()^2"D"_(5text(/)2) (F = 2)] de l’ion de
^199^Hg^\+^, à la fréquence de stem:[f^(199)Hg^+ = 1 " "064 " "721 " "609 " "899 " "145 " Hz"], avec une incertitude-type
relative estimée de stem:[3 xx 10^{-15}],
* la transition optique non perturbée stem:[6"s" text()^2"S"_(1text(/)2) (F = 0) – 5"d" text()^2"D"_(3text(/)2) (F = 2)] de l’ion de ^171^Yb^\+^, à la
fréquence de stem:[f^(171)Yb^+ = 688 " "358 " "979 " "309 " "308 " Hz"], avec une incertitude-type relative estimée
de stem:[9 xx 10^{-15}],
* la transition optique non perturbée stem:[5"s"^2 text()^1"S"_0 – 5"s" 5"p" text()^3"P"_0] de l’atome neutre de ^87^Sr, à la
fréquence de stem:[f_("Sr")^(87) = 429 " " 228 " "004 " "229 " "877 " Hz"], avec une incertitude-type relative estimée de
stem:[1,5 xx 10^{-14}]