== CIPM, 2007

=== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (PV, 75, 85)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*considérant* que

* l’on a déterminé des valeurs plus précises des fréquences de molécules dans le domaine des
télécommunications optiques, valeurs déjà publiées dans la liste des fréquences étalons,
à l’aide de peignes à impulsions femtosecondes;
* l’on a déterminé, pour la première fois, les fréquences de molécules dans le domaine des
télécommunications optiques, à l’aide de peignes à impulsions femtosecondes;
* l’on a déterminé, pour la première fois, les fréquences de certaines transitions dans l’iode,
en cellule, transitions proches de la radiation émise par l’étalon de fréquence optique à
532 nm, à l’aide de peignes à impulsions femtosecondes;

*propose* que la liste des fréquences étalons soit révisée pour y inclure:

* les valeurs mises à jour des fréquences de la bande (stem:[ν1 + ν3]) de ^12^C~2~H~2~, autour de stem:[1,54] stem:[mu "m"];

* les valeurs des fréquences de la bande (stem:[2_{ν1}]) de ^12^C~2~HD, autour de stem:[1,54] stem:[mu "m"];

* les valeurs des fréquences des composantes hyperfines des transitions P(142) 37-0,
R(121) 35-0 et R(85) 33-0 dans l’iode à 532 nm.