== 23^e^ CGPM, 2007

=== Sur la révision de la mise en pratique de la définition du mètre et sur la mise au point de nouveaux étalons optiques de fréquence (CR, 171)

[align=center]
*Résolution 9*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* les progrès rapides et les améliorations importantes des performances des étalons optiques
de fréquence,
* que les techniques des peignes à impulsions femtosecondes sont maintenant couramment
utilisées pour relier les radiations optiques et micro-ondes dans un même lieu,
* que les laboratoires nationaux de métrologie travaillent à des techniques de comparaison
d’étalons optiques de fréquence sur de courtes distances,
* que des techniques de comparaison à distance doivent être élaborées au niveau international
afin de pouvoir comparer les étalons optiques de fréquence,

*accueille favorablement*

* les activités du Groupe de travail commun au Comité consultatif des longueurs et au Comité
consultatif du temps et des fréquences pour examiner les fréquences des représentations de
la seconde fondées sur des fréquences optiques,
* les ajouts à la mise en pratique de la définition du mètre des radiations recommandées
approuvées par le Comité international des poids et mesures en 2002, 2003, 2005, 2006 et
2007,
* l’initiative prise par le Bureau international des poids et mesures (BIPM) de s’interroger sur le
moyen de comparer les étalons optiques de fréquence,

*recommande* que

* les laboratoires nationaux de métrologie engagent les ressources nécessaires à la mise au
point d’étalons optiques de fréquence et à leur comparaison,
* le BIPM oeuvre à la coordination d’un projet international auquel participeraient les
laboratoires nationaux de métrologie, projet orienté vers l’étude des techniques qui pourraient
servir à comparer les étalons optiques de fréquence.


=== Sur la clarification de la définition du kelvin, unité de température thermodynamique (CR, 172)

[align=center]
*Résolution 10*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* que le kelvin, l’unité de température thermodynamique, est défini par la fraction 1/273,16 de
la température thermodynamique du point triple de l’eau,
* que la température du point triple de l’eau dépend des abondances relatives des isotopes de
l’hydrogène et de l’oxygène présents dans l’échantillon d’eau utilisé,
* que cet effet est maintenant l’une des sources majeures d’écarts observés entre les
différentes réalisations du point triple de l’eau,

*prend acte de, et accueille favorablement*, la décision du Comité international en octobre
2005, sur l’avis du Comité consultatif de thermométrie, selon laquelle

* la définition du kelvin se réfère à une eau de composition isotopique spécifiée

* cette composition isotopique de l’eau est la suivante:
+
--
[align=left]
0,00015576 mole de ^2^H par mole de ^1^H, +
0,0003799 mole de ^17^O par mole de ^16^O, et +
0,0020052 mole de ^18^O par mole de ^16^O,

cette composition étant celle du matériau de référence de l’Agence internationale de l’énergie
atomique « Vienna Standard Mean Ocean Water (VSMOW) », recommandée par l’Union
internationale de chimie pure et appliquée dans « Atomic Weights of the Elements: Review
2000 »,
--

* cette composition est définie dans une note attachée à la définition du kelvin dans la
Brochure sur le Système international d’unités de la manière suivante:
+
--
« Cette définition se réfère à l’eau de composition isotopique définie par les rapports de quantité
de matière suivants: stem:[0.000" " 155 " "76] mole de ^2^H par mole de ^1^H, stem:[0.000" " 379 " "9] mole de ^17^O par
mole de ^16^O et stem:[0.002 " "005 " "2] mole de ^18^O par mole de ^16^O ».
--

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion
en 2018 (Résolution 1, _voir_ p. 92).

=== Sur l’éventuelle redéfinition de certaines unités de base du Système international d’unités (SI) (CR, 174)

[align=center]
*Résolution 12*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* que les laboratoires nationaux de métrologie et le Bureau international des poids et mesures
(BIPM) ont consacré des efforts considérables depuis de nombreuses années en vue de
promouvoir et d’améliorer le Système international d’unités (SI), en repoussant les limites de
la métrologie, afin de définir les unités de base du SI en fonction de constantes de la nature –
les constantes physiques fondamentales,

* que parmi les sept unités de base du SI, seul le kilogramme est encore défini à partir d’un
objet matériel (artefact), à savoir le prototype international du kilogramme (2^e^ CGPM, 1889 et
3^e^ CGPM, 1901), et que les définitions de l’ampère, de la mole et de la candela dépendent du
kilogramme,

* la 21^e^ Conférence générale a adopté en 1999 la Résolution 7, laquelle recommandait que
« les laboratoires nationaux poursuivent leurs efforts pour affiner les expériences qui relient
l’unité de masse à des constantes fondamentales ou atomiques et qui pourraient, dans
l’avenir, servir de base à une nouvelle définition du kilogramme »,

* de nombreux progrès ont été réalisés ces dernières années pour relier la masse du prototype
international à la constante de Planck, stem:[h], ou à la constante d’Avogadro, stem:[N_"A"],

* les initiatives prises pour déterminer la valeur d’un certain nombre de constantes
fondamentales, y compris celle de la constante de Boltzmann stem:[k_"B"],

* que des implications significatives et des avantages potentiels découlent de nouvelles
définitions du kilogramme, de l’ampère, du kelvin et de la mole, suite aux progrès récents
accomplis,

* la Recommandation 1 (CI-2005) du Comité international adoptée lors de sa session d’octobre
2005 et diverses recommandations des Comités consultatifs sur la redéfinition d’une ou
plusieurs unités de base du SI,

*notant*

* que les changements dans les définitions des unités du SI doivent être cohérents,

* que les définitions des unités de base du SI doivent être faciles à comprendre,

* le travail effectué par le Comité international et par ses Comités consultatifs,

* la nécessité de contrôler les résultats des expériences,

* l’importance de solliciter les commentaires et les contributions de la vaste communauté des
scientifiques et des utilisateurs,

* la décision du Comité international en 2005 d’approuver, en principe, la préparation de
nouvelles définitions du kilogramme, de l’ampère, du kelvin et la possibilité de redéfinir la
mole,

*recommande* que les laboratoires nationaux de métrologie et le BIPM

* poursuivent les expériences appropriées afin que le Comité international puisse juger s’il est
possible ou non de redéfinir le kilogramme, l’ampère, le kelvin et la mole en utilisant des
valeurs fixées pour certaines constantes fondamentales lors de la 24^e^ Conférence générale
en 2011,

* réfléchissent, en collaboration avec le Comité international, ses Comités consultatifs et les
groupes de travail concernés, aux moyens pratiques de réaliser les nouvelles définitions
fondées sur des valeurs fixées de constantes fondamentales, préparent une mise en pratique
de chacune d’elles, et examinent quel est le moyen le plus approprié pour expliquer les
nouvelles définitions aux utilisateurs,

* suscitent des campagnes de sensibilisation pour alerter les communautés d’utilisateurs sur
l’éventualité de nouvelles définitions afin que leurs implications techniques et juridiques, ainsi
que leurs réalisations pratiques, soient discutées et examinées avec soin,

*et demande* au Comité international de présenter un rapport à ce sujet à la 24^e^ Conférence
générale en 2011 et d’entreprendre tous les préparatifs qu’il considère comme nécessaires de
manière à ce que, si les résultats des expériences sont jugés convenables et les besoins des
utilisateurs satisfaits, il puisse être officiellement proposé à la 24^e^ Conférence générale
d’approuver de nouvelles définitions du kilogramme, de l’ampère, du kelvin et de la mole.

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la
révision du SI (Résolution 1, _voir_ p. 92).