[[cipm2009]]
== CIPM, 2009

[[cipm2009r2]]
=== Mises à jour de la liste des fréquences étalons (PV, 77, 105)

[[cipm2009r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des «valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde» a été établie;

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste;

*recommande*

que les fréquences de transition suivantes soient incluses ou mises à jour dans la liste des
fréquences étalons recommandées:

* la transition optique non perturbée stem:[5"s"^2 text()^1"S"_0 – 5"s" 5"p" text()^3"P"_0] de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f = 429228004229873.7 " Hz"], avec une incertitude-type relative de
stem:[1 xx 10^{-15}] (cette radiation a déjà été approuvée par le CIPM comme représentation secondaire
de la seconde);

* la transition optique non perturbée stem:[5"s"^2 text()^1"S"_0 – 5"s" 5"p" text()^3"P"_0] de l’atome neutre de ^88^Sr,
à la fréquence de stem:[f = 429228066418012 " Hz"], avec une incertitude-type relative de
stem:[1 xx 10^{-14}];

* la transition optique non perturbée stem:[4"s" text()^2 "S"_(1text(/)2) – 3"d" text()^2"D"_(5text(/)2)] de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f = 411042129776393 " Hz"], avec une incertitude-type relative de stem:[4 xx 10^{-14}];

* la transition optique non perturbée ^2^S~1/2~ stem:[(F = 0) – text()^2 F_(7text(/)2) (F = 3, m_F = 0)] de l’ion de ^171^Yb^+^, à la
fréquence de stem:[f = 642121496772657 " Hz"], avec une incertitude-type relative de stem:[6 xx 10^{-14}];

* la transition optique non perturbée stem:[6"s"^2 text()^1"S"_0 (F = 1text(/)2) – 6"s" 6"p" text()^3 "P"_0 (F = 1text(/)2)] de l’atome neutre de
^171^Yb à la fréquence de stem:[f = 518295836590864 " Hz"], avec une incertitude-type relative de
stem:[1.6 xx 10^{-13}].
____