== CIPM, 2009

=== Mises à jour de la liste des fréquences étalons (PV, 77, 105)

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures (CIPM),

considérant

* qu’une liste commune des « valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » a été établie;

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste;
recommande
que les fréquences de transition suivantes soient incluses ou mises à jour dans la liste des
fréquences étalons recommandées:

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s 5p ^3^P~0~ de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f = 429 228 004 229 873,7] stem:["Hz"], avec une incertitude-type relative de
stem:[1 xx 10^{-15}] (cette radiation a déjà été approuvée par le CIPM comme représentation secondaire
de la seconde);

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s 5p ^3^P~0~ de l’atome neutre de ^88^Sr,
à la fréquence de stem:[f = 429 228 066 418 012] stem:["Hz"], avec une incertitude-type relative de
stem:[1 xx 10^{-14}];

* la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f = 411042129776393] stem:["Hz"], avec une incertitude-type relative de stem:[4 xx 10^{-14}];

* la transition optique non perturbée ^2^S~1/2~ (F = 0) – ^2^F~7/2~ (F = 3, ~mF~ = 0) de l’ion de ^171^Yb^+^, à la
fréquence de stem:[f = 642121496772657] stem:["Hz"], avec une incertitude-type relative de stem:[6 xx 10^{-14}];

* la transition optique non perturbée 6s^2^ ^1^S~0~ (F = 1/2) – 6s 6p ^3^P~0~ (F = 1/2) de l’atome neutre de
^171^Yb à la fréquence de stem:[f = 518 295 836 590 864] stem:["Hz"], avec une incertitude-type relative de
stem:[1,6 xx 10^{-13}].