[[cipm2009]]
[%unnumbered]
== CIPM, 2009

[[cipm2009r2]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Mises à jour de la liste des fréquences étalons* (<<PV77_2>>)

[[cipm2009r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des «{nbsp}valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre(((mètre (stem:["unitsml(m)"])))) et aux représentations secondaires de la
seconde{nbsp}» a été établie{nbsp};

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste{nbsp};

*recommande*

que les fréquences de transition suivantes soient incluses ou mises à jour dans la liste des
fréquences étalons recommandées{nbsp}:

* la transition optique non perturbée stem:[5"s"^2 " "^1"S"_0 – 5"s " 5"p" " "^3"P"_0] de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f = 429228004229873.7 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1 xx 10^(-15)] (cette radiation a déjà été approuvée par le CIPM comme représentation secondaire
de la seconde){nbsp};

* la transition optique non perturbée stem:[5"s"^2 " "^1"S"_0 – 5"s " 5"p" " "^3"P"_0] de l’atome neutre de ^88^Sr,
à la fréquence de stem:[f = 429228066418012 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1 xx 10^(-14)]{nbsp};

* la transition optique non perturbée stem:[4"s" " "^2 "S"_(1//2) – 3"d" " "^2"D"_(5//2)] de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f = 411042129776393 "unitsml(Hz)"], avec une incertitude-type relative de stem:[4 xx 10^(-14)]{nbsp};

* la transition optique non perturbée stem:[text()^2"S"_(1//2) (ii(F) = 0) – " "^2 ii(F)_(7//2) (ii(F) = 3," " m_"F" = 0)] de l’ion de ^171^Yb^+^, à la
fréquence de stem:[f = 642121496772657 "unitsml(Hz)"], avec une incertitude-type relative de stem:[6 xx 10^(-14)]{nbsp};

* la transition optique non perturbée stem:[6"s"^2 " "^1"S"_0 (ii(F) = 1//2) – 6"s " 6"p" " "^3 "P"_0 (ii(F) = 1//2)] de l’atome neutre de
^171^Yb à la fréquence de stem:[f = 518295836590864 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1.6 xx 10^(-13)].
____
