== 24^e^ CGPM, 2011

=== Sur l’éventuelle révision à venir du Système international d’unités, le SI (CR, 212)

____
[align=center]
*Résolution 1*

La Conférence générale des poids et mesures (CGPM), à sa 24^e^ réunion,

*considérant*

* qu’il existe un consensus international sur l’importance, la valeur et les bénéfices potentiels de la
redéfinition d’un certain nombre d’unités du Système international d’unités (SI),

* que les laboratoires nationaux de métrologie et le Bureau international des poids et mesures
(BIPM) ont, à juste titre, déployé des efforts considérables au cours de ces dernières
décennies afin de faire progresser le Système international d’unités (SI),
en repoussant les limites de la métrologie, de façon à ce que les unités de base du SI
puissent être définies en s’appuyant sur les constantes de la nature – les constantes
physiques fondamentales ou les propriétés des atomes,

* qu’un exemple marquant du succès de ces efforts est la définition actuelle de l’unité de
longueur du SI, le mètre (17^e^ réunion de la CGPM, 1983, Résolution 1), qui relie l’unité à une
valeur exacte de la vitesse de la lumière dans le vide stem:[c], à savoir 299 792 458 mètres par
seconde,

* que parmi les sept unités de base du SI, seul le kilogramme est encore défini à partir d’un
objet matériel (artefact), à savoir le prototype international du kilogramme (1^re^ réunion de la
CGPM, 1889; 3^e^ réunion de la CGPM, 1901), et que les définitions de l’ampère, de la mole et
de la candela dépendent du kilogramme,

* que, bien que le prototype international ait rendu des services à la science et la technologie
depuis qu’il a été sanctionné par la CGPM lors de sa 1re réunion en 1889, son utilisation
présente des limites importantes, l’une des plus significatives étant que sa masse n’est pas
explicitement reliée à une constante de la nature et que, par conséquent, sa stabilité à long
terme ne peut être garantie,

* que la CGPM, lors de sa 21^e^ réunion en 1999, a adopté la Résolution 7, laquelle recommande
que « les laboratoires nationaux poursuivent leurs efforts pour affiner les expériences qui relient
l’unité de masse à des constantes fondamentales ou atomiques et qui pourraient, dans l’avenir,
servir de base à une nouvelle définition du kilogramme »,

* que de nombreux progrès ont été effectués ces dernières années pour relier la masse du
prototype international à la constante de Planck stem:[h], par des méthodes telles que les
expériences de la balance du watt ou les mesures de la masse d’un atome de silicium,

* que les incertitudes associées à l’ensemble des unités électriques du SI réalisées, directement ou
indirectement, au moyen de l’effet Josephson et de l’effet Hall quantique et à partir des valeurs
dans le SI des constantes de Josephson et de von Klitzing, stem:[K_"J"] et stem:[R_"K"], pourraient être réduites de
manière significative si le kilogramme était redéfini de façon à ce qu’il soit relié à une valeur
numérique exacte de stem:[h], et si l’ampère était redéfini de façon à ce qu’il soit relié à une valeur
numérique exacte de la charge élémentaire stem:[e],

* que la définition actuelle du kelvin se fonde sur une propriété intrinsèque de l’eau qui, bien
qu’étant une constante de la nature, dépend dans la pratique de la pureté et de la
composition isotopique de l’eau utilisée,

* qu’il est possible de redéfinir le kelvin de façon à le relier à une valeur numérique exacte de
la constante de Boltzmann stem:[k],

* qu’il est également possible de redéfinir la mole de façon à la relier à une valeur numérique
exacte de la constante d’Avogadro stem:[N_"A"], de sorte qu’elle ne dépende plus de la définition du
kilogramme, même lorsque le kilogramme sera défini de façon à le relier à une valeur
numérique exacte de stem:[h], ce qui mettrait en évidence la distinction entre les grandeurs quantité
de matière et masse,

* que les incertitudes liées aux valeurs d’autres constantes fondamentales et facteurs de
conversion d’énergie importants seraient éliminées ou réduites de façon considérable si stem:[h], stem:[e],
stem:[k] et stem:[N_"A"] avaient des valeurs numériques exactes lorsqu’elles sont exprimées en unités du SI,

* que la CGPM, lors de sa 23^e^ réunion en 2007, a adopté la Résolution 12 qui expose le travail
à accomplir par les laboratoires nationaux de métrologie, le BIPM et le Comité international
des poids et mesures (CIPM), ainsi que ses Comités consultatifs, afin que les nouvelles
définitions du kilogramme, de l’ampère, du kelvin et de la mole fondées sur des constantes
fondamentales puissent être adoptées,

* que, bien que des progrès notables aient été réalisés, tous les objectifs fixés par la
Résolution 12 adoptée par la CGPM à sa 23^e^ réunion n’ont pas été atteints, ce qui ne permet
pas au CIPM de soumettre une proposition finalisée,

* qu’il est néanmoins désormais possible de présenter une version claire et détaillée de ce qui
sera sans doute proposé,

*prend acte* de l’intention du Comité international des poids et mesures de proposer une révision
du SI qui se présenterait de la manière suivante:

* le Système international d’unités, le SI, sera le système d’unités selon lequel:
+
--
* la fréquence de la transition hyperfine dans l’état fondamental de l’atome de césium
133 stem:[Delta nu](^133^Cs)~hfs~ est égale à exactement stem:[9" " 192 " "631 " "770 text( hertz)],
* la vitesse de la lumière dans le vide stem:[c] est égale à exactement stem:[299 " "792 " "458] mètre
par seconde,
* la constante de Planck stem:[h] est égale à exactement stem:[6,626 " "06"X" xx 10^{-34}] joule seconde footnote:[Le symbole stem:["X"] apparaissant dans l’expression des constantes indique que le chiffre correspondant n’était pas connu au moment de l’adoption de la Résolution.],


* la charge élémentaire stem:[e] est égale à exactement stem:[1.602 " "17"X" xx 10^{-19} " coulomb"],
* la constante de Boltzmann stem:[k] est égale à exactement stem:[1.380" " 6"X" xx 10^{-23} " joule par kelvin"],
* la constante d’Avogadro stem:[N_"A"] est égale à exactement stem:[6.022" " 14"X" xx 10^(23) " par mole"],
* l’efficacité lumineuse stem:[K_{"cd"}] d’un rayonnement monochromatique de fréquence
stem:[540 xx 10^(12) " Hz"] est égale à exactement stem:[683 " lumens par watt"],
--

où

. les unités hertz, joule, coulomb, lumen et watt, qui ont respectivement pour symbole stem:["Hz", " J", " C", " lm"], et stem:["W"], sont reliées aux unités seconde, mètre, kilogramme, ampère, kelvin, mole et candela,
qui ont respectivement pour symbole stem:["s", " m", " kg", " A", " K", " mol"], et stem:["cd"], selon les relations stem:["Hz" = "s"^{-1}],
stem:["J" = "m"^2 " kg s"^{-2}], stem:["C" = "s A"], stem:["lm" = "cd m"^2 " m"^{-2} = "cd sr"], et stem:["W" = "m"^2 " kg s"^{-3}],

. le symbole stem:["X"] dans le présent projet de résolution correspond à un ou plusieurs chiffres qui
devront être ajoutés aux valeurs numériques de stem:[h], stem:[e], stem:[k], et stem:[N_"A"] selon les valeurs résultant de
l’ajustement le plus récent fourni par la CODATA,

ce qui signifie que le SI continuera à être établi sur les sept unités de base actuelles et que
notamment

* le kilogramme restera l’unité de masse mais son amplitude sera déterminée en
fixant la valeur numérique de la constante de Planck à exactement
stem:[6.626" " 06"X" xx 10^(−34)] lorsqu’elle sera exprimée en stem:["m"^2 " kg s"^{-1}], unité du SI égale au joule
seconde, stem:["J s"],

* l’ampère restera l’unité de courant électrique mais son amplitude sera déterminée
en fixant la valeur numérique de la charge élémentaire à exactement
stem:[1.602 " "17"X" xx 10^(−19)] lorsqu’elle sera exprimée en stem:["s A"], unité du SI égale au coulomb, stem:["C"],

* le kelvin restera l’unité de température thermodynamique mais son amplitude sera
déterminée en fixant la valeur numérique de la constante de Boltzmann à
exactement stem:[1.380 " "6"X" xx 10^(−23)] lorsqu’elle sera exprimée en stem:["m"^2 " kg s"^{-2} " K"^{-1}], unité du SI
égale au joule par kelvin stem:["J K"^{-1}],

* la mole restera l’unité de quantité de matière d’une entité élémentaire spécifique,
c’est-à-dire un atome, une molécule, un ion, un électron, ou toute autre particule ou
groupe particulier de telles particules, mais son amplitude sera déterminée en fixant
la valeur numérique de la constante d’Avogadro à exactement stem:[6.022 " "14"X" xx 10^(23)]
lorsqu’elle sera exprimée en unité du SI stem:["mol"^{-1}].

La Conférence générale des poids et mesures,

*note également*

* que les nouvelles définitions du kilogramme, de l’ampère, du kelvin et de la mole seront
rédigées en utilisant une formulation dite « à constante explicite », c’est-à-dire une définition
dans laquelle l’unité est définie indirectement en donnant explicitement une valeur exacte à
une constante fondamentale reconnue,

* que la définition actuelle du mètre est reliée à une valeur exacte de la vitesse de la lumière
dans le vide, qui est également une constante fondamentale reconnue,

* que la définition actuelle de la seconde est reliée à une valeur exacte caractérisant une
propriété bien définie de l’atome de césium, qui constitue également une constante de la
nature,

* que la définition existante de la candela n’est pas liée à une constante fondamentale mais
qu’elle peut être considérée comme étant reliée à une valeur exacte d’une constante de la
nature,

* que l’intelligibilité du Système international d’unités serait renforcée si toutes ses unités de
base étaient définies en utilisant la même formulation,

c’est pourquoi le Comité international des poids et mesures proposera également

de reformuler les définitions actuelles de la seconde, du mètre et de la candela selon une forme
complètement équivalente qui pourrait être la suivante:

* la seconde, symbole stem:["s"], est l’unité de temps; son amplitude est déterminée en fixant la valeur
numérique de la fréquence de la transition hyperfine de l’état fondamental de l’atome de
césium 133 au repos, à une température de stem:[0 " K"], à exactement stem:[9" " 192 " "631 " "770] lorsqu’elle est
exprimée en stem:["s"^{-1}], unité du SI égale au hertz, stem:[" Hz"],

* le mètre, symbole stem:["m"], est l’unité de longueur; son amplitude est déterminée en fixant la valeur
numérique de la vitesse de la lumière dans le vide à exactement stem:[299 " "792 " "458] lorsqu’elle est
exprimée en unité du SI stem:["m s"^(−1)],

* la candela, symbole stem:["cd"], est l’unité d’intensité lumineuse dans une direction donnée; son
amplitude est déterminée en fixant la valeur numérique de l’efficacité lumineuse d’un
rayonnement monochromatique d’une fréquence de stem:[540 xx 10^12] stem:["Hz"] à exactement 683
lorsqu’elle est exprimée en stem:["m"^{-2} " kg"^{-1} " s"^3 " cd sr"] ou en stem:["cd sr W"^{-1}], unité du SI égale au lumen par
watt, stem:["lm W"^{-1}].

Il sera ainsi manifeste que les définitions des sept unités de base du SI découlent naturellement
des sept constantes précédemment indiquées.

En conséquence, à la date choisie pour mettre en oeuvre la révision du SI

* la définition du kilogramme en vigueur depuis 1889, établie à partir de la masse du prototype
international du kilogramme (1^re^ réunion de la CGPM, 1889; 3^e^ réunion de la CGPM, 1901),
sera abrogée,

* la définition de l’ampère en vigueur depuis 1948 (9^e^ réunion de la CGPM, 1948), établie à
partir de la définition proposée par le Comité international des poids et mesures (CIPM, 1946,
Résolution 2), sera abrogée,

* les valeurs conventionnelles de la constante de Josephson stem:[K_{"J–90"}] et de la constante de von
Klitzing stem:[R_{"K–90"}] adoptées par le Comité international des poids et mesures
(CIPM, 1988, Recommandations 1 et 2) à la demande de la CGPM (18^e^ réunion de la CGPM,
1987, Résolution 6) pour l’établissement des représentations du volt et de l’ohm à l’aide des
effets Josephson et Hall quantique, respectivement, seront abrogées,

* la définition du kelvin en vigueur depuis 1967/68 (13^e^ réunion de la CGPM, 1967/68), établie
à partir d’une définition antérieure moins explicite (10^e^ réunion de la CGPM, 1954, Résolution
3), sera abrogée,

* la définition de la mole en vigueur depuis 1971 (14^e^ réunion de la CGPM, 1971, Résolution
3), selon laquelle la masse molaire du carbone 12 a la valeur exacte de stem:[0,012 " kg mol"^{-1}], sera
abrogée,

* les définitions existantes du mètre, de la seconde et de la candela, en vigueur depuis leur
adoption par la CGPM lors de ses 17^e^ (1983, Résolution 1), 13^e^ (1967/68, Résolution 1) et
16^e^ (1979, Résolution 3) réunions respectivement, seront abrogées.

La Conférence générale des poids et mesures,

*prend en considération* qu’à la même date

* la masse du prototype international du kilogramme stem:[m(cc "K")] sera égale à stem:[1 " kg"], avec cependant
une incertitude relative égale à celle de la valeur recommandée de stem:[h] juste avant la
redéfinition, puis sa valeur sera déterminée de façon expérimentale,

* la constante magnétique (la perméabilité du vide) stem:[mu_0] sera égale à stem:[4 pi xx 10^{-7} " H m"^{-1}], avec
cependant une incertitude relative égale à celle de la valeur recommandée de la constante
de structure fine stem:[alpha], puis sa valeur sera déterminée de façon expérimentale,

* la température thermodynamique du point triple de l’eau stem:[T_("TPW")] sera égale à stem:[273,16 " K"], avec
cependant une incertitude relative égale à celle de la valeur recommandée de stem:[k] juste avant la
redéfinition, puis sa valeur sera déterminée de façon expérimentale,

* la masse molaire du carbone 12 M(^12^C) sera égale à stem:[0,012 " kg mol"^{-1}], avec cependant une
incertitude relative égale à celle de la valeur recommandée de stem:[N_"A" h] juste avant la redéfinition,
puis sa valeur sera déterminée de façon expérimentale.


La Conférence générale des poids et mesures,

*encourage*

* les chercheurs des laboratoires nationaux de métrologie, le BIPM et les institutions
universitaires à poursuivre leurs efforts et à transmettre à la communauté scientifique en
général et à la CODATA en particulier les résultats de leurs travaux sur la détermination des
constantes de stem:[h], stem:[e], stem:[k], et stem:[N_"A"], et

* le BIPM à poursuivre son travail afin d’assurer la traçabilité au prototype international du
kilogramme des prototypes de masse qu’il maintient, ainsi qu’à mettre au point un ensemble
d’étalons de référence qui permettra de faciliter la dissémination de l’unité de masse une fois
le kilogramme redéfini,

*et invite*

* la CODATA à continuer à fournir des valeurs pour les constantes fondamentales de la
physique ajustées à partir de toutes les données pertinentes disponibles, ainsi qu’à
transmettre les résultats au CIPM par l’intermédiaire du Comité consultatif des unités,
puisque ce sont les valeurs et incertitudes de la CODATA qui seront utilisées pour la révision
du SI,

* le CIPM à lui proposer de réviser le SI dès que les recommandations de la Résolution 12
adoptée par la CGPM à sa 23^e^ réunion seront satisfaites, en particulier la préparation des
mises en pratique des nouvelles définitions du kilogramme, de l’ampère, du kelvin et de la
mole,

* le CIPM à poursuivre son travail afin d’obtenir une meilleure formulation des définitions des
unités de base du SI fondées sur des constantes fondamentales, l’objectif étant de parvenir,
autant que possible, à une description plus facilement compréhensible pour l’ensemble des
utilisateurs tout en gardant rigueur et clarté scientifiques,

* le CIPM, les Comités consultatifs, le BIPM, l’OIML et les laboratoires nationaux de métrologie
à intensifier leurs efforts afin de mettre en place des campagnes de sensibilisation pour
informer les communautés d’utilisateurs et le grand public du projet de redéfinition de
certaines unités du SI, et à encourager l’examen des implications juridiques, techniques et
pratiques de ces redéfinitions, afin de solliciter les commentaires et les contributions de la
vaste communauté des scientifiques et des utilisateurs.
____

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la révision du SI <<cgpm26th2018r1,(Résolution 1)>>.

=== Sur la révision de la mise en pratique de la définition du mètre et sur la mise au point de nouveaux étalons optiques de fréquence (CR, 227)

____
[align=center]
*Résolution 8*

La Conférence générale des poids et mesures (CGPM), à sa 24^e^ réunion,

*considérant*

* que les performances des étalons optiques de fréquence s’améliorent rapidement et de manière
très significative,

* que les laboratoires nationaux de métrologie mettent actuellement en oeuvre des techniques de
comparaison à courte distance d’étalons optiques de fréquence,

* que des techniques de comparaison à distance d’étalons optiques de fréquence doivent être
mises au point au niveau international,

*accueille favorablement*

* les activités du Groupe de travail commun au Comité consultatif des longueurs (CCL) et au
Comité consultatif du temps et des fréquences (CCTF) visant à examiner les fréquences des
représentations optiques de la seconde,

* les éléments ajoutés par le CIPM en 2009 à la liste commune des « valeurs recommandées de
fréquences étalons destinées à la mise en pratique de la définition du mètre et aux
représentations secondaires de la seconde »,

* l’établissement d’un groupe de travail du CCTF sur la coordination de la mise au point de
techniques avancées de comparaison de temps et de fréquences,

*recommande* que

* les laboratoires nationaux de métrologie engagent les ressources nécessaires à la mise au point
d’étalons optiques de fréquence et à leur comparaison,
* le BIPM aide à la coordination d’un projet international auquel participeraient les laboratoires
nationaux de métrologie, portant sur l’étude des techniques qui pourraient être utilisées pour
comparer les étalons optiques de fréquence.
____