== CIPM, 2013

=== Mises à jour de la liste des fréquences étalons (PV, 81, 53)

[align=center]
*Recommandation 1*


Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des « valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste,

*recommande* d’apporter les changements suivant à la liste commune des « valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde »:

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées:
** la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s 6p ^3^P~0~ de l’atome neutre de ^199^Hg,
à la fréquence de 1 128 575 290 808 162 Hz avec une incertitude-type relative estimée
de stem:[1,7 xx 10^{-14}];

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées:
** la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^,
à la fréquence de 411 042 129 776 395 Hz avec une incertitude-type relative estimée
de stem:[1,5 xx 10^{-14}];
** la transition optique non perturbée 1S – 2S de l’atome neutre de ^1^H, à la fréquence
de 1 233 030 706 593 518 Hz avec une incertitude-type relative estimée de
stem:[1,2 xx 10^{-14}];

Remarque: cette fréquence correspond à la moitié de l’écart en énergie entre les états 1S et
2S;

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde:
** la transition optique non perturbée 6s ^2^S~1/2~ – 4f ^13^6s^2^ ^2^F~7/2~ de l’ion de ^171^Yb^+^ (octupôle),
à la fréquence de 642 121 496 772 645,6 Hz avec une incertitude-type relative
estimée de stem:[1,3 xx 10^{-15}];
** la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s 6p ^3^P~0~ de l’atome neutre de ^171^Yb,
à la fréquence de 518 295 836 590 865,0 Hz avec une incertitude-type relative
estimée de stem:[2,7 xx 10^{-15}];

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde:
** la transition optique non perturbée 3s^2^ ^1^S~0~ – 3s 3p ^3^P~0~ de l’ion de ^27^Al^+^, à la fréquence
de 1 121 015 393 207 857,3 Hz avec une incertitude-type relative estimée de
stem:[1,9 xx 10^{-15}];

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde:
** la transition optique non perturbée 5d ^10^6s ^2^S~1/2~ – 5d ^9^6s^2^ ^2^D~5/2~ de l’ion de ^199^Hg^+^,
à la fréquence de 1 064 721 609 899 145,3 Hz avec une incertitude-type relative
estimée de stem:[1,9 xx 10^{-15}];
** la transition optique non perturbée 6s 2S1/2 (stem:[F = 0], stem:[m_F = 0]) – 5d ^2^D~3/2~ (F = 2, mF = 0) de
l’ion de 171Yb+ (quadrupôle), à la fréquence de 688 358 979 309 307,1 Hz avec une
incertitude-type relative estimée de stem:[3 xx 10^{-15}];
** la transition optique non perturbée 5s 2S1/2 – 4d ^2^D~5/2~ de l’ion de ^88^Sr^+^, à la fréquence
de 444 779 044 095 485,3 Hz avec une incertitude-type relative estimée de
stem:[4,0 xx 10^{-15}];
** la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s5p ^3^P~0~ de l’atome neutre de ^87^Sr, à la
fréquence de 429 228 004 229 873,4 Hz avec une incertitude-type relative estimée de
stem:[1 xx 10^{-15}];

* mettre à jour la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde:
** la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de
^87^Rb, à la fréquence de 6 834 682 610,904 312 Hz avec une incertitude-type
relative estimée de stem:[1,3 xx 10^{-15}].

Remarque: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.