[[cipm2013]]
[%unnumbered]
== CIPM, 2013

[[cipm2013r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Mises à jour de la liste des fréquences étalons* (<<PV81, page=53>>)

[[cipm2013r1r1]]
==== Recommandation 1
____

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des «{nbsp}valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre(((mètre (stem:["unitsml(m)"])))) et aux représentations secondaires de la
seconde{nbsp}» a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste,

*recommande* d’apporter les changements suivant à la liste commune des «{nbsp}valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde{nbsp}»{nbsp}:

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées{nbsp}:
** la transition optique non perturbée stem:[6"s"^2 " "^1S_0 – 6"s " 6"p" " "^3"P"_0] de l’atome neutre de ^199^Hg,
à la fréquence de stem:[1128575290808162 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[1.7 xx 10^(-14)]{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées{nbsp}:
** la transition optique non perturbée stem:[4"s" " "^2"S"_(1//2) – 3"d" " "^2"D"_(5//2)] de l’ion de ^40^Ca^+^,
à la fréquence de stem:[411042129776395 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[1.5 xx 10^(-14)]{nbsp};
** la transition optique non perturbée stem:[1"S" – 2"S"] de l’atome neutre de ^1^H, à la fréquence
de stem:[1233030706593518 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1.2 xx 10^(-14)]{nbsp};
+
NOTE: cette fréquence correspond à la moitié de l’écart en énergie entre les états stem:[1"S"] et stem:[2"S"]{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde{nbsp}:
** la transition optique non perturbée stem:[6"s" " "^2 "S"_(1//2) – 4"f" " "^(13)6"s"^2 " "^2"F"_(7//2)] de l’ion de ^171^Yb^+^ (octupôle),
à la fréquence de stem:[642121496772645.6 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[1.3 xx 10^(-15)]{nbsp};
** la transition optique non perturbée stem:[6"s"^2 " "^1"S"_0 – 6"s " 6"p" " "^3"P"_0] de l’atome neutre de ^171^Yb,
à la fréquence de stem:[518295836590865.0 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[2.7 xx 10^(-15)]{nbsp};

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde{nbsp}:
** la transition optique non perturbée stem:[3"s"^2 " "^1"S"_0 – 3"s " 3"p" " "^3"P"_0] de l’ion de ^27^Al^+^, à la fréquence
de stem:[1121015393207857.3 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1.9 xx 10^(-15)]{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde{nbsp}:
** la transition optique non perturbée stem:[5"d" " "^(10)6"s" " "^2"S"_(1//2) – 5"d" " "^96"s"^2 " "^2"D"_(5//2)] de l’ion de ^199^Hg^+^,
à la fréquence de stem:[1064721609899145.3 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[1.9 xx 10^(-15)]{nbsp};
** la transition optique non perturbée stem:[6"s" " "^2"S"_(1//2) (ii(F) = 0," "m_"F" = 0) – 5"d" " "^2"D"_(3//2) (ii(F) = 2," "m_"F" = 0)] de
l’ion de ^171^Yb^+^ (quadrupôle), à la fréquence de stem:[688358979309307.1 "unitsml(Hz)"] avec une
incertitude-type relative estimée de stem:[3 xx 10^(-15)]{nbsp};
** la transition optique non perturbée stem:[5"s" " "^2"S"_(1//2) – 4"d" " "^2"D"_(5//2)] de l’ion de ^88^Sr^+^, à la fréquence
de stem:[444779044095485.3 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[4.0 xx 10^(-15)]{nbsp};
** la transition optique non perturbée stem:[5"s"^2 " "^1"S"_0 – 5"s"5"p" " "^3"P"_0] de l’atome neutre de ^87^Sr, à la
fréquence de stem:[429228004229873.4 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1 xx 10^(-15)]{nbsp};

* mettre à jour la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde{nbsp}:
** la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de
^87^Rb, à la fréquence de stem:[6834682610.904312 "unitsml(Hz)"] avec une incertitude-type
relative estimée de stem:[1.3 xx 10^(-15)].

NOTE: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.
____
