[[cgpm25e2014]]
== 25^e^ CGPM, 2014

[[cgpm25e2014r1]]
=== Sur la révision à venir du Système international d’unités, le SI (CR, 177 et _Metrologia_, 2015, 52, 155)

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la révision du SI (<<cgpm26th2018r1r1,Résolution 1>>).

[[cgpm25e2014r1r1]]
==== Résolution 1
____

La Conférence générale des poids et mesures (CGPM), à sa 25^e^ réunion,
(((kilogramme,prototype international)))

*rappelant*

* la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011) qui prend acte de l’intention du
Comité international des poids et mesures (CIPM) de proposer une révision du SI consistant à
relier les définitions du kilogramme, de l’ampère(((ampère (A)))), du kelvin et de la mole à des valeurs numériques
exactes de la constante de Planck(((constante, de Planck))) stem:[h], de la charge élémentaire stem:[e], de la constante de Boltzmann(((constante, de Boltzmann))) stem:[k],
et de la constante d’Avogadro(((constante, d'Avogadro))) stem:[ii(N)_"A"], respectivement, et à modifier la façon de définir le SI, ainsi que
la formulation des définitions des unités du SI pour les grandeurs temps, longueur, masse, ((courant électrique)), température thermodynamique, quantité de matière et ((intensité lumineuse)), de manière
à ce que les constantes de référence sur lesquelles se fonde le SI apparaissent clairement,

* les nombreux avantages, mentionnés dans la Résolution 1, que présentera cette révision du SI
pour la science, la technologie, l’industrie et le commerce, tel que le fait de relier le kilogramme à
une constante de la nature et non plus à la masse d’un objet matériel (artefact), ce qui assurera sa
stabilité à long terme,

* la Résolution 7 adoptée par la CGPM à sa 21^e^ réunion (1999) qui encourage les laboratoires
nationaux de métrologie à poursuivre les expériences visant à parvenir à une telle redéfinition du
kilogramme,

* la Résolution 12 adoptée par la CGPM à sa 23^e^ réunion (2007) qui décrit les travaux devant
être effectués par les laboratoires nationaux de métrologie, le Bureau international des poids
et mesures (BIPM), ainsi que le CIPM et ses Comités consultatifs, afin de permettre
l’adoption par la CGPM de la révision du SI,

*considérant* les progrès significatifs réalisés afin d’effectuer les travaux nécessaires, parmi
lesquels,

* l’acquisition des données pertinentes, et leur analyse par le Committee on Data for Science
and Technology (&nbsp;((CODATA))&nbsp;), afin d’obtenir les valeurs requises pour les constantes
fondamentales(((constante, fondamentale (de la physique)))) de stem:[h], stem:[e], stem:[k], et stem:[ii(N)_"A"],

* la mise au point par le BIPM d’un ensemble d’étalons de masse de référence qui permettra
de faciliter la dissémination de l’unité de masse une fois le SI révisé,

* la préparation des mises en pratique des nouvelles définitions du ((kilogramme)), de l’ampère(((ampère (A)))),
du kelvin(((kelvin (K)))) et de la mole,

*notant que* le Comité consultatif des unités (CCU), le CIPM, le BIPM, les laboratoires nationaux
de métrologie et les Comités consultatifs doivent poursuivre leurs travaux en se concentrant sur

* la mise en place de campagnes de sensibilisation pour informer les communautés
d’utilisateurs et le grand public du projet de révision du SI,

* la préparation de la 9^e^ édition de la _Brochure sur le SI_ dans laquelle le SI révisé serait
présenté de façon compréhensible par l’ensemble des lecteurs sans pour autant en
compromettre la rigueur scientifique,

*considérant que*, malgré les progrès effectués, les données disponibles ne semblent pas
encore suffisamment robustes pour que la CGPM adopte le SI révisé lors de sa 25^e^ réunion,

*encourage*

* les laboratoires nationaux de métrologie, le BIPM et les institutions universitaires à poursuivre
leurs efforts afin de déterminer expérimentalement les valeurs des constantes de stem:[h], stem:[e], stem:[k] et stem:[ii(N)_"A"]
au niveau d’incertitude requis,

* les laboratoires nationaux de métrologie à continuer activement à examiner et discuter de ces
résultats au sein des Comités consultatifs,

* le CIPM à continuer à planifier la mise en oeuvre de la Résolution 1 adoptée par la CGPM à
sa 24^e^ réunion (2011), en collaboration étroite avec les Comités consultatifs et le CCU,

* le CIPM et ses Comités consultatifs, les laboratoires nationaux de métrologie, le BIPM, ainsi
que d’autres organisations telles que l’Organisation internationale de métrologie légale
(OIML), à poursuivre leurs efforts afin d’effectuer les travaux nécessaires pour que la CGPM
adopte, lors de sa 26^e^ réunion, une résolution permettant de remplacer le SI actuel par le SI
révisé, sous réserve que les données obtenues, tant concernant leur nombre, les incertitudes
associées ou leur niveau de cohérence, soient jugées satisfaisantes.
____

