== CIPM, 2015

=== Mises à jour de la liste des fréquences étalons (PV, 83, 54)

NOTE: Des mises à jour sont disponibles sur le site
internet du BIPM.

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des « valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates afin de mettre à jour cette liste,

*recommande*

que les fréquences des transitions suivantes soient mises à jour dans la liste des fréquences
étalons recommandées:

* la transition optique non perturbée 6s^2^ ^1^S0 – 6s6p ^3^P~0~ de l’atome neutre de ^199^Hg,
à la fréquence de f199Hg = 1 128 575 290 808 154,8 Hz avec une incertitude-type relative
estimée de stem:[6 xx 10^{-16}];

* la transition optique non perturbée 6s ^2^S~1/2~ – 4f^13^ 6s2 ^2^F~7/2~ de l’ion de ^17^1Yb^+^, à la fréquence
de stem:[f_{171Yb+}] (octupôle) = 642 121 496 772 645,0 Hz avec une incertitude-type relative estimée
de stem:[6 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition optique non perturbée 6s ^2^S~1/2~ (stem:[F = 0], stem:[m_F = 0]) – 5d ^2^D~3/2~ (_F_ = 2, _m~F~_ = 0) de l’ion
de 171Yb+, à la fréquence de f171Yb+ (quadripôle) = 688 358 979 309 308,3 Hz avec une
incertitude-type relative estimée de stem:[6 xx 10^{-16}] (cette radiation a déjà été approuvée par le
CIPM comme représentation secondaire de la seconde);

* la transition optique non perturbée 5s ^2^S~1/2~ – 4d ^2^D~5/2~ de l’ion de ^88^Sr^+^, à la fréquence de
f88Sr+ = 444 779 044 095 486,6 Hz avec une incertitude-type relative estimée de stem:[1,6 xx 10^{-15}]
(cette radiation a déjà été approuvée par le CIPM comme représentation secondaire de la
seconde);

* la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f_{40Ca+} = 411 042 129 776 398,4] stem:["Hz"] avec une incertitude-type relative estimée de stem:[1,2 xx 10^{-14}];
* la transition optique non perturbée 1S – 2S de l’atome neutre de ^1^H, à la fréquence de f~1H~ = 1
233 030 706 593 514 Hz avec une incertitude-type relative estimée de stem:[9 xx 10^{-15}];

Remarque: cette fréquence correspond à la moitié de l’écart en énergie entre les états 1S et
2S;

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s5p ^3^P~0~ de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f_{87Sr} = 429 228 004 229 873,2] stem:["Hz"] avec une incertitude-type relative estimée
de stem:[5 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s6p ^3^P~0~ de l’atome neutre de ^171^Yb,
à la fréquence de stem:[f_{171"Yb"} = 518295836590864,0] stem:["Hz"] avec une incertitude-type relative
estimée de stem:[2 xx 10^{-15}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition hyperfine non perturbée de l’état fondamental de l’atome de 87Rb,
à la fréquence de stem:[f_{87Rb} = 6 834 682 610,904 310] stem:["Hz"] avec une incertitude-type relative estimée
de stem:[7 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

*recommande* par ailleurs

que les fréquences des transitions suivantes soient incluses dans la liste des fréquences étalons
recommandées:

* Molécule absorbante de ^127^I~2~, composante a1 du spectre d’absorption saturée,
transition R(36) 32-0.
+
--
Les valeurs:: stem:[f_{a1} = 564 074 632,42] stem:["MHz"] +
stem:[lambda_{a1} = 531 476 582,65] stem:["fm"]
--

avec une incertitude-type relative estimée de stem:[1 xx 10^{-10}] s’appliquent à la radiation d’un laser à
diode à rétroaction répartie doublé en fréquence, asservi à l’aide d’une cellule d’iode située à
l’extérieur du laser.

* Atome absorbant de ^87^Rb, transition 5S~1/2~ - 5P~3/2~, croisement de niveaux entre les
composantes hyperfines d et f de l’absorption saturée à 780 nm (transition D2).
+
--
Les valeurs:: stem:[f_{"croisement d/f"} = 384 227 981,9] stem:["MHz"] +
stem:[lambda_{"croisement d/f"} = 780 246 291,6] stem:["fm"]
--

avec une incertitude-type relative estimée de stem:[5 xx 10^{-10}] s’appliquent à la radiation d’un laser
accordable à diode et à cavité externe, asservi sur la résonance de croisement de niveaux d/f
dans une cellule de rubidium située à l’extérieur du laser.

Remarque: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.