[[cipm2015]]
== CIPM, 2015

[[cipm2015r2]]
=== Mises à jour de la liste des fréquences étalons (PV, 83, 54)

NOTE: Des mises à jour sont disponibles sur le site
internet du BIPM.

[[cipm2015r2r2]]
==== Recommandation 2
____

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des « valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde » a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates afin de mettre à jour cette liste,

*recommande*

que les fréquences des transitions suivantes soient mises à jour dans la liste des fréquences
étalons recommandées:

* la transition optique non perturbée stem:[6"s"^2 text()^1"S"_0 – 6"s"6"p" text()^3"P"_0] de l’atome neutre de ^199^Hg,
à la fréquence de stem:[f_(199"Hg") = 1128575290808154.8 " Hz"] avec une incertitude-type relative
estimée de stem:[6 xx 10^{-16}];

* la transition optique non perturbée stem:[6"s" text()^2"S"_(1text(/)2) – 4"f"^(13) 6"s"^2 text()^2"F"_(7text(/)2)] de l’ion de ^171^Yb^\+^, à la fréquence
de stem:[f_(171"Yb+") "(octupole)" = 642121496772645.0 " Hz"] avec une incertitude-type relative estimée
de stem:[6 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition optique non perturbée stem:[6"s" text()^2"S"_(1text(/)2) (F = 0, m_F = 0) – 5"d" text()^2"D"_(3text(/)2) (F = 2, m_F = 0)] de l’ion
de ^171^Yb^\+^, à la fréquence de stem:[f_(171"Yb+") "(quadrupole)" = 688358979309308.3 " Hz"] avec une
incertitude-type relative estimée de stem:[6 xx 10^{-16}] (cette radiation a déjà été approuvée par le
CIPM comme représentation secondaire de la seconde);

* la transition optique non perturbée stem:[5"s" text()^2"S"_(1text(/)2) – 4"d" text()^2"D"_(5text(/)2)] de l’ion de ^88^Sr^\+^, à la fréquence de
stem:[f_(88"Sr+") = 444779044095486.6 " Hz"] avec une incertitude-type relative estimée de stem:[1,6 xx 10^{-15}]
(cette radiation a déjà été approuvée par le CIPM comme représentation secondaire de la
seconde);

* la transition optique non perturbée stem:[4"s" text()^2"S"_(1text(/)2) – 3"d" text()^2"D"_(5text(/)2)] de l’ion de ^40^Ca^\+^, à la fréquence de
stem:[f_(40"Ca+") = 411042129776398.4 " Hz"] avec une incertitude-type relative estimée de stem:[1,2 xx 10^{-14}];
* la transition optique non perturbée stem:[1"S" - 2"S"] de l’atome neutre de ^1^H, à la fréquence de stem:[f_(1"H") = 1233030706593514 " Hz"] avec une incertitude-type relative estimée de stem:[9 xx 10^{-15}];
+
--
NOTE: cette fréquence correspond à la moitié de l’écart en énergie entre les états stem:[1"S"] et stem:[2"S"];
--

* la transition optique non perturbée stem:[5"s"^2 text()^1"S"_0 – 5"s"5"p" text()^3"P"_0] de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f_(87"Sr") = 429228004229873.2 " Hz"] avec une incertitude-type relative estimée
de stem:[5 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition optique non perturbée stem:[6"s"^2 text()^1"S"_0 – 6"s"6"p" text()^3"P"_0] de l’atome neutre de ^171^Yb,
à la fréquence de stem:[f_(171"Yb") = 518295836590864.0 " Hz"] avec une incertitude-type relative
estimée de stem:[2 xx 10^{-15}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

* la transition hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb,
à la fréquence de stem:[f_(87"Rb") = 6834682610.904310 " Hz"] avec une incertitude-type relative estimée
de stem:[7 xx 10^{-16}] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde);

*recommande* par ailleurs

que les fréquences des transitions suivantes soient incluses dans la liste des fréquences étalons
recommandées:

* Molécule absorbante de ^127^I~2~, composante stem:["a"_1] du spectre d’absorption saturée,
transition R(36) 32-0.
+
--
[align=left]
Les valeurs:: stem:[f_("a"1) = 564074632.42 " MHz"] +
stem:[lambda_("a"1) = 531476582.65 " fm"]

avec une incertitude-type relative estimée de stem:[1 xx 10^{-10}] s’appliquent à la radiation d’un laser à
diode à rétroaction répartie doublé en fréquence, asservi à l’aide d’une cellule d’iode située à
l’extérieur du laser.
--

* Atome absorbant de ^87^Rb, transition 5S~1/2~ - 5P~3/2~, croisement de niveaux entre les
composantes hyperfines stem:["d"] et stem:["f"] de l’absorption saturée à 780 nm (transition D2).
+
--
[align=left]
Les valeurs:: stem:[f_{"croisement d/f"} = 384227981.9 " MHz"] +
stem:[lambda_{"croisement d/f"} = 780246291.6 " fm"]

avec une incertitude-type relative estimée de stem:[5 xx 10^{-10}] s’appliquent à la radiation d’un laser
accordable à diode et à cavité externe, asservi sur la résonance de croisement de niveaux stem:["d/f"]
dans une cellule de rubidium située à l’extérieur du laser.

NOTE: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que, rétrospectivement, cela ne s’avère pas exact.
--
____

