[[cgpm26th2018]]
== 26th CGPM, 2018

[[cgpm26th2018r1]]
=== Sur la révision du Système international d’unités (SI) (CR, sous presse et _Metrologia_, 2019, 56, 022001)

[[cgpm26th2018r1r1]]
==== Résolution 1
____

La Conférence générale des poids et mesures (CGPM), à sa 26^e^ réunion,
index-range:kilogramme_prototype-3[(((kilogramme,prototype international)))]

*considérant*

* qu’il est essentiel de disposer d’un Système international d’unités (SI) uniforme et accessible
dans le monde entier, pour le commerce international, l’industrie de haute technologie, la santé
humaine et la sécurité, la protection de l’environnement, les études sur l’évolution du climat,
ainsi que la science fondamentale qui étaye tous ces domaines,

* que les unités du SI doivent être stables sur le long terme, auto cohérentes et réalisables
dans la pratique, en étant fondées sur la description théorique actuelle de la nature, au plus
haut niveau,

* qu’une révision du SI visant à satisfaire ces exigences a été proposée dans la Résolution 1
adoptée à l’unanimité par la CGPM à sa 24^e^ réunion (2011), qui expose en détail une
nouvelle façon de définir le SI à partir d’un ensemble de sept constantes, choisies parmi les
constantes fondamentales(((constante, fondamentale (de la physique)))) de la physique et d’autres constantes de la nature, à partir
desquelles les définitions des sept unités de base sont déduites,

* que les conditions requises par la CGPM à sa 24^e^ réunion (2011), confirmées à sa
25^e^ réunion (2014), pour procéder à l’adoption d’une telle révision du SI sont désormais
remplies,

*décide*
(((unité(s),de base)))

qu’à compter du 20 mai 2019, le Système international d’unités, le SI, est le système d’unités
selon lequel:

* la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium((("atome de césium, niveaux hyperfins")))
133 non perturbé, stem:[Delta ii(nu)_{"Cs"}], est égale à stem:[9192631770 "unitsml(Hz)"],
* la ((vitesse de la lumière dans le vide)), stem:[c], est égale à stem:[299792458 "unitsml(m/s)"],
* la constante de Planck(((constante, de Planck))), stem:[h], est égale à stem:[6.62607015 xx 10^{-34} "unitsml(J/s)"],
* la charge élémentaire, stem:[e], est égale à stem:[1.602176634 xx 10^(-19) "unitsml(C)"],
* la constante de Boltzmann(((constante, de Boltzmann))), stem:[k], est égale à stem:[1.380649 xx 10^{-23} "unitsml(J/K)"],
* la constante d’Avogadro(((constante, d'Avogadro))), stem:[ii(N)_"A"], est égale à stem:[6.02214076 xx 10^(23) "unitsml(mol^(-1))"],
* l’efficacité lumineuse d’un ((rayonnement monochromatique)) de fréquence
stem:[540 xx 10^(12) "unitsml(Hz)"], stem:[ii(K)_{"cd"}], est égale à stem:[683 "unitsml(lm/W)"],
(((hertz (stem:["unitsml(Hz)"]))))(((joule (stem:["unitsml(J)"]))))(((kelvin (stem:["unitsml(K)"]))))(((lumen (stem:["unitsml(lm)"]))))(((watt (W))))
index-range:kilogramme-3[(((kilogramme)))]

où les unités hertz, joule, coulomb(((coulomb (stem:["unitsml(C)"])))), lumen et watt, qui ont respectivement pour symbole stem:["unitsml(Hz)", "unitsml(J)", "unitsml(C)", "unitsml(lm)"] et stem:["unitsml(W)"], sont reliées aux unités seconde, mètre, kilogramme, ampère(((ampère (stem:["unitsml(A)"])))), kelvin, mole et candela(((candela (stem:["unitsml(cd)"])))),
qui ont respectivement pour symbole stem:["unitsml(s)", "unitsml(m)", "unitsml(kg)", "unitsml(A)", "unitsml(K)", "unitsml(mol)"] et stem:["unitsml(cd)"], selon les relations, stem:["unitsml(J)" = "unitsml(kg*m^2*s^(-2))"],
stem:["unitsml(C)" = "unitsml(A)""unitsml(s)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], et stem:["unitsml(W)" = "unitsml(kg*m^2*s^(-3))"],

*prend acte* des conséquences de la révision du SI concernant les unités de base du SI,
énoncées dans la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011), et les confirme
dans les annexes de la présente résolution, qui ont même force que la résolution elle-même,

*invite* le Comité international des poids et mesures (CIPM) à publier une nouvelle édition de la
_Brochure sur le SI_, «&nbsp;Le Système international d’unités&nbsp;», contenant une description complète du
SI révisé.
____
