== 26th CGPM, 2018

[[cgpm26th2018r1]]
=== Sur la révision du Système international d’unités (SI) (CR, sous presse et _Metrologia_, 2019, 56, 022001)

____
[align=center]
*Résolution 1*

La Conférence générale des poids et mesures (CGPM), à sa 26^e^ réunion,

*considérant*

* qu’il est essentiel de disposer d’un Système international d’unités (SI) uniforme et accessible
dans le monde entier, pour le commerce international, l’industrie de haute technologie, la santé
humaine et la sécurité, la protection de l’environnement, les études sur l’évolution du climat,
ainsi que la science fondamentale qui étaye tous ces domaines,

* que les unités du SI doivent être stables sur le long terme, auto cohérentes et réalisables
dans la pratique, en étant fondées sur la description théorique actuelle de la nature, au plus
haut niveau,

* qu’une révision du SI visant à satisfaire ces exigences a été proposée dans la Résolution 1
adoptée à l’unanimité par la CGPM à sa 24^e^ réunion (2011), qui expose en détail une
nouvelle façon de définir le SI à partir d’un ensemble de sept constantes, choisies parmi les
constantes fondamentales de la physique et d’autres constantes de la nature, à partir
desquelles les définitions des sept unités de base sont déduites,

* que les conditions requises par la CGPM à sa 24^e^ réunion (2011), confirmées à sa
25^e^ réunion (2014), pour procéder à l’adoption d’une telle révision du SI sont désormais
remplies,

*décide*

qu’à compter du 20 mai 2019, le Système international d’unités, le SI, est le système d’unités
selon lequel:

* la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium
133 non perturbé, stem:[Delta nu_{"Cs"}], est égale à stem:[9 " "192 " "631 " "770 " Hz"],
* la vitesse de la lumière dans le vide, stem:[c], est égale à stem:[299 " "792 " "458 " m/s"],
* la constante de Planck, stem:[h], est égale à stem:[6,626 " "070 " "15 xx 10^{-34} " J s"],
* la charge élémentaire, stem:[e], est égale à stem:[1,602 " "176 " "634 xx 10^{-19} " C"],
* la constante de Boltzmann, stem:[k], est égale à stem:[1,380 " " 649 xx 10^{-23} " J/K"],
* la constante d’Avogadro, stem:[N_"A"], est égale à stem:[6.022 " "140 " "76 times 10^(23) " mol"^(-1)],
* l’efficacité lumineuse d’un rayonnement monochromatique de fréquence
stem:[540 xx 10^(12) " Hz"], stem:[K_{"cd"}], est égale à stem:[683 " lm/W"],

où les unités hertz, joule, coulomb, lumen et watt, qui ont respectivement pour symbole stem:["Hz", " J", " C", " lm"] et stem:["W"], sont reliées aux unités seconde, mètre, kilogramme, ampère, kelvin, mole et candela,
qui ont respectivement pour symbole stem:["s", " m", " kg", " A", " K", " mol"] et stem:["cd"], selon les relations, stem:["J" = "kg m"^2 " s"^{-2}],
stem:["C" = "A s"], stem:["lm" = "cd m"^2 " m"^{-2} = "cd sr"], et stem:["W" = "kg m"^2 " s"^{-3}],

*prend acte* des conséquences de la révision du SI concernant les unités de base du SI,
énoncées dans la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011), et les confirme
dans les annexes de la présente résolution, qui ont même force que la résolution elle-même,

*invite* le Comité international des poids et mesures (CIPM) à publier une nouvelle édition de la
Brochure sur le SI, « Le Système international d’unités », contenant une description complète du
SI révisé.
____