
[appendix]
== Décisions de la Conférence générale des poids et mesures et du Comité international des poids et mesures

Cette annexe regroupe les décisions de la Conférence générale des poids et mesures
(CGPM) et du Comité international des poids et mesures (CIPM) qui concernent
directement les définitions des unités SI, les préfixes à utiliser avec le SI, ainsi que les
conventions relatives à l’écriture des symboles d’unités et des nombres. Il ne s’agit pas
d’une liste exhaustive des décisions de la CGPM et du CIPM. Pour consulter toutes ces
décisions, il faut se référer aux volumes successifs des _Comptes rendus_ de la Conférence
générale des poids et mesures (CR) et des Procès-verbaux du Comité international des
poids et mesures (PV) et, pour les décisions récentes, à _Metrologia_.

Le SI n’est pas statique, il suit les progrès de la métrologie, aussi certaines décisions
ont-elles été abrogées ou modifiées{nbsp}; d’autres ont été précisées par des adjonctions.
Les décisions qui ont fait l’objet d’un changement sont identifiées par un astérisque (*) et
renvoient à une note qui fait référence à la décision qui officialise cette modification.

Le texte original des décisions figure dans une police différente (sans empattement) pour le
distinguer du texte principal. Les astérisques et notes ont été ajoutés par le BIPM pour
rendre le texte plus compréhensible. Ils ne font pas partie des décisions proprement dites.

Les décisions de la CGPM et du CIPM figurent dans cette annexe par ordre chronologique,
de 1889 à 2018, afin de préserver la continuité. Cependant, afin de pouvoir identifier
facilement les décisions concernant un domaine particulier, une table des matières par sujet
indique les réunions pendant lesquelles ces décisions ont été adoptées et donne les numéros
des pages où sont reproduites les publications originelles.


=== 1^re^ CGPM, 1889

==== Sanction des prototypes internationaux du mètre et du kilogramme (<<CR1889-1,page=34-38>>)

NOTE: La définition du mètre a
été abrogée en 1960 par la 11^e^ CGPM (Résolution 6, _voir_ p. 53).


La Conférence générale,

*considérant*

* le «{nbsp}Compte rendu du Président du Comité international{nbsp}» et le «{nbsp}Rapport du Comité
international des poids et mesures{nbsp}», d’où il résulte que, par les soins communs de la Section
française de la Commission internationale du Mètre, et du Comité international des poids et
mesures, les déterminations métrologiques fondamentales des prototypes internationaux et
nationaux du mètre et du kilogramme ont été exécutées dans toutes les conditions de garantie
et de précision que comporte l’état actuel de la science{nbsp};
* que les prototypes internationaux et nationaux du mètre et du kilogramme sont formés de
platine allié à 10 pour 100 d’iridium, à stem:[0.0001] près{nbsp};
* l’identité de longueur du Mètre et l’identité de la masse du Kilogramme internationaux avec la
longueur du Mètre et la masse du Kilogramme déposés aux Archives de France{nbsp};
* que les équations des Mètres nationaux, par rapport au Mètre international, sont renfermées
dans la limite de stem:[0.01] millimètre et que ces équations reposent sur une échelle thermométrique
à hydrogène qu’il est toujours possible de reproduire, à cause de la permanence de l’état de ce
corps, en se plaçant dans des conditions identiques{nbsp};
* que les équations des Kilogrammes nationaux, par rapport au Kilogramme international, sont
renfermées dans la limite de 1 milligramme{nbsp};
* que le Mètre et le Kilogramme internationaux et que les Mètres et les Kilogrammes nationaux
remplissent les conditions exigées par la Convention du Mètre,


*sanctionne*

. En ce qui concerne les prototypes internationaux{nbsp}:
.. Le Prototype du mètre choisi par le Comité international. Ce prototype représentera
désormais, à la température de la glace fondante, l’unité métrique de longueur.
.. Le Prototype du kilogramme adopté par le Comité international. Ce prototype sera considéré
désormais comme unité de masse.
.. L’échelle thermométrique centigrade à hydrogène par rapport à laquelle les équations des
Mètres prototypes ont été établies.

. En ce qui concerne les prototypes nationaux{nbsp}:

&#x200c;. . .



=== 3^e^ CGPM, 1901

==== Déclaration concernant la définition du litre (<<CR1901,page=38-39>>)

NOTE: Définition abrogée en 1964 par la 12^e^ CGPM (Résolution 6, _voir_ p. 57).


&#x200c;. . .

*La Conférence déclare{nbsp}:*

. L’unité de volume, pour les déterminations de haute précision, est le volume occupé par la
masse de 1 kilogramme d’eau pure, à son maximum de densité et sous la pression
atmosphérique normale{nbsp}; ce volume est dénommé «{nbsp}litre{nbsp}».

. . . .


==== Déclaration relative à l’unité de masse et à la définition du poids{nbsp}; valeur conventionnelle de stem:[g_{"n"}] (<<CR1901-2,page=70>>)

*Vu* la décision du Comité international des poids et mesures du 15 octobre 1887,
par laquelle le kilogramme a été défini comme unité de masse{nbsp};

*Vu* la décision contenue dans la formule de sanction des prototypes du Système métrique,
acceptée à l’unanimité par la Conférence générale des poids et mesures dans sa réunion du 26
septembre 1889{nbsp};

*Considérant* la nécessité de faire cesser l’ambiguïté qui existe encore dans l’usage courant sur
la signification du terme poids, employé tantôt dans le sens du terme _masse_, tantôt dans le sens
du terme _effort mécanique_{nbsp};


*La Conférence déclare{nbsp}:*

. Le kilogramme est l’unité de masse{nbsp}; il est égal à la masse du prototype international du
kilogramme{nbsp};
+
NOTE: Définition abrogée en 2018 par la CGPM
à sa 26^e^ réunion (Résolution 1, _voir_ p.92).

. Le terme poids désigne une grandeur de la même nature qu’une force{nbsp}; le poids d’un corps
est le produit de la masse de ce corps par l’accélération de la pesanteur{nbsp};
en particulier, le poids normal d’un corps est le produit de la masse de ce corps par
l’accélération normale de la pesanteur{nbsp};

. Le nombre adopté dans le Service international des Poids et Mesures pour la valeur de
l’accélération normale de la pesanteur est stem:[980.665] stem:["unitsml(cm//s^2)"], nombre sanctionné déjà par
quelques législations.
+
NOTE: Cette valeur de gn est la valeur conventionnelle de
référence pour le calcul de l’unité kilogramme-force
maintenant abolie.


=== 7^e^ CGPM, 1927

==== Définition du mètre par le Prototype international (<<CR1927-1,page=49>>)

NOTE: Définition abrogée en 1960 par la CGPM à sa
11^e^ réunion (Résolution 6, _voir_ p. 53).

L’unité de longueur est le mètre, défini par la distance, à stem:[0 "unitsml(deg)"], des axes des deux traits médians
tracés sur la barre de platine iridié déposée au Bureau international des poids et mesures, et
déclarée Prototype du mètre par la Première Conférence générale des poids et mesures, cette
règle étant soumise à la pression atmosphérique normale et supportée par deux rouleaux d’au
moins un centimètre de diamètre, situés symétriquement dans un même plan horizontal et à la
distance de stem:[571 "unitsml(mm)"] l’un de l’autre.


=== CIPM, 1946

==== Définition des unités photométriques (<<PV20, page=119-122>>)

NOTE: Les deux définitions contenues dans cette
Résolution furent ratifiées par la CGPM à sa
9^e^ réunion en 1948, qui a en outre approuvé le nom de
candela(((candela (stem:["unitsml(cd)"])))) donné à la «{nbsp}bougie nouvelle{nbsp}» (<<CR54>>). Pour le
lumen, le qualificatif «{nbsp}nouveau{nbsp}» a été
abandonné par la suite.

[align=center]
*Résolution*

&#x200c;. . .
4. Les unités photométriques peuvent être définies comme suit{nbsp}:
+
--
*Bougie nouvelle* (unité d’intensité lumineuse). -- La grandeur de la bougie nouvelle est telle
que la brillance du radiateur intégral à la température de solidification du platine soit de
60 bougies nouvelles par centimètre carré.

*Lumen nouveau* (unité de flux lumineux). -- Le lumen nouveau est le flux lumineux émis dans
l’angle solide unité (stéradian) par une source ponctuelle uniforme ayant une intensité
lumineuse de 1 bougie nouvelle.
--

5. . . .


NOTE: La définition de la candela(((candela (stem:["unitsml(cd)"])))) a été modifiée par la 13^e^ CGPM en 1967 (Résolution 5, _voir_ p. 59).


==== Définitions des unités électriques (<<PV20, page=132-133>>)

[align=center]
*Résolution 2*


&#x200c;. . .

. Définitions des unités mécaniques utilisées dans les définitions des unités électriques{nbsp}:
+
--
*Unité de force.* -- L’unité de force [dans le système MKS (mètre, kilogramme, seconde)] est la
force qui communique à une masse de 1 kilogramme l’accélération de 1 mètre par seconde,
par seconde.

*Joule* (unité d’énergie ou de travail) -- Le joule est le travail effectué lorsque le point
d’application de 1 unité MKS de force [newton] se déplace d’une distance égale à 1 mètre
dans la direction de la force.

*Watt* (unité de puissance) -- Le watt est la puissance qui donne lieu à une production d’énergie
égale à 1 joule par seconde.
--

. Définitions des unités électriques. Le Comité [international] admet les propositions
suivantes définissant la grandeur théorique des unités électriques{nbsp}:
+
--
*Ampère*(((ampère (stem:["unitsml(A)"])))) (unité d’intensité de courant électrique) -- L’ampère(((ampère (stem:["unitsml(A)"])))) est l’intensité d’un courant
constant qui, maintenu dans deux conducteurs parallèles, rectilignes, de longueur infinie, de
section circulaire négligeable et placés à une distance de 1 mètre l’un de l’autre dans le vide,
produirait entre ces conducteurs une force égale à stem:[2 xx 10^(-7)] unité MKS de force [newton] par
mètre de longueur.

NOTE: Définition de l’ampère(((ampère (stem:["unitsml(A)"])))) abrogée en 2018 par la
CGPM à sa 26^e^ réunion (Résolution 1, _voir_ p.92).
(((volt (stem:["unitsml(V)"]))))

*Volt* (unité de différence de potentiel et de force électromotrice) -- Le volt est la différence de
potentiel électrique qui existe entre deux points d’un fil conducteur transportant un courant
constant de 1 ampère(((ampère (stem:["unitsml(A)"])))), lorsque la puissance dissipée entre ces points est égale à 1 watt.

*Ohm* (unité de résistance électrique) -- L’ohm est la résistance électrique qui existe entre deux
points d’un conducteur lorsqu’une différence de potentiel constante de 1 volt, appliquée
entre ces deux points, produit, dans ce conducteur, un courant de 1 ampère(((ampère (stem:["unitsml(A)"])))), ce conducteur
n’étant le siège d’aucune force électromotrice.

*Coulomb* (unité de quantité d’électricité) -- Le coulomb est la quantité d’électricité transportée
en 1 seconde par un courant de 1 ampère(((ampère (stem:["unitsml(A)"])))).

*Farad* (unité de capacité électrique) -- Le farad est la capacité d’un condensateur électrique
entre les armatures duquel apparaît une différence de potentiel électrique de 1 volt, lorsqu’il
est chargé d’une quantité d’électricité égale à 1 coulomb.

*Henry* (unité d’inductance électrique) -- Le henry est l’inductance électrique d’un circuit fermé
dans lequel une force électromotrice de 1 volt est produite lorsque le courant électrique qui
parcourt le circuit varie uniformément à raison de 1 ampère par seconde.
(((weber (stem:["unitsml(Wb)"]))))

*Weber* (unité de flux magnétique) -- Le weber est le flux magnétique qui, traversant un circuit
d’une seule spire, y produirait une force électromotrice de 1 volt, si on l’amenait à zéro en
1 seconde par décroissance uniforme.
--


=== 9^e^ CGPM, 1948

==== Point triple de l’eau{nbsp}; échelle thermodynamique à un seul point fixe{nbsp}; unité de quantité de chaleur (joule) (<<CR1948-2,page=55>> et <<CR1948-5,page=63>>)

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion en 2018 (Résolution 1,
_voir_ p.92).

[align=center]
*Résolution 3*

. En l’état actuel de la technique, le point triple de l’eau est susceptible de constituer un repère
thermométrique avec une précision plus élevée que le point de fusion de la glace.
+
--
En conséquence, le Comité consultatif [de thermométrie et calorimétrie] estime que le zéro
de l’échelle thermodynamique centésimale doit être défini comme étant la température
inférieure de stem:[0.0100] degré à celle du point triple de l’eau pure.
--

. Le Comité consultatif [de thermométrie et calorimétrie] admet le principe d’une échelle
thermodynamique absolue ne comportant qu’un seul point fixe fondamental, constitué
actuellement par le point triple de l’eau pure, dont la température absolue sera fixée
ultérieurement.
+
--
L’introduction de cette nouvelle échelle n’affecte en rien l’usage de l’Échelle internationale,
qui reste l’échelle pratique recommandée.
--

. L’unité de quantité de chaleur est le joule.
+
--
NOTE: Il est demandé que les résultats d’expériences calorimétriques soient autant que possible
exprimés en joules. Si les expériences ont été faites par comparaison avec un échauffement
d’eau (et que, pour une raison quelconque, on ne puisse éviter l’usage de la calorie), tous les
renseignements nécessaires pour la conversion en joules doivent être fournis. Il est laissé aux
soins du Comité international, après avis du Comité consultatif de thermométrie et calorimétrie,
d’établir une table qui présentera les valeurs les plus précises que l’on peut tirer des
expériences faites sur la chaleur spécifique de l’eau, en joules par degré.

Une table, établie conformément à cette demande, a été approuvée et publiée par le Comité
international en 1950 (<<PV22, page=92>>).
--

==== Adoption de «{nbsp}degré Celsius{nbsp}» [CIPM, 1948 (<<PV21, page=88>>) et 9^e^ CGPM, 1948 (<<CR1948-6,page=64>>)]

Entre les trois termes («{nbsp}degré centigrade{nbsp}», «{nbsp}degré centésimal{nbsp}», «{nbsp}degré Celsius{nbsp}») proposés
pour désigner le degré de température, le Comité international a choisi «{nbsp}degré Celsius{nbsp}» (<<PV21, page=88>>).

Ce terme est également adopté par la 9^e^ Conférence générale (<<CR1948-6,page=64>>).


==== Proposition d’établissement d’un système pratique d’unités de mesure (<<CR1948-6,page=64>>)

[align=center]
*Résolution 6*

La Conférence générale,

*considérant*

* que le Comité international des poids et mesures a été saisi d’une demande de l’Union
internationale de physique le sollicitant d’adopter pour les relations internationales un système
pratique international d’unités, recommandant le système MKS et une unité électrique du
système pratique absolu, tout en ne recommandant pas que le système CGS soit abandonné
par les physiciens{nbsp};

* qu’elle-même a reçu du Gouvernement français une demande analogue, accompagnée d’un
projet destiné à servir de base de discussion pour l’établissement d’une réglementation
complète des unités de mesure{nbsp};

*charge* le Comité international{nbsp}:

* d’ouvrir à cet effet une enquête officielle sur l’opinion des milieux scientifiques, techniques et
pédagogiques de tous les pays (en offrant effectivement comme base le document français)
et de la pousser activement{nbsp};

* de centraliser les réponses{nbsp};

* et d’émettre des recommandations concernant l’établissement d’un même système pratique
d’unités de mesure, susceptible d’être adopté dans tous les pays signataires de la Convention
du Mètre.



==== Écriture des symboles d’unités et des nombres (<<CR1948-7,page=70>>)

NOTE: La Conférence générale a abrogé un certain nombre
de décisions concernant les unités et la terminologie,
en particulier celles relatives au micron, au
degré absolu et aux noms «{nbsp}degré{nbsp}» et «{nbsp}deg{nbsp}»,
13^e^ CGPM, 1967/68 (Résolutions 7 et 3,
_voir_ pp. 60 et 58, respectivement), ainsi
qu’au litre, 16^e^ CGPM, 1979 (Résolution 6, _voir_ p. 64).

[align=center]
*Résolution 7*

*Principes*

Les symboles des unités sont exprimés en caractères romains, en général minuscules{nbsp};
toutefois, si les symboles sont dérivés de noms propres, les caractères romains majuscules sont
utilisés. Ces symboles ne sont pas suivis d’un point.

Dans les nombres, la virgule (usage français) ou le point (usage britannique) sont utilisés
seulement pour séparer la partie entière des nombres de leur partie décimale.
Pour faciliter la lecture, les nombres peuvent être partagés en tranches de trois chiffres{nbsp}:
ces tranches ne sont jamais séparées par des points, ni par des virgules.


[cols="1,^,1,^",options="unnumbered"]
|===
| Unités | Symboles | Unités | Symboles

a| &#x2022; mètre | stem:["unitsml(m)"] | ampère(((ampère (stem:["unitsml(A)"])))) | stem:["unitsml(A)"]
a| &#x2022; mètre carré | stem:["unitsml(m^2)"] | volt(((volt (stem:["unitsml(V)"])))) | stem:["unitsml(V)"]
a| &#x2022; mètre cube | stem:["unitsml(m^3)"] | watt | stem:["unitsml(W)"]
a| &#x2022; micron | stem:[mu] | ohm | stem:["unitsml(Ohm)"]
a| &#x2022; litre | stem:["unitsml(l)"] | coulomb | stem:["unitsml(C)"]
a| &#x2022; gramme | stem:["unitsml(g)"] | farad | stem:["unitsml(F)"]
a| &#x2022; tonne | stem:["unitsml(t)"] | henry | stem:["unitsml(H)"]
| seconde | stem:["unitsml(s)"] | hertz | stem:["unitsml(Hz)"]
| erg | stem:["unitsml(erg)"] | poise | stem:["unitsml(P)"]
| dyne | stem:["unitsml(dyn)"] | newton | stem:["unitsml(N)"]
| degré Celsius | stem:["unitsml(degC)"] a| &#x2022; candela(((candela (stem:["unitsml(cd)"])))) (bougie nouvelle) | stem:["unitsml(cd)"]
a| &#x2022; degré absolu | stem:["unitsml(degK)"] | lux | stem:["unitsml(lx)"]
| calorie | stem:["unitsml(cal)"] | lumen | stem:["unitsml(lm)"]
| bar | stem:["unitsml(bar)"] | stilb | stem:["unitsml(sb)"]
| heure | stem:["unitsml(h)"] | |
|===


*Remarques*

. Les symboles dont les unités sont précédées d’un point sont ceux qui avaient déjà été
antérieurement adoptés par une décision du Comité international.

. L’unité de volume stère, employée dans le mesurage des bois, aura pour symbole «{nbsp}stem:["unitsml(st)"]{nbsp}» et
non plus «{nbsp}s{nbsp}», qui lui avait été précédemment affecté par le Comité international.

. S’il s’agit, non d’une température, mais d’un intervalle ou d’une différence de température,
le mot «{nbsp}degré{nbsp}» doit être écrit en toutes lettres ou par l’abréviation «{nbsp}deg{nbsp}».


=== 10^e^ CGPM, 1954

==== Définition de l’échelle thermodynamique de température (<<CR1954-3,page=79>>)

[NOTE]
====
La 13^e^ CGPM en 1967/68 (Résolution 4,
_voir_ p. 59) a explicitement défini le kelvin.

Le kelvin a été redéfini par
la CGPM à sa 26^e^ réunion en 2018 (Résolution 1,
_voir_ p.92).
====

[align=center]
*Résolution 3*

La Dixième Conférence générale des poids et mesures décide de définir l’échelle
thermodynamique de température au moyen du point triple de l’eau comme point fixe
fondamental, en lui attribuant la température stem:[273.16] degrés Kelvin, exactement.


==== Définition de l’atmosphère normale (<<CR1954-4,page=79>>)

[align=center]
*Résolution 4*

La Dixième Conférence générale des poids et mesures, ayant constaté que la définition de
l’atmosphère normale donnée par la Neuvième Conférence générale des poids et mesures dans
la définition de l’Échelle internationale de température a laissé penser à quelques physiciens
que la validité de cette définition de l’atmosphère normale était limitée aux besoins de la
thermométrie de précision,

*déclare* qu’elle adopte, pour tous les usages, la définition{nbsp}:

1 atmosphère normale = 1013250 dynes par centimètre carré,

c’est-à-dire{nbsp}: 101325 newtons par mètre carré.


==== Système pratique d’unités de mesure (<<CR1954-6,page=80>>)

NOTE: Le nom de l’unité de température thermodynamique
a été changé en «{nbsp}kelvin{nbsp}» en 1967
par la 13^e^ CGPM (Résolution 3, _voir_ p.58).

[align=center]
*Résolution 6*

La Dixième Conférence générale des poids et mesures, en exécution du voeu exprimé dans sa
Résolution 6 par la Neuvième Conférence générale concernant l’établissement d’un système
pratique d’unités de mesure pour les relations internationales,

*décide* d’adopter comme unités de base de ce système à établir, les unités suivantes{nbsp}:

[cols="2",options="unnumbered"]
|===
| longueur | mètre
| masse | kilogramme
| temps | seconde
| intensité de courant électrique | ampère(((ampère (stem:["unitsml(A)"]))))
| température thermodynamique | degré Kelvin
| intensité lumineuse | candela(((candela (stem:["unitsml(cd)"]))))
|===


=== CIPM, 1956

==== Définition de l’unité de temps (seconde) (<<PV25, page=77>>)

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM
(Résolution 1, _voir_ p. 58).

[align=center]
*Résolution 1*

En vertu des pouvoirs que lui a conférés la Dixième Conférence générale des poids et mesures
par sa Résolution 5, le Comité international des poids et mesures,

*considérant*

1. que la Neuvième Assemblée générale de l’Union astronomique internationale (Dublin, 1955)
a émis un avis favorable au rattachement de la seconde à l’année tropique,

2. que, selon les décisions de la Huitième Assemblée générale de l’Union astronomique
internationale (Rome, 1952), la seconde de temps des éphémérides (T.E.) est la fraction
+
--
stem:[12960276813//408986496 xx 10^(-9)] de l’année tropique pour 1900 janvier 0 à 12 h T.E.,
décide

«{nbsp}La seconde est la fraction stem:[1//31556925.9747] de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides.{nbsp}»
--

==== Système international d’unités (<<PV25, page=83>>)

[align=center]
*Résolution 3*

Le Comité international des poids et mesures,

*considérant*

* la mission dont l’a chargé la Neuvième Conférence générale des poids et mesures par sa
Résolution 6 concernant l’établissement d’un système pratique d’unités de mesure susceptible
d’être adopté par tous les pays signataires de la Convention du Mètre,
* l’ensemble des documents envoyés par les vingt et un pays qui ont répondu à l’enquête
prescrite par la Neuvième Conférence générale des poids et mesures,
* la Résolution 6 de la Dixième Conférence générale des poids et mesures fixant le choix des
unités de base du système à établir,

*recommande*

. que soit désigné comme «{nbsp}Système international d’unités{nbsp}» le système fondé sur les unités
de base adoptées par la Dixième Conférence générale, qui sont{nbsp}: +
[Suit la liste des six unités de base avec leur symbole, reproduite dans la Résolution 12
de la 11^e^ CGPM (1960)].
. que soient employées les unités de ce système énumérées au tableau suivant, sans
préjudice d’autres unités qu’on pourrait ajouter à l’avenir{nbsp}: +
[Suit le tableau des unités reproduit dans le paragraphe 4 de la Résolution 12 de la
11^e^ CGPM (1960)].


=== 11^e^ CGPM, 1960

==== Définition du mètre (<<CR1960-6,page=85>>)

NOTE: Définition abrogée en 1983 par la 17^e^ CGPM
(Résolution 1, _voir_ p. 66).


*Résolution 6*

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le Prototype international ne définit pas le mètre avec une précision suffisante pour les
besoins actuels de la métrologie,
* qu’il est d’autre part désirable d’adopter un étalon naturel et indestructible,

*décide*

. Le mètre est la longueur égale à stem:[1650763.73] longueurs d’onde dans le vide de la radiation
correspondant à la transition entre les niveaux 2p~10~ et 5d~5~ de l’atome de krypton 86.

. La définition du mètre en vigueur depuis 1889, fondée sur le Prototype international en
platine iridié, est abrogée.

. Le Prototype international du mètre sanctionné par la Première Conférence générale des
poids et mesures en 1889 sera conservé au Bureau international des poids et mesures dans
les mêmes conditions que celles qui ont été fixées en 1889.



==== Définition de l’unité de temps (seconde) (<<CR1960-9,page=86>>)

NOTE: Définition abrogée en 1967 par la 13^e^ CGPM
(Résolution 1, _voir_ p. 58).

*Résolution 9*

La Onzième Conférence générale des poids et mesures,

*considérant*

* le pouvoir donné par la Dixième Conférence générale des poids et mesures au Comité
international des poids et mesures de prendre une décision au sujet de la définition de l’unité
fondamentale de temps,
* la décision prise par le Comité international des poids et mesures dans sa session de 1956,

*ratifie* la définition suivante{nbsp}:

«{nbsp}La seconde est la fraction stem:[1//31556925.9747] de l’année tropique pour 1900 janvier 0 à
12 heures de temps des éphémérides.{nbsp}»


==== Système international d’unités (<<CR1960-12,page=87>>)

NOTE: La CGPM a ultérieurement abrogé
certaines de ces décisions et complété la liste des
préfixes SI{nbsp}: _voir_ notes ci-dessous.

*Résolution 12*

*considérant*

* la Résolution 6 de la Dixième Conférence générale des poids et mesures par laquelle elle a
adopté les six unités devant servir de base à l’établissement d’un système pratique de mesure
pour les relations internationales{nbsp}:
+
--
[cols="3",options="unnumbered"]
|===
| longueur | mètre | stem:["unitsml(m)"]
| masse | kilogramme | stem:["unitsml(kg)"]
| temps | seconde | stem:["unitsml(s)"]
| intensité de courant électrique | ampère(((ampère (stem:["unitsml(A)"])))) | stem:["unitsml(A)"]
| température thermodynamique | degré Kelvin | stem:["unitsml(degK)"]
| intensité lumineuse | candela(((candela (stem:["unitsml(cd)"])))) | stem:["unitsml(cd)"]
|===

NOTE: Le nom et symbole de l’unité de température
thermodynamique ont été modifiés par la 13^e^ CGPM
en 1967 (Résolution 3, _voir_ p. 58).
--

* la Résolution 3 adoptée par le Comité international des poids et mesures en 1956,
* les recommandations adoptées par le Comité international des poids et mesures en 1958
concernant l’abréviation du nom de ce système et les préfixes pour la formation des multiples et
sous-multiples des unités,

*décide*

. le système fondé sur les six unités de base ci-dessus est désigné sous le nom de «{nbsp}Système
international d’unités{nbsp}»{nbsp};
+
--
NOTE: Une septième unité de base, la mole, fut adoptée
par la 14^e^ CGPM en 1971 (Résolution 3, _voir_ p. 62).
--
. l’abréviation internationale du nom de ce Système est{nbsp}: SI{nbsp};

. les noms des multiples et sous-multiples des unités sont formés au moyen des préfixes
suivants{nbsp}:
+
--
[cols="1,^,^,1,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole | Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[1000000000000 = 10^12] | téra | T | stem:[0.1 = 10^(-1)] | déci | d
| stem:[1000000000 = 10^9] | giga | G | stem:[0.01 = 10^(-2)] | centi | c
| stem:[1000000 = 10^6] | méga | M | stem:[0.001 = 10^(-3)] | milli | m
| stem:[1000 = 10^3] | kilo | k | stem:[0.000001 = 10^(-6)] | micro | stem:[mu]
| stem:[100 = 10^2] | hecto | h | stem:[0.000000001 = 10^(-9)] | nano | n
| stem:[10 = 10^1] | déca | da | stem:[0.000000000001 = 10^(-12)] | pico | p
|===

NOTE: D’autres préfixes furent
adoptés par la 12^e^ CGPM en 1964 (Résolution 8,
_voir_ p. 57), par la 15^e^ CGPM en 1975
(Résolution 10, _voir_ p. 63)
et par la 19^e^ CGPM en 1991 (Résolution 4,
_voir_ p. 70).
--

. sont employées dans ce Système les unités ci-dessous, sans préjudice d’autres unités qu’on
pourrait ajouter à l’avenir

[cols="3",options="unnumbered"]
|===
3+h| _Unités supplémentaires_

| angle | radian | stem:["unitsml(rad)"]
| angle solide | stéradian | stem:["unitsml(sr)"]
|===

NOTE: La 20^e^ CGPM a abrogé en
1995 la classe des unités
supplémentaires dans le SI
(Résolution 8, _voir_ p. 70).
Ces unités sont maintenant
considérées comme des
unités dérivées.

[cols="4",options="unnumbered"]
|===
4+h| _Unités dérivées_

| superficie | mètre carré | stem:["unitsml(m^2)"] |
| volume mètre | cube | stem:["unitsml(m^3)"] |
| fréquence | hertz | stem:["unitsml(Hz)"] | stem:[1//"unitsml(s)"]
| masse volumique (densité) | kilogramme par mètre cube | stem:["unitsml(kg/m^3)"] |
| vitesse | mètre par seconde | stem:["unitsml(m/s)"] |
| vitesse angulaire | radian par seconde | stem:["unitsml(rad/s)"] |
| accélération | mètre par seconde carrée | stem:["unitsml(m/s^2)"] |
| accélération angulaire | radian par seconde carrée | stem:["unitsml(rad/s^2)"] |
| force | newton | stem:["unitsml(N)"] | stem:["unitsml(kg)" * "unitsml(m/s^2)"]
| pression (tension mécanique) | newton par mètre carré | stem:["unitsml(N/m^2)"] |
| viscosité cinématique (((viscosité,cinématique (stokes)))) | mètre carré par seconde | stem:["unitsml(m^2/s)"] |
| viscosité dynamique (((viscosité,dynamique (poise)))) | newton-seconde par mètre carré | stem:["unitsml(N*s//m^2)"] |
| travail, énergie, quantité de chaleur | joule | stem:["unitsml(J)"] | stem:["unitsml(N*m)"]
| puissance | watt | stem:["unitsml(W)"] | stem:["unitsml(J/s)"]
| quantité d’électricité | coulomb | stem:["unitsml(C)"] | stem:["unitsml(A*s)"]
| tension électrique, différence de potentiel, force électromotrice | volt(((volt (stem:["unitsml(V)"])))) | stem:["unitsml(V)"] | stem:["unitsml(W/A)"]
| intensité de champ électrique | volt(((volt (stem:["unitsml(V)"])))) par mètre | stem:["unitsml(V/m)"] |
| résistance électrique | ohm | stem:["unitsml(Ohm)"] | stem:["unitsml(V/A)"]
| capacité électrique | farad | stem:["unitsml(F)"] | stem:["unitsml(A*s//V)"]
| flux d’induction magnétique | weber | stem:["unitsml(Wb)"] | stem:["unitsml(V*s)"]
| inductance | henry | stem:["unitsml(H)"] | stem:["unitsml(V*s/A)"]
| induction magnétique | tesla | stem:["unitsml(T)"] | stem:["unitsml(Wb/m^2)"]
| intensité de champ magnétique | ampère par mètre | stem:["unitsml(A/m)"] |
| force magnétomotrice | ampère(((ampère (stem:["unitsml(A)"])))) | stem:["unitsml(A)"] |
| flux lumineux | lumen | stem:["unitsml(lm)"] | stem:["unitsml(cd*sr)"]
| luminance | candela par mètre carré | stem:["unitsml(cd/m^2)"] |
| éclairement | lux | stem:["unitsml(lx)"] | stem:["unitsml(lm/m^2)"]
|===

NOTE: La 13^e^ CGPM en 1967 (Résolution 6, _voir_ p. 59)
a ajouté d’autres unités à cette liste d’unités
dérivées, qui, en principe, n’est pas limitative.


==== Décimètre cube et litre (<<CR1960-13,page=88>>)

[align=center]
*Résolution 13*

La Onzième Conférence générale des poids et mesures,

*considérant*

* que le décimètre cube et le litre sont inégaux et diffèrent d’environ 28 millionièmes,
* que les déterminations de grandeurs physiques impliquant des mesures de volume ont une
précision de plus en plus élevée, aggravant par là les conséquences d’une confusion possible
entre le décimètre cube et le litre,

*invite* le Comité international des poids et mesures à mettre ce problème à l’étude et à
présenter ses conclusions à la Douzième Conférence générale.


=== CIPM, 1961

==== Décimètre cube et litre (<<PV29, page=34>>)

[align=center]
*Recommandation*

Le Comité international des poids et mesures recommande que les résultats des mesures
précises de volume soient exprimés en unités du Système international et non en litres.


=== CIPM, 1964

==== Étalons de fréquence (<<PV32, page=26>> et <<CR1964-5,page=93>>)

[align=center]
*Déclaration*

Le Comité international des poids et mesures,

*habilité* par la Résolution 5 de la Douzième Conférence générale des poids et mesures à
désigner les étalons atomiques ou moléculaires de fréquence à employer temporairement pour
les mesures physiques de temps,

*déclare que* l’étalon à employer est la transition entre les niveaux hyperfins stem:[F = 4], stem:[M = 0] et
stem:[F = 3], stem:[M = 0] de l’état fondamental ^2^S~1/2~ de l’atome de césium 133 non perturbé par des champs
extérieurs, et que la valeur stem:[9192631770] hertz est assignée à la fréquence de cette transition.


=== 12^e^ CGPM, 1964

==== Étalon atomique de fréquence (<<CR1964-5,page=93>>)

[align=center]
*Résolution 5*

La Douzième Conférence générale des poids et mesures,

*considérant*

* que la Onzième Conférence générale des poids et mesures a constaté dans sa Résolution 10
l’urgence pour les buts de la haute métrologie d’arriver à un étalon atomique ou moléculaire
d’intervalle de temps,
* que, malgré les résultats acquis dans l’utilisation des étalons atomiques de fréquence à césium,
le moment n’est pas encore venu pour la Conférence générale d’adopter une nouvelle définition
de la seconde, unité de base du Système international d’unités, en raison des progrès
nouveaux et importants qui peuvent être obtenus à la suite des études en cours,

*considérant aussi* qu’on ne peut pas attendre davantage pour fonder les mesures physiques
de temps sur des étalons atomiques ou moléculaires de fréquence,

*habilite* le Comité international des poids et mesures à désigner les étalons atomiques ou
moléculaires de fréquence à employer temporairement,

*invite* les Organisations et les Laboratoires experts dans ce domaine à poursuivre les études
utiles à une nouvelle définition de la seconde.


==== Litre (<<CR1964-6,page=93>>)

[align=center]
*Résolution 6*

La Douzième Conférence générale des poids et mesures,

*considérant* la Résolution 13 adoptée par la Onzième Conférence générale en 1960 et la
Recommandation adoptée par le Comité international des poids et mesures à sa session de
1961,

. *abroge* la définition du litre donnée en 1901 par la Troisième Conférence générale des poids
et mesures,
. *déclare* que le mot «{nbsp}litre{nbsp}» peut être utilisé comme un nom spécial donné au décimètre
cube,
. *recommande* que le nom de litre ne soit pas utilisé pour exprimer les résultats des mesures
de volume de haute précision.


==== Curie (<<CR1964-7,page=94>>)

NOTE: Le nom «{nbsp}becquerel{nbsp}»(((becquerel (stem:["unitsml(Bq)"])))) (Bq) a été adopté par la
15^e^ CGPM en 1975 (Résolution 8, _voir_ p. 63)
pour l’unité SI d’activité{nbsp}:
1 stem:[ii(C)_i = 3.7 xx 10^10 "unitsml(Bq)"].

[align=center]
*Résolution 7*

La Douzième Conférence générale des poids et mesures,

*considérant* que depuis longtemps le curie est utilisé dans beaucoup de pays comme unité
pour l’activité des radionucléides,

*reconnaissant* que dans le Système international d’unités (SI), l’unité de cette activité est la
seconde à la puissance moins un (stem:["unitsml(s^(-1))"]),

*admet* que le curie soit encore retenu comme unité en dehors du SI pour l’activité, avec la
valeur stem:[3.7 xx 10^10] stem:["unitsml(s^(-1))"]. Le symbole de cette unité est stem:[ii(C)_i].


==== Préfixes SI femto et atto (<<CR1964-8,page=94>>)

NOTE: De nouveaux préfixes
furent ajoutés par la 15^e^ CGPM en 1975
(Résolution 10, _voir_ p. 63).

[align=center]
*Résolution 8*

La Douzième Conférence générale des poids et mesures,

décide d’ajouter à la liste des préfixes pour la formation des noms des multiples et des
sous-multiples des unités, adoptée par la Onzième Conférence générale, Résolution 12,
paragraphe 3, les deux nouveaux préfixes suivants{nbsp}:

[cols="^,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[10^(-15)] | femto | f
| stem:[10^(-18)] | atto | a
|===


=== CIPM, 1967

==== Multiples et sous-multiples décimaux de l’unité de masse (<<PV35, page=29>> et _Metrologia_, 1968, 4, 45)

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures,

*considérant* que la règle de formation des noms des multiples et sous-multiples décimaux des
unités du paragraphe 3 de la Résolution 12 de la Onzième Conférence générale des poids et
mesures (1960) peut prêter à des interprétations divergentes dans son application à l’unité de
masse,

*déclare* que les dispositions de la Résolution 12 de la Onzième Conférence générale
s’appliquent dans le cas du kilogramme de la façon suivante{nbsp}: les noms des multiples et
sous-multiples décimaux de l’unité de masse sont formés par l’adjonction des préfixes au mot
«{nbsp}gramme{nbsp}».


=== 13^e^ CGPM, 1967/68

==== Unité SI de temps (seconde) (<<CR1967-1,page=103>> et _Metrologia_, 1968, 4, 43)

[align=center]
*Résolution 1*

La Treizième Conférence générale des poids et mesures,

*considérant*

* que la définition de la seconde décidée par le Comité international des poids et mesures à sa
session de 1956 (Résolution 1) et ratifiée par la Résolution 9 de la Onzième Conférence
générale (1960), puis maintenue par la Résolution 5 de la Douzième Conférence générale
(1964) ne suffit pas aux besoins actuels de la métrologie,
* qu’à sa session de 1964 le Comité international des poids et mesures, habilité par la Résolution
5 de la Douzième Conférence (1964), a désigné pour répondre à ces besoins un étalon
atomique de fréquence à césium à employer temporairement,
* que cet étalon de fréquence est maintenant suffisamment éprouvé et suffisamment précis pour
servir à une définition de la seconde répondant aux besoins actuels,
* que le moment est venu de remplacer la définition actuellement en vigueur de l’unité de temps
du Système international d’unités par une définition atomique fondée sur cet étalon,


*décide*

. L’unité de temps du Système international d’unités est la seconde définie dans les termes
suivants{nbsp}:
+
--
«{nbsp}La seconde est la durée de stem:[9192631770] périodes de la radiation correspondant à
la transition entre les deux niveaux hyperfins de l’état fondamental de l’atome de
césium 133{nbsp}».

NOTE: Lors de sa session de 1997, le Comité international a
confirmé que cette définition se réfère à un
atome de césium au repos, à une température de stem:[0 "unitsml(K)"].
--
. La Résolution 1 adoptée par le Comité international des poids et mesures à sa session de
1956 et la Résolution 9 de la Onzième Conférence générale des poids et mesures sont
abrogées.
+
--
NOTE: La formulation de la définition de la seconde a
été modifiée par la CGPM à sa 26^e^ réunion en 2018
(Résolution 1, _voir_ p.92).
--


==== Unité SI de température thermodynamique (kelvin) (<<CR1967-3,page=104>> et _Metrologia_, 1968, 4, 43)

NOTE: À sa session de 1980, le Comité international a
approuvé le rapport de la 7^e^ session du CCU
demandant que l’emploi des symboles «{nbsp}stem:["unitsml(degK)"]{nbsp}» et
«{nbsp}deg{nbsp}» ne soit plus admis.

[align=center]
*Résolution 3*

La Treizième Conférence générale des poids et mesures,

*considérant*

* les noms «{nbsp}degré Kelvin{nbsp}» et «{nbsp}degré{nbsp}», les symboles «{nbsp}stem:["unitsml(degK)"]{nbsp}» et «{nbsp}deg{nbsp}» et leurs règles d’emploi
contenus dans la Résolution 7 de la Neuvième Conférence générale (1948), dans la Résolution
12 de la Onzième Conférence générale (1960) et la décision prise par le Comité international
des poids et mesures en 1962 (<<PV30, page=27>>),

* que l’unité de température thermodynamique et l’unité d’intervalle de température sont une
même unité qui devrait être désignée par un nom unique et par un symbole unique,

*décide*

. l’unité de température thermodynamique est désignée sous le nom «{nbsp}kelvin{nbsp}» et son symbole
est «{nbsp}stem:["unitsml(K)"]{nbsp}»{nbsp};
+
--
NOTE: Voir la Recommandation 2
(CI-2005) du CIPM relative à la composition
isotopique de l’eau entrant dans la définition du
kelvin (p. 76).
--
. ce même nom et ce même symbole sont utilisés pour exprimer un intervalle de température{nbsp};
. un intervalle de température peut aussi s’exprimer en degrés Celsius{nbsp};
. les décisions mentionnées au premier considérant concernant le nom de l’unité de
température thermodynamique, son symbole et la désignation de l’unité pour exprimer un
intervalle ou une différence de température sont abrogées, mais les usages qui sont la
conséquence de ces décisions restent admis temporairement.


==== Définition de l’unité SI de température thermodynamique (kelvin) (<<CR1967-4,page=104>> et _Metrologia_, 1968, 4, 43)*

[NOTE]
====
Voir la Recommandation 5
(CI-1989) du CIPM relative à l’Échelle
internationale de température de 1990 (p. 69).

Le kelvin a été redéfini
par la CGPM à sa 26^e^
réunion en 2018
(Résolution 1, _voir_ p.92).
====

[align=center]
*Résolution 4*

La Treizième Conférence générale des poids et mesures,

*considérant* qu’il est utile de formuler dans une rédaction explicite la définition de l’unité de
température thermodynamique contenue dans la Résolution 3 de la Dixième Conférence
générale (1954),

*décide* d’exprimer cette définition de la façon suivante{nbsp}:
«{nbsp}Le kelvin, unité de température thermodynamique, est la fraction stem:[1//273.16] de la température
thermodynamique du point triple de l’eau.{nbsp}»


==== Unité SI d’intensité lumineuse (candela(((candela (stem:["unitsml(cd)"]))))) (<<CR1967-5,page=104>> et _Metrologia_, 1968, 4, 43-44)

NOTE: Définition abrogée en 1979 par la 16^e^ CGPM
(Résolution 3, _voir_ p. 63).


*Résolution 5*

La Treizième Conférence générale des poids et mesures,

*considérant*

* la définition de l’unité d’intensité lumineuse ratifiée par la Neuvième Conférence générale
(1948) et contenue dans la «{nbsp}Résolution concernant le changement des unités
photométriques{nbsp}» adoptée par le Comité international des poids et mesures en 1946
(<<PV20, page=119>>) en vertu des pouvoirs conférés par la Huitième Conférence générale (1933),
* que cette définition fixe bien la grandeur de l’unité d’intensité lumineuse mais prête à des
critiques d’ordre rédactionnel,

*décide* d’exprimer la définition de la candela(((candela (stem:["unitsml(cd)"])))) de la façon suivante{nbsp}:

«{nbsp}La candela(((candela (stem:["unitsml(cd)"])))) est l’intensité lumineuse, dans la direction perpendiculaire, d’une surface de
stem:[1//600000] mètre carré d’un corps noir à la température de congélation du platine sous la
pression de stem:[101325] newtons par mètre carré.{nbsp}»


==== Unités SI dérivées (<<CR1975-8,page=105>> et _Metrologia_, 1968, 4, 44)

NOTE: L’unité d’activité a reçu un nom spécial et un
symbole particulier lors de la 15^e^ CGPM en 1975
(Résolution 8, _voir_ p. 63).

[align=center]
*Résolution 6*

La Treizième Conférence générale des poids et mesures,

*considérant* qu’il est utile de citer d’autres unités dérivées dans la liste du paragraphe 4 de la
Résolution 12 de la Onzième Conférence générale (1960),

*décide* d’y ajouter{nbsp}:

[cols="3",options="unnumbered"]
|===
| nombre d’ondes | 1 par mètre | stem:["unitsml(m^(-1))"]
| entropie | joule par kelvin | stem:["unitsml(J/K)"]
| chaleur massique | joule par kilogramme kelvin | stem:["unitsml(J//(kg*K),symbol:J//(kg cdot K))"]
| conductivité thermique | watt par mètre kelvin | stem:["unitsml(W//(m*K),symbol:W//(m cdot K))"]
| intensité énergétique | watt par stéradian | stem:["unitsml(W/sr)"]
| activité (d’une source radioactive) | 1 par seconde | stem:["unitsml(s^(-1))"]
|===


==== Abrogation de décisions antérieures (micron et bougie nouvelle) (<<CR1968-7,page=105>> et _Metrologia_, 1968, 4, 44)

[align=center]
*Résolution 7*

La Treizième Conférence générale des poids et mesures,

*considérant* que les décisions prises ultérieurement par la Conférence générale concernant le
Système international d’unités contredisent quelques parties de la Résolution 7 de la Neuvième
Conférence générale (1948),

*décide* en conséquence de retirer de la Résolution 7 de la Neuvième Conférence{nbsp}:

. le nom d’unité «{nbsp}micron{nbsp}», et le symbole «{nbsp}stem:[mu]{nbsp}» qui fut attribué à cette unité et qui est devenu
un préfixe{nbsp};
. le nom d’unité «{nbsp}bougie nouvelle{nbsp}».


=== CIPM, 1969

==== Système international d’unités, modalités d’application de la Résolution 12 de la 11^e^ CGPM (1960) (<<PV37, page=30>> et _Metrologia_, 1970, 6, 66)*

NOTE: La 20^e^ CGPM a décidé
d’abroger en 1995 (Résolution 8, _voir_ p. 70)
la classe des unités supplémentaires dans le SI.

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*considérant* que la Résolution 12 de la Onzième Conférence générale des poids et mesures
(1960), concernant le Système international d’unités, a suscité des discussions sur certaines
dénominations,

*déclare*

1. les unités de base, les unités supplémentaires et les unités dérivées du Système
international d’unités, qui forment un ensemble cohérent, sont désignées sous le nom
d’«{nbsp}unités SI{nbsp}»{nbsp};
+
--
NOTE: Le CIPM a approuvé en
2001 une proposition du
CCU visant à clarifier la
définition des «{nbsp}unités SI{nbsp}»
et «{nbsp}unités du SI{nbsp}»,
_voir_ p. 72.
--
2. les préfixes adoptés par la Conférence générale pour la formation des multiples et
sous-multiples décimaux des unités SI sont appelés «{nbsp}préfixes SI{nbsp}»{nbsp};

*et recommande*

3. d’employer les unités SI et leurs multiples et sous-multiples décimaux dont les noms sont
formés au moyen des préfixes SI.

NOTE: L’appellation «{nbsp}unités supplémentaires{nbsp}», figurant dans la Résolution 12 de la Onzième
Conférence générale des poids et mesures (et dans la présente Recommandation), est donnée
aux unités SI pour lesquelles la Conférence générale ne décide pas s’il s’agit d’unités de base
ou bien d’unités dérivées.


=== CCDS, 1970 (In CIPM, 1970) (((unité(s),ayant des noms spéciaux et des symboles particuliers)))

==== Définition du TAI (<<PV38, page=110-111>> et _Metrologia_, 1971, 7, 43)

[align=center]
*Recommandation S 2*

Le Temps atomique international est la coordonnée de repérage temporel établie par le Bureau
international de l’heure sur la base des indications d’horloges atomiques fonctionnant dans
divers établissements conformément à la définition de la seconde, unité de temps du Système
international d’unités.

En 1980, la définition du TAI a été complétée comme suit (déclaration du CCDS, _BIPM Com.
cons. déf. seconde_, 1980, 9, S 15 et _Metrologia_, 1981, 17, 70){nbsp}:

Le TAI est une échelle de temps-coordonnée définie dans un repère de référence géocentrique
avec comme unité d’échelle la seconde du SI telle qu’elle est réalisée sur le géoïde en rotation.

[NOTE]
====
L’Union astronomique internationale a précisé
cette définition dans sa Résolution A4 de 1991{nbsp}:

«{nbsp}Le TAI est une échelle de temps réalisée dont la
forme idéale, si l’on néglige un décalage
constant de stem:[32.184 "unitsml(s)"], est le Temps terrestre (TT),
lui-même relié à la coordonnée temps du
référentiel géocentrique, le Temps-coordonnée
géocentrique (TCG), par une marche
constante.{nbsp}»

(_voir_ Proc. 21st General
Assembly of the IAU, _IAU Trans._, 1991,
vol. XXIB, Kluwer.)
====


=== 14^e^ CGPM, 1971

==== Pascal et siemens (<<CR1971-2,page=78>>)

La 14^e^ Conférence générale a adopté les noms spéciaux «{nbsp}pascal{nbsp}» (symbole stem:["unitsml(Pa)"]) pour l’unité SI
newton par mètre carré et «{nbsp}siemens{nbsp}» (symbole stem:["unitsml(S)"]) pour l’unité SI de conductance électrique
(ohm à la puissance moins un).


==== Temps atomique international{nbsp}; rôle du CIPM (<<CR1971-1,page=77>>-<<CR1971-1,page=78>> et _Metrologia_, 1972, 8, 35)

[align=center]
*Résolution 1*

La Quatorzième Conférence générale des poids et mesures,

*considérant*

* que la seconde, unité de temps du Système international d’unités, est définie depuis 1967
d’après une fréquence atomique naturelle, et non plus d’après des échelles de temps fournies
par des mouvements astronomiques,
* que le besoin d’une échelle de Temps atomique international (TAI) est une conséquence de la
définition atomique de la seconde,
* que plusieurs organisations internationales ont assuré et assurent encore avec succès
l’établissement des échelles de temps fondées sur des mouvements astronomiques,
particulièrement grâce aux services permanents du Bureau international de l’heure (BIH),
* que le Bureau international de l’heure a commencé à établir une échelle de temps atomique
dont les qualités sont reconnues et qui a prouvé son utilité,
* que les étalons atomiques de fréquence servant à la réalisation de la seconde ont été
considérés et doivent continuer de l’être par le Comité international des poids et mesures
assisté d’un Comité consultatif, et que l’intervalle unitaire de l’échelle de Temps atomique
international doit être la seconde réalisée conformément à sa définition atomique,
* que toutes les organisations scientifiques internationales compétentes et les laboratoires
nationaux actifs dans ce domaine ont exprimé le désir que le Comité international et la
Conférence générale des poids et mesures donnent une définition du Temps atomique
international, et contribuent à l’établissement de l’échelle de Temps atomique international,
* que l’utilité du Temps atomique international nécessite une coordination étroite avec les
échelles de temps fondées sur des mouvements astronomiques,


*demande* au Comité international des poids et mesures

. de donner une définition du Temps atomique international{nbsp};
. de prendre les mesures nécessaires, en accord avec les organisations internationales
intéressées, pour que les compétences scientifiques et les moyens d’action existants soient
utilisés au mieux pour la réalisation de l’échelle de Temps atomique international, et pour
que soient satisfaits les besoins des utilisateurs du Temps atomique international.

NOTE: La définition du TAI a été
donnée par le CCDS en 1970 (maintenant renommé CCTF),
_voir_ p. 61.


==== Unité SI de quantité de matière (mole) (<<CR1971-2,page=78>> et _Metrologia_, 1972, 8, 36)

NOTE: À sa session de 1980, le CIPM a approuvé le rapport de la 7^e^ session du
CCU (1980) précisant que, dans cette définition, il est
entendu que l’on se réfère à des atomes de carbone 12 non liés,
au repos et dans leur état fondamental.


[align=center]
*Résolution 3*

La Quatorzième Conférence générale des poids et mesures,

*considérant* les avis de l’Union internationale de physique pure et appliquée, de l’Union
internationale de chimie pure et appliquée et de l’Organisation internationale de normalisation
concernant le besoin de définir une unité de quantité de matière,

*décide*

. La mole est la quantité de matière d’un système contenant autant d’entités élémentaires qu’il
y a d’atomes dans stem:[0.012] kilogramme de carbone 12{nbsp}; son symbole est «{nbsp}stem:["unitsml(mol)"]{nbsp}».
+
--
NOTE: La mole a été redéfinie
par la CGPM à sa
26^e^ réunion en 2018
(Résolution 1, _voir_ p.92).
--
. Lorsqu’on emploie la mole, les entités élémentaires doivent être spécifiées et peuvent être
des atomes, des molécules, des ions, des électrons, d’autres particules ou des groupements
spécifiés de telles particules.
. La mole est une unité de base du Système international d’unités.


=== 15^e^ CGPM, 1975

==== Valeur recommandée pour la vitesse de la lumière (<<CR1975-2,page=103>> et _Metrologia_, 1975, 11, 179-180)

[align=center]
*Résolution 2*

La Quinzième Conférence générale des poids et mesures,

*considérant* l’excellent accord entre les résultats des mesures de longueur d’onde portant sur
des radiations de lasers asservis sur une raie d’absorption moléculaire dans la région visible ou
infrarouge, avec une incertitude estimée à stem:[+- 4 xx 10^(-9)] qui correspond à l’indétermination de la
réalisation du mètre,

*considérant* aussi les mesures concordantes de la fréquence de plusieurs de ces radiations,

*recommande* l’emploi de la valeur qui en résulte pour la vitesse de propagation des ondes
électromagnétiques dans le vide stem:[c = 299792458] mètres par seconde.

NOTE: L’incertitude relative doit être comprise comme étant
trois fois l’incertitude-type estimée sur les résultats
considérés.


==== Temps universel coordonné (UTC) (<<CR1975-5,page=104>> et _Metrologia_, 1975, 11, 180)

[align=center]
*Résolution 5*

La Quinzième Conférence générale des poids et mesures,

*considérant* que le système appelé «{nbsp}Temps universel coordonné{nbsp}» (UTC) est employé très
largement, qu’il est diffusé par la plupart des émetteurs hertziens de signaux horaires, que sa
diffusion fournit aux utilisateurs à la fois des fréquences étalons, le Temps atomique
international et une approximation du Temps universel (ou, si l’on préfère, du temps solaire
moyen),

*constate* que ce Temps universel coordonné est à la base du temps civil dont l’usage est légal
dans la plupart des pays,

*estime* que cet emploi est parfaitement recommandable.


==== Unités SI pour les rayonnements ionisants (becquerel(((becquerel (stem:["unitsml(Bq)"])))) et gray) (<<CR105>> et _Metrologia_, 1975, 11, 180)

NOTE: À sa session de 1976, le Comité international a
approuvé le rapport de la 5^e^ session du CCU (1976)
précisant que, suivant l’avis de l’ICRU, le gray
peut être employé aussi pour exprimer l’énergie
communiquée massique, le kerma et l’indice de
dose absorbée.

[align=center]
*Résolutions 8 et 9*

La Quinzième Conférence générale des poids et mesures, +
en raison de l’urgence, exprimée par la Commission internationale des unités et mesures de
rayonnements (ICRU), d’étendre l’usage du Système international d’unités aux recherches et
aux applications de la radiologie, +
en raison de la nécessité de rendre aussi simple que possible l’usage des unités aux
non-spécialistes, +
tenant compte aussi de la gravité des risques d’erreurs dans la thérapeutique,

*adopte* le nom spécial suivant d’unité SI pour l’activité{nbsp}:

le *becquerel*(((becquerel (stem:["unitsml(Bq)"])))), symbole stem:["unitsml(Bq)"], égal à la seconde à la puissance moins un (Résolution 8),

*adopte* le nom spécial suivant d’unité SI pour les rayonnements ionisants{nbsp}:

le *gray*, symbole stem:["unitsml(Gy)"], égal au joule par kilogramme (Résolution 9).

NOTE: Le gray est l’unité SI de dose absorbée. Dans le domaine des rayonnements ionisants, le
gray peut encore être employé avec d’autres grandeurs physiques qui s’expriment aussi en
joules par kilogramme{nbsp}; le Comité consultatif des unités est chargé d’étudier cette question en
collaboration avec les organisations internationales compétentes.


==== Préfixes SI péta et exa (<<CR1975-10,page=106>> et _Metrologia_, 1975, 11, 180-181)

NOTE: De nouveaux préfixes furent ajoutés en 1991
par la 19^e^ CGPM (Résolution 4, _voir_ p. 70).

[align=center]
*Résolution 10*

La Quinzième Conférence générale des poids et mesures, +
*décide* d’ajouter à la liste des préfixes SI pour la formation des noms des multiples des unités,
adoptée par la Onzième Conférence générale, Résolution 12, paragraphe 3,
les deux préfixes suivants{nbsp}:

[cols="^,^,^",options="unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole
| stem:[10^15] | peta | P
| stem:[10^18] | exa | E
|===

NOTE: En français, il est d’usage
courant de mettre un accent à péta.


=== 16^e^ CGPM, 1979

==== Unité SI d’intensité lumineuse (candela(((candela (stem:["unitsml(cd)"]))))) (<<CR1979-3,page=100>> et _Metrologia_, 1980, 16, 56)

NOTE: La formulation de la définition de la candela(((candela (stem:["unitsml(cd)"])))) a
été modifiée par la CGPM à sa 26^e^ réunion en 2018
(Résolution 1, _voir_ p.92).

[align=center]
*Résolution 3*

La Seizième Conférence générale des poids et mesures,

*considérant*

* que, malgré les efforts méritoires de quelques laboratoires, il subsiste des divergences
excessives entre les résultats de la réalisation de la candela(((candela (stem:["unitsml(cd)"])))) à l’aide du corps noir étalon
primaire actuel,
* que les techniques radiométriques se développent rapidement, autorisant des précisions qui
sont déjà analogues à celles de la photométrie et que ces techniques sont déjà en usage dans
des laboratoires nationaux pour réaliser la candela(((candela (stem:["unitsml(cd)"])))) sans avoir à construire un corps noir,
* que la relation entre les grandeurs lumineuses de la photométrie et les grandeurs énergétiques,
à savoir la valeur 683 lumens par watt pour l’efficacité lumineuse spectrale de la radiation
monochromatique de fréquence stem:[540 xx 10^12] hertz, a été adoptée par le Comité international des
poids et mesures en 1977,
+
--
NOTE: La vision photopique est détectée sur la rétine de
l’oeil par les cônes, sensibles aux luminances
élevées (stem:["unitsml(L)" >] environ stem:[10] stem:["unitsml(cd*m^(-2))"]), qui
correspondent à la vision diurne.
--
* que cette valeur a été reconnue suffisamment exacte pour le système des grandeurs
lumineuses photopiques, qu’elle n’entraîne qu’un changement d’environ 3 % pour le système
des grandeurs lumineuses scotopiques et que par conséquent elle assure une continuité
satisfaisante,
* que le moment est venu de donner à la candela(((candela (stem:["unitsml(cd)"])))) une définition susceptible d’améliorer la facilité
d’établissement des étalons photométriques et leur précision, et qui s’applique aux grandeurs
photopiques et scotopiques de la photométrie et aux grandeurs à définir dans le domaine
mésopique,
+
--
NOTE: La vision scotopique est détectée sur la rétine de
l’oeil par les bâtonnets, sensibles aux faibles
luminances (L < environ stem:[10^(−3) "unitsml(cd*m^(−2))"]), qui correspondent à la
vision nocturne.
--

*décide*

. La candela(((candela (stem:["unitsml(cd)"])))) est l’intensité lumineuse, dans une direction donnée, d’une source qui émet un
rayonnement monochromatique de fréquence stem:[540 xx 10^12] stem:["hertz"] et dont l’intensité énergétique
dans cette direction est 1/683 watt par stéradian.

. La définition de la candela(((candela (stem:["unitsml(cd)"])))) (à l’époque appelée bougie nouvelle) décidée par le Comité
international des poids et mesures en 1946 en vertu des pouvoirs conférés par la
8^e^ Conférence générale des poids et mesures (CGPM) en 1933, ratifiée par la 9^e^ CGPM en
1948, puis amendée par la 13^e^ CGPM en 1967, est abrogée.

NOTE: Dans le cas de luminances intermédiaires entre la
vision photopique et la vision scotopique, les
cônes et les bâtonnets fonctionnent
simultanément, on est alors dans le domaine
de la vision mésopique.


==== Nom spécial pour l’unité SI d’équivalent de dose (sievert) (<<CR1979-4,page=100>> et _Metrologia_, 1980, 16, 56)

NOTE: Le Comité international a décidé en 1984 d’accompagner cette
Résolution d’une explication, (Recommandation 1, _voir_ p. 67).

[align=center]
*Résolution 5*

La Seizième Conférence générale des poids et mesures,

*considérant*

* l’effort fait pour introduire les unités SI dans le domaine des rayonnements ionisants,
* les risques que peuvent encourir des êtres humains soumis à des irradiations sous-estimées,
risques qui pourraient résulter de la confusion entre dose absorbée et équivalent de dose,
* que la prolifération des noms spéciaux représente un danger pour le Système international
d’unités et doit être évitée dans toute la mesure du possible, mais que cette règle peut être
transgressée lorsqu’il s’agit de sauvegarder la santé humaine,

*adopte* le nom spécial *sievert*, symbole stem:["unitsml(Sv)"], pour l’unité SI d’équivalent de dose dans le
domaine de la radioprotection. Le sievert est égal au joule par kilogramme.


==== Symboles du litre (<<CR1979-6,page=101>> et _Metrologia_, 1980, 16, 56-57)

[align=center]
*Résolution 6*

La Seizième Conférence générale des poids et mesures,

*reconnaissant* les principes généraux adoptés pour l’écriture des symboles des unités dans la
Résolution 7 de la 9^e^ Conférence générale des poids et mesures (1948),

*considérant* que le symbole stem:["unitsml(l)"] pour l’unité litre a été adopté par le Comité international des poids
et mesures en 1879 et confirmé dans cette même Résolution de 1948,

*considérant* aussi que, afin d’éviter un risque de confusion entre la lettre l et le chiffre 1,
plusieurs pays ont adopté le symbole stem:["unitsml(L)"] au lieu de l pour l’unité litre,

*considérant* que le nom litre, bien qu’il ne soit pas inclus dans le Système international d’unités,
doit être admis pour l’usage général avec ce Système,

*décide*, à titre exceptionnel, d’adopter les deux symboles stem:["unitsml(l)"] et stem:["unitsml(L)"] comme symboles utilisables
pour l’unité litre,

NOTE: Le Comité international a estimé encore prématuré,
en 1990, de choisir un symbole unique du litre.

*considérant* en outre que dans l’avenir un seul des deux symboles devrait être retenu,

*invite* le Comité international des poids et mesures à suivre le développement de l’usage des
deux symboles et à donner à la 18^e^ Conférence générale des poids et mesures son avis sur la
possibilité de supprimer l’un d’eux.


=== CIPM, 1980

==== Unités SI supplémentaires (radian et stéradian) (<<PV48, page=24>> et _Metrologia_, 1981, 17, 72)

NOTE: La classe des unités supplémentaires dans le SI
a été abrogée en 1995 par décision de la 20^e^ CGPM
(Résolution 8, _voir_ p. 70).

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures (CIPM),

*prenant en considération* la Résolution 3 adoptée par l’ISO/TC 12 en 1978 et la
Recommandation U 1 (1980) adoptée par le Comité consultatif des unités (CCU)
à sa 7^e^ session,

*considérant*

* que les unités radian et stéradian sont introduites usuellement dans des expressions des unités
pour des besoins de clarification, notamment en photométrie où le stéradian joue un rôle
important pour distinguer les unités correspondant aux diverses grandeurs,
* que dans les équations utilisées on exprime généralement l’angle plan comme le rapport entre
deux longueurs et l’angle solide comme le rapport entre une aire et le carré d’une longueur, et
que par conséquent ces grandeurs sont traitées comme des grandeurs sans dimension,
* que l’étude des formalismes en usage dans le domaine scientifique montre qu’il n’en existe
aucun qui soit à la fois cohérent et convenable, et dans lequel les grandeurs angle plan et angle
solide soient considérées comme des grandeurs de base,

*considérant aussi*

* que l’interprétation donnée par le CIPM en 1969 pour la classe des unités supplémentaires
introduite dans la Résolution 12 de la 11^e^ Conférence générale des poids et mesures en 1960
laisse la liberté de traiter le radian et le stéradian comme unités de base dans le Système
international,
* qu’une telle possibilité compromet la cohérence interne du Système international fondé sur sept
unités de base seulement,

*décide* d’interpréter la classe des unités supplémentaires dans le Système international comme
une classe d’unités dérivées sans dimension pour lesquelles la Conférence générale des poids
et mesures laisse la liberté de les utiliser ou non dans les expressions des unités dérivées du
Système international.


=== 17^e^ CGPM, 1983

==== Définition du mètre (<<CR1983-1,page=97>> et _Metrologia_, 1984, 20, 25)

NOTE: La formulation de la définition du mètre a été
modifiée par la CGPM à sa 26^e^ réunion en 2018
(Résolution 1, _voir_ p.92).

[align=center]
*Résolution 1*

La Dix-septième Conférence générale des poids et mesures,

*considérant*

* que la définition actuelle ne permet pas une réalisation du mètre suffisamment précise pour
tous les besoins,
* que les progrès réalisés dans l’asservissement des lasers permettent d’obtenir des radiations
plus reproductibles et plus faciles à utiliser que la radiation étalon émise par une lampe à
krypton 86,
* que les progrès réalisés dans la mesure des fréquences et des longueurs d’onde de ces
radiations ont abouti à des déterminations concordantes de la vitesse de la lumière dont
l’exactitude est limitée principalement par la réalisation du mètre dans sa définition actuelle,
* que les valeurs des longueurs d’onde déterminées à partir de mesures de fréquence et d’une
valeur donnée de la vitesse de la lumière ont une précision supérieure à celle qui peut être
obtenue par comparaison avec la longueur d’onde de la radiation étalon du krypton 86,
* qu’il y a avantage, notamment pour l’astronomie et la géodésie, à maintenir inchangée la valeur
de la vitesse de la lumière recommandée en 1975 par la 15^e^ Conférence générale des poids et
mesures, dans sa Résolution 2 (stem:[c = 299792458 "unitsml(m/s)"]),
* qu’une nouvelle définition du mètre a été envisagée sous diverses formes qui ont toutes pour
effet de donner à la vitesse de la lumière une valeur exacte, égale à la valeur recommandée, et
que cela n’introduit aucune discontinuité appréciable de l’unité de longueur, compte tenu de
l’incertitude relative de stem:[+- 4 xx 10^(-9)] des meilleures réalisations du mètre dans sa définition
actuelle.
+
--
NOTE: La valeur de l’incertitude donnée ici correspond à
trois fois l’écart-type de la valeur en question.
--
* que ces diverses formes, faisant appel soit au trajet parcouru par la lumière dans un intervalle
de temps spécifié, soit à la longueur d’onde d’une radiation de fréquence mesurée ou de
fréquence spécifiée, ont fait l’objet de consultations et de discussions approfondies, qu’elles ont
été reconnues équivalentes et qu’un consensus s’est dégagé en faveur de la première forme,
* que le Comité consultatif pour la définition du mètre est dès maintenant en mesure de donner
des instructions pour la mise en pratique d’une telle définition, instructions qui pourront inclure
l’emploi de la radiation orangée du krypton 86 utilisée jusqu’ici comme étalon et qui pourront
être complétées ou révisées par la suite,

*décide*

. Le mètre est la longueur du trajet parcouru dans le vide par la lumière pendant une durée de
stem:[1//299792458] de seconde.

. La définition du mètre en vigueur depuis 1960, fondée sur la transition entre les niveaux 2p10
et 5d5 de l’atome de krypton 86, est abrogée.


==== Sur la mise en pratique de la définition du mètre (<<CR1983-2,page=98>> et _Metrologia_, 1984, 20, 25-26)

NOTE: Voir Recommandation 1 (CI-2002) du CIPM
relative à la révision de la mise en pratique de la
définition du mètre, p. 72.

[align=center]
*Résolution 2*

La Dix-septième Conférence générale des poids et mesures

*invite* le Comité international des poids et mesures

* à établir des instructions pour la mise en pratique de la nouvelle définition du mètre,
* à choisir des radiations qui puissent être recommandées comme étalons de longueur d’onde
pour la mesure interférentielle des longueurs et à établir des instructions pour leur emploi,
* à poursuivre les études entreprises pour améliorer ces étalons.


=== CIPM, 1984

==== Au sujet du sievert (<<PV52, page=31>> et _Metrologia_, 1985, 21, 90)

NOTE: Le CIPM a décidé en 2002 de modifier les
explications sur la grandeur «{nbsp}équivalent de
dose{nbsp}» dans la Brochure sur le SI
(Recommandation 2 (CI-2002), _voir_ p. 74).

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*considérant* la confusion qui continue d’exister au sujet de la Résolution 5, votée par la
16^e^ Conférence générale des poids et mesures (1979),

*décide* d’introduire l’explication suivante dans la Brochure «{nbsp}Le Système international d’unités
(SI){nbsp}»{nbsp}:

La grandeur équivalent de dose H est le produit de la dose absorbée D de rayonnements
ionisants et de deux facteurs sans dimension Q (facteur de qualité) et N (produit de tous les
autres facteurs de multiplication) prescrits par l’International Commission on Radiological
Protection{nbsp}:

[stem%unnumbered]
++++
ii(H) = ii(Q) * ii(N) * ii(D)
++++

Ainsi, pour une radiation donnée, la valeur numérique de stem:[ii(H)] en joules par kilogramme peut être
différente de la valeur numérique de stem:[ii(D)] en joules par kilogramme, puisqu’elle est fonction de la
valeur de stem:[ii(Q)] et de stem:[ii(N)]. Afin d’éviter tout risque de confusion entre la dose absorbée stem:[ii(D)] et
l’équivalent de dose stem:[ii(H)], il faut employer les noms spéciaux pour les unités correspondantes,
c’est-à-dire qu’il faut utiliser le nom gray au lieu de joule par kilogramme pour l’unité de dose
absorbée stem:[ii(D)] et le nom sievert au lieu de joule par kilogramme pour l’unité d’équivalent de dose
stem:[ii(H)].


=== 18^e^ CGPM, 1987

==== Ajustement prévu des représentations du volt et de l’ohm (<<CR1987-,page=100>> et _Metrologia_, 1988, 25, 115)

[align=center]
*Résolution 6*

La Dix-huitième Conférence générale des poids et mesures,

*considérant*

* que l’uniformité mondiale et la constance à long terme des représentations nationales des
unités électriques sont d’une importance majeure pour la science, le commerce et l’industrie du
point de vue technique comme du point de vue économique,
* que de nombreux laboratoires nationaux utilisent l’effet Josephson et commencent à utiliser
l’effet Hall quantique pour conserver respectivement des représentations du volt et de l’ohm qui
donnent les meilleures garanties de stabilité à long terme,
* qu’en raison de l’importance de la cohérence entre les unités de mesure des diverses
grandeurs physiques les valeurs attribuées à ces représentations doivent être autant que
possible en accord avec le SI,
* que l’ensemble des résultats des expériences en cours ou récemment achevées permettra
d’établir une valeur acceptable, suffisamment compatible avec le SI, pour le coefficient qui relie
chacun de ces effets à l’unité électrique correspondante,

*invite* les laboratoires dont les travaux peuvent contribuer à établir la valeur du quotient de la
tension par la fréquence dans l’effet Josephson et de la tension par le courant dans l’effet Hall
quantique à poursuivre activement ces travaux et à communiquer sans délai leurs résultats au
Comité international des poids et mesures et,

*charge* le Comité international des poids et mesures de recommander, dès qu’il le jugera
possible, une valeur de chacun de ces quotients et une date à laquelle elle pourra être mise en
pratique simultanément dans tous les pays{nbsp}; cette valeur devrait être annoncée au moins un an
à l’avance et pourrait être adoptée au 1^er^ janvier 1990.


=== CIPM, 1988 (((volt (stem:["unitsml(V)"]))))

==== Représentation du volt au moyen de l’effet Josephson (<<PV56, page=19>> et _Metrologia_, 1989, 26, 69)

NOTE: La CGPM à sa 26^e^ réunion en 2018 (Résolution 1,
_voir_ p.92) a abrogé l’adoption d’une valeur
conventionnelle de stem:[ii(K)_J].

[align=center]
*Recommandation 1*
(((volt (stem:["unitsml(V)"]))))

Le Comité international des poids et mesures

*agissant* conformément aux instructions données dans la Résolution 6 de la 18^e^ Conférence
générale des poids et mesures concernant l’ajustement prévu des représentations du volt et de
l’ohm,

*considérant*

* qu’une étude approfondie des résultats des déterminations les plus récentes conduit à une
valeur de stem:[483597.9 "unitsml(GHz/V)"] pour la constante de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))), stem:[ii(K)_J], c’est-à-dire pour le quotient de
la fréquence par la tension correspondant au palier de rang stem:[n = 1] dans l’effet Josephson,
* que l’effet Josephson, avec cette valeur de stem:[ii(K)_J], peut être utilisé pour établir un étalon de
référence de force électromotrice dont l’incertitude (écart-type), par rapport au volt, est estimée
à stem:[4 xx 10^(-7)] en valeur relative et dont la reproductibilité est nettement meilleure,

*recommande*

* que l’on adopte, par convention, pour la constante de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))), stem:[ii(K)_J], la valeur
stem:[ii(K)_{J-90} = 483597.9] stem:["unitsml(GHz/V)"] exactement,
* que cette nouvelle valeur soit utilisée à partir du 1^er^ janvier 1990, et non auparavant,
pour remplacer les valeurs actuellement en usage,
* que cette nouvelle valeur soit utilisée à partir de cette même date par tous les laboratoires qui
fondent sur l’effet Josephson leurs mesures de force électromotrice,
* qu’à partir de cette même date tous les autres laboratoires ajustent la valeur de leurs étalons de
référence pour la mettre en accord avec cette nouvelle valeur,

*estime* qu’aucun changement de cette valeur recommandée de la constante de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))) ne
sera nécessaire dans un avenir prévisible,

*attire* l’attention des laboratoires sur le fait que la nouvelle valeur est supérieure de stem:[3.9 "unitsml(GHz/V)"],
soit approximativement stem:[8 xx 10^(-6)] en valeur relative, à la valeur donnée en 1972 par le Comité
consultatif d’électricité dans sa Déclaration E-72.


==== Représentation de l’ohm au moyen de l’effet Hall quantique (<<PV56, page=20>> et _Metrologia_, 1989, 26, 70)

NOTE: Lors de sa 89^e^ session en 2000, le CIPM a approuvé
la déclaration de la 22^e^ session du CCEM
concernant la valeur de la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))).

[align=center]
*Recommandation 2*
(((volt (stem:["unitsml(V)"]))))

Le Comité international des poids et mesures,

*agissant* conformément aux instructions données dans la Résolution 6 de la 18^e^ Conférence
générale des poids et mesures concernant l’ajustement prévu des représentations du volt et de
l’ohm,

*considérant*

* que la plupart des étalons actuels de référence de résistance électrique présentent au cours du
temps des variations significatives,
* qu’un étalon de référence de résistance électrique fondé sur l’effet Hall quantique serait stable
et reproductible,
* qu’une étude approfondie des résultats des déterminations les plus récentes conduit à une
valeur de stem:[25812.807 "unitsml(Ohm)"] pour la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))), stem:[ii(R)_K], c’est-à-dire pour le quotient de la
tension de Hall par le courant correspondant au plateau de rang stem:[i = 1] dans l’effet Hall
quantique,
* que l’effet Hall quantique, avec cette valeur de stem:[ii(R)_K], peut être utilisé pour établir un étalon de
référence de résistance dont l’incertitude (écart-type), par rapport à l’ohm, est estimée stem:[2 xx 10^(-7)]
en valeur relative et dont la reproductibilité est nettement meilleure,

*recommande*

* que l’on adopte par convention, pour la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))), stem:[ii(R)_"K"], la valeur
stem:[ii(R)_{K-90} = 25812.807 "unitsml(Ohm)"] exactement,
* que cette valeur soit utilisée à partir du 1^er^ janvier 1990, et non auparavant, par tous les
laboratoires qui fondent sur l’effet Hall quantique leurs mesures de résistance électrique,
* qu’à partir de cette même date tous les autres laboratoires ajustent la valeur de leurs étalons de
référence pour la mettre en accord avec stem:[ii(R)_{K-90}],
* que, pour établir un étalon de référence de résistance électrique fondé sur l’effet Hall quantique,
les laboratoires suivent les conseils pour la mise en oeuvre de la résistance de Hall quantifiée
élaborés par le Comité consultatif d’électricité et publiés par les soins du Bureau international
des poids et mesures, dans leur édition la plus récente,

*et estime* qu’aucun changement de cette valeur recommandée de la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"]))))
ne sera nécessaire dans un avenir prévisible.


=== CIPM, 1989

==== L’Échelle internationale de température de 1990 (<<PV57, page=26>> et _Metrologia_, 1990, 27, 13)

NOTE: Le kelvin a été redéfini par
la CGPM à sa 26^e^ réunion en 2018 (Résolution 1,
_voir_ p.92).


[align=center]
*Recommandation 5*

Le Comité international des poids et mesures (CIPM), conformément à l’invitation formulée par
la 18^e^ Conférence générale des poids et mesures en 1987 (Résolution 7),
a adopté l’Échelle internationale de température de 1990 (EIT-90) en remplacement de l’Échelle
internationale pratique de température de 1968 (EIPT-68).

Le CIPM *souligne* que, par rapport à l’EIPT-68, l’EIT-90

* s’étend vers des températures plus basses, jusqu’à stem:[0.65 "unitsml(K)"], et remplace, de ce fait, aussi
l’Échelle provisoire de température de 1976 (EPT-76),
* est en bien meilleur accord avec les températures thermodynamiques correspondantes,
* a une continuité, une précision et une reproductibilité nettement améliorées sur toute son
étendue,
* comporte des sous-domaines et donne, dans certains domaines, des définitions équivalentes
qui facilitent grandement son utilisation.

Le CIPM *note* de plus, que le texte de l’EIT-90 sera accompagné de deux documents,
_Supplementary Information for the ITS-90_ et _Techniques for Approximating the ITS-90_,
qui seront publiés par le Bureau international des poids et mesures et remis à jour
périodiquement.

Le CIPM recommande

* que l’EIT-90 soit mise en application le 1^er^ janvier 1990,
* et que, à la même date, l’EIPT-68 et l’EPT-76 soient abrogées.


=== 19^e^ CGPM, 1991

==== Préfixes SI zetta, zepto, yotta et yocto (<<CR1991-4,page=97>> et _Metrologia_, 1992, 29, 3)

NOTE: Les noms zepto et zetta évoquent le chiffre sept
(septième puissance de stem:[10^3]) et la lettre «{nbsp}z{nbsp}»
remplace la lettre «{nbsp}s{nbsp}» pour éviter le double
emploi de la lettre «{nbsp}s{nbsp}» comme symbole. Les noms
yocto et yotta sont dérivés de octo, qui évoque le
chiffre huit (huitième puissance de stem:[10^3]){nbsp}; la lettre
«{nbsp}y{nbsp}» est ajoutée pour éviter l’emploi de la lettre
«{nbsp}o{nbsp}» comme symbole à cause de la confusion
possible avec le chiffre zéro.

[align=center]
*Résolution 4*

La 19^e^ Conférence générale des poids et mesures (CGPM),

*décide* d’ajouter à la liste des préfixes SI pour la formation des noms des multiples et
sous-multiples des unités, adoptée par la 11^e^ CGPM, Résolution 12, paragraphe 3,
la 12^e^ CGPM, Résolution 8 et la 15^e^ CGPM, Résolution 10, les préfixes suivants{nbsp}:

[cols="^,^,^",options="header,unnumbered"]
|===
| Facteur par lequel l’unité est multipliée | Préfixe | Symbole

| stem:[10^21] | zetta | Z
| stem:[10^(-21)] | zepto | z
| stem:[10^24] | yotta | Y
| stem:[10^{-24}] | yocto | y
|===


=== 20^e^ CGPM, 1995

=== Suppression de la classe des unités supplémentaires dans le SI (<<CR1995-8,page=121>> et _Metrologia_, 1996, 33, 83)

[align=center]
*Résolution 8*

La 20^e^ Conférence générale des poids et mesures,

*considérant*

* que la 11^e^ Conférence générale, en 1960, dans sa Résolution 12 établissant le Système
international d’unités, SI, a distingué trois classes d’unités, celle des unités de base,
celle des unités dérivées et celle des unités supplémentaires, cette dernière comprenant
seulement le radian et le stéradian,
* que le statut des unités supplémentaires par rapport aux unités de base et aux unités dérivées,
a donné lieu à des discussions,
* que le Comité international des poids et mesures (CIPM), en 1980, constatant que le statut
ambigu des unités supplémentaires compromet la cohérence interne du SI,
a interprété dans sa Recommandation 1 (CI-1980) les unités supplémentaires, dans le SI,
comme des unités dérivées sans dimension,

*approuvant* l’interprétation donnée par le CIPM en 1980,

*décide*

* d’interpréter les unités supplémentaires, dans le SI, c’est-à-dire le radian et le stéradian,
comme des unités dérivées sans dimension dont les noms et les symboles peuvent être
utilisés, mais pas nécessairement, dans les expressions d’autres unités dérivées SI, suivant les
besoins,
* et, par conséquent, de supprimer la classe des unités supplémentaires en tant que classe
séparée dans le SI.


=== 21^e^ CGPM, 1999

==== La définition du kilogramme (<<CR1999-7,page=141>>-<<CR1999-7,page=142>> et _Metrologia_, 2000, 37, 94)

[align=center]
*Résolution 7*

La 21^e^ Conférence générale des poids et mesures,

*considérant*

* le besoin d'assurer la stabilité à long terme du Système international d’unités (SI),
* l'incertitude intrinsèque relative à la stabilité à long terme du prototype qui sert à définir l'unité
de masse, l'une des unités de base du SI,
* que cette incertitude se répercute sur la stabilité à long terme des trois autres unités de base du
SI, nommément l'ampère(((ampère (stem:["unitsml(A)"])))), la mole et la candela(((candela (stem:["unitsml(cd)"])))), dont la définition dépend de celle du
kilogramme,
* les progrès déjà obtenus dans différentes expériences destinées à relier l'unité de masse à des
constantes fondamentales ou atomiques,
* qu'il est souhaitable de disposer de plusieurs méthodes pour réaliser ce lien,

*recommande* que les laboratoires nationaux poursuivent leurs efforts pour affiner les
expériences qui relient l'unité de masse à des constantes fondamentales ou atomiques et qui
pourraient, dans l'avenir, servir de base à une nouvelle définition du kilogramme.


==== Nom spécial donné à l'unité SI mole par seconde, le katal, pour exprimer l'activité catalytique (<<CR1999-12,page=145>> et _Metrologia_, 2000, 37, 95)

[align=center]
*Résolution 12*

La 21^e^ Conférence générale des poids et mesures,

*considérant*

* l'importance pour la santé humaine et la sécurité de faciliter l'emploi des unités du Système
international d’unités (SI) dans les domaines de la médecine et de la biochimie,
* qu'une unité en dehors du SI appelée «{nbsp}unité{nbsp}» représentée par le symbole U, qui est égale à
stem:[1] stem:["unitsml(umol*min^(-1))"], et qui n'est pas cohérente avec le SI, a été largement répandue en médecine et
en biochimie depuis 1964 pour exprimer l'activité catalytique,
* que l'absence d'un nom spécial pour désigner l'unité dérivée et cohérente du SI qu'est la mole
par seconde a conduit à ce que des résultats de mesures cliniques soient donnés en
différentes unités locales,
* que l'emploi des unités SI en médecine et en chimie clinique est vivement recommandé par les
unions internationales de ces domaines,
* que la Fédération internationale de chimie clinique et médecine de laboratoire a demandé au
Comité consultatif des unités de recommander le nom spécial katal, symbole stem:["unitsml(kat)"], pour l'unité SI
mole par seconde,
* que tandis que la prolifération de noms spéciaux représente un danger pour le SI,
il existe des exceptions pour certains sujets liés à la santé humaine et à la sécurité
(15^e^ Conférence générale, 1975, Résolutions 8 et 9, 16^e^ Conférence générale, 1979,
Résolution 5),

*notant* que le nom katal, symbole stem:["unitsml(kat)"], est utilisé pour l'unité SI mole par seconde depuis plus de
trente ans, pour exprimer l'activité catalytique,

*décide* d'adopter le nom spécial katal, symbole stem:["unitsml(kat)"], pour l'unité SI mole par seconde pour
exprimer l'activité catalytique, particulièrement dans les domaines de la médecine et de la
biochimie,

et *recommande* que, lorsque le katal est utilisé, le mesurande soit spécifié en faisant référence
au mode opératoire de mesure{nbsp}; le mode opératoire de mesure doit mentionner le produit
indicateur de la réaction mesurée.


=== CIPM, 2001

==== «{nbsp}unités SI{nbsp}» et «{nbsp}unités du SI{nbsp}» (<<PV69, page=38-39>>)

Le Comité international a approuvé en 2001 la proposition suivante du CCU concernant les
«{nbsp}unités SI{nbsp}» et les «{nbsp}unités du SI{nbsp}»{nbsp}:

«{nbsp}Nous suggérons que les termes «{nbsp}unité SI{nbsp}» et «{nbsp}unité du SI{nbsp}» fassent tous deux référence aux
unités de base et aux unités cohérentes dérivées, ainsi qu’à toutes les unités obtenues en les
combinant aux préfixes recommandés des multiples et sous-multiples.

Nous suggérons que le terme «{nbsp}unité cohérente du SI{nbsp}» soit utilisé quand nous désirons
restreindre son sens aux seules unités de base et aux unités cohérentes dérivées du SI.{nbsp}»


=== CIPM, 2002

==== Révision de la mise en pratique de la définition du mètre (<<PV70, page=90-101>> et _Metrologia_, 40, 103-133)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*rappelant*

* qu’en 1983 la 17^e^ Conférence générale des poids et mesures (CGPM) a adopté une nouvelle
définition du mètre,
* qu’à la même date la Conférence générale a invité le Comité international des poids et mesures
(CIPM)
** à établir des instructions pour la réalisation pratique de la nouvelle définition du mètre
(la mise en pratique),
** à choisir des radiations qui puissent être recommandées comme étalons de longueur
d'onde pour la mesure interférentielle des longueurs et à établir des instructions pour leur
emploi,
** à poursuivre les études entreprises pour améliorer ces étalons et à compléter ou réviser
par la suite ces instructions,
* qu’en réponse à cette invitation le CIPM a adopté la Recommandation 1 (CI-1983) (mise en
pratique de la définition du mètre) avec pour effet
** que le mètre soit réalisé par l’une des méthodes suivantes{nbsp}:
+
--
. au moyen de la longueur stem:[l] du trajet parcouru dans le vide par une onde électromagnétique
plane pendant la durée t{nbsp}; cette longueur est obtenue à partir de la mesure de la durée stem:[t], en
utilisant la relation stem:[l = c_0 cdot t] et la valeur de la ((vitesse de la lumière dans le vide))
stem:[c_0 = 299792458 "unitsml(m/s)"],
. au moyen de la longueur d’onde dans le vide stem:[lambda] d’une onde électromagnétique plane de
fréquence f{nbsp}; cette longueur d’onde est obtenue à partir de la mesure de la fréquence f, en
utilisant la relation stem:[lambda = c_0 // f] et la valeur de la ((vitesse de la lumière dans le vide))
stem:[c_0 = 299792458 "unitsml(m/s)"],
. au moyen de l’une des radiations de la liste ci-dessous, radiations pour lesquelles on peut
utiliser la valeur donnée de la longueur d’onde dans le vide ou de la fréquence, avec
l’incertitude indiquée, pourvu que l’on observe les conditions spécifiées et le mode opératoire
reconnu comme approprié{nbsp};

** que dans tous les cas les corrections nécessaires soient appliquées pour tenir compte
des conditions réelles telles que diffraction, gravitation ou imperfection du vide{nbsp};

** que dans le contexte de la relativité générale, le mètre est considéré comme une unité de
longueur propre. Sa définition s’applique donc seulement dans un domaine spatial
suffisamment petit, pour lequel les effets de la non-uniformité du champ gravitationnel
peuvent être ignorés (notons, qu’à la surface de la Terre, cet effet est d’environ stem:[1 xx 10^(-16)]
par mètre d’altitude en valeur relative). Dans ce cas, les seuls effets à prendre en compte
sont ceux de la relativité restreinte. Les méthodes locales, préconisées en b) et c) pour
réaliser le mètre, fournissent le mètre propre, mais la méthode préconisée en a) ne le
permet pas nécessairement. La méthode préconisée en a) devrait donc être restreinte
aux longueurs l suffisamment courtes pour que les effets prévus par la relativité générale
soient négligeables par rapport aux incertitudes de mesure. Si ce n’est pas le cas,
il convient de se référer au rapport du Groupe de travail du Comité consultatif du temps
et des fréquences (CCTF) sur l’application de la relativité générale à la métrologie pour
l’interprétation des mesures (Application of general relativity to metrology, _Metrologia_,
1997, *34*, 261-290),
--
* que le CIPM avait recommandé une liste de radiations à cet effet{nbsp};

*rappelant* aussi qu’en 1992 et en 1997 le CIPM a révisé la mise en pratique de la définition du
mètre{nbsp};

considérant

* que la science et les techniques continuent à exiger une meilleure exactitude dans la réalisation
du mètre{nbsp};
* que, depuis 1997, les travaux effectués dans les laboratoires nationaux, au BIPM et dans
d’autres laboratoires ont permis d’identifier de nouvelles radiations et des méthodes pour leur
mise en oeuvre qui conduisent à de plus faibles incertitudes{nbsp};
* que l’on s’oriente de plus en plus vers des fréquences optiques pour les activités liées au
temps, et que l’on continue à élargir le domaine d’application des radiations recommandées
dans la mise en pratique, non seulement à la métrologie dimensionnelle et à la réalisation du
mètre, mais aussi à la spectroscopie de haute résolution, à la physique atomique et
moléculaire, aux constantes fondamentales et aux télécommunications{nbsp};
* que l’on dispose maintenant d’un certain nombre de nouvelles valeurs plus exactes de
l’incertitude des fréquences de radiations d’atomes et d’ions refroidis très stables déjà
mentionnées dans la liste de radiations recommandées, que la valeur de la fréquence de la
radiation de plusieurs espèces d’atomes et d’ions refroidis a aussi été mesurée récemment, et
que de nouvelles valeurs améliorées, et présentant des incertitudes réduites de manière
significative, d’un certain nombre d’étalons de fréquence optique fondés sur des cuves à gaz
ont été déterminées, y compris dans le domaine des longueurs d’ondes pour les
télécommunications optiques{nbsp};
* que les nouvelles techniques de peigne à impulsions femtosecondes ont un intérêt manifeste
pour relier la fréquence des étalons de fréquence optique très stables à celle des étalons de
fréquence utilisés pour la réalisation de la seconde du Système international d’unités (SI), que
ces techniques de mesure sont un moyen commode pour assurer la traçabilité au SI et peuvent
fournir aussi bien des sources de fréquence que des techniques de mesure{nbsp};


*reconnaît* que les techniques de peigne arrivent au moment opportun et sont appropriées, et
recommande de poursuivre les recherches pour étudier leurs possibilités{nbsp};

*accueille favorablement* les essais de validation en cours des techniques de peigne effectués
par comparaison avec les autres techniques de chaînes de fréquence{nbsp};

*encourage* les laboratoires nationaux de métrologie et les autres laboratoires à poursuivre les
études sur les techniques de peigne au plus haut niveau d’exactitude possible et à rechercher la
simplicité pour encourager leur mise en pratique la plus étendue{nbsp};
recommande

* que la liste des radiations recommandées donnée par le CIPM en 1997 (Recommandation 1
(CI-1997)) soit remplacée par la liste de radiations ci-dessous*, qui inclut{nbsp};
+
--
NOTE: La liste des radiations
recommandées, Recommandation 1
(CI-2002), figure dans les <<PV70, page=93-101>> et dans
_Metrologia_, 2003, 40, 104-115.
--

** des valeurs mises à jour de la fréquence des atomes de calcium et d’hydrogène refroidis
et de l’ion piégé de strontium,
** la valeur de la fréquence de nouvelles espèces d’ions refroidis, y compris de l’ion piégé
de stem:["Hg"^+], de l’ion piégé d’In^+^, et de l’ion piégé d’Yb^+^,
** des valeurs mises à jour de la fréquence de lasers asservis sur le rubidium, de lasers à
grenat d’yttrium-aluminium dopé au néodyme (Nd{nbsp}:YAG) et de lasers à hélium-néon
(He-Ne) asservis sur l’iode, de lasers à hélium-néon asservis sur le méthane, et de lasers
à dioxyde de carbone asservis sur le tétroxyde d’osmium à stem:[10] stem:["unitsml(um)"],
** des valeurs de la fréquence d’étalons pour les télécommunications optiques, y compris
les lasers asservis sur le rubidium et l’acétylène.

&#x200c;. . .

NOTE: La liste des radiations recommandées, Recommandation 1
(CI-2002), figure dans les <<PV70, page=93-101>> et dans
_Metrologia_, 2003, 40, 104-115.


==== Équivalent de dose (<<PV70, page=102>>)

NOTE: _Voir_ aussi _J. Radiol. Prot._, 2005, 25, 97-100.

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures,

considérant que

* la définition actuelle de l’unité SI d’équivalent de dose (sievert) comprend un facteur «{nbsp}N{nbsp}»
(produit de tous les autres facteurs de multiplication) prescrit par l’International Commission on
Radiological Protection (ICRP),
* l’ICRP et l’International Commission on Radiation Units and Measurements (ICRU) ont décidé
de supprimer ce facteur N qui n’est plus considéré comme nécessaire,
* la définition actuelle de l’équivalent de dose stem:[ii(H)] dans le Système international d’unités, qui
comprend le facteur N, porte à confusion,

*décide* de modifier l’explication donnée dans la Brochure sur «{nbsp}Le Système International
d'Unités (SI){nbsp}» de la manière suivante{nbsp}:

La grandeur équivalent de dose stem:[ii(H)] est le produit de la dose absorbée stem:[ii(D)] de rayonnements
ionisants et du facteur sans dimension stem:[ii(Q)] (facteur de qualité) prescrit par l’ICRU, facteur défini
en fonction du transfert d’énergie linéaire{nbsp}:

[stem%unnumbered]
++++
ii(H) = ii(Q) * ii(D)
++++

Ainsi, pour une radiation donnée, la valeur numérique de H en joules par kilogramme peut être
différente de la valeur de stem:[ii(D)] en joules par kilogramme, puisqu’elle
est fonction de la valeur de stem:[ii(Q)].

Le Comité *décide* donc de maintenir la dernière phrase de l’explication sous la forme suivante{nbsp}:

Afin d’éviter tout risque de confusion entre la dose absorbée stem:[ii(D)] et l’équivalent de dose H,
il faut employer les noms spéciaux pour les unités correspondantes, c’est-à-dire qu’il faut utiliser
le nom gray au lieu de joule par kilogramme pour l’unité de dose absorbée stem:[ii(D)] et le nom sievert
au lieu de joule par kilogramme pour l’unité d’équivalent de dose stem:[ii(H)].


=== CIPM, 2003

==== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (<<PV71, page=70>> et _Metrologia_, 2004, 41, 99-100)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

considérant que

* l’on dispose depuis peu de meilleures valeurs des fréquences des radiations de certains
étalons à ions refroidis très stables, déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a déterminé de meilleures valeurs des fréquences des étalons de fréquence optique dans
l’infrarouge, fondés sur des cuves à gaz, dans le domaine des télécommunications optiques,
valeurs déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a effectué récemment et pour la première fois des mesures de fréquence à l’aide de
peignes à impulsions femtosecondes de certains étalons fondés sur des cuves à iode, qui
figurent sur la liste complémentaire de radiations recommandées, mesures qui conduisent à
une réduction considérable de l’incertitude{nbsp};

*propose* que la liste des radiations recommandées soit révisée pour inclure{nbsp}:

* les valeurs mises à jour des fréquences de la transition quadripolaire de l’ion piégé de ^88^Sr^\+^ et
de la transition octupolaire de l’ion piégé de ^171^Yb^+^{nbsp};
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’acétylène à stem:[1.54 "unitsml(um)"]{nbsp};
* des valeurs mises à jour de la fréquence d’étalons asservis sur l’iode à stem:[543 "unitsml(nm)"] et à stem:[515 "unitsml(nm)"].


=== 22^e^ CGPM, 2003

==== Symbole du séparateur décimal (<<CR2003-10,page=169>> et _Metrologia_, 2004, 41, 104)

[align=center]
*Résolution 10*

La 22^e^ Conférence générale des poids et mesures,

considérant que

* l’un des principaux objectifs du Système international d’unités (SI) est de permettre d’exprimer
la valeur des grandeurs d’une manière aisément compréhensible dans le monde entier,
* la valeur d’une grandeur est normalement exprimée par un nombre qui multiplie une unité,
* souvent le nombre utilisé pour exprimer la valeur d’une grandeur contient plusieurs chiffres,
avec une partie entière et une partie décimale,
* la 9^e^ Conférence générale dans sa Résolution 7 (1948) avait décidé que «{nbsp}Dans les nombres,
la virgule (usage français) ou le point (usage britannique) sont utilisés seulement pour séparer
la partie entière des nombres de leur partie décimale{nbsp}»,
* conformément à la décision du Comité international des poids et mesures lors de sa
86^e^ session (1997), le Bureau international des poids et mesures utilise maintenant le point
(sur la ligne) comme séparateur décimal dans toutes les versions en anglais de ses
publications, y compris dans le texte anglais de la Brochure sur le SI (la référence internationale
sur le SI), tout en continuant à utiliser la virgule (sur la ligne) comme séparateur décimal dans
toutes ses publications en français,
* néanmoins certaines organisations internationales utilisent la virgule sur la ligne comme
séparateur décimal dans leurs documents en anglais,
* de plus, certaines organisations internationales, y compris certaines organisations
internationales de normalisation, spécifient que le séparateur décimal doit être la virgule sur la
ligne, dans toutes les langues,
* la recommandation d’utiliser la virgule sur la ligne comme séparateur décimal est, dans de
nombreuses langues, en conflit avec l’usage courant, qui consiste à utiliser le point sur la ligne,
* le fait d’utiliser le point sur la ligne ou la virgule sur la ligne comme séparateur décimal n’est pas
toujours lié à la langue, car certains pays de même langue maternelle ont des usages
différents, alors que d’autres pays pratiquant le plurilinguisme utilisent le point sur la ligne ou la
virgule sur la ligne suivant la langue,

*déclare* que le symbole du séparateur décimal pourra être le point sur la ligne ou la virgule sur
la ligne,

*réaffirme* que «{nbsp}Pour faciliter la lecture, les nombres peuvent être partagés en tranches de trois
chiffres{nbsp}; ces tranches ne sont jamais séparées par des points, ni par des virgules{nbsp}», comme le
recommande la Résolution 7 de la 9^e^ Conférence générale de 1948.


=== CIPM, 2005

==== Clarification de la définition du kelvin, unité de température thermo-dynamique (<<PV73, page=119>> et _Metrologia_, 2006, 43, 177-178)

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion
en 2018 (Résolution 1, _voir_ p.92).


[align=center]
*Recommandation 2*

Le Comité international des poids et mesures (CIPM),

*considérant*

* que le kelvin, l’unité de température thermodynamique, est défini par la fraction stem:[1//273.16] de la
température thermodynamique du point triple de l’eau,
* que la température du point triple de l’eau dépend des abondances relatives des isotopes de
l’hydrogène et de l’oxygène présents dans l’échantillon d’eau utilisé,
* que cet effet est maintenant l’une des sources majeures d’écarts observés entre les différentes
réalisations du point triple de l’eau,

*décide*

* que la définition du kelvin se réfère à une eau de composition isotopique spécifiée,
* que cette composition isotopique de l’eau soit la suivante{nbsp}:
+
--
stem:[0.00015576] mole de ^2^H par mole de ^1^H, +
stem:[0.0003799] mole de ^17^O par mole de ^16^O, et +
stem:[0.0020052] mole de ^18^O par mole de ^16^O,
--

cette composition étant celle du matériau de référence de l’Agence internationale de l’énergie
atomique «{nbsp}Vienna Standard Mean Ocean Water (VSMOW){nbsp}», recommandée par l’Union
internationale de chimie pure et appliquée dans «{nbsp}Atomic Weights of the Elements{nbsp}: Review
2000{nbsp}»,

* que cette composition soit définie dans une note attachée à la définition du kelvin dans la
Brochure sur le SI de la manière suivante{nbsp}:
+
--
«{nbsp}Cette définition se réfère à l’eau de composition isotopique définie par les rapports de
quantité de matière suivants{nbsp}: stem:[0.00015576] mole de ^2^H par mole de ^1^H, stem:[0.0003799] mole de
^17^O par mole de ^16^O et stem:[0.0020052] mole de ^18^O par mole de ^16^O{nbsp}».
--


==== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (<<PV73, page=120>> et _Metrologia_, 2006, 43, 178)

[align=center]
*Recommandation 3*

Le Comité international des poids et mesures,

*considérant que*

* l’on dispose de meilleures valeurs des fréquences des radiations de certains étalons à ion ou à
atomes refroidis très stables, déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a déterminé de meilleures valeurs des fréquences des étalons de fréquence optique,
fondés sur des cuves à gaz, dans le domaine des télécommunications optiques, dans
l’infrarouge, valeurs déjà publiées dans la liste des radiations recommandées{nbsp};
* l’on a déterminé de meilleures valeurs des fréquences de certains étalons fondés sur des cuves
à iode, valeurs déjà publiées dans la liste complémentaire des sources recommandées{nbsp};
* l’on a effectué pour la première fois des mesures de la fréquence de nouveaux atomes
refroidis, d’atomes dans la région de l’infrarouge proche et de molécules dans le domaine des
télécommunications optiques, à l’aide de peignes à impulsions femtosecondes{nbsp};

*décide* que la liste des radiations recommandées soit révisée pour y inclure{nbsp}:

* les valeurs mises à jour des fréquences des transitions quadripolaires de l’ion piégé de ^88^Sr^\+^,
de l’ion piégé de ^199^Hg^+^ et de l’ion piégé de ^171^Yb^+^{nbsp};
* la valeur mise à jour de la fréquence de la transition de l’atome de calcium{nbsp};
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’acétylène à stem:[1.54 "unitsml(um)"]{nbsp};
* la valeur mise à jour de la fréquence de l’étalon asservi sur l’iode à stem:[515 "unitsml(nm)"]{nbsp};
* la fréquence de la transition de l’atome de ^87^Sr à stem:[698 "unitsml(nm)"]{nbsp};
* les fréquences des transitions de l’atome de ^87^Rb autour de stem:[760 "unitsml(nm)"]{nbsp};
* les fréquences des transitions de la bande (stem:[ii(nu)_1 + ii(nu)_3]) de ^12^C~2~H~2~, et des bandes (stem:[ii(nu)_1 + ii(nu)_3]) et
(stem:[ii(nu)_1 + ii(nu)_3 + ii(nu)_4 + ii(nu)_5]) de ^13^C~2~H~2~, autour de stem:[1.54 "unitsml(um)"].


=== CIPM, 2006

==== Au sujet des représentations secondaires de la seconde (<<PV74, page=123>> et _Metrologia_, 2007, 44, 97)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune de «{nbsp}valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde{nbsp}» est à établir,
* que le Groupe de travail commun au Comité consultatif des longueurs (CCL) et au CCTF sur
la mise en pratique de la définition du mètre et sur les représentations secondaires de la
seconde, lors de sa réunion au Bureau international des poids et mesures (BIPM) en
septembre 2005, a discuté des fréquences des radiations candidates potentielles en vue de
leur inclusion dans la liste des représentations secondaires de la seconde,
* que le Groupe de travail commun au CCL et au CCTF a examiné et mis à jour les valeurs
des fréquences des transitions de l’ion de mercure (Hg), de l’ion de strontium (Sr), de l’ion
d’ytterbium (Yb) et de l’atome neutre de strontium lors de sa session de septembre 2006,
* que le CCTF avait déjà recommandé dans sa Recommandation CCTF 1 (2004) la fréquence
de la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de 87Rb
comme représentation secondaire de la seconde,

*recommande* que les fréquences des transitions suivantes soient utilisées comme
représentations secondaires de la seconde et soient intégrées à la nouvelle liste des «{nbsp}valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde{nbsp}»

* la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb, à la
fréquence de f^87^~Rb~ stem:[= 6834682610.904324 "unitsml(Hz)"], avec une incertitude-type relative estimée de
stem:[3 xx 10^(-15)],
* la transition optique non perturbée 5s ^2^S~1/2~ – 4d ^2^D~5/2~ de l’ion de ^88^Sr^\+^, à la fréquence de
f^88^Sr^+^ stem:[= 444779044095484 "unitsml(Hz)"], avec une incertitude-type relative estimée de stem:[7 xx 10^(-15)],
* la transition optique non perturbée
5d^10^ 6s ^2^S~1/2~ (stem:[F = 0]) – 5d^9^ 6s^2^ ^2^D~5/2~ (stem:[F = 2]) de l’ion de
^199^Hg^\+^, à la fréquence de f^199^Hg^+^ stem:[= 1064721609899145 "unitsml(Hz)"], avec une incertitude-type
relative estimée de stem:[3 xx 10^(-15)],
* la transition optique non perturbée 6s ^2^S~1/2~ (F = 0) – 5d ^2^D~3/2~ (F = 2) de l’ion de ^171^Yb^\+^, à la
fréquence de f^171^Yb^+^ stem:[= 688358979309308 "unitsml(Hz)"], avec une incertitude-type relative estimée
de stem:[9 xx 10^(-15)],
* la transition optique non perturbée 5s^2^ ^1^S0 – 5s 5p ^3^P0 de l’atome neutre de ^87^Sr, à la
fréquence de f^87^~Sr~ stem:[= 429228004229877 "unitsml(Hz)"], avec une incertitude-type relative estimée de
stem:[1.5 xx 10^(-14)]



=== CIPM, 2007

==== Révision de la liste des radiations recommandées pour la mise en pratique de la définition du mètre (<<PV75, page=85>>)

[align=center]
*Recommandation 1*

Le Comité international des poids et mesures,

*considérant* que

* l’on a déterminé des valeurs plus précises des fréquences de molécules dans le domaine des
télécommunications optiques, valeurs déjà publiées dans la liste des fréquences étalons,
à l’aide de peignes à impulsions femtosecondes{nbsp};
* l’on a déterminé, pour la première fois, les fréquences de molécules dans le domaine des
télécommunications optiques, à l’aide de peignes à impulsions femtosecondes{nbsp};
* l’on a déterminé, pour la première fois, les fréquences de certaines transitions dans l’iode,
en cellule, transitions proches de la radiation émise par l’étalon de fréquence optique à
stem:[532 "unitsml(nm)"], à l’aide de peignes à impulsions femtosecondes{nbsp};

*propose* que la liste des fréquences étalons soit révisée pour y inclure{nbsp}:

* les valeurs mises à jour des fréquences de la bande (stem:[ii(nu)_1 + ii(nu)_3]) de ^12^C~2~H~2~, autour de stem:[1.54 "unitsml(um)"]{nbsp};

* les valeurs des fréquences de la bande (stem:[2_{ii(nu)_1}]) de ^12^C~2~HD, autour de stem:[1.54 "unitsml(um)"]{nbsp};

* les valeurs des fréquences des composantes hyperfines des transitions P(142) 37-0,
R(121) 35-0 et R(85) 33-0 dans l’iode à stem:[532 "unitsml(nm)"].


=== 23^e^ CGPM, 2007

==== Sur la révision de la mise en pratique de la définition du mètre et sur la mise au point de nouveaux étalons optiques de fréquence (<<CR2007-9,page=171>>)

[align=center]
*Résolution 9*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* les progrès rapides et les améliorations importantes des performances des étalons optiques
de fréquence,
* que les techniques des peignes à impulsions femtosecondes sont maintenant couramment
utilisées pour relier les radiations optiques et micro-ondes dans un même lieu,
* que les laboratoires nationaux de métrologie travaillent à des techniques de comparaison
d’étalons optiques de fréquence sur de courtes distances,
* que des techniques de comparaison à distance doivent être élaborées au niveau international
afin de pouvoir comparer les étalons optiques de fréquence,

*accueille favorablement*

* les activités du Groupe de travail commun au Comité consultatif des longueurs et au Comité
consultatif du temps et des fréquences pour examiner les fréquences des représentations de
la seconde fondées sur des fréquences optiques,
* les ajouts à la mise en pratique de la définition du mètre des radiations recommandées
approuvées par le Comité international des poids et mesures en 2002, 2003, 2005, 2006 et
2007,
* l’initiative prise par le Bureau international des poids et mesures (BIPM) de s’interroger sur le
moyen de comparer les étalons optiques de fréquence,

*recommande* que

* les laboratoires nationaux de métrologie engagent les ressources nécessaires à la mise au
point d’étalons optiques de fréquence et à leur comparaison,
* le BIPM oeuvre à la coordination d’un projet international auquel participeraient les
laboratoires nationaux de métrologie, projet orienté vers l’étude des techniques qui pourraient
servir à comparer les étalons optiques de fréquence.


==== Sur la clarification de la définition du kelvin, unité de température thermodynamique (<<CR2007-10,page=172>>)

NOTE: Le kelvin a été redéfini par la CGPM à sa 26^e^ réunion
en 2018 (Résolution 1, _voir_ p. 92).

[align=center]
*Résolution 10*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* que le kelvin, l’unité de température thermodynamique, est défini par la fraction stem:[1//273.16] de
la température thermodynamique du point triple de l’eau,
* que la température du point triple de l’eau dépend des abondances relatives des isotopes de
l’hydrogène et de l’oxygène présents dans l’échantillon d’eau utilisé,
* que cet effet est maintenant l’une des sources majeures d’écarts observés entre les
différentes réalisations du point triple de l’eau,

*prend acte de, et accueille favorablement*, la décision du Comité international en octobre
2005, sur l’avis du Comité consultatif de thermométrie, selon laquelle

* la définition du kelvin se réfère à une eau de composition isotopique spécifiée

* cette composition isotopique de l’eau est la suivante{nbsp}:
+
--
stem:[0.00015576] mole de ^2^H par mole de ^1^H, +
stem:[0.0003799] mole de ^17^O par mole de ^16^O, et +
stem:[0.0020052] mole de ^18^O par mole de ^16^O,

cette composition étant celle du matériau de référence de l’Agence internationale de l’énergie
atomique «{nbsp}Vienna Standard Mean Ocean Water (VSMOW){nbsp}», recommandée par l’Union
internationale de chimie pure et appliquée dans «{nbsp}Atomic Weights of the Elements{nbsp}: Review
2000{nbsp}»,
--

* cette composition est définie dans une note attachée à la définition du kelvin dans la
Brochure sur le Système international d’unités de la manière suivante{nbsp}:
+
--
«{nbsp}Cette définition se réfère à l’eau de composition isotopique définie par les rapports de quantité
de matière suivants{nbsp}: stem:[0.00015576] mole de ^2^H par mole de ^1^H, stem:[0.0003799] mole de ^17^O par
mole de ^16^O et stem:[0.0020052] mole de ^18^O par mole de ^16^O{nbsp}».
--


==== Sur l’éventuelle redéfinition de certaines unités de base du Système international d’unités (SI) (<<CR2007-12,page=174>>)

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la
révision du SI (Résolution 1, _voir_ p. 92).

[align=center]
*Résolution 12*

La 23^e^ Conférence générale des poids et mesures,

*considérant*

* que les laboratoires nationaux de métrologie et le Bureau international des poids et mesures
(BIPM) ont consacré des efforts considérables depuis de nombreuses années en vue de
promouvoir et d’améliorer le Système international d’unités (SI), en repoussant les limites de
la métrologie, afin de définir les unités de base du SI en fonction de constantes de la nature –
les constantes physiques fondamentales,

* que parmi les sept unités de base du SI, seul le kilogramme est encore défini à partir d’un
objet matériel (artefact), à savoir le prototype international du kilogramme (2^e^ CGPM, 1889 et
3^e^ CGPM, 1901), et que les définitions de l’ampère(((ampère (stem:["unitsml(A)"])))), de la mole et de la candela(((candela (stem:["unitsml(cd)"])))) dépendent du
kilogramme,

* la 21^e^ Conférence générale a adopté en 1999 la Résolution 7, laquelle recommandait que
«{nbsp}les laboratoires nationaux poursuivent leurs efforts pour affiner les expériences qui relient
l’unité de masse à des constantes fondamentales ou atomiques et qui pourraient, dans
l’avenir, servir de base à une nouvelle définition du kilogramme{nbsp}»,

* de nombreux progrès ont été réalisés ces dernières années pour relier la masse du prototype
international à la constante de Planck(((constante, de Planck))), stem:[h], ou à la constante d’Avogadro, stem:[ii(N)_"A"],

* les initiatives prises pour déterminer la valeur d’un certain nombre de constantes
fondamentales, y compris celle de la constante de Boltzmann stem:[k_B],

* que des implications significatives et des avantages potentiels découlent de nouvelles
définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et de la mole, suite aux progrès récents
accomplis,

* la Recommandation 1 (CI-2005) du Comité international adoptée lors de sa session d’octobre
2005 et diverses recommandations des Comités consultatifs sur la redéfinition d’une ou
plusieurs unités de base du SI,

*notant*

* que les changements dans les définitions des unités du SI doivent être cohérents,

* que les définitions des unités de base du SI doivent être faciles à comprendre,

* le travail effectué par le Comité international et par ses Comités consultatifs,

* la nécessité de contrôler les résultats des expériences,

* l’importance de solliciter les commentaires et les contributions de la vaste communauté des
scientifiques et des utilisateurs,

* la décision du Comité international en 2005 d’approuver, en principe, la préparation de
nouvelles définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et la possibilité de redéfinir la
mole,

*recommande* que les laboratoires nationaux de métrologie et le BIPM

* poursuivent les expériences appropriées afin que le Comité international puisse juger s’il est
possible ou non de redéfinir le kilogramme, l’ampère(((ampère (stem:["unitsml(A)"])))), le kelvin et la mole en utilisant des
valeurs fixées pour certaines constantes fondamentales lors de la 24^e^ Conférence générale
en 2011,

* réfléchissent, en collaboration avec le Comité international, ses Comités consultatifs et les
groupes de travail concernés, aux moyens pratiques de réaliser les nouvelles définitions
fondées sur des valeurs fixées de constantes fondamentales, préparent une mise en pratique
de chacune d’elles, et examinent quel est le moyen le plus approprié pour expliquer les
nouvelles définitions aux utilisateurs,

* suscitent des campagnes de sensibilisation pour alerter les communautés d’utilisateurs sur
l’éventualité de nouvelles définitions afin que leurs implications techniques et juridiques, ainsi
que leurs réalisations pratiques, soient discutées et examinées avec soin,

*et demande* au Comité international de présenter un rapport à ce sujet à la 24^e^ Conférence
générale en 2011 et d’entreprendre tous les préparatifs qu’il considère comme nécessaires de
manière à ce que, si les résultats des expériences sont jugés convenables et les besoins des
utilisateurs satisfaits, il puisse être officiellement proposé à la 24^e^ Conférence générale
d’approuver de nouvelles définitions du kilogramme, de l’ampère, du kelvin et de la mole.


=== CIPM, 2009

==== Mises à jour de la liste des fréquences étalons (<<PV77, page=105>>)

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures (CIPM),

considérant

* qu’une liste commune des «{nbsp}valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde{nbsp}» a été établie{nbsp};

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste{nbsp};
recommande
que les fréquences de transition suivantes soient incluses ou mises à jour dans la liste des
fréquences étalons recommandées{nbsp}:

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s 5p ^3^P~0~ de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f = 429228004229873.7 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1 xx 10^(-15)] (cette radiation a déjà été approuvée par le CIPM comme représentation secondaire
de la seconde){nbsp};

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s 5p ^3^P~0~ de l’atome neutre de ^88^Sr,
à la fréquence de stem:[f = 429228066418012 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1 xx 10^(-14)]{nbsp};

* la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f = 411042129776393 "unitsml(Hz)"], avec une incertitude-type relative de stem:[4 xx 10^(-14)]{nbsp};

* la transition optique non perturbée ^2^S~1/2~ (F = 0) – ^2^F~7/2~ (F = 3, ~mF~ = 0) de l’ion de ^171^Yb^+^, à la
fréquence de stem:[f = 642121496772657 "unitsml(Hz)"], avec une incertitude-type relative de stem:[6 xx 10^(-14)]{nbsp};

* la transition optique non perturbée 6s^2^ ^1^S~0~ (F = 1/2) – 6s 6p ^3^P~0~ (F = 1/2) de l’atome neutre de
^171^Yb à la fréquence de stem:[f = 518295836590864 "unitsml(Hz)"], avec une incertitude-type relative de
stem:[1.6 xx 10^(-13)].


=== 24^e^ CGPM, 2011

==== Sur l’éventuelle révision à venir du Système international d’unités, le SI (<<CR2011-1,page=212>>)

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la
révision du SI (Résolution 1, _voir_ p. 92).

[align=center]
*Résolution 1*

La Conférence générale des poids et mesures (CGPM), à sa 24^e^ réunion,

*considérant*

* qu’il existe un consensus international sur l’importance, la valeur et les bénéfices potentiels de la
redéfinition d’un certain nombre d’unités du Système international d’unités (SI),

* que les laboratoires nationaux de métrologie et le Bureau international des poids et mesures
(BIPM) ont, à juste titre, déployé des efforts considérables au cours de ces dernières
décennies afin de faire progresser le Système international d’unités (SI),
en repoussant les limites de la métrologie, de façon à ce que les unités de base du SI
puissent être définies en s’appuyant sur les constantes de la nature – les constantes
physiques fondamentales ou les propriétés des atomes,

* qu’un exemple marquant du succès de ces efforts est la définition actuelle de l’unité de
longueur du SI, le mètre (17^e^ réunion de la CGPM, 1983, Résolution 1), qui relie l’unité à une
valeur exacte de la ((vitesse de la lumière dans le vide)) stem:[c], à savoir 299792458 mètres par
seconde,

* que parmi les sept unités de base du SI, seul le kilogramme est encore défini à partir d’un
objet matériel (artefact), à savoir le prototype international du kilogramme (1^re^ réunion de la
CGPM, 1889{nbsp}; 3^e^ réunion de la CGPM, 1901), et que les définitions de l’ampère(((ampère (stem:["unitsml(A)"])))), de la mole et
de la candela(((candela (stem:["unitsml(cd)"])))) dépendent du kilogramme,

* que, bien que le prototype international ait rendu des services à la science et la technologie
depuis qu’il a été sanctionné par la CGPM lors de sa 1re réunion en 1889, son utilisation
présente des limites importantes, l’une des plus significatives étant que sa masse n’est pas
explicitement reliée à une constante de la nature et que, par conséquent, sa stabilité à long
terme ne peut être garantie,

* que la CGPM, lors de sa 21^e^ réunion en 1999, a adopté la Résolution 7, laquelle recommande
que «{nbsp}les laboratoires nationaux poursuivent leurs efforts pour affiner les expériences qui relient
l’unité de masse à des constantes fondamentales ou atomiques et qui pourraient, dans l’avenir,
servir de base à une nouvelle définition du kilogramme{nbsp}»,

* que de nombreux progrès ont été effectués ces dernières années pour relier la masse du
prototype international à la constante de Planck(((constante, de Planck))) stem:[h], par des méthodes telles que les
expériences de la balance du watt ou les mesures de la masse d’un atome de silicium,

* que les incertitudes associées à l’ensemble des unités électriques du SI réalisées, directement ou
indirectement, au moyen de l’effet Josephson et de l’effet Hall quantique et à partir des valeurs
dans le SI des constantes de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))) et de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))), stem:[ii(K)_J] et stem:[ii(R)_K], pourraient être réduites de
manière significative si le kilogramme était redéfini de façon à ce qu’il soit relié à une valeur
numérique exacte de stem:[h], et si l’ampère(((ampère (stem:["unitsml(A)"])))) était redéfini de façon à ce qu’il soit relié à une valeur
numérique exacte de la charge élémentaire e,

* que la définition actuelle du kelvin se fonde sur une propriété intrinsèque de l’eau qui, bien
qu’étant une constante de la nature, dépend dans la pratique de la pureté et de la
composition isotopique de l’eau utilisée,

* qu’il est possible de redéfinir le kelvin de façon à le relier à une valeur numérique exacte de
la constante de Boltzmann stem:[k],

* qu’il est également possible de redéfinir la mole de façon à la relier à une valeur numérique
exacte de la constante d’Avogadro stem:[ii(N)_"A"], de sorte qu’elle ne dépende plus de la définition du
kilogramme, même lorsque le kilogramme sera défini de façon à le relier à une valeur
numérique exacte de stem:[h], ce qui mettrait en évidence la distinction entre les grandeurs quantité
de matière et masse,

* que les incertitudes liées aux valeurs d’autres constantes fondamentales et facteurs de
conversion d’énergie importants seraient éliminées ou réduites de façon considérable si h, e,
k et NA avaient des valeurs numériques exactes lorsqu’elles sont exprimées en unités du SI,

* que la CGPM, lors de sa 23^e^ réunion en 2007, a adopté la Résolution 12 qui expose le travail
à accomplir par les laboratoires nationaux de métrologie, le BIPM et le Comité international
des poids et mesures (CIPM), ainsi que ses Comités consultatifs, afin que les nouvelles
définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et de la mole fondées sur des constantes
fondamentales puissent être adoptées,

* que, bien que des progrès notables aient été réalisés, tous les objectifs fixés par la
Résolution 12 adoptée par la CGPM à sa 23^e^ réunion n’ont pas été atteints, ce qui ne permet
pas au CIPM de soumettre une proposition finalisée,

* qu’il est néanmoins désormais possible de présenter une version claire et détaillée de ce qui
sera sans doute proposé,

*prend acte* de l’intention du Comité international des poids et mesures de proposer une révision
du SI qui se présenterait de la manière suivante{nbsp}:

* le Système international d’unités, le SI, sera le système d’unités selon lequel{nbsp}:
+
--
* la fréquence de la transition hyperfine dans l’état fondamental de l’atome de césium
133 stem:[Delta nu](^133^Cs)~hfs~ est égale à exactement 9192631770 hertz,
* la ((vitesse de la lumière dans le vide)) c est égale à exactement 299792458 mètres par seconde,
* la constante de Planck(((constante, de Planck))) stem:[h] est égale à exactement stem:[6.62606X xx 10^{-34}] joule seconde*,
+
NOTE: Le symbole X apparaissant dans
l’expression des constantes indique que
le chiffre correspondant n’était pas connu au
moment de l’adoption de la Résolution.

* la charge élémentaire e est égale à exactement stem:[1.60217X xx 10^(-19)] stem:["coulomb"],
* la constante de Boltzmann stem:[k] est égale à exactement stem:[1.3806X xx 10^{-23}] joule par kelvin,
* la constante d’Avogadro stem:[ii(N)_"A"] est égale à exactement stem:[6.02214X xx 10^23] par mole,
* l’efficacité lumineuse stem:[ii(K)_{cd}] d’un rayonnement monochromatique de fréquence
stem:[540 xx 10^12] stem:["unitsml(Hz)"] est égale à exactement 683 lumens par watt,
--

où
(((watt (stem:["unitsml(W)"]))))

. les unités hertz, joule, coulomb, lumen et watt, qui ont respectivement pour symbole stem:["unitsml(Hz)"], stem:["unitsml(J)"], stem:["unitsml(C)"],
stem:["unitsml(lm)"], et stem:["unitsml(W)"], sont reliées aux unités seconde, mètre, kilogramme, ampère(((ampère (stem:["unitsml(A)"])))), kelvin, mole et candela(((candela (stem:["unitsml(cd)"])))),
qui ont respectivement pour symbole stem:["unitsml(s)"], stem:["unitsml(m)"], stem:["unitsml(kg)"], stem:["unitsml(A)"], stem:["unitsml(K)"], stem:["unitsml(mol)"], et stem:["unitsml(cd)"], selon les relations stem:["unitsml(Hz)" = "unitsml(s^(-1))"],
stem:["unitsml(J)" = "unitsml(m^2*kg*s^(-2))"], stem:["unitsml(C)" = "unitsml(s*A)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], et stem:["unitsml(W)" = "unitsml(m^2*kg*s^(-3))"],

. le symbole X dans le présent projet de résolution correspond à un ou plusieurs chiffres qui
devront être ajoutés aux valeurs numériques de stem:[h], stem:[e], stem:[k], et stem:[ii(N)_"A"] selon les valeurs résultant de
l’ajustement le plus récent fourni par la CODATA,

ce qui signifie que le SI continuera à être établi sur les sept unités de base actuelles et que
notamment

* le kilogramme restera l’unité de masse mais son amplitude sera déterminée en
fixant la valeur numérique de la constante de Planck(((constante, de Planck))) à exactement
stem:[6.62606X xx 10^{-34}] lorsqu’elle sera exprimée en stem:["unitsml(m^2*kg*s^(-1))"], unité du SI égale au joule
seconde, stem:["unitsml(J*s)"],

* l’ampère(((ampère (stem:["unitsml(A)"])))) restera l’unité de courant électrique mais son amplitude sera déterminée
en fixant la valeur numérique de la charge élémentaire à exactement
stem:[1.60217X xx 10^(-19)] lorsqu’elle sera exprimée en stem:["unitsml(s*A)"], unité du SI égale au coulomb, stem:["unitsml(C)"],

* le kelvin restera l’unité de température thermodynamique mais son amplitude sera
déterminée en fixant la valeur numérique de la constante de Boltzmann à
exactement stem:[1.3806X xx 10^{-23}] lorsqu’elle sera exprimée en stem:["unitsml(m^2*kg*s^(-2)*K^(-1))"], unité du SI
égale au joule par kelvin stem:["unitsml(J*K^(-1))"],

* la mole restera l’unité de quantité de matière d’une entité élémentaire spécifique,
c’est-à-dire un atome, une molécule, un ion, un électron, ou toute autre particule ou
groupe particulier de telles particules, mais son amplitude sera déterminée en fixant
la valeur numérique de la constante d’Avogadro à exactement stem:[6.02214X xx 10^23]
lorsqu’elle sera exprimée en unité du SI stem:["unitsml(mol^(-1))"].

La Conférence générale des poids et mesures,

*note également*

* que les nouvelles définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et de la mole seront
rédigées en utilisant une formulation dite «{nbsp}à constante explicite{nbsp}», c’est-à-dire une définition
dans laquelle l’unité est définie indirectement en donnant explicitement une valeur exacte à
une constante fondamentale reconnue,

* que la définition actuelle du mètre est reliée à une valeur exacte de la vitesse de la lumière
dans le vide, qui est également une constante fondamentale reconnue,

* que la définition actuelle de la seconde est reliée à une valeur exacte caractérisant une
propriété bien définie de l’atome de césium, qui constitue également une constante de la
nature,

* que la définition existante de la candela(((candela (stem:["unitsml(cd)"])))) n’est pas liée à une constante fondamentale mais
qu’elle peut être considérée comme étant reliée à une valeur exacte d’une constante de la
nature,

* que l’intelligibilité du Système international d’unités serait renforcée si toutes ses unités de
base étaient définies en utilisant la même formulation,

c’est pourquoi le Comité international des poids et mesures proposera également

de reformuler les définitions actuelles de la seconde, du mètre et de la candela(((candela (stem:["unitsml(cd)"])))) selon une forme
complètement équivalente qui pourrait être la suivante{nbsp}:

* la seconde, symbole stem:["unitsml(s)"], est l’unité de temps{nbsp}; son amplitude est déterminée en fixant la valeur
numérique de la fréquence de la transition hyperfine de l’état fondamental de l’atome de
césium 133 au repos, à une température de stem:[0 "unitsml(K)"], à exactement 9192631770 lorsqu’elle est
exprimée en stem:["unitsml(s^(-1))"], unité du SI égale au hertz, stem:["unitsml(Hz)"],

* le mètre, symbole stem:["unitsml(m)"], est l’unité de longueur{nbsp}; son amplitude est déterminée en fixant la valeur
numérique de la ((vitesse de la lumière dans le vide)) à exactement 299792458 lorsqu’elle est
exprimée en unité du SI stem:["unitsml(m*s^(-1))"],

* la candela(((candela (stem:["unitsml(cd)"])))), symbole stem:["unitsml(cd)"], est l’unité d’intensité lumineuse dans une direction donnée{nbsp}; son
amplitude est déterminée en fixant la valeur numérique de l’efficacité lumineuse d’un
rayonnement monochromatique d’une fréquence de stem:[540 xx 10^12 "unitsml(Hz)"] à exactement 683
lorsqu’elle est exprimée en stem:["unitsml(m^(-2)*kg^(-1)*s^3*cd*sr)"] ou en stem:["unitsml(cd*sr*W^(-1))"], unité du SI égale au lumen par
watt, stem:["unitsml(lm*W^(-1))"].

Il sera ainsi manifeste que les définitions des sept unités de base du SI découlent naturellement
des sept constantes précédemment indiquées.

En conséquence, à la date choisie pour mettre en oeuvre la révision du SI

* la définition du kilogramme en vigueur depuis 1889, établie à partir de la masse du prototype
international du kilogramme (1^re^ réunion de la CGPM, 1889{nbsp}; 3^e^ réunion de la CGPM, 1901),
sera abrogée,

* la définition de l’ampère(((ampère (stem:["unitsml(A)"])))) en vigueur depuis 1948 (9^e^ réunion de la CGPM, 1948), établie à
partir de la définition proposée par le Comité international des poids et mesures (CIPM, 1946,
Résolution 2), sera abrogée,
(((volt (stem:["unitsml(V)"]))))

* les valeurs conventionnelles de la constante de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))) stem:[ii(K)_{J–90}] et de la constante de von
Klitzing stem:[ii(R)_{K–90}] adoptées par le Comité international des poids et mesures
(CIPM, 1988, Recommandations 1 et 2) à la demande de la CGPM (18^e^ réunion de la CGPM,
1987, Résolution 6) pour l’établissement des représentations du volt et de l’ohm à l’aide des
effets Josephson et Hall quantique, respectivement, seront abrogées,

* la définition du kelvin en vigueur depuis 1967/68 (13^e^ réunion de la CGPM, 1967/68), établie
à partir d’une définition antérieure moins explicite (10^e^ réunion de la CGPM, 1954, Résolution
3), sera abrogée,

* la définition de la mole en vigueur depuis 1971 (14^e^ réunion de la CGPM, 1971, Résolution
3), selon laquelle la masse molaire du carbone 12 a la valeur exacte de stem:[0.012 "unitsml(kg*mol^(-1))"], sera
abrogée,

* les définitions existantes du mètre, de la seconde et de la candela(((candela (stem:["unitsml(cd)"])))), en vigueur depuis leur
adoption par la CGPM lors de ses 17^e^ (1983, Résolution 1), 13^e^ (1967/68, Résolution 1) et
16^e^ (1979, Résolution 3) réunions respectivement, seront abrogées.

La Conférence générale des poids et mesures,

*prend en considération* qu’à la même date

* la masse du prototype international du kilogramme stem:[m(K)] sera égale à stem:[1 "unitsml(kg)"], avec cependant
une incertitude relative égale à celle de la valeur recommandée de h juste avant la
redéfinition, puis sa valeur sera déterminée de façon expérimentale,

* la constante magnétique (la perméabilité du vide) stem:[mu_0] sera égale à stem:[4 pi xx 10^(-7)] stem:["unitsml(H*m^(-1))"], avec
cependant une incertitude relative égale à celle de la valeur recommandée de la constante
de structure fine(((constante, de structure fine))) stem:[alpha], puis sa valeur sera déterminée de façon expérimentale,

* la température thermodynamique du point triple de l’eau stem:[ii(T)_("TPW")] sera égale à stem:[273.16 "unitsml(K)"], avec
cependant une incertitude relative égale à celle de la valeur recommandée de k juste avant la
redéfinition, puis sa valeur sera déterminée de façon expérimentale,

* la masse molaire du carbone 12 stem:[ii(M)(""^{12}"C")] sera égale à stem:[0.012] stem:["unitsml(kg*mol^(-1))"], avec cependant une
incertitude relative égale à celle de la valeur recommandée de stem:[ii(N)_"A" h] juste avant la redéfinition,
puis sa valeur sera déterminée de façon expérimentale.


La Conférence générale des poids et mesures,

*encourage*

* les chercheurs des laboratoires nationaux de métrologie, le BIPM et les institutions
universitaires à poursuivre leurs efforts et à transmettre à la communauté scientifique en
général et à la CODATA en particulier les résultats de leurs travaux sur la détermination des
constantes de stem:[h], stem:[e], stem:[k], et stem:[ii(N)_"A"], et

* le BIPM à poursuivre son travail afin d’assurer la traçabilité au prototype international du
kilogramme des prototypes de masse qu’il maintient, ainsi qu’à mettre au point un ensemble
d’étalons de référence qui permettra de faciliter la dissémination de l’unité de masse une fois
le kilogramme redéfini,

*et invite*

* la CODATA à continuer à fournir des valeurs pour les constantes fondamentales de la
physique ajustées à partir de toutes les données pertinentes disponibles, ainsi qu’à
transmettre les résultats au CIPM par l’intermédiaire du Comité consultatif des unités,
puisque ce sont les valeurs et incertitudes de la CODATA qui seront utilisées pour la révision
du SI,

* le CIPM à lui proposer de réviser le SI dès que les recommandations de la Résolution 12
adoptée par la CGPM à sa 23^e^ réunion seront satisfaites, en particulier la préparation des
mises en pratique des nouvelles définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et de la
mole,

* le CIPM à poursuivre son travail afin d’obtenir une meilleure formulation des définitions des
unités de base du SI fondées sur des constantes fondamentales, l’objectif étant de parvenir,
autant que possible, à une description plus facilement compréhensible pour l’ensemble des
utilisateurs tout en gardant rigueur et clarté scientifiques,

* le CIPM, les Comités consultatifs, le BIPM, l’OIML et les laboratoires nationaux de métrologie
à intensifier leurs efforts afin de mettre en place des campagnes de sensibilisation pour
informer les communautés d’utilisateurs et le grand public du projet de redéfinition de
certaines unités du SI, et à encourager l’examen des implications juridiques, techniques et
pratiques de ces redéfinitions, afin de solliciter les commentaires et les contributions de la
vaste communauté des scientifiques et des utilisateurs.


==== Sur la révision de la mise en pratique de la définition du mètre et sur la mise au point de nouveaux étalons optiques de fréquence (<<CR2011-8,page=227>>)

[align=center]
*Résolution 8*

La Conférence générale des poids et mesures (CGPM), à sa 24^e^ réunion,

*considérant*

* que les performances des étalons optiques de fréquence s’améliorent rapidement et de manière
très significative,

* que les laboratoires nationaux de métrologie mettent actuellement en oeuvre des techniques de
comparaison à courte distance d’étalons optiques de fréquence,

* que des techniques de comparaison à distance d’étalons optiques de fréquence doivent être
mises au point au niveau international,

*accueille favorablement*

* les activités du Groupe de travail commun au Comité consultatif des longueurs (CCL) et au
Comité consultatif du temps et des fréquences (CCTF) visant à examiner les fréquences des
représentations optiques de la seconde,

* les éléments ajoutés par le CIPM en 2009 à la liste commune des «{nbsp}valeurs recommandées de
fréquences étalons destinées à la mise en pratique de la définition du mètre et aux
représentations secondaires de la seconde{nbsp}»,

* l’établissement d’un groupe de travail du CCTF sur la coordination de la mise au point de
techniques avancées de comparaison de temps et de fréquences,

*recommande* que

* les laboratoires nationaux de métrologie engagent les ressources nécessaires à la mise au point
d’étalons optiques de fréquence et à leur comparaison,
* le BIPM aide à la coordination d’un projet international auquel participeraient les laboratoires
nationaux de métrologie, portant sur l’étude des techniques qui pourraient être utilisées pour
comparer les étalons optiques de fréquence.


=== CIPM, 2013

==== Mises à jour de la liste des fréquences étalons (<<PV81, page=53>>)

[align=center]
*Recommandation 1*


Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des «{nbsp}valeurs recommandées des fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde{nbsp}» a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates en vue de leur inclusion dans cette liste,

*recommande* d’apporter les changements suivant à la liste commune des «{nbsp}valeurs
recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre
et aux représentations secondaires de la seconde{nbsp}»{nbsp}:

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées{nbsp}:
** la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s 6p ^3^P~0~ de l’atome neutre de ^199^Hg,
à la fréquence de stem:[1128575290808162 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[1.7 xx 10^(-14)]{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées{nbsp}:
** la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^,
à la fréquence de stem:[411042129776395 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[1.5 xx 10^(-14)]{nbsp};
** la transition optique non perturbée 1S – 2S de l’atome neutre de ^1^H, à la fréquence
de stem:[1233030706593518 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1.2 xx 10^(-14)]{nbsp};

Remarque{nbsp}: cette fréquence correspond à la moitié de l’écart en énergie entre les états 1S et
2S{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde{nbsp}:
** la transition optique non perturbée 6s ^2^S~1/2~ – 4f ^13^6s^2^ ^2^F~7/2~ de l’ion de ^171^Yb^+^ (octupôle),
à la fréquence de stem:[642121496772645.6 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[1.3 xx 10^(-15)]{nbsp};
** la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s 6p ^3^P~0~ de l’atome neutre de ^171^Yb,
à la fréquence de stem:[518295836590865.0 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[2.7 xx 10^(-15)]{nbsp};

* inclure la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde{nbsp}:
** la transition optique non perturbée 3s^2^ ^1^S~0~ – 3s 3p ^3^P~0~ de l’ion de ^27^Al^+^, à la fréquence
de stem:[1121015393207857.3 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1.9 xx 10^(-15)]{nbsp};

* mettre à jour les fréquences des transitions suivantes dans la liste des fréquences étalons
recommandées et les approuver comme représentations secondaires de la seconde{nbsp}:
** la transition optique non perturbée 5d ^10^6s ^2^S~1/2~ – 5d ^9^6s^2^ ^2^D~5/2~ de l’ion de ^199^Hg^+^,
à la fréquence de stem:[1064721609899145.3 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[1.9 xx 10^(-15)]{nbsp};
** la transition optique non perturbée 6s ^2^S~1/2~ (stem:[F = 0], stem:[m_"F" = 0]) – 5d ^2^D~3/2~ (stem:[F = 2], stem:[m_"F" = 0]) de
l’ion de ^171^Yb^+^ (quadrupôle), à la fréquence de stem:[688358979309307.1 "unitsml(Hz)"] avec une
incertitude-type relative estimée de stem:[3 xx 10^(-15)]{nbsp};
** la transition optique non perturbée 5s ^2^S~1/2~ – 4d ^2^D~5/2~ de l’ion de ^88^Sr^+^, à la fréquence
de stem:[444779044095485.3 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[4.0 xx 10^(-15)]{nbsp};
** la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s5p ^3^P~0~ de l’atome neutre de ^87^Sr, à la
fréquence de stem:[429228004229873.4 "unitsml(Hz)"] avec une incertitude-type relative estimée de
stem:[1 xx 10^(-15)]{nbsp};

* mettre à jour la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde{nbsp}:
** la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de
^87^Rb, à la fréquence de stem:[6834682610.904312 "unitsml(Hz)"] avec une incertitude-type
relative estimée de stem:[1.3 xx 10^(-15)].

Remarque{nbsp}: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.


=== 25^e^ CGPM, 2014

==== Sur la révision à venir du Système international d’unités, le SI (<<CR2014-1,page=177>> et _Metrologia_, 2015, 52, 155)

NOTE: La CGPM à sa 26^e^ réunion (2018) a approuvé la
révision du SI (Résolution 1, _voir_ p. 92).

[align=center]
*Résolution 1*

La Conférence générale des poids et mesures (CGPM), à sa 25^e^ réunion,

*rappelant*

* la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011) qui prend acte de l’intention du
Comité international des poids et mesures (CIPM) de proposer une révision du SI consistant à
relier les définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))), du kelvin et de la mole à des valeurs numériques
exactes de la constante de Planck(((constante, de Planck))) stem:[h], de la charge élémentaire stem:[e], de la constante de Boltzmann stem:[k],
et de la constante d’Avogadro stem:[ii(N)_"A"], respectivement, et à modifier la façon de définir le SI, ainsi que
la formulation des définitions des unités du SI pour les grandeurs temps, longueur, masse, courant
électrique, température thermodynamique, quantité de matière et intensité lumineuse, de manière
à ce que les constantes de référence sur lesquelles se fonde le SI apparaissent clairement,

* les nombreux avantages, mentionnés dans la Résolution 1, que présentera cette révision du SI
pour la science, la technologie, l’industrie et le commerce, tel que le fait de relier le kilogramme à
une constante de la nature et non plus à la masse d’un objet matériel (artefact), ce qui assurera sa
stabilité à long terme,

* la Résolution 7 adoptée par la CGPM à sa 21^e^ réunion (1999) qui encourage les laboratoires
nationaux de métrologie à poursuivre les expériences visant à parvenir à une telle redéfinition du
kilogramme,

* la Résolution 12 adoptée par la CGPM à sa 23^e^ réunion (2007) qui décrit les travaux devant
être effectués par les laboratoires nationaux de métrologie, le Bureau international des poids
et mesures (BIPM), ainsi que le CIPM et ses Comités consultatifs, afin de permettre
l’adoption par la CGPM de la révision du SI,

*considérant* les progrès significatifs réalisés afin d’effectuer les travaux nécessaires, parmi
lesquels,

* l’acquisition des données pertinentes, et leur analyse par le Committee on Data for Science
and Technology (CODATA), afin d’obtenir les valeurs requises pour les constantes
fondamentales de stem:[h], stem:[e], stem:[k], et stem:[ii(N)_"A"],

* la mise au point par le BIPM d’un ensemble d’étalons de masse de référence qui permettra
de faciliter la dissémination de l’unité de masse une fois le SI révisé,

* la préparation des mises en pratique des nouvelles définitions du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))),
du kelvin et de la mole,

*notant que* le Comité consultatif des unités (CCU), le CIPM, le BIPM, les laboratoires nationaux
de métrologie et les Comités consultatifs doivent poursuivre leurs travaux en se concentrant sur

* la mise en place de campagnes de sensibilisation pour informer les communautés
d’utilisateurs et le grand public du projet de révision du SI,

* la préparation de la 9^e^ édition de la _Brochure sur le SI_ dans laquelle le SI révisé serait
présenté de façon compréhensible par l’ensemble des lecteurs sans pour autant en
compromettre la rigueur scientifique,

*considérant que*, malgré les progrès effectués, les données disponibles ne semblent pas
encore suffisamment robustes pour que la CGPM adopte le SI révisé lors de sa 25^e^ réunion,

*encourage*

* les laboratoires nationaux de métrologie, le BIPM et les institutions universitaires à poursuivre
leurs efforts afin de déterminer expérimentalement les valeurs des constantes de stem:[h], stem:[e], stem:[k] et stem:[ii(N)_"A"]
au niveau d’incertitude requis,

* les laboratoires nationaux de métrologie à continuer activement à examiner et discuter de ces
résultats au sein des Comités consultatifs,

* le CIPM à continuer à planifier la mise en oeuvre de la Résolution 1 adoptée par la CGPM à
sa 24^e^ réunion (2011), en collaboration étroite avec les Comités consultatifs et le CCU,

* le CIPM et ses Comités consultatifs, les laboratoires nationaux de métrologie, le BIPM, ainsi
que d’autres organisations telles que l’Organisation internationale de métrologie légale
(OIML), à poursuivre leurs efforts afin d’effectuer les travaux nécessaires pour que la CGPM
adopte, lors de sa 26^e^ réunion, une résolution permettant de remplacer le SI actuel par le SI
révisé, sous réserve que les données obtenues, tant concernant leur nombre, les incertitudes
associées ou leur niveau de cohérence, soient jugées satisfaisantes.


=== CIPM, 2015

==== Mises à jour de la liste des fréquences étalons (<<PV83, page=54>>)

NOTE: Des mises à jour sont disponibles sur le site
internet du BIPM.

[align=center]
*Recommandation 2*

Le Comité international des poids et mesures (CIPM),

*considérant*

* qu’une liste commune des «{nbsp}valeurs recommandées de fréquences étalons destinées à la
mise en pratique de la définition du mètre et aux représentations secondaires de la
seconde{nbsp}» a été établie,

* que le Groupe de travail commun au CCL et au CCTF sur les étalons de fréquence a
examiné plusieurs fréquences candidates afin de mettre à jour cette liste,

*recommande*

que les fréquences des transitions suivantes soient mises à jour dans la liste des fréquences
étalons recommandées{nbsp}:

* la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s6p ^3^P~0~ de l’atome neutre de ^199^Hg,
à la fréquence de f^199^Hg = stem:[1128575290808154.8 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[6 xx 10^(-16)]{nbsp};

* la transition optique non perturbée 6s ^2^S~1/2~ – 4f^13^ 6s2 ^2^F~7/2~ de l’ion de ^17^1Yb^+^, à la fréquence
de stem:[f_{171Yb+}] (octupôle) = stem:[642121496772645.0 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[6 xx 10^(-16)] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde){nbsp};

* la transition optique non perturbée 6s ^2^S~1/2~ (stem:[F = 0], stem:[m_"F" = 0]) – 5d ^2^D~3/2~ (stem:[F = 2], stem:[m_"F" = 0]) de l’ion
de ^171^Yb^+^, à la fréquence de f~171Yb+~ (quadripôle) stem:[= 688358979309308.3 "unitsml(Hz)"] avec une
incertitude-type relative estimée de stem:[6 xx 10^(-16)] (cette radiation a déjà été approuvée par le
CIPM comme représentation secondaire de la seconde){nbsp};

* la transition optique non perturbée 5s ^2^S~1/2~ – 4d ^2^D~5/2~ de l’ion de ^88^Sr^+^, à la fréquence de
f~88Sr+~ = stem:[444779044095486.6 "unitsml(Hz)"] avec une incertitude-type relative estimée de stem:[1.6 xx 10^(-15)]
(cette radiation a déjà été approuvée par le CIPM comme représentation secondaire de la
seconde){nbsp};

* la transition optique non perturbée 4s ^2^S~1/2~ – 3d ^2^D~5/2~ de l’ion de ^40^Ca^+^, à la fréquence de
stem:[f_{40Ca+} = 411042129776398.4 "unitsml(Hz)"] avec une incertitude-type relative estimée de stem:[1.2 xx 10^(-14)]{nbsp};
* la transition optique non perturbée 1S – 2S de l’atome neutre de ^1^H, à la fréquence de f~1H~ = 1
stem:[233030706593514 "unitsml(Hz)"] avec une incertitude-type relative estimée de stem:[9 xx 10^(-15)]{nbsp};

Remarque{nbsp}: cette fréquence correspond à la moitié de l’écart en énergie entre les états 1S et
2S{nbsp};

* la transition optique non perturbée 5s^2^ ^1^S~0~ – 5s5p ^3^P~0~ de l’atome neutre de ^87^Sr,
à la fréquence de stem:[f_{87Sr} = 429228004229873.2 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[5 xx 10^(-16)] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde){nbsp};

* la transition optique non perturbée 6s^2^ ^1^S~0~ – 6s6p ^3^P~0~ de l’atome neutre de ^171^Yb,
à la fréquence de stem:[f_{171"Yb"} = 518295836590864.0 "unitsml(Hz)"] avec une incertitude-type relative
estimée de stem:[2 xx 10^(-15)] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde){nbsp};

* la transition hyperfine non perturbée de l’état fondamental de l’atome de ^87^Rb,
à la fréquence de stem:[f_{87Rb} = 6834682610.904310 "unitsml(Hz)"] avec une incertitude-type relative estimée
de stem:[7 xx 10^(-16)] (cette radiation a déjà été approuvée par le CIPM comme représentation
secondaire de la seconde){nbsp};

*recommande* par ailleurs

que les fréquences des transitions suivantes soient incluses dans la liste des fréquences étalons
recommandées{nbsp}:

* Molécule absorbante de ^127^I~2~, composante a1 du spectre d’absorption saturée,
transition R(36) 32-0.
+
--
Les valeurs:: stem:[f_{a1} = 564074632.42 "unitsml(MHz)"] +
stem:[lambda_{a1} = 531476582.65 "unitsml(fm)"]
--

avec une incertitude-type relative estimée de stem:[1 xx 10^(-10)] s’appliquent à la radiation d’un laser à
diode à rétroaction répartie doublé en fréquence, asservi à l’aide d’une cellule d’iode située à
l’extérieur du laser.

* Atome absorbant de ^87^Rb, transition 5S~1/2~ - 5P~3/2~, croisement de niveaux entre les
composantes hyperfines d et f de l’absorption saturée à stem:[780 "unitsml(nm)"] (transition D2).
+
--
Les valeurs:: stem:[f_{"croisement d/f"} = 384227981.9 "unitsml(MHz)"] +
stem:[lambda_{"croisement d/f"} = 780246291.6 "unitsml(fm)"]
--

avec une incertitude-type relative estimée de stem:[5 xx 10^(-10)] s’appliquent à la radiation d’un laser
accordable à diode et à cavité externe, asservi sur la résonance de croisement de niveaux d/f
dans une cellule de rubidium située à l’extérieur du laser.

Remarque{nbsp}: La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.


=== CIPM, 2017

==== Sur les progrès réalisés en vue d’une éventuelle révision du SI (<<PV85, page=28>>)

[align=center]
*Décision 10*

Le CIPM accueille favorablement les recommandations relatives à la révision du SI formulées
par ses Comités consultatifs.

Le CIPM note que les conditions fixées pour procéder à la révision du SI sont désormais
remplies et décide de soumettre le Projet de résolution A à la Conférence générale des poids et
mesures (CGPM) à sa 26^e^ réunion et de prendre toutes les autres dispositions nécessaires en
vue de procéder, tel que cela a été planifié, à la redéfinition du kilogramme, de l’ampère(((ampère (stem:["unitsml(A)"])))),
du kelvin et de la mole.


=== 26th CGPM, 2018

==== Sur la révision du Système international d’unités (SI) (CR, sous presse et _Metrologia_, 2019, 56, 022001)

[align=center]
*Résolution 1*

La Conférence générale des poids et mesures (CGPM), à sa 26^e^ réunion,

*considérant*

* qu’il est essentiel de disposer d’un Système international d’unités (SI) uniforme et accessible
dans le monde entier, pour le commerce international, l’industrie de haute technologie, la santé
humaine et la sécurité, la protection de l’environnement, les études sur l’évolution du climat,
ainsi que la science fondamentale qui étaye tous ces domaines,

* que les unités du SI doivent être stables sur le long terme, auto cohérentes et réalisables
dans la pratique, en étant fondées sur la description théorique actuelle de la nature, au plus
haut niveau,

* qu’une révision du SI visant à satisfaire ces exigences a été proposée dans la Résolution 1
adoptée à l’unanimité par la CGPM à sa 24^e^ réunion (2011), qui expose en détail une
nouvelle façon de définir le SI à partir d’un ensemble de sept constantes, choisies parmi les
constantes fondamentales de la physique et d’autres constantes de la nature, à partir
desquelles les définitions des sept unités de base sont déduites,

* que les conditions requises par la CGPM à sa 24^e^ réunion (2011), confirmées à sa
25^e^ réunion (2014), pour procéder à l’adoption d’une telle révision du SI sont désormais
remplies,

*décide*

qu’à compter du 20 mai 2019, le Système international d’unités, le SI, est le système d’unités
selon lequel{nbsp}:

* la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium
133 non perturbé, stem:[Delta ii(nu)_{"Cs"}], est égale à stem:[9192631770 "unitsml(Hz)"],
* la ((vitesse de la lumière dans le vide)), stem:[c], est égale à stem:[299792458 "unitsml(m/s)"],
* la constante de Planck(((constante, de Planck))), stem:[h], est égale à stem:[6.62607015 xx 10^{-34} "unitsml(J*s)"],
* la charge élémentaire, stem:[e], est égale à stem:[1.602176634 xx 10^(-19) "unitsml(C)"],
* la constante de Boltzmann, stem:[k], est égale à stem:[1.380649 xx 10^{-23} "unitsml(J/K)"],
* la constante d’Avogadro, stem:[ii(N)_"A"], est égale à stem:[6.02214076 xx 10^(23) "unitsml(mol^(-1))"],
* l’efficacité lumineuse d’un rayonnement monochromatique de fréquence
stem:[540 xx 10^12 "unitsml(Hz)"], stem:[ii(K)_{cd}], est égale à stem:[683 "unitsml(lm/W)"],

où les unités hertz, joule, coulomb, lumen et watt, qui ont respectivement pour symbole stem:["unitsml(Hz)"], stem:["unitsml(J)"], stem:["unitsml(C)"],
stem:["unitsml(lm)"] et stem:["unitsml(W)"], sont reliées aux unités seconde, mètre, kilogramme, ampère(((ampère (stem:["unitsml(A)"])))), kelvin, mole et candela(((candela (stem:["unitsml(cd)"])))),
qui ont respectivement pour symbole stem:["unitsml(s)"], stem:["unitsml(m)"], stem:["unitsml(kg)"], stem:["unitsml(A)"], stem:["unitsml(K)"], stem:["unitsml(mol)"] et stem:["unitsml(cd)"], selon les relations, stem:["unitsml(J)" = "unitsml(kg*m^2*s^(-2))"],
stem:["unitsml(C)" = "unitsml(A*s)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], et stem:["unitsml(W)" = "unitsml(kg*m^2*s^(-3))"],

*prend acte* des conséquences de la révision du SI concernant les unités de base du SI,
énoncées dans la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011), et les confirme
dans les annexes de la présente résolution, qui ont même force que la résolution elle-même,

*invite* le Comité international des poids et mesures (CIPM) à publier une nouvelle édition de la
Brochure sur le SI, «{nbsp}Le Système international d’unités{nbsp}», contenant une description complète du
SI révisé.


*Annexe 1. Abrogation des précédentes définitions des unités de base*

Il résulte de la nouvelle définition du SI décrite ci-dessus qu’à compter du 20 mai 2019{nbsp}:

* la définition de la seconde en vigueur depuis 1967/68 (13^e^ réunion de la CGPM,
Résolution 1) est abrogée,
* la définition du mètre en vigueur depuis 1983 (17^e^ réunion de la CGPM, Résolution 1)
est abrogée,
* la définition du kilogramme en vigueur depuis 1889 (1^ère^ réunion de la CGPM, 1889,
3^e^ réunion de la CGPM, 1901), établie à partir de la masse du prototype international du
kilogramme, est abrogée,
* la définition de l’ampère(((ampère (stem:["unitsml(A)"])))) en vigueur depuis 1948 (9^e^ réunion de la CGPM), établie à partir de
la définition proposée par le CIPM (1946, Résolution 2), est abrogée,
* la définition du kelvin en vigueur depuis 1967/68 (13^e^ réunion de la CGPM, Résolution 4)
est abrogée,
* la définition de la mole en vigueur depuis 1971 (14^e^ réunion de la CGPM, Résolution 3)
est abrogée,
* la définition de la candela(((candela (stem:["unitsml(cd)"])))) en vigueur depuis 1979 (16^e^ réunion de la CGPM, Résolution 3)
est abrogée,
* la décision d’adopter les valeurs conventionnelles de la constante de Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))) stem:[ii(K)_{J–90}] et de
la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K"], stem:[ii(R)_"K-90"])))) stem:[ii(R)_{K–90}], prise par le CIPM (1988, Recommandations 1 et 2)
à la demande de la CGPM (18^e^ réunion de la CGPM, 1987, Résolution 6) pour
l’établissement des représentations du volt et de l’ohm à l’aide des effets Josephson et Hall
quantique, respectivement, est abrogée.


*Annexe 2. Statut des constantes utilisées antérieurement dans les anciennes définitions*

Il résulte de la nouvelle définition du SI décrite ci-dessus, et des valeurs recommandées dans
l’ajustement spécial de 2017 du Committee on Data for Science and Technology (CODATA),
sur lesquelles se fondent les valeurs des constantes choisies pour définir le SI, qu’à compter du
20 mai 2019{nbsp}:

* la masse du prototype international du kilogramme, stem:[m(K)], est égale à stem:[1 "unitsml(kg)"] avec une
incertitude-type relative égale à celle de la valeur recommandée de h au moment de
l’adoption de la présente résolution, à savoir stem:[1.0 xx 10^{-8}]{nbsp}; dans le futur, sa valeur sera
déterminée de façon expérimentale,
* la perméabilité magnétique du vide, stem:[mu_0], est égale à stem:[4 pi xx 10^(-7) "unitsml(H*m^(-1))"] avec une incertitude-type
relative égale à celle de la valeur recommandée de la constante de structure fine(((constante, de structure fine))) stem:[alpha]
au moment de l’adoption de la présente résolution, à savoir stem:[2.3 xx 10^{-10}]{nbsp}; dans le futur,
sa valeur sera déterminée de façon expérimentale,
* la température thermodynamique du point triple de l’eau, stem:[ii(T)_("TPW")], est égale à stem:[273.16 "unitsml(K)"] avec
une incertitude-type relative presque égale à celle de la valeur recommandée de stem:[k]
au moment de l’adoption de la présente résolution, à savoir stem:[3.7 xx 10^{-7}]{nbsp}; dans le futur, sa
valeur sera déterminée de façon expérimentale,
* la masse molaire du carbone 12, stem:[ii(M)(""^{12}"C")], est égale à stem:[0.012 "unitsml(kg*mol^(-1))"] avec une incertitude-type
relative égale à celle de la valeur recommandée de stem:[ii(N)_"A"h] au moment de l’adoption de la
présente résolution, à savoir stem:[4.5 xx 10^{-10}]{nbsp}; dans le futur, sa valeur sera déterminée de façon
expérimentale.


*Annexe 3. Les unités de base du SI*

La nouvelle définition du SI décrite ci-dessus, fondée sur les valeurs numériques fixées des
constantes choisies, permet de déduire la définition de chacune des sept unités de base du SI à
l’aide d’une ou plusieurs de ces constantes, selon les cas. Les définitions qui en découlent,
qui prendront effet à compter du 20 mai 2019, sont les suivantes{nbsp}:

* La seconde, symbole stem:["unitsml(s)"], est l’unité de temps du SI. Elle est définie en prenant la valeur
numérique fixée de la fréquence du césium, stem:[Delta ii(nu)_{"Cs"}], la fréquence de la transition hyperfine de
l’état fondamental de l’atome de césium 133 non perturbé, égale à 9192631770 lorsqu’elle
est exprimée en stem:["unitsml(Hz)"], unité égale à stem:["unitsml(s^(-1))"].

* Le mètre, symbole stem:["unitsml(m)"], est l’unité de longueur du SI. Il est défini en prenant la valeur
numérique fixée de la ((vitesse de la lumière dans le vide)), stem:[c], égale à stem:[299792458] lorsqu’elle
est exprimée en stem:["unitsml(m/s)"], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le kilogramme, symbole stem:["unitsml(kg)"], est l’unité de masse du SI. Il est défini en prenant la valeur
numérique fixée de la constante de Planck(((constante, de Planck))), stem:[h], égale à stem:[6.6267015 xx 10^{-34}] lorsqu’elle est
exprimée en stem:["unitsml(J*s)"], unité égale à stem:["unitsml(kg*m^2*s^(-1))"], le mètre et la seconde étant définis en fonction de stem:[c]
et stem:[Delta ii(nu)_{"Cs"}].

* L’ampère(((ampère (stem:["unitsml(A)"])))), symbole stem:["unitsml(A)"], est l’unité de courant électrique du SI. Il est défini en prenant la valeur
numérique fixée de la charge élémentaire, stem:[e], égale à stem:[1.602176634 xx 10^(-19)] lorsqu’elle est
exprimée en stem:["unitsml(C)"], unité égale à stem:["unitsml(A*s)"], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le kelvin, symbole stem:["unitsml(K)"], est l’unité de température thermodynamique du SI. Il est défini en
prenant la valeur numérique fixée de la constante de Boltzmann, stem:[k], égale à stem:[1.380649 xx 10^{-23}]
lorsqu’elle est exprimée en stem:["unitsml(J*K^(-1))"], unité égale à stem:["unitsml(kg*m^2*s^(-2)*K^(-1))"], le kilogramme, le mètre et la
seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}].

* La mole, symbole stem:["unitsml(mol)"], est l’unité de quantité de matière du SI. Une mole contient exactement
stem:[6.02214076 xx 10^23] entités élémentaires. Ce nombre, appelé «{nbsp}nombre d’Avogadro{nbsp}»,
correspond à la valeur numérique fixée de la constante d’Avogadro, stem:[ii(N)_"A"], lorsqu’elle est
exprimée en stem:["unitsml(mol^(-1))"].
+
--
La quantité de matière, symbole stem:[n], d’un système est une représentation du nombre d’entités
élémentaires spécifiées. Une entité élémentaire peut être un atome, une molécule, un ion,
un électron, ou toute autre particule ou groupement spécifié de particules.
--
* La candela(((candela (stem:["unitsml(cd)"])))), symbole stem:["unitsml(cd)"], est l’unité du SI d’intensité lumineuse dans une direction donnée.
Elle est définie en prenant la valeur numérique fixée de l’efficacité lumineuse d’un
rayonnement monochromatique de fréquence stem:[540 xx 10^12 "unitsml(Hz)"], stem:[ii(K)_"cd"], égale à 683 lorsqu’elle est
exprimée en stem:["unitsml(lm*W^(-1))"], unité égale à stem:["unitsml(cd*sr*W^(-1))"], ou stem:["unitsml(cd*sr*kg^(-1)*m^(-2)*s^3)"], le kilogramme, le mètre et
la seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}].

