[appendix,obligation=informative]
== Annexe 1. Abrogation des précédentes définitions des unités de base

Il résulte de la nouvelle définition du SI décrite ci-dessus qu’à compter du 20 mai 2019{nbsp}:

* la définition de la seconde en vigueur depuis 1967/68 (13^e^ réunion de la CGPM,
Résolution 1) est abrogée,
* la définition du mètre(((mètre (stem:["unitsml(m)"])))) en vigueur depuis 1983 (17^e^ réunion de la CGPM, Résolution 1)
est abrogée,
* la définition du kilogramme en vigueur depuis 1889 (1^ère^ réunion de la CGPM, 1889,
3^e^ réunion de la CGPM, 1901), établie à partir de la masse du prototype international du
kilogramme, est abrogée,
* la définition de l’ampère(((ampère (stem:["unitsml(A)"])))) en vigueur depuis 1948 (9^e^ réunion de la CGPM), établie à partir de
la définition proposée par le CIPM (1946, Résolution 2), est abrogée,
* la définition du kelvin en vigueur depuis 1967/68 (13^e^ réunion de la CGPM, Résolution 4)
est abrogée,
* la définition de la mole en vigueur depuis 1971 (14^e^ réunion de la CGPM, Résolution 3)
est abrogée,
* la définition de la candela en vigueur depuis 1979 (16^e^ réunion de la CGPM, Résolution 3)
est abrogée,
(((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))
(((volt (stem:["unitsml(V)"]))))

* la décision d’adopter les valeurs conventionnelles de la constante de Josephson stem:[ii(K)_{"J–90"}] et de
la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K",ii(R)_"K-90"])))) stem:[ii(R)_{"K–90"}], prise par le CIPM (1988, Recommandations 1 et 2)
à la demande de la CGPM (18^e^ réunion de la CGPM, 1987, Résolution 6) pour
l’établissement des représentations du volt et de l’ohm à l’aide des effets Josephson et Hall
quantique, respectivement, est abrogée.