[appendix,obligation=informative]
== Annexe 2. Statut des constantes utilisées antérieurement dans les anciennes définitions

Il résulte de la nouvelle définition du SI décrite ci-dessus, et des valeurs recommandées dans
l’ajustement spécial de 2017 du Committee on Data for Science and Technology (CODATA),
sur lesquelles se fondent les valeurs des constantes choisies pour définir le SI, qu’à compter du
20 mai 2019:

* la ((masse)) du prototype international du ((kilogramme)), stem:[m(cc "K")], est égale à 1 kg avec une
incertitude-type relative égale à celle de la valeur recommandée de stem:[h] au moment de
l’adoption de la présente résolution, à savoir stem:[1.0 xx 10^{-8}]; dans le futur, sa valeur sera
déterminée de façon expérimentale,
* la perméabilité magnétique du vide(((constante, magnétique&#44; perméabilité du vide))), stem:[ii(mu)_0], est égale à stem:[4 pi xx 10^{-7} " "rm(H)" "rm(m)^{-1}] avec une incertitude-type
relative égale à celle de la valeur recommandée de la constante de structure fine(((constante, de structure fine))) stem:[alpha]
au moment de l’adoption de la présente résolution, à savoir stem:[2.3 xx 10^{-10}]; dans le futur,
sa valeur sera déterminée de façon expérimentale,
* la température thermodynamique du ((point triple de l’eau)), stem:[ii(T)_{"TPW"}], est égale à stem:[273.16 " "rm(K)] avec
une incertitude-type relative presque égale à celle de la valeur recommandée de stem:[k]
au moment de l’adoption de la présente résolution, à savoir stem:[3.7 xx 10^{-7}]; dans le futur, sa
valeur sera déterminée de façon expérimentale,
* la ((masse)) molaire du ((carbone)) 12, stem:[ii(M)(""^{12}"C")], est égale à stem:[0.012 " "rm(kg)" "rm(mol)^{-1}] avec une incertitude-type
relative égale à celle de la valeur recommandée de stem:[ii(N)_"A"h] au moment de l’adoption de la
présente résolution, à savoir stem:[4.5 xx 10^{-10}]; dans le futur, sa valeur sera déterminée de façon
expérimentale.
