[appendix,obligation=informative]
== Annexe 3. Les unités de base du SI

La nouvelle définition du SI décrite ci-dessus, fondée sur les valeurs numériques fixées des
constantes choisies, permet de déduire la définition de chacune des sept unités de base du SI à
l’aide d’une ou plusieurs de ces constantes, selon les cas. Les définitions qui en découlent,
qui prendront effet à compter du 20 mai 2019, sont les suivantes:

* La seconde, symbole stem:[rm(s)], est l’unité de temps du SI. Elle est définie en prenant la valeur
numérique fixée de la ((fréquence du césium)), stem:[Delta nu_{"Cs"}], la fréquence de la transition hyperfine de
l’état fondamental de l’atome de césium(((atome de césium, niveaux hyperfins))) 133 non perturbé, égale à stem:[9192631770] lorsqu’elle
est exprimée en stem:[rm(Hz)], unité égale à stem:[rm(s)^{-1}].

* Le mètre, symbole stem:[rm(m)], est l’unité de longueur du SI. Il est défini en prenant la valeur
numérique fixée de la vitesse de la lumière dans le vide, stem:[c], égale à stem:[299792458] lorsqu’elle
est exprimée en stem:[rm(m)//rm(s)], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le ((kilogramme)), symbole stem:[rm(kg)], est l’unité de masse du SI. Il est défini en prenant la valeur
numérique fixée de la constante de Planck(((constante, de Planck))), stem:[h], égale à stem:[6.62607015 xx 10^{-34}] lorsqu’elle est
exprimée en stem:[rm(J)" "rm(s)], unité égale à stem:[rm(kg)" "rm(m)^2 " "rm(s)^{-1}], le mètre et la seconde étant définis en fonction de stem:[c]
et stem:[Delta ii(nu)_{"Cs"}].

* L’ampère(((ampère (A)))), symbole stem:[rm(A)], est l’unité de ((courant électrique)) du SI. Il est défini en prenant la valeur
numérique fixée de la charge élémentaire, stem:[e], égale à stem:[1.602176634 xx 10^{-19}] lorsqu’elle est
exprimée en stem:[rm(C)], unité égale à stem:[rm(A)" "rm(s)], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le kelvin(((kelvin (K)))), symbole stem:[rm(K)], est l’unité de température thermodynamique du SI. Il est défini en
prenant la valeur numérique fixée de la constante de Boltzmann(((constante, de Boltzmann))), stem:[k], égale à stem:[1.380649 xx 10^{-23}]
lorsqu’elle est exprimée en stem:[rm(J)" "rm(K)^{-1}], unité égale à stem:[rm(kg)" "rm(m)^2 " "rm(s)^{-2} " "rm(K)^{-1}], le ((kilogramme)), le mètre et la
seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}].
(((nombre d’Avogadro)))(((quantité de matière)))

* La mole, symbole stem:[rm(mol)], est l’unité de quantité de matière du SI. Une mole contient exactement
stem:[6.02214076 xx 10^23] entités élémentaires. Ce nombre, appelé «&nbsp;nombre d’Avogadro&nbsp;»,
correspond à la valeur numérique fixée de la constante d’Avogadro(((constante, d'Avogadro))), stem:[ii(N)_"A"], lorsqu’elle est
exprimée en stem:[rm(mol)^{-1}].
+
--
La quantité de matière(((quantité de matière))), symbole stem:[n], d’un système est une représentation du nombre d’entités
élémentaires spécifiées. Une entité élémentaire peut être un atome, une molécule, un ion,
un électron, ou toute autre particule ou groupement spécifié de particules.
--
* La candela, symbole cd, est l’unité du SI d’intensité lumineuse dans une direction donnée.
Elle est définie en prenant la valeur numérique fixée de l’efficacité lumineuse d’un
((rayonnement monochromatique)) de fréquence stem:[540 xx 10^(12) " "rm(Hz)], stem:[ii(K)_("cd")], égale à 683 lorsqu’elle est
exprimée en stem:[rm(lm)" "rm(W)^{-1}], unité égale à stem:[rm(cd)" "rm(sr)" "rm(W)^{-1}], ou stem:[rm(cd)" "rm(sr)" "rm(kg)^{-1} " "rm(m)^{-2} " "rm(s)^3], le ((kilogramme)), le mètre et
la seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}]. [[kilogramme-3]] [[kilogramme_prototype-3]]
