== Measurement of photochemical or photobiological quantities and their corresponding units

The photometric quantities and photometric units which are defined for vision are well established and have been widely used for a long time. They are not affected by the following rules. For all other photochemical and photobiological quantities the rules given below shall be applied for defining the units to be used. This method was recommended by the Consultative Committee for Photometry and Radiometry at its 9th meeting in 1977 for use with action spectra expressed in terms of the spectral radiometric system and was contained in Appendix 3 of the 8th SI brochure. The CCPR at its 23rd meeting in 2016 recommended that this wording be revised for the on-line version of this Appendix in the 9th SI brochure to clarify the use of action spectra expressed in terms of the spectral photon system as well as the spectral radiometric system.

A photochemical or photobiological quantity is defined in purely physical terms as the quantity derived from the corresponding radiant quantity by evaluating the radiation according to its action upon a selective receptor, the spectral sensitivity of which is defined by the action spectrum of the photochemical or photobiological effect considered. The quantity is given by the integral over wavelength of the spectral distribution of the radiant quantity weighted by the appropriate weighting function. The use of integrals implicitly assumes a law of arithmetic additivity for photochemical or photobiological quantities, although such a law is often not perfectly obeyed by actual effects. The weighting function is a relative quantity; it is dimensionless, with the SI unit one. The radiant quantity has the radiometric unit corresponding to that quantity. Thus, following the rule for obtaining the SI unit for a derived quantity, the unit of the photochemical or photobiological quantity is the radiometric unit of the corresponding radiant quantity; this also means that for compliance with the SI, the efficacy constant is unity. When giving a quantitative value, it is essential to specify whether a radiometric or spectrally weighted quantity is intended, as the unit is the same. If a given photochemical or photobiological effect exists in several action spectra, the action spectrum used for measurement has to be clearly specified.

As an example, the erythemal irradiance, stem:[ii(E)_("er")], from a source of ultraviolet radiation is obtained by weighting the spectral irradiance at wavelength stem:[ii(lambda)] by the effectiveness of radiation at this wavelength to cause an erythema and summing over all wavelengths present in the source spectrum over the full wavelength range of the action spectrum. This can be expressed mathematically as:

[[eq-a-3-1]]
[stem]
++++
ii(E)_("er") = int ii(E)_(ii(lambda))(ii(lambda)) s_("er")(ii(lambda)) "d" ii(lambda)
++++

where stem:[ii(E)_(ii(lambda))(ii(lambda))] is the spectral irradiance at wavelength stem:[ii(lambda)] (usually reported in the SI unit stem:["unitsml(W*m^(-2)*nm^(-1))"]), and stem:[s_("er")(ii(lambda))] is the erythema spectral weighting function expressed in the spectral radiometric system and normalized to 1 at its maximum spectral value. The erythemal irradiance, stem:[ii(E)_("er")], determined this way is reported in the SI unit stem:["unitsml(W*m^(−2))"].