=== Conversion of action spectra between spectral radiometric system and spectral photon system

As described above, in photochemistry and photobiology optical radiation measurements may be performed in terms of the spectral power distribution or the spectral photon distribution. If an effect is purely actinic, i.e. a purely chemical/molecular interaction, the magnitude of the effect is governed by the number of photons absorbed and thus the weighting function in the spectral photon system is proportional to the absorption spectrum of the actinic material. In this case, it is necessary to apply a conversion to the absorption spectrum before it can be used in the spectral power distribution system. In contrast, if an effect is purely thermal, i.e. related to heating without a chemical change and hence dependent on the energy absorbed, the weighting function in the spectral radiometric system is proportional to the absorption spectrum; in this case a conversion must be applied to the absorption spectrum to allow use in the spectral photon system.

Photochemical and photobiological quantities may be determined using either the spectral radiometric system or the spectral photon system, so it is essential not only to apply the correct weighting function but also to make clear the system being used when describing the quantity. Thus by analogy to <<eq-a-3-1>>, the erythema caused by a source of ultraviolet radiation can be characterized in the units of the spectral photon distribution system using the erythemal photon irradiance:

[[eq-a-3-2]]
[stem]
++++
E_(p,er) = int E_(p,lambda)(lambda) s_(p,er)(lambda) d lambda
++++

where stem:[E_(p,lambda)(lambda)] is the spectral photon flux footnote:[Photon flux is the number of photons emitted, transmitted or received per unit time interval, usually reported in the unit s^−1^].] per unit area at wavelength stem:[lambda] (usually reported in the unit stem:[s^(−1) m^(−2) nm^(−1)]), and stem:[s_(p,er)(lambda)] is the erythema spectral weighting function expressed in the spectral photon distribution system and normalized to 1 at its maximum spectral value. The erythemal *photon* irradiance, stem:[E_(p,er)], determined in this way is usually reported in the unit stem:[s^(−1) m^(−2)], as the number of photons is dimensionless.

It follows directly from the above equations that the relationship between the expressions for the spectrally weighted quantity in the two systems depends on both the spectral shape of stem:[E_(lambda)(lambda)] and the action spectrum. However, for a general response process A, the relationship between the shapes of the two spectral weighting functions stem:[s_(p,A)(lambda)] and stem:[s_(e,A)(lambda)] (in the photon system and radiometric system, respectively) that can be used to describe the effect is governed by:

[[eq-a-3-3]]
[stem]
++++
s_(p,A)(lambda) = gamma_A * (hc)/(lambda) * n_a(lambda) * s_(e,A)(lambda)
++++

where stem:[gamma_A] is a constant (reported in units of stem:[J^(−1)]), independent of the spectral irradiance, stem:[E_(lambda)(lambda)], that satisfies the requirement to set the maximum values of stem:[s_(p,A)(lambda)] to 1, stem:[h] is the Planck constant, stem:[c] is the speed of light in vacuum, and stem:[n_a(lambda)] is the refractive index in air footnote:[Action spectra are defined in terms of the magnitude of the effect as a function of wavelength. The wavelength of radiation depends on the refractive index of the medium, meaning that the value of the action spectrum at any stated wavelength will vary depending on the medium for which that wavelength is determined. In general, the medium under consideration is air and the CIE action spectra mentioned above apply for wavelengths measured in air.] at the given wavelength, stem:[lambda]. It should be noted that the two spectral weighting functions stem:[s_(p,A)(lambda)] and stem:[s_(e,A)(lambda)] describing the same effect are different in form, and the peak wavelength of the effect is different when expressed in photon quantities or radiometric quantities.
