
<<<

[type=toc]
== Table des matières de l’annexe 1

=== Décisions concernant l'établissement du SI (((système,international d’unités (SI)))) (((système,international d’unités (SI),création)))

* <<cgpm9e1948r6,9^e^ CGPM, 1948:pass:[<tab/>]décision d'établir le SI>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]décision d'adopter les six premières unités de base>>

* <<cipm1956r3,CIPM, 1956:pass:[<tab/>]décision d'adopter le nom Système international d'unités>>

* <<cgpm11e1960r12,11^e^ CGPM, 1960:pass:[<tab/>]confirmation du nom et de l'abréviation SI, noms des préfixes téra à pico, établissement des unités supplémentaires stem:["unitsml(rad)"] et stem:["unitsml(sr)"], établissement de la liste de certaines unités dérivées>>

* <<cipm1969r1,CIPM, 1969:pass:[<tab/>]déclarations concernant les unités de base, supplémentaires, dérivées et cohérentes, et utilisation des préfixes>>

* <<cipm_unites_si,CIPM, 2001:pass:[<tab/>]«{nbsp}unités SI{nbsp}» et «{nbsp}unités du SI{nbsp}»>>

* <<cgpm23e2007r12,23^e^ CGPM, 2007:pass:[<tab/>]éventuelle redéfinition de certaines unités de base du Système international d'unités (SI)>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm25e2014r1,25^e^ CGPM, 2014:pass:[<tab/>]révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

=== Décisions concernant les unités de base du SI

==== Longueur (((longueur)))(((mètre (stem:["unitsml(m)"])))

* <<cgpm1re1889sanction,1^re^ CGPM, 1889:pass:[<tab/>]sanction du Prototype du mètre>>

* <<cgpm7e1927metre,7^e^ CGPM, 1927:pass:[<tab/>]définition du mètre par le Prototype international>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption du mètre comme unité de base>>

* <<cgpm11e1960r6,11^e^ CGPM, 1960:pass:[<tab/>]redéfinition du mètre au moyen de la radiation du krypton 86>>

* <<cgpm15e1975r2,15^e^ CGPM, 1975:pass:[<tab/>]recommandation de la valeur de la vitesse de la lumière>>

* <<cgpm17e1983r1,17^e^ CGPM, 1983:pass:[<tab/>]redéfinition du mètre en fonction de la vitesse de la lumière, mise en pratique de la définition du mètre>>

* <<cipm2002r1,CIPM, 2002:pass:[<tab/>]révision de la mise en pratique de la définition du mètre>>

* <<cipm2003r1,CIPM, 2003:pass:[<tab/>]révision de la liste des radiations recommandées>>

* <<cipm2005r3,CIPM, 2005:pass:[<tab/>]révision de la liste des radiations recommandées>>

* <<cipm2007r1,CIPM, 2007:pass:[<tab/>]révision de la liste des radiations recommandées>>

* <<cgpm23e2007r9,23^e^ CGPM, 2007:pass:[<tab/>]révision de la mise en pratique de la définition du mètre et mise au point de nouveaux étalons optiques de fréquence>>

* <<cipm2009r2,CIPM, 2009:pass:[<tab/>]mises à jour de la liste des fréquences étalons>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm24e2011r8,24^e^ CGPM, 2011:pass:[<tab/>]révision de la mise en pratique de la définition du mètre et mise au point de nouveaux étalons optiques de fréquence>>

* <<cipm2013r1,CIPM, 2013:pass:[<tab/>]mises à jour de la liste des fréquences étalons>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Masse (((masse)))

* <<cgpm1re1889sanction,1^re^ CGPM, 1889:pass:[<tab/>]sanction du Prototype du kilogramme>>

* <<cgpm3e1901mass,3^e^ CGPM, 1901:pass:[<tab/>]déclaration au sujet de la différence entre masse et poids, et valeur conventionnelle de stem:[g_{"n"}]>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption du kilogramme comme unité de base>>

* <<cipm1967r2,CIPM, 1967:pass:[<tab/>]déclaration sur les préfixes du gramme>>

* <<cgpm21e1999r7,21^e^ CGPM, 1999:pass:[<tab/>]redéfinition éventuelle du kilogramme>>

* <<cgpm23e2007r12,23^e^ CGPM, 2007:pass:[<tab/>]éventuelle redéfinition de certaines unités de base du Système international d'unités (SI)>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm25e2014r1,25^e^ CGPM, 2014:pass:[<tab/>]révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Temps (((seconde)))(((temps,durée)))

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption de la seconde comme unité de base>>

* <<cipm1956r1,CIPM, 1956:pass:[<tab/>]définition de la seconde comme la fraction de l'année tropique 1900>>

* <<cgpm11e1960r9,11^e^ CGPM, 1960:pass:[<tab/>]ratification de la définition de la seconde donnée par le CIPM en 1956>>

* <<cipm1964freq,CIPM, 1964:pass:[<tab/>]déclaration selon laquelle l'étalon à employer est la transition hyperfine du césium 133>>

* <<cgpm12e1964r5,12^e^ CGPM, 1964:pass:[<tab/>]pouvoir au CIPM de désigner les étalons de fréquence atomique et moléculaire à employer>>

* <<cgpm13e1968r1,13^e^ CGPM, 1967/68:pass:[<tab/>]définition de la seconde au moyen de la transition du césium>>

* <<ccds-tai-definition,CCDS, 1970:pass:[<tab/>]définition du Temps atomique international, TAI>>

* <<cgpm14e1971r1,14^e^ CGPM, 1971:pass:[<tab/>]demande au CIPM de définir et d'établir le Temps atomique international, TAI>>

* <<cgpm15e1975r5,15^e^ CGPM, 1975:pass:[<tab/>]sanction du Temps universel coordonné, UTC>>

* <<cipm2006r1,CIPM, 2006:pass:[<tab/>]représentations secondaires de la seconde>>

* <<cgpm23e2007r9,23^e^ CGPM, 2007:pass:[<tab/>]révision de la mise en pratique de la définition du mètre et mise au point de nouveaux étalons optiques de fréquence>>

* <<cipm2009r2,CIPM, 2009:pass:[<tab/>]mises à jour de la liste des fréquences étalons>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm24e2011r8,24^e^ CGPM, 2011:pass:[<tab/>]révision de la mise en pratique de la définition du mètre et mise au point de nouveaux étalons optiques de fréquence>>

* <<cipm2013r1,CIPM, 2013:pass:[<tab/>]mises à jour de la liste des fréquences étalons>>

* <<cipm2015r2,CIPM, 2015:pass:[<tab/>]mises à jour de la liste des fréquences étalons>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Unités électriques (((unité(s),électriques)))

* <<cipm1946r2,CIPM, 1946:pass:[<tab/>]définition des unités électriques cohérentes dans le système d'unités ((MKS)) (mètre-kilogramme-seconde)  (mise en œuvre le 1^er^ janvier 1948)>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption de l'ampère(((ampère (stem:["unitsml(A)"])))) comme unité de base>>

* <<cgpm14e1971siemens,14^e^ CGPM, 1971:pass:[<tab/>]adoption du nom siemens, symbole stem:["unitsml(S)"], pour la conductance électrique>>

* <<cgpm18e1987r6,18^e^ CGPM, 1987:pass:[<tab/>]ajustement prévu des représentations du volt et de l'ohm>>

* <<cipm1988r1,CIPM, 1988:pass:[<tab/>]définition de la valeur conventionnelle de la constante de  Josephson(((constante, de Josephson (stem:[ii(K)_"J"," "ii(K)_"J-90"])))) (mise en œuvre le 1^er^ janvier 1990)>>

* <<cipm1988r2,CIPM, 1988:pass:[<tab/>]définition de la valeur conventionnelle de la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K",ii(R)_"K-90"])))) (mise en œuvre le 1^er^ janvier 1990)>>

* <<cgpm23e2007r12,23^e^ CGPM, 2007:pass:[<tab/>]éventuelle redéfinition de certaines unités de base du Système international d'unités (SI)>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm25e2014r1,25^e^ CGPM, 2014:pass:[<tab/>]révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Température thermodynamique (((température,thermodynamique)))

* <<cgpm9e1948r3,9^e^ CGPM, 1948:pass:[<tab/>]adoption du point triple de l'eau comme point de référence pour la température thermodynamique, adoption du degré Celsius, et définition du zéro comme étant la température de référence inférieure de 0,01 degré à celle du point triple de l'eau>>

* <<cipm1948,CIPM, 1948:pass:[<tab/>]adoption du nom degré Celsius pour l'échelle de température Celsius>>

* <<cgpm10e1954r3,10^e^ CGPM, 1954:pass:[<tab/>]définition de la température thermodynamique du point triple de l'eau à 273,16 degrés Kelvin exactement, définition de l'((atmosphère normale))>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption du degré Kelvin comme unité de base>>

* <<cgpm13e1968r3,13^e^ CGPM, 1967/68:pass:[<tab/>]définition officielle du kelvin, symbole stem:["unitsml(K)"]>>

* <<cipm1989r5,CIPM, 1989:pass:[<tab/>]Échelle internationale de température de 1990, EIT-90>>

* <<cipm2005r2,CIPM, 2005:pass:[<tab/>]note ajoutée à la définition du kelvin à propos de la composition isotopique de l'eau>>

* <<cgpm23e2007r10,23^e^ CGPM, 2007:pass:[<tab/>]clarification de la définition du kelvin, unité de température thermodynamique>>

* <<cgpm23e2007r12,23^e^ CGPM, 2007:pass:[<tab/>]éventuelle redéfinition de certaines unités de base du Système international d'unités (SI)>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm25e2014r1,25^e^ CGPM, 2014:pass:[<tab/>]révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Quantité de matière (((quantité de matière)))

* <<cgpm14e1971r3,14^e^ CGPM, 1971:pass:[<tab/>]définition de la mole(((mole (stem:["unitsml(mol)"])))), symbole mol, comme 7^e^ unité de base, et règles d'utilisation>>

* <<cgpm21e1999r12,21^e^ CGPM, 1999:pass:[<tab/>]adoption du nom spécial katal, stem:["unitsml(kat)"]>>

* <<cgpm23e2007r12,23^e^ CGPM, 2007:pass:[<tab/>]éventuelle redéfinition de certaines unités de base du Système international d'unités (SI)>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm25e2014r1,25^e^ CGPM, 2014:pass:[<tab/>]révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

==== Intensité lumineuse (((intensité lumineuse))) (((lumen (stem:["unitsml(lm)"]))))

* <<cipm1946photo,CIPM, 1946:pass:[<tab/>]définition des unités photométriques, bougie nouvelle(((bougie nouvelle))) et lumen nouveau (mise en œuvre le 1^er^ janvier 1948)>>

* <<cgpm10e1954r6,10^e^ CGPM, 1954:pass:[<tab/>]adoption de la candela(((candela (stem:["unitsml(cd)"])))) comme unité de base>>

* <<cgpm13e1968r5,13^e^ CGPM, 1967/68:pass:[<tab/>]définition de la candela(((candela (stem:["unitsml(cd)"])))), symbole stem:["unitsml(cd)"], en fonction du corps noir>>

* <<cgpm16e1979r3,16^e^ CGPM, 1979:pass:[<tab/>]redéfinition de la candela(((candela (stem:["unitsml(cd)"])))) à partir d'un ((rayonnement monochromatique))>>

* <<cgpm24e2011r1,24^e^ CGPM, 2011:pass:[<tab/>]éventuelle révision à venir du Système international d'unités, le SI>>

* <<cgpm26th2018r1,26^e^ CGPM, 2018:pass:[<tab/>]révision du Système international d'unités (SI) (mise en œuvre le 20 mai 2019)>>

=== Décisions concernant les unités SI dérivées et les unités supplémentaires (((unité(s),dérivées)))
==== Unités SI dérivées

* <<cgpm12e1964r5,12^e^ CGPM, 1964:pass:[<tab/>]décision d'accepter de continuer à utiliser le curie comme unité en dehors du SI>>

* <<cgpm13e1967r6,13^e^ CGPM, 1967/68:pass:[<tab/>]exemples d'unités dérivées>>

* <<cgpm15e1975r8_9,15^e^ CGPM, 1975:pass:[<tab/>]adoption des noms spéciaux becquerel(((becquerel (stem:["unitsml(Bq)"])))), stem:["unitsml(Bq)"], et gray(((gray (stem:["unitsml(Gy)"])))), stem:["unitsml(Gy)"]>>

* <<cgpm16e1979r5,16^e^ CGPM, 1979:pass:[<tab/>]adoption du nom spécial sievert(((sievert (stem:["unitsml(Sv)"])))), stem:["unitsml(Sv)"]>>

* <<cipm1984r1,CIPM, 1984:pass:[<tab/>]décision de clarifier les relations entre la dose absorbée (unité SI gray) et l'équivalent de dose (unité SI sievert)(((sievert (stem:["unitsml(Sv)"]))))>>

* <<cipm2002r2,CIPM, 2002:pass:[<tab/>]modification des relations entre la dose absorbée et l'équivalent de dose>>

==== Unités supplémentaires

* <<cipm1980r1,CIPM, 1980:pass:[<tab/>]décision d'interpréter les unités supplémentaires comme des unités dérivées sans dimension>>

* <<cgpm20e1995r8,20^e^ CGPM, 1995:pass:[<tab/>]décision de supprimer la classe des unités supplémentaires, et confirmation de l'interprétation du CIPM selon laquelle ce sont des unités dérivées sans dimension>>

=== Décisions concernant la terminologie et approbation des unités en usage avec le SI
==== Préfixes SI (((préfixes SI)))

* <<cgpm12e1964r8,12^e^ CGPM, 1964:pass:[<tab/>]décision d'ajouter femto et atto à la liste des préfixes>>

* <<cgpm15e1975r10,15^e^ CGPM, 1975:pass:[<tab/>]décision d'ajouter péta et exa à la liste des préfixes>>

* <<cgpm19e1991r4,19^e^ CGPM, 1991:pass:[<tab/>]décision d'ajouter zetta, zepto, yotta et yocto à la liste des préfixes>>

==== Symboles d'unités et nombres

* <<cgpm9e1948r7,9^e^ CGPM, 1948:pass:[<tab/>]décision sur les règles d'écriture des symboles d'unités et des nombres>>

==== Noms d'unités

* <<cgpm13e1968r7,13^e^ CGPM, 1967/68:pass:[<tab/>]abrogation de l'utilisation du micron et de la bougie nouvelle(((bougie nouvelle))) comme unités en usage avec le SI>>

==== Séparateur décimal (((séparateur décimal)))

* <<cgpm22e2003r10,22^e^ CGPM, 2003:pass:[<tab/>]décision d'autoriser l'usage du point ou de la virgule sur la ligne comme séparateur décimal>>

==== Unités en usage avec le SI{nbsp}: un exemple, le litre(((litre (stem:["unitsml(L)"] ou stem:["unitsml(l)"]))))

* <<cgpm3e1901litre,3^e^ CGPM, 1901:pass:[<tab/>]définition du litre comme le volume d'stem:[1 "unitsml(kg)"] d'eau>>

* <<cgpm11e1960r13,11^e^ CGPM, 1960:pass:[<tab/>]demande au CIPM d'étudier la différence entre le décimètre cube et le litre>>

* <<cipm1961litre,CIPM, 1961:pass:[<tab/>]recommandation d'exprimer les volumes en unités SI et non en litres>>

* <<cgpm12e1964r6,12^e^ CGPM, 1964:pass:[<tab/>]abrogation de la précédente définition du litre et recommandation d'utiliser le litre comme nom spécial donné au décimètre cube>>

* <<cgpm16e1979r6,16^e^ CGPM, 1979:pass:[<tab/>]décision, à titre exceptionnel, d'autoriser les deux symboles L et l pour le litre>>


<<<
