[[cgpm26th2018]]
[%unnumbered]
== 26th CGPM, 2018

[[cgpm26th2018r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Sur la révision du Système international d’unités (SI)* (CR, 210 et <<Met_56_2_022001,_Metrologia_, 2019, *56*, 022001>>)

[[cgpm26th2018r1r1]]
==== Résolution 1
____

La Conférence générale des poids et mesures (CGPM), à sa 26^e^ réunion,
index-range:kilogramme_prototype-3[(((kilogramme,prototype international)))]

*considérant*

* qu’il est essentiel de disposer d’un Système international d’unités (SI) uniforme et accessible
dans le monde entier, pour le commerce international, l’industrie de haute technologie, la santé
humaine et la sécurité, la protection de l’environnement, les études sur l’évolution du climat,
ainsi que la science fondamentale qui étaye tous ces domaines,

* que les unités du SI doivent être stables sur le long terme, auto cohérentes et réalisables
dans la pratique, en étant fondées sur la description théorique actuelle de la nature, au plus
haut niveau,

* qu’une révision du SI visant à satisfaire ces exigences a été proposée dans la Résolution 1
adoptée à l’unanimité par la CGPM à sa 24^e^ réunion (2011), qui expose en détail une
nouvelle façon de définir le SI à partir d’un ensemble de sept constantes, choisies parmi les
constantes fondamentales(((constante, fondamentale (de la physique)))) de la physique et d’autres constantes de la nature, à partir
desquelles les définitions des sept unités de base sont déduites,

* que les conditions requises par la CGPM à sa 24^e^ réunion (2011), confirmées à sa
25^e^ réunion (2014), pour procéder à l’adoption d’une telle révision du SI sont désormais
remplies,

*décide*
(((unité(s),de base)))

qu’à compter du 20 mai 2019, le Système international d’unités, le SI, est le système d’unités
selon lequel{nbsp}:

* la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium((("atome de césium, niveaux hyperfins")))
133 non perturbé, stem:[Delta ii(nu)_{"Cs"}], est égale à stem:[9192631770 "unitsml(Hz)"],
* la ((vitesse de la lumière dans le vide)), stem:[c], est égale à stem:[299792458 "unitsml(m/s)"],
* la constante de Planck(((constante, de Planck))), stem:[h], est égale à stem:[6.62607015 xx 10^{-34} "unitsml(J)" " " "unitsml(s)"],
* la charge élémentaire, stem:[e], est égale à stem:[1.602176634 xx 10^(-19) "unitsml(C)"],
* la constante de Boltzmann(((constante, de Boltzmann))), stem:[k], est égale à stem:[1.380649 xx 10^{-23} "unitsml(J/K)"],
* la constante d’Avogadro(((constante, d'Avogadro))), stem:[ii(N)_"A"], est égale à stem:[6.02214076 xx 10^(23) "unitsml(mol^(-1))"],
* l’efficacité lumineuse d’un ((rayonnement monochromatique)) de fréquence
stem:[540 xx 10^(12) "unitsml(Hz)"], stem:[ii(K)_{"cd"}], est égale à stem:[683 "unitsml(lm/W)"],
(((hertz (stem:["unitsml(Hz)"]))))(((joule (stem:["unitsml(J)"]))))(((kelvin (stem:["unitsml(K)"]))))(((lumen (stem:["unitsml(lm)"]))))(((watt (stem:["unitsml(W)"]))))
index-range:kilogramme-3[(((kilogramme)))]

où les unités hertz, joule, coulomb(((coulomb (stem:["unitsml(C)"])))), lumen et watt, qui ont respectivement pour symbole stem:["unitsml(Hz)", "unitsml(J)", "unitsml(C)", "unitsml(lm)"] et stem:["unitsml(W)"], sont reliées aux unités seconde, mètre, kilogramme, ampère(((ampère (stem:["unitsml(A)"])))), kelvin, mole et candela(((candela (stem:["unitsml(cd)"])))),
qui ont respectivement pour symbole stem:["unitsml(s)", "unitsml(m)", "unitsml(kg)", "unitsml(A)", "unitsml(K)", "unitsml(mol)"] et stem:["unitsml(cd)"], selon les relations, stem:["unitsml(J)" = "unitsml(kg*m^2*s^(-2))"],
stem:["unitsml(C)" = "unitsml(A)""unitsml(s)"], stem:["unitsml(lm)" = "unitsml(cd*m^2*m^(-2))" = "unitsml(cd*sr)"], et stem:["unitsml(W)" = "unitsml(kg*m^2*s^(-3))"],

*prend acte* des conséquences de la révision du SI concernant les unités de base du SI,
énoncées dans la Résolution 1 adoptée par la CGPM à sa 24^e^ réunion (2011), et les confirme
dans les annexes de la présente résolution, qui ont même force que la résolution elle-même,

*invite* le Comité international des poids et mesures (CIPM) à publier une nouvelle édition de la
_Brochure sur le SI_, «{nbsp}Le Système international d’unités{nbsp}», contenant une description complète du
SI révisé.
____


===== Annexe 1. Abrogation des précédentes définitions des unités de base

____
Il résulte de la nouvelle définition du SI décrite ci-dessus qu’à compter du 20 mai 2019{nbsp}:

* la définition de la seconde en vigueur depuis 1967/68 (13^e^ réunion de la CGPM,
Résolution 1) est abrogée,
* la définition du mètre(((mètre (stem:["unitsml(m)"])))) en vigueur depuis 1983 (17^e^ réunion de la CGPM, Résolution 1)
est abrogée,
* la définition du kilogramme en vigueur depuis 1889 (1^ère^ réunion de la CGPM, 1889,
3^e^ réunion de la CGPM, 1901), établie à partir de la masse du prototype international du
kilogramme, est abrogée,
* la définition de l’ampère(((ampère (stem:["unitsml(A)"])))) en vigueur depuis 1948 (9^e^ réunion de la CGPM), établie à partir de
la définition proposée par le CIPM (1946, Résolution 2), est abrogée,
* la définition du kelvin en vigueur depuis 1967/68 (13^e^ réunion de la CGPM, Résolution 4)
est abrogée,
* la définition de la mole en vigueur depuis 1971 (14^e^ réunion de la CGPM, Résolution 3)
est abrogée,
* la définition de la candela en vigueur depuis 1979 (16^e^ réunion de la CGPM, Résolution 3)
est abrogée,
(((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))
(((volt (stem:["unitsml(V)"]))))

* la décision d’adopter les valeurs conventionnelles de la constante de Josephson stem:[ii(K)_{"J–90"}] et de
la constante de von Klitzing(((constante, de von Klitzing (stem:[ii(R)_"K",ii(R)_"K-90"])))) stem:[ii(R)_{"K–90"}], prise par le CIPM (1988, Recommandations 1 et 2)
à la demande de la CGPM (18^e^ réunion de la CGPM, 1987, Résolution 6) pour
l’établissement des représentations du volt et de l’ohm à l’aide des effets Josephson et Hall
quantique, respectivement, est abrogée.
____


===== Annexe 2. Statut des constantes utilisées antérieurement dans les anciennes définitions

____
Il résulte de la nouvelle définition du SI décrite ci-dessus, et des valeurs recommandées dans
l’ajustement spécial de 2017 du Committee on Data for Science and Technology (CODATA),
sur lesquelles se fondent les valeurs des constantes choisies pour définir le SI, qu’à compter du
20 mai 2019{nbsp}:

* la ((masse)) du prototype international du ((kilogramme)), stem:[m(cc "K")], est égale à stem:[1 "unitsml(kg)"] avec une
incertitude-type relative égale à celle de la valeur recommandée de stem:[h] au moment de
l’adoption de la présente résolution, à savoir stem:[1.0 xx 10^{-8}]{nbsp}; dans le futur, sa valeur sera
déterminée de façon expérimentale,
* la perméabilité magnétique du vide(((constante, magnétique&#44; perméabilité du vide))), stem:[ii(mu)_0], est égale à stem:[4 pi xx 10^(-7) "unitsml(H*m^(-1))"] avec une incertitude-type
relative égale à celle de la valeur recommandée de la constante de structure fine(((constante, de structure fine))) stem:[alpha]
au moment de l’adoption de la présente résolution, à savoir stem:[2.3 xx 10^{-10}]{nbsp}; dans le futur,
sa valeur sera déterminée de façon expérimentale,
* la température thermodynamique du ((point triple de l’eau)), stem:[ii(T)_{"TPW"}], est égale à stem:[273.16 "unitsml(K)"] avec
une incertitude-type relative presque égale à celle de la valeur recommandée de stem:[k]
au moment de l’adoption de la présente résolution, à savoir stem:[3.7 xx 10^{-7}]{nbsp}; dans le futur, sa
valeur sera déterminée de façon expérimentale,
* la ((masse)) molaire(((masse molaire))) du ((carbone)) 12, stem:[ii(M)(""^{12}"C")], est égale à stem:[0.012 "unitsml(kg*mol^(-1))"] avec une incertitude-type
relative égale à celle de la valeur recommandée de stem:[ii(N)_"A"h] au moment de l’adoption de la
présente résolution, à savoir stem:[4.5 xx 10^{-10}]{nbsp}; dans le futur, sa valeur sera déterminée de façon
expérimentale.
____


===== Annexe 3. Les unités de base du SI

____
La nouvelle définition du SI décrite ci-dessus, fondée sur les valeurs numériques fixées des
constantes choisies, permet de déduire la définition de chacune des sept unités de base du SI à
l’aide d’une ou plusieurs de ces constantes, selon les cas. Les définitions qui en découlent,
qui prendront effet à compter du 20 mai 2019, sont les suivantes{nbsp}:

* La seconde, symbole stem:["unitsml(s)"], est l’unité de temps du SI. Elle est définie en prenant la valeur
numérique fixée de la ((fréquence du césium)), stem:[Delta nu_{"Cs"}], la fréquence de la transition hyperfine de
l’état fondamental de l’atome de césium((("atome de césium, niveaux hyperfins"))) 133 non perturbé, égale à stem:[9192631770] lorsqu’elle
est exprimée en stem:["unitsml(Hz)"], unité égale à stem:["unitsml(s^(-1))"].

* Le mètre, symbole stem:["unitsml(m)"], est l’unité de longueur du SI. Il est défini en prenant la valeur
numérique fixée de la ((vitesse de la lumière dans le vide)), stem:[c], égale à stem:[299792458] lorsqu’elle
est exprimée en stem:["unitsml(m/s)"], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le ((kilogramme)), symbole stem:["unitsml(kg)"], est l’unité de masse du SI. Il est défini en prenant la valeur
numérique fixée de la constante de Planck(((constante, de Planck))), stem:[h], égale à stem:[6.62607015 xx 10^{-34}] lorsqu’elle est
exprimée en stem:["unitsml(J*s)"], unité égale à stem:["unitsml(kg*m^2*s^(-1))"], le mètre et la seconde étant définis en fonction de stem:[c]
et stem:[Delta ii(nu)_{"Cs"}].

* L’ampère(((ampère (stem:["unitsml(A)"])))), symbole stem:["unitsml(A)"], est l’unité de ((courant électrique)) du SI. Il est défini en prenant la valeur
numérique fixée de la charge élémentaire, stem:[e], égale à stem:[1.602176634 xx 10^(-19)] lorsqu’elle est
exprimée en stem:["unitsml(C)"], unité égale à stem:["unitsml(A*s)"], la seconde étant définie en fonction de stem:[Delta ii(nu)_{"Cs"}].

* Le kelvin(((kelvin (stem:["unitsml(K)"])))), symbole stem:["unitsml(K)"], est l’unité de température thermodynamique du SI. Il est défini en
prenant la valeur numérique fixée de la constante de Boltzmann(((constante, de Boltzmann))), stem:[k], égale à stem:[1.380649 xx 10^{-23}]
lorsqu’elle est exprimée en stem:["unitsml(J*K^(-1))"], unité égale à stem:["unitsml(kg*m^2*s^(-2)*K^(-1))"], le ((kilogramme)), le mètre et la
seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}].
(((nombre d’Avogadro)))(((quantité de matière)))

* La mole, symbole stem:["unitsml(mol)"], est l’unité de quantité de matière du SI. Une mole contient exactement
stem:[6.02214076 xx 10^23] entités élémentaires. Ce nombre, appelé «{nbsp}nombre d’Avogadro{nbsp}»,
correspond à la valeur numérique fixée de la constante d’Avogadro(((constante, d'Avogadro))), stem:[ii(N)_"A"], lorsqu’elle est
exprimée en stem:["unitsml(mol^(-1))"].
+
--
La quantité de matière(((quantité de matière))), symbole stem:[n], d’un système est une représentation du nombre d’entités
élémentaires spécifiées. Une entité élémentaire peut être un atome, une molécule, un ion,
un électron, ou toute autre particule ou groupement spécifié de particules.
--
* La candela, symbole stem:["unitsml(cd)"], est l’unité du SI d’intensité lumineuse dans une direction donnée.
Elle est définie en prenant la valeur numérique fixée de l’efficacité lumineuse d’un
((rayonnement monochromatique)) de fréquence stem:[540 xx 10^(12) "unitsml(Hz)"], stem:[ii(K)_("cd")], égale à 683 lorsqu’elle est
exprimée en stem:["unitsml(lm*W)"^(-1)], unité égale à stem:["unitsml(cd*sr*W^(-1))"], ou stem:["unitsml(cd*sr*kg^(-1)*m^(-2)*s^3)"], le ((kilogramme)), le mètre et
la seconde étant définis en fonction de stem:[h], stem:[c] et stem:[Delta ii(nu)_{"Cs"}]. [[kilogramme-3]] [[kilogramme_prototype-3]]
____
