== The historical development of the realization of SI units
index-range:realization_unit-3[(((realization of a unit)))]

Experimental methods used for the realization of units and which use equations of physics are known as primary methods. The essential characteristic of a primary method is that it allows a quantity to be measured in a particular unit directly from its definition by using only quantities and constants that themselves do not contain that unit.

(((length)))
Traditionally, a unit for a given quantity was taken to be a particular example of that quantity, which was chosen to provide numerical values of common measurements of a convenient size. Before the rise of modern science, units were necessarily defined in terms of material artefacts, notably the metre and kilogram for length and mass, or the property of a particular object, namely the rotation of the earth for the second. Even at the origin of the ((metric system)) at the end of the 18th century it was recognized that a more desirable definition of a unit of length for example would be one based on a universal property of nature such as the length of a pendulum beating seconds. Such a definition would be independent of time and place and would in principle accessible all over the world. At the time, practical considerations resulted in the simpler, artefact definitions for the metre and the kilogram and the second remained linked to the rotation of the Earth. It was only in 1960 that the first non-material definition was adopted, namely the wavelength of a specified optical radiation for the metre.

Since then, definitions of the ampere(((ampere (A)))), kelvin, mole(((mole (mol)))) and candela(((candela (cd)))) have been adopted that do not refer to material artefacts. In the case of the ampere(((ampere (A)))) it refers to a specified ((electric current)) required to produce a given electromagnetic force and, in the case of the kelvin, to a particular thermodynamic state, namely the triple point of water. Even the atomic definition of the second was in terms of a specified transition of the the caesium atom. The kilogram has always stood out as the one unit that had resisted the transformation from an artefact. The definition that opened the way to real universality was that of the metre in 1983. This definition implied, although it did not state, a fixed numerical value for the speed of light. The definition was worded, however, in the traditional form and stated essentially that the metre was the distance travelled by light in a specified time. In this way it reflected the other definitions of the base units(((base unit(s)))) of the SI each of which has the same form, for example "the ampere(((ampere (A)))) is the current which..." and "the kelvin is a fraction of a specified temperature". Such definitions can be called explicit unit definitions. (((explicit unit definition)))

Although these definitions meet many of the requirements for universality and accessibility, and a variety of realizations are often possible, they nevertheless constrain practical realizations to experiments that are directly or indirectly linked to the particular conditions or states specified in each definition. In consequence, the accuracy of realization of such definitions can never be better than the accuracy of realization of the particular conditions or states specified in the definitions.

This is a particular problem with the present definition of the second, which is based on a microwave transition of an atom of caesium. Frequencies of optical transitions of different atoms or ions are now demonstrably more reproducible, by some orders of magnitude, than the defined frequency of caesium.

In the present definition of the SI based on the set of ((defining constants)), instead of each definition specifying a particular condition or state, which sets a fundamental limit to the accuracy of realization, any convenient equation of physics that links the particular constant or constants to the quantity we want to measure may be used. This is a much more general way of defining the basic units of measurement. It is one that is not limited by today's science or technology as future developments may lead to as yet unknown equations that could result in different ways of realizing units with a much higher accuracy. When defined in this way, there is, in principle, no limit to the accuracy with which a unit can be realized. The exception remains the definition of the second in which the original microwave transition of caesium remains, for the time being, the basis of the definition.

The difference between an explicit unit and an ((explicit constant definition)) can be clearly illustrated using the two previous definitions of the metre that depended upon a fixed numerical value of the speed of light and secondly the two definitions of the kelvin. The original 1983 definition of the metre states, in effect, that "the metre is the length of the path travelled by light in vacuum during a time interval of stem:[1//299792458] of a second". The new definition simply states that the metre is defined by taking the constant that defines the second, the specified ((caesium frequency)) and the fixed numerical value of the speed of light expressed in units stem:[rm(m)" "rm(s)^(−1)]. We can thus use any equation of physics including, of course, that indicated by the former definition, the time taken to travel the given distance which is used for astronomical distances, but also the simple equation relating frequency and wavelength to the speed of light. The former definition of the kelvin based on a fixed numerical value for the temperature of the triple point of water requires ultimately a measurement at the triple point of water. The new definition, based on the fixed numerical value for the ((Boltzmann constant)), is much more general in that any thermodynamic equation in which stem:[k] appears can in principle be used to determine a thermodynamic temperature at any point on the temperature scale. For example, by determining the total radiant exitance of a black body at temperature stem:[ii(T)], equal to stem:[(2pi^5k^4//15c^2h^3) ii(T)^4], in stem:[rm(W)" "rm(m)^(−2)] we can determine stem:[ii(T)] directly.

(((Josephson effect)))
For the kilogram, the unit whose definition has undergone the most fundamental change, realization can be through any equation of physics that links mass, the ((Planck constant)), the velocity of light and the ((caesium frequency)). One such equation is that which describes the operation of an electro-mechanical balance, previously known as a watt balance, more recently known as a Kibble footnote:[To recognize Bryan Kibble's invention of the watt balance] balance. With this apparatus, a mechanical power, measured in terms of a mass, stem:[m], the local acceleration due to gravity, stem:[g], and a velocity, stem:[v], can be measured in terms of an electrical power measured in terms of an ((electric current)) and voltage measured in terms of the quantum Hall and Josephson effects respectively. The resulting equation is stem:[mgv = ii(C) h] where stem:[ii(C)] is a calibration constant that includes measured frequencies and stem:[h] is Planck's constant. (((acceleration due to gravity - standard value of (stem:[g_{"n"}]))))

Another method that can be used for a primary realization of the kilogram is through the determination of the number of atoms in a silicon sphere and using the equation:

[stem%unnumbered]
++++
m = (8 ii(V))/(a_0^3) (2ii(R)_(oo)h)/(c ii(alpha)^2) (m_("Si"))/(m_"e")
++++

with the mass stem:[m] and volume stem:[ii(V)] of the sphere (about 1 kg), lattice parameter stem:[a_0], ((Rydberg constant)) stem:[ii(R)_(oo)], ((fine structure constant)) stem:[ii(alpha)], and the masses of a silicon atom (averaged over the three isotopes used for the sphere) stem:[m_("Si")], and the electron stem:[m_"e"], respectively. The first fraction corresponds to the number of atoms in the sphere, the second to the electron mass and the third fraction is the ratio of the mass of the (isotopically averaged) silicon atom to the electron mass. (((electron mass)))

Another possibility for measuring mass through the new definition, but this time at the microscopic level, is through measurements of atomic recoil using the relation that includes stem:[h // m].

All these provide a striking illustration of the generality of the new way of defining units. Detailed information on the current realization of the base and other units is given on the BIPM website. [[realization_unit-3]]
