== The historical development of the International System index-range:establisment_si[(((establishment of the SI)))] index-range:[(((historical notes)))]
index-range:si_4[(((International System of Units (SI))))]

The 9th CGPM (1948, Resolution 6; CR 64) instructed the CIPM:

* to study the establishment of a complete set of rules for units of measurement;
* to find out for this purpose, by official enquiry, the opinion prevailing in scientific, technical and educational circles in all countries;
* to make recommendations on the establishment of a _practical system of units of measurement_ suitable for adoption by all signatories to the _((Metre Convention))_.

The same CGPM also laid down, in Resolution 7 (CR 70), 'general principles for the writing of unit symbols' and listed some ((coherent derived units)) that were assigned special names.

The 10th CGPM (1954, Resolution 6; CR 80) adopted as base quantities(((base quantity))) and units for this practical system the following six quantities: length, ((mass)), time, ((electric current)), thermodynamic temperature and luminous intensity, as well as the six corresponding base units(((base unit(s)))): metre, kilogram, second, ampere(((ampere (A)))), kelvin and candela(((candela (cd)))). After a lengthy discussion between physicists and chemists, the 14th CGPM (1971, Resolution 3, CR 78 and _Metrologia_ 1972, *8*, 36) added amount of substance, unit mole, as the seventh ((base quantity)) and unit.

The 11th CGPM (1960, Resolution 12; CR 87) adopted the name _Système international d'unités_, with the international abbreviation _SI_, for this practical system of units and laid down rules for prefixes, derived units and the former supplementary units, as well as other matters; it thus established a comprehensive specification for units of measurement. Subsequent meetings of the CGPM and the CIPM have added to and modified the original structure of the SI to take account of advances in science and of the changing needs of users.

The historical sequence that led to these important decisions may be summarized as follows. (((Gauss)))

* The creation of the ((decimal metric system)) at the time of the French Revolution and the subsequent deposition of two platinum standards representing the metre and the kilogram, on 22 June 1799, in the _Archives de la République_ in Paris, which can be seen as the first step that led to the present International System of Units.
* In 1832, Gauss strongly promoted the application of this ((metric system)), together with the second defined in astronomy, as a coherent system of units for the physical sciences. Gauss was the first to make absolute measurements of the earth's magnetic field in terms of a decimal system based on the _three mechanical units_ millimetre, ((gram)) and second for, respectively, the quantities length, mass and time. In later years Gauss and Weber extended these measurements to include other electrical phenomena.
* These applications in the field of electricity and magnetism were further extended in the 1860s under the active leadership of ((Maxwell)) and Thomson through the ((British Association for the Advancement of Science (BAAS))). They formulated the requirement for a _coherent system of units_ with _base units_(((base unit(s)))) and _derived units_. In 1874 the BAAS introduced the _CGS system_(((CGS))), a three-dimensional coherent unit system based on the three mechanical units centimetre, ((gram)) and second, using prefixes(((multiples - prefixes for))) ranging from micro to mega to express decimal sub-multiples and multiples. The subsequent development of physics as an experimental science was largely based on this system.
* The sizes of the coherent ((CGS)) units in the fields of electricity and magnetism proved to be inconvenient, so in the 1880s the BAAS and the International Electrical Congress, predecessor of the International Electrotechnical Commission (IEC), approved a mutually coherent set of _practical units_. Among them were the ohm for electrical resistance, the volt for electromotive force, and the ampere for ((electric current)). (((ampere (A))))
* After the signing of the Metre Convention on 20 May 1875, which created the BIPM and established the CGPM and the CIPM, work began on establishing new international prototypes for the metre and the kilogram. In 1889 the 1st CGPM sanctioned the international prototypes for the metre and the kilogram. Together with the astronomical second as the unit of time, these units constituted a three-dimensional mechanical unit system similar to the ((CGS)) system, but with the base units(((base unit(s)))) metre, kilogram and second, known as the _((MKS system))_.
* In 1901 Giorgi showed that it is possible to combine the mechanical units of this ((MKS system)) with the practical ((electrical units)) to form a coherent four-dimensional system by adding to the three base units(((base unit(s)))) a fourth unit, of an electrical nature such as the ampere(((ampere (A)))) or the ohm, and also rewriting the equations occurring in electromagnetism in the so-called rationalized form. Giorgi's proposal opened the path to a number of new developments. (((Giorgi)))
* After the revision of the Metre Convention by the 6th CGPM (1921), which extended the scope and responsibilities of the BIPM to other fields in physics and the subsequent creation of the Consultative Committee for Electricity (CCE) by the 7th CGPM (1927), the Giorgi proposal was thoroughly discussed by the IEC, the International Union of Pure and Applied Physics (IUPAP) and other international organizations. This led the CCE to propose in 1939 the adoption of a four-dimensional system based on the metre, kilogram, second and ampere(((ampere (A)))), the ((MKSA system)), a proposal approved by the CIPM in 1946.
* Following an international enquiry by the BIPM, which began in 1948, the 10th CGPM (1954), approved the further introduction of the kelvin and the candela(((candela (cd)))), as base units(((base unit(s)))) for thermodynamic temperature and ((luminous intensity)), respectively. The name International System of Units, with the abbreviation SI, was given to the system by the 11th CGPM (1960). Rules for prefixes, derived units, the former supplementary units as well as other matters, were established, thus providing a comprehensive specification for all units of measurement.
* At the 14th CGPM (1971) a new base unit(((base unit(s)))), the mole, symbol stem:[rm(mol)], was adopted for the quantity amount of substance. This followed a proposal from the International Organization for Standardization originating in a proposal from the Commission on Symbols, Units and Nomenclature (SUN Commission) of IUPAP, which was supported by the International Union for Pure and Applied Chemistry (IUPAC). This brought the number of base units(((base unit(s)))) of the SI to seven. (((IUPAC)))
* Since then, extraordinary advances have been made in relating SI units to truly invariant quantities such as the fundamental constants of physics and the properties of atoms. Recognizing the importance of linking SI units to such invariant quantities, the 24th CGPM (2011), adopted the principles of a new definition of the SI based on using a set of seven such constants as references for the definitions. At the time of the 24th CGPM, experiments to determine their values in terms of the then base units(((base unit(s)))) were not completely consistent but by the time of the 26th CGPM (2018) this had been achieved and the new definition of the SI was adopted in Resolution 1. This is the basis of the definition presented in this brochure and it is the simplest and most fundamental way of defining the SI. (((fundamental constants (of physics))))
* The SI was previously defined in terms of seven base units(((base unit(s)))) and derived units defined as products of powers of the base units(((base unit(s)))). The seven base units(((base unit(s)))) were chosen for historical reasons, as the metric system, later the SI, evolved and developed over the last 130 years. Their choice was not unique, but it has become established and familiar over the years, not only by providing a framework for describing the SI, but also for defining the derived units. This role for the base units(((base unit(s)))) continues in the present SI even though the SI itself is now defined in terms of the seven ((defining constants)). In this brochure therefore, definitions of the seven base units(((base unit(s)))) can still be found but are henceforth based on the seven ((defining constants)): the caesium hyperfine frequency stem:[Delta ii(nu)_("Cs")]; the speed of light in vacuum stem:[c]; the Planck constant stem:[h]; ((elementary charge)) stem:[e]; ((Boltzmann constant)) stem:[k]; ((Avogadro constant)) stem:[ii(N)_"A"]; and the ((luminous efficacy)) of a defined visible radiation stem:[ii(K)_("cd")].

The definitions of the seven base units(((base unit(s)))) can be related unambiguously to the numerical values of the seven ((defining constants)). However, there is not a one-to-one relationship between the seven ((defining constants)) and the seven base units(((base unit(s)))) as many of the base units(((base unit(s)))) call upon more than one of the ((defining constants)). [[establisment_si]]