== Historical perspective on the base units

=== Unit of time, second

Before 1960, the unit of time the second, was defined as the fraction stem:[1//86400] of the mean solar day. The exact definition of "mean solar day" was left to astronomers. However measurements showed that irregularities in the rotation of the Earth made this an unsatisfactory definition. In order to define the unit of time more precisely, the 11th CGPM (1960, Resolution 9, CR, 86) adopted a definition given by the International Astronomical Union based on the tropical year 1900. Experimental work, however, had already shown that an atomic standard of time, based on a transition between two energy levels of an atom or a molecule, could be realized and reproduced much more accurately. Considering that a very precise definition of the unit of time is indispensable for science and technology, the 13th CGPM (1967-1968, Resolution 1, CR, 103 and _Metrologia_, 1968, *4*, 43) chose a new definition of the second referenced to the frequency of the ground state hyperfine transition in the caesium 133 atom. A revised more precise wording of this same definition now in terms of a fixed numerical value of the unperturbed ground-state hyperfine transition frequency of the caesium 133 atom, stem:[Delta nu_("Cs")], was adopted in Resolution 1 of the 26th CGPM (2018).

=== Unit of length, metre

The 1889 definition of the metre, namely, the length of the international prototype of platinum-iridium, was replaced by the 11th CGPM (1960) using a definition based on the wavelength of the radiation corresponding to a particular transition in krypton 86. This change was adopted in order to improve the accuracy with which the definition of the metre could be realized, this being achieved using an interferometer with a travelling microscope to measure the optical path difference as the fringes were counted. In turn, this was replaced in 1983 by the 17th CGPM (Resolution 1, CR, 97, and _Metrologia_, 1984, *20*, 25) with a definition referenced to the distance that light travels in vacuum in a specified interval of time. The original international prototype of the metre, which was sanctioned by the 1st CGPM in 1889 (CR, 34-38), is still kept at the BIPM under conditions specified in 1889. In order to make clear its dependence on the fixed numerical value of the speed of light, stem:[c], the wording of the definition was changed in Resolution 1 of the 26th CGPM (2018).

=== Unit of mass, kilogram

The 1889 definition of the kilogram was simply the mass of the international prototype of the kilogram, an artefact made of platinum-iridium. This was, and still is, kept at the BIPM under the conditions specified by the 1st CGPM (1889, CR, 34-38) when it sanctioned the prototype and declared that "this prototype shall henceforth be considered to be the unit of mass". Forty similar prototypes were made at about the same time and these were all machined and polished to have closely the same mass as the international prototype. At the 1st CGPM (1889), after calibration against the international prototype, most of these "national prototypes" were individually assigned to Member States of the Metre Convention, and some also to the BIPM. The 3rd CGPM (1901, CR, 70), in a declaration intended to end the ambiguity in common usage concerning the use of the word "weight", confirmed that "the kilogram is the unit of mass; it is equal to the mass of the international prototype of the kilogram". The complete version of these declarations appears on p. 70 of the above-mentioned CGPM proceedings.

By the time of the second verification of national prototypes in 1946 it was found that on average the masses of these prototypes were diverging from that of the international prototype. This was confirmed by the third verification carried out from 1989 to 1991, the median difference being about 25 micrograms for the set of original prototypes sanctioned by the 1st CGPM (1889). In order to assure the long-term stability of the unit of mass, to take full advantage of quantum electrical standards and to be of more utility to modern science, a new definition for the kilogram based on the value of a fundamental constant, for which purpose the Planck constant stem:[h] was chosen, was adopted by Resolution 1 of the 26th CGPM (2018).

=== Unit of electric current, ampere

Electric units, called "international units", for current and resistance were introduced by the International Electrical Congress held in Chicago in 1893 and definitions of the "international ampere" and "international ohm" were confirmed by the International Conference in London in 1908.

By the time of the 8th CGPM (1933) there was a unanimous desire to replace the "international units" by so-called "absolute units". However because some laboratories had not yet completed experiments needed to determine the ratios between the international and absolute units, the CGPM gave authority to the CIPM to decide at an appropriate time both these ratios and the date at which the new absolute units would come into effect. The CIPM did so in 1946 (1946, Resolution 2, PV, *20*, 129-137), when it decided that the new units would come into force on 1 January 1948. In October 1948 the 9th CGPM approved the decisions taken by the CIPM. The definition of the ampere, chosen by the CIPM, was referenced to the force between parallel wires carrying an electric current and it had the effect of fixing the numerical value of the vacuum magnetic permeability stem:[mu_0] (also called the magnetic constant). The numerical value of the vacuum electric permittivity stem:[epsilon_0] (also called the electric constant) then became fixed as a consequence of the new definition of the metre adopted in 1983.

However the 1948 definition of the ampere proved difficult to realize and practical quantum standards (based on Josephson and quantum-Hall effects), which link both the volt and the ohm to particular combinations of the Planck constant stem:[h] and elementary charge stem:[e], became almost universally used as a practical realization of the ampere through Ohm's law (18th CGPM (1987), Resolution 6, CR 100). As a consequence, it became natural not only to fix the numerical value of h to redefine the kilogram, but also to fix the numerical value of stem:[e] to redefine the ampere in order to bring the practical quantum electrical standards into exact agreement with the SI. The present definition based on a fixed numerical value for the elementary charge, stem:[e], was adopted in Resolution 1 of the 26th CGPM (2018).

=== Unit of thermodynamic temperature, kelvin

The definition of the unit of thermodynamic temperature was given by the 10th CGPM (1954, Resolution 3; CR 79) which selected the triple point of water, stem:[T_("TPW")], as a fundamental fixed point and assigned to it the temperature 273.16 K, thereby defining the kelvin. The 13th CGPM (1967-1968, Resolution 3; CR, 104 and _Metrologia_, 1968, *4*, 43) adopted the name kelvin, symbol stem:["K"], instead of "degree kelvin", symbol stem:[ยบ"K"], for the unit defined in this way. However, the practical difficulties in realizing this definition, requiring a sample of pure water of well-defined isotopic composition and the development of new primary methods of thermometry, led to the adoption of a new definition of the kelvin based on a fixed numerical value of the Boltzmann constant stem:[k]. The present definition, which removed both of these constraints, was adopted in Resolution 1 of the 26th CGPM (2018).

=== Unit of amount of substance, mole

Following the discovery of the fundamental laws of chemistry, units called, for example, "gram-atom" and "gram molecule", were used to specify amounts of chemical elements or compounds. These units had a direct connection with "atomic weights" and "molecular weights", which are in fact relative atomic and molecular masses. The first compilations of "Atomic weights" were originally linked to the atomic weight of oxygen, which was, by general agreement, taken as being 16. Whereas physicists separated the isotopes in a mass spectrometer and attributed the value 16 to one of the isotopes of oxygen, chemists attributed the same value to the (slightly variable) mixture of isotopes 16, 17 and 18, which for them constituted the naturally occurring element oxygen. An agreement between the International Union of Pure and Applied Physics (IUPAP) and the International Union of Pure and Applied Chemistry (IUPAC) brought this duality to an end in 1959-1960. Physicists and chemists had agreed to assign the value 12, exactly, to the so-called atomic weight, correctly referred to as the relative atomic mass stem:[A_"r"], of the isotope of carbon with mass number 12 (carbon 12, ^12^C). The unified scale thus obtained gives the relative atomic and molecular masses, also known as the atomic and molecular weights, respectively. This agreement is unaffected by the redefinition of the mole.

The quantity used by chemists to specify the amount of chemical elements or compounds is called "amount of substance". Amount of substance, symbol stem:[n], is defined to be proportional to the number of specified elementary entities stem:[N] in a sample, the proportionality constant being a universal constant which is the same for all entities. The proportionality constant is the reciprocal of the Avogadro constant stem:[N_"A"], so that stem:[n = N//N_"A"]. The unit of amount of substance is called the _mole_, symbol stem:["mol"]. Following proposals by the IUPAP, IUPAC and ISO, the CIPM developed a definition of the mole in 1967 and confirmed it in 1969, by specifying that the molar mass of carbon 12 should be exactly 0.012 kg/mol. This allowed the amount of substance stem:[n_"S"("X")] of any pure sample stem:["S"] of entity stem:["X"] to be determined directly from the mass of the sample stem:[m_"S"] and the molar mass stem:[M("X")] of entity stem:["X"], the molar mass being determined from its relative atomic mass stem:[A_"r"] (atomic or molecular weight) without the need for a precise knowledge of the Avogadro constant, by using the relations

[stem%unnumbered]
++++
n_"S"("X") = m_"S""/M(X)", text( and ) M("X") = A_"r"("X") " g/mol"
++++

Thus, this definition of the mole was dependent on the artefact definition of the kilogram.

The numerical value of the Avogadro constant defined in this way was equal to the number of atoms in 12 grams of carbon 12. However, because of recent technological advances, this number is now known with such precision that a simpler and more universal definition of the mole has become possible, namely, by specifying exactly the number of entities in one mole of any substance, thus fixing the numerical value of the Avogadro constant. This has the effect that the new definition of the mole and the value of the Avogadro constant are no longer dependent on the definition of the kilogram. The distinction between the fundamentally different quantities 'amount of substance' and 'mass' is thereby emphasized. The present definition of the mole based on a fixed numerical value for the Avogadro constant, stem:[N_"A"], was adopted in Resolution 1 of the 26th CGPM (2018).

=== Unit of luminous intensity, candela

The units of luminous intensity, which were based on flame or incandescent filament standards in use in various countries before 1948, were replaced initially by the "new candle" based on the luminance of a Planckian radiator (a black body) at the temperature of freezing platinum. This modification had been prepared by the International Commission on Illumination (CIE) and by the CIPM before 1937 and the decision was promulgated by the CIPM in 1946. It was then ratified in 1948 by the 9th CGPM, which adopted a new international name for this unit, the _candela_, symbol stem:["cd"]; in 1954 the 10th CGPM established the candela as a base unit; In 1967 the 13th CGPM (Resolution 5, CR, 104 and _Metrologia_, 1968, *4*, 43-44) amended this definition.

In 1979, because of the difficulties in realizing a Planck radiator at high temperatures, and the new possibilities offered by radiometry, i.e. the measurement of optical radiation power, the 16th CGPM (1979, Resolution 3, CR, 100 and _Metrologia_,1980, *16*, 56) adopted a new definition of the candela.

The present definition of the candela uses a fixed numerical value for the luminous efficacy of monochromatic radiation of frequency stem:[540 times 10^(12) " Hz", text( ) K_("cd")], adopted in Resolution 1 of the 26th CGPM (2018).