== Spectre d’action

Un rayonnement optique peut être caractérisé par sa distribution spectrale. Les mécanismes selon lesquels le rayonnement optique est absorbé par le système chimique ou biologique sont en général très complexes, et sont toujours fonction de la longueur d’onde (ou de la fréquence). Pour les applications métrologiques, cependant, la complexité des mécanismes d’absorption peut être ignorée et l’effet est simplement caractérisé par un spectre d’action qui relie la réponse photochimique ou photobiologique au rayonnement incident. Ce spectre d’action (ou fonction de pondération) décrit l’efficacité relative d’un rayonnement optique monochromatique à la longueur d’onde stem:[ii(lambda)] à produire une réponse donnée. Il est donné en valeur relative, normalisée à 1 pour la longueur d’onde d’efficacité maximale. Les spectres d’action sont définis et recommandés par les organisations internationales scientifiques ou de normalisation, notamment par la Commission internationale de l’éclairage (CIE). La fonction de pondération peut être combinée à une constante d’efficacité reliant la réponse photochimique ou photobiologique absolue aux unités caractérisant les rayonnements optiques : en photométrie, il s’agit de l’efficacité lumineuse spectrale exprimée en stem:["unitsml(lm*W^(−1))"].

En photochimie et en photobiologie, les mesures de rayonnements optiques peuvent être réalisées en fonction de la distribution spectrale de la grandeur radiométrique (système radiométrique spectral) ou de la distribution spectrale d’une grandeur photonique (système photonique spectral), ci-après simplement dénommées «&nbsp;distribution spectrale de puissance&nbsp;» et «&nbsp;distribution spectrale photonique&nbsp;». Comme la distribution spectrale de puissance et la distribution spectrale photonique décrivent le rayonnement optique dans des unités différentes, un effet photochimique ou photobiologique donné a deux constantes d’efficacité, une pour chacun des systèmes. Par ailleurs, comme la distribution spectrale de puissance n’est pas proportionnelle à la distribution spectrale photonique, il en résulte que les fonctions de pondération de ces systèmes de mesure ne sont pas, elles non plus, proportionnelles. Pour éviter toute confusion, il est essentiel lors de l’utilisation d’un spectre d’action ou d’une fonction de pondération de préciser le système (radiométrique ou photonique) qui le/la définit. Les deux constantes d’efficacité, et leurs fonctions de pondération respectives, sont étroitement liées, tel que décrit dans la mise en pratique de la candela et des unités dérivées associées pour les grandeurs photométriques et radiométriques dans le Système international d’unités (SI), section 1.2.

Pour la vision, deux fonctions de pondération radiométriques ont été définies par la CIE et approuvées par le CIPM : stem:[ii(V)(ii(lambda))] pour la vision photopique et stem:[ii(V)ʹ(ii(lambda))] pour la vision scotopique. Ces fonctions sont utilisées dans les mesures des grandeurs photométriques et font implicitement partie de la définition de l’unité SI pour la photométrie, la candela. La vision photopique est régie par une stimulation des cônes de la rétine de l’oeil, qui sont sensibles aux luminances élevées (stem:["L" > text( environ ) 5 "unitsml(cd*m^(−2))"]) et sont utilisés pour la vision diurne. La vision scotopique est régie par une stimulation des bâtonnets de la rétine de l’oeil, qui sont sensibles aux faibles luminances (stem:["L" < text( environ ) 10^(−3) "unitsml(cd*m^(−2))"]) et sont utilisés pour la vision nocturne. Dans le cas de luminances intermédiaires entre la vision photopique et la vision scotopique, les cônes et les bâtonnets fonctionnent simultanément, on est alors dans le domaine de la vision mésopique.

Des spectres d’action radiométriques ont également été définis par la CIE pour d’autres effets photobiologiques, tel le spectre d’action de l’érythème (rougissement de la peau) dû au rayonnement ultraviolet. Ces spectres n’ont cependant pas de statut particulier dans le SI.

Les processus actiniques photochimiques et photobiologiques sont souvent influencés par d’autres facteurs. Par exemple, l’absorption thermique peut altérer l’efficacité actinique d’un rayonnement à une longueur d’onde donnée ou un filtrage optique peut se produire en raison de couches intermédiaires entre la source de rayonnement optique et la couche actinique. Il est souvent pratique d’utiliser des spectres d’action qui combinent ces types d’effets modificateurs avec l’effet actinique, en particulier pour les diverses réponses de la rétine aux rayonnements optiques. C’est pourquoi le terme «&nbsp;spectre d’action&nbsp;» peut également faire référence à des fonctions de pondération utilisées pour dériver les grandeurs pondérées en fonction de leur spectre à partir des effets photochimiques et photobiologiques qui ne sont pas purement actiniques.