== Mesure des grandeurs photochimiques et photobiologiques ; unités correspondantes

Les grandeurs et unités photométriques définies dans le domaine de la vision sont bien établies et très largement utilisées depuis longtemps. Elles ne sont pas concernées par les règles énoncées dans la suite de ce texte. Pour toutes les autres grandeurs photochimiques ou photobiologiques, les règles suivantes doivent être appliquées pour définir les unités à utiliser. Cette façon de définir les unités à l’aide des spectres d’action exprimés selon le système spectral radiométrique a été recommandée par le Comité consultatif de photométrie et radiométrie (CCPR) lors de sa 9^e^ réunion en 1977 et était décrite dans l’Annexe 3 de la 8^e^ édition de la _Brochure sur le SI_. Le CCPR, lors de sa 23^e^ réunion en 2016, a recommandé de réviser le texte de la version en ligne de l’Annexe 3 de la 9^e^ édition de la _Brochure sur le SI_ afin de clarifier l’utilisation des spectres d’action lorsqu’ils sont exprimés selon le système spectral photonique ou selon le système spectral radiométrique.

Une grandeur photochimique ou photobiologique est définie de manière purement physique comme la grandeur dérivée de la grandeur radiométrique correspondante par l’évaluation de l’effet du rayonnement selon son action sur un récepteur sélectif, la sensibilité spectrale de ce récepteur étant définie par le spectre d’action de l’effet photochimique ou photobiologique considéré. La grandeur est donnée par l’intégrale par rapport à la longueur d’onde de la distribution spectrale de la grandeur radiométrique considérée, pondérée par la fonction de pondération appropriée. L’utilisation d’une intégrale suppose implicitement l’additivité arithmétique des grandeurs photochimiques ou photobiologiques bien que dans la pratique, cette loi ne soit, souvent, pas parfaitement vérifiée en pratique. La fonction de pondération est donnée en valeur relative ; c’est une grandeur sans dimension dont l’unité SI est le nombre un. La grandeur radiométrique a sa propre unité radiométrique correspondante. Ainsi, selon la règle d’obtention de l’unité SI d’une grandeur dérivée, l’unité de la grandeur photochimique ou photobiologique est celle de la grandeur radiométrique correspondante ; cela signifie également que pour être conforme au SI, la constante d’efficacité est un. Quand on donne un résultat numérique, il est indispensable de préciser s’il s’agit d’une grandeur radiométrique ou d’une grandeur pondérée de manière spectrale puisque les unités sont les mêmes. Si pour un effet photochimique ou photobiologique donné il existe plusieurs spectres d’action, le spectre d’action utilisé pour les mesures doit être clairement indiqué.

À titre d’exemple, l’éclairement érythémal, stem:[ii(E)_("er")], d’une source de rayonnement ultraviolet est obtenu en pondérant l’éclairement énergétique spectral à la longueur stem:[ii(lambda)] par l’efficacité de ce rayonnement à cette longueur d’onde à provoquer un érythème, et en sommant sur l’ensemble de toutes les longueurs d’onde présentes dans le spectre de la source sur toute la gamme de longueurs d’onde du spectre d’action. Ceci peut s’exprimer sous la forme mathématique suivante :

[[eq-a-3-1]]
[stem]
++++
ii(E)_("er") = int ii(E)_(ii(lambda))(ii(lambda)) s_("er")(ii(lambda)) "d" ii(lambda)
++++

où stem:[ii(E)_(ii(lambda))(ii(lambda))] est l’éclairement énergétique spectral à la longueur d’onde stem:[ii(lambda)] (généralement exprimé en unité SI stem:["unitsml(W m^(−2)) nm^(−1))"]) et stem:[s_("er")(ii(lambda))] la fonction de pondération spectrale de l’érythème exprimée selon le système radiométrique spectral et normalisée à 1 à sa valeur spectrale maximale. L’éclairement érythémal, stem:[ii(E)_("er")], déterminé de cette façon est exprimé en unité SI stem:["unitsml(W m^(−2))"].