[[cgpm17e1983]]
[%unnumbered]
== 17^e^ CGPM, 1983 index-range:metre-1[(((mètre (stem:["unitsml(m)"]))))]

[[cgpm17e1983r1]]
[%unnumbered]
=== {blank}

[.variant-title,type=quoted]
*Définition du mètre* (<<CR1983-1>> et <<Met_20_1_25,_Metrologia_, 1984, *20*, 25>>)

NOTE: La formulation de la définition du mètre a été
modifiée par la CGPM à sa 26^e^ réunion en 2018 (<<cgpm26th2018r1r1,Résolution 1>>).

[[cgpm17e1983r1r1]]
==== Résolution 1
____

La Dix-septième Conférence générale des poids et mesures,

*considérant*

* que la définition actuelle ne permet pas une réalisation du mètre suffisamment précise pour
tous les besoins,
* que les progrès réalisés dans l’asservissement des lasers permettent d’obtenir des radiations
plus reproductibles et plus faciles à utiliser que la radiation étalon émise par une lampe à
krypton 86,
(((longueur)))

* que les progrès réalisés dans la mesure des fréquences et des longueurs d’onde de ces
radiations ont abouti à des déterminations concordantes de la vitesse de la lumière dont
l’exactitude est limitée principalement par la réalisation du mètre dans sa définition actuelle,
* que les valeurs des longueurs d’onde déterminées à partir de mesures de fréquence et d’une
valeur donnée de la vitesse de la lumière ont une précision supérieure à celle qui peut être
obtenue par comparaison avec la longueur d’onde de la radiation étalon du krypton 86,
* qu’il y a avantage, notamment pour l’astronomie et la géodésie, à maintenir inchangée la valeur
de la vitesse de la lumière recommandée en 1975 par la 15^e^ Conférence générale des poids et
mesures, dans sa Résolution 2 (stem:[c = 299792458 "unitsml(m//s)"]),
* qu’une nouvelle définition du mètre a été envisagée sous diverses formes qui ont toutes pour
effet de donner à la vitesse de la lumière une valeur exacte, égale à la valeur recommandée, et
que cela n’introduit aucune dis((continuité)) appréciable de l’unité de ((longueur)), compte tenu de
l’incertitude relative de stem:[+- 4 xx 10^(-9)] des meilleures réalisations du mètre dans sa définition
actuelle footnote:[La valeur de l’incertitude donnée ici correspond à
trois fois l’écart-type de la valeur en question.].
* que ces diverses formes, faisant appel soit au trajet parcouru par la lumière dans un intervalle
de temps spécifié, soit à la ((longueur)) d’onde d’une radiation de fréquence mesurée ou de
fréquence spécifiée, ont fait l’objet de consultations et de discussions approfondies, qu’elles ont
été reconnues équivalentes et qu’un consensus s’est dégagé en faveur de la première forme,
* que le Comité consultatif pour la définition du mètre est dès maintenant en mesure de donner
des instructions pour la mise en pratique d’une telle définition, instructions qui pourront inclure
l’emploi de la radiation orangée du krypton 86 utilisée jusqu’ici comme étalon et qui pourront
être complétées ou révisées par la suite,

*décide*

. Le mètre est la ((longueur)) du trajet parcouru dans le vide par la lumière pendant une durée de
stem:[1//299792458] de seconde.

. La définition du mètre en vigueur depuis 1960, fondée sur la transition entre les niveaux stem:[2"p"_(10)]
et stem:[5"d"_5] de l’atome de krypton 86, est abrogée.
____



=== {blank}

[.variant-title,type=quoted]
*Sur la mise en pratique de la définition du mètre* (<<CR1983-2>> et <<Met_20_1_25,_Metrologia_, 1984, *20*, 25-26>>)

NOTE: _Voir_ <<cipm2002r1r1,Recommandation 1 (CI-2002) du CIPM>> relative à la
révision de la mise en pratique de la définition du mètre.

==== Résolution 2
____

La Dix-septième Conférence générale des poids et mesures

*invite* le Comité international des poids et mesures

* à établir des instructions pour la mise en pratique de la nouvelle définition du mètre,
* à choisir des radiations qui puissent être recommandées comme étalons de ((longueur)) d’onde
pour la mesure interférentielle des longueurs et à établir des instructions pour leur emploi,
* à poursuivre les études entreprises pour améliorer ces étalons. [[metre-1]]
____
