
[[le_bipm_et_la_cdm]]
[.preface]
== Le BIPM et la Convention du Mètre

Le Bureau international des poids et mesures (BIPM) a été créé par la Convention du Mètre
signée à Paris le 20 mai 1875 par dix-sept États, lors de la dernière séance de la Conférence
diplomatique du Mètre. Cette Convention a été modifiée en 1921.

Le Bureau international a son siège près de Paris, dans le domaine (stem:[43520] stem:["m"^2]) du Pavillon
de Breteuil (Parc de Saint-Cloud) mis à sa disposition par le Gouvernement français;
son entretien est assuré à frais communs par les États Membres de la Convention du Mètre.

Le Bureau international a pour mission d’assurer l’unification mondiale des mesures;
les objectifs du BIPM sont les suivants:

* représenter la communauté métrologique internationale afin d’en maximiser la
reconnaissance et l’impact,

* être un centre de collaboration scientifique et technique entre les États Membres,
leur permettant de développer des aptitudes pour les comparaisons internationales de
mesure, sur le principe des frais partagés,

* coordonner le système mondial de mesure, en garantissant la comparabilité et la
reconnaissance au niveau international des résultats de mesures.

Le Bureau international fonctionne sous la surveillance exclusive du Comité international
des poids et mesures (CIPM), placé lui-même sous l’autorité de la Conférence générale des
poids et mesures (CGPM) à laquelle il présente son rapport sur les travaux accomplis par le
Bureau international.

[NOTE]
====
Au 20 mai 2019, on comptait cinquante-neuf États
Membres: Afrique du Sud, Allemagne, Arabie saoudite,
Argentine, Australie, Autriche, Belgique, Brésil,
Bulgarie, Canada, Chili, Chine, Colombie, Corée
(République de), Croatie, Danemark, Égypte, Émirats
arabes unis, Espagne, États-Unis d’Amérique, Fédération
de Russie, Finlande, France, Grèce, Hongrie, Inde,
Indonésie, Iran (Rép. islamique d’), Irak,
Irlande, Israël, Italie, Japon, Kazakhstan, Kenya, Lituanie,
Malaisie, Mexique, Monténégro, Norvège,
Nouvelle-Zélande, Pakistan, Pays-Bas, Pologne, Portugal,
Roumanie, Royaume-Uni de Grande Bretagne et d’Irlande
du Nord, Serbie, République tchèque, Singapour,
Slovaquie, Slovénie, Suède, Suisse, Thaïlande, Tunisie,
Turquie, Ukraine, Uruguay.
====

La Conférence générale rassemble des délégués de tous les États Membres et se réunit
généralement tous les quatre ans dans le but:

* de discuter et de provoquer les mesures nécessaires pour assurer la propagation et le
perfectionnement du Système international d’unités (SI), forme moderne du Système
métrique;

* de sanctionner les résultats des nouvelles déterminations métrologiques fondamentales
et d’adopter diverses résolutions scientifiques de portée internationale;

* d’adopter toutes les décisions importantes concernant la dotation, l’organisation et le
développement du Bureau international.

[NOTE]
====
Quarante-deux États et Entités économiques sont
Associés à la Conférence générale des poids et
mesures: Albanie, Azerbaïdjan, Bangladesh,
Belarus, Bolivie, Bosnie-Herzégovine,
Botswana, CARICOM, Costa
Rica, Cuba, Équateur, Estonie, Éthiopie, Géorgie,
Ghana, Hong Kong (Chine), Jamaïque, Koweït, Lettonie,
Luxembourg, Macédoine du Nord, Malte, Maurice,
Moldova (République de), Mongolie, Namibie, Oman,
Ouzbékistan, Panama, Paraguay, Pérou, Philippines,
Qatar, République arabe syrienne, Seychelles,
Soudan, Sri Lanka, Taipei chinois, Tanzanie, Viet Nam,
Zambie et Zimbabwe.
====

Le Comité international comprend dix-huit membres appartenant à des États différents;
il se réunit actuellement tous les ans. Le bureau de ce Comité adresse aux Gouvernements
des États Membres un rapport annuel sur la situation administrative et financière du Bureau
international. La principale mission du Comité international est d’assurer l’unification
mondiale des unités de mesure, en agissant directement ou en soumettant des propositions à
la Conférence générale.

Limitées à l’origine aux mesures de longueur et de masse et aux études métrologiques en
relation avec ces grandeurs, les activités du Bureau international ont été étendues aux
étalons de mesure électriques (1927), photométriques et radiométriques (1937),
des rayonnements ionisants (1960), aux échelles de temps (1988) et à la chimie (2000).
Dans ce but, un agrandissement des premiers laboratoires construits en 1876-1878 a eu lieu
en 1929; de nouveaux bâtiments ont été construits en 1963-1964 pour les laboratoires de la
section des rayonnements ionisants, en 1984 pour le travail sur les lasers, en 1988 pour la
bibliothèque et des bureaux, et en 2001 a été inauguré un bâtiment pour l’atelier,
des bureaux et des salles de réunion.

Environ quarante-cinq physiciens et techniciens travaillent dans les laboratoires du Bureau
international. Ils y font principalement des recherches métrologiques, des comparaisons
internationales des réalisations des unités et des vérifications d’étalons. Ces travaux font
l’objet d’un rapport annuel du directeur.

Devant l’extension des tâches confiées au Bureau international en 1927, le Comité
international a institué, sous le nom de Comités consultatifs, des organes destinés à le
renseigner sur les questions qu’il soumet, pour avis, à leur examen. Ces Comités
consultatifs, qui peuvent créer des groupes de travail temporaires ou permanents pour
l’étude de sujets particuliers, sont chargés de coordonner les travaux internationaux
effectués dans leurs domaines respectifs et de proposer au Comité international des
recommandations concernant les unités.

Les Comités consultatifs ont un règlement commun (Document CIPM-D-01, _Rules of
procedure for the Consultative Committees (CCs) created by the CIPM_, _CC working
groups and CC workshops_). Ils tiennent leurs sessions à des intervalles irréguliers.
Le président de chaque Comité consultatif est désigné par le Comité international;
il est généralement membre du Comité international. Les Comités consultatifs ont pour
membres des laboratoires de métrologie et des instituts spécialisés, dont la liste est établie
par le Comité international, qui envoient des délégués de leur choix. Ils comprennent aussi
des membres nominativement désignés par le Comité international, et un représentant du
Bureau international (Document CIPM-D-01, _Rules of procedure for the Consultative
Committees (CCs) created by the CIPM_, _CC working groups and CC workshops_).
Ces Comités sont actuellement au nombre de dix:

. Le Comité consultatif d’électricité et magnétisme (CCEM), nouveau nom donné en
1997 au Comité consultatif d’électricité (CCE) créé en 1927;

. Le Comité consultatif de photométrie et radiométrie (CCPR), nouveau nom donné en
1971 au Comité consultatif de photométrie (CCP) créé en 1933 (de 1930 à 1933 le
CCE s’est occupé des questions de photométrie);

. Le Comité consultatif de thermométrie (CCT), créé en 1937;

. Le Comité consultatif des longueurs (CCL), nouveau nom donné en 1997 au Comité
consultatif pour la définition du mètre (CCDM) créé en 1952;

. Le Comité consultatif du temps et des fréquences (CCTF), nouveau nom donné en
1997 au Comité consultatif pour la définition de la seconde (CCDS) créé en 1956;

. Le Comité consultatif des rayonnements ionisants (CCRI), nouveau nom donné en
1997 au Comité consultatif pour les étalons de mesure des rayonnements ionisants
(CCEMRI) créé en 1958. En 1969, ce Comité consultatif a institué quatre sections:
Section I (Rayons x et stem:[gamma], électrons), Section II (Mesure des radionucléides), Section III
(Mesures neutroniques), Section IV (Étalons d’énergie stem:[alpha]); cette dernière section a été
dissoute en 1975, son domaine d’activité étant confié à la Section II);

. Le Comité consultatif des unités (CCU), créé en 1964 (ce Comité consultatif a
remplacé la «&nbsp;Commission du système d’unités&nbsp;» instituée par le Comité international
en 1954);

. Le Comité consultatif pour la masse et les grandeurs apparentées (CCM), créé en
1980;

. Le Comité consultatif pour la quantité de matière: métrologie en chimie et biologie
(CCQM), créé en 1993;

. Le Comité consultatif de l’acoustique, des ultrasons et des vibrations (CCAUV),
créé en 1999.

Les travaux de la Conférence générale et du Comité international sont publiés par les soins
du Bureau international dans les collections suivantes:

* _Comptes rendus des séances de la Conférence générale des poids et mesures_;
* _Procès-verbaux des séances du Comité international des poids et mesures_.

Le Comité international a décidé en 2003 que les rapports des sessions des Comités
consultatifs ne seraient plus imprimés, mais placés sur le site internet du BIPM, dans leur
langue originale.

Le Bureau international publie aussi des monographies sur des sujets métrologiques
particuliers et, sous le titre _Le Système international d’unités (SI)_, une brochure remise à
jour périodiquement qui rassemble toutes les décisions et recommandations concernant les
unités.

La collection des _Travaux et mémoires du Bureau international des poids et mesures_
(22 tomes publiés de 1881 à 1966) a été arrêtée par décision du Comité international,
de même que le Recueil de travaux du Bureau international des poids et mesures
(11 volumes publiés de 1966 à 1988).

Les travaux du Bureau international font l’objet de publications dans des journaux
scientifiques.

Depuis 1965 la revue internationale _Metrologia_, éditée sous les auspices du Comité
international des poids et mesures, publie des articles sur la métrologie scientifique,
l’amélioration des méthodes de mesure, les travaux sur les étalons et sur les unités,
ainsi que des rapports concernant les activités, les décisions et les recommandations des
organes de la Convention du Mètre.

