
.Preface

Depuis son établissement en 1960 par une résolution adoptée par la Conférence générale
des poids et mesures (CGPM) à sa 11^e^ réunion, le Système international d’unités (SI) est
utilisé dans le monde entier comme le système préféré d’unités et comme le langage
fondamental de la science, de la technologie, de l’industrie et du commerce.

Cette Brochure sur le SI est publiée par le Bureau international des poids et mesures
(BIPM) afin d’expliquer et de promouvoir le SI. Elle regroupe les résolutions de la CGPM
et les décisions du Comité international des poids et mesures (CIPM) les plus importantes
concernant le système métrique depuis la première réunion de la CGPM en 1889.

Le SI a toujours été un système pratique et dynamique qui a évolué afin d’exploiter les
avancées scientifiques et technologiques les plus récentes. En particulier, les formidables
progrès réalisés ces 50 dernières années en physique atomique et en métrologie quantique
ont permis de réviser les définitions de la seconde et du mètre et d’ajuster la représentation
pratique des unités électriques afin de tirer parti des phénomènes atomiques et quantiques
pour atteindre, lors de la réalisation de ces unités, des niveaux d’exactitude qui ne sont
limités que par nos aptitudes techniques et non par les définitions elles-mêmes. Ces progrès
scientifiques, ainsi que l’évolution des technologies de mesure, ont conduit à apporter des
changements au SI qui ont tous été décrits dans les précédentes éditions de cette brochure.

La 9^e^ édition de la Brochure sur le SI a été préparée à la suite de l’adoption par la CGPM à
sa 26^e^ réunion d’un ensemble de changements profonds. La CGPM a adopté une nouvelle
manière de formuler les définitions des unités en général, et celles des sept unités de base
en particulier, en fixant la valeur numérique de sept constantes définissant le SI. Parmi ces
constantes figurent des constantes fondamentales de la nature, telles que la constante de
Planck et la vitesse de la lumière: ainsi, les définitions prennent pour fondement,
et représentent, notre compréhension actuelle des lois de la physique. Pour la première fois,
nous disposons d’un ensemble complet de définitions dont aucune ne fait référence à des
étalons physiques, des propriétés matérielles ou des descriptions de mesure.
Les changements apportés au SI permettent de réaliser l’ensemble des unités à un niveau
d’exactitude qui n’est finalement limité que par la structure quantique de la nature et nos
aptitudes techniques mais non par les définitions elles-mêmes. Toute équation valide de la
physique établissant un lien entre des constantes définissant le SI et une unité peut être
utilisée pour réaliser l’unité en question, ce qui ouvre la voie à de nouvelles possibilités
d’innovation, l’unité étant réalisable en tout lieu à un niveau d’exactitude croissant à
mesure que les technologies progressent. Ainsi, cette révision du SI constitue une avancée
historique fondamentale.

La révision du SI a été adoptée par la CGPM en novembre 2018 et les nouvelles définitions
prendront effet à compter du 20 mai 2019, date anniversaire de la signature de la
Convention du Mètre, célébrée par la Journée mondiale de la métrologie. Les changements
auront certes de profondes répercussions mais une attention particulière a été portée au fait
de garantir la cohérence de ces définitions avec celles en vigueur au moment de la mise en
oeuvre de la révision du SI.

Nous attirons l’attention sur le fait que depuis son établissement en 1960, le Système
international d’unités a, sous sa forme abrégée, toujours été désigné comme « le SI ».
Ce principe a été maintenu dans les huit précédentes éditions de la brochure et a été
réaffirmé dans la Résolution 1 adoptée par la CGPM à sa 26^e^ réunion, qui a par ailleurs
confirmé que le titre de cette brochure était simplement « Le Système international
d’unités ». Cette cohérence des références au SI reflète les efforts de la CGPM et du CIPM
afin d’assurer la continuité des valeurs des mesures exprimées en unités du SI lors de
chaque changement effectué.

Le texte de la brochure a pour objectif de fournir une description complète du SI et d’en
donner le contexte historique. En outre, la brochure compte quatre annexes:


L’annexe 1 reproduit, par ordre chronologique, toutes les décisions (Résolutions,
Recommandations, déclarations) promulguées depuis 1889 par la CGPM et le
CIPM sur les unités de mesure et le Système international d’unités.

L’annexe 2 est uniquement disponible en version électronique (www.bipm.org).
Elle concerne la réalisation pratique des sept unités de base et d’autres unités
importantes pour chaque domaine métrologique. Cette annexe sera mise à jour
régulièrement afin de refléter les progrès des techniques expérimentales utilisées
pour réaliser les unités.

L’annexe 3 est uniquement disponible en version électronique (www.bipm.org).
Elle décrit les unités permettant de mesurer les grandeurs photochimiques et
photobiologiques.

L’annexe 4 rend compte de l’évolution historique du SI.

Nous tenons, pour conclure, à remercier les membres du Comité consultatif des unités
(CCU) du CIPM qui ont eu pour responsabilité de préparer cette brochure. Le CCU et le
CIPM ont tous deux approuvé le texte final.

[align=right]
mars 2019


[NOTE]
====
La CGPM à sa 22^e^ réunion (2003) a décidé, suite à une décision prise par le CIPM en 1997,
que « le symbole du séparateur décimal pourra être soit le point sur la ligne, soit la virgule
sur la ligne ». Conformément à cette décision, et suivant l’usage dans les deux langues,
on utilise dans cette édition le point sur la ligne comme séparateur décimal en anglais,
et la virgule sur la ligne en français. Cette pratique n’a aucune implication en ce qui
concerne la traduction du séparateur décimal dans d’autres langues. Il faut noter qu’il existe
de petites variations dans l’orthographe de certains mots en anglais (par exemple, « metre »
et « meter », « litre » et « liter »). À cet égard, le texte anglais publié ici suit la série de
normes ISO/IEC 80000 « _Grandeurs et unités_ ». Néanmoins, les symboles des unités du SI
utilisés dans la présente brochure demeurent identiques dans toutes les langues.

Le lecteur doit noter que le texte officiel des réunions de la CGPM et des procès-verbaux du
CIPM est celui rédigé en français. La présente brochure est également disponible en anglais
mais c’est le français qui fait autorité si une référence est nécessaire ou s’il y a un doute sur
l’interprétation.
====