
== Introduction

=== Le SI défini en fonction de constantes de la physique

La Brochure sur le SI présente les informations nécessaires à la définition et à l’utilisation
du Système international d’unités, qui est universellement connu sous l’abréviation SI et
dont la Conférence générale des poids et mesures (CGPM) a la responsabilité. Le SI a été
formellement défini et établi en 1960 par la CGPM à sa 11^e^ réunion; il a ensuite été révisé
à plusieurs reprises afin de répondre aux exigences des utilisateurs et aux avancées de la
science et de la technologie. La révision la plus récente, et probablement la plus importante
depuis la création du SI, a été approuvée par la CGPM à sa 26^e^ réunion (2018): elle est
décrite dans cette 9^e^ édition de la Brochure sur le SI. La Convention du Mètre et ses
organes, à savoir la CGPM, le Comité international des poids et mesures (CIPM) et le
Bureau international des poids et mesures (BIPM), ainsi que les Comités consultatifs,
sont décrits dans le texte «&nbsp;<<le_bipm_et_la_cdm>>&nbsp;».

Le SI est un système d’unités cohérent qui est utilisé dans tous les aspects de la vie, que ce
soit le commerce international, la production industrielle, la santé et la sécurité,
la protection de l’environnement, ou les sciences fondamentales qui sont à la base de tous
ces domaines. Le système de grandeurs qui sous-tend le SI et les équations définissant les
relations entre ces grandeurs reposent sur la description actuelle de la nature et sont connus
de tous les scientifiques, techniciens et ingénieurs.

Les définitions des unités du SI sont établies à partir d’un ensemble de sept constantes de la
physique. À partir des valeurs fixées de ces sept constantes, exprimées en unités SI, il est
possible de déduire toutes les unités du système. Ces sept constantes sont ainsi l’élément le
plus essentiel de la définition de tout le système d’unités. Le choix spécifique de ces
sept constantes a été considéré le meilleur possible, en tenant compte de la précédente
définition du SI -- qui était fondée sur sept unités de base -- et des progrès de la science.

Diverses méthodes expérimentales, décrites par les Comités consultatifs du CIPM, peuvent
être utilisées afin de réaliser les unités: ces descriptions sont également appelées des
«&nbsp;mises en pratique&nbsp;». Ces réalisations sont susceptibles d’être révisées lorsque de nouvelles
expériences seront mises au point, c’est pourquoi la présente brochure ne contient pas de
recommandations en la matière: de telles informations sont disponibles sur le site internet
du BIPM.


=== Fondement de l’utilisation de constantes afin de définir le SI

Depuis l’établissement du SI, les unités du SI ont été présentées en fonction d’un ensemble
d’__unités de base__ – au nombre de sept depuis quelques décennies. Toutes les autres unités,
appelées _unités dérivées_, sont formées à partir de produits de puissances des unités de base.

Différents types de définitions ont été utilisés pour les unités de base: des propriétés
particulières de certains artéfacts comme la masse du prototype international du
kilogramme pour l’unité «&nbsp;kilogramme&nbsp;»; un état physique particulier tel que le point triple
de l’eau pour l’unité «&nbsp;kelvin&nbsp;»; des principes expérimentaux nécessitant des conditions
idéalisées comme dans le cas des unités «&nbsp;ampère&nbsp;» et «&nbsp;candela&nbsp;»; ou des constantes de la
nature telles que la vitesse de la lumière pour la définition de l’unité «&nbsp;mètre&nbsp;».

Pour avoir une utilité pratique, ces unités doivent non seulement être définies mais elles
doivent également être réalisées concrètement pour pouvoir être disséminées. Dans le cas
d’un artéfact, la définition et la réalisation sont équivalentes. Ce choix a été privilégié par
d’anciennes civilisations avancées. Bien que cette méthode soit simple et claire,
les artéfacts présentent un risque de perte, d’endommagement ou de variation de leurs
caractéristiques. Les autres types de définitions d’une unité sont devenus de plus en plus
abstraits ou idéalisés. D’un point de vue conceptuel, les réalisations sont alors dissociées
des définitions, de sorte que les unités puissent, par principe, être réalisées de façon
indépendante en tout lieu et à tout moment. En outre, de meilleures réalisations pourront
être développées grâce aux progrès des sciences et des technologies, sans qu’il ne soit
nécessaire pour autant de redéfinir l’unité concernée. Comme le démontre l’histoire de la
définition du mètre, fondée d’abord sur des artéfacts puis sur une transition atomique de
référence et, enfin, sur la fixation d’une valeur numérique de la vitesse de la lumière, ces
avantages ont conduit à prendre la décision de définir toutes les unités à l’aide de constantes
choisies.

Le choix des unités de base n’a jamais été imposé; ce choix s’est affirmé dans le temps et il
est désormais bien connu des utilisateurs du SI. La description du SI en fonction d’unités de
base et d’unités dérivées est conservée dans la présente brochure mais a été reformulée du
fait de l’adoption des constantes définissant le SI.


=== Mise en oeuvre du SI

Les définitions des unités du SI, telles qu’adoptées par la CGPM, représentent le niveau de
référence le plus élevé en matière de traçabilité de mesure au SI.

Les laboratoires de métrologie à travers le monde mettent au point des réalisations pratiques
des définitions afin de permettre la traçabilité de leurs mesures au SI. Les Comités consultatifs
déterminent le cadre permettant d’établir l’équivalence des réalisations afin d’harmoniser la
traçabilité au niveau mondial.

Les organismes de normalisation peuvent donner des informations supplémentaires sur les
grandeurs et unités, ainsi que sur leurs règles d’application, lorsque cela est requis par les
parties intéressées. Lorsque des unités du SI sont mentionnées dans des normes, ces dernières
doivent faire référence aux définitions adoptées par la CGPM. De telles informations sont
notamment incluses dans les normes internationales élaborées par l’Organisation
internationale de normalisation (ISO) et la Commission électrotechnique internationale (IEC),
telles que les normes de la série ISO/IEC 80000.

Les États fixent par voie législative les règles concernant l’utilisation des unités sur le plan
national, soit pour l’usage général, soit pour certains domaines particuliers comme le
commerce, la santé, la sécurité publique ou l’enseignement. Dans la plupart des pays,
la législation est fondée sur l’emploi du SI. L’Organisation internationale de métrologie
légale (OIML) est en charge de l’harmonisation mondiale des spécifications techniques de
ces législations.

