
[[chapter3]]
== Multiples et sous-multiples décimaux des unités SI

Des multiples et sous-multiples décimaux de stem:[10^24] à stem:[10^{-24}] peuvent être utilisés avec les
unités SI. Les noms et les symboles des préfixes adoptés pour former les noms et symboles
des multiples et sous-multiples décimaux des unités sont présentés dans le <<table-7>>.

Les symboles des préfixes sont écrits en caractères romains, comme les symboles d’unités,
quelle que soit la police utilisée dans le reste du texte; ils sont attachés aux symboles
d’unités, sans espace entre le symbole du préfixe et celui de l’unité. À l’exception des
symboles stem:["da"] (déca), stem:["h"] (hecto), et stem:["k"] (kilo), tous les symboles des préfixes des multiples sont
en majuscules et tous les symboles des préfixes des sous-multiples sont en minuscules.
Tous les noms de préfixes sont en minuscules, sauf en début de phrase.

[NOTE]
====
Les préfixes SI représentent strictement
des puissances de 10. Ils ne doivent pas être
utilisés pour exprimer des puissances de 2
(par exemple, un kilobit représente 1000 bits
et non 1024 bits). Les noms et symboles
recommandés pour les préfixes correspondant
à des puissances de 2 sont les suivants :

[%unnumbered]
[cols="<,<,<"]
|===
| kibi | stem:["Ki"] | stem:[2^(10)]
| mebi | stem:["Mi"] | stem:[2^(20)]
| gibi | stem:["Gi"] | stem:[2^(30)]
| tebi | stem:["Ti"] | stem:[2^(40)]
| pebi | stem:["Pi"] | stem:[2^(50)]
| exbi | stem:["Ei"] | stem:[2^(60)]
| zebi | stem:["Zi"] | stem:[2^(70)]
| yobi | stem:["Yi"] | stem:[2^(80)]
|===
====

[[table-7]]
.Préfixes du SI
[cols="^,1,^,^,1,^",options="header"]
|===
| Facteur | Nom | Symbole | Facteur | Nom | Symbole

| stem:[10^1] | déca | stem:["da"] | stem:[10^{-1}] | déci | stem:["d"]
| stem:[10^2] | hecto | stem:["h"] | stem:[10^{-2}] | centi | stem:["c"]
| stem:[10^3] | kilo | stem:["k"] | stem:[10^{-3}] | milli | stem:["m"]
| stem:[10^6] | méga | stem:["M"] | stem:[10^{-6}] | micro | stem:[mu]
| stem:[10^9] | giga | stem:["G"] | stem:[10^{-9}] | nano | stem:["n"]
| stem:[10^12] | téra | stem:["T"] | stem:[10^{-12}] | pico | stem:["p"]
| stem:[10^15] | péta | stem:["P"] | stem:[10^{-15}] | femto | stem:["f"]
| stem:[10^18] | exa | stem:["E"] | stem:[10^{-18}] | atto | stem:["a"]
| stem:[10^21] | zetta | stem:["Z"] | stem:[10^{-21}] | zepto | stem:["z"]
| stem:[10^24] | yotta | stem:["Y"] | stem:[10^{-24}] | yocto | stem:["y"]
|===



Le groupe formé par le symbole d’un préfixe attaché au symbole d’une unité constitue un
nouveau symbole d’unité inséparable (indiquant un multiple ou sous-multiple de l’unité en
question) qui peut être élevé à une puissance positive ou négative et qui peut être combiné à
d’autres symboles d’unités pour former des symboles d’unités composés.


====
stem:["pm"] (picomètre), stem:["mmol"] (millimole), stem:["G" Omega] (gigaohm), stem:["THz"] (terahertz)

[stem%unnumbered]
++++
2.3 " cm"^3 = 2.3 ("cm")^3 = 2.3 (10^{-2} "m")^3 = 2.3 xx 10^{-6} " m"^3
++++

[stem%unnumbered]
++++
1 " cm"^{-1} = 1 ("cm")^{-1} = 1 (10^{-2} "m")^{-1} = 10^2 " m"^{-1} = 100 " m"^{-1}
++++
====


De même, les noms de préfixes ne sont pas séparés des noms d’unités auxquels ils sont
attachés. Par exemple, millimètre, micropascal et méganewton s’écrivent en un seul mot.

Les symboles de préfixes composés, c’est-à-dire les symboles de préfixes formés par
juxtaposition de deux ou plusieurs symboles de préfixes, sont interdits. Cette règle
s’applique aussi aux noms de préfixes composés.

Les symboles de préfixes ne peuvent pas être utilisés seuls ou attachés au nombre 1,
le symbole de l’unité « un ». De même, les noms de préfixes ne peuvent pas être attachés au
nom de l’unité « un », c’est-à-dire au mot « un ».

Le kilogramme est la seule unité SI cohérente dont le nom et le symbole, pour des raisons
historiques, contiennent un préfixe. Les noms et les symboles des multiples et
sous-multiples décimaux de l’unité de masse sont formés par l’adjonction de noms de
préfixes au mot « gramme » et de symboles de ces préfixes au symbole de l’unité « g ».
Ainsi, stem:[10^{-6} " kg"] s’écrit milligramme, stem:["mg"], et non microkilogramme, stem:[mu"kg"].

