== Partie 1. L’évolution historique de la réalisation des unités du SI

Les méthodes expérimentales utilisées pour réaliser les unités à l’aide d’équations de la
physique sont appelées méthodes primaires. Une méthode primaire a pour caractéristique
essentielle de permettre de mesurer directement une grandeur dans une unité particulière à
partir de sa définition en utilisant seulement des grandeurs et constantes qui n’impliquent
pas elles-mêmes l’unité en question.

De façon traditionnelle, une unité pour une grandeur donnée était considérée comme un
exemple particulier de cette grandeur, choisie pour fournir des valeurs numériques de
mesures courantes d’une taille convenable. Avant l’avènement de la science moderne,
les unités étaient nécessairement définies à partir d’artéfacts matériels, notamment le mètre
pour la longueur et le kilogramme pour la masse, ou à partir de la propriété d’un objet
particulier, comme la rotation de la Terre pour la seconde. Toutefois, même à l’origine du
système métrique à la fin du 18^e^ siècle, il était reconnu qu’une définition plus souhaitable
de l’unité de longueur, par exemple, serait une définition fondée sur une propriété
universelle de la nature telle que la longueur d’un pendule battant la seconde. Une telle
définition serait indépendante du moment et du lieu de réalisation de l’unité et serait en
principe accessible dans le monde entier. À cette époque, des considérations pratiques ont
conduit à des définitions plus simples, fondées sur des artéfacts, du mètre et du kilogramme
et la seconde est restée liée à la rotation de la Terre. Ce n’est qu’en 1960 que la première
définition non matérielle du mètre, à savoir la longueur d’onde d’un rayonnement optique
spécifique, a été adoptée.

Les définitions de l’ampère, du kelvin, de la mole et de la candela qui furent ensuite
adoptées ne faisaient pas référence à des artéfacts matériels: la définition de l’ampère était
fondée sur un courant électrique spécifique requis pour produire une force
électromagnétique donnée et la définition du kelvin sur un état thermodynamique
particulier du point triple de l’eau. La définition atomique de la seconde reposait sur une
transition spécifique de l’atome de césium. Le kilogramme a toujours fait exception puisque
c’était la seule unité restant fondée sur un artéfact. La définition qui a ouvert la voie à une
réelle universalité a été celle du mètre adoptée en 1983. Bien qu’elle ne l’indique pas
explicitement, cette définition impliquait une valeur numérique fixée de la vitesse de la
lumière. La définition était formulée, cependant, de façon traditionnelle et énonçait pour
l’essentiel que le mètre était la distance parcourue par la lumière en un temps donné.
De cette façon, la définition du mètre avait la même forme que les définitions des autres
unités de base du SI («&nbsp; l’ampère est le courant qui... &nbsp;», «&nbsp; le kelvin est une fraction d’une
température précise &nbsp;», etc.). De telles définitions peuvent être désignées sous le terme de
«&nbsp; définitions à unité explicite &nbsp;».

Bien que ces définitions répondent à plusieurs des exigences d’universalité et
d’accessibilité, et qu’elles peuvent être réalisées de diverses façons possibles, elles limitent
toutefois les réalisations pratiques à des expériences directement ou indirectement liées aux
conditions ou états particuliers précisés dans les définitions. Par conséquent, l’exactitude de
la mise en pratique de telles définitions ne peut jamais être meilleure que l’exactitude de la
réalisation des conditions ou états particuliers précisés dans les définitions.

C’est un problème particulier avec l’actuelle définition de la seconde fondée sur une
transition microonde d’un atome de césium. Il a été établi que les fréquences des transitions
optiques de différents atomes ou ions sont désormais plus reproductibles, de quelques
ordres de grandeur, que la fréquence définie du césium.

Dans la présente révision du SI fondée sur un ensemble de constantes choisies, au lieu que
chaque définition indique une condition ou un état spécifique, ce qui impose une limite
fondamentale à l’exactitude de la réalisation, toute équation appropriée de la physique qui
relie la ou les constantes particulières à la grandeur à mesurer peut être utilisée. Les unités
de base sont ainsi définies de façon beaucoup plus générale, sans limite imposée par la
science ou les technologies actuelles car les progrès à venir pourront conduire à découvrir
des équations aujourd’hui inconnues qui permettront de réaliser les unités de différentes
manières, à un niveau d’exactitude beaucoup plus élevé. Avec un système d’unités ainsi
défini, il n’existe en principe aucune limite concernant l’incertitude à laquelle une unité
peut être réalisée. L’exception reste la définition de la seconde pour laquelle la transition
microonde du césium est conservée, pour le moment, comme base de la définition.

La différence entre une «&nbsp; définition à unité explicite &nbsp;» et une «&nbsp; définition à constante
explicite &nbsp;» peut être clairement illustrée à l’aide des deux précédentes définitions du mètre
qui reposaient sur une valeur numérique fixée de la vitesse de la lumière ou à l’aide des
deux définitions du kelvin. La définition originale du mètre de 1983 indique, en effet, que
«&nbsp; le mètre est la longueur du trajet parcouru dans le vide par la lumière pendant une durée
de stem:[1//299792458] de seconde &nbsp;». La nouvelle définition indique simplement que le mètre est
défini en fonction de la constante définissant la seconde, la fréquence du césium précisée,
et de la valeur numérique de la vitesse de la lumière exprimée en unité stem:["m s"^{-1}]. Il est ainsi
possible d’utiliser toute équation de la physique, y compris bien sûr celle spécifiée dans la
précédente définition, le temps nécessaire pour effectuer le trajet d’une distance donnée,
utilisée pour les distances astronomiques, mais aussi la simple équation reliant la fréquence
et la longueur d’onde à la vitesse de la lumière. La précédente définition du kelvin fondée
sur une valeur numérique fixée de la température du point triple de l’eau nécessite en fin de
compte une mesure à la température du point triple de l’eau. La nouvelle définition, fondée
sur la valeur numérique fixée de la constante de Boltzmann, est beaucoup plus générale au
sens où toute équation thermodynamique contenant stem:[k] peut en principe être utilisée pour
déterminer une température thermodynamique à tout point de l’échelle de température.
Par exemple, en déterminant l’exitance énergétique totale d’un corps noir à la température stem:[T], équivalente à stem:[(2 pi^5 k^4//15c^2 h^3) T^4], en stem:["W m"^{-2}], il est possible de déterminer directement stem:[T].

Concernant le kilogramme, l’unité dont la définition a changé de la façon la plus
fondamentale dans la présente brochure, la réalisation peut être effectuée à partir de toute
équation de la physique reliant la masse, la constante de Planck, la vitesse de la lumière et
la fréquence du césium. L’une de ces équations est celle décrivant le fonctionnement d’une
balance électromécanique, connue précédemment sous le nom de balance du watt et plus
récemment de balance de Kibble
footnote:[La balance du watt a été renommée balance de Kibble, du nom de son inventeur Bryan Kibble.].
Une balance de Kibble permet de mesurer une puissance
mécanique, mesurée en fonction d’une masse, stem:[m], l’accélération due à la gravité, stem:[g], et une
vitesse, stem:[v], à l’aide d’une puissance électrique mesurée à partir d’un courant électrique et
d’une tension mesurées à l’aide des effets Hall quantique et Josephson, respectivement.
L’équation qui en résulte est la suivante stem:[mgv = Ch] où stem:[C] est une constante d’étalonnage qui
comprend des fréquences mesurées et stem:[h] la constante de Planck.

Une autre méthode pouvant être utilisée comme réalisation primaire du kilogramme est la
détermination du nombre d’atomes contenus dans une sphère de silicium à l’aide de
l’équation:

[stem%unnumbered]
++++
m = {8V}/{a_0^3} {2R_{oo}h}/{c alpha^2} m_{"Si"}/m_"e"
++++


avec la masse stem:[m] et le volume stem:[V] de la sphère (d’environ stem:[1 " kg"]), le paramètre de réseau stem:[a_0],
la constante de Rydberg stem:[R_{oo}], la constante de structure fine stem:[alpha], la masse d’un atome de
silicium (en établissant une moyenne par rapport aux trois isotopes des sphères) stem:[m_"Si"],
et la masse d’un électron stem:[m_"e"]. La première fraction correspond au nombre d’atomes contenus
dans la sphère, la deuxième à la masse de l’électron et la troisième au rapport de la masse
de l’atome de silicium (pondérée isotopiquement) et de la masse de l’électron.

Une autre possibilité pour mesurer la masse à l’aide de la nouvelle définition du
kilogramme, mais cette fois au niveau microscopique, est de mesurer le recul atomique à
l’aide de la relation incluant stem:[h//m].

Toutes ces méthodes illustrent parfaitement le caractère général de la nouvelle façon de
définir les unités. Le site internet du BIPM contient des informations détaillées sur les
réalisations actuelles des unités de base et des autres unités.

