== L’évolution historique du Système international

La CGPM à sa 9^e^ réunion (1948, Résolution 6; CR, 64), chargea le CIPM:

* d’étudier l’établissement d’une réglementation complète des unités de mesure;

* d’ouvrir à cet effet une enquête officielle sur l’opinion des milieux scientifiques,
techniques et pédagogiques de tous les pays et

* d’émettre des recommandations concernant l’établissement d’un [...]
_système pratique d’unités de mesure_, susceptible d’être adopté dans tous les pays
signataires de la Convention du Mètre.

Cette même CGPM adopta aussi la Résolution 7 (CR, 70) qui fixe des principes généraux
pour l’écriture des symboles d’unités et donne une liste de quelques unités cohérentes ayant
un nom spécial.

La CGPM à sa 10^e^ réunion (1954, Résolution 6; CR, 80) adopta comme grandeurs et unités
de base de ce système pratique d’unités les six grandeurs suivantes: longueur, masse,
temps, courant électrique, température thermodynamique et intensité lumineuse, ainsi que
les six unités de base correspondantes: mètre, kilogramme, seconde, ampère, kelvin et
candela. Après de longues discussions entre physiciens et chimistes, la CGPM à sa
14^e^ réunion (1971, Résolution 3, CR 78 et _Metrologia_ 1972, *8*, 36) ajouta la quantité de
matière comme septième grandeur de base, avec pour unité de base la mole.

La CGPM à sa 11^e^ réunion (1960, Résolution 12; CR, 87) adopta le nom
_Système international d’unités_, avec l’abréviation internationale _SI_, pour ce système pratique
d’unités et fixa des règles pour les préfixes, les unités dérivées et les unités supplémentaires
(disparues depuis) et d’autres indications, établissant ainsi une réglementation d’ensemble
pour les unités de mesure. Au cours des réunions qui suivirent, la CGPM et le CIPM
étoffèrent et modifièrent la structure originelle du SI pour tenir compte des progrès de la
science et de l’évolution des besoins des utilisateurs.

Il est possible de résumer comme suit les principales étapes historiques qui conduisirent à
ces décisions importantes:

* La création du Système métrique décimal au moment de la Révolution française et le
dépôt qui en a résulté, le 22 juin 1799, de deux étalons en platine représentant le
mètre et le kilogramme aux Archives de la République à Paris peuvent être
considérés comme la première étape ayant conduit au Système international d’unités
actuel.

* En 1832, Gauss oeuvra activement en faveur de l’application du Système métrique,
associé à la seconde, définie en astronomie, comme système cohérent d’unités pour
les sciences physiques. Gauss fut le premier à faire des mesures absolues du champ
magnétique terrestre en utilisant un système décimal fondé sur les _trois unités
mécaniques_ millimètre, gramme et seconde pour, respectivement, les grandeurs
longueur, masse et temps. Par la suite, Gauss et Weber ont étendu ces mesures pour
y inclure d’autres phénomènes électriques.

* Dans les années 1860, Maxwell et Thomson mirent en oeuvre de manière plus complète
ces mesures dans les domaines de l’électricité et du magnétisme au sein de la British
Association for the Advancement of Science (BAAS). Ils exprimèrent les règles de
formation d’un _système cohérent d’unités_ composé d’unités de base et d’unités dérivées.
En 1874, la BAAS introduisit le système CGS, un système d’unités tri-dimensionnel
cohérent fondé sur les trois unités mécaniques centimètre, gramme et seconde, et utilisant
des préfixes allant de micro à méga pour exprimer les sous-multiples et multiples
décimaux. C’est en grande partie sur l’utilisation de ce système que se fonda, par la suite,
le développement expérimental des sciences physiques.

* Le fait de compléter de façon cohérente le système CGS pour les domaines de
l’électricité et du magnétisme conduisit à choisir des unités d’amplitude peu adaptée
à la pratique. Le BAAS et le Congrès international d’électricité, qui précéda la
Commission électrotechnique internationale (IEC), approuvèrent, dans les années
1880, un système mutuellement cohérent d’__unités pratiques__. Parmi celles-ci
figuraient l’ohm pour la résistance électrique, le volt pour la force électromotrice et
l’ampère pour le courant électrique.

* Après la signature, le 20 mai 1875, de la Convention du Mètre, qui créa le BIPM et
établit la CGPM et le CIPM, on fabriqua de nouveaux prototypes internationaux du
mètre et du kilogramme, approuvés en 1889 par la CGPM à sa 1^ère^ réunion.
Avec la seconde des astronomes comme unité de temps, ces unités constituaient un
système d’unités mécaniques tri-dimensionnel similaire au système CGS, mais dont
les unités de base étaient le mètre, le kilogramme et la seconde, connu sous le nom
de système MKS.

* En 1901, Giorgi montra qu’il était possible de combiner les unités mécaniques du
système MKS au système pratique d’unités électriques pour former un seul système
cohérent quadri-dimensionnel en ajoutant à ces trois unités de base une quatrième
unité, de nature électrique, telle que l’ampère ou l’ohm, et en rationalisant les
équations utilisées en électromagnétisme. La proposition de Giorgi ouvrit la voie à
d’autres extensions.

* Après la révision de la Convention du Mètre par la CGPM à sa 6^e^ réunion (1921),
qui étendit les attributions et les responsabilités du BIPM à d’autres domaines de la
physique, et la création du Comité consultatif d’électricité (CCE) par la CGPM à sa
7^e^ réunion qui en a résulté en 1927, la proposition de Giorgi fut discutée en détail
par l’IEC, l’International Union of Pure and Applied Physics (IUPAP) et d’autres
organisations internationales. Ces discussions conduisirent le CCE à proposer,
en 1939, l’adoption d’un système quadri-dimensionnel fondé sur le mètre,
le kilogramme, la seconde et l’ampère (système MKSA), une proposition qui fut
approuvée par le Comité international en 1946.

* À la suite d’une enquête internationale effectuée par le BIPM à partir de 1948,
la CGPM à sa 10^e^ réunion (1954) approuva l’introduction du kelvin et de la candela
comme unités de base de la température thermodynamique et de l’intensité
lumineuse, respectivement. La CGPM à sa 11^e^ réunion (1960) donna le nom de
Système international d’unités (SI) à ce système. Des règles pour les préfixes,
les unités dérivées et les unités supplémentaires (disparues depuis) et d’autres
indications furent établies, établissant ainsi une réglementation d’ensemble pour les
unités de mesure.

* Lors de la 14^e^ réunion de la CGPM (1971), une nouvelle unité de base, la mole,
symbole stem:[rm(mol)], a été adoptée pour la quantité de matière. Cela fit suite à une
proposition formulée par l’Organisation internationale de normalisation (ISO),
émanant en premier lieu de la Commission on Symbols, Units and Nomenclature de
l’International Union of Pure and Applied Physics (IUPAP) et soutenue par
l’International Union of Pure and Applied Chemistry (IUPAC). Le SI passa ainsi à
sept unités de base.

* Depuis, des avancées extraordinaires ont été réalisées pour relier les unités du SI à
des grandeurs véritablement invariantes telles que les constantes fondamentales de la
physique et les propriétés des atomes. Reconnaissant l’importance de relier les unités
du SI à de telles grandeurs invariantes, la CGPM à sa 24^e^ réunion (2011) adopta les
principes d’une nouvelle définition du SI fondée sur l’utilisation d’un ensemble de
sept constantes de ce type comme références des définitions des unités. Au moment
de la 24^e^ réunion de la CGPM, les expériences visant à déterminer les valeurs
numériques de ces constantes ne permettaient pas d’obtenir des résultats
complètement cohérents mais cela fut le cas lors de la 26^e^ réunion de la CGPM
(2018) et la nouvelle définition du SI fut adoptée dans la Résolution 1. Telle est la
base de la définition du SI présentée dans la présente brochure: elle constitue la
façon la plus simple et la plus fondamentale de définir le SI.

* Le SI était précédemment défini en fonction de sept unités de base, et d’unités
dérivées définies comme le produit de puissances des unités de base. Les sept unités
de base avaient été choisies pour des raisons historiques, en fonction de l’évolution
du système métrique et du développement du SI au cours des 130 dernières années.
Le choix de ces unités n’était pas le seul possible mais au fil des ans, cela est devenu
un fait établi et ces unités sont devenues familières, fournissant non seulement un
cadre pour décrire le SI mais aussi pour définir les unités dérivées. Le rôle des unités
de base demeure le même dans l’actuel SI, bien que le SI lui-même soit défini sur la
base de sept constantes choisies. Ainsi, dans la présente brochure, les définitions des
sept unités de base restent présentes mais elles se fondent sur les sept constantes
définissant le SI, à savoir la fréquence stem:[Delta nu_{"Cs"}] de la transition hyperfine de l’état
fondamental de l’atome de césium, la vitesse stem:[c] de la lumière dans le vide,
la constante de Planck stem:[h], la charge élémentaire stem:[e], la constante de Boltzmann stem:[k],
la constante d’Avogadro stem:[ii(N)_"A"] et l’efficacité lumineuse stem:[ii(K)_{"cd"}] d’un rayonnement visible
défini.

Les définitions des sept unités de base peuvent être reliées sans ambiguïté aux valeurs
numériques des sept constantes définissant le SI mais il n’existe pas de correspondance
biunivoque entre les sept constantes et les sept unités de base car plusieurs des unités de
base peuvent être reliées à plus d’une de ces sept constantes.
