== Perspective historique sur les unités de base du SI

=== Unité de temps, la seconde (((seconde))) (((temps,durée)))

Avant 1960, l’unité de temps, la seconde, était définie comme la fraction stem:[1//86400] du jour
solaire moyen. La définition exacte du «&nbsp;jour solaire moyen&nbsp;» était laissée aux astronomes.
Toutefois, les observations ont montré que cette définition n’était pas satisfaisante du fait
des irrégularités de la rotation de la Terre. Pour donner plus de précision à la définition de
l’unité de temps, la CGPM à sa 11^e^ réunion (1960, Résolution 9; CR, 86) approuva une
définition, donnée par l’Union astronomique internationale, qui était fondée sur l’année
tropique 1900. Cependant, les recherches expérimentales avaient déjà montré qu’un étalon
atomique de temps, fondé sur une transition entre deux niveaux d’énergie d’un atome ou
d’une molécule, pourrait être réalisé et reproduit avec une exactitude beaucoup plus élevée.
Considérant qu’une définition de haute précision de l’unité de temps était indispensable
pour la science et la technologie, la CGPM à sa 13^e^ réunion (1967-1968, Résolution 1;
CR, 103 et _Metrologia_, 1968, *4*, 43) choisit une nouvelle définition de la seconde fondée sur
la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium((("atome de césium, niveaux hyperfins"))) 133.
Une nouvelle formulation plus précise de cette même définition, fondée désormais sur une
valeur numérique fixée de la fréquence de la transition hyperfine de l’état fondamental
de l’atome de césium((("atome de césium, niveaux hyperfins"))) 133 non perturbé, stem:[Delta ii(nu)_{Cs}], a été adoptée par la CGPM à sa 26^e^ réunion
(2018) dans sa Résolution 1.


=== Unité de longueur, le mètre (((longueur)))(((mètre (m))))(((mètre (m),prototype international)))

La définition du mètre de 1889, à savoir la longueur du prototype international en platine
iridié, avait été remplacée par la CGPM à sa 11^e^ réunion (1960) par une définition fondée
sur la longueur d’onde d’une radiation correspondant à une transition particulière du
krypton 86, afin d’améliorer l’exactitude de la réalisation de la définition du mètre.
Cette réalisation était effectuée au moyen d’un interféromètre et d’un microscope mobile en
translation utilisés pour mesurer la variation des trajets optiques par comptage de franges.
Cette définition fut remplacée en 1983 par la CGPM à sa 17^e^ réunion (Résolution 1;
CR, 97 et _Metrologia_, 1984, *20*, 25) par une définition fondée sur la ((longueur)) du trajet
parcouru dans le vide par la lumière dans un intervalle de temps spécifique. Le prototype
international du mètre originel, qui fut approuvé par la CGPM à sa 1^ère^ réunion en 1889
(CR, 34-38), est toujours conservé au BIPM dans les conditions fixées en 1889. Afin de
mettre en évidence la dépendance de la définition du mètre(((mètre (m)))) vis-à-vis de la valeur numérique
fixée de la vitesse de la lumière, stem:[c], la formulation de la définition du mètre a été modifiée
par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


=== Unité de masse, le kilogramme (((kilogramme,prototype international)))(((masse)))

Selon la définition du ((kilogramme)) de 1889, l’unité de masse était simplement égale à la
masse du prototype international du kilogramme, un artéfact fabriqué en platine iridié.
Ce prototype était conservé au BIPM, et l’est toujours, dans les conditions fixées par la
CGPM à sa 1^ère^ réunion en 1889 (CR, 34-38) lorsque cette dernière sanctionna le prototype
et déclara: «&nbsp;Ce prototype sera considéré désormais comme unité de masse&nbsp;».
Quarante prototypes similaires ont été fabriqués à la même époque; tous ont été usinés et
polis afin d’avoir la même ((masse)) que celle du prototype international. Lors de la première
réunion de la CGPM en 1889, la plupart de ces «&nbsp;étalons nationaux&nbsp;», une fois étalonnés à
l’aide du prototype international du kilogramme, ont été assignés à des États Membres de la
((Convention du Mètre)) et certains au BIPM. La CGPM à sa 3^e^ réunion en 1901 (CR, 70),
dans une déclaration visant à faire cesser l’ambiguïté qui existait dans l’usage courant sur la
signification du terme «&nbsp;poids&nbsp;», confirma que «&nbsp;le kilogramme est l’unité de masse; il est
égal à la ((masse)) du prototype international du kilogramme&nbsp;»; la version complète de cette
déclaration figure page 70 des comptes rendus de la CGPM précédemment mentionnés.

Lors de la ((seconde)) vérification des prototypes nationaux en 1946, il fut toutefois constaté
qu’en moyenne, la ((masse)) de ces prototypes divergeait par rapport à celle du prototype
international. Cela fut confirmé lors de la troisième vérification, effectuée de 1989 à 1991,
la différence moyenne étant d’environ 25 microgrammes pour l’ensemble des prototypes
originaux sanctionnés par la CGPM à sa première réunion (1889). Afin d’assurer la stabilité
à long terme de l’unité de ((masse)), de tirer pleinement parti des étalons électriques
quantiques et de répondre au mieux à la science moderne, une nouvelle définition du
((kilogramme)) fondée sur la valeur d’une constante fondamentale(((constante, fondamentale (de la physique)))), la constante de Planck(((constante, de Planck))) stem:[h],
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


=== Unité de ((courant électrique)), l’ampère(((ampère (A)))) index-range:ohm_omega-2[(((ohm (stem:[Omega]))))]

Des unités électriques, dites «&nbsp;internationales&nbsp;», pour le courant et la résistance, avaient été
introduites par le Congrès international d’électricité tenu à Chicago en 1893 et les
définitions de l’ampère(((ampère (A)))) «&nbsp;international&nbsp;» et de l’ohm «&nbsp;international&nbsp;» furent confirmées par
la Conférence internationale de Londres en 1908.

Le souhait unanime de remplacer ces unités «&nbsp;internationales&nbsp;» par des unités dites
«&nbsp;absolues&nbsp;» fut déjà exprimé lors de la 8^e^ réunion de la CGPM (1933). Toutefois, étant
donné que certains laboratoires n’avaient pas encore achevé les expériences nécessaires
pour déterminer les rapports entre les unités internationales et les unités absolues, la CGPM
chargea le CIPM de décider, en temps opportun, des rapports et de la date d’adoption de ces
nouvelles unités absolues. Le CIPM décida en 1946 (1946, Résolution 2, PV, *20*, 129-137)
que les nouvelles unités entreraient en vigueur le 1^er^ janvier 1948. En octobre 1948,
la CGPM à sa 9^e^ réunion approuva les décisions prises par le CIPM. La définition de
l’ampère(((ampère (A)))) choisie par le CIPM était fondée sur la force produite entre deux conducteurs
parallèles parcourus par un ((courant électrique)) et fixait par conséquent la valeur de la
perméabilité magnétique du vide(((constante, magnétique&#44; perméabilité du vide))) stem:[ii(mu)_0] (ou constante magnétique). La valeur de la permittivité
diélectrique du vide stem:[ii(epsilon)_0] (ou constante électrique) fut ensuite fixée du fait
de l’adoption de la nouvelle définition du mètre en 1983.
(((effet,Hall (y compris Hall quantique))))(((effet,Josephson)))

Toutefois, la définition de l’ampère(((ampère (A)))) de 1948 s’avéra difficile à réaliser et les étalons
quantiques pratiques (à effet Josephson et à effet Hall quantique), qui relient le volt et
l’ohm aux combinaisons particulières de la constante de Planck(((constante, de Planck))) stem:[h] et de la charge
élémentaire stem:[e], furent utilisés de façon presque universelle comme réalisation pratique de
l’ampère(((ampère (A)))) à l’aide de la loi d’Ohm (CGPM, 1987, Résolution 6; CR, 100). Par conséquent,
il devint naturel non seulement de fixer la valeur numérique de stem:[h] pour redéfinir le
kilogramme mais aussi de fixer la valeur numérique de stem:[e] pour redéfinir l’ampère(((ampère (A)))) afin que
les étalons électriques quantiques pratiques soient exactement en accord avec le SI.
L’actuelle définition de l’ampère(((ampère (A)))) fondée sur une valeur numérique fixée de la charge
élémentaire, stem:[e], a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1. [[ohm_omega-2]]


=== Unité de température thermodynamique, le kelvin (((kelvin (K))))(((température,thermodynamique)))

La définition de l’unité de température thermodynamique fut donnée par la CGPM à sa
10^e^ réunion (1954, Résolution 3; CR, 79) qui choisit
le ((point triple de l’eau)), stem:[ii(T)_{"TPW"}], comme
point fixe fondamental en lui attribuant la température de stem:[273.16 " "rm(K)] par définition.
La CGPM à sa 13^e^ réunion (1967-1968, Résolution 3; CR, 104 et _Metrologia_, 1968, *4*, 43)
adopta le nom «&nbsp;kelvin&nbsp;», symbole stem:[rm(K)], au lieu de «&nbsp;degré kelvin&nbsp;»(((degré kelvin))), symbole stem:["°"rm(K)], pour l’unité
définie de cette façon. Toutefois, les difficultés pratiques liées à la réalisation de cette
définition, qui requiert un échantillon d’eau pure à la composition isotopique bien définie
ainsi que le développement de nouvelles méthodes primaires thermométriques, ont conduit
à l’adoption d’une nouvelle définition du kelvin fondée sur une valeur numérique fixée de
la constante de Boltzmann(((constante, de Boltzmann))), stem:[k]. L’actuelle définition du kelvin, qui supprime ces contraintes,
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


=== Unité de quantité de matière, la mole index-range:mole_mol-2[(((mole (mol))))](((molécule gramme)))(((poids atomique)))(((poids moléculaire)))(((quantité de matière))) index-range:quantite_matiere-2[(((quantité de matière)))]

Après la découverte des lois fondamentales de la chimie, on a utilisé, pour spécifier les
quantités des divers éléments et composés chimiques, des unités portant par exemple les
noms de «&nbsp;atome-gramme&nbsp;»(((atome gramme))) et «&nbsp;molécule-gramme&nbsp;». Ces unités étaient liées directement
aux «&nbsp;poids atomiques&nbsp;» et aux «&nbsp;poids moléculaires&nbsp;» qui étaient en réalité des masses
atomiques et moléculaires relatives. Les «&nbsp;poids atomiques&nbsp;» furent d’abord rapportés à
celui de l’élément chimique oxygène, pris par convention égal à 16. Tandis que les
physiciens séparaient les isotopes au spectromètre de ((masse)) et attribuaient la valeur 16 à
l’un des isotopes de l’oxygène, les chimistes attribuaient la même valeur au mélange
(de composition légèrement variable) des isotopes 16, 17 et 18 qui constitue l’élément
oxygène naturel. Un accord entre l’International Union of Pure and Applied Physics
(IUPAP)(((IUPAP))) et l’International Union of Pure and Applied Chemistry (IUPAC)(((IUPAC))) mit fin à cette
dualité en 1959/60. Physiciens et chimistes convinrent d’attribuer la valeur 12, exactement,
au «&nbsp;poids atomique&nbsp;» de l’isotope 12 du ((carbone)) (((carbone)) 12, ^12^C), ou selon une
formulation plus correcte à la ((masse)) atomique relative stem:[ii(A)_"r"] de l’isotope 12 du ((carbone)).
L’échelle unifiée ainsi obtenue donne les valeurs des masses atomiques et moléculaires
relatives, aussi connues sous le nom de poids atomiques et moléculaires, respectivement.
Cet accord est resté en vigueur jusqu’à la redéfinition du SI en 2018.

La grandeur utilisée par les chimistes pour spécifier la quantité d’éléments ou de composés
chimiques est appelée «&nbsp;quantité de matière&nbsp;». La quantité de matière, symbole stem:[n],
est définie comme étant proportionnelle au nombre d’entités élémentaires stem:[ii(N)] d’un
échantillon, la constante de proportionnalité étant une constante universelle identique pour
toutes les entités. La constante de proportionnalité est l’inverse de la constante d’Avogadro(((constante, d'Avogadro))),
stem:[ii(N)_"A"], de sorte que stem:[n = ii(N)//ii(N)_"A"]. L’unité de ((quantité de matière)) est appelée la _mole_, symbole stem:[rm(mol)].
Suivant les propositions de l’IUPAP, de l’IUPAC(((IUPAC))) et de l’ISO, le CIPM donna une
définition de la mole(((mole (mol)))) en 1967 qu’il confirma en 1969: la ((masse)) molaire
(((masse molaire))) du ((carbone)) 12
devait être exactement stem:[0.012 " "rm(kg)//rm(mol)]. Cela permettait de déterminer directement la quantité
de matière stem:[n_"S"("X")] de tout échantillon pur stem:["S"] d’une entité stem:["X"] à partir de la ((masse)) de
l’échantillon stem:[m_"S"] et de la ((masse)) molaire stem:[ii(M)("X")] de l’entité stem:["X"], la ((masse molaire)) étant
elle-même déterminée à partir de sa ((masse)) atomique relative stem:[ii(A)_"r"] (poids atomique(((poids atomique))) ou
moléculaire(((poids moléculaire))) sans avoir besoin de connaître de façon précise la constante d’Avogadro(((constante, d'Avogadro))),
à l’aide des relations

[stem%unnumbered]
++++
n_"S"("X") = m_"S" // ii(M)("X"), " and " ii(M)(""X"") = ii(A)_"r"("X") " g/mol"
++++

Ainsi, la définition de la mole(((mole (mol)))) dépendait de la définition du kilogramme fondée sur un
artéfact.

La valeur numérique de la constante d’Avogadro(((constante, d'Avogadro))) ainsi définie était égale au nombre
d’atomes dans 12 grammes de ((carbone)) 12. Toutefois, en raison des avancées
technologiques récentes, ce nombre est désormais connu avec une précision telle qu’une
définition plus simple et plus universelle de la mole est devenue possible, à savoir une
définition indiquant exactement le nombre d’entités dans une mole d’une matière quelle
qu’elle soit, ce qui fixe la valeur numérique de la constante d’Avogadro(((constante, d'Avogadro))). Par conséquent,
cette nouvelle définition de la mole et la valeur de la constante d’Avogadro(((constante, d'Avogadro))) ne sont plus
dépendantes de la définition du kilogramme. Par ailleurs, cela souligne la distinction entre
les grandeurs fondamentalement différentes «&nbsp;quantité de matière&nbsp;» et «&nbsp;masse&nbsp;»(((masse))). L’actuelle
définition de la mole(((mole (mol)))) fondée sur une valeur numérique fixée de la constante d’Avogadro(((constante, d'Avogadro))),
stem:[ii(N)_"A"], a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1. [[mole_mol-2]] [[notes_historiques]] [[si_systeme_creation]]


=== Unité d’intensité lumineuse, la candela(((candela (cd))))(((intensité lumineuse)))

Les unités d’intensité lumineuse fondées sur des étalons à flamme ou à filament
incandescent, qui étaient en usage dans différents pays avant 1948, furent d’abord
remplacées par la «&nbsp;bougie nouvelle&nbsp;»(((bougie nouvelle))) fondée sur la luminance du radiateur de Planck
(corps noir) à la température de congélation du platine. Cette modification avait été
préparée dès avant 1937 par la Commission internationale de l’éclairage (CIE) et par le
CIPM; la décision fut prise par le CIPM en 1946. Elle fut ratifiée en 1948 par la CGPM à
sa 9^e^ réunion qui adopta pour cette unité un nouveau nom international, la _candela_,
symbole stem:[rm(cd)]; en 1954, la CGPM à sa 10^e^ réunion établit la candela(((candela (cd)))) comme unité de base;
en 1967, la CGPM à sa 13^e^ réunion (Résolution 5; CR, 104 et _Metrologia_, 1968, *4*, 43-44)
donna une forme modifiée à la définition de 1946.

En 1979, en raison des difficultés expérimentales liées à la réalisation du radiateur de
Planck aux températures élevées et des possibilités nouvelles offertes par la radiométrie,
c’est-à-dire la mesure de la puissance des rayonnements optiques, la 16^e^ CGPM (1979,
Résolution 3; CR, 100 et _Metrologia_, 1980, *16*, 56) adopta une nouvelle définition de la
candela(((candela (cd)))).

L’actuelle définition de la candela(((candela (cd)))), fondée sur une valeur numérique fixée de l’efficacité
lumineuse d’un ((rayonnement monochromatique)) de fréquence stem:[540 xx 10^(12) " "rm(Hz)], stem:[ii(K)_"cd"],
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1. [[quantite_matiere-2]]
