= MEP 2003
:appendix: 2
:partnumber: 1
:edition: 9
:copyright-year: 2019
:language: en
:docnumber: SI MEP M REC 640nm
:title-appendix-en: Recommended Values of Standard Frequencies for Applications Including the Practical Realization of the Metre and Secondary Representations of the Definition of the Second: Iodine (stem:[ii(lambda) ~~ 640" "rm(nm)]) (2003)
:title-appendix-fr:
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:parent-document: si-brochure.adoc
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Iodine (stem:[ii(lambda) ~~ 640" "rm(nm)])

*Absorbing molecule ^127^I~2~, a~9~ component, P(10) 8-5 transition* footnote:[All transitions in I~2~ refer to the stem:["B"^3Pi" "0_u^+ – "X"^1" "Sigma_g^+] system.]

=== CIPM recommended values

[align=left]
The values:: stem:[f = 468218332.4" "rm(MHz)] +
stem:[ii(lambda) = 640283468.7" "rm(fm)]

with a relative standard uncertainty of stem:[4.5 xx 10^(−10)] apply to the radiation of a He-Ne laser stabilized with an internal iodine cell having a cold-finger temperature of stem:[(16 +- 1)" °C"] footnote:[For the specification of operating conditions, such as temperature, modulation width and laser power, the symbols ± refer to a tolerance, not an uncertainty.] and a frequency modulation width, peak-to-peak, of stem:[(6 +- 1)" "rm(MHz)].


=== Source data

[align=left]
Adopted value:: stem:[f = 468218332.4(2)" "rm(MHz)] +
stem:[u_c//y = 4.5 xx 10^(-10)]

[align=left]
for which:: stem:[ii(lambda) = 640283468.7(3)" "rm(fm)] +
stem:[u_c//y = 4.5 xx 10^(-10)]

calculated from::

[%unnumbered]
|===
| stem:[f] / kHz | stem:[u_c//y] | source data
| stem:[468218332419] | stem:[1.0 xx 10^(−10)] | <<sec2-1>>
| stem:[468218332310] | stem:[1.2 xx 10^(−10)] | <<sec2-2>>
| stem:[468218332069] | stem:[4.6 xx 10^(−10)] | <<sec2-3>>
3+a| Weighted mean:: stem:[f = 468218332366" "rm(kHz)]
|===

Given the small number of determinations, the CCL considered it prudent to assume a relative standard uncertainty of stem:[4.5 xx 10^(−10)].

Source data

[[sec2-1]]
==== {blank}

Bennet and Mills-Baker <<bennett1984>> give:: stem:[ii(lambda)_(a9) = 640.2834686" "rm(nm)].

From this paper the ratio stem:[f_(a9) // f_i] is calculated as

[align=left]
stem:[f_(a9) // f_i = 0.988611184191] +
stem:[u_c//y = 1 xx 10^(−10)].

Using the recommended value of the absorbing molecule ^127^I~2~, a~16~ or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633" "rm(nm)] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_i = 473612214712" "rm(kHz)] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a9) = 468218332434" "rm(kHz)] +
stem:[u_c//y = 1.0 xx 10^(−10)]

at a cold-finger temperature of 14.3 °C (iodine pressure = 16 Pa) and a modulation width of 7 MHz. For a reference temperature of 16 °C (iodine pressure = 18.9 Pa) and a modulation width of 6 MHz, corrections of –23 kHz and +8 kHz has to be applied to this value assuming a pressure dependence of –7.8 kHz/Pa and a modulation dependence of –7.6 kHz/MHz, similar to that reported in <<zhao2>>, giving

[align=left]
stem:[f_(a9) = 468218332419" "rm(kHz)] +
stem:[u_c//y = 1.0 xx 10^(−10)].

[[sec2-2]]
==== {blank}

[align=left]
Zhao et al. <<zhao2>>, <<ccdm92-10a>> give:: stem:[ii(lambda)_(a9) = 640.2834688" "rm(nm)] +
stem:[3 xx (u_c8//y ) = 1.1 xx 10^(−9)].

[align=left]
Bönsch <<bonsch>> gives:: stem:[ii(lambda)_i//lambda_(a9) = 0.9886111838] +
stem:[u_c//y = 12 xx 10^(−11)].

Using the recommended value of the absorbing molecule ^127^I~2~, a~16~ or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633" "rm(nm)] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_i = 473612214712" "rm(kHz)] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a9) = 468218332277" "rm(kHz)] +
stem:[u_c//y = 1.2 xx 10^(−10)]

at a cold-finger temperature of 18 °C (iodine pressure = 22.6 Pa) and a modulation width of 6.5 MHz. For a reference temperature of 16 °C (iodine pressure = 18.9 Pa) and a modulation width of 6 MHz, corrections of +29 kHz and +4 kHz have to be applied to this value knowing a pressure dependence of –7.8 kHz/Pa and a modulation dependence of –7.6 kHz/MHz, giving

[align=left]
stem:[f_(a9) = 468218332310" "rm(kHz)] +
stem:[u_c//y = 1.2 xx 10^(−10)].

[[sec2-3]]
==== {blank}

[align=left]
Reference <<ccdm92-20a>>, <<ccgm92-6a>> give:: stem:[ii(lambda)_(a9)(17 °C) // lambda_e (20 °C) = 1.01152034104] +
stem:[u_c//y = 4.6 xx 10^(−10)].

Using the recommended value of the absorbing molecule ^127^I~2~, a~16~ or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633" "rm(nm)] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_e = 473612366967" "rm(kHz)] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a9) = 468218332055" "rm(kHz)] +
stem:[u_c//y = 4.6 xx 10^(−10)]

at a cold-finger temperature of 17 °C (iodine pressure = 20.7 Pa). For a reference temperature of 16 °C (iodine pressure = 18.9 Pa), a correction of +14 kHz has to be applied to this value, assuming a pressure dependence of –7.8 kHz/Pa similar to that reported in <<zhao2>>, giving

[align=left]
stem:[f_(a9) = 468218332069" "rm(kHz)] +
stem:[u_c//y = 4.6 xx 10^(−10)].

=== Absolute frequency of the other transitions related to those adopted as recommended and frequency intervals between transitions and hyperfine components

These tables replace those published in BIPM Com. Cons. Long., 2001, *10*, 188 and _Metrologia_ , 2003, *40*, 128.

The notation for the transitions and the components is that used in the source references. The values adopted for the frequency intervals are the weighted means of the values given in the references.

For the uncertainties, account has been taken of:

* the uncertainties given by the authors;
* the spread in the different determinations of a single component;
* the effect of any perturbing components;
* the difference between the calculated and the measured values.

In the tables, uc represents the estimated combined standard uncertainty (stem:[1 ii(sigma)] ).

All transitions in molecular iodine refer to the B-X system.


[[table1]]
|===
6+^.^| stem:[ii(lambda) ~~ 640" "rm(nm)] ^127^I~2~ P(10) 8-5
| stem:[a_n] | stem:[[f (a_n) – f (a_9)\]//rm(MHz)] | stem:[u_c//rm(MHz)] | stem:[a_n] | stem:[[f (a_n) – f (a_9)\]//rm(MHz)] | stem:[u_c//rm(MHz)]

| stem:[a_1] | –495.4 | 0.4 | stem:[a_9] | 0 | -
| stem:[a_2] | –241.5 | 0.7 | stem:[a_(10)] | 77.84 | 0.03
| stem:[a_3] | –233.0 | 0.4 | stem:[a_(11)] | 186.22 | 0.07
| stem:[a_4] | –177.8 | 1.3 | stem:[a_(12)] | 199.51 | 0.07
| stem:[a_5] | –175.2 | 0.6 | stem:[a_(13)] | 256.6 | 0.2
| stem:[a_6] | –130.8 | 0.1 | stem:[a_(14)] | 272.75 | 0.07
| stem:[a_7] | –82.45 | 0.03 | stem:[a_(15)] | 374.0 | 0.2
| stem:[a_8] | –61.85 | 0.14 | | |
6+a| Frequency referenced to::
stem:[a_9], P(10) 8-5, ^127^I~2~: stem:[f = 468218332.4" "rm(MHz)] <<ci2002>>
|===
Ref. <<glaser1987>>, <<bertinetto>>, <<bennett1978>>, <<kegung>>, <<zhao1983>>, <<zhao1985>>, <<glaser1985>>, <<zhao1987>>


[[table2]]
|===
3+^.^| stem:[ii(lambda) ~~ 640" "rm(nm)] ^127^I~2~ R(16) 8-5
| stem:[b_n] | stem:[[f (b_n) – f (a_9)\]//rm(MHz)] | stem:[u_c//rm(MHz)]

| stem:[b_1] | 62.834 | 0.01
| stem:[b_2] | 329.8 | 0.2
| stem:[b_3] | 335.99 | 0.02
3+a| Frequency referenced to:: stem:[a_9], P(10) 8-5, ^127^I~2~: stem:[f = 468218332.4" "rm(MHz)] <<ci2002>>
|===
Ref. <<glaser1987>>, <<bertinetto>>, <<bennett1978>>, <<kegung>>, <<zhao1983>>, <<zhao1985>>, <<glaser1985>>, <<zhao1987>>


[bibliography]
=== References

* [[[bennett1984,1]]], Bennett S. J., Mills-Baker P., Iodine Stabilized 640 nm Helium-Neon laser, _Opt. Commun._,1984, *51*, 322-324.

* [[[zhao2,2]]], Zhao K. G., Blabla J., Helmcke J., ^127^I~2~-Stabilized ^3^He-^22^Ne Laser at 640 nm Wavelength, _IEEE Trans. Instrum. Meas._, 1985, *IM-34*, 252-256.

* [[[ccdm92-10a,3]]], CCDM/92-10a, NIM, Research findings in realizing the definition of the metre measurement/intercomparison of frequency (wavelength) and geometrical standard of length.

* [[[bonsch,4]]], Bönsch G., Simultaneous Wavelength Comparison of Iodine-Stabilized Lasers at 515 nm, 633 nm, and 640 nm, _IEEE Trans. Instrum. Meas._, 1985, *IM-34*, 248-251.

* [[[ccdm92-20a,5]]], CCDM/92-20a, BIPM, Reply to the Questionnaire for the CCDM.

* [[[ccgm92-6a,6]]], CCDM/92-6a, IMGC, Reply to questionnaire CCDM/92-1, 5 June 1992.

* [[[ci2002,7]]], Recommendation CCL3 (_BIPM Com. Cons. Long._, 10th Meeting, 2001) adopted by the Comité International des Poids et Mesures at its 91th Meeting as Recommendation 1 (CI-2002).

* [[[glaser1987,8]]], Gläser M., Hyperfine Components of Iodine for Optical Frequency Standards _PTB-Bericht_, 1987, *PTB-Opt-25*.

* [[[bertinetto,9]]], Bertinetto F., Cordiale P., Fontana S., Picotto G. B., Recent Progresses in He-Ne Lasers Stabilized to ^127^I~2~, _IEEE Trans. Instrum. Meas._, 1985, *IM-34*, 256-261.

* [[[bennett1978,10]]], Bennett S. J., Cérez P., Hyperfine Structure in Iodine at the 612-nm and 640-nm Helium-Neon Laser Wavelengths, _Opt. Commun._, 1978, *25*, 343-347.

* [[[kegung,11]]], Kegung D., Xu J., Li C.-Y., Liu H.-T., Hyperfine Structure in Iodine Observed at the 612 nm and 640 nm ^3^He-^22^Ne Laser Wavelengths, _Acta Metrologica Sinica_, 1982, *3*, 322-323.

* [[[zhao1983,12]]], Zhao K., Li H., Hyperfine structure of iodine at 640 nm ^3^He-^22^Ne laser wavelength and identification, _Acta Metrologica Sinica_, 1983, *3*, 673-677.

* [[[zhao1985,13]]], Zhao K.-G., Li H., Analysis and Calculation of Hyperfine Lines of Iodine Molecule, _Acta Metrologica Sinica_, 1985, *6*, 83-88.0-2c.

* [[[glaser1985,14]]], Gläser M., Identification of Hyperfine Structure Components of the Iodine Molecule at 640 nm Wavelength, _Opt. Commun._, 1985, *54*, 335-342.

* [[[zhao1987,15]]], Zhao K.-G., Li C.-Y., Li H., Xu J., Way H., Investigations of ^127^I~2~-Stabilized He - Ne Laser at 640 nm, _Acta Metrologica Sinica_, 1987, *8*, 88-95.
