= MEP 2003
:appendix: 2
:partnumber: 1
:edition: 9
:copyright-year: 2019
:language: en
:docnumber: 
:title-en: 
:title-fr: 
:doctype: guide
:parent-document: si-brochure.adoc
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Krypton spectral lamp (stem:[lambda ~~ 606" nm"])

*^86^Kr spectral lamp radiation, 5d~5~ – 2p~10~ transition*

=== CIPM recommended value

[align=left]
The value stem:[lambda = 605" "780" "210.3" fm"] +
with a relative expanded uncertainty stem:[U = 3.9 xx 10^(−9)], where stem:[U = ku_c (k = 3)], stem:[u_c] being the combined standard uncertainty, applies to the radiation emitted by a discharge lamp. The radiation of 86Kr is obtained by means of a hot-cathode discharge lamp containing ^86^Kr, of a purity not less than 99 %, in sufficient quantity to assure the presence of solid krypton at a temperature of 64 K, this lamp having a capillary with an inner diameter from 2 mm to 4 mm and a wall thickness of about 1 mm.

It is estimated that the wavelength of the radiation emitted by the positive column is equal, to within 1 part in 108, to the wavelength corresponding to the transition between the unperturbed levels, when the following conditions are satisfied:

* the capillary is observed end-on from the side closest to the anode;
* the lower part of the lamp, including the capillary, is immersed in a cold bath maintained at a temperature within one degree of the triple point of nitrogen;
* the current density in the capillary is (stem:[0.3 +- 0.1)" A" * " cm"^(−2)].

=== Source data

[align=left]
Adopted value:: stem:[f = 494" "886" "516.4" (6) MHz"] +
stem:[u_c//y = 1.3 xx 10^(-9)]

[align=left]
for which:: stem:[lambda = 605" "780" "210.30" (.8) fm"] +
stem:[u_c//y = 1.3 xx 10^(-9)]

calculated from::

[%unnumbered]
|===
| stem:[f // "kHz"] | stem:[u_c//y] | source data
| 494 886 516 422 kHz | stem:[1.3 xx 10^(−9)] | <<sec2-1>>
|===


Source data

[[sec2-1]]
==== {blank}

The CCDM 1982 <<docs-metre>>, <<bipm-metre>> gives

[align=left]
stem:[f_(Kr) // f_i = 1.044" "919" "242" "05] +
stem:[u_c//y = 1.3 xx 10^(−9)], +
using the recommended operation conditions <<bipmx2>>.

Using the recommended value of the absorbing molecule ^127^I~2~, a~16~ or f component, R(127) 11-5 transition (see iodine at stem:[lambda ~~ 633 " nm"] and frequency differences listed in corresponding Table 1) one obtains

[align=left]
stem:[f_i = 473" "612" "214" "712" kHz"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

[align=left]
which leads to

[align=left]
stem:[f_(Kr) = 494" "886" "516" "422" kHz"] +
stem:[u_c//y = 1.3 xx 10^(−9)].


[bibliography]
=== References

* [[[docs-metre,1]]], Documents Concerning the New Definition of the Metre, _Metrologia_, 1984, *19*, 163-178.

* [[[bipm-metre,2]]], _BIPM, Com. Cons. Déf. Mètre_, 1982, *7*, M58..

* [[[bipmx2,3]]], _BIPM Proc. Verb. Com. Int. Poids et Mesures_, 1960, *28*, 71-72 and _BIPM Comptes Rendus 11^e^ Conf. Gén. Poids et Mesures_, 1960, *85*.