= Recommended Values of Standard Frequencies: Iodine (stem:[ii(lambda) ~~ 612 "unitsml(nm)"])
:appendix-id: 2
:partnumber: 2.14
:edition: 9
:copyright-year: 2003
:language: en
:docnumber: SI MEP M REC 612nm
:title-appendix-en: Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second
:title-appendix-fr: Valeurs recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre et aux représentations secondaires de la seconde
:title-part-en: Iodine (stem:[ii(lambda) ~~ 612 "unitsml(nm)"])
:title-part-fr: Iodine (stem:[ii(lambda) ~~ 612 "unitsml(nm)"])
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Iodine (stem:[ii(lambda) ~~ 612 "unitsml(nm)"])

*Absorbing molecule ^127^I~2~, stem:["a"_7] component, R(47) 9-2 transition* footnote:[All transitions in I~2~ refer to the stem:["B"^3Pi" "0_u^+ - "X"^1" "Sigma_g^+] system.]

== CIPM recommended values

The values:: stem:[f = 489880354.9 "unitsml(MHz)"] +
stem:[ii(lambda) = 611970770.0 "unitsml(fm)"]

with a relative standard uncertainty of stem:[3 xx 10^(−10)] apply to the radiation of a He-Ne laser stabilized with an iodine cell, within or external to the laser, having a cold-finger temperature of stem:[(-5 +- 2) "unitsml(degC)"] footnote:[For the specification of operating conditions, such as temperature, modulation width and laser power, the symbols stem:[pm] refer to a tolerance, not an uncertainty.].

== Source data

Adopted value:: stem:[f = 489880354.93(15) "unitsml(MHz)"] +
stem:[u_c//y = 3.0 xx 10^(-10)] +
+
for which: +
stem:[ii(lambda) = 611970769.97(18) "unitsml(fm)"] +
stem:[u_c//y = 3.0 xx 10^(-10)]

calculated from

[%unnumbered]
|===
h| stem:[f // "unitsml(kHz)"] h| stem:[u_c//y] h| source data

| stem:[489880354979] | stem:[1 xx 10^(−10)] | <<sec2-1>>
| stem:[489880354728] | stem:[2.1 xx 10^(−10)] | <<sec2-2>>
| stem:[489880355026] | stem:[8.3 xx 10^(−11)] | <<sec2-3>>
| stem:[489880355062] | stem:[3.0 xx 10^(−10)] | <<sec2-4>>
| stem:[489880358850] | stem:[8.5 xx 10^(−11)] | <<sec2-5>>
| Unweighted mean: 2+| stem:[f = 489880354929 "unitsml(kHz)"]
|===

Other available values having relative uncertainties higher than stem:[3.0 xx 10^(−10)] have not been used. The relative standard uncertainty calculated from the dispersion of the six values is stem:[2.8 xx 10^(−10)], which the CCL preferred to round up to stem:[3.0 xx 10^(-10)].

Source data

[[sec2-1]]
=== {blank}

Reference <<ccdm82-34>> gives:: stem:[f_(a7) // f_i = 1.03434907243] +
stem:[u_c//y = 1 xx 10^(−10)].

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_i = 473612214712 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a7) = 489880354979 "unitsml(kHz)"] +
stem:[u_c//y = 1 xx 10^(−10)].

[[sec2-2]]
=== {blank}

Reference <<ccdm82-19a>> gives:: stem:[f_(a7) // f_i = 1.03434907190] +
stem:[u_c//y = 2.1 xx 10^(−10)].

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or stem:[f] component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_i = 473612214712 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a7) = 489880354728 "unitsml(kHz)"] +
stem:[u_c//y = 2.1 xx 10^(−10)].

[[sec2-3]]
=== {blank}

Bönsch et al. <<bonsch>> give:: stem:[ii(lambda)_(b15)//ii(lambda)_i = 0.96679192143] +
stem:[u_c//y = 8 xx 10^(−11)].

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or stem:[f] component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_i = 473612214712 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(b15) = 489880194708 "unitsml(kHz)"] +
stem:[u_c//y = 8.3 xx 10^(−11)].

[align=left]
From the measured value (see <<table4>> below) +
stem:[f_(b15) - f_(a7) = -160318 "unitsml(kHz)"] +
stem:[u_c = 3 "unitsml(kHz)"]

one calculates

[align=left]
stem:[f_(a7) = 489880355026 "unitsml(kHz)"] +
stem:[u_c//y = 8.3 xx 10^(−11)].

[[sec2-4]]
=== {blank}

Vitushkin et al. <<vitushkin>> give:: stem:[ii(lambda)_d // lambda_(a7) = 1.034348712] +
stem:[u_c//y = 3 xx 10^(−10)].

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_d = 473612379828 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a7) = 489880355062 "unitsml(kHz)"] +
stem:[u_c//y = 3.0 xx 10^(−10)].

[[sec2-5]]
=== {blank}

Himbert et al. <<himbert>> give:: stem:[f_(a13) = 489880604541 "unitsml(kHz)"] +
stem:[u_c = 88 "unitsml(kHz)"].

This value is a result of the frequency ratio stem:[f_(a13)//f_e], to which the recommended value adopted by the CIPM in 1983 <<bipm1983>>, <<docs-metre>> was applied, i.e. stem:[f_i = 473612214.8 "unitsml(MHz)"]. (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>)

[align=left]
stem:[f_e - f_i = 152255 "unitsml(kHz)"] +
stem:[u_c = 5 "unitsml(kHz)"],

one obtains

stem:[f_e = 473612367055 "unitsml(kHz)"],

and hence

[align=left]
stem:[f_(a13) // f_e = 1.034349267] +
stem:[u_c//y = 8 xx 10^(−11)].

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding <<table1>>) one obtains

[align=left]
stem:[f_e = 473612366967 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

one calculates

[align=left]
stem:[f_(a13) = 489880604450] +
stem:[u_c//y = 8.3 xx 10^(−11)].

[align=left]
Knowing the frequency difference (see <<table1>>) +
stem:[f_(a7) - f_(a13) = -249600 "unitsml(kHz)"] +
stem:[u_c = 10 "unitsml(kHz)"],

one obtains

[align=left]
stem:[f_(a7) = 489880354850] +
stem:[u_c//y = 8.5 xx 10^(−11)].


== Absolute frequency of the other transitions related to those adopted as recommended and frequency intervals between transitions and hyperfine components

These tables replace those published in BIPM Com. Cons. Long., 2001, *10*, 184-187 and _Metrologia_, 2003, *40*, 127-128.

The notation for the transitions and the components is that used in the source references. The values adopted for the frequency intervals are the weighted means of the values given in the references.

For the uncertainties, account has been taken of:

* the uncertainties given by the authors;
* the spread in the different determinations of a single component;
* the effect of any perturbing components;
* the difference between the calculated and the measured values.

In the tables, stem:[u_c] represents the estimated combined standard uncertainty (stem:[1 ii(sigma)] ).

All transitions in molecular iodine refer to the B-X system.

[[table1]]
|===
8+^.^h| stem:[ii(lambda) ~~ 612 "unitsml(nm)"] ^127^I~2~ R(47) 9-2
h| stem:["a"_n] h| stem:[x] h| [stem:[f ("a"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"] h| stem:["a"_n] h| stem:[x] h| [stem:[f ("a"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"]

| stem:["a"_1] | u | stem:[-357.16] | stem:[0.02] | stem:["a"_{12}] | j | stem:[219.602] | 0.006
| stem:["a"_2] | t | stem:[-333.97] | stem:[0.01] | stem:["a"_{13}] | i | stem:[249.60] | 0.01
| stem:["a"_3] | s | stem:[-312.46] | stem:[0.02] | stem:["a"_{14}] | h | stem:[284.30] | 0.01
| stem:["a"_4] | r | stem:[-86.168] | stem:[0.007] | stem:["a"_{15}] | g | stem:[358.37] | 0.03
| stem:["a"_5] | q | stem:[-47.274] | stem:[0.004] | stem:["a"_{16}] | f | stem:[384.66] | 0.01
| stem:["a"_6] | p | stem:[-36.773] | stem:[0.003] | stem:["a"_{17}] | e | stem:[403.76] | 0.02
| stem:["a"_7] | o | stem:[0] | -- | stem:["a"_{18}] | d | stem:[429.99] | 0.02
| stem:["a"_8] | n | stem:[81.452] | 0.003 | stem:["a"_{19}] | c | stem:[527.16] | 0.02
| stem:["a"_9] | m | stem:[99.103] | 0.003 | stem:["a"_{20}] | b | stem:[539.22] | 0.02
| stem:["a"_{10}] | l | stem:[107.463] | 0.005 | stem:["a"_{21}] | a | stem:[555.09] | 0.02
| stem:["a"_{11}] | k | stem:[119.045] | 0.006 | | | |
8+<a| Frequency referenced to:: stem:["a"_7], R(47) 9-2, ^127^I~2~: stem:[f = 489880354.9 "unitsml(MHz)"] <<ci2002>>
|===
Ref. <<glaser-ptb>>, <<razet>>, <<cerez>>, <<glaser-im>>, <<bertinetto1985>>, <<robertsson>>


[[table2]]
|===
6+^.^h| stem:[ii(lambda) ~~ 612 "unitsml(nm)"] ^127^I~2~ P(48) 11-3
h| stem:["b"_n] h| [stem:[f ("b"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"] h| stem:["b"_n] h| [stem:[f ("b"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"]

| stem:["b"_1] | stem:[-1034.75] | stem:[0.07] | stem:["b"_9] | stem:[-579.91] | 0.01
| stem:["b"_2] | stem:[-755.86] | stem:[0.05] | stem:["b"_{10}] | stem:[-452.163] | 0.005
| stem:["b"_3] | stem:[-748.28] | stem:[0.03] | stem:["b"_{11}] | stem:[-316.6] | 0.4
| stem:["b"_4] | stem:[-738.35] | stem:[0.04] | stem:["b"_{12}] | stem:[-315.8] | 0.4
| stem:["b"_5] | stem:[-731.396] | stem:[0.006] | stem:["b"_{13}] | stem:[-297.42] | 0.03
| stem:["b"_6] | stem:[-616.01] | stem:[0.03] | stem:["b"_{14}] | stem:[-294.72] | 0.03
| stem:["b"_7] | stem:[-602.42] | stem:[0.03] | stem:["b"_{15}] | stem:[-160.318] | 0.003
| stem:["b"_8] | stem:[-593.98] | stem:[0.01] | | |
6+<a| Frequency referenced to:: stem:["a"_7], R(47) 9-2, ^127^I~2~: stem:[f = 489880354.9 "unitsml(MHz)"] <<ci2002>>
|===
Ref. <<glaser-ptb>>, <<razet>>, <<glaser-im>>, <<bertinetto1985>>, <<robertsson>>, <<bertinetto1983>>


[[table3]]
|===
6+^.^h| stem:[ii(lambda) ~~ 612 "unitsml(nm)"] ^127^I~2~ R(48) 15-5
h| stem:["c"_n] h| [stem:[f ("c"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"] h| stem:["c"_n] h| [stem:[f ("c"_n) - f ("a"_7)]]/stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"]

| stem:["c"_1] | stem:[-513.83] | stem:[0.03] | stem:["c"_5] | stem:[-209.96] | 0.03
| stem:["c"_2] | stem:[-237.40] | stem:[0.03] | stem:["c"_6] | stem:[-97.74] | 0.03
| stem:["c"_3] | stem:[-228.08] | stem:[0.03] | stem:["c"_8] | stem:[-73.92] | 0.03
| stem:["c"_4] | stem:[-218.78] | stem:[0.03] | stem:["c"_9] | stem:[-59.30] | 0.03
6+<a| Frequency referenced to:: stem:["a"_7], R(47) 9-2, ^127^I~2~: stem:[f = 489880354.9 "unitsml(MHz)"] <<ci2002>>
|===
Ref. <<razet>>


[[table4]]
[cols="8*^"]
|===
8+^.^h| stem:[ii(lambda) ~~ 612 "unitsml(nm)"] ^129^I~2~ P(110) 10-2
h| stem:["a"_n] h| stem:[x] h| stem:[[f ("a"_n) - f (a7{""^(127)ii(I)_2})\]] / stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"] h| stem:["a"_n] h| stem:[x] h| stem:[[f ("a"_n) - f ("a"_7{^(127)ii(I)_2})\]] / stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"]

| stem:["a"_1] | b' | stem:[-376.29] | stem:[0.05] | stem:["a"_{15}] | n | stem:[1.61] | 0.20
| stem:["a"_2] | a' | stem:[-244.76] | stem:[0.10] | stem:["a"_{16}] | m | stem:[10.63] | 0.15
| stem:["a"_3] | z | stem:[-230.79] | stem:[0.20] | stem:["a"_{17}] | l | stem:[15.82] | 0.20
| stem:["a"_4] | y | stem:[-229.40] | stem:[0.20] | stem:["a"_{18}] | k | stem:[25.32] | 0.10
| stem:["a"_5] | x | stem:[-216.10] | stem:[0.05] | stem:["a"_{19}] | j | stem:[49.44] | 0.15
| stem:["a"_6] | w | stem:[-149.37] | stem:[0.10] | stem:["a"_{20}] | i | stem:[54.66] | 0.20
| stem:["a"_7] | v | stem:[-134.68] | stem:[0.10] | stem:["a"_{21}] | h | stem:[69.02] | 0.10
| stem:["a"_8] | u | stem:[-130.98] | stem:[0.10] | stem:["a"_{22}] | g | stem:[74.47] | 0.15
| stem:["a"_9] | t | stem:[-116.67] | stem:[0.05] | stem:["a"_{23}] | f | stem:[110.60] | 0.10
| stem:["a"_{10}] | s | stem:[-96.26] | stem:[0.20] | stem:["a"_{24}] | e | stem:[153.09] | 0.20
| stem:["a"_{11}] | r | stem:[-90.70] | stem:[0.20] | stem:["a"_{25}] | d | stem:[154.70] | 0.20
| stem:["a"_{12}] | q | stem:[-84.12] | stem:[0.20] | stem:["a"_{26}] | c | stem:[163.98] | 0.20
| stem:["a"_{13}] | p | stem:[-77.79] | stem:[0.20] | stem:["a"_{27}] | b | stem:[166.22] | 0.20
| stem:["a"_{14}] | o | stem:[-72.70] | stem:[0.20] | stem:["a"_{28}] | a | stem:[208.29] | 0.10
8+<a| Frequency referenced to:: stem:["a"_7], R(47) 9-2, ^127^I~2~: stem:[f = 489880354.9 "unitsml(MHz)"] <<ci2002>>
|===
Ref. <<kegung>>, <<ciddor>>, <<glaser1981>>


[[table5]]
[cols="8*^"]
|===
8+^.^h| stem:[ii(lambda) ~~ 612 "unitsml(nm)"] ^129^I~2~ R(113) 14-4
h| stem:["b"_n] h| stem:[x] h| stem:[[f ("b"_n) - f (a7{""^(127)ii(I)_2})\]] / stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"] h| stem:["b"_n] h| stem:[x] h| stem:[[f ("b"_n) - f ("a"_7{^(127)ii(I)_2})\]] / stem:["unitsml(MHz)"] h| stem:[u_c//"unitsml(MHz)"]

| stem:["b"_{19}] | r | stem:[-410.4] | stem:[0.3] | stem:["b"_{28}] | i | stem:[-289.4] | 0.5
| stem:["b"_{20}] | q | stem:[-390.0] | stem:[0.3] | stem:["b"_{29}] | h | stem:[-273.1] | 0.3
| stem:["b"_{21}] | p | stem:[-383.9] | stem:[0.5] | stem:["b"_{30}] | g | stem:[-255.7] | 0.5
| stem:["b"_{22}] | o | stem:[-362.8] | stem:[0.3] | stem:["b"_{31}] | f | stem:[-247] | 5
| stem:["b"_{23}] | n | stem:[-352.9] | stem:[0.3] | stem:["b"_{32}] | e | stem:[-237] | 5
| stem:["b"_{24}] | m | stem:[-346.4] | stem:[0.3] | stem:["b"_{33}] | d | stem:[-223] | 5
| stem:["b"_{25}] | l | stem:[-330.0] | stem:[0.3] | stem:["b"_{34}] | c | stem:[-198.6] | 0.3
| stem:["b"_{26}] | k | stem:[-324.9] | stem:[0.3] | stem:["b"_{35}] | b | stem:[-193.1] | 0.3
| stem:["b"_{27}] | j | stem:[-304.7] | stem:[0.3] | stem:["b"_{36}] | a | stem:[-187.0] | 0.3
8+<a| Frequency referenced to:: stem:["a"_7], R(47) 9-2, ^127^I~2~: stem:[f = 489880354.9 "unitsml(MHz)"] <<ci2002>>
|===
Ref. <<ciddor>>, <<glaser1981>>


[bibliography]
== References

* [[[ccdm82-34,1]]], CCDM/82-34, NPL, Laser wavelength Measurements, May 1982.

* [[[ccdm82-19a,2]]], CCDM/82-19a, BIPM, Réponse au questionnaire CCDM/82-3.

* [[[bonsch,3]]], Bönsch G., Gläser M., Spieweck F., Bestimmung der Wellenlängenverhältnisse von drei ^127^I~2~-stabilisierten Lasern bei stem:[515 "unitsml(nm)"], stem:[612 "unitsml(nm)"] und stem:[633 "unitsml(nm)"], _PTB Jahresbericht_, 1986, 161.

* [[[vitushkin,4]]], Vitushkin L. F., Zakharenko Yu. G., Yvanov I. V., Leibengardt G. I., Shur V. L., Measurements of Wavelength of High-Stabilized He-Ne/I~2~ Laser at stem:[612 "unitsml(nm)"], _Opt. Spectr._, 1990, *68*, 705-707.

* [[[himbert,5]]], Himbert M., Bouchareine P., Hachour A., Juncar P., Millerioux Y., Razet A., Measurements of Optical Wavelength Ratios Using a Compensated Field Sigmameter, _IEEE Trans. Instrum. Meas._, 1991, *40*, 200-203.

* [[[bipm1983,6]]], _BIPM, Proc. Verb. Com. Int. Poids et Mesures_, 1983, *51*.

* [[[docs-metre,7]]], Documents Concerning the New Definition of the Metre, _Metrologia_, 1984, *19*, 163-178.

* [[[ci2002,8]]], Recommendation CCL3 (_BIPM Com. Cons. Long._, 10th Meeting, 2001) adopted by the Comité International des Poids et Mesures at its 91th Meeting as Recommendation 1 (CI-2002).

* [[[glaser-ptb,9]]], Gläser M., Hyperfine Components of Iodine for Optical Frequency Standards _PTB-Bericht_, 1987, *PTB-Opt-25*.

* [[[razet,10]]], Razet A., Millerioux Y., Juncar P., Hyperfine Structure of the 47R(9-2), 48P(11-3) and 48R(15-5) Lines of ^127^I~2~ at stem:[612 "unitsml(nm)"] as Secondary Standards of Optical Frequency, _Metrologia_, 1991, *28*, 309-316.

* [[[cerez,11]]], Cérez P., Bennett S. J., Helium-neon laser stabilized by saturated absorption in iodine at stem:[612 "unitsml(nm)"], _Appl. Opt._,1979, *18*, 1079-1083.

* [[[glaser-im,12]]], Gläser M., Properties of a He-Ne Laser at stem:[ii(lambda) ~~ 612 "unitsml(nm)"], Stabilized by Means of an External Iodine Absorption Cell, _IEEE Trans. Instrum. Meas._, 1987, *IM-36*, 604-608.

* [[[bertinetto1985,13]]], Bertinetto F., Cordiale P., Fontana S., Picotto G. B., Recent Progresses in He-Ne Lasers Stabilized to ^127^I~2~, _IEEE Trans. Instrum. Meas._, 1985, *IM-34*, 256-261.

* [[[robertsson,14]]], Robertsson L., Iodine-stabilized He-Ne lasers at stem:[ii(lambda) = 612 "unitsml(nm)"] using internal and external cells, _BIPM Proc.-Verb. Com. Int. Poids et Mesures_, 1992, *60*, 160-162.

* [[[bertinetto1983,15]]], Bertinetto F., Cordiale P., Picotto G. B., Chartier J.-M., Felder R., Gläser M., Comparison Between the ^127^I~2~ Stabilized He-Ne Lasers at stem:[633 "unitsml(nm)"] and at stem:[612 "unitsml(nm)"] of the BIPM and the IMGC, _IEEE Trans. Instrum. Meas._, 1983, *IM-32*, 72-76.

* [[[kegung,16]]], Kegung D., Gläser M., Helmcke J., I~2~ Stabilized He-Ne Lasers at stem:[612 "unitsml(nm)"], _IEEE Trans. Instrum. Meas._, 1980, *IM-29*, 354-357.

* [[[ciddor,17]]], Ciddor P. E., Brown N., Hyperfine Spectra in Iodine-129 at stem:[612 "unitsml(nm)"], _Opt. Commun._, 1980, *34*, 53-56.

* [[[glaser1981,18]]], Gläser M., Kegung D., Foth H. J., Hyperfine Structure and Fluorescence Analysis of Enriched ^129^I~2~ at the stem:[612 "unitsml(nm)"] Wavelength of the He-Ne Laser, _Opt. Commun._, 1981, *38*, 119-123.
