= Recommended Values of Standard Frequencies: Spectral lamp radiations
:appendix-id: 2
:partnumber: 2.28
:edition: 9
:copyright-year: 2003
:language: en
:docnumber: SI MEP M REC Spectral
:title-appendix-en: Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second
:title-appendix-fr: Valeurs recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre et aux représentations secondaires de la seconde
:title-part-en: Spectral lamp radiations
:title-part-fr: Rayonnements spectraux de la lampe
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Spectral lamp radiations

*^86^Kr, ^198^Hg, ^114^Cd, spectral lamp radiations*

== CIPM recommended values

Vacuum wavelengths, stem:[ii(lambda)], for ^86^Kr, ^198^Hg and ^114^Cd transitions

[cols="^,^,^"]
[%unnumbered]
|===
| Atom | Transition | stem:[ii(lambda) // "pm"]
| ^86^Kr | stem:[rm(2p_9 - 5d'_4)] | stem:[645807.20]
| ^86^Kr | stem:[rm(2p_8 - 5d_4)] | stem:[642280.06]
| ^86^Kr | stem:[rm(1s_3 - 3p_10)] | stem:[565112.86]
| ^86^Kr | stem:[rm(1s_4 - 3p_8)] | stem:[450361.62]
| ^198^Hg | stem:[rm(6^1 P_1 - 6^1 D_2)] | stem:[579226.83]
| ^198^Hg | stem:[rm(6^1 P_1 - 6^3 D_2)] | stem:[577119.83]
| ^198^Hg | stem:[rm(6^3 P_2 - 7^3 S_1)] | stem:[546227.05]
| ^198^Hg | stem:[rm(6^3 P_1 - 7^3 S_1)] | stem:[435956.24]
| ^114^Cd | stem:[rm(5^1 P_1 - 5^1 D_2)] | stem:[644024.80]
| ^114^Cd | stem:[rm(5^3 P_2 - 6^3 S_1)] | stem:[508723.79]
| ^114^Cd | stem:[rm(5^3 P_1 - 6^3 S_1)] | stem:[480125.21]
| ^114^Cd | stem:[rm(5^3 P_0 - 6^3 S_1)] | stem:[467945.81]
|===

For ^86^Kr, the above values with a relative expanded uncertainty stem:[ii(U) = 2 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a hot-cathode discharge lamp containing ^86^Kr, of a purity not less than 99 %, in sufficient quantity to assure the presence of solid krypton at a temperature of stem:[64 "unitsml(K)"], this lamp having a capillary with an inner diameter from stem:[2 "unitsml(mm)"] to stem:[4 "unitsml(mm)"] and a wall thickness of about stem:[1 "unitsml(mm)"].

It is estimated that the wavelength of the radiation emitted by the positive column is equal, to within 1 part in stem:[10^8], to the wavelength corresponding to the transition between the unperturbed levels, when the following conditions are satisfied:

* the capillary is observed end-on from the side closest to the anode;
* the lower part of the lamp, including the capillary, is immersed in a cold bath maintained at a temperature within one degree of the triple point of nitrogen;
* the current density in the capillary is stem:[(0.3 +- 0.1) "unitsml(A*cm^(-2))"].

For ^198^Hg, the above values with a relative expanded uncertainty stem:[ii(U) = 5 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a discharge lamp when the following conditions are met:

* the radiations are produced using a discharge lamp without electrodes containing ^198^Hg, of a purity not less than 98 %, and argon at a pressure from stem:[0.5 "unitsml(mm)"] Hg to stem:[1.0 "unitsml(mm)"] Hg (stem:[66 "unitsml(Pa)"] to stem:[133 "unitsml(Pa)"]);
* the internal diameter of the capillary of the lamp is about stem:[5 "unitsml(mm)"], and the radiation is observed transversely;
* the lamp is excited by a high-frequency field at a moderate power and is maintained at a temperature less than stem:[10 "unitsml(degC)"];
* it is preferred that the volume of the lamp be greater than stem:[20"unitsml(cm^3)"].

For ^114^Cd, the above values with a relative expanded uncertainty stem:[ii(U) = 7 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a discharge lamp under the following conditions:

* the radiations are generated using a discharge lamp without electrodes, containing ^114^Cd of a purity not less than 95 %, and argon at a pressure of about stem:[1 "unitsml(mm)"] Hg (stem:[133 "unitsml(Pa)"]) at ambient temperature;
* the internal diameter of the capillary of the lamp is about stem:[5 "unitsml(mm)"], and the radiation is observed transversely;
* the lamp is excited by a high-frequency field at a moderate power and is maintained at a temperature such that the green line is not reversed.

== Source data

The recommended wavelengths are those recommended by the CIPM in 1963 <<bipm1962>>, <<bipm1963>>.

[bibliography]
== References

* [[[bipm1962,1]]], _BIPM, Com. Cons. Déf. Mètre_, 1962, *3*, 18-19

* [[[bipm1963,2]]], _BIPM, Proc. Verb. Com. Int. Poids et Mesures_, 1963, *31*, 26-27.
