= Recommended Values of Standard Frequencies: Krypton spectral lamp (stem:[ii(lambda) ~~ 606 "unitsml(nm)"])
:appendix-id: 2
:partnumber: 2.13
:edition: 9
:copyright-year: 2003
:language: en
:docnumber: SI MEP M REC 606nm
:title-appendix-en: Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second
:title-appendix-fr: Valeurs recommandées des fréquences étalons destinées à la mise en pratique de la définition du mètre et aux représentations secondaires de la seconde
:title-part-en: Krypton spectral lamp (stem:[ii(lambda) ~~ 606 "unitsml(nm)"])
:title-part-fr: Krypton spectral lamp (stem:[ii(lambda) ~~ 606 "unitsml(nm)"])
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

[%unnumbered]
== {blank}

*^86^Kr spectral lamp radiation, stem:[5"d"_5 - 2"p"_{10}] transition*

== CIPM recommended value

The value stem:[ii(lambda) = 605780210.3 "unitsml(fm)"] +
with a relative expanded uncertainty stem:[ii(U) = 3.9 xx 10^(−9)], where stem:[ii(U) = ku_c (k = 3)], stem:[u_c] being the combined standard uncertainty, applies to the radiation emitted by a discharge lamp. The radiation of ^86^Kr is obtained by means of a hot-cathode discharge lamp containing ^86^Kr, of a purity not less than 99 %, in sufficient quantity to assure the presence of solid krypton at a temperature of stem:[64 "unitsml(K)"], this lamp having a capillary with an inner diameter from stem:[2 "unitsml(mm)"] to stem:[4 "unitsml(mm)"] and a wall thickness of about stem:[1 "unitsml(mm)"].

It is estimated that the wavelength of the radiation emitted by the positive column is equal, to within 1 part in stem:[10^8], to the wavelength corresponding to the transition between the unperturbed levels, when the following conditions are satisfied:

* the capillary is observed end-on from the side closest to the anode;
* the lower part of the lamp, including the capillary, is immersed in a cold bath maintained at a temperature within one degree of the triple point of nitrogen;
* the current density in the capillary is (stem:[0.3 +- 0.1) "unitsml(A*cm^(-2),symbol:A cdot cm^(-2))"].

== Source data

Adopted value:: stem:[f = 494886516.4" "(6) "unitsml(MHz)"] +
stem:[u_c//y = 1.3 xx 10^(-9)]
+
for which: +
stem:[ii(lambda) = 605780210.3" "(.8) "unitsml(fm)"] +
stem:[u_c//y = 1.3 xx 10^(-9)]

calculated from

[%unnumbered]
|===
h| stem:[f // "unitsml(kHz)"] h| stem:[u_c//y] h| source data

| stem:[494886516422 "unitsml(kHz)"] | stem:[1.3 xx 10^(−9)] | <<sec2-1>>
|===


Source data

[[sec2-1]]
=== {blank}

The CCDM 1982 <<docs-metre>>, <<bipm-metre>> gives

[align=left]
stem:[f_(Kr) // f_i = 1.04491924205] +
stem:[u_c//y = 1.3 xx 10^(−9)], +
using the recommended operation conditions <<bipmx2>>.

Using the recommended value of the absorbing molecule ^127^I~2~, stem:["a"_{16}] or f component, R(127) 11-5 transition (see iodine at stem:[ii(lambda) ~~ 633 "unitsml(nm)"] and frequency differences listed in corresponding Table 1) one obtains

[align=left]
stem:[f_i = 473612214712 "unitsml(kHz)"] +
stem:[u_c//y = 2.2 xx 10^(−11)],

[align=left]
which leads to

[align=left]
stem:[f_(Kr) = 494886516422 "unitsml(kHz)"] +
stem:[u_c//y = 1.3 xx 10^(−9)].


[bibliography]
== References

* [[[docs-metre,1]]], Documents Concerning the New Definition of the Metre, _Metrologia_, 1984, *19*, 163-178.

* [[[bipm-metre,2]]], _BIPM, Com. Cons. Déf. Mètre_, 1982, *7*, M58..

* [[[bipmx2,3]]], _BIPM Proc. Verb. Com. Int. Poids et Mesures_, 1960, *28*, 71-72 and _BIPM Comptes Rendus 11^e^ Conf. Gén. Poids et Mesures_, 1960, *85*.
