= MEP 2003
:appendix: 2
:partnumber: 1
:edition: 9
:copyright-year: 2019
:language: en
:docnumber: SI MEP M REC Spectral
:title-appendix-en: Recommended Values of Standard Frequencies for Applications Including the Practical Realization of the Metre and Secondary Representations of the Definition of the Second: Spectral lamp radiations (2003)
:title-appendix-fr:
:title-en: The International System of Units
:title-fr: Le système international d’unités
:doctype: mise-en-pratique
:parent-document: si-brochure.adoc
:committee-acronym: CCL-CCTF-WGFS
:committee-en: CCL-CCTF Frequency Standards Working Group
:si-aspect: m_c_deltanu
:docstage: in-force
:confirmed-date:
:revdate:
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Spectral lamp radiations

*^86^Kr, ^198^Hg, ^114^Cd, spectral lamp radiations*

=== CIPM recommended values

Vacuum wavelengths, stem:[ii(lambda)], for ^86^Kr, ^198^Hg and ^114^Cd transitions

[cols="^,^,^"]
[%unnumbered]
|===
| Atom | Transition | stem:[ii(lambda) // rm(pm)]
| ^86^Kr | 2p~9~ – 5d'~4~ | stem:[645807.20]
| ^86^Kr | 2p~8~ – 5d~4~ | stem:[642280.06]
| ^86^Kr | 1s~3~ – 3p~10~ | stem:[565112.86]
| ^86^Kr | 1s~4~ – 3p~8~ | stem:[450361.62]
| ^198^Hg | 6~1~P~1~ – 6^1^D~2~ | stem:[579226.83]
| ^198^Hg | 6~1~P~1~ – 6^3^D~2~ | stem:[577119.83]
| ^198^Hg | 6~3~P~2~ – 7^3^S~1~ | stem:[546227.05]
| ^198^Hg | 6~3~P~1~ – 7^3^S~1~ | stem:[435956.24]
| ^114^Cd | 5~1~P~1~ – 5^1^D~2~ | stem:[644024.80]
| ^114^Cd | 5~3~P~2~ – 6^3^S~1~ | stem:[508723.79]
| ^114^Cd | 5~3~P~1~ – 6^3^S~1~ | stem:[480125.21]
| ^114^Cd | 5~3~P~0~ – 6^3^S~1~ | stem:[467945.81]
|===

For ^86^Kr, the above values with a relative expanded uncertainty stem:[ii(U) = 2 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a hot-cathode discharge lamp containing ^86^Kr, of a purity not less than 99 %, in sufficient quantity to assure the presence of solid krypton at a temperature of 64 K, this lamp having a capillary with an inner diameter from 2 mm to 4 mm and a wall thickness of about 1 mm.

It is estimated that the wavelength of the radiation emitted by the positive column is equal, to within 1 part in stem:[10^8], to the wavelength corresponding to the transition between the unperturbed levels, when the following conditions are satisfied:

* the capillary is observed end-on from the side closest to the anode;
* the lower part of the lamp, including the capillary, is immersed in a cold bath maintained at a temperature within one degree of the triple point of nitrogen;
* the current density in the capillary is stem:[(0.3 +- 0.1)" A "*" cm"^(−2)].

For ^198^Hg, the above values with a relative expanded uncertainty stem:[ii(U) = 5 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a discharge lamp when the following conditions are met:

* the radiations are produced using a discharge lamp without electrodes containing ^198^Hg, of a purity not less than 98 %, and argon at a pressure from 0.5 mm Hg to 1.0 mm Hg (66 Pa to 133 Pa);
* the internal diameter of the capillary of the lamp is about 5 mm, and the radiation is observed transversely;
* the lamp is excited by a high-frequency field at a moderate power and is maintained at a temperature less than 10 °C;
* it is preferred that the volume of the lamp be greater than stem:[20" "rm(cm)^3].

For ^114^Cd, the above values with a relative expanded uncertainty stem:[ii(U) = 7 xx 10^(−8)], where stem:[ii(U) = ku_c" "(k = 3)], apply to radiations emitted by a discharge lamp under the following conditions:

* the radiations are generated using a discharge lamp without electrodes, containing ^114^Cd of a purity not less than 95 %, and argon at a pressure of about 1 mm Hg (133 Pa) at ambient temperature;
* the internal diameter of the capillary of the lamp is about 5 mm, and the radiation is observed transversely;
* the lamp is excited by a high-frequency field at a moderate power and is maintained at a temperature such that the green line is not reversed.

=== Source data

The recommended wavelengths are those recommended by the CIPM in 1963 <<bipm1962>>, <<bipm1963>>.

[bibliography]
=== References

* [[[bipm1962,1]]], _BIPM, Com. Cons. Déf. Mètre_, 1962, *3*, 18-19

* [[[bipm1963,2]]], _BIPM, Proc. Verb. Com. Int. Poids et Mesures_, 1963, *31*, 26-27.
