
[appendix]
== Notes historiques sur l’évolution du Système international d’unités et ses unités de base

=== L’évolution historique de la réalisation des unités du SI

Les méthodes expérimentales utilisées pour réaliser les unités à l’aide d’équations de la
physique sont appelées méthodes primaires. Une méthode primaire a pour caractéristique
essentielle de permettre de mesurer directement une grandeur dans une unité particulière à
partir de sa définition en utilisant seulement des grandeurs et constantes qui n’impliquent
pas elles-mêmes l’unité en question.

De façon traditionnelle, une unité pour une grandeur donnée était considérée comme un
exemple particulier de cette grandeur, choisie pour fournir des valeurs numériques de
mesures courantes d’une taille convenable. Avant l’avènement de la science moderne,
les unités étaient nécessairement définies à partir d’artéfacts matériels, notamment le mètre
pour la longueur et le kilogramme pour la masse, ou à partir de la propriété d’un objet
particulier, comme la rotation de la Terre pour la seconde. Toutefois, même à l’origine du
système métrique à la fin du 18^e^ siècle, il était reconnu qu’une définition plus souhaitable
de l’unité de longueur, par exemple, serait une définition fondée sur une propriété
universelle de la nature telle que la longueur d’un pendule battant la seconde. Une telle
définition serait indépendante du moment et du lieu de réalisation de l’unité et serait en
principe accessible dans le monde entier. À cette époque, des considérations pratiques ont
conduit à des définitions plus simples, fondées sur des artéfacts, du mètre et du kilogramme
et la seconde est restée liée à la rotation de la Terre. Ce n’est qu’en 1960 que la première
définition non matérielle du mètre, à savoir la longueur d’onde d’un rayonnement optique
spécifique, a été adoptée.

Les définitions de l’ampère, du kelvin, de la mole et de la candela qui furent ensuite
adoptées ne faisaient pas référence à des artéfacts matériels: la définition de l’ampère était
fondée sur un courant électrique spécifique requis pour produire une force
électromagnétique donnée et la définition du kelvin sur un état thermodynamique
particulier du point triple de l’eau. La définition atomique de la seconde reposait sur une
transition spécifique de l’atome de césium. Le kilogramme a toujours fait exception puisque
c’était la seule unité restant fondée sur un artéfact. La définition qui a ouvert la voie à une
réelle universalité a été celle du mètre adoptée en 1983. Bien qu’elle ne l’indique pas
explicitement, cette définition impliquait une valeur numérique fixée de la vitesse de la
lumière. La définition était formulée, cependant, de façon traditionnelle et énonçait pour
l’essentiel que le mètre était la distance parcourue par la lumière en un temps donné.
De cette façon, la définition du mètre avait la même forme que les définitions des autres
unités de base du SI (« l’ampère est le courant qui... », « le kelvin est une fraction d’une
température précise », etc.). De telles définitions peuvent être désignées sous le terme de
« définitions à unité explicite ».

Bien que ces définitions répondent à plusieurs des exigences d’universalité et
d’accessibilité, et qu’elles peuvent être réalisées de diverses façons possibles, elles limitent
toutefois les réalisations pratiques à des expériences directement ou indirectement liées aux
conditions ou états particuliers précisés dans les définitions. Par conséquent, l’exactitude de
la mise en pratique de telles définitions ne peut jamais être meilleure que l’exactitude de la
réalisation des conditions ou états particuliers précisés dans les définitions.

C’est un problème particulier avec l’actuelle définition de la seconde fondée sur une
transition microonde d’un atome de césium. Il a été établi que les fréquences des transitions
optiques de différents atomes ou ions sont désormais plus reproductibles, de quelques
ordres de grandeur, que la fréquence définie du césium.

Dans la présente révision du SI fondée sur un ensemble de constantes choisies, au lieu que
chaque définition indique une condition ou un état spécifique, ce qui impose une limite
fondamentale à l’exactitude de la réalisation, toute équation appropriée de la physique qui
relie la ou les constantes particulières à la grandeur à mesurer peut être utilisée. Les unités
de base sont ainsi définies de façon beaucoup plus générale, sans limite imposée par la
science ou les technologies actuelles car les progrès à venir pourront conduire à découvrir
des équations aujourd’hui inconnues qui permettront de réaliser les unités de différentes
manières, à un niveau d’exactitude beaucoup plus élevé. Avec un système d’unités ainsi
défini, il n’existe en principe aucune limite concernant l’incertitude à laquelle une unité
peut être réalisée. L’exception reste la définition de la seconde pour laquelle la transition
microonde du césium est conservée, pour le moment, comme base de la définition.

La différence entre une « définition à unité explicite » et une « définition à constante
explicite » peut être clairement illustrée à l’aide des deux précédentes définitions du mètre
qui reposaient sur une valeur numérique fixée de la vitesse de la lumière ou à l’aide des
deux définitions du kelvin. La définition originale du mètre de 1983 indique, en effet, que
« le mètre est la longueur du trajet parcouru dans le vide par la lumière pendant une durée
de 1/299 792 458 de seconde ». La nouvelle définition indique simplement que le mètre est
défini en fonction de la constante définissant la seconde, la fréquence du césium précisée,
et de la valeur numérique de la vitesse de la lumière exprimée en unité stem:[m s^{-1}]. Il est ainsi
possible d’utiliser toute équation de la physique, y compris bien sûr celle spécifiée dans la
précédente définition, le temps nécessaire pour effectuer le trajet d’une distance donnée,
utilisée pour les distances astronomiques, mais aussi la simple équation reliant la fréquence
et la longueur d’onde à la vitesse de la lumière. La précédente définition du kelvin fondée
sur une valeur numérique fixée de la température du point triple de l’eau nécessite en fin de
compte une mesure à la température du point triple de l’eau. La nouvelle définition, fondée
sur la valeur numérique fixée de la constante de Boltzmann, est beaucoup plus générale au
sens où toute équation thermodynamique contenant k peut en principe être utilisée pour
déterminer une température thermodynamique à tout point de l’échelle de température.
Par exemple, en déterminant l’exitance énergétique totale d’un corps noir à la température
stem:[T], équivalente à stem:[(2 pi^5 k^4//15c^2 h^3) T^4], en stem:["W m"^{-2}], il est possible de déterminer directement stem:[T].

Concernant le kilogramme, l’unité dont la définition a changé de la façon la plus
fondamentale dans la présente brochure, la réalisation peut être effectuée à partir de toute
équation de la physique reliant la masse, la constante de Planck, la vitesse de la lumière et
la fréquence du césium. L’une de ces équations est celle décrivant le fonctionnement d’une
balance électromécanique, connue précédemment sous le nom de balance du watt et plus
récemment de balance de Kibble
footnote:[La balance du watt a été renommée balance de Kibble, du nom de son inventeur Bryan Kibble.].
Une balance de Kibble permet de mesurer une puissance
mécanique, mesurée en fonction d’une masse, stem:[m], l’accélération due à la gravité, g, et une
vitesse, v, à l’aide d’une puissance électrique mesurée à partir d’un courant électrique et
d’une tension mesurées à l’aide des effets Hall quantique et Josephson, respectivement.
L’équation qui en résulte est la suivante stem:[mgv = Ch] où stem:[C] est une constante d’étalonnage qui
comprend des fréquences mesurées et stem:[h] la constante de Planck.

Une autre méthode pouvant être utilisée comme réalisation primaire du kilogramme est la
détermination du nombre d’atomes contenus dans une sphère de silicium à l’aide de
l’équation:

[stem%unnumbered]
++++
m = {8V}/{a_0^3} {2R_{oo}h}/{c alpha^2} m_{Si}/m_e
++++


avec la masse m et le volume stem:[V] de la sphère (d’environ 1 kg), le paramètre de réseau stem:[a_0],
la constante de Rydberg stem:[R_{oo}], la constante de structure fine stem:[alpha], la masse d’un atome de
silicium (en établissant une moyenne par rapport aux trois isotopes des sphères) mSi,
et la masse d’un électron stem:[m_e]. La première fraction correspond au nombre d’atomes contenus
dans la sphère, la deuxième à la masse de l’électron et la troisième au rapport de la masse
de l’atome de silicium (pondérée isotopiquement) et de la masse de l’électron.

Une autre possibilité pour mesurer la masse à l’aide de la nouvelle définition du
kilogramme, mais cette fois au niveau microscopique, est de mesurer le recul atomique à
l’aide de la relation incluant stem:[h//m].

Toutes ces méthodes illustrent parfaitement le caractère général de la nouvelle façon de
définir les unités. Le site internet du BIPM contient des informations détaillées sur les
réalisations actuelles des unités de base et des autres unités.


=== L’évolution historique du Système international

La CGPM à sa 9^e^ réunion (1948, Résolution 6; CR, 64), chargea le CIPM:

* d’étudier l’établissement d’une réglementation complète des unités de mesure;

* d’ouvrir à cet effet une enquête officielle sur l’opinion des milieux scientifiques,
techniques et pédagogiques de tous les pays et

* d’émettre des recommandations concernant l’établissement d’un […]
_système pratique d’unités de mesure_, susceptible d’être adopté dans tous les pays
signataires de la Convention du Mètre.

Cette même CGPM adopta aussi la Résolution 7 (CR, 70) qui fixe des principes généraux
pour l’écriture des symboles d’unités et donne une liste de quelques unités cohérentes ayant
un nom spécial.

La CGPM à sa 10^e^ réunion (1954, Résolution 6; CR, 80) adopta comme grandeurs et unités
de base de ce système pratique d’unités les six grandeurs suivantes: longueur, masse,
temps, courant électrique, température thermodynamique et intensité lumineuse, ainsi que
les six unités de base correspondantes: mètre, kilogramme, seconde, ampère, kelvin et
candela. Après de longues discussions entre physiciens et chimistes, la CGPM à sa
14^e^ réunion (1971, Résolution 3, CR 78 et _Metrologia_ 1972, 8, 36) ajouta la quantité de
matière comme septième grandeur de base, avec pour unité de base la mole.

La CGPM à sa 11^e^ réunion (1960, Résolution 12; CR, 87) adopta le nom 
_Système international d’unités_, avec l’abréviation internationale _SI_, pour ce système pratique
d’unités et fixa des règles pour les préfixes, les unités dérivées et les unités supplémentaires
(disparues depuis) et d’autres indications, établissant ainsi une réglementation d’ensemble
pour les unités de mesure. Au cours des réunions qui suivirent, la CGPM et le CIPM
étoffèrent et modifièrent la structure originelle du SI pour tenir compte des progrès de la
science et de l’évolution des besoins des utilisateurs.

Il est possible de résumer comme suit les principales étapes historiques qui conduisirent à
ces décisions importantes:

* La création du Système métrique décimal au moment de la Révolution française et le
dépôt qui en a résulté, le 22 juin 1799, de deux étalons en platine représentant le
mètre et le kilogramme aux Archives de la République à Paris peuvent être
considérés comme la première étape ayant conduit au Système international d’unités
actuel.

* En 1832, Gauss oeuvra activement en faveur de l’application du Système métrique,
associé à la seconde, définie en astronomie, comme système cohérent d’unités pour
les sciences physiques. Gauss fut le premier à faire des mesures absolues du champ
magnétique terrestre en utilisant un système décimal fondé sur les _trois unités
mécaniques_ millimètre, gramme et seconde pour, respectivement, les grandeurs
longueur, masse et temps. Par la suite, Gauss et Weber ont étendu ces mesures pour
y inclure d’autres phénomènes électriques.

* Dans les années 1860, Maxwell et Thomson mirent en oeuvre de manière plus complète
ces mesures dans les domaines de l’électricité et du magnétisme au sein de la British
Association for the Advancement of Science (BAAS). Ils exprimèrent les règles de
formation d’un _système cohérent d’unités_ composé d’unités de base et d’unités dérivées.
En 1874, la BAAS introduisit le système CGS, un système d’unités tri-dimensionnel
cohérent fondé sur les trois unités mécaniques centimètre, gramme et seconde, et utilisant
des préfixes allant de micro à méga pour exprimer les sous-multiples et multiples
décimaux. C’est en grande partie sur l’utilisation de ce système que se fonda, par la suite,
le développement expérimental des sciences physiques.

* Le fait de compléter de façon cohérente le système CGS pour les domaines de
l’électricité et du magnétisme conduisit à choisir des unités d’amplitude peu adaptée
à la pratique. Le BAAS et le Congrès international d’électricité, qui précéda la
Commission électrotechnique internationale (IEC), approuvèrent, dans les années
1880, un système mutuellement cohérent d’__unités pratiques__. Parmi celles-ci
figuraient l’ohm pour la résistance électrique, le volt pour la force électromotrice et
l’ampère pour le courant électrique.

* Après la signature, le 20 mai 1875, de la Convention du Mètre, qui créa le BIPM et
établit la CGPM et le CIPM, on fabriqua de nouveaux prototypes internationaux du
mètre et du kilogramme, approuvés en 1889 par la CGPM à sa 1^ère^ réunion.
Avec la seconde des astronomes comme unité de temps, ces unités constituaient un
système d’unités mécaniques tri-dimensionnel similaire au système CGS, mais dont
les unités de base étaient le mètre, le kilogramme et la seconde, connu sous le nom
de système MKS.

* En 1901, Giorgi montra qu’il était possible de combiner les unités mécaniques du
système MKS au système pratique d’unités électriques pour former un seul système
cohérent quadri-dimensionnel en ajoutant à ces trois unités de base une quatrième
unité, de nature électrique, telle que l’ampère ou l’ohm, et en rationalisant les
équations utilisées en électromagnétisme. La proposition de Giorgi ouvrit la voie à
d’autres extensions.

* Après la révision de la Convention du Mètre par la CGPM à sa 6^e^ réunion (1921),
qui étendit les attributions et les responsabilités du BIPM à d’autres domaines de la
physique, et la création du Comité consultatif d’électricité (CCE) par la CGPM à sa
7^e^ réunion qui en a résulté en 1927, la proposition de Giorgi fut discutée en détail
par l’IEC, l’International Union of Pure and Applied Physics (IUPAP) et d’autres
organisations internationales. Ces discussions conduisirent le CCE à proposer,
en 1939, l’adoption d’un système quadri-dimensionnel fondé sur le mètre,
le kilogramme, la seconde et l’ampère (système MKSA), une proposition qui fut
approuvée par le Comité international en 1946.

* À la suite d’une enquête internationale effectuée par le BIPM à partir de 1948,
la CGPM à sa 10^e^ réunion (1954) approuva l’introduction du kelvin et de la candela
comme unités de base de la température thermodynamique et de l’intensité
lumineuse, respectivement. La CGPM à sa 11^e^ réunion (1960) donna le nom de
Système international d’unités (SI) à ce système. Des règles pour les préfixes,
les unités dérivées et les unités supplémentaires (disparues depuis) et d’autres
indications furent établies, établissant ainsi une réglementation d’ensemble pour les
unités de mesure.

* Lors de la 14^e^ réunion de la CGPM (1971), une nouvelle unité de base, la mole,
symbole mol, a été adoptée pour la quantité de matière. Cela fit suite à une
proposition formulée par l’Organisation internationale de normalisation (ISO),
émanant en premier lieu de la Commission on Symbols, Units and Nomenclature de
l’International Union of Pure and Applied Physics (IUPAP) et soutenue par
l’International Union of Pure and Applied Chemistry (IUPAC). Le SI passa ainsi à
sept unités de base.

* Depuis, des avancées extraordinaires ont été réalisées pour relier les unités du SI à
des grandeurs véritablement invariantes telles que les constantes fondamentales de la
physique et les propriétés des atomes. Reconnaissant l’importance de relier les unités
du SI à de telles grandeurs invariantes, la CGPM à sa 24^e^ réunion (2011) adopta les
principes d’une nouvelle définition du SI fondée sur l’utilisation d’un ensemble de
sept constantes de ce type comme références des définitions des unités. Au moment
de la 24^e^ réunion de la CGPM, les expériences visant à déterminer les valeurs
numériques de ces constantes ne permettaient pas d’obtenir des résultats
complètement cohérents mais cela fut le cas lors de la 26^e^ réunion de la CGPM
(2018) et la nouvelle définition du SI fut adoptée dans la Résolution 1. Telle est la
base de la définition du SI présentée dans la présente brochure: elle constitue la
façon la plus simple et la plus fondamentale de définir le SI.

* Le SI était précédemment défini en fonction de sept unités de base, et d’unités
dérivées définies comme le produit de puissances des unités de base. Les sept unités
de base avaient été choisies pour des raisons historiques, en fonction de l’évolution
du système métrique et du développement du SI au cours des 130 dernières années.
Le choix de ces unités n’était pas le seul possible mais au fil des ans, cela est devenu
un fait établi et ces unités sont devenues familières, fournissant non seulement un
cadre pour décrire le SI mais aussi pour définir les unités dérivées. Le rôle des unités
de base demeure le même dans l’actuel SI, bien que le SI lui-même soit défini sur la
base de sept constantes choisies. Ainsi, dans la présente brochure, les définitions des
sept unités de base restent présentes mais elles se fondent sur les sept constantes
définissant le SI, à savoir la fréquence stem:[Delta ν_{C_s}] de la transition hyperfine de l’état
fondamental de l’atome de césium, la vitesse stem:[c] de la lumière dans le vide,
la constante de Planck stem:[h], la charge élémentaire stem:[e], la constante de Boltzmann stem:[k],
la constante d’Avogadro NA et l’efficacité lumineuse stem:[K_{cd}] d’un rayonnement visible
défini.

Les définitions des sept unités de base peuvent être reliées sans ambiguïté aux valeurs
numériques des sept constantes définissant le SI mais il n’existe pas de correspondance
biunivoque entre les sept constantes et les sept unités de base car plusieurs des unités de
base peuvent être reliées à plus d’une de ces sept constantes.


=== Perspective historique sur les unités de base du SI

==== Unité de temps, la seconde

Avant 1960, l’unité de temps, la seconde, était définie comme la fraction 1/86 400 du jour
solaire moyen. La définition exacte du « jour solaire moyen » était laissée aux astronomes.
Toutefois, les observations ont montré que cette définition n’était pas satisfaisante du fait
des irrégularités de la rotation de la Terre. Pour donner plus de précision à la définition de
l’unité de temps, la CGPM à sa 11^e^ réunion (1960, Résolution 9; CR, 86) approuva une
définition, donnée par l’Union astronomique internationale, qui était fondée sur l’année
tropique 1900. Cependant, les recherches expérimentales avaient déjà montré qu’un étalon
atomique de temps, fondé sur une transition entre deux niveaux d’énergie d’un atome ou
d’une molécule, pourrait être réalisé et reproduit avec une exactitude beaucoup plus élevée.
Considérant qu’une définition de haute précision de l’unité de temps était indispensable
pour la science et la technologie, la CGPM à sa 13^e^ réunion (1967-1968, Résolution 1;
CR, 103 et Metrologia, 1968, *4*, 43) choisit une nouvelle définition de la seconde fondée sur
la fréquence de la transition hyperfine de l’état fondamental de l’atome de césium 133.
Une nouvelle formulation plus précise de cette même définition, fondée désormais sur une
valeur numérique fixée de la fréquence de la transition hyperfine de l’état fondamental
de l’atome de césium 133 non perturbé, stem:[Delta ν_{C_s}], a été adoptée par la CGPM à sa 26^e^ réunion
(2018) dans sa Résolution 1.


==== Unité de longueur, le mètre

La définition du mètre de 1889, à savoir la longueur du prototype international en platine
iridié, avait été remplacée par la CGPM à sa 11^e^ réunion (1960) par une définition fondée
sur la longueur d’onde d’une radiation correspondant à une transition particulière du
krypton 86, afin d’améliorer l’exactitude de la réalisation de la définition du mètre.
Cette réalisation était effectuée au moyen d’un interféromètre et d’un microscope mobile en
translation utilisés pour mesurer la variation des trajets optiques par comptage de franges.
Cette définition fut remplacée en 1983 par la CGPM à sa 17^e^ réunion (Résolution 1;
CR, 97 et Metrologia, 1984, *20*, 25) par une définition fondée sur la longueur du trajet
parcouru dans le vide par la lumière dans un intervalle de temps spécifique. Le prototype
international du mètre originel, qui fut approuvé par la CGPM à sa 1^ère^ réunion en 1889
(CR, 34-38), est toujours conservé au BIPM dans les conditions fixées en 1889. Afin de
mettre en évidence la dépendance de la définition du mètre vis-à-vis de la valeur numérique
fixée de la vitesse de la lumière, stem:[c], la formulation de la définition du mètre a été modifiée
par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


==== Unité de masse, le kilogramme

Selon la définition du kilogramme de 1889, l’unité de masse était simplement égale à la
masse du prototype international du kilogramme, un artéfact fabriqué en platine iridié.
Ce prototype était conservé au BIPM, et l’est toujours, dans les conditions fixées par la
CGPM à sa 1ère réunion en 1889 (CR, 34-38) lorsque cette dernière sanctionna le prototype
et déclara: « Ce prototype sera considéré désormais comme unité de masse ».
Quarante prototypes similaires ont été fabriqués à la même époque; tous ont été usinés et
polis afin d’avoir la même masse que celle du prototype international. Lors de la première
réunion de la CGPM en 1889, la plupart de ces « étalons nationaux », une fois étalonnés à
l’aide du prototype international du kilogramme, ont été assignés à des États Membres de la
Convention du Mètre et certains au BIPM. La CGPM à sa 3^e^ réunion en 1901 (CR, 70),
dans une déclaration visant à faire cesser l’ambiguïté qui existait dans l’usage courant sur la
signification du terme « poids », confirma que « le kilogramme est l’unité de masse; il est
égal à la masse du prototype international du kilogramme »; la version complète de cette
déclaration figure page 70 des comptes rendus de la CGPM précédemment mentionnés.

Lors de la seconde vérification des prototypes nationaux en 1946, il fut toutefois constaté
qu’en moyenne, la masse de ces prototypes divergeait par rapport à celle du prototype
international. Cela fut confirmé lors de la troisième vérification, effectuée de 1989 à 1991,
la différence moyenne étant d’environ 25 microgrammes pour l’ensemble des prototypes
originaux sanctionnés par la CGPM à sa première réunion (1889). Afin d’assurer la stabilité
à long terme de l’unité de masse, de tirer pleinement parti des étalons électriques
quantiques et de répondre au mieux à la science moderne, une nouvelle définition du
kilogramme fondée sur la valeur d’une constante fondamentale, la constante de Planck stem:[h],
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


==== Unité de courant électrique, l’ampère

Des unités électriques, dites « internationales », pour le courant et la résistance, avaient été
introduites par le Congrès international d’électricité tenu à Chicago en 1893 et les
définitions de l’ampère « international » et de l’ohm « international » furent confirmées par
la Conférence internationale de Londres en 1908.

Le souhait unanime de remplacer ces unités « internationales » par des unités dites
« absolues » fut déjà exprimé lors de la 8^e^ réunion de la CGPM (1933). Toutefois, étant
donné que certains laboratoires n’avaient pas encore achevé les expériences nécessaires
pour déterminer les rapports entre les unités internationales et les unités absolues, la CGPM
chargea le CIPM de décider, en temps opportun, des rapports et de la date d’adoption de ces
nouvelles unités absolues. Le CIPM décida en 1946 (1946, Résolution 2, PV, 20, 129-137)
que les nouvelles unités entreraient en vigueur le 1^er^ janvier 1948. En octobre 1948,
la CGPM à sa 9^e^ réunion approuva les décisions prises par le CIPM. La définition de
l’ampère choisie par le CIPM était fondée sur la force produite entre deux conducteurs
parallèles parcourus par un courant électrique et fixait par conséquent la valeur de la
perméabilité magnétique du vide stem:[mu_0] (ou constante magnétique). La valeur de la permittivité
diélectrique du vide stem:[epsilon_0] (ou constante électrique) fut ensuite fixée du fait
de l’adoption de la nouvelle définition du mètre en 1983.

Toutefois, la définition de l’ampère de 1948 s’avéra difficile à réaliser et les étalons
quantiques pratiques (à effet Josephson et à effet Hall quantique), qui relient le volt et
l’ohm aux combinaisons particulières de la constante de Planck h et de la charge
élémentaire e, furent utilisés de façon presque universelle comme réalisation pratique de
l’ampère à l’aide de la loi d’Ohm (CGPM, 1987, Résolution 6; CR, 100). Par conséquent,
il devint naturel non seulement de fixer la valeur numérique de h pour redéfinir le
kilogramme mais aussi de fixer la valeur numérique de e pour redéfinir l’ampère afin que
les étalons électriques quantiques pratiques soient exactement en accord avec le SI.
L’actuelle définition de l’ampère fondée sur une valeur numérique fixée de la charge
élémentaire, stem:[e], a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


==== Unité de température thermodynamique, le kelvin

La définition de l’unité de température thermodynamique fut donnée par la CGPM à sa
10^e^ réunion (1954, Résolution 3; CR, 79) qui choisit
le point triple de l’eau, stem:[T_{TPW}], comme
point fixe fondamental en lui attribuant la température de 273,16 K par définition.
La CGPM à sa 13^e^ réunion (1967-1968, Résolution 3; CR, 104 et Metrologia, 1968, 4, 43)
adopta le nom « kelvin », symbole K, au lieu de « degré kelvin », symbole ºK, pour l’unité
définie de cette façon. Toutefois, les difficultés pratiques liées à la réalisation de cette
définition, qui requiert un échantillon d’eau pure à la composition isotopique bien définie
ainsi que le développement de nouvelles méthodes primaires thermométriques, ont conduit
à l’adoption d’une nouvelle définition du kelvin fondée sur une valeur numérique fixée de
la constante de Boltzmann, stem:[k]. L’actuelle définition du kelvin, qui supprime ces contraintes,
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


==== Unité de quantité de matière, la mole

Après la découverte des lois fondamentales de la chimie, on a utilisé, pour spécifier les
quantités des divers éléments et composés chimiques, des unités portant par exemple les
noms de « atome-gramme » et « molécule-gramme ». Ces unités étaient liées directement
aux « poids atomiques » et aux « poids moléculaires » qui étaient en réalité des masses
atomiques et moléculaires relatives. Les « poids atomiques » furent d’abord rapportés à
celui de l’élément chimique oxygène, pris par convention égal à 16. Tandis que les
physiciens séparaient les isotopes au spectromètre de masse et attribuaient la valeur 16 à
l’un des isotopes de l’oxygène, les chimistes attribuaient la même valeur au mélange
(de composition légèrement variable) des isotopes 16, 17 et 18 qui constitue l’élément
oxygène naturel. Un accord entre l’International Union of Pure and Applied Physics
(IUPAP) et l’International Union of Pure and Applied Chemistry (IUPAC) mit fin à cette
dualité en 1959/60. Physiciens et chimistes convinrent d’attribuer la valeur 12, exactement,
au « poids atomique » de l’isotope 12 du carbone (carbone 12, ^12^C), ou selon une
formulation plus correcte à la masse atomique relative stem:[A_r] de l’isotope 12 du carbone.
L’échelle unifiée ainsi obtenue donne les valeurs des masses atomiques et moléculaires
relatives, aussi connues sous le nom de poids atomiques et moléculaires, respectivement.
Cet accord est resté en vigueur jusqu’à la redéfinition du SI en 2018.

La grandeur utilisée par les chimistes pour spécifier la quantité d’éléments ou de composés
chimiques est appelée « quantité de matière ». La quantité de matière, symbole stem:[n],
est définie comme étant proportionnelle au nombre d’entités élémentaires N d’un
échantillon, la constante de proportionnalité étant une constante universelle identique pour
toutes les entités. La constante de proportionnalité est l’inverse de la constante d’Avogadro,
stem:[N_"A"], de sorte que stem:[n = N//N_"A"]. L’unité de quantité de matière est appelée la mole, symbole mol.
Suivant les propositions de l’IUPAP, de l’IUPAC et de l’ISO, le CIPM donna une
définition de la mole en 1967 qu’il confirma en 1969: la masse molaire du carbone 12
devait être exactement 0,012 kg/mol. Cela permettait de déterminer directement la quantité
de matière stem:[nS(X)] de tout échantillon pur S d’une entité X à partir de la masse de
l’échantillon stem:[m_S] et de la masse molaire stem:[M("X")] de l’entité X, la masse molaire étant
elle-même déterminée à partir de sa masse atomique relative stem:[A_r] (poids atomique ou
moléculaire) sans avoir besoin de connaître de façon précise la constante d’Avogadro,
à l’aide des relations

[stem%unnumbered]
++++
n_S("X") = m_S // M("X"), " and " M("X") = A_r("X") " g/mol"
++++

Ainsi, la définition de la mole dépendait de la définition du kilogramme fondée sur un
artéfact.

La valeur numérique de la constante d’Avogadro ainsi définie était égale au nombre
d’atomes dans 12 grammes de carbone 12. Toutefois, en raison des avancées
technologiques récentes, ce nombre est désormais connu avec une précision telle qu’une
définition plus simple et plus universelle de la mole est devenue possible, à savoir une
définition indiquant exactement le nombre d’entités dans une mole d’une matière quelle
qu’elle soit, ce qui fixe la valeur numérique de la constante d’Avogadro. Par conséquent,
cette nouvelle définition de la mole et la valeur de la constante d’Avogadro ne sont plus
dépendantes de la définition du kilogramme. Par ailleurs, cela souligne la distinction entre
les grandeurs fondamentalement différentes « quantité de matière » et « masse ». L’actuelle
définition de la mole fondée sur une valeur numérique fixée de la constante d’Avogadro,
NA, a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.


==== Unité d’intensité lumineuse, la candela

Les unités d’intensité lumineuse fondées sur des étalons à flamme ou à filament
incandescent, qui étaient en usage dans différents pays avant 1948, furent d’abord
remplacées par la « bougie nouvelle » fondée sur la luminance du radiateur de Planck
(corps noir) à la température de congélation du platine. Cette modification avait été
préparée dès avant 1937 par la Commission internationale de l’éclairage (CIE) et par le
CIPM; la décision fut prise par le CIPM en 1946. Elle fut ratifiée en 1948 par la CGPM à
sa 9^e^ réunion qui adopta pour cette unité un nouveau nom international, la candela,
symbole cd; en 1954, la CGPM à sa 10^e^ réunion établit la candela comme unité de base;
en 1967, la CGPM à sa 13^e^ réunion (Résolution 5; CR, 104 et _Metrologia_, 1968, *4*, 43-44)
donna une forme modifiée à la définition de 1946.

En 1979, en raison des difficultés expérimentales liées à la réalisation du radiateur de
Planck aux températures élevées et des possibilités nouvelles offertes par la radiométrie,
c’est-à-dire la mesure de la puissance des rayonnements optiques, la 16^e^ CGPM (1979,
Résolution 3; CR, 100 et _Metrologia_, 1980, 16, 56) adopta une nouvelle définition de la
candela.

L’actuelle définition de la candela, fondée sur une valeur numérique fixée de l’efficacité
lumineuse d’un rayonnement monochromatique de fréquence stem:[540 xx 10^12] stem:["Hz"], Kcd,
a été adoptée par la CGPM à sa 26^e^ réunion (2018) dans sa Résolution 1.

