=== CIPM, 1956

==== Definition of the unit of time (second) (PV, 25, 77)

[align=center]
*Resolution 1*

In virtue of the powers invested in it by Resolution 5 of the 10th Conférence Générale des Poids et Mesures, the Comité International des Poids et Mesures,

*considering*

. that the 9th General Assembly of the International Astronomical Union (Dublin, 1955) declared itself in favour of linking the second to the tropical year,

[align=left]
. that, according to the decisions of the 8th General Assembly of the International Astronomical Union (Rome, 1952), the second of ephemeris time (ET) is the fraction +
stem:[((12 960 276 813) / (408 986 496)) times 10^(-9)] of the tropical year for 1900 January 0 at 12 h ET,

*decides*

"The second is the fraction stem:[1text(/)31 556 925.9747] of the tropical year for 1900 January 0 at 12 hours ephemeris time."

NOTE: This definition was abrogated in 1967 by the 13th CGPM (Resolution 1, see p. 168).

==== Système International d'Unités (PV, 25, 83)

[align=center]
*Resolution 3*

The Comité International des Poids et Mesures,

*considering*

* the task entrusted to it by Resolution 6 of the 9th Conférence Générale des Poids et Mesures (CGPM) concerning the establishment of a practical system of units of measurement suitable for adoption by all countries adhering to the Metre Convention,
* the documents received from twenty-one countries in reply to the enquiry requested by the 9th CGPM,
* Resolution 6 of the 10th CGPM, fixing the base units of the system to be established,

*recommends*

[align=left]
. that the name "Système International d'Unités" be given to the system founded on the base units adopted by the 10th CGPM, viz.: +
[This is followed by the list of the six base units with their symbols, reproduced in Resolution 12 of the 11th CGPM (1960)].

. that the units listed in the table below be used, without excluding others which might be added later: +
[This is followed by the table of units reproduced in paragraph 4 of Resolution 12 of the 11th CGPM (1960)].