=== 19th CGPM, 1991

==== SI prefixes zetta, zepto, yotta and yocto (CR, 185 and Metrologia, 1992, 29, 3)

[align=center]
*Resolution 4*

The 19th Conférence Générale des Poids et Mesures (CGPM)

*decides* to add to the list of SI prefixes to be used for multiples and submultiples of units, adopted by the 11th CGPM, Resolution 12, paragraph 3, the 12th CGPM, Resolution 8 and the 15th CGPM, Resolution 10, the following prefixes:

[%unnumbered]
|===
| Multiplying factor | Prefix | Symbol

| stem:[10^(21)] | zetta | Z
| stem:[10^(-21)] | zepto | z
| stem:[10^(24)] | yotta | Y
| stem:[10^(-24)] | yocto | y
|===

NOTE: The names zepto and zetta are derived from septo suggesting the number seven (the seventh power of stem:[10^3]) and the letter "z" is substituted for the letter "s" to avoid the duplicate use of the letter "s" as a symbol. The names yocto and yotta are derived from octo, suggesting the number eight (the eighth power of stem:[10^3]); the letter "y" is added to avoid the use of the letter "o" as a symbol because it may be confused with the number zero.