=== CIPM, 2007

==== Revision of the Mise en pratique list of recommended radiations (PV, 75, 185)

[align=center]
*Recommendation 1*

The International Committee for Weights and Measures,

*considering that*:

* improved frequency values of molecules in the optical telecommunications region, already documented in the list of standard frequencies, have been determined by femtosecond comb-based frequency measurements; 
* frequencies of molecules in the optical telecommunications region have been determined by femtosecond comb-based frequency measurements for the first time; 
* frequencies of certain iodine gas-cell absorptions close to the stem:[532 text( ) nm] optical frequency standard have been determined by femtosecond comb-based frequency measurements for the first time; 

*proposes* that the list of standard frequencies be revised to include the following:

* an updated list of frequency values for the stem:[text()^12C_2H_2 (nu1 + nu3)] band at stem:[1.54 text( ) mum];
* the addition of frequency values for the stem:[text()^12C_2HD (2nu_1)] band at stem:[1.54 text( ) mum];
* the addition of frequency values for the hyperfine components of the stem:[P(142) 37-0, R(121) 35-0] and stem:[R(85) 33-0] iodine transitions at stem:[532 text( ) nm].