=== CIPM, 2009

==== Updates to the list of standard frequencies (PV, 77, 235)

[align=center]
*Recommendation 2*

The International Committee for Weights and Measures (CIPM),

*considering* that

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established; 
* the CCL-CCTF Frequency Standards Working Group (FSWG) has reviewed several promising candidates for inclusion in the list;

*recommends*

that the following transition frequencies shall be included or updated in the list of recommended standard frequencies:

* the unperturbed optical transition stem:[5s^2 text()^1S_0 – 5s 5p text()^3P_0] of the stem:[text()^(87)Sr] neutral atom with a frequency of stem:[f = 429 228 004 229 873.7 text( ) Hz] and a relative standard uncertainty of stem:[1 times 10^(−15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second);
* the unperturbed optical transition stem:[5s^2 text()^1S_0 – 5s 5p text()^3P_0] of the stem:[text()^(88)Sr] neutral atom with a frequency of stem:[f = 429 228 066 418 012 text( ) Hz] and a relative standard uncertainty of stem:[1 times 10^(−14)];
* the unperturbed optical transition stem:[4s text()^2 S_(1text(/)2) – 3d text()^2D_(5text(/)2)] of the stem:[text()^(40)Ca^+] ion with a frequency of stem:[f = 411 042 129 776 393 text( ) Hz] and a relative standard uncertainty of stem:[4 times 10^(−14)];
* the unperturbed optical transition stem:[text()^2 S_(1text(/)2) (F = 0) – text()^2 F_(7text(/)2) (F = 3, m_F = 0)] of the stem:[text()^(171)Yb^+] ion with a frequency of stem:[f = 642 121 496 772 657 text( ) Hz] and a relative standard uncertainty of stem:[6 times 10^(−14)]; 
* the unperturbed optical transition stem:[6s^2 text()^1S_0 (F = 1text(/)2) – 6s 6p text()^3 P_0 (F = 1text(/)2)] of the stem:[text()^(171)Yb] neutral atom with a frequency of stem:[f = 518 295 836 590 864 text( ) Hz] and a relative standard uncertainty of stem:[1.6 times 10^(−13)].