=== CIPM, 2015

==== Updates to the list of standard frequencies (PV, 83, 207)

[align=center]
*Recommendation 2*

The International Committee for Weights and Measures (CIPM),

*considering*

* a common list of "Recommended values of standard frequencies for applications including the practical realization of the metre and secondary representations of the second" has been established, 
* the CCL-CCTF Frequency Standards Working Group (WGFS) has reviewed several candidates for updating the list,

*recommends*

that the following transition frequencies shall be updated in the list of recommended values of standard frequencies:

* the unperturbed optical transition stem:[6s^2 text()^1S_0 – 6s6p text()^3P_0] of the stem:[text()^(199)Hg] neutral atom with a frequency of stem:[f_(199Hg) = 1 128 575 290 808 154.8 text( ) Hz] and an estimated relative standard uncertainty of stem:[6 times 10^(−16)]; 
* the unperturbed optical transition stem:[6s text()^2S_(1text(/)2) – 4f^(13) 6s^2 text()^2F_(7text(/)2)] of the stem:[text()^(171)Yb^+] ion with a frequency of stem:[f_(171Yb+) (octupole) = 642 121 496 772 645.0 text( ) Hz] and an estimated relative standard uncertainty of stem:[6 times 10^(−16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed optical transition stem:[6s text()^2S_(1text(/)2) (F = 0, m_F = 0) – 5d text()^2D_(3text(/)2) (F = 2, m_F = 0)] of the stem:[text()^(171)Yb^+] ion with a frequency of stem:[f_(171Yb+) (quadrupole) = 688 358 979 309 308.3 text( ) Hz] and an estimated relative standard uncertainty of stem:[6 times 10^(−16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed optical transition stem:[5s text()^2S_(1text(/)2) – 4d text()^2D_(5text(/)2)] of the stem:[text()^(88)Sr^+] ion with a frequency of stem:[f_(88Sr+) = 444 779 044 095 486.6 text( ) Hz] and an estimated relative standard uncertainty of stem:[1.6 times 10^(−15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed optical transition stem:[4s text()^2S_(1text(/)2) – 3d text()^2D_(5text(/)2)] of the stem:[text()^(40)Ca^\+] ion with a frequency of stem:[f_(40Ca^+) = 411 042 129 776 398.4 text( ) Hz] and an estimated relative standard uncertainty of stem:[1.2 times 10^(−14)];
* the unperturbed optical transition stem:[1S – 2S] of the stem:[1H] neutral atom with a frequency of stem:[f_(1H) = 1 233 030 706 593 514 text( ) Hz] and an estimated relative standard uncertainty of stem:[9 times 10^(−15)]. +
NOTE: This frequency corresponds to half of the energy difference between the stem:[1S] and stem:[2S] states;
* the unperturbed optical transition stem:[5s^2 text()^1S_0 – 5s5p text()^3P_0] of the stem:[text()^(87)Sr] neutral atom with a frequency of stem:[f_(87Sr) = 429 228 004 229 873.2 text( ) Hz] and an estimated relative standard uncertainty of stem:[5 times 10^(−16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed optical transition stem:[6s^2 text()^1S_0 – 6s6p text()^3P_0] of the stem:[text()^(171)Yb] neutral atom with a frequency of stem:[f_(171Yb) = 518 295 836 590 864.0 text( ) Hz] and an estimated relative standard uncertainty of stem:[2 times 10^(−15)] (this radiation is already endorsed by the CIPM as a secondary representation of the second); 
* the unperturbed ground-state hyperfine transition of stem:[text()^(87)Rb] with a frequency of stem:[f_(87Rb) = 6 834 682 610.904 310 text( ) Hz] and an estimated relative standard uncertainty of stem:[7 times 10^(−16)] (this radiation is already endorsed by the CIPM as a secondary representation of the second). 

and also *recommends*

that the following transition frequencies shall be included in the list of recommended values of standard frequencies:

* Absorbing molecule stem:[text()^(127)I_2], saturated absorption stem:[a_1] component, stem:[R(36) 32-0] transition.
+
--
[align=left]
The values stem:[f_(a1) = 564 074 632.42 text( ) MHz] +
stem:[lambda_(a1) = 531 476 582.65 text( ) fm]

with an estimated relative standard uncertainty of stem:[1 times 10^(−10)] apply to the radiation of a frequency-doubled diode DFB laser, stabilized with an iodine cell external to the laser.
--
* Absorbing atom stem:[text()^(87)Rb 5S_(1text(/)2) - 5P_(3text(/)2)] crossover between the stem:[d] and stem:[f] hyperfine components of the saturated absorption at stem:[780 text( ) nm] (D2 transition)
+
--
[align=left]
The values stem:[f_(dtext(/)f text(crossover)) = 384 227 981.9 text( ) MHz] +
stem:[lambda_(dtext(/)f text(crossover)) = 780 246 291.6 text( ) fm]

with an estimated relative standard uncertainty of stem:[5 times 10^(−10)] apply to the radiation of a tunable External Cavity Diode Laser, stabilized to the stem:[dtext(/)f] crossover in a rubidium cell external to the laser.

NOTE: The value of the standard uncertainty is assumed to correspond to a confidence level of 68 %. However, given the limited availability of data there is a possibility that in hindsight this might not prove to be exact
--

NOTE: Further updates are available on the BIPM website.